### ISSUE TITLE
Remove "deleted" status record in OAI record.

### ISSUE THREAD

**Issue by yh-repo** [IQSS/dataverse#10040]
May I know if there is a way to remove the OAI records of "deleted" status or remove all OAI records and re-export?
I faced an issue with the OAI record. The OAI record can be found at:
https://researchdata.um.edu.my/oai?verb=ListRecords&metadataPrefix=oai_dc

From the OAI list, there is a total of 55 OAI records. However, we have 28 registered datasets only. This is cause by the migration of dummy DOIs.

**Comment by landreev** [comment]
Hello, 
I just realized looking at your question that there is no supported way to do this for the main set, through either the UI or the API. 
For any _named_, created set you could simply delete the set (either in the UI Dashboard, or via the api), and then re-create the set under the same name/same configuration, and all the "deleted" records will disappear in the process. For the main/default, "all published datasets" set we don't provide a way to delete all the records in it...

It's still very easy to delete all these records, but you'll have to run a database query: 
```
DELETE FROM oairecord WHERE setname='' AND removed IS TRUE;
```

... but we should implement a way to re-export a set from scratch from the application as well.

**Comment by yh-repo** [comment]
Hi, thank you for the solution. I had actually tried to delete the entry directly with database query during this past week in testing environment. However, may I know if there is any consequences with direct database query in this case? I had have experienced some other applications suffer from database corruption with direct database query. 

It would be great if there is an API that can re-export the default oaiset from scratch in this case. But, from my understanding on OAI-PMH2 (p.s: I might be wrong), the "deleted" status record(s) would happen if the dataset go through deaccession or so. When other harvesting client(s) receive the OAI set record, the harvesting client(s) would remove the link and metadata of the related dataset(s). In this case, if the "deleted" record is removed instead of staying on "deleted", would this affect the result on the harvesting client(s)? Once again, I might be misunderstanding regarding to OAI-PMH, correct me if so. Thank you very much for your response and solution.

**Comment by landreev** [comment]
Making direct changes in the database definitely is inherently dangerous. With this particular query, I felt comfortable suggesting it to you because I was confident that there are no dependencies on these entries anywhere else in the database, and that all these OAI records are essentially secondary (i.e., can be re-generated from the main dataset entries, if needed). But this is an exception, our normal advise would be not to run direct queries like that unless absolutely necessary. And it is generally a good idea to have database backups just in case.

**Comment by landreev** [comment]
The purpose of these "deleted" records is to communicate to harvesting clients who may have already harvested your holdings to drop the records that you no longer serve. Is this actually a case with your OAI records - are there any other archives who have been harvesting from you, who may still have those records, that you no longer host? (probably not - because you've been advertising them as "deleted" for some time now, presumably - ?)

If you look at the "2.5.1 Deleted records" section of the OAI documentation (http://www.openarchives.org/OAI/openarchivesprotocol.html), it explains different levels of handling deleted records that an OAI archive must advertise to clients. Note that the Dataverse OAI implementation advertises itself as `<deletedRecord>transient</deletedRecord>` - which really means "we are going to make an effort to let other clients know about records we stop serving, but we don't promise to keep them forever". So it should generally be ok to remove them. 

Generally, if anyone harvesting from you has any reasons to think that their harvested records are stale or out of sync with your archive (or if you believe that anything you harvest from other places is stale), it should be safe to simply delete them all and re-harvest everything from scratch. And then it doesn't matter if any records that the remote archive no longer serves are still there marked as "deleted" or not.

**Comment by landreev** [comment]
And yes, we will use this github issue to add an api for re-building the main set from scratch.

**Comment by yh-repo** [comment]
We do advertised the OAI record for quite some time. I will proceed with the solution to fix the OAI record. Thank you very much for the solution and the detailed explanation.

**Comment by pdurbin** [comment]
Yes, thanks, @landreev!

Should this be documented at https://guides.dataverse.org/en/6.0/admin/harvestserver.html ?

@yh-repo are you interested in making a pull request? 😄

**Comment by landreev** [comment]
@pdurbin I was thinking of opening a new issue for adding an api endpoint for rebuilding an oai set from scratch (similar to the reExportAll etc. calls), and then closing this issue. It should be fairly easy to add. And then we could document the new api call, instead of documenting the direct database update workaround. 
It should also be worth pointing out that having these legacy records in the database shouldn't really cause any problems, neither on the server nor on the clients side.

**Comment by pdurbin** [comment]
@landreev great plan 🎉

**Comment by yh-repo** [comment]
Hi @pdurbin, I have not code with Java language in a long time. I'm afraid that I could not provide productive help with the pull request.

**Comment by pdurbin** [comment]
@yh-repo no worries. It sounds like we'll create a new issue, etc. Thanks.

**Comment by landreev** [comment]
Closing this, in favor of the newly-opened #10110.
