### ISSUE TITLE
Use try-with-resources in DatasetUtil.java to close "src = new FileInputStream(tmpFile).getChannel();" and also "dest = new FileOutputStream(tmpFile).getChannel();"  in method persistDatasetLogoToStorageAndCreateThumbnails(...)

### ISSUE THREAD

**Issue by rtreacy** [IQSS/dataverse#10053]

**Comment by qqmyers** [comment]
Note that in #9669, I switched from using channels to streams because the channel.transferFrom method is not guaranteed to transfer all bytes (and can transfer 0 bytes) whereas the InputStream.transferTo method blocks until all bytes are transferred. I don't know if that's relevant here too (i.e. if this code also has that potential bug).

**Comment by bencomp** [comment]
I was going to create a small separate PR for this, but I created a merge conflict and it was then easier to keep the fix as part of #10077. Reviews are welcome :)
