### ISSUE TITLE
Tutorial for running containers as a demo or for evaluation

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#10238]
Draft: https://docs.google.com/document/d/16rmOV2kJSVEKj3fCnoV_YbWr-i1AZGAAuwmle3sQD_A/edit?usp=sharing

---

Various notes:

Add under https://guides.dataverse.org/en/6.0/installation/prep.html#choose-your-own-installation-adventure ?
What do we call the page in the Container Guide?
Demo Usage? (to mirror Dev Usage)
creating metadata blocks
evaluation
demos
kicking the tires
try Dataverse
Make a five minute demo?
From dataverse.org, link to demo site
From demo site, link to Installation Guide

**Comment by johannes-darms** [comment]
@pdurbin As a prerequisite for evaluation or demo usage the latest releases should be tagged and available on dockerhub. I suggest something like `beta-6.1`,`6.1-beta` as a tag, so that everyone knows those images or not (yet) official but can be used for evaluation and testing environment. 
The Evaluation should be as simple as possible and IMHO should be done one some released stable version and not on a violate tag like `unstable` or `alpha`.

**Comment by pdurbin** [comment]
@johannes-darms good idea. As discussed in the [container meeting](https://harvard.zoom.us/rec/share/rDo_V6heO9vo6UDIVhm0mnnsdTDXqA4lNX72lCjhGWrmOEpZttM13CsBceAFXkvr.SgokYNw-AoOACtSm) earlier today, it's out of scope for this little "7 hours" issue, but something we can certain consider in the future (please feel free to create an issue)!

**Comment by pdurbin** [comment]
I created a draft PR, stubbing out some new pages:

- #10273

I'll put a preview link there. Please leave comments in the PR or feel free to add reviews.
