### ISSUE TITLE
Metadata Blocks: Non citation blocks field required/optional selection is reset after hiding/showing another field in a block

### ISSUE THREAD

**Issue by esotiri** [IQSS/dataverse#1030]
Edit dataverse> general information  > ie: Social Science and Humanities Metadata block > make Universe  required > click checkbox to hide or show other fields > resets the requested field.

**Comment by eaquigley** [comment]
I tried this on demo.dataverse and wasn't able to reproduce. Passing to @kcondon to see if it can be closed.

**Comment by kcondon** [comment]
@eaquigley 
This still happens if you do not click done after making choices as indicated in Stephen's comment.
So:
1. make Universe required, uncheck Data Collector, do not click done, click save changes. Data Collector is correctly marked as hidden but Universe is back to optional.
2. repeat test 1 but click done then save, works. 
3. after running test 2, edit again and this time make Time Method required in addition to previously required Universe, uncheck Collector Training, do not click done, click save changes. The 2 hidden fields (Data Collector, Collector Training) are still hidden but the 2 required fields (Universe, Time Method) are now both optional.

Weird, man.
