### ISSUE TITLE
AdminIT.testBannerMessages failing on Rocky 9

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#10312]
This test has failed consistently enough on Rocky 9 that I feel it's worth reporting:

`"[ERROR]   AdminIT.testBannerMessages:863 expected: <OK> but was: <ERROR>"`

Unfortunately I don't find anything more helpful in the stack of server.logs generated during end-to-end tests.

Related to #10271

**Comment by donsizemore** [comment]
@jp-tosca as of May 13 2024 on Rocky 9 this test still fails:
`[ERROR]   AdminIT.testBannerMessages:864 expected: <OK> but was: <ERROR>`

**Comment by jp-tosca** [comment]
FTR: After some testing it seems that there is something wrong with the endpoint in Rocky IX 🥊.

Thanks @donsizemore for all the help with testing this. 

After doing some changes on the test and eliminating points of failure we concluded that in this environment a valid call is producing a success output with an unexpected result.

A simple call like this:

```
curl -H "Content-type:application/json" -X POST "http://localhost:8080/api/admin/bannerMessage" --data '{"dismissibleByUser":"false","messageTexts":[{"lang":"en","message":"Banner Message For Deletion"},{"lang":"fr","message":"Banner Message For Deletion"}]}'
```

Will generate in Rocky IX 🥊  the following output:

`
{"status":"OK","data":{"message":"Banner Message added successfully."}}
`

But when checking with:

```
$ curl http://localhost:8080/api/admin/bannerMessage
```

We get something like this : `{"status":"OK","data":[{"id":0,"displayValue":""}]}`
When this is expected: ` {"status":"OK","data":[{"id":0,"displayValue":"Banner Message For Deletion"}]}`


So far it doesn't seem to be an exception or anything on the back but I will post as soon as I find more details

**Comment by jp-tosca** [comment]
This test is failing because:

https://github.com/IQSS/dataverse/blob/da3dd95184846da6bd04fe37526c3785ab6e8ddc/src/main/java/edu/harvard/iq/dataverse/BannerMessage.java#L51

Use the locale to define what message to return, rocky is returning "c".

On the test, this line will call the method `UtilIT.getBannerMessageIdFromResponse`: 

https://github.com/IQSS/dataverse/blob/da3dd95184846da6bd04fe37526c3785ab6e8ddc/src/test/java/edu/harvard/iq/dataverse/api/AdminIT.java#L856

Which is searching explicitly from this string `Banner Message For Deletion`: 

https://github.com/IQSS/dataverse/blob/da3dd95184846da6bd04fe37526c3785ab6e8ddc/src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java#L3382

And the value is empty

**Comment by donsizemore** [comment]
This doesn't require code changes within Dataverse -- this problem is specific to the Rocky 9 AWS AMI. Closing in favor of https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/issues/352
