### ISSUE TITLE
Computational Workflow metadata block bug: links don't link

### ISSUE THREAD

**Issue by kmika11** [IQSS/dataverse#10339]
In the Computational Workflow metadata block, the field for "External Code Repository URL" requires a valid URL, but then does not present a link in the UI.  

**What steps does it take to reproduce the issue?**

* When does this issue occur?
When adding a URL to the "External Code Repository URL" field in the Computational Workflow metadata block. 

* Which page(s) does it occurs on?
The dataset page, under the Metadata tab. 

* What happens?
Plain text is displayed.

* To whom does it occur (all users, curators, superusers)?
All users. 

* What did you expect to happen?
A clickable link to be displayed that takes the user to the URL location. 

**Which version of Dataverse are you using?**
6.1

**Any related open or closed issues to this bug report?**
No

**Screenshots:**
<img width="1173" alt="Screenshot 2024-02-22 at 4 45 40 PM" src="https://github.com/IQSS/dataverse/assets/23460791/4a246b53-b54b-4d24-b2cd-4e7959bd3f58">

--

<img width="1062" alt="Screenshot 2024-02-22 at 4 46 29 PM" src="https://github.com/IQSS/dataverse/assets/23460791/496bcfb7-df8f-450e-9cad-888a58a31fdc">

**Comment by cmbz** [comment]
Related to: https://github.com/IQSS/dataverse-pm/issues/146

**Comment by jggautier** [comment]
In the metadatablock's TSV ([see copy on Google Sheets](https://docs.google.com/spreadsheets/d/13HP-jI_cwLDHBetn9UKTREPJ_F4iHdAvhjmlvmYdSSw)), the field's "fieldType" is url, so it accepts only that. But its "displayFormat" is empty, where we would normally have something like `<a href="#VALUE" target="_blank">#VALUE</a>`, so that the URL is displayed as a link.

So I think we'd want to add `<a href="#VALUE" target="_blank">#VALUE</a>` for its "displayFormat". Then follow [the steps for reloading the metadata block](https://guides.dataverse.org/en/latest/admin/metadatacustomization.html#reloading-a-metadata-block).

**Comment by pdurbin** [comment]
@jggautier yep, sounds right. We'll also want to update the version in git, of course: https://github.com/IQSS/dataverse/blob/develop/scripts/api/data/metadatablocks/computational_workflow.tsv

**Comment by jggautier** [comment]
Ah, yeah updating that TSV file, not the Google Sheets copy, is what I meant. Once that TSV file is updated, I could update the Google Sheets copy.

**Comment by pdurbin** [comment]
@cmbz FYI, @kmika11 made a pull request...

- #10441 

... so I advanced it to "ready for review" and removed this issue (10339) from the board, like we usually do. It was in "this sprint".

I'm not sure if Katie has permission to do this on her own but we could obviously adjust perms for the future.

Thanks for the pull request, Katie!
