### ISSUE TITLE
Datasets created Via Template are not indexed

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#10442]
**What steps does it take to reproduce the issue?**
Create any dataset via the UI and a template. The draft is created successfully but it is not indexed

* When does this issue occur? On dataset create

* Which page(s) does it occurs on? Create Dataset

* What happens? created draft does not appear on home page

* To whom does it occur (all users, curators, superusers)? anyone who can create a dataset

* What did you expect to happen? I expect the draft to be indexed/findable

**Which version of Dataverse are you using?** current dev

**Any related open or closed issues to this bug report?** unknown 

**Screenshots:**

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*

**Comment by scolapasta** [comment]
So I was able to do some further investigation on this last week - in the end, I don't think the issue would affect any installation that actually used the new code AND updated their tsv files. However the PR above is just a simple null check and a reasonable defensive measure for cases where a tsv file is not appropriately updated, so we went ahead and merged the change.

More details:

There were some datasetfield templates that were erroneously defined on the tsv as allowControlledVocabulary, but had no controlled vocabualry values defined. The code previously treated them as text fields because:

```    public boolean isControlledVocabulary() {
        return controlledVocabularyValues != null && !controlledVocabularyValues.isEmpty();
```

That code was changed to:
```    public boolean isControlledVocabulary() {
        return allowControlledVocabulary;
```

and the tsv files allowControlledVocabulary for these fields was changed from true to false.

So previous templates using these fields treated then as text and created null datasetFieldValues (whether we really want these null values is out of scope as this happens for any text fields currently). 
        
So if you use the new code and don't update the tsv files, then allowControlledVocabulary is true, and then it looks at this value and gets a null that it wasn't expected. The fix now checks for that null. In practice these fields, when properly updated, would return allowControlledVocabulary as false, and not go in this part of the code.
