### ISSUE TITLE
When upgrading to 6.2, installations with multiple languages see the error "staticSearchFields.license key is missing"

### ISSUE THREAD

**Issue by sergejzr** [IQSS/dataverse#10510]
Dear Dataverse Developers,

just to inform you that in existing installation after an upgrade top 6.2, the system stops working and throws exception
"staticSearchFields.license key is missing"

I reinstalled staticSearchFields.properties from the current version and it worked.

It might be worth adding to release notes, in case properties files are changed.

Even better would be an exception handling and informing the admin that some keys are missing instead of killing the whole system.

Best regards
Sergej

**Comment by pdurbin** [comment]
@sergejzr thanks for opening this issue. It looks like the following pull request...

- #10204

... added lines to two different properties files, actually:

src/main/java/propertyFiles/License.properties got license.custom_terms.name=Custom Terms

src/main/java/propertyFiles/staticSearchFields.properties got staticSearchFields.license=License

So you might want to grab the other file as well.

Killing the whole system sounds pretty terrible! Can you please advise on what steps we can take to reproduce this? We're you creating a dataset? Trying to publish it? Thanks!

**Comment by sergejzr** [comment]
Unfortunately, I could not reproduce this on the both of my other test servers. There, the update run smoothly. 

However, the issue with missing keys did occur couple of times in the past. I will try to make a test case and record more in case it occurs in the future.

**Comment by vbonamy** [comment]
Hello, 

I encountered the same error "staticSearchFields.license key is missing" when upgrading from 6.1 to 6.2. 

The issue was that I hadn't updated the /home/dataverse/langBundles directory; that's where Dataverse was trying to retrieve staticSearchFields.license from the staticSearchFields.properties file or one of its i18n translations (rather than from the staticSearchFields.properties file provided in the classpath from the WAR).

I believe it would be helpful to mention in the [Upgrade Instructions](https://github.com/IQSS/dataverse/releases/tag/v6.2#-upgrade-instructions) to remember to update translations via [dataverse-language-packs](https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs) accordingly.

Thank you!

**Comment by scolapasta** [comment]
Sizing as update the release notes to go get language bundles

**Comment by pdurbin** [comment]
@sergejzr @vbonamy we added a note in this PR:

- #10560

@jp-tosca updated the live release notes as well: https://github.com/IQSS/dataverse/releases/tag/v6.2
