### ISSUE TITLE
Improving Saved Search feature

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#10628]
From https://github.com/IQSS/dataverse.harvard.edu/issues/277#issuecomment-2163891748:

> After creating a "Saved Search", links may not be added to the collection immediately. This needs to be documented in the Guide or fixed, or added to the success message that there is a delay between the action and the results. Success message may say "this action takes 24 hours" ?

**Comment by pdurbin** [comment]
Whoops, I see that we removed this from the guides...

"Of particular interest should be the "makelinks" endpoint because it needs to be called periodically (via cron or similar) to find new dataverses and datasets that match the saved search and then link the search results to the dataverse in which the saved search is defined"

... when we switched from cron to a timer in this PR:

- #7152

We can easily add equivalent language back in.
