### ISSUE TITLE
Importing datasets with unmanaged (Permalink) PIDs

### ISSUE THREAD

**Issue by vera** [IQSS/dataverse#10753]
**What steps does it take to reproduce the issue?**

1. Import dataset with pre-existing PID (that is not managed by any configured PID provider) using API, e.g. `/api/dataverses/$dataverseAlias/datasets/:import?pid=perma:https://example.com/mypermalink123`

3. Receive error response: status code 400

```
{
    "status": "ERROR",
    "message": "Cannot validate PID due to an error: null"
}
```

I think this unexpected error message is caused by a bug.

I have found that the error originates here:

https://github.com/IQSS/dataverse/blob/ac32b00ee1f2431807a01ae997a4d5ddc9a96761/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/ImportDatasetCommand.java#L65-L99

The GET request for the Permalink always results in a 404, since the Permalink is not requested directly, but via Dataverse, e.g. `http://localhost:8080/citation?persistentId=perma:https://example.com/mypermalink123`. If I understand correctly, at this point in the import process, this URL cannot lead anywhere since the dataset is neither imported nor published yet.

Thus, the check for `alreadyRegistered` happens next.

All of the unmanaged PID providers do not implement `alreadyRegistered`. They throw a `NotImplementedException` (with an error message of `null`, which causes the output `"Cannot validate PID due to an error: null"` above).

(Side note, this also happens when importing a dataset with an unmanaged DOI that resolves to 404, e.g. `/api/dataverses/$dataverseAlias/datasets/:import?pid=doi:10.5073/FK2/ABCD11`)

To fix this, I think the following needs to be done:

- [ ] Check the actual permalink (in the example above: `https://example.com/mypermalink123`) instead of the link via Dataverse (`http://localhost:8080/citation?persistentId=perma:https://example.com/mypermalink123`)
- [ ] In case of a 404, handle it appropriately. I'm not sure what should be done here, should the dataset be imported or not? If not, an understandable error message should be returned

What do you think?

I would be happy to submit a PR for this.

**Comment by qqmyers** [comment]
In general, I think we want it to be an error to import a Dataset that can't be managed - Dataverse has no way to update the PID with the appropriate landing page URL (for DOIs/ things with a resolver service), users can't edit/republish (permalinks as well as DOI, Handle), etc. (The ability to have an alternate PID is meant to address at least some use cases where you still want an old PID, not managable by Dataverse, associated with the dataset.)

I'm not sure I understand your overall use case, but before making a change to the unmanaged provider - can your case be covered by having a managed Perma provider? Possibly using a [base-url](https://guides.dataverse.org/en/latest/installation/config.html#dataverse-pid-permalink-base-url)? If there's an issue with migrating a dataset with a manageable permalink, it would definitely be a bug and a PR would be welcome. 

And. at a minimum, having a better error message for the unmanaged case would be a good thing. A 400 might still be appropriate if Dataverse can't manage the PID, but a message other than null would help in figuring out how to proceed (change the PID or get the admins to add a provider that can manage it).

**Comment by vera** [comment]
Hmm. From the documentation, I understood that importing datasets with pre-existing unmanaged PIDs was supported/intended usage:

> A Dataverse installation can import datasets with a valid PID that uses a different protocol or authority than said server is configured for. However, the server will not update the PID metadata on subsequent update and publish actions.

https://guides.dataverse.org/en/latest/api/native-api.html#import-a-dataset-into-a-dataverse-collection

So that's what I tried to do and why I thought the error was unexpected behavior. Is it not intended?

**Comment by qqmyers** [comment]
Good question! I see that text was added ~6 years ago. When I did the work to support multiple PID providers, I don't think I was aware of it and did not try to maintain that functionality (as one of the reasons for multiple PID providers was to let you migrate PIDs and have them be manageable) and I don't think this case was tested at all in QA.

I guess I would say that, if your use case can be handled with a managed perma provider, that would be the simpler route (and we could look at updating the docs and error messages, and fixing any bugs or extensions needed related to base-url etc.).

If you are relying on the unmanaged case working, or others know a reason we need to keep it working, I expect it could be made to work, starting with some fix like the one you're suggesting. We might want a design discussion first to understand the use cases - it seems problematic to allow changes that would affect any PID metadata if you can't update the PID, so should an unmanaged PID turn off editing? Also, I wouldn't be surprised if there are other issues given my changes to support multiple PID providers and many other changes over the last 6 years where I doubt this case was tested.

**Comment by vera** [comment]
I see! I'm going to experiment with using managed permalink providers. Maybe that will solve my issue.

I feel like I don't quite understand the difference between a managed and an unmanaged Permalink provider though. In both cases, the PID metadata isn't updated anywhere external like it would be with e.g. DOIs registered at DataCite, right?

**Comment by johannes-darms** [comment]
Our use case is fairly straightforward. We need to integrate metadata from records published in other repositories that do not provide an OAI-PMH API. So we need to import the metadata and make it publicly visible without creating another identifier. The dataset should not be modified within the dataverse instance, but will be periodically updated by an external process (to keep the data in sync). 

However, the dataset does not have a DOI or handle, but uses some kind of permalink. As an example, we can take the clinical trials platform `https://clinicaltrials.gov`. Here, each record has a unique identifier that is used like a DOI, e.g. `NCT04345510`, and can be resolved via a permalink `https://clinicaltrials.gov/study/NCT04345510`. 

>We might want a design discussion first to understand the use cases - it seems problematic to allow changes that would affect any PID metadata if you can't update the PID, so should an unmanaged PID turn off editing? 

Yes, I think these should be read-only. Maybe we can add a property that decides whether the imported dataset should be managed by dataverse (i.e. allow edits and publish versions, which requires minting PIDs) or just unmanaged (similar to harvest datasets, no changes possible). 

>Also, I wouldn't be surprised if there are other issues given my changes to support multiple PID providers and many other changes over the last 6 years where I doubt this case was tested.

There are several (including obsolete?) [1...6] ways to add or import dataset metadata into a dataverse instance. Shall we start a document explaining the options and their benefits and eventually try to reduce duplicate or overlapping options including duplicate code sections?  

[0]https://guides.dataverse.org/en/latest/api/native-api.html#create-a-dataset-in-a-dataverse-collection (default create API)
[1] https://guides.dataverse.org/en/latest/api/native-api.html#import-a-dataset-into-a-dataverse-collection (outdated?)
[2] https://guides.dataverse.org/en/latest/developers/dataset-migration-api.html 
[3] https://github.com/IQSS/dataverse/tree/develop/src/main/java/edu/harvard/iq/dataverse/api/imports (batch import undocumented)
[4] https://guides.dataverse.org/en/latest/developers/dataset-semantic-metadata-api.html 
[5] https://guides.dataverse.org/en/latest/api/sword.html (SWORD complaint API)
[6] https://guides.dataverse.org/en/latest/admin/harvestclients.html (OAI-PMH client)

**Comment by qqmyers** [comment]
> , but will be periodically updated by an external process (to keep the data in sync).
This sounds like editing and managing. You're saying that these entries will be changed over time - by some process using the API to edit the dataset? 

A managed PID Provider still sounds like a solution to me. The one thing I could see changing would be to add a flag to allow you to force canCreatePidsLike to return false. That would stop the Provider from ever creating new PIDs, essentially only allowing you to import existing PIDs. (Nominally if you don't use file PIDs and don't assign this provider for use in a collection you'd never mint PIDs anyway, but such a flag could avoid errors.)

Or is this really like Harvesting in that there shouldn't be a local dataset/file pages, just an entry in search that redirects you to the original when you click. If so, perhaps some update to the harvesting mechanism or an OIA-PMH proxy might make sense.

To me the key problem with allowing unmanaged PIDs is that it is **any** PID - managed providers have an authority/shoulder scope (and separator and base-url for perma) that let you decide what can be added to a Dataverse. Unmanaged are wide open - really meant for alternate PIDs, etc. where that's what you want.

**Comment by johannes-darms** [comment]
> This sounds like editing and managing.  You're saying that these entries will be changed over time - by some process using the API to edit the dataset?

> Or is this really like Harvesting in that there shouldn't be a local dataset/file pages, just an entry in search that redirects you to the original when you click. If so, perhaps some update to the harvesting mechanism or an OIA-PMH proxy might make sense.

Yes and no. These resources change in the original repository, and we want our dataverse instance to have the latest published version. Theoretically, the OIA-PMH client does this. In principle, we could use an OIA-PMH proxy, but due to some other dependencies, the metadata integration is done as an offline batch process. One reason is that we need to harvest more metadata properties (custom metadata blocks) to improve search. After a short initial evaluation, it was estimated that an offline transformation and import is faster to implement (and sufficient for an MVP) than tweaking the harvester code (something we would like to work on if the MVP is successful and additional metadata harvesting is of interest to others).

> A managed PID Provider still sounds like a solution to me. The one thing I could see changing would be to add a flag to allow you to force canCreatePidsLike to return false. That would stop the Provider from ever creating new PIDs, essentially only allowing you to import existing PIDs. (Nominally if you don't use file PIDs and don't assign this provider for use in a collection you'd never mint PIDs anyway, but such a flag could avoid errors.)

Thanks for the explanation, it looks like we want a managed PIDprovder! I think we can get by without an explicit feature to disable minting, since the conditions listed apply to us. To me personally, it sounds a bit odd to configure a PID provider and disable the only function of it...

We should at least update the documentation with this information and update the code to provide a more meaningful error message. What do you think?

**Comment by qqmyers** [comment]
> Yes and no. These resources change in the original repository, and we want our dataverse instance to have the latest published version. Theoretically, the OIA-PMH client does this. In principle, we could use an OIA-PMH proxy, but due to some other dependencies, the metadata integration is done as an offline batch process. One reason is that we need to harvest more metadata properties (custom metadata blocks) to improve search. After a short initial evaluation, it was estimated that an offline transformation and import is faster to implement (and sufficient for an MVP) than tweaking the harvester code (something we would like to work on if the MVP is successful and additional metadata harvesting is of interest to others).

Makes sense. My question about using the API/editing is just that if the entry has to change, we don't currently have ways to block that in the UI and allow it in the API. I guess using the superuser destroy dataset and recreating it might work. In any case, this is moot if you can use a managed provider.

> Thanks for the explanation, it looks like we want a managed PIDprovder! I think we can get by without an explicit feature to disable minting, since the conditions listed apply to us. To me personally, it sounds a bit odd to configure a PID provider and disable the only function of it...

I guess that's true for a perma provider without any resolver service, where managing is a no-op, but the overall managed provider design is definitely supposed to allow importing things with existing PIDs and automating keeping the underlying services updated.

> We should at least update the documentation with this information and update the code to provide a more meaningful error message. What do you think?

Sounds great.

**Comment by johannes-darms** [comment]
> > Yes and no. These resources change in the original repository, and we want our dataverse instance to have the latest published version. Theoretically, the OIA-PMH client does this. In principle, we could use an OIA-PMH proxy, but due to some other dependencies, the metadata integration is done as an offline batch process. One reason is that we need to harvest more metadata properties (custom metadata blocks) to improve search. After a short initial evaluation, it was estimated that an offline transformation and import is faster to implement (and sufficient for an MVP) than tweaking the harvester code (something we would like to work on if the MVP is successful and additional metadata harvesting is of interest to others).

> Makes sense. My question about using the API/editing is just that if the entry has to change, we don't currently have ways to block that in the UI and allow it in the API. I guess using the superuser destroy dataset and recreating it might work. In any case, this is moot if you can use a managed provider.

Our approach is a separate collection where only the API client has edit privileges, and we keep the older version in the system even though we don't need them.
An option to make a dataset behave more like a harvest one would be nice. 


> I guess that's true for a perma provider without any resolver service, where managing is a no-op, but the overall managed provider design is definitely supposed to allow importing things with existing PIDs and automating keeping the underlying services updated.

I can't follow. What do you mean? I only see three different states of records related to PIDs: 
1) Default 
Initially created and managed by an instance. So new PIDs should be created and records updated as needed. So a classic managed PID provider.
2) Read-only  (Harvested or imported into an instance.)
The instance is not allowed to propagate changes to a PID provider. A managed provider with minting disabled would make sense here. On the other hand, can we - and do we want to - enumerate and configure the providers beforehand. I'm thinking of broken/incomplete harvesting because a single new PID doesn't match any configured PID provider. How is this currently handled in harvesting? We should aim for similar code paths/logic for harvest and import. 
3) In-migration (created elsewhere, but PID management is or will be transferred)
This is more of an intermediate state, e.g. the metadata has been (partially) migrated, but the files have not yet been copied. Therefore, no imprinting should take place until a release has taken place. On completion, the dataset is in the `default' state. I do not think this state really needs to be implemented in code. It is more or less the same as the two or three step process of the current migration code path [https://guides.dataverse.org/en/latest/developers/dataset-migration-api.html] ), and the user must ensure that PIDs are not updated prematurely.

**Comment by qqmyers** [comment]
> I can't follow. What do you mean? I only see three different states of records related to PIDs:

Trying to frame in your terms, I think I'm saying that normal managed PID providers can handle 1 and 3, i.e. they handle updating the PID service with the new metadata/landing page URL during migration (if you choose), and later, in response to the update-PID API or normally when versions are published. In use case 3, they don't mint anything/minting is not the only function for the provider.

**Comment by johannes-darms** [comment]
> > I can't follow. What do you mean? I only see three different states of records related to PIDs:
> 
> Trying to frame in your terms, I think I'm saying that normal managed PID providers can handle 1 and 3, i.e. they handle updating the PID service with the new metadata/landing page URL during migration (if you choose), and later, in response to the update-PID API or normally when versions are published. In use case 3, they don't mint anything/minting is not the only function for the provider.

Thank you. I expressed myself badly, I subsumed updating under the term embossing. Surely these providers offer CRUD functions for PIDs.


Regarding use case 2 (read-only PIDs). When are these read-only data records created? Am I right in assuming that they are created when importing and harvesting datasets? If so, do we want the same behaviour for harvested and imported datasets?  Because currently the resolvability of a PID is not checked for harvested datasets, but it is for imported datasets. More specifically only the import API, the batch import skips the validation by using the CreateNewDatasetCommand and CreateDatasetVersionCommand or CreateHarvestedDatasetCommand and not the ImportCommand.


I believe that we could combine both process flows, as harvesting and importing are more or less the same, with the only difference that one is controlled by dataverse and the other by an external process.

**Comment by qqmyers** [comment]
I'm not sure I understand what change(s) you're suggesting. Harvesting is logically different from importing (in Dataverse). A harvested dataset is added to the search index, but all references to the dataset or its files are redirected to source repository. Thus, there is no way to edit in Dataverse, no need to update the landing page URL of the DOI, etc. For importing/migrating, a real, editable dataset is created in Dataverse, and the expectation is that the PID landing page will change, PID metadata will be updated if it is edited in Dataverse, etc. For cataloging use cases, if harvesting isn't appropriate, I think we've suggested using the AlternativePersistentIdentifier to reference the original PID (e.g. a DOI) and create the dataset using a PermaLink (One could use other PID types, but the usual concern is that another DOI would split citations, etc.). That allows creating an editable dataset (so you can add metadata that is not in the original source), while avoiding creating a second DOI, or redirecting the DOI landing page to the Dataverse copy, etc. It explicitly avoids having two resources in the world that are claiming to be the 'real' item for a given PID. My guess is that, if we want to make changes, it is to better support this use case in some way, e.g. making it clearer that the Dataverse copy has more metadata but academic citations should still reference the original DOI/original resource, and/or making it clearer that the Dataverse dataset is logically "the same as" the remote resource in an export format that supports that concept.

This may be something where we should revive the 'Cataloging' working group and consider trying to write up a doc with possible design changes.

**Comment by johannes-darms** [comment]
Thanks for the detailed response. I'd like to add datasets to dataverse that behaves like the current implementation of harvested datasets, with the only difference being that the metadata is actively submitted to dataverse via a REST API call rather than retrieved via OAI-PMH. (Use case: There is no OAI-PMH interface and running an OAI-PMH proxy is out of the question, but the metadata should be included in dataverse). 

Maybe we can add a property that decides whether the imported dataset should be managed by dataverse (i.e. allow edits and publish versions, which requires minting PIDs) [current implementation] or just unmanaged (similar to harvest datasets, no changes possible) [new feature]. Looking into the two commands [CreateHarvestedDatasetCommand](https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateHarvestedDatasetCommand.java) and 
[ImportDatasetCommand](https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/ImportDatasetCommand.java ) there isn't much difference...
