### ISSUE TITLE
Installer: --pg_only mode not working, needed to support installs with remote dbs.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1097]
I tried running the install where the web server and database were on different boxes but the --pg_only mode needed to set up the db side no longer works, it just says: pg only!!

**Comment by pdurbin** [comment]
@landreev what's the status of this issue? We chatted about this a few days ago and I think you were saying that using a remote database works. Should this go to QA?

**Comment by landreev** [comment]
The installer should now be working with a remote PostgreSQL server address specified. 

There are 2 ways in which it can accomplish this: 
It will try to connect to the remote database, as the Postgres *admin user*, in order to create and set up the database. If this does not succeed (if the user doesn't know their Postgres admin password; if they don't want to allow remote admin access; etc.) the installer gives them an option to go to that remote host, run the installer there, locally, in the "postgres-only" mode, then come back and resume the installation. 

(a pull request is coming shortly for all these install issues).

**Comment by kcondon** [comment]
This works, closing.
