### ISSUE TITLE
URL: Pretty Faces URL with Dataverse Alias Bugs

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1111]
When you add/ display a dataverse on the featured dataverse area, the urls are the former, non pretty types.

**Comment by scolapasta** [comment]
@mheppler let's review this together.

**Comment by mheppler** [comment]
Ran a search, found 40 references to "dataverse.xhtml" that are still in the system. Spent 15 minutes trying to resolve a few of them relating to the dataverse_header, search-include and login pages, but didn't get anywhere.

**Comment by eaquigley** [comment]
@mheppler does this need to be passed to someone else?

**Comment by mheppler** [comment]
The following pages all reference "dataverse.xhtml", and will need to be individually review, so as to consistently use the Pretty Faces URLs for dataverses, across the entire site.

- [ ] AdvancedSearch.java
- [ ] DatasetPage.java
- [ ] DataverseHeaderFragment.java
- [ ] DataversePage.java
- [ ] LoginPage.java
- [ ] SearchIncludeFragment.java
- [ ] Shib.java
- [ ] BuiltinUserPage.java
- [ ] PasswordResetPage.java
- [ ] 404.xhtml
- [ ] web.xml
- [ ] datafilemap.xhtml
- [ ] dataset.xhtml
- [ ] dataverse.xhtml
- [ ] dataverse_header.xhtml
- [ ] dataverseuser.xhtml
- [ ] loginpage.xhtml
- [ ] passwordreset.xhtml
- [ ] widjets.js
- [ ] search-include-fragment.xhtml

**Comment by mheppler** [comment]
AdvancedSearch.java, dataset.xhtml, dataverse.xhtml, dataverseuser.xhtml, widgets.js, themeAndWidgetsFragment.xhtml -- were all easy changes from id to alias. The rest will require review with a developer.

I am editing this list to be two parts. The above pages are easy, these next pages are more complicated.

**Comment by mheppler** [comment]
Passing to Gustavo to see if he can fix the use of "dataverse.xhtml" on Shib.java.
````
private final String homepage = "/dataverse.xhtml";
````

**Comment by scolapasta** [comment]
I'm actually going to pass this to @pdurbin, so he can add it how he would prefer (I think the easiest is to just remove the use of homepage and add dataverse.xhtml?alias=XXX in the places it's used).

@pdurbin, can you adjust this? the old way "dataverse.xhtml" is not good enough because it does not go through pretty faces. We have another issue #1519 to track how to do this, but for 4.0 we're just changing all those links to include the alias in the query string for the root (which you can get with the DataverseServieBean.findRootDataverse() method). Let me know if you have any questions.

**Comment by pdurbin** [comment]
As of b6b73f3 Shib users are redirected to the "pretty" URL for the homepage (http://localhost:8080/dataverse/root). There are three possible ways to end up there:

- When you log in with an existing Shib account
- When you log in as part of creating a Shib acount
- When you log in as part of converting a Shib account (#796)

In looking at this @scolapasta and I noticed that Shib users do not benefit from the fancy redirectPage logic developed in #869 for builtin users. We'll decided to open a new ticket at #1551 so that Shibboleth users get feature parity for this feature. For now, Shib users always end up at the homepage, but now it's the "pretty" URL. Passing to QA.

**Comment by posixeleni** [comment]
@mheppler @scolapasta @pdurbin @kcondon 

Sorry to bug ya but I need someone to help me with this ticket.

I'm seeing pretty URLs when I go to a:
- Dataverse page: https://dvn-build.hmdc.harvard.edu/dataverse/sonia
- Advance Search: https://dvn-build.hmdc.harvard.edu/dataverse/sonia/search

But from this ticket I am unclear where else these should display in the UI and/or how they should look so I can complete my testing.
- Dataset page: https://dvn-build.hmdc.harvard.edu/dataset.xhtml?globalId=doi:10.5072/FK2/7W7U42&versionId=7 (is this what you expect to see?)
- Widget: Is this the expected URL?
![image](https://cloud.githubusercontent.com/assets/5013837/6757354/d225682a-cf06-11e4-9faa-bd75646a139a.png)

**Comment by posixeleni** [comment]
@kcondon showed me what I need to test for this.

**Comment by posixeleni** [comment]
I have tested different workflows indicated by @mheppler and @pdurbin (Shibb) above for getting to a Dataverse page. I'm seeing all pretty dataverse URLs. Including Widgets which takes you to a URL that looks like this: https://dvn-build.hmdc.harvard.edu/dataverse.xhtml?alias=sonia&q=Sonia

Closing.
