### ISSUE TITLE
Installer: Make complete and working installer for v4.0

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1119]
This is a placeholder ticket to make sure the installer we use accounts for all the config settings and results in a running system. We should review this ticket near the end of the release as a final check.
https://github.com/IQSS/dataverse/issues/new#

**Comment by pdurbin** [comment]
@kcondon what's your ruling on this issue. It has 4.0 in the title and obviously people are able to install 4.0 and later. Should we just close this? Should we define what else we want the installer to do? @landreev has mentioned that he's fine with someone rewriting the whole thing in whatever language rather than Perl and I'm mentioning this in my rewrite of the Installation Guide at #2884.

**Comment by kcondon** [comment]
OK, this fulfills the basics: you can install and it works. I think I was hoping for some other params to be set but we have documented them now and this can be an ongoing project. Closing.
