### ISSUE TITLE
Installer: Add solr server location to installer.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1167]
Phil has added a new settings option that allows pointing to a separate solr server on another box. This should be added to the install script.

The option is:
curl -X PUT -d localhost:8983 http://localhost:8080/api/s/settings/:SolrHostColonPort

**Comment by landreev** [comment]
The installer now asks for the remote SOLR service address in the configuration dialogue.
The user has an option to leave it set to the default value of "LOCAL". In which case no Dataverse setting option is created, and the application proceeds to assume that SOLR is running locally. 

The installer provides a brief paragraph of text explaining what this setting is about.

A documentation entry has been added to the installation guide, under "New in 4.3".

**Comment by pdurbin** [comment]
I just tested `vagrant up` on both develop (5535970) and 4.3-installer-improvements (a83066f) and I'm happy to report that it still works in both places (I mean that I can log in at <http://localhost:8888> when it's done). We **could** improve the Vagrant script at https://github.com/IQSS/dataverse/blob/4.3-installer-improvements/scripts/vagrant/install-dataverse.sh to have it explicitly say it's using the "LOCAL" option but since it's the default, it's fine as is. Some of this stuff will probably change anyway when we get around to looking at the #2985 pull request by @bionary.

**Comment by kcondon** [comment]
Tested with the default local option. Still need to test the remote/url option.

**Comment by kcondon** [comment]
remote option works, closing.
