### ISSUE TITLE
Custom Icons - Create Custom Vector Icons for Various Buttons/Links

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1178]
Create custom icons, where needed, for things like the Dataverse logo, datasets, data files, etc.

This application allows for the creation of Bootstrap icon, used via CSS.

http://fontcustom.com/

Upon further review, this ticket will be expanded to include all the custom icons needed across the app.

**Comment by eaquigley** [comment]
Assigning this to Beta 13 so you can check in with Dwayne about the status of these icons.

**Comment by landreev** [comment]
@mheppler , 
do you have a list somewhere, of what mime types correspond to which of the "Specific File Type" classes? I do remember we started working on that list.

**Comment by landreev** [comment]
Mike, 
I checked in some code that identifies a) whether a preview (thumbnail) is available and b) the file type class, and displays these *as text* in the search cards. (see attached). Have fun with it. 

The following classes are identified: 

audio
code
document
astro
image
network
geodata
tabular
video
other

Note that I replaced "fits" with "astro" and "shape" with "geodata" - because we'll likely be supporting other formats in the future. 
Let me know if these "type classes" are not identified to your liking. Like if a particular audio format is not shown as "audio", etc. 

![screen shot 2015-02-13 at 3 09 20 pm](https://cloud.githubusercontent.com/assets/737558/6194479/b9b1a356-b392-11e4-8de8-ec9f5d5a71bc.png)

**Comment by mheppler** [comment]
Made all the custom icons, as outlined above. Notes have been added for those that were not created. This might not be the easiest to test, due to not being able to display all of them currently.

To see the individual icons, I've included a preview:

![fontcustom-icons](https://cloud.githubusercontent.com/assets/687227/6237747/5b2d5ecc-b6c3-11e4-89fc-1dee91a1acd7.png)

**Comment by mheppler** [comment]
Applied some render logic to get the "Restricted with Access" icons to display on the dataset page.

**Comment by mheppler** [comment]
Creating new tickets for outstanding icon development issues:

-  Dataverse Search/Browse Card - File Permissions: Restricted File Icons #1457 
-  Dataverse Search/Browse Card - Linked Dataverse/Dataset/File: Linked Icon #1459

**Comment by kcondon** [comment]
Custom icons as mentioned above are present: dv, ds, file, access. Other icon issues will be verified in other tickets. Closing.

**Comment by pdurbin** [comment]
> Made all the custom icons, as outlined above.

@mheppler These are great! :)
