### ISSUE TITLE
Permissions: Add Info, Error, Success Messages

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1187]
Need to add in error and success messages for permissions. Related to #682

**Comment by kcondon** [comment]
One more message needs correcting:
Role description size is limited to 255 but currently throws only this error:
Validation Error – Required fields were missed or there was a validation error. Please scroll down to see details.

And there is nothing else

**Comment by scolapasta** [comment]
Role validation won't be done until after 4.0, as we are only allowing superusers to do it: #1384. Merged messaging info from there into #1135, so am checking box as complete for this issue (adding - deferred).

All's that's left are the asterisks. passing to @mheppler

**Comment by mheppler** [comment]
Added required asterisks to fields in the Assign Role popup and also changed the popup header to read "Assign Role". Cleaned up other UI issues including, opening Users/Groups panel on Manage Permissions if it's on a dataset, and the Permissions panel isn't displayed above it.

I did not get to the asterisks for Add New Role popup, because it appears there is no validation on the form. If I click "Save Changes", the popup closes. There are no validation errors, so I do not know which field labels need asterisks. Passing to @scolapasta to wire up. Code for the asterisks is simple to copy and paste from the Assign Role popup (role-assign.xhtml, Line 19) and add to Add New Role popup if needed.

````
<span class="glyphicon glyphicon-asterisk text-danger" title="#{bundle.requiredField}"/>
````

**Comment by scolapasta** [comment]
Yes, as stated above the add/edit role validation / messaging is defered to post 4.0 and tracked in issue #1135.

So passing to QA, to test the rest.

**Comment by kcondon** [comment]
Tested the available and working messages. Because Role validation is not in place, basic incomplete messages are not appearing.

**Comment by scolapasta** [comment]
I added role validation to #1135, can we close this one?

**Comment by kcondon** [comment]
Closing
