### ISSUE TITLE
Install: Add "open dv" as an option to install/ setup-all scripts

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1192]
This behavior may change but it is being recorded here to help with installation.
Now, by default, no user may add dataverses or datasets to the root dv, unless it is assigned directly or made an "open dv". Our root dataverse will be open so it may make sense to make it an option during install, documented in the guide, and possibly added to setup-all but commented out to facilitate dev configurations.

From Phil's post, this is the command:
curl -s -X POST -H 'Content-Type: application/x-www-form-urlencoded' "http://localhost:8080/api/roles/assignments?username=:AuthenticatedUsers&roleId=$DV_CONTRIBUTOR_ROLE&definitionPointId=$ROOT_DATAVERSE&key=$ADMINKEY"

**Comment by pdurbin** [comment]
Many of the API tests I've written as part of #2746 require the ability to create a user who can create a dataverse as a testing sandbox in which to create datasets. That's why in my phoenix scripts I call my "grant-authusers-add-on-root" script from https://github.com/IQSS/dataverse/blob/develop/scripts/deploy/phoenix.dataverse.org/post . Otherwise I wouldn't be able to run these tests. I didn't realize this is called an "open dv" but whatever. :)

**Comment by sbarbosadataverse** [comment]
Can close, hasn't been requested recently at all. Users can be directed to add this manually if needed. Can be done via the API.
