### ISSUE TITLE
Install: Add jvm option to use G1 garbage collector

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1202]
The G1 garbage collector is new and is the most efficient collector so we should be using it in production. It is enabled this way:

        <jvm-options>-XX:+UseG1GC</jvm-options>

More info on the collector:
http://www.oracle.com/technetwork/java/javase/tech/g1-intro-jsp-135488.html

**Comment by scolapasta** [comment]
@rtreacy do you know anything about this? Can we just add it? If so, let's have @landreev add it to the installer script (uness you want to go in directly and make that change)

**Comment by rtreacy** [comment]
I agree. Assigning to leonid to update the installer script. Additional details in this tutorial particularly at the end. However, I would start by just using the jvm-option that Kevin suggested, rather than messing with the many other options mentioned in the tutorial
.
http://www.oracle.com/technetwork/tutorials/tutorials-1876574.html
