### ISSUE TITLE
Widgets: New Features, Visualize + Analyze Contents of Files 

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1203]
F1000 Research would like us to be able to use the Dataverse widget feature to display the actual contents or preview of a file instead of just showing the Dataverse site within it. Example: if they had a tabular file or PDF deposited in Dataverse they'd like to have a widget where you can see the contents of the tabular file or PDF file itself. 

Figshare has a feature like this so I am including a link to their website but please let me know if you have any questions regarding this Feature Request. http://figshare.com/blog/Embeddable_figshare_content/87 F1000 research is using this widget from figshare for their journal articles and had asked if we offered this kind of visualization support: http://blog.f1000research.com/2012/07/10/new-figshare-widget-gives-previews-of-data-on-f1000-research/
They would also like the widget to be able to handle tabular data visualizations (TwoRavens) and Geospatial (WorldMap) visualizations.

This is something we had put into the Sloan proposal which we received funding for starting in January 2015 so we can start planning and scoping this out after 4.0

**Comment by posixeleni** [comment]
This can also be something we work with Gus on to provide visualizations for World Wide Telescope files that can have a widget inserted in a journal article.

**Comment by augustfly** [comment]
Yep, @posixeleni!

**Comment by posixeleni** [comment]
Received word from F1000 that these are the most common file types they would like to visualize in a Dataverse file visualization widget:

>The most common in no particular order are (those that we don’t have but are possible have a *):
 
>TSV; CSV; ODS; XML; XLSX; MPEG-4; MPEG-3*; FASTA; TIFF; PDF; TXT; GIS*; FCS (flow cytometry)*; .mat* would be great if possible, but probably has some proprietary issues.

**Comment by augustfly** [comment]
my random thoughts:

* .tex -- That is a good list, but if you're going to do XML/TXT then also include .TEX. 
* .ipynb -- 
* As for astronomy, I would recommend converting astronomy 1 or 2D "FITS" to 8 bit png and then display that instead of trying to do native FITS in a file viz widget. I guess you could push FITS to WWT, but boy that is a lot of wasted bits unless WWT preparses FITS files in dataverse.

**Comment by posixeleni** [comment]
Here's a mockup of how this data file widget might look:

![image](https://cloud.githubusercontent.com/assets/5013837/10791519/1c7ff0e6-7d5f-11e5-9a74-2a0129037f79.png)

**Comment by posixeleni** [comment]
changed the priority to high since this is a deliverable for a grant project

**Comment by sbarbosadataverse** [comment]
@posixeleni can we bring this up in girt please? We can't necessarily agree with this being a priority 2. Thanks

**Comment by pdurbin** [comment]
Anyone interested in this issue may want to participate in this Tuesday's community call because Scholars Portal will be giving a demo of their new "DDI Explorer" app. For details on how to call in, please see https://groups.google.com/d/msg/dataverse-community/Zpib-uCIG1g/Rg9tJGieBAAJ . DDI Explorer is only for tabular data, but I wonder if it could be made into a widget of some sort.

**Comment by raprasad** [comment]
basic tabular preview example using file id ```2966861```:

 - basic/basic table: https://services.dataverse.harvard.edu/miniverse/datafile/table-preview-html/2966861
 - json:   https://services.dataverse.harvard.edu/miniverse/datafile/table-preview-json/2966861
 

Add any id of a _published_ file to the url above

**Comment by pdurbin** [comment]
Related: Files: Quick Viewers for Common File Extensions #2214

**Comment by djbrooke** [comment]
I'm going to close this, as I believe that this would be handled by some mix of better previews (#3758) and file level external tools.
