### ISSUE TITLE
Code Cleanup: use bean validation for archive note/deaccession reason

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1219]
In setting of archive note, there is a length check. This could / should be done by bean validation, so it is cleaner (and cirrect error message gets displayed).

**Comment by pdurbin** [comment]
@scolapasta are you still interested in this code cleanup?

**Comment by pdurbin** [comment]
I took a quick look at pull request #5452 and it seems sane. Less validation happening in the front end, in the Javascript. So it seems to be going in the right direction. Or perfect. I can't tell from a quick look.

At standup I mentioned that @sekmiller and I discussed the benefits to the user from this effort. My understanding is that users get:

- a more consistent user experience with regard to messaging of errors
- no more situations where a user dismisses a popup and then dismisses another popup, over and over.

**Comment by sekmiller** [comment]
For testing verification that all of the validators in the Deaccession Popup work and give inline error messages.
1) If there are multiple versions available for deaccession one must be selected.
2) A reason for deaccession must be chosen
3) If the reason is "Other" then additional text must be added to the free text box. (also free text must not exceed the size limit [default=1000 may be customized]) 
4) the forwarding url must be valid (or empty) There is also a separate customizable size limit.
