### ISSUE TITLE
Search API: Support non-public search

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1299]
In a meeting this morning (in which we discussed the [Search API functional requirements](https://docs.google.com/document/d/1FfB4hX2FE-xVRzDpW9UcV7-FBN2vWd4cIpAbI_GtRWY/edit?usp=sharing)) @scolapasta @eaquigley @rtreacy and I decided that for Dataverse 4.0 we will only support searching of public (published) data via the Search API (which seems to be in line with the general [Dataverse API requirements](https://docs.google.com/document/d/1d8sT2GLSavgiAuMTVX8KzTCX0lROEET1edhvHHRDZOs/edit?usp=sharing)). This ticket will be used to track the addition of that feature (probably including "data related to me") in the future.

**Comment by pdurbin** [comment]
These days there's an (undocumented) "MyData" API that could probably be used to support non-public search. I added a script that exercises it here: https://github.com/IQSS/dataverse/blob/v4.2.1/scripts/issues/2649/reproduce

**Comment by pdurbin** [comment]
Does anyone even want this feature? If so, please get in touch. Closing.

**Comment by bencomp** [comment]
I suppose users who have lots of dataverses and datasets in Dataverse which isn't all public could want this. Or someone who hears that she's been given private access to some published dataset, who uses the search bar as her main entrypoint to The Data (instead of going through notifications of the access granting).

**Comment by bencomp** [comment]
Oh, wait, this is about the API. Never mind my previous comment :)
