### ISSUE TITLE
Create Status Page for Dataverse

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#131]
---

Author Name: **Elizabeth Quigley** (@eaquigley)
Original Redmine Issue: 3540, https://redmine.hmdc.harvard.edu/issues/3540
Original Date: 2014-02-07

---

If there is an issue (i.e. Solr is down, Rserve is down) a message should appear on the page to inform the user what is going on with a link to this status page where they can get more information. Examples: http://services.huit.harvard.edu/status-dashboard or https://status.github.com

**Comment by pdurbin** [comment]
It seems that in practice the most common need we have for a status page is one that's served up by Apache when Dataverse is slow to respond. This is the dreaded "503 Service Temporarily Unavailable" page that says, "The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later." Basically, Apache is trying to serve up content from Glassfish (the Dataverse app) but it isn't returning in a timely manner. Rather than returning the default page used by Apache (screenshot below) we could configure Apache to serve up a friendlier page. In 
aba7cd2 I just pushed a proof of concept in the Vagrant config. The [HTML file I added](https://github.com/IQSS/dataverse/blob/aba7cd21bd9fcfd8fe37123f9d58339ed9436081/conf/vagrant/var/www/dataverse/error-documents/503.html) is currently very basic but it say whatever we want and be styled however we want. The idea is for the custom HTML page to be an improvement over this:

![503_service_temporarily_unavailable_-_2015-10-08_17 38 10](https://cloud.githubusercontent.com/assets/21006/10382848/4f29cb8e-6df6-11e5-8b28-090e7dd63a7e.png)

**Comment by pdurbin** [comment]
Since GitHub went down yesterday it seems like a good time to grab some screenshots from https://status.github.com since the data is "interesting" instead of showing that they are always up:

![github_system_status_-_2016-01-28_10 24 19](https://cloud.githubusercontent.com/assets/21006/12648802/a2064548-c5a9-11e5-8791-5fd230a0b5fd.png)
![github_system_status_-_2016-01-28_10 24 37](https://cloud.githubusercontent.com/assets/21006/12648801/a202fa6e-c5a9-11e5-9434-4640a975b922.png)


We love you GitHub! Great recovery!

**Comment by kcondon** [comment]
We are working toward having better error pages to let users know what's going on.

**Comment by pdurbin** [comment]
Related:

- more gracefully report Amazon / other storage outages #8285
