### ISSUE TITLE
Root Breadcrumb: Remove this from homepage

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1321]
From General UI Doc: https://docs.google.com/document/d/1VXac5Eqx1LDVWvMogf4EYVfxv-9gIavgAnL4x_esiTI/edit

@mcrosas comment: Do we need to display the breadcrumb in the root Dataverse? Looks a bit awkward.

@mheppler comment: Seems simple enough to remove. Why not?

**Comment by mheppler** [comment]
I think I remember why this is still there on the page -- there is supposed to be a dropdown that displays a tree hierarchical structure of the Root Dataverse. If you browse only using the cards on the dataverse page, you see EVERY dataverse, whether it's a direct child or great-great-great-grandchild. The dropdown was the only place to easily see direct children.

Is that dynamic hierarchical tree ever coming back? Wasn't it removed due to performance? Once upon a time, it was important to see this hierarchical structure of a dataverse.

@mcrosas @eaquigley @scolapasta

**Comment by eaquigley** [comment]
@scolapasta and I discussed the dynamic breadcrumbs functionality and decided that will be done during the 4.01 milestone. #182 is the ticket where this is being tracked.

**Comment by mheppler** [comment]
@eaquigley @scolapasta 

Does that mean we can leave this there for when that functionality returns and close this ticket?

**Comment by eaquigley** [comment]
@mheppler I'd say its fine to go ahead and pass it to QA to close.

**Comment by mheppler** [comment]
Thank you, @eaquigley.

Closing since the dynamic functionality associated with that lone breadcrumb on the root will be returned post-4.0.

**Comment by kcondon** [comment]
Closing, bye dynamic breadcrumb.
