### ISSUE TITLE
Revisit notifications

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1336]
In 4.0, we have a notification type and store a reference to the relevant object. However, if that object changes (or is deleted) the notfication itself will change. We have discussed changing this so the notification is what it is at the time it is created and does not change.

**Comment by eaquigley** [comment]
Also need notifications for:

- [ ] when a dataverse is published
- [ ] when a dataset is published

**Comment by pdurbin** [comment]
Now that I'm working on #3943 I see a great need to revisit notifications. See also some refactoring @sekmiller and I talked about at https://github.com/IQSS/dataverse/pull/3945#discussion_r123352118 .

**Comment by mheppler** [comment]
Related issues like #2891, #2892, #3949, #4120 outline some common problems with notifications in general. I think it is important to consider these improvements to notifications with issues like Guestbook - Enabled for Request File Access #2043 and Integrate with DataTags #871 in the roadmap.

**Comment by mbamouni** [comment]
Hi,
We have dataverse and we propose these improvements 

- Pagination in the notifications page. With this by default, only the first page is load for user

- Add parameter for user to setting the storage duration of notifications and automatic deletion when the time is exceeded

- Offer the ability to select multiple notifications on the same page for deletion

**Comment by mheppler** [comment]
New year. New comment. Same issue. Just piling on here that this old code is still causing developer headaches. See #7512.

Happy belated 6th birthday, issue 1336.

🎂 🎈

**Comment by poikilotherm** [comment]
Hey @mheppler, @pdurbin, @scolapasta,

while looking at #7424 #5472 #7649 and the future stuff ahead for supporting software, workflows and containers (@atrisovic), I worry we will need this refactoring. I gave it a whirl and here are some thoughts. Maybe we can discuss those... (Maybe there's a chance I can work on this.)

- Move all the notification stuff in a package, keeping it all together in one place. Moving plus refactoring enables future use cases like sending notifications to stuff like Kafka, Apache Airflow (hello @4tikhonov), Push Notifications, Chat rooms, ...
- `UserNotification.Type` enum should be extended to contain 
   - At least pointers to the bundle properties (currently done in `MailUtil.getSubjectTextBasedOnNotification()` and `MailServiceBean.getMessageTextBasedOnNotification()`)
   - A `Class` value to save the type of the object `UserNotification.objectId` is refering to (currently done within `MailServiceBean.getObjectOfNotification()` )
- Maybe, instead of trying to write mail text completely in code, it might be a good idea to use a templating engine like [FreeMarker](https://freemarker.apache.org) to generate the message text. This should be more easy to extend, maintain and reuse (see above about new targets)
- And eventually: reuse the notifications database to make sending the notifications async:
  - Create a `DummyNotifierJob` and a `MailNotifierJob` that scan the table for unsent messages (for mail this is already present as a property!)
  - The `DummyNotifier` is in the test classes only to enable easier integration testing
  - The jobs are triggered via (configurable) Jakarta EE Timers
  - Jobs retrieve unsent messages and check every message if it should be sent.
  - Distinction between "send" and "don't send" can do deduplication, collecting and send as batch, respect user settings about filtering, disabling certain notification channels, notification frequency etc etc.
- The `MailServiceBean` could be focusing on sending the mails then instead of building the messages. Make code more readable and maintainable...

**Comment by 4tikhonov** [comment]
Hi @poikilotherm, can you please elaborate on the use case with pushing notifications? Input and output?

**Comment by poikilotherm** [comment]
> Hi @poikilotherm, can you please elaborate on the use case with pushing notifications? Input and output?

I meant pushing notifications to iOS/Android with "push notifications".

In general, we should try to make the notification system a bit more agnostic, so we can send events to other systems and not just rely on mail. Those events could be the stuff we currently send mails for, but also new use cases like workflow integrations etc.

That leads me to another thought: I have to admit it might be worth a look to see if JMS can help us with all of this, as it already contains queues etc. Would be a bit different approach, maybe even creating an inversion of current control (save notifications to database when received from JMS).

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
