### ISSUE TITLE
Object Storage for Dataverse

### ISSUE THREAD

**Issue by spalan** [IQSS/dataverse#1347]
It is increasingly common to use cloud based object storage as an alternative to local block storage for holding digital objects.  The cost savings of cloud storage are one benefit; the ability to replicate objects in the cloud, using Swift for instance, are another when the goal is long-term archiving and preservation.  

Would it be possible to implement in Dataverse the ability to identify different locations for storage of indexes from the storage of digital objects, and specify different storage providers for digital objects including Swift and S3?

**Comment by pdurbin** [comment]
@landreev I assigned this ticket to you just to put it on your radar. The suggestion came from a [2015-01-14 meeting](https://docs.google.com/a/harvard.edu/document/d/1LwGSTTiaoCCSTKjT_uyGZEhNdN203BfY1xm_udfv9oI/edit?usp=sharing) with @spalan @scolapasta and Leanne Trimble. I imagine the upcoming [Davaverse Storage Options Community Group](http://community.dataverse.org/community-groups/) would be a good place to discuss this in the future.

**Comment by pdurbin** [comment]
As @posixeleni [points out](https://github.com/IQSS/dataverse/issues/2728) this issue is definitely related to #2728. We could keep this one to be about Swift/S3 specifically and the other to be more about Globus (and other technologies?). In practice I don't think the Davaverse Storage Options Community Group really ever took off, but as I mentioned in the other issue there are projects about large files coming up such as https://hms.harvard.edu/news/dropbox-structural-biologists . Also, @CCI-MOC is interested in Swift.

**Comment by pdurbin** [comment]
Just a quick heads up that @landreev is working on code related to object storage (Swift, which is basically S3) in #2909. /cc @pameyer and @bmckinney

**Comment by pdurbin** [comment]
Pull request #3239 contains some Swift code by @anuj-rt but I'm not sure exactly what it does or if it addresses @spalan original request.

**Comment by pdurbin** [comment]
I just wanted to point out that there's been some good discussion about Mass Open Cloud, etc. at #2909 recently.

Also, we have fairly concrete plans for using Globus over at #3403.

**Comment by pdurbin** [comment]
@djbrooke you and I just talked about open issues related to S3/Swift and Globus and the one I was thinking about for Globus support is #2728 which I will leave a comment on next.

This issue is about Swift/S3 support, which is available in an experimental fashion now that pull request #3812 was merged yesterday. I'm advancing this issue to QA at https://waffle.io/IQSS/dataverse to see if the team agrees that this will be delivered in at least a preliminary form in 4.6.2. If we agree, let's add the 4.6.2 milestone to this issue and close it out.
