### ISSUE TITLE
File Permissions: Requesting File Access

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1348]
- [ ] Lock icon displayed with thumbnail for restricted files. (Need to also figure out how this will display when restrictions are changed between versions.)
- [x] Individual "Request Access" buttons
- [ ] "Request Access to Selected Files" button, associated with checkboxes on dataset page.
- [?] Confirmation popup with user name, email, to show it is being sent.
- [?] Email sent with user name, email, requested files names, dataset title, dataverse name, date/time to admin/dataset contact.
- [?] Notification for end user that request was sent, in account page, with link to dataset.
- [x] Notification for admin/dataset contact that request was sent, in account page, with link to dataset.
- [x] In Users/Groups panel on Files Permissions page, user name and files from request displayed at top of the table with Grant Access button.
- [?] Email sent to end user that access was granted to requested files names, along with dataset title, dataverse name.
- [x] Notification for end user that access was granted to requested files names, with link to dataset.

**Comment by mheppler** [comment]
Related to #792 and #1345.

**Comment by scolapasta** [comment]
Note: here is no separate logic for e-mails. Notifications are created and e-mail will be sent according to those rules.

**Comment by scolapasta** [comment]
So, some decisions I made that we can review:
- see earlier comment about e-mails
- no confirm popup - the button changes to Access requested, so user knows request got sent.
- notifications needs work, but unfortunately, that will not be able to be done to until post 4.0. What that means is that the notification may not have all the dynamic details we want (i.e file name/s, username)
- also not really sure how we would handle file names (individual per grant / request)? That could lead to way too many notifications.

- do we really need a notification to the user who requested?

I went ahead and changed the description above to ?s for the confirm popup and the e-mails.

Also, we need to decide how the workflow for requesting multiple at a time would work (since you may or may not have access and yet we also have checkboxes for download.

Let's review Monday. Passing to @equigley while these decisions are being made.

**Comment by kcondon** [comment]
OK, tested basic workflow: restrict, request, notification of request, reject, notification of rejection, grant, notification of grant and then access enabled, revoke, permission revoked.

One awkwardness is if there is a draft version, you need to go to the draft to grant access, cannot do it from published version. Also, request link should go to permissions page, Users/Groups assignment panel where you can actually grant access.

**Comment by eaquigley** [comment]
sending to @scolapasta to determine who can change the link in the notification so it goes straight to the File Permission page for the dataset rather than the dataset page.

**Comment by scolapasta** [comment]
This can be actually be done by @eaquigley if you're up to it, or by @mheppler . The text for the links is in the bundles and the parameters it sends currently globalId and displayName are on the xhtml calling the bundle (dataverseuser.xhtml). The permissions page, I think, uses id, instead of globalId.

**Comment by scolapasta** [comment]
FYI, there are a couple of checkboxes not yet finished at the top. Should we move those to separate issues (the first, I think is mpstly for @mheppler ) and the second requires a design for how best to work (since you may have access to some files already, or already requested access). Possibly could be left for post 4.0, but I think people will want to request for multiple files, so I doubt it.

**Comment by mheppler** [comment]
There is a lot of clean up required for Notifications on the Dataverse Account page, so I am creating a new ticket.

- Notifications/Dataverse Account - Various Clean Up #1460 

I am giving this ticket back to Gustavo, to decide what to do with it.

**Comment by scolapasta** [comment]
OK, so the notification part is now tracked elsewhere. What is left with this ticket is the two checkboxes from above that are unchecked:

Lock icon displayed with thumbnail for restricted files. (Need to also figure out how this will display when restrictions are changed between versions.)

and

"Request Access to Selected Files" button, associated with checkboxes on dataset page.

From my previous comment:

Should we move those to separate issues (the first, I think is mostly for @mheppler ) and the second requires a design for how best to work (since you may have access to some files already, or already requested access). Possibly could be left for post 4.0, but I think people will want to request for multiple files, so I doubt it.

**Comment by eaquigley** [comment]
Checkbox one is now in #1462 and checkbox 3 is in #1476 passing this ticket to QA to be closed.

**Comment by kcondon** [comment]
Closing
