### ISSUE TITLE
Groups: Update indexing and search to support groups

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1378]
The low level IP Group infrastructure is in place and groups can be create via API currently. However, indexing needs to be updated to include IP Groups.

**Comment by scolapasta** [comment]
Note: what is especially needed is indexing of all groups. IP groups, in particular, if the logic is not part of generic group indexing, can be deferred to post 4.0.

**Comment by pdurbin** [comment]
@kcondon as we discussed, I'm giving this to QA for an initial look. I still have some outstanding questions for @michbarsinai about when explicit groups of a user can be known at runtime.

Also, as I demonstrated, even if you can see a card based on your group membership, clicking it may prompt for login because permissions for groups has not been fully implemented. My understanding is that we're using the "no effect" ticket at #1380 for tracking this.

Also, permissions are not inherited. In my testing I've been using direct assignment of the "Admin" role to various groups (Shib, IP, Explicit, Builtin).

**Comment by kcondon** [comment]
This works with the above caveats. Permissions are not inherited beyond dv to ds or sub dvs. So unreleased sub dv's or ds are not visible and add data buttons not available on sub dv's.

**Comment by pdurbin** [comment]
> Permissions are not inherited beyond dv to ds or sub dvs

Right, specifying `permissionRoot=false` in the JSON you use to create a dataverse no longer has an effect as of this commit:

for now, make all dataverses permission root (on create) · fb7e65f

In practice, this means that there is no inheritance of permissions.
