### ISSUE TITLE
Log In & Shibboleth: Onboarding Process

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1387]
Due to passwords needing to be changed and Shibboleth account conversions, we need a robust, interactive, and helpful onboarding process to let users know how their accounts need to be updated.

**Comment by raprasad** [comment]
\cc @scolapasta @eaquigley @pdurbin 
(... Summary of my memory on the username issues.  Some of it may have changed in last few months)

## What happens when an existing Harvard user wants to use Shibboleth? (local account -> shib account)
**summary**: User loses her/his username.  User no longer has separate first/last name fields

- Currently, if existing Dataverse users are migrated to Shibboleth (or other outside authentication), they will lose their Dataverse Usernames.  For account migration, the process may be made easier by allowing users to keep their existing usernames.
- In general, requiring Usernames for one type of authenticated user but not another leads to inconsistencies.  It may make it harder to transition users from one type of authentication to another.

## What happens when a User leaves Harvard? (shib account -> local account)
**summary**: User be assigned a brand new username.  User's first and last name fields will be combined into one field

- Although not relevant immediately, having a Username for all authenticated users will help when trying to migrate users off of Shibboleth (or other institution-dependent authentication.)
- In the case of a scholar who accesses Dataverse via Shibboleth and is leaving Harvard, the existence of a Username from the beginning would make migration to a local account much easier.


## Not storing First name, Last name for Shibboleth users
- Only local Dataverse account holders have separate first and last names stored in the database.  Shibboleth users, and other outside authenticated users, have only a “Display Name” stored in the database.
- Currently, first and last name would be lost if moving to shibboleth from a local account
   - Shibboleth Users:  Display Name
   - Local Account Users:  Display Name, First Name, Last Name

Given that first and last name information is available via Shibboleth (and other known authentication systems), it seems to make sense to store this data.  In this way, the name of a user may be displayed in “FirstName LastName” format, or “LastName, FirstName” format, as appropriate.

**Comment by pdurbin** [comment]
@eaquigley this ticket seems to be a duplicate of #796 which says, "This ticket is about the UI/UX for the conversion."

**Comment by raprasad** [comment]
(Following up on above)  
## Potentially problematic storage of User and Group Keys

Within Postgres, role assignments within the permissions system do not use traditional relational database keys, such as integers.   Instead, user and group identifiers are referenced as follows:
  - Table: roleassignment 
  - Column: assigneeidentifier (not a ForeignKey)
	- User format:  @identifier.   
        - Example assigneeidentifier values in db: ```@pete, @uma```		
	- Group format: &identifier.  
        - Example assigneeidentifier values in db: ``&1, &2```

The “@” and “&” symbols are used to distinguish between users and groups.  More traditional models would use either separate tables for users and groups or a “type” column to distinguish between the two.

### The use of Usernames, in the cases of @pete and @uma, may become problematic if those users are migrated to shibboleth or vice versa.

More specifically, the “assigneeidentifier” string may change when:

*	A person who authenticates via an institution (Shib users) wants to become a local user.
*	A person who is a local user wants to use her/his institutional (Shib) authentication

Using a traditional database key would avoid this potential issue.

If this understanding is correct, it's another reason why every user should have a consistent Username--so Usernames are not added or lost depending on the direction of the move.  

*	Local auth -> Shib auth:  Username is *lost*
*	Shib auth - > Local auth:  Username is *added*

**Comment by mheppler** [comment]
I'm just going to leave this here, with hopes that sanity will reign and we implement what we first designed for this workflow.

https://iqssharvard.mybalsamiq.com/projects/loginwithshibboleth/Dataverse%20Account%20II%20-%20Choose%20Username

**Comment by pdurbin** [comment]
> Example assigneeidentifier values in db: @pete, @uma

See also the "Stop using `@pete` and `@uma` (strings) in role assignments" ticket: #1151

**Comment by michbarsinai** [comment]
Discussion was moved to email. (TL;DR: either This ticket can be closed, or someone gets a Turing award :-) )

**Comment by pdurbin** [comment]
> either This ticket can be closed, or someone gets a Turing award

I wouldn't say that. A significant amount of refactoring work has been proposed: https://github.com/IQSS/dataverse/issues/1151#issuecomment-72210257

That's my understanding, anyway.

**Comment by eaquigley** [comment]
As mentioned during the weekly team meeting yesterday, this ticket is more about making sure users can tell the differences between logging in with a built in account and logging in with Shibboleth NOT about all the technical details as listed above. That discussion and the decision reached is more of a fit for #1151.

**Comment by michbarsinai** [comment]
BTW, here's NYT on the revamped twitter on boarding process. Some parts may be applicable for us (but not for Beta 12).
http://bits.blogs.nytimes.com/2015/02/02/twitter-displays-its-value-with-instant-timeline-for-new-users/?_r=1&utm_medium=email&utm_campaign=Versioning <http://bits.blogs.nytimes.com/2015/02/02/twitter-displays-its-value-with-instant-timeline-for-new-users/?_r=1&utm_medium=email&utm_campaign=Versioning>

**Comment by eaquigley** [comment]
I registered dataverse-demo today. Passing ticket to QA to be able to close. (@kcondon not sure how you will check this, you will just need to trust that I did this)

**Comment by eaquigley** [comment]
I am closing this ticket and starting a new one about this so these comments aren't deleted.
