### ISSUE TITLE
Add Support for Meta-tags in HTML of Dataset for Reference Managers (Citation Metadata)

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1393]
Worked with Reference Managers at FORCE2015 to come up with ways Dataverse could make the metadata in a Dataset page's HTML (especially the Data Citation) machine-readable for Reference Managers like EndNote, Zotero, etc to automatically extract data citation metadata into their system. See [notes from meeting](https://docs.google.com/document/d/1rpHmoCZQNQOeK1RbLW--JloWRc5hmREVKnwj1ZIYdIU/edit?usp=sharing).

To support this we would need to add meta-tags (dcterms) in the `<head>` section of a dataset's HTML. See an example below from a [Dryad dataset](http://datadryad.org/resource/doi:10.5061/dryad.gm2sm) (view source)

```
  <title>Data from: Historical retreat of alpine glaciers in the Ahklun Mountains, western Alaska - Dryad</title>
  <link rel="schema.DCTERMS" href="http://purl.org/dc/terms/"/>
  <link rel="schema.DC" href="http://purl.org/dc/elements/1.1/"/>
  <meta name="DC.creator" content="Walsh, Patrick"/>
  <meta name="DC.creator" content="Kaufman, Darrell"/>
  <meta name="DC.creator" content="McDaniel, Tess"/>
  <meta name="DC.creator" content="Beeman, Jai"/>
  <meta name="DCTERMS.spatial" content="Ahklun Mountains"/>
  <meta name="DCTERMS.spatial" content="southwestern Alaska"/>
  <meta name="DCTERMS.temporal" content="Holocene"/>
  <meta name="DCTERMS.dateAccepted" content="2015-01-09T23:18:49Z" scheme="DCTERMS.W3CDTF"/>
  <meta name="DCTERMS.available" content="2015-01-09T23:18:49Z" scheme="DCTERMS.W3CDTF"/>
  <meta name="DCTERMS.issued" content="2015-01-09" scheme="DCTERMS.W3CDTF"/>
  <meta name="DC.identifier" content="doi:10.5061/dryad.gm2sm"/>
  <meta name="DC.identifier" content="http://hdl.handle.net/10255/dryad.78197" scheme="DCTERMS.URI"/>
  <meta name="DC.description" content="The Ahklun Mountains support the only extant glaciers in western Alaska. The glaciers were originally mapped by the U.S. Geological Survey using photogrammetry methods based on 1972 - 1973 aerial photos. We surveyed for presence or absence of the glaciers by fixed-wing aircraft in 2006. Of 109 glaciers originally mapped, 10 (9%) had disappeared. Using aerial imagery of a subset of 76 glaciers at three time steps between 1957 - 2009, we determined the average rate of areal loss was 45% over 52 years. At this rate, it is likely that all Ahklun Mountain glaciers will be extinguished by the end of the current century."/>
  <meta name="DCTERMS.hasPart" content="doi:10.5061/dryad.gm2sm/1"/>
  <meta name="DCTERMS.hasPart" content="doi:10.5061/dryad.gm2sm/2"/>
  <meta name="DC.subject" content="Glaciers"/>
  <meta name="DC.subject" content="Recession"/>
  <meta name="DC.title" content="Data from: Historical retreat of alpine glaciers in the Ahklun Mountains, western Alaska"/>
  <meta name="DC.type" content="Article"/>
  <meta name="DC.identifier" content="jfwm-012014-JFWM-008R"/>
```

Figshare also has meta-tags but dont use dcterms: [Example](http://figshare.com/articles/University_of_Warwick_APCs_2014/1296232)

```
<meta name="citation_title" content="University  of Warwick APCs 2014">
<meta name="citation_author" content="Stuart Lawson">
<meta name="citation_doi" content="doi:10.6084/m9.figshare.1296232" />
<meta name="citation_publication_date" content="2015/01/28">
```

@eaquigley I spoke with @mcrosas and this is something we would like to schedule for after 4.0 so please let me know when this can be scheduled and who we can assign this to work on.

Updated 2017-03-06 by @pdurbin to make the first code block more readable as a couple dozen lines rather than a single line.

**Comment by posixeleni** [comment]
Related to https://github.com/IQSS/dataverse/issues/2243

**Comment by borsna** [comment]
I also think the description for each item should be in the <meta name="description"> on landing pages. 
right now the same static description is used:

```xml
<meta name="description" content="The Dataverse Project is an open source software application to share, cite and archive data. Dataverse provides a robust infrastructure for data stewards to host and archive data, while offering researchers an easy way to share and get credit for their data.">
```

**Comment by bencomp** [comment]
This would be a great feature. +1

@borsna is right about what the description should be: the item, not the software.

**Comment by borsna** [comment]
@posixeleni, @bencomp meta tags for generic dublin core / terms should also be exported for better discoverabity:
See examples of how to define prefixes: 
http://dublincore.org/documents/dc-html/ and http://dublincore.org/documents/dcq-html/

Another note, for dates use ISO 8601 format:
``` content="2015-01-28" ``` instead of ```content="2015/01/28"```

**Comment by jggautier** [comment]
This is also one of the 11 recommendations made in [A Data Citation Roadmap for Scholarly Data Repositories](https://doi.org/10.1101/097196) (https://doi.org/10.1101/097196).

**Comment by landreev** [comment]
Corresponding pull request: https://github.com/IQSS/dataverse/pull/3828
(reviewing)

**Comment by landreev** [comment]
I have reviewed the DC fields that this PR adds to the dataset page, and checked if they were being populated with the same values that our DC export util puts in these fields. 
Here's what I found: 

1. DC.identifier
In a parallel development, (#3809) we had requests from users to populate these field with a resolvable URL, instead of our normal identifier; 
i.e. "http://hdl.handle.net/1902.1/XYZ" 
instead of 
"hdl:1902.1/XYZ"
Another user has made a PR, and we've already moved it into QA. 
It's up to you, but you may want to switch to doing the same thing with this metadata added to the dataset page  - ? 
If you decide to do so, instead of using DatasetPage.persistentId, you could add something like this to the page:
```
public String getPersistentIdURL() {
   GlobalId globalId = new GlobalId(this.dataset);
    return globalId.toURL().toString();    
}
```

(the url *may* need to be encoded, as to not to break the html?? - idk)

2. DC.type

You simply put the word "Dataset" into this field; 
The DublinCoreExportUtil however appears to be populating this field with the metadata field "kindOfData", from the citation metdata block. 
IRL it would be populated with things like "survey data",  "medical records data", etc. 

I don't have a strong opinion on whether this is "wrong" necessarily. It seems to make sense in each case... So I'll leave this to somebody else to decide whether it is worth/necessary for the field to contain the same thing in both situations. 

3. DC.date

You put workingVersion.getReleaseTime() into the field; 

The export util populates it with the value of the field "productionDate"

I honestly have NO idea which is the correct way... the "productionDate" is something that can only be entered by the dataset author manually, as a metadata field. The "release time" is a column in the datasetversion table, that gets set automatically. 
It is null however in a Draft version, until it gets published. So @pameyer - I'm not sure what your code there is going to do, when it is null... (is it going to throw a null pointer/default to the epoch/...?)

Anyone wants to weigh on either of the last 2?

(all the other fields appear to be handled identically)

**Comment by pameyer** [comment]
@landreev - thanks for taking a look!

1. I'll defer to the identifier folks, but I think it makes more sense to have this as an identifier (with identifier scheme) rather than a URL.

2. I'll have to see if I can track down any notes from my previous implementation to see why I did it this way (aka - not the equivalent of "Dataset/${kind of data}" or "${kind of data}"); but that doesn't mean this was the correct interpretation. 

3. Good catch on the null - I'll take a look to make sure that doesn't cause problems with Draft.

**Comment by pameyer** [comment]
Draft datasets now have empty string in publication date (since the commit messages aren't showing up in this issue).

**Comment by jggautier** [comment]
About the DC type, I'm wondering if it's best to use "dataset" instead of what's put in the kindOfData field for a few reasons:
- I thought that in the context of the html meta tags, the DC type should identify the resource as a dataset, as opposed to a journal article or blog or something else that reference managers and search engines would be interested in knowing about the resource.
- kindofdata accepts any values right now, or none at all. Some datasets have values like "awesome data". So no value may wind up in dc.type if kindofdata is used (only [about 2800 published datasets in HDV have a value for kindofdata](https://dataverse.harvard.edu/dataverse/harvard?q=kindOfData%3A*&fq0=metadataSource%3A%22Harvard+Dataverse%22&types=dataverses%3Adatasets%3Afiles&sort=score&order=desc)), and what's entered in there might not be helpful at all.
- What's entered in the kindofdata field might be helpful in dc.subject.

**Comment by pameyer** [comment]
@jggautier 

- for DC type, I agree with your thinking about "dataset" in html meta tags.

- would using kindOfData for DC.subject conflict with the Dataverse subject?

- for identifier vs URL, there's more implementation complexity involved in pulling an identifier from a URL than there is determining a URL to use to resolve the identifier (of known identifier scheme). It could also seem counter-intituive to have ${protocol}://${details_of_identifier} when ${protocol} is `http`/`https`, because it's not the identifier protocol.  The trade off is slightly increased complexity for resolving the identifier, though.  There does seem to be a trend towards using `http`/`https` URLs for identifiers though - this may turn out to be an area where we go with what the experts recommend, and disregard the fact that the arguments from the experts haven't convinced me.

**Comment by jggautier** [comment]
Thanks @pameyer. This is an update with what we discussed last week:

- @pameyer and I agreed the value for DC.type should be "dataset". (I was thinking values from kindofData could be one of multiple metadata fields used to populate DC.subjects, but we agreed to stick to just the 14 dataset subjects for this issue and consider other values later.)
- The explanation about DC.identifier makes sense to me. Thanks! I'm not sure how that conflicts with #3809.

This is what I think we agree would appear on dataset page html (taking an example from [https://data.sbgrid.org/dataset/447/](https://data.sbgrid.org/dataset/447/):

`<meta name="DC.identifier" content="DOI:10.15785/SBGRID/447" />`
and/or `<meta name="DC.identifier" content="HDL:10.15785/SBGRID/447" />`
```
<meta name="DC.title" content="X-Ray Diffraction data from human WDR5 in complex with MLL Win6mer peptide, source of 5SXM structure"/>
<meta name="DC.publisher" content="SBGrid Data Bank"/>
<meta name="DC.type" content="Dataset" />
``` 
`<meta name="DC.date" content="May 26, 2017"/>`
May 26, 2017 would be the date the dataset's last version was published

```
<meta name="DC.creator" content="Alicea-Velazquez, Nilda"/>
<meta name="DC.creator" content="Shinsky, Stephen"/>
<meta name="DC.creator" content="Cosgrove, Michael"/>
```
Lastly, @borsna [mentioned in an earlier comment](https://github.com/IQSS/dataverse/issues/1393#issuecomment-109413067) that that the existing static DC.description on landing pages: `<meta name="description" content="The Dataverse Project is an open source software application to share, cite and archive data. Dataverse provides ...">` should describe the dataset instead of the software. Datasets in SBGrid Data Bank have "Dataset Description". For SBGrid's use case, could that be used?:
`<meta name="DC.description" content="Native data set"/>`

**Comment by pdurbin** [comment]
@oscardssmith please move as much business logic as possible from `src/main/java/edu/harvard/iq/dataverse/DatasetPage.java` to `src/main/java/edu/harvard/iq/dataverse/dataset/DatasetUtil.java` and write tests in `src/test/java/edu/harvard/iq/dataverse/dataset/DatasetUtilTest.java`. Once the code is in `DatasetUtil.java`, please run it through the Netbeans formatter. Thanks!

**Comment by oscardssmith** [comment]
I think I can move it to `DatasetVersion.java` more easily, as the most of what I'm doing is calling something there. Would that work similarly well, or is there a good reason for it to be in `DatasetUtil.java` instead?

**Comment by pdurbin** [comment]
@oscardssmith that's fine. In that case, your tests should go in `DatasetVersionTest.java`. Thanks.

**Comment by jggautier** [comment]
@pameyer, @scolapasta, @oscardssmith and I talked about questions raised in my last comment. All of the decisions regarding DC.identifier, type, subject and description hold.

A definition of done for this issue is that a user on a dataset landing page could press her Zotero or Endnote browser extension button and have a metadata record with these metadata tags imported into her Zotero or Endnote library. (I'm not aware of any other reference managers that use html metatags to create metadata records.)

I imagine this will also improve how search engines index dataset pages, but that's harder to test right away.

I think closing this issue will solve issue #2445, a more broadly-worded ticket about metatags in dataset landing pages. But we can consider the points raised there about what tags to use (Highwire Press tags, Eprints tags, BE Press tags, and PRISM tags) when we want to add and improve dataset metatags.

@oscardssmith asked what metatags should appear in _dataverse_ landing page html, which for now isn't changing, but I'm thinking should be revisited to help discoverability in search engines.

**Comment by oscardssmith** [comment]
To do the final testing, we will need this on a server, so we can test against zotero and/or endnote to make sure they can deal with the stuff we are doing.

**Comment by landreev** [comment]
Reviewed, looking good, dragged into QA. (sorry for the delay...)

**Comment by oscardssmith** [comment]
Now that it's in QA, is there anything I need to do?

**Comment by kcondon** [comment]
Not unless we find a bug.

**Comment by pdurbin** [comment]
@oscardssmith actually, I just spoke with @kcondon about the `1393_exp_dcmeta` branch and there is one thing we'd like you to do. Can you please merge (not rebase) the latest from the `develop` branch into `1393_exp_dcmeta`? Right now that branch is 270 commits behind `develop`. Please be very careful not to write to the `develop` branch. Here's the sequence I use:

`git checkout develop`

`git pull`

`git checkout 1393_exp_dcmeta`

`git merge develop`

Either commit as prompted are resolve merge conflicts and then commit.

`git push origin 1393_exp_dcmeta`

If you have any question, please just grab any Dataverse developer.

**Comment by oscardssmith** [comment]
Done, can you confirm that my latest push fixes this?

**Comment by kcondon** [comment]
Yes, I'm able to build now. Thanks!

**Comment by pdurbin** [comment]
I was chatting with @adam3smith about this today and loaded the code on a test server and he seemed to be saying that it works fine with Zotero.

When we announce this feature, it'll be more meaningful if we have something like "Zotero browser extension" in the title so I tweaked it.

**Comment by pdurbin** [comment]
There's some bonus discussion with @adam3smith at https://github.com/IQSS/dataverse/pull/3828#issuecomment-310395228 where he uploaded the following screenshot from his testing with Zotero (thanks!):

![zotero](https://user-images.githubusercontent.com/21006/27446710-90cdcb8a-574c-11e7-8f85-36bea98d0649.png)

**Comment by HughP** [comment]
> @posixeleni, @bencomp meta tags for generic dublin core / terms should also be exported for better discoverabity.
> Examples of how to define prefixes:
> http://dublincore.org/documents/dc-html/ and http://dublincore.org/documents/dcq-html/
> 
> Another note, for dates use ISO 8601 format:
> `content="2015-01-28"` instead of `content="2015/01/28"`

Commenting on a closed issue, mostly for those who read it like I do much later.... @borsna is generally correct about the use of dates in DC meta tags (ISO8601), however, GoogleScholar's implementation instructions for dates requires the slash format. GoogleScholar does several non-standard things with DC meta tags.

**Comment by jggautier** [comment]
Good point. It's mentioned at https://scholar.google.com/intl/en-us/scholar/inclusion.html#indexing, which was included in another old issue at https://github.com/IQSS/dataverse/issues/2717. But Google Scholar still indexes only scholarly literature and has no plans to index datasets, right?
