### ISSUE TITLE
Search: Searching on dv subject from basic search returns no results, adv search works.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1431]
Searching on dv subject from basic search returns no results, adv search works.

**Comment by pdurbin** [comment]
Basic search of dataverse affiliation wasn't working either. I'm copying both dataverse subject and dataverse affiliation to the "catchall" field used by basic search as of b6d6425b01b4ba966baf3cef97a0a1ad3d866aaa

Testing will require a new schema.xml and re-indexing.

Please note that I'm aware that highlighting on these two fields in the dataverse card doesn't work. The reason is that the "unfriendly" names "dvSubject_en" and "dvAffiliation_en" would be exposed in the GUI. I tried to have the friendly names show up but couldn't do so quickly. I left a todo in the code to think about this.

Passing to QA.

**Comment by kcondon** [comment]
Works, closing
