### ISSUE TITLE
Config Dataverse: Cannot feature dataverses other than in Root dv: feature or bug?

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1434]
Cannot feature dataverses other than in Root dv: feature or bug?

**Comment by eaquigley** [comment]
@kcondon I just tried this and was able to do featured dataverses in a dataverse i created beneath the root. the dataverses have to published and i've found that it is VERY easy to skip over the checkmark at the top of the featured dataverses pop up that a user has to check in order to have featured dataverses show. I'd really like it if we could add in logic so if a user moves a dv into the list of "dataverses to display" the box above is automatically checked. Or we could have the checkbox underneath the list widget. I'll create a separate ticket for that.

**Comment by kcondon** [comment]
Apparent user error, works, closing
