### ISSUE TITLE
File Thumbnail Image Preview - Remove Default Icon Image File

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1463]
Now that we have new vector custom icons, we need to remove the old image icon from the backing bean. It is currently being used when a thumbnail image preview can't be generated.

**Comment by landreev** [comment]
Should be ready to QA. 
To clarify: there's no new behavior to observe for this one. 
There's new logic and new code in the back end, but the frontend behavior should stay the same: 
when you upload files and are still in temp view (before clicking save), there should be thumbnails with the word "preview", for files where a thumbnail could be generated; and a neat vector icon otherwise.

**Comment by sbarbosadataverse** [comment]
This is the image logo showing up when a thumbnail preview can't be generated

![qbjrebekx1ikd2berdcn15vpyf19hh9bwqinwsojt10](https://cloud.githubusercontent.com/assets/8322346/6760885/aafcc500-cf23-11e4-9848-dc0aad9a5d97.png)

**Comment by sbarbosadataverse** [comment]
Kevin if this is the image we should see, you can close.

**Comment by kcondon** [comment]
Yes, that's the correct image. Closing
