### ISSUE TITLE
Dataset Search/Browse Card - Remove Default Icon

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1464]
Now that we have new vector custom icons, we need to remove the old image icon from the backing bean. It is currently being used when a dataset doesn't contain files that have a thumbnail image preview.

**Comment by landreev** [comment]
@mheppler 
Mike, I added more image logic and modified the search fragment. 
now it only displays a thumbnail on a dataset card if a non-default image is available. 
otherwise it displays text "(no image available for dataset)". 
Please replace this with your fancy vector image. 
![screen shot 2015-02-28 at 9 23 57 pm](https://cloud.githubusercontent.com/assets/737558/6429186/36ef63fe-bf90-11e4-872e-8155587f0be3.png)

**Comment by mheppler** [comment]
Added icons for restricted and restricted with access to file cards. Added default icons for dataverse and dataset to the preview for cards. Cleaned up markup and moved CSS to stylesheet.

**Comment by posixeleni** [comment]
Works as expected with default icons only appearing when there is no image file available at the Dataverse or Dataset level.
