### ISSUE TITLE
API Documentation Organization

### ISSUE THREAD

**Issue by mcrosas** [IQSS/dataverse#1489]
The API guides should be organized in the following way:

Main APIs, more frequently used by external parties:
- Deposit API (SWORD)
- Search API
- Dataset Metadata API (get metadata for a dataset in multiple formats)
- Dataset File API (or Data API, get data files for a dataset)

Dataverse Native  APIs (advanced APIs)
- All native APIs

**Comment by posixeleni** [comment]
@scolapasta can we meet next week to discuss what remains to be done for this? And who needs to work on documenting each API. @mcrosas and I spoke recently that the API Guides will need to be ready sooner than other guides (aside from User Guide) since we want others to easily be able to integrate with us ASAP after 4.0 is released.

**Comment by pdurbin** [comment]
Putting "all native APIs" on a single page at http://guides.dataverse.org/en/latest/api/native-api.html feels wrong since there are so many endpoints there.

Are we saying that creating a dataset with JSON is an advanced operation?

**Comment by eaquigley** [comment]
Passing to @posixeleni to QA for me.

**Comment by posixeleni** [comment]
now displaying as expected in http://guides.dataverse.org/en/latest/api/index.html

closing.

**Comment by pdurbin** [comment]
@posixeleni I'm a little troubled that my concerns at https://github.com/IQSS/dataverse/issues/1489#issuecomment-91090017 were not addressed at all. :(

**Comment by posixeleni** [comment]
@pdurbin I'm going to create a new ticket related to your concern so that we can track it separately from this ticket which needed to be completed asap. Unfortunately I dont have an answer for you but if you have a proposal for how you want the Native API documentation to look like I would strongly recommend you put something together!

**Comment by pdurbin** [comment]
@posixeleni perfect! Thanks for creating #2174! We'll sort this out in a future version of the API docs. :)

**Comment by bencomp** [comment]
It seems there is no Dataset Metadata API at http://guides.dataverse.org/en/latest/api/index.html. Am I missing something?

**Comment by pdurbin** [comment]
@bencomp since this ticket is in QA can we please discuss this further in #2174?

**Comment by bencomp** [comment]
@pdurbin I think it has little to do with the native API #2174, so creating a new issue or reopening this one makes more sense to me.

**Comment by pdurbin** [comment]
@bencomp it sounds like you're going think some more about what the new issue would be: http://irclog.iq.harvard.edu/dataverse/2015-05-20#i_20044

And that you're ok with this issue going through QA for 4.0.

Again, we'll improve the API doc organization in #2174.
