### ISSUE TITLE
Index: Cannot see unpublished dv or ds if assigned proper view perms as IPGroup.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1513]
I've directly assigned admin role/ view unpublished dv/ds to an ipgroup but still cannot see the unpublished dv/ds cards, though I can see the role assignment on the permissions page. I can go directly to the landing pages for both and the permissions page for both as a member of the ip group.

**Comment by scolapasta** [comment]
Please retest.

Be aware that IPGroups cannot have edit typer permissions, just read permissions.

**Comment by kcondon** [comment]
Waiting for #1380 to be fixed before we can test.

**Comment by kcondon** [comment]
Related, possibly a duplicate: #3105

**Comment by pdurbin** [comment]
Today @michbarsinai @scolapasta @kcondon and I discussed IP groups and I've been asked to try to reproduce this bug in the branch that pull request #3103 is based on. It's believed this is still a bug.

**Comment by pdurbin** [comment]
I can easily reproduce this bug by giving an IP Group "admin" on an unpublished non-root dataverse, which should result in the "Guest" user being able to see a search card for the unpublished dataverse.

Interestingly, the indexing seems fine. The unpublished dataverse in question says it's discoverable by the IP Group: `"discoverableBy":["group_ip/ipGroup3", "group_user5"]`

The problem is at runtime we need a method in Dataverse to provide a list of all the IP Groups that a user (such as Guest) is a member of. This strongly reminds me of the `public Set<Group> groupsFor(AuthenticatedUser au)` method I introduced in pull request #3062 but in the code you can see I wrote `@todo Determine if this method works with IP Groups`. Sadly, it seems the answer is no and since @michbarsinai is in town I plan to see if he can help with this.

**Comment by pdurbin** [comment]
Some initial progress in e6438c7 but a bit rushed. Ideally I'd add some API tests.

**Comment by kcondon** [comment]
This is working now. Phil, we can close this unless there is something more you want to do.

**Comment by pdurbin** [comment]
@kcondon I'm glad to hear e6438c7 helped. It's in pull request #3103. I'll close this issue but I'll note that #3273 is still open which is about "groups within groups".
