### ISSUE TITLE
Root Dataverse URL + Pretty Faces -- Unecessary?

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1519]
Currently, we have the root using Pretty Faces, to add the alias to the URL:

https://dvn-build.hmdc.harvard.edu/dataverse/root

That shouldn't be necessary. All links to the root should just be:

https://dvn-build.hmdc.harvard.edu/

**Comment by pdurbin** [comment]
@mheppler once https://dataverse.harvard.edu has a custom homepage (#3639) I think we'll need https://dataverse.harvard.edu/dataverse/harvard to get at the facets, etc.

**Comment by pdurbin** [comment]
Related: #3872

**Comment by scolapasta** [comment]
Discussed with @mheppler 

As @pdurbin points out we do need both versions in the case of using a custom home page.

Even when we don't, the https://dvn-build.hmdc.harvard.edu/dataverse/root url exists because the root dataverse follows the same rules as any other dataverse (as much as we can, of course).

Once concern was SEO, but reviewing google policy (https://webmasters.googleblog.com/2008/09/demystifying-duplicate-content-penalty.html):

"There's no such thing as a 'duplicate content penalty.' "
"most site owners whom I hear worrying about duplicate content aren't talking about scraping or domain farms; they're talking about things like having multiple URLs on the same domain that point to the same content. Like www.example.com/skates.asp?color=black&brand=riedell and www.example.com/skates.asp?brand=riedell&color=black. Having this type of duplicate content on your site can potentially affect your site's performance, but it doesn't cause penalties."

Closing this issue.
