### ISSUE TITLE
search-include-fragment ui:param - dataverseLinksStayOnPage == true ?

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1521]
```
<ui:param name="dataversePage" value="#{dataverseLinksStayOnPage == true ? '' : '/dataverse.xhtml' }"/>
```

That is from the search-include-fragment. No one seems to know what it is or what it does or why it was added. Look into it, and remove if not needed.

**Comment by pdurbin** [comment]
@mheppler it was added in 84facac5e4d67637d53e3ac0b5366a24ce260905 because at the time we were using the search-include-fragment across the "dataverse" page (the home page) and the "data related to me" page. These days "data related to me" has been replaced with "my data" so `dataverseLinksStayOnPage` can be safely removed.

**Comment by mheppler** [comment]
Removing in the `3776-public-only` branch for issue #3776. Will add note to that issue. Closing this issue.
