### ISSUE TITLE
Privacy Policy - Storing & Displaying Harvard Privacy Policy

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1547]
The Harvard Dataverse installation will need to have the Site Privacy Policy stored in either an HTML page or in the DB for our installation. The site Privacy Policy is specific to Harvard's installation: https://www.dropbox.com/s/azsnb9dfle2jbh6/HarvardDataverse_PrivacyPolicy_Final.docx?dl=0 (note: this is just a temporary location for this doc to have it easily accessible (GitHub doesnt allow file attachments) It should live on the Harvard Dataverse website.

**Comment by mheppler** [comment]
Don't this should go in the HTML. Giving to Gustavo to decide how to dynamically store this.

**Comment by eaquigley** [comment]
spoke with @mcrosas and the privacy policy will live in the docs under Best Practices->Harvard Dataverse Policies. Additionally, have Dataverse Account Terms of Use and Sample Data Usage Agreement documents live here.

Privacy Policy will have a link in the footer of the Harvard Dataverse Installation that will point to the sphinx doc for this.

**Comment by scolapasta** [comment]
Similar to terms of access, should be a setting in the settings table and then add a link to the footer that uses the setting. The value if that setting will be gotten from @posixeleni

**Comment by pdurbin** [comment]
I added a place in the settings to store the privacy policy and documented how to populate it: http://guides.dataverse.org/en/latest/installation/installation-main.html#applicationprivacypolicy

**Comment by pdurbin** [comment]
> should be a setting in the settings table and then add a link to the footer that uses the setting

@mheppler as I showed you on https://apitest.dataverse.org I added a link in the footer that reads from the database the contents of a file that has been pushed into the database like this:

curl -X PUT -d@/Users/pdurbin/Desktop/privacy-policy.html http://localhost:8080/api/s/settings/:ApplicationPrivacyPolicy

I don't think the link works the way @scolapasta wants though so over to you to figure out with him and @eaquigley how it should work. At least it's reading from the database.

I mentioned to @raprasad that since this is in the footer, it breaks the rule where the footer is synced between these sites...

- https://dataverse-demo.iq.harvard.edu
- http://dataverse.org
- http://guides.dataverse.org/en/latest/
- http://community.dataverse.org
- http://best-practices.dataverse.org

... but maybe this is fine.

I also mentioned to @michbarsinai that we dropped the 1024 character limit in 44e46611186fabe83d781d5cd3188e883cb5430f for #972 but perhaps that's a discussion for another ticket.

Over to @mheppler for design work.

**Comment by mheppler** [comment]
Cleaned up the layout of the Privacy Policy link in the footer of the dataverse_template. Moved remaining text to bundle, and inline CSS to stylesheet.

Passing to @posixeleni to let us know when Privacy Policy is added to Best Practices Sphinx site.

**Comment by pdurbin** [comment]
@mheppler the backend changes we talked about are done. The installer will put a default URL in (@posixeleni will be letting us know the final URL) and I updated the guides since I changed the "key" from ApplicationPrivacyPolicy to ApplicationPrivacyPolicyUrl.

@posixeleni if you want to update the final URL yourself, here are the two places:

- https://github.com/IQSS/dataverse/blob/00a63e9740dab98b72d3f5515705cf606e852ceb/scripts/api/setup-all.sh#L39
- https://github.com/IQSS/dataverse/blob/00a63e9740dab98b72d3f5515705cf606e852ceb/doc/sphinx-guides/source/installation/installation-main.rst#applicationprivacypolicyurl

Or just pass the ticket to me or @mheppler and we can do update them.

**Comment by pdurbin** [comment]
Actually, @scolapasta wants a render=false if no privacy policy link is configured and said to give this to @mheppler for that. Then back to @posixeleni please.

**Comment by mheppler** [comment]
Added render logic for Privacy Policy link in the footer of dataverse_template page.
````
#{!empty systemConfig.applicationPrivacyPolicyUrl}
````

**Comment by posixeleni** [comment]
@pdurbin @mheppler I have created the Sphinx doc for the Privacy Policy on dataverse.org. The URL is now: 

http://best-practices.dataverse.org/harvard-policies/harvard-privacy-policy.html

Will assign to either one of you to add into the db.

**Comment by pdurbin** [comment]
I updated the links. Passing to QA.

**Comment by eaquigley** [comment]
I'm not seeing the Privacy Policy in the footer of dvn-build. @mheppler & @pdurbin

**Comment by mheppler** [comment]
Get an updated script from @pdurbin to run on dvn-build in order to have the Privacy Policy link display in the footer.

**Comment by pdurbin** [comment]
@kcondon as @mheppler pointed out there **is** a new script to run for Harvard-specific settings such as the Privacy Policy. Please see https://github.com/IQSS/dataverse/issues/1587#issuecomment-77455465

(@eaquigley the behavior you're seeing where the link is hidden unless you explicitly set up the Privacy Policy is by design, per earlier comments in this ticket.)

**Comment by posixeleni** [comment]
Unable to test this in dvn-build or demo. I cannot see the Privacy Policy in the footer of dvn-build. @kcondon looking at @pdurbin comment https://github.com/IQSS/dataverse/issues/1547#issuecomment-78243656 it looks like there needs to be a script that is run to test this. Re-assigning to @kcondon to properly QA this.

**Comment by posixeleni** [comment]
Correction: Was able to test this in demo rather than dvn-build and works as expected. Closing.

![image](https://cloud.githubusercontent.com/assets/5013837/6723550/0508473c-cdc0-11e4-83e4-0ef1c8959c72.png)
