### ISSUE TITLE
Title Tags: Not Appearing in the UI 

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1567]
From UI review on 2/26. Title tags don't appear in the UI at all. Will need these for icons in the search/browse cards as more are added in the upper right.

**Comment by mheppler** [comment]
Examples of title tags that should be added:

- "log in" : "Log into your Dataverse Account"
- "sign up" : "Sign Up for a Dataverse Account"
- "search guide" : "Finding & Using Data - Dataverse User Guide"
- "dataverse management (read more about adding data in the user guide)" : "Dataverse Management - Dataverse User Guide"

**Comment by mheppler** [comment]
This was a high-level ticket, covering the title attributes for links across the site. All of the links in the bundle, for pages like User Guides, Best Practices, etc., have the title attribute, to help improve accessibility and usability. A majority of the links in the XHTML across the app, do as well. Any stragglers found can be fixed with a new ticket, in a future release.

**Comment by sbarbosadataverse** [comment]
Kevin can you please clarify what I'm supposed to be looking for?
