### ISSUE TITLE
Alias is not case sensitive

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1601]

**Comment by scolapasta** [comment]
Let's discuss Monday on where the logic should be.

**Comment by sekmiller** [comment]
To test - you shouldn't be able to add/edit a dv so that it's alias matches another dv's alias with a different case i.e. "RooT" shouldn't pass validation.  Also if there are matching aliases (with mismatched case) in the db you'll get a 404 error if you try the link.  You'll have to manually change them in the DB.

**Comment by posixeleni** [comment]
Tested and works as expected:
![image](https://cloud.githubusercontent.com/assets/5013837/6713967/261ed67e-cd6c-11e4-9f78-ea7789e83b7d.png)

**Comment by kcondon** [comment]
OK, UI prevents dupes of varying case and 404 occurs if same exists in db. Closing.
