### ISSUE TITLE
Custom Fields Migration: Create Two More Custom Metadata Blocks

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1607]
@pdurbin before you put in a schema.xml change and db drop for #1597 I need to also put in these two new metadata blocks that will be necessary for @ekraffmiller custom fields migration to be completed. Will try to complete this by end of day tomorrow.

It will be a **Digaii** block and a **CHIA** block.

Unrelated to Ellen's custom field migration is the **PSI** Metadata block that I will check in as well.

**Comment by pdurbin** [comment]
@posixeleni ok, it turns out the change you made for #1597 didn't require a Solr schema change so I went ahead and merged that commit ( eb101e8  ) into master per my comment at https://github.com/IQSS/dataverse/issues/1597#issuecomment-77598311

For **this** ticket, please just let me know which non-master branch you commit the change to. If it's easy enough I would recommend simply making a new branch for this ticket but it's really up to you. You can use the branch you started for the other ticket if you want.

**Comment by posixeleni** [comment]
Related to #1452 @pdurbin this is checked into a different branch (metadata-facets-beta14) and since these are new metadata blocks I am assuming it will need a schema.xml and db drop.

**Comment by pdurbin** [comment]
@posixeleni I updated the Solr schema in 24d19ca based on your commit at 4110b4d but I did not yet merge to master (rather, I pushed to the branch you've been using: https://github.com/IQSS/dataverse/commits/metadata-facets-beta14 ) because the following things jumped out at me as strange:

- "Source" and "Variables" are probably too generic. We changed "type" to "astroType" in #485 for disambiguation.

- "Nmero"? "Ttulo"? I assume the accents were dropped on purpose?

Passing back to you for comment. @scolapasta please feel free to jump in if you know more about this since @posixeleni is away at a conference.

**Comment by posixeleni** [comment]
@pdurbin please go ahead and commit these changes so we can go ahead and have these Dataverses try out

The field names that you refer to as generic were developed by CHIA and @sbarbosadataverse and these facets would only be visible in the CHIA Dataverse so I think its fine to have them as generic in the field_title display but I will change the field_name in the db to make sure its unique in the backend.

Secondly, the field_names that you mention had letters dropped is on purpose since this is in the backend and reflect the custom field names we stored for them in 3.6

**Comment by posixeleni** [comment]
Back to you @pdurbin... thanks for spotting those issues. I have to get back to the conference but hope I can help with anything else.

**Comment by pdurbin** [comment]
@posixeleni the new commit is looking better but I'm still seeing "Ttulo" over and over (36 rows, looks like) under `#controlledVocabulary 	DatasetField`:

https://github.com/IQSS/dataverse/blob/0c1aafaf69af40a9cb45e30f0e8faf2e4c8bc616/scripts/api/data/metadatablocks/customDigaai.tsv

Can you please take a look?

**Comment by posixeleni** [comment]
@pdurbin in my haste I forgot to update the controlled vocabulary section. Fixed this.

**Comment by pdurbin** [comment]
@posixeleni This is looking better. Thanks! I merged it with master. Passing to QA.

**Comment by posixeleni** [comment]
Seeing these new custom blocks in dvn5
![image](https://cloud.githubusercontent.com/assets/5013837/6713692/73ef9fde-cd6a-11e4-8f13-51147287e8da.png)

As expected these custom blocks are hidden in dvn-build unless they are associated with a specific dataverse(s).
