### ISSUE TITLE
Index: Files are not indexed on dataset create but ok on index all.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1628]
Files are not being indexed on dataset create but are on index all:
create dataset, go to dataverse, see dataset but 0 files.

**Comment by pdurbin** [comment]
I haven't confirmed this bug personally but my guess is that it's a result of making indexing async per https://github.com/IQSS/dataverse/issues/702#issuecomment-77287316

**Comment by scolapasta** [comment]
I created a dataset with a file and I do see it being indexed. Can we retest?

**Comment by pdurbin** [comment]
I'm seeing the same as @scolapasta. I can't reproduce the bug. I tried adding the file while creating the dataset (instead of a "save" in between). We are considering touching the async code but haven't yet.

**Comment by pdurbin** [comment]
Ok, I can reproduce this. You have to publish the dataset to see it and you have to have the unpublishedDataRelatedToMeModeEnabled boolean set to true, which we do at the moment.

The problem was that the file was being indexed with the wrong string:

    "discoverable_by_ss":["Published"],

I changed it to the correct string:

    "discoverable_by_ss":["group_public"],

@kcondon if you could re-test, I'd appreciate it.

**Comment by kcondon** [comment]
OK works, closing
