### ISSUE TITLE
Account Terms of Use: Add Account to Tool Tip

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1655]
is this an @mheppler or @posixeleni thing?

**Comment by mheppler** [comment]
@eaquigley -- not sure what you are asking to be done.

Do you want the word "account" added to the tooltip description, "Outlines how this data can be used once downloaded." that is linked from the bundle to the "Terms of Use" label on the Sign Up page?

**Comment by eaquigley** [comment]
@mheppler Please add Account before the Label (currently says Terms of Use, change to be Account Terms of Use). Also, that tool tip description needs to change because it isn't about how this data can be used once downloaded, this is about what a user is agreeing to when creating an account. I'm guessing it is pulling the description from the other Terms of Use tooltip on the License + Terms page.

Also, need account in "I have read and accept the Dataverse Terms of Use as outlined above." should say, "I have read and accept the Dataverse Account Terms of Use as outlined above."

**Comment by mheppler** [comment]
Made the label and help text account specific in the bundle for the Account Terms of Use include.

Passing to @eaquigley to review my attempt at account specific tooltip for the label.

"Outlines how you may use this site and the datas on it."

**Comment by eaquigley** [comment]
updated tool tip. passing to QA to close.

**Comment by sbarbosadataverse** [comment]
"account" in both field name, in text box, and tool tip updated as below. screen shot attached
was added to terms of use for login page--which as described above is "Also, that tool tip description needs to change because it isn't about how this data can be used once downloaded, this is about what a user is agreeing to when creating an account."

https://www.dropbox.com/s/di05cd81vbw71ni/Screenshot%202015-03-19%2011.56.29.png?dl=0
