### ISSUE TITLE
Dataset Page - Includes + Multiple Pages

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1665]
Coming in at over 2300 lines of code, the dataset.xhtml file should be split up into includes, and multiple pages (ie: new page for Edit Dataset and Upload + Edit Files, rather than editMode views).

**Comment by mheppler** [comment]
This also would allow for using PrettyFaces URLs for datasets.

From @scolapasta in an email dated 12/10/14:
> we want global ids for the dataset URL, both for pretty face (which like we said in the meeting on Monday had an issue with the file upload) or not pretty faces (though id will also work, visible URLs should not show them). 

Also see, related dataverse Theme + Widget file upload + PrettyFaces ticket #1126.

**Comment by mheppler** [comment]
Development for this high-end task has been started. The initial commit 87b5c659282d3727f418eab8dde521be9cdd2609 from @landreev is just the beginning of the work needed to break out the edit and upload workflows for dataset files.

The metadata edit view might be held off for a later release. A new issue (#2486) has been created for the PrettyFaces URL formatting.

**Comment by landreev** [comment]
@pdurbin also did some work related to this task, by isolating some of the files display functionality in its own xhtml include fragment. 
The next step now is to modify the dataset.xhtml page, to redirect to my editfilespage.xhtml when users click the "edit files" button (for the files selected via checkboxes). It looks like @sekmiller is working on it. 
Steve, you mind if I give you this ticket for now?

**Comment by sekmiller** [comment]
Leonid,

I’m also going to have to do some work on your edit data files page (editDatafiles.xhtml) since it refers to some terms of use and access before they were split out from datasetVersion.  Are you out of that for the time being?

Thanks!


On Sep 1, 2015, at 3:59 PM, landreev <notifications@github.com<mailto:notifications@github.com>> wrote:


@pdurbin<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_pdurbin&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=TnTMaRk7w3lQI_hyPJEbRtAKSelMZfFLydK9bhD7gfg&s=DVoYa18zqew39_at1HlcDi52oMU9Pt5dakr5XFwql7A&e=> also did some work related to this task, by isolating some of the files display functionality in its own xhtml include fragment.
The next step now is to modify the dataset.xhtml page, to redirect to my editfilespage.xhtml when users click the "edit files" button (for the files selected via checkboxes). It looks like @sekmiller<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sekmiller&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=TnTMaRk7w3lQI_hyPJEbRtAKSelMZfFLydK9bhD7gfg&s=l-meI6TCj65iDfXK02Yz8B5SxptTADV7Qf-AaisdgYc&e=> is working on it.
Steve, you mind if I give you this ticket for now?

**Comment by landreev** [comment]
Steve, 

Sorry - somehow missed your last question. I'm still working on the editDatafiles.xhtml; but feel free to make changes to it - I don't mind merging my changes if I need to. 
For now I just changed workingVersion.termsOfAccess to workingVersion.termsOfUseAndAccess.termsOfAccess in a couple of places ther, after you committed your Terms of Use changes. 

(also, there's a chance I'll be completely done with that page over the weekend)

**Comment by sekmiller** [comment]
Added bulk update of files (restrict/unrestrict, tags, delete)

**Comment by eaquigley** [comment]
Final updates for 4.2 with Edit Admin View Workflow:

- [ ] Download All taken away
- [ ] Download button is disabled till a file has been selected
- [ ] Edit Selected Files link goes away and is replaced by currently titled Bulk Updates button (change text to be Edit like mockups: https://iqssharvard.mybalsamiq.com/projects/filesprovenancefacetsfilter-dataverse40/grid

**Comment by kcondon** [comment]
OK, discussed with Mike and Liz about what this ticket meant in terms of scope of testing since there are other UI related tickets. This ticket will cover the workflows identified by Liz' doc:

https://docs.google.com/document/d/1wyJe2J1RNg-zs24YTGHqOwd1YyhwqjRRMBgtw6mWMOc/edit?usp=sharing

These have been tested so I will close the ticket.
Remaining testing includes:
Verifying UI against mockups, testing incomplete work (download selected), and individual issues that were reported.

Closing.
