### ISSUE TITLE
Citation for Tabular dataset

### ISSUE THREAD

**Issue by mercecrosas** [IQSS/dataverse#1682]
We need to display the citation for each tabular dataset, as we had in 3.6 (including UNF and file name in the citation).

**Comment by mcrosas** [comment]
I had not noticed that we already offer a "Data File Citation" option under the Download button. So, this is fine for 4.0. But I will leave this issue open, because we should review whether we provide a user friendly View Citation option (similar to the citation display for a dataset). Moving to another release.

**Comment by mheppler** [comment]
@mcrosas -- did we deliver this feature in 4.6 with the file pg?

```
King, Gary; Soneji, Samir, 2011, "Replication data for: The Future of Death in America", hdl:1902.1/16178, Harvard Dataverse, V12; bmi.smooth.tab [fileName], UNF:5:xV9hRaQykyqAwxxk9sX8nQ== [fileUNF] 
```

**Comment by mcrosas** [comment]
I think that the citation for an individual file should include the "dataset UNF" (that is, the total UNF for all the files in the dataset, which is part of the regular data citation), plus the UNF of the individual file. This citation seems to be missing the dataset UNF:
https://dataverse.harvard.edu/file.xhtml?fileId=2326305&version=7.0

I would ask @thegaryking to confirm this for an individual file.

**Comment by pdurbin** [comment]
@mercecrosas do you plan to ask him or do you want someone else to?

**Comment by pdurbin** [comment]
Related:

- #5988
- #7328
