### ISSUE TITLE
Published Studies Showing Up In "My Unpublished Data"

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1686]
@eaquigley and I caught this during a demo with CfA yesterday on the demo site.

![image](https://cloud.githubusercontent.com/assets/5013837/6690262/efaa9316-cc95-11e4-911b-a5c787e58c0e.png)

@scolapasta please assign to the appropriate developer to fix

cc/ @kcondon

**Comment by scolapasta** [comment]
This is only occuring for a supruser (since the search must not be linking to the permissions documents in solr). For tis tab it should do that - but that can be a post 4.0 issue.

**Comment by pdurbin** [comment]
> since the search must not be linking to the permissions documents in solr

See superusers bypass all Solr permissions at #1125 and ac22c89 for details. Originally I called a findSuperusers (plural) method and gave each superuser explicit permission. Then @scolapasta and I decided to change it to simply bypass the permission docs entirely. Note that superusers can not use the experimental configuration of the Search API I'm working in in #1299 because they get the permission documents in their search results (since they don't do a JOIN against them).

So yeah, superusers have special rules. And they bypass the permission system. We shouldn't even be using those accounts much, I would think.

**Comment by pdurbin** [comment]
@mheppler and I just discussed this. I'm wondering if for superusers if we should call it something other than "My Unpublished Data". For superusers it's really "All Data" and there's no difference from regular browsing from the home page.

> So yeah, superusers have special rules. And they bypass the permission system. We shouldn't even be using those accounts much, I would think.

On a related note, last night @scolapasta and I were spitballing the idea of making the superuser boolean something you could turn on and off. Maybe one boolean set to true if you're **able** to become a superuser and another boolean to indicated whether your not you're in superuser mode or not.

**Comment by sbarbosadataverse** [comment]
@kcondon 
since my unpublished is now going to be "my data" does this make sense to test?

**Comment by sbarbosadataverse** [comment]
created a dataverse in build, added two datasets, 1 published, one unpublished. when I go under "my data" and click on the "published" "unpublished" nothing shows up for results. I also can't see any results for dataverses I created and published under "my data" although I have one.

**Comment by kcondon** [comment]
@sbarbosadataverse  Can you try this again? I had misconfigured the build machine so it wasn't working properly.

**Comment by sbarbosadataverse** [comment]
looks good!
