### ISSUE TITLE
License + Terms Tab - Empty "License" for Migrated Dataset

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1691]
Migrated datasets on demo have empty License and Terms of Use.

If these datasets have only "3.6 Dataverse Network" terms, it should be "CC0", otherwise it should display "No license has been selected for this dataset."

Review with the Berkman peoples to confirm all this.

**Comment by eaquigley** [comment]
Can we legally change these datasets to be CC0? Are the 3.6 Dataverse Network terms equivalent to CC0? 

cc: @mcrosas

**Comment by mcrosas** [comment]
You are right that we should be sure that won't be a problem. Can you ask
Berkman again?

The Dataverse Network Terms said two main things:

1. If you use the data, you should cite it. (this is now part of the "norm"
and Berkman and many others agree that it shouldn't be part of a license or
terms of use)
2. If the data refers to human subjects, you wont' try to identify it. (as
Bekrman and others agree that this should not be something to ask in terms
of use, this will be handled by DataTags. Users should not deposit
identifiable data at Dataverse meanwhile).

So, from a logical sense, if we decide to remove these terms of use because
they were not valid, we could then, as a "publisher or distributor" of the
data decide on the CC0  (it's basically changing the terms). But Berkman
might suggest we leave the license empty for now, and then we encourage
people to change it to CC0 (there might be legal reasons about this that I
don't know).




Mercè Crosas, Ph.D.
Director of Data Science, IQSS
Harvard University
http://datascience.iq.harvard.edu

On Tue, Mar 17, 2015 at 5:41 PM, Elizabeth Quigley <notifications@github.com

**Comment by posixeleni** [comment]
If my memory serves me right, I do recall the Berkman team suggesting that we keep the Terms as we had them but ask users to go and update their terms for their datasets. Would we be able to set the terms for datasets at the Dataverse-level though?

-Eleni

**Comment by mcrosas** [comment]
I think there is some confusion, here is a summary:

In 3.6 there were:
- Dataverse Network Terms of Use (we set them and could change them as we
wanted, based on any changes from Harvard Dataverse policies): Apply to all
datasets.
- Dataverse Terms of Use: Admins of a Dataverse could set ToUs for all
datasets in their dataverse.
- Dataset Terms of Use

In 4.0:
- For now, we only support dataset Terms of Use
- The Dataverse Network Terms of Use go away, and should disappear from all
datasets.
- Dataverse Terms of use become dataset terms of use for all datasets in
that dataverse

Unfortunately we don;t have a way to easily set Terms of Use for all
datasets in dataverse. We'll probably need this in a later release, but we
could for now do this at the DB level.

In my opinion, all datasets that had ONLY Network terms of use in 3.6
should have now CC0. But, again, we should confirm this doesn't violate
anything.

**Comment by posixeleni** [comment]
Thanks for clarifying, Merce. We are meeting with Berkman on Monday the 23rd so we can make sure we get clarification from them then.

--
Eleni Castro
Research Coordinator, Data Acquisition and Archiving, Data Science
IQSS, Harvard University
http://www.iq.harvard.edu/people/eleni-castro

We're redesigning Dataverse and want your feedback! Please check out our Beta Site.<http://dataverse-demo.iq.harvard.edu/>

**Comment by ekraffmiller** [comment]
@mheppler @eaquigley , what is the exact text wanted here for CC0?

**Comment by kcondon** [comment]
Closing since behavior is correct.
