### ISSUE TITLE
Dataset Version Details - Cleanup Table + Popup Layout

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1701]
Versions Tab
- [x] Change "Show Differences" and "Show Details" to "View..."
- [x] Add icon to "View Differences" button
- [x] Move "View Differences" button to right for consistency?

Popup
- [x] Cleanup width, add “Done” button, remove “Viewing: ...“
- [x] Improve messaging of popup when no versions are selected.

**Comment by eaquigley** [comment]
Looks good to me. @mheppler One thing though is that once you've selected a version, it is really quite hard to see the view details link that is now in white, only matters that it is hard to see because it is still a clickable link. Could we have it stay the blue link color instead of turn to white.

**Comment by mheppler** [comment]
@eaquigley -- That is a CSS issue that was fixed and can be seen with a SHIFT + reload of dvn-build, in your browser to clear your cache and go to the server to get the latest and greatest stylesheet.

**Comment by eaquigley** [comment]
@mheppler -- ahhh, got it. okay. closing ticket. everything looks great.
