### ISSUE TITLE
Allow For Anonymous Peer Review of a Dataset for Journals

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1724]
Palgrave Communications journal and many other journals have a blind / anonymous peer review process for their journal articles and any underlying research data. To support this in Dataverse we would need to allow for datasets to hide the names/affilitation of authors for an anonymous peer review of data to take place. 

This is somewhat related to #1012

**Comment by jeisner** [comment]
This problem comes up increasingly in my subfield of computer science.  I'm an action editor on 2 journals and am also often involved in setting the reviewing and publishing practices for our conferences.

Often, an author would like to point to their dataset from the double-blind review version of a paper.  I think it would be great if Dataverse could provide a standard solution that we could recommend to our authors.  To my knowledge, no one in my community is using Dataverse yet, so this would expand the user base.

A few issues:

* To preserve anonymity, the authors should not use their own institution's Dataverse.  Rather, each journal or conference would have to recommend a *specific* Dataverse installation such as https://dataverse.harvard.edu.  Would that be acceptable to the maintainers of that installation?

* **Anonymity** is what's important to the journals.  **Privacy** is an orthogonal issue (see #1012).  Sure, some authors may want their datasets to remain at a private (unguessable) URL until the paper is published.  But some authors would be delighted if people are able to discover and use their dataset right away, as long as the journal's anonymity policy isn't broken.

* Sometimes at present, an author is in a bind, because they want to point to their own dataset that has already been released *non*-anonymously, in a way that would make it pretty obvious that they're an author.  (The biggest case is where the author is submitting a new paper that announces the release of version 2.0.)  

Thus, my suggested design:

* First, a user creates a dataset at Dataverse A in the usual way, with their name attached.  The dataset could be private (#1012) or discoverable -- that's up to the user.

* When submitting a paper to a journal that recommends the use of Dataverse B, the user requests an anonymous URL at Dataverse B that is just an alias for the dataset stored at Dataverse A.  Anyone who accesses the data through this anonymous URL will be able to see all the same data, but will not be able to see the names of the contributors or commenters.

* The anonymous URL might expire after a stated period.  (This is especially useful if the implementation actually copies any data from Dataverse A to Dataverse B, rather than just tunneling through B to A.)

* In an initial version, for simplicity, you could just require B=A, although that's not ideal.

Thoughts?

**Comment by jeisner** [comment]
By the way, I would actually like to use Dataverse *now* for an anonymous submission, and I wonder if the following stopgap trick would work for the moment:

Suppose I create an account with username "Anonymous Author", and upload the data.  If I did that, would my email address be masked, or would I have to create an email address that can't be traced back to me? 

After publication, would I be able to change the anonymous account to have my real name and email -- or better yet, transfer ownership of the dataset to an existing account with a real name and email?

**Comment by pdurbin** [comment]
@jeisner I see you left your latest comment on April 28th and a day later Elizabeth replied with the following message at https://groups.google.com/d/msg/dataverse-community/sJiqJMQ32Rw/cQ4ixsjpBAAJ

---

Hi Jason,

There's definitely a way for you to do this since you need to be able to do it now. You could create an account using your email address and the username being the username you want but have the Given Name, Last Name fields be populated with Anonymous Author. It's more important to have the name be that because in the versions tab, it will list the name, not the username, of the person who has edited the dataset. Email addresses for dataset contacts are hidden behind the email button at the top of the dataset page so those accessing your dataset wouldn't see it.

Doing it this way, you wouldn't have to transfer the dataset to another account. All you would need to do is after the double blind review process is over, change the Author field in the dataset and update your name for your account. No need for another account if you do that.

If the dataset is published with Anonymous Author as the author and username, you will need to make a new version and publish it so it has the correct metadata. You can also create a new version to make any edits the reviewers suggest.

Hope that helps! Please let me know if you need further assistance or clarification.

Cheers,

Elizabeth

p.s. One thing I forgot. If you wanted to do a trial run to make sure it all works they way you want it to, we have a demo site available to all at: http://demo.dataverse.org

---

Then you wrote "Elizabeth - Thank you very much for the quick and helpful response!   -jason". I'm hoping this means that this proposed workaround is ok for you for now.

**Comment by jeisner** [comment]
Thanks for following up, Philip.  (We ended up just using the action editor as an anonymous channel in case the reivewers wanted to look at the dataset, which they didn't.  The paper is now published and the dataset is hosted on Dataverse.)

**Comment by pdurbin** [comment]
@jeisner I'm glad to hear you're all set. When you get a chance, please let me know what an "action editor" is. 😄 Congrats on publishing. I *think* I found your dataset at http://dx.doi.org/10.7910/DVN/8ZT5KF and I have a bit of feedback for you but I'll use the "Email Dataset Contact" button since this is all getting off topic for this issue. 😄

**Comment by jggautier** [comment]
Jonathan Bohan at CISER emailed about a user of their planned Dataverse installation needing a feature like this:

> [The user] is looking for a way to provide completely anonymized data for anonymous peer review, that is, no identification of the creator or institution - and wanted to know whether Dataverse could do it. Now, since creator and contact are required fields, I would guess we would have to include dummy information in those fields ("Unidentified" as name, etc). But I'm not sure if there is a way of setting up a dataverse without identifying the INSTITUTION itself - if it were in our dataverse, that would be a pretty obvious tell. I was hoping maybe you would have some thoughts on this.

I pointed him to this issue and [the post on Google Groups](https://groups.google.com/forum/#!msg/dataverse-community/sJiqJMQ32Rw/cQ4ixsjpBAAJ) and he realizes that "the need for the institution to remain anonymous as well as the author adds a wrinkle of complexity."

> A thought (completely coming off the top of my head here, I'm sure there are complications I'm not thinking of) would be to have a sort-of temporary Dataverse - one that would be used specifically to house these datasets which would expire after some term - say, a year - once the review process was over, the data could then be uploaded to the institution's own Dataverse. Of course, that would need to be hosted somewhere and then cost issues would be involved. It seems it would be a desirable service, however.

**Comment by pdurbin** [comment]
@jggautier yes, that post from Liz is the one to read for now. Do you think we should document that workaround in the User Guide?

**Comment by jggautier** [comment]
It would be great to document this workaround and in the same space mention circumstances where this workaround doesn't work.

Looking at the guides though, I can't imagine where to put something like this. In the appendix? @dlmurphy is there a place or plans for a place to document a workaround like this?

**Comment by pdurbin** [comment]
@jggautier I'm happy to defer to @dlmurphy on wherever he thinks the workaround would be best documented but I'd like to suggest that a link to the workaround could at least be mentioned in a future version of the place where we document the Private URL feature: http://guides.dataverse.org/en/4.7/user/dataset-management.html#private-url-to-review-unpublished-dataset .

**Comment by jggautier** [comment]
Describing how to deposit a dataset in a way that hides info about the depositor (in cases where the reviewer of the dataset shouldn't know who the author is), Elizebeth wrote that:

> Email addresses for dataset contacts are hidden behind the email button at the top of the dataset page so those accessing your dataset wouldn't see it.

On the dataset create/edit form, the tooltip for the email label lets the depositor know this:

<kbd><img width="501" alt="screen shot 2019-02-27 at 3 07 46 pm" src="https://user-images.githubusercontent.com/18374574/53519519-7a72cb80-3aa1-11e9-93b8-333ab60d6fa3.png"></kbd>

But the email is in some of the metadata exports (DDI, "Native JSON", and OAI-ORE) unless the installation uses [the "exclude email from export" setting where contact emails aren't put in the metadata exports](http://guides.dataverse.org/en/4.11/installation/config.html#excludeemailfromexport).

For installations that include emails in the metadata exports, the depositor looking to hide info that could expose her identity may not realize that the contact email is in the metadata exports. If we promote the workaround for hiding depositor identifying info, I think we should make sure that the depositor knows that the contact email is exposed in the metadata (e.g. by letting the depositor know through the tooltip and mentioning it in anywhere we document this workaround), that way the depositor can take extra steps to mask her identity (like using a safer email address) or decide not to deposit the dataset in that installation.

Because depositors don't often come back to the dataset to add the correct info when it's safe to, and self-curated installations may not be able to check and curate these datasets often, this workaround will become more of a problem if installations see an increase in the number of datasets submitted as part of double blind reviews.

**Comment by Duhem123** [comment]
In addition to the above discussion: If the Private URL feature is further developed for the purpose of blind peer review, it would be useful if the containing dataverse and breadcrumb navigation with its name were not displayed as well. In this way, the dataset would not have to be created in the root dataverse.

**Comment by pdurbin** [comment]
@Duhem123 good point.

I also wanted to point out to all that there was a recently lively discussion in a maiilng list thread called "blind peer review of dataset" at https://groups.google.com/d/msg/dataverse-community/6tG4i1Vb880/27voi_JVCQAJ

Please keep the feedback coming!

**Comment by adam3smith** [comment]
We're also now facing the need to ensure private _and_ anonymous peer review more frequently and would probably be looking at this some time in the next 3-6months. The curator option described by @philippconzett in the linked google group works, but is clearly not ideal. Here's my current summary of what I think we'd want and people have pointed out:

1. There should be an option "anonymize for peer review" -- could be a separate button or could be a choice when creating a private URL (or something else)

2. That option should do the following things:
- Hide the author, depositor and contact, their emails and affiliation in both metadata and citation
- Hide the depositor and any other contributors from the version tab (or hide the version tab entirely)
- Hide the breadcrumbs and dataverse information of the containing dataverse(s)
Some other things to consider, useful but non-essential
- Hide funding information (grant numbers can be looked up) as well as related publications (which may contain authors)
- flag any files that include the name of one of the contributors. We have seen contributor files in metatags and even OCRd on a archive request note on a scan...

To consider: Would this version exist separately from the existing data project, i.e. is there still a non-anonymous version around? That would be the most elegant solution, but might also be harder to do.

cc @qqmyers

**Comment by philippconzett** [comment]
Thanks, @adam3smith, I think you covered all the crucial issues. Since my comment in the Google group we have spelled out the routines on how to handle DataverseNO datasets that are part of double-blind peer review, and they pretty much cover the same issues as Sebastian mentioned (see the the instructions on the metadata field _Related Publication_ in our [Deposit Guidelines](https://site.uit.no/dataverseno/deposit/deposit-your-data/#enter-metadata) and [Curator Guidelines](https://site.uit.no/dataverseno/admin-en/curatorguide/#metadata)). The only thing that currently is not covered is the issue about anonymizing the collection (sub-dataverse) the dataset is part of. We have been discussing whether we should create such anonymized datasets either in the root collection or in a collection dedicated to datasets that will be part of double-blind peer review. We're looking forward to Dataverse providing complete support for anonymization of datasets for double-blind peer review. This will make the curator's life much easier in such cases. Thanks!

**Comment by TaniaSchlatter** [comment]
[Slide doc](https://docs.google.com/presentation/d/1ySzkynVT4-Okd9DrmELpzkFvv6KZ5lQYogJUKr6_bSE/edit?usp=sharing) with screen shots showing the feature implemented in the Qualitative Data Repository.

**Comment by jeisner** [comment]
Great to hear, thanks!  
Q: Once a version has been published, what happens with the anonymized URL?  Someone may find it in an older discussion and try to follow it.  Does it redirect?

**Comment by philippconzett** [comment]
Great work! Would be nice to see a live demo of the QDR feature. Maybe at a community call?

**Comment by pdurbin** [comment]
> Q: Once a version has been published, what happens with the anonymized URL? Someone may find it in an older discussion and try to follow it. Does it redirect?

@jeisner I'm not sure if the behavior has changed in this pull request or not but with existing Private URLs as of Dataverse 5.5 the Private URL does not redirect after the dataset has been published. I just published the dataset behind the following Private URL on the demo site and now when you click it you get a 404 as in the screenshot below: https://demo.dataverse.org/privateurl.xhtml?token=17eecae0-8c3e-4bef-b65f-5a4e4ee86847 

<img width="967" alt="Screen Shot 2021-06-28 at 10 16 42 AM" src="https://user-images.githubusercontent.com/21006/123652327-340d1300-d7fa-11eb-8438-b1754a08e7e0.png">

**Comment by qqmyers** [comment]
The PR doesn't change what happens after a PrivateURL is disabled/deleted. FWIW: Currently, Dataverse doesn't keep track of old privateURLs in the db, so redirects would require some redesign. I'm not sure that would be that useful overall though:

- if a private URL is disabled prior to publication, it should still go to 404 (as the dataset isn't public)
- for review cases, should reviewers be keeping review materials and links beyond the review period?
