### ISSUE TITLE
Getting a New Draft after Clicking Publish

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#1734]
(This is with the latest code/solr/rebuilt db on my local machine)

### Steps to replicate issue.  
- Create New Dataset with 1 file
- Publish Dataset (and associated dataverse)
- Go to home page
- **2 new files** are showing: 1 published + 1 Draft

\cc @scolapasta

**Comment by pdurbin** [comment]
Good catch @raprasad 

This bug is due to a change I made in cleaning up Solr fields in #1314 where I made `parentId` non-searchable. This means that we no longer get any matches here, for example:

passing this Solr query to find draft files to delete: rows=2147483647&q=parentId%3A10&fq=id%3A*_draft

In #544 @scolapasta had suggested *not* doing a Solr query to figure out which drafts to delete so maybe I'll change that now. It would probably be a better fix than making parentId searchable... I don't *think* we want parentId to be searchable. parentId is the id of the entity that is the parent of the Solr document in question. Above, a Solr document with an id of "datafile_12_draft" has a parentId of "10" because it's attached to dataset with an id of 10.

**Comment by pdurbin** [comment]
I pushed a fix (43911e4) for this bug and #544 into a new branch because master is not compiling.

@scolapasta can I please revert master to a commit that compiles? I branched from one commit back (5e890c6a34330e8cfc4756b636f50aee7fb39756) so I would revert 8f53c297c0b09caf901f6c7005631bc8dc67e593. Then would merge the commit above into master.

**Comment by pdurbin** [comment]
I just merge my fix into master. Passing to QA.

**Comment by kcondon** [comment]
Fixed, only one file showing. Closing.
