### ISSUE TITLE
File Upload: Cannot generate thumbnail for .tif files.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1738]
I've uploaded a couple different tif files and though they are recognized as TIFF Image, there is not generated thumbnail and no error in the log file.

**Comment by landreev** [comment]
Yeah, I can reproduce this - and it's not working, even on the TIFF files I originally used to test the feature. 
Not exactly a show stopper, but annoying. Hopefully it's something easy to figure out.

**Comment by landreev** [comment]
Here's what's going on: 
In order to handle image formats other than the basic JPG, BMP, and a couple of others, we ship the app with JAI - Java Advanced Imaging library. However, it appears that the only way to actually make these extra image codec plugins available at run-time, with Glassfish 4, is to put them into Glassfish's "extension library" path. That is glassfish/domains/domain1/lib/ext. 
So this needs to be done on any system where we install: 

cd /usr/local/glassfish4/glassfish/domains/domain1/
cp applications/dataverse-4.0/WEB-INF/lib/jai_imageio-1.1.1.jar lib/ext/

(and restart glassfish). 
Ideally it should be part of the installer process. 

I'm seeing that on dataverse-demo this was done, in the old Glassfish directory - glassfish4_0. 
I absolutely don't remember doing it... But somehow it looks like it was part of our setup early on. Which explains why tiff thumbnails were working before.

**Comment by sbarbosadataverse** [comment]
Thumbnail generated for .tif file

![s9kw4zx1fcvnh6y7lvweggeofh-w75ibms041z1dh0u](https://cloud.githubusercontent.com/assets/8322346/6987490/6e252d3c-da15-11e4-8cd0-ec3636663cec.png)
