### ISSUE TITLE
Templates: custom templates created in 3.6, recreated/migrated in 4.0

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#1766]

**Comment by sbarbosadataverse** [comment]
https://docs.google.com/spreadsheets/d/1Y_y5SbxbZZrCLQOIpTIar236BFjQ18V2hYdX6ZKAjFg/edit?usp=sharing

**Comment by posixeleni** [comment]
@scolapasta is there any way for us to get access into 3.6 to view what is in the actual templates ? 3.6 is currently in read-only mode.

**Comment by posixeleni** [comment]
I now have access to the templates in 3.6 and am recreating them in 4.0

**Comment by posixeleni** [comment]
Working on templates here: https://docs.google.com/spreadsheets/d/1Y_y5SbxbZZrCLQOIpTIar236BFjQ18V2hYdX6ZKAjFg/edit#gid=0

**Comment by posixeleni** [comment]
Completed templates given the current functionality available and left notes in the spreadsheet: https://docs.google.com/spreadsheets/d/1Y_y5SbxbZZrCLQOIpTIar236BFjQ18V2hYdX6ZKAjFg/edit?usp=sharing

Any items in the spreadsheet with a red box indicates that I was not able to 100% complete the template copying due to us not having the Terms of Use and Terms of Access in the templates for 4.0.

Will close this ticket and make a note in this one https://github.com/IQSS/dataverse/issues/1229 that templates need to be revisited to add terms of access and terms of use for dataverses that had this filled in 3.6.
