### ISSUE TITLE
Review dataverses that have no admin

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1782]
Aliases:

GAS
social

**Comment by scolapasta** [comment]
3.6 query to get this list:
select id, alias, creator_id from vdc where id not in (
select vdc_id from  vdcrole 
where role_id=3
);

**Comment by posixeleni** [comment]
@scolapasta sorry but this ticket is a bit hard to understand what you need me to do. Can you please explain this to me when you get the chance?

**Comment by scolapasta** [comment]
There are two dataverses that in 3.6 have no admin and will be migrated a such. @mcrosas asked that we review with them if this is the appropriate state or do we need to set someone to as admin.

**Comment by sbarbosadataverse** [comment]
Have contact CfA on GAS dataverse and PSI on the social dataverse

**Comment by sbarbosadataverse** [comment]
@scolapasta 
Dana will be added for PSI (her user account doesn't show up yet under permissions)-when will we be able to actually update the site with users? thnx

**Comment by sbarbosadataverse** [comment]
Hi Sonia,

I'm good, glad it is warmer! I had a conversation not too long ago with Eleni about admin access. Our permissions should still be active, right? We can also consolidate to one admin account, which might be actually easier for us to use.

Thanks!
Chris

Hi Sonia and Chris,

Because I am now another step removed from Harvard, and because I really don't want to have people asking me to admin their accounts for them unless it is related to the Journals, I do think consolidation is appropriate. If it is easier for Wolbach, then by all means, consolidate!


 - Gus

**Comment by sbarbosadataverse** [comment]
@scolapasta 

I am seeing a list of admins and contributor for the GAS dataverse so I'm not sure why it's on this list:


![vwtt6jpa78nsgtwqmfxokmt8sbgfqb0fbmnmik007qg](https://cloud.githubusercontent.com/assets/8322346/7140896/1a0f8ac8-e29c-11e4-89ea-5eb58443d77b.png)
