### ISSUE TITLE
Dataverse - Views, Downloads, Citations, Shares

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1808]
Add counting metrics like views, downloads, citations, shares to the top of the dataverse page.

**Comment by kcondon** [comment]
This has been requested by several users for which we manually generated counts, see RT tickets: 227143, 227255:

227143:
Would love to see total #s displayed on the main page of the Dataverse and
sounds like this is in the works. Was a good feature of the old interface,
in my view. also, downloads are a bit buried now within the study pages
instead of visible from the main page (with list of studies)... but I
imagine you have a lot to work on! Just mentioning in case that's a
possibility in the future.

227255:
it’s one of the key ways we “sell” Dataverse for the journal.  By telling authors about all of the visibility
they get by putting their studies in our journal’s Dataverse, we get nearly universal compliance with our policy.   These download metrics are also extremely valuable to us as we try to get other journals and societies to comply with DART standards like our journals.  To be able to say that we
have had (for example) 15,000 downloads from our journal’s Dataverse is very impressive to societies, publishers, and other journals — they know that those downloads translate into more visibility for their journal’s papers, as well as better social science.
 
So if there are any arms we can twist to get those metrics back on our journal’s website, that would be great.  Even better would be a dashboard for Dataverse users, where they could track overall downloads, and downloads of specific datasets.  I’m guessing that such a dashboard wouldn’t be 
extremely difficult to develop, given that I think your API would give access to those numbers.

**Comment by pdurbin** [comment]
This is for 4.2? In #2502 I suggested getting rid of "coming soon" if it isn't.

**Comment by posixeleni** [comment]
Spoke with @mcrosas that we may want to consider implementing the following for dataset-level metrics http://dlm.labs.datacite.org/

>Lagotto is an Open Source application started in March 2009 by the Open Access publisher Public Library of Science (PLOS). Lagotto retrieves data from a wide set of services (sources). Some of these sources represent the actual channels where users are directly viewing, sharing, discussing, citing, recommending the works (e.g., Twitter and Mendeley). Others are third-party vendors which provide this information (e.g., CrossRef for citations).

**Comment by mheppler** [comment]
Related to: Metrics: Display visualizations on dataverse.org #3230

**Comment by mheppler** [comment]
Related to, duplicate of issue **Dataverse metrics bar at sub-dataverse level #3527** and **Track views for Dataverses and Datasets #1969**.

**Comment by mheppler** [comment]
Closing as duplicate in favor of _Display Make Data Count use and citation metrics #5253_.
