### ISSUE TITLE
Performance: Dataset Versions Tab

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#1820]
Preview computation can significantly add # of queries (30%, 50% of queries, etc)  

These queries are the No.1 and/or No.2 issues on the Profiler.
#### Redo the Dataset Versions Tab.
- [ ] Do not pre-calculate version differences
- [ ] Set "View Details" to trigger same event as checking that selected version and previous version
- [ ] Save dataset version summary "note" for each published dataset
- DatasetVersion.java: https://github.com/IQSS/dataverse/blob/master/src/main/java/edu/harvard/iq/dataverse/DatasetVersion.java#L485
  - see   `DatasetVersionDifference dvd = new DatasetVersionDifference(this, dvTest);`
- dataset-versions.xhtml: https://github.com/IQSS/dataverse/blob/master/src/main/webapp/dataset-versions.xhtml#L43

---

Considerations:

**Comment by kcondon** [comment]
There are clearly performance issues affecting the versions tab in production but at times appear to be intermittent. They also appear to track with # version for dataset.

An example that is intermittent is #2635

**Comment by pdurbin** [comment]
The code has changed significantly in the three years since this issue has been reported. I don't think there's a lot of value in keeping this open. If the application is unacceptably slow in places, users tell us and we try to fix it. If you're one of of those users, please open a new issue! :smile: Closing.
