### ISSUE TITLE
Edit User Account: Revisit Logic around duplicate email

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#1835]
We are checking both the built in users and authenticated users for email matches.  In edit mode we say this is ok if the ids match.  This works in my local db after I manually add an authenticated user to the table.  just want to make sure it works when we let the world in.

**Comment by pdurbin** [comment]
I believe @sekmiller is talking about the `validateUserEmail` method in DataverseUserPage in the 3338-oauth-login branch as of b61897b and I think it looks ok. I'm going to pass this to issue to him for Code Review at https://waffle.io/IQSS/dataverse since we've been messing this is code as part of #3338. If there's something we should fix, now would be a good time. Please note that I copied this method into OAuth2FirstLoginPage and tweaked it a bit.

**Comment by pdurbin** [comment]
@sekmiller and I chatted briefly about this. It may have been an April Fool's joke. 😉

**Comment by sekmiller** [comment]
Code review complete. As noted there is some opportunity to reduce repetition of the validateUserEmail method which is in the backing bean of the DataversseUserPage and the OAuth2FirstLoginPage.

**Comment by kcondon** [comment]
Trusting code review for validation. Closing
