### ISSUE TITLE
Guestbook only showing "Cancel" option when prompted to complete fields/no "submit" option available

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#1843]
![bkg12mae6olrrktxixqt5lqbdztswrohzkrigz4d4qw](https://cloud.githubusercontent.com/assets/8322346/6966494/787106b0-d927-11e4-8f47-fe0238d371e9.png)

**Comment by sbarbosadataverse** [comment]
Could not reproduce again

**Comment by sekmiller** [comment]
I haven't been able to get this to happen

**Comment by sekmiller** [comment]
Tried multiple ways to recreate this.  Have not been able to do so.

**Comment by kcondon** [comment]
I was able to reproduce this the buy editing a stale view of a dataset and then saving:
1. In one browser, create/edit a dataset, submit for review, leave page open.
2. In another browser, publish the dataset.
3. In the first browser, edit the submitted dataset, still showing draft, change something, save, see error.

@eaquigley @mheppler @scolapasta 
I think the bug is when you click edit, it should take you automatically to the latest version to edit or say the version you are seeing is stale, do you want to edit latest? but that is more complicated. In any case the workaround for the case I describe is just refresh your browser to get the latest version to edit.

**Comment by sbarbosadataverse** [comment]
All set!
