### ISSUE TITLE
Email notifications as they get created

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1848]
We had logic for e-mailing bulk notifications, but decided to have it send the notification when it gets created, instead. Post 4.0, users will be able to configure how they want their notifications e-mailed.

**Comment by sekmiller** [comment]
Coding around creating email notifications complete.  The text of the emails is in the bundle if they need to be modified.  Verified that email is being created as expected, but didn't actually test send because the "no-reply" address not set 

Info:   Email as 
Hello, 
Welcome to Dataverse 4.0 Beta! Please take a look around, try everything out, 
 and check out our Google Group (https://groups.google.com/forum/#!forum/dataverse-community)
 to leave feedback.
Warning:   Skipping sending mail to mac@gmail.com, because the "no-reply" address not set.

**Comment by scolapasta** [comment]
if you run setup-optional-harvard, it will set the mail and can be tested (sent from support@dataverse.org). (You can also just run that individual curl command)

**Comment by kcondon** [comment]
OK, email is sent when notification is sent. Closing.

**Comment by colima** [comment]
@kcondon , I am also getting the same issue. The users are not getting any noifications even on password reset. I have checked usernotifications table and emailed is all FALSE. Any idea what I might have missed in my settings.
