### ISSUE TITLE
Create/Edit Dataset Page: Add Info, Error, and Success Messages

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#185]
---

Author Name: **Gustavo Durand** (@scolapasta)
Original Redmine Issue: 3597, https://redmine.hmdc.harvard.edu/issues/3597
Original Date: 2014-02-27
Original Assignee: Gustavo Durand

---

None

**Comment by sekmiller** [comment]
Leonid, can you put in the ingest success/failure messages? or point me in the right direction?
Thanks!

**Comment by landreev** [comment]
@sekmiller 
@eaquigley 
@scolapasta 
I just saw this ticket. 
I don't know how to do this easily. 
The whole thing about ingest is that it happens asynchronously, in the background. 
Once it completes, the next time the page refreshes it will show the tworavens icon next to it... so that should give them an idea that they can now explore the data, etc. 
But I don't immediately know how to detect the actual event, when the page sees the file as subsettable/explorable for the first time. 

It could be done (using the same websocket message that alerts the page, telling it to refresh).  but it would take work. So I suggest we live without it. At least for now.

**Comment by landreev** [comment]
@sekmiller
@eaquigley
@scolapasta 

OK, I was able to think of a quick way to trigger a success message on ingest completion. 
I slightly modified the message in the bundle (above): 
"The file(s) have been successfully ingested. You can now explore them with TwoRavens or download them."
- added "... download them in alternative formats"... (you can download a file before tabular ingest is complete). 
There's no message for ingest failure still; but I don't have any more time to look into this at this point.

**Comment by scolapasta** [comment]
Since the ingest failure does have the red triangle, we do make the user aware of this state. 

We may need to revisit once users have used the system more, but for now we can close this.

**Comment by eaquigley** [comment]
All of these messages appear and look good. Closing ticket.
