### ISSUE TITLE
Saved Search - do not link to search or link to files

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1884]
Since we currently don't support linking to files (and may not want to), we should not create any links for files.

Also, we can remove the files as something for the filter query when saving.

**Comment by pdurbin** [comment]
It sounds like this ticket is about two things:

Thing 1: If there's a hit on a file, don't ever link the parent dataset.

This is easy enough. It's just a backend change to skip any hits for files when making links. I pushed this change in a new branch in this commit: fee47b7

@scolapasta please let me know if you'd like this to be merged in.

Thing 2: After a user has done a search, explain that even though files matches the search (assuming they did), the "saved search" will **not** include datasets where files matched. This is much more of a usability issue since I think the user will expect that if a search matched something, it will be linked. After all, we're re-using the normal search interface to construct saved searches. Here's a screenshot:

![mali_dataverse_-_2015-04-06_11 23 07](https://cloud.githubusercontent.com/assets/21006/7006554/1ba6e48c-dc50-11e4-9535-6dee7d9832dd.png)

I guess we'll need to change the pop up to explain this. Passing to @scolapasta for comment.

**Comment by pdurbin** [comment]
From chatting with @scolapasta it sounds like the backend change at fee47b7 is the main one he's interested in (not linking datasets of files that match). We can sort out the usability issue later.

**Comment by scolapasta** [comment]
While there is still work to be done on this on the usability side, since this is a super user feature, it is OK for 4.0.

**Comment by suenjedt** [comment]
Test result: 
- Successfully linked the search results. DV and datasets were included; files were not shown in the destination collection/dataverse
- However, UX/UI wise I did not see any warning that "files" are not linked. 
@kcondon: I understand that it is possibly implemented yet - correct?

![screen shot 2015-04-09 at 10 36 54](https://cloud.githubusercontent.com/assets/7300319/7069179/4d48fc9e-dea5-11e4-9c45-29c6289ea6f7.png)

**Comment by pdurbin** [comment]
> UX/UI wise I did not see any warning that "files" are not linked

This is expected. @mheppler didn't want this:

![warning](https://cloud.githubusercontent.com/assets/21006/7007079/643393f4-dc54-11e4-8cb8-779ebeafdc6e.png)

I suggest that we use #1890 to improve the UX/UI.

**Comment by mheppler** [comment]
@suenjedt @pdurbin @kcondon -- if the functionality is as promised, I say ship it for 4.0. As pointed out, we have a 4.0.1 issue tracking UI improvements, before this feature is expanded beyond super-user admins.

And yes, we shouldn't be using great big, red "error/danger" message blocks (as shown above) for help/warning message text. We use those for when something breaks or is invalid. (If we had a robust design guide, that would be outlined in it.)

**Comment by suenjedt** [comment]
For me (as a newbie to this endeavor), the functionality worked as expected.

**Comment by scolapasta** [comment]
Yesterday we established using the warning orange block for something similar. (Not getting what you expected )

**Comment by suenjedt** [comment]
Expected was: I search, save/link the search in a (destination) dataverse. I find the searched items (DV, dataset) in the destination dataverse. 
Conclusion: all this worked

[All the other musing above were about the remaining UX/UI challenge]
