### ISSUE TITLE
Dataset Metadata - Contact "[Email in Contact button above]"

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1923]
The message displayed next to the Contact name, in place of the email, needs to be cleaned up, styled, reviewed, changed.

![screen shot 2015-04-08 at 3 14 19 pm](https://cloud.githubusercontent.com/assets/687227/7053281/ef19cfd4-de01-11e4-9afa-553a36710aa6.png)

**Comment by sbarbosadataverse** [comment]
@mheppler 
this doesn't seem any better? 
Contact
barbosa, sonia [- Use email button above to contact.]

**Comment by mheppler** [comment]
The database on your test server will need to be dropped, and rebuilt to remove those brackets "[ ]", which are coming from the TSV file. If this revision isn't up to snuff, I'll gladly look over it with @scolapasta or anyone else that has the time and know-how to improve upon this (hacked) solution.

I made the simplest change I could, because that is all I understood how to do with the code I didn't write. I'd hate to say this, but it might have to wait for another release to clean up further. The idea is that post-4.0, we'll look to improve the layout of compound metadata fields on the dataset page (and hopefully on the dataverse page search results cards as well).

**Comment by sbarbosadataverse** [comment]
@kcondon  should I move to 4.0x?

**Comment by mheppler** [comment]
The post-4.0 clean up is already a ticket -- Dataset Metadata - Improve display of compound fields in metadata tab #1625.

**Comment by sbarbosadataverse** [comment]
Will double check brackets (dropping database)-but even with that the message is confusing, there is a "-" and "." showing up in the brackets....

suggestion: add the "email" button next to the contact name instead of upper right hand of page

**Comment by mheppler** [comment]
If I could get HTML in that area, I would, and we'd have the greatest app ever. But due to limited know-how and resources, we got a text change. With a new database, it will look like this (see attached) which is going to have to be good enough.

![screen shot 2015-04-09 at 11 29 14 am](https://cloud.githubusercontent.com/assets/687227/7070243/b2aca29c-deab-11e4-81c5-566e5b139b19.png)

**Comment by mheppler** [comment]
But since you're showing such concern with this layout (and I do appreciate it, no fooling), maybe we review it with the powers that be. It does look kinda funny with multiple contacts.

![screen shot 2015-04-09 at 11 32 38 am](https://cloud.githubusercontent.com/assets/687227/7070331/45f09c3e-deac-11e4-8b84-4cb7a1643849.png)

@mcrosas @scolapasta @eaquigley @kcondon -- Thoughts?

**Comment by eaquigley** [comment]
👏👍👏👍👏👍



On Apr 9, 2015, at 11:34 AM, Michael Heppler <notifications@github.com<mailto:notifications@github.com>> wrote:


But since you're showing such concern with this layout (and I do appreciate it, no fooling), maybe we review it with the powers that be. It does look kinda funny with multiple contacts.

[screen shot 2015-04-09 at 11 32 38 am]<https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_687227_7070331_45f09c3e-2Ddeac-2D11e4-2D8b84-2D4cb7a1643849.png&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=Lz8fPZnH7o_EBcN-ij-ziN3e-_8lPDnEnfiBxSu2_jo&s=JnyNRQqOJU0YtW3NTYcl8bz_hnURsNRa4IL1k3tqwY8&e=>

@mcrosas<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mcrosas&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=Lz8fPZnH7o_EBcN-ij-ziN3e-_8lPDnEnfiBxSu2_jo&s=KvOxKTfYi1LfaHBaUCyhv0-ohYN6DAEwkmh3VWYY-q8&e=> @scolapasta<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_scolapasta&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=Lz8fPZnH7o_EBcN-ij-ziN3e-_8lPDnEnfiBxSu2_jo&s=uEy5dtdpuq3u3riDBP85v90ExEEr3AWkf3j6mqFxV8Q&e=> @eaquigley<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_eaquigley&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=Lz8fPZnH7o_EBcN-ij-ziN3e-_8lPDnEnfiBxSu2_jo&s=DJPQfPELeDXhXOiQe973y9Q8nIjxiGN_Y0yoGdEOJJs&e=> @kcondon<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_kcondon&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=Lz8fPZnH7o_EBcN-ij-ziN3e-_8lPDnEnfiBxSu2_jo&s=j_f4Qg4aPDXW_LIxwUv1lzUG8bVvYwlE5S0tFrFydwU&e=> -- Thoughts?

**Comment by sbarbosadataverse** [comment]
If an account has multiple contacts the best option is to configure so that
if we put the little email icon in the contact field, it would email all
the contacts at once. Is this possible? Or just email the first contact?


On Thu, Apr 9, 2015 at 11:36 AM, Elizabeth Quigley <notifications@github.com
> wrote:

> [image: 👏][image: 👍][image: 👏][image: 👍][image: 👏][image: 👍]
>
>
>
> On Apr 9, 2015, at 11:34 AM, Michael Heppler <notifications@github.com

**Comment by mheppler** [comment]
I believe the "Email Dataset Contact" button at the top of the page, emails all contacts associated with the dataset, in that metadata field. If (and maybe when) we add a button next to the field values, it will do the same. Maybe we add some help text to explain that. That said, I believe all of this is a conversation for another release.

**Comment by mheppler** [comment]
Improved help text message for Contact metadata values in Citation Metadata tab on dataset. It now contains one message, with a help icon, above the contact values.
