### ISSUE TITLE
Glassfish is installed and run as root

### ISSUE THREAD

**Issue by bencomp** [IQSS/dataverse#1934]
The installer script (#1119) requires that it be run as root. Glassfish is installed by this script, possibly making root the owner of the Glassfish server.

In our test environment, Glassfish now runs as the root user.

I am told running Glassfish as root is **very bad practice** and unnecessary. As we followed install instructions closely, I suspect the script is in some way responsible and would like to have this reviewed.

Does Glassfish on IQSS's servers also run as root?

**Comment by pdurbin** [comment]
In Vagrant at https://github.com/IQSS/dataverse/blob/master/scripts/vagrant/setup.sh I **unzip** the Glassfish zip file as non-root, at least. But I believe @bencomp is right that the installer (called by the Vagrant scripts) later starts Glassfish as root: https://github.com/IQSS/dataverse/blob/master/scripts/installer/install

@bencomp if you want to mess around with the installer to have it do more stuff as `$GLASSFISH_USER` I'd be happy to review a pull request!

**Comment by pdurbin** [comment]
[Yesterday in #glassfish](http://javabot.evanchooly.com/logs/%23glassfish/2015-06-22) on freenode @phillipross was making the point that iptables can be used for port forwarding. This is something I could play around with in Vagrant some day, perhaps, but as of this writing we're hoping to reintroduce Apache in #2180 in order to restore Shibboleth support for #2117. That is to say, I probably wouldn't bother with the iptables port forwarding unless we choose a non-Apache direction for Shibboleth support (such as using a Java library like OpenSAML right in the app itself).

Anyway, I share the sentiment that we should avoid running Glassfish as root if we don't have to.

**Comment by bencomp** [comment]
I was told that Apache very briefly gets root access to 'claim' ports under 1000 (80 and 443) and then goes into a non-root mode for normal operation.

**Comment by pdurbin** [comment]
Right, "In typical operation, Apache is started by the root user, and it switches to the user defined by the User directive to serve hits." http://httpd.apache.org/docs/2.4/misc/security_tips.html

**Comment by pdurbin** [comment]
In #2443 @michbarsinai and I have discussed the need for a "developer-machine friendly setup script" that does not require root.

Also, these days we're back to running Glassfish behind Apache on https://dataverse.harvard.edu per #2180 so there's no need to run Glassfish on a low port. Glassfish runs on its normal high ports (8080 and 8181) and doesn't need to be started as root.

**Comment by pdurbin** [comment]
In pull request #3017 it says the installer no longer has to be run as root.

**Comment by pdurbin** [comment]
@donsizemore must be taking advantage of the "**NEW in Dataverse 4.3:** It is no longer necessary to run the installer as root!" feature added in pull request #3017 because he mentioned the other day that Odum/UNC doesn't run Glassfish as root: https://groups.google.com/d/msg/dataverse-community/U04sLtEkJ7Q/TB-xvjXHBQAJ

He wrote, "Dataverse.unc.edu is running RHEL7 with Shibboleth 2.6, with each service (glassfish, httpd, rserve, shibd) running as separate, non-privileged users."

**Comment by pdurbin** [comment]
@donsizemore and I talked about this at http://irclog.iq.harvard.edu/dataverse/2017-02-02#i_48097

My main take away is that by default, Don's Ansible code at https://github.com/IQSS/dataverse-ansible runs Glassfish with a dedicated non-root user called "glassfish". This is a great default to have.

**Comment by donsizemore** [comment]
I install glassfish as root but give the glassfish user ownership of /usr/local/glassfish4/glassfish/domains/domain1 and the JVM-specified filesdir. Protects Glassfish from itself, and so far, so good.

**Comment by pdurbin** [comment]
We should document in the Installation Guide how to run Glassfish as a user under than root. I wonder if the currently suggested init script will need to change: http://guides.dataverse.org/en/4.6/installation/prerequisites.html#glassfish-init-script

In addition, I assume the installer will need to be updated as well, from a quick peek at https://github.com/IQSS/dataverse/blob/v4.6/scripts/installer/install I don't a variable for `$GLASSFISH_USER`, for example.

Hmm, I'm reading "NEW in Dataverse 4.3: It is no longer necessary to run the installer as root! Just make sure the user that runs the installer has the write permission in the Glassfish directory." at http://guides.dataverse.org/en/4.6/installation/installation-main.html#running-the-dataverse-installer . Perhaps that means that one should create a user called `glassfish` or whatever and then run the installer as that user? More investigation is needed. I always just run the installer as root, both manually and in Vagrant. Vagrant would be an excellent place to place to test out any changes to the installer.

**Comment by donsizemore** [comment]
@pdurbin if you assume that new installations will move to RedHat/CentOS 7 you could include a sample glassfish.service file for systemd. c.f. https://github.com/IQSS/dataverse-ansible/blob/master/roles/dataverse/templates/glassfish.service.j2 and https://github.com/tdilauro/dataverse-ansible-role/blob/master/roles/dataverse/templates/glassfish.service.j2

in my experience at Odum Glassfish just needed to own the domain1/ hierarchy and files.dir/

dataverse-ansible does this by default; you could just make vagrant create a glassfish and you should be good.

**Comment by pdurbin** [comment]
In recent memory we estimated this issue as a "5" which you can see at https://waffle.io/IQSS/dataverse?search=1934

I just closed #3607 but we could re-confirm if it's possible to deploy via POST when we start work on this issue.

**Comment by pdurbin** [comment]
@donsizemore is this something you could tackle? I imagine that the main change to make is to the init script at http://guides.dataverse.org/en/4.7/installation/prerequisites.html#glassfish-init-script so that Glassfish doesn't start as root? We could take it from there in terms of updating documentation and messing with the Vagrant scripts to make sure Glassfish isn't installed or run as root. Please let me know what you think. Thanks!

**Comment by donsizemore** [comment]
@pdurbin i'm happy to take a look (so far I haven't knowingly been bitten by simply chowning /usr/local/glassfish4/glassfish/domains/domain1 to a service account (i.e. "glassfish") and running in an unprivileged fashion from there).

This might be memorialized in the Great Installer Script Rewrite - I'm tweaking Craig's Docker stuff and running into some similar, stop-gap sort of decisions.

**Comment by pdurbin** [comment]
@donsizemore heh, yes, over at #3938 we have expressed a desire to investigate using Docker in dev environments at least. Awesome that you're able to build off the great work by @craig-willis . Can you please remind me if you've already pushed code to a git repo? Also, I'm assigning this issue to you. :smile:

**Comment by donsizemore** [comment]
@pdurbin the simplest thing to do (in view of the looming rewrite) might be to tag back the postgres database creation bit, and in the documentation encourage 1st-time installers to create a glassfish service account and chown gf_dir to that user. Then even the installer script itself could be run under the service account. 

Maybe provide an SQL script that a complete n00b such as myself could run as the postgres admin user to create the database, chown -R gf_dir and off we go? I appreciate the script's care to do as much as it can for the end user, so if we want to continue running the installer as root but only launch Glassfish under a service account, that's do-able as well.

**Comment by pdurbin** [comment]
@donsizemore over in Vagrant land I'm already doing a `useradd $GLASSFISH_USER` at https://github.com/IQSS/dataverse/blob/v4.7/scripts/vagrant/setup.sh#L29 . So in that environment anyway, there's already a glassfish user to play with.

I agree the need to figure out who runs the installer. I assume the glassfish user can't run it because it needs to mess with Postgres? If you're in there, please remind me.

Yesterday #3937 got moved from Backlog to Inbox at https://waffle.io/IQSS/dataverse so please do not assume that a rewrite is looming at this time. 😄

**Comment by donsizemore** [comment]
@pdurbin The glassfish user can run the script as long as it can write to glassfish/domains/domain1/ and glassfish/lib/ during the installation process. So far I've tweaked the install script to check that it's not run as root (since we want to discourage this) and check if glassfish_dir/glassfish/domains/domain1 and glassfish_dir/glassfish/lib are writable by the user running the script.

Then we'd tweak the documentation to recommend a prerequisite Glassfish service account and provide modified init and systemd examples for launching the service as the Glassfish user. A step in the right direction?

**Comment by pdurbin** [comment]
@donsizemore please push what you've got so far so I can give you a little feedback. Thanks!

**Comment by pdurbin** [comment]
@donsizemore made pull request #3991 (thanks!) and I just advanced it to Code Review per http://guides.dataverse.org/en/4.7/developers/version-control.html#make-sure-your-pull-request-has-been-advanced-to-code-review

**Comment by pameyer** [comment]
Looks good to me: CentOS 6 init script for glassfish; running installer as glassfish user (non-interactively); after installer glassfish isn't running as root.  No problems w\ emails, no problems creating users/dataverses/datasets  (didn't check publishing due 3957 / current provisioning setup; but don't see any reason it would have problems).

**Comment by pdurbin** [comment]
The thing that really gave me confidence yesterday at standup was hearing that @pameyer is using these new init scripts. Awesome.

**Comment by donsizemore** [comment]
@pdurbin I tested the CentOS6 example before including it, and Odum has been using the Systemd example in production for nearly a year.

**Comment by landreev** [comment]
Kevin just tried to run the installer as root (something a user still should be able to do, if, against our recommendations, they still have some reason to run glassfish as root...); and it failed with 'no such user "glassfish"'. 
So it looks like the username is hard-coded in the installer: 
```
my %CONFIG_DEFAULTS = (
...
    'GLASSFISH_USER',	   'glassfish',
```

We really want it to be configurable; i.e., it needs to be added to "@CONFIG_VARIABLES", with an extra entry in "%CONFIG_PROMPTS". 

The message early on says "Consider creating a glassfish service account..." - not "you must create a non-root account, and the name must be 'glassfish'". I think this is the correct approach; but then the installer script should behave accordingly.

**Comment by landreev** [comment]
Oh, another thing is, this script is not just for admins setting up dataverse servers - all the developers who want to contribute to the project have to run it too. And for a developer the recommended setup is to just run Glassfish as themselves; i.e. their normal unprivileged user id. 

So the ideal behavior would be for GLASSFISH_USER to default to the current user, unless it is root - in which case to "glassfish". But, if it's too much hassle, defaulting to "glassfish" is ok, as long as it's configurable.

**Comment by donsizemore** [comment]
whoops! will fix. thank you for the feedback.

**Comment by donsizemore** [comment]
Okay, I think I have this right. The updated script:

- warns if run as root but carries on
- checks default.config for GLASSFISH_USER
- checks CLI arg for gfuser, which trumps default.config
- falls back to current user per ENV or getpwuid

I tried a number of combinations to test precedence, but was interrupted and... I think I have it right. Additions or corrections are welcome and requested.

**Comment by landreev** [comment]
Thanks @donsizemore! - looking great. 
@kcondon is back tomorrow, he should be able to do his final QA check and merge your branch quickly.
