### ISSUE TITLE
Metrics page for Dataverses

### ISSUE THREAD

**Issue by mercecrosas** [IQSS/dataverse#1971]
In additions to the metrics icon on the top of a Dataverse (views, downloads, shares, citations), we need a page with all type of metrics we want to share about the Root Dataverse (and possible for each dataverse). For example: # of files counting all formats, # of unique subset downloads, # of data explorations, etc

**Comment by mcrosas** [comment]
Include: Map of location of dataverses

**Comment by pdurbin** [comment]
#2729 has some information on \# of data explorations.

**Comment by mheppler** [comment]
Related to: Metrics: Display visualizations on dataverse.org #3230

**Comment by pdurbin** [comment]
https://github.com/IQSS/miniverse does some of this stuff these days.

**Comment by pdurbin** [comment]
QDR has a nice metrics pages at https://data.qdr.syr.edu/metrics_5ef2ae2be4b/

It's powered by the code at https://github.com/IQSS/dataverse-metrics (the "installation-level app").

There are lots of good charts but I especially like the one that shows which datasets (they call them "data projects") have the most downloads:

![Screen Shot 2022-04-12 at 4 45 47 PM](https://user-images.githubusercontent.com/21006/163050743-f097a9ae-e1e4-4f7a-a56f-2c4865931a53.png)

I'd also like to highlight (since it's mentioned above) that you can drill down into sub-dataverse (sub-collections):

![Screen Shot 2022-04-12 at 4 46 59 PM](https://user-images.githubusercontent.com/21006/163050958-a45ce8fc-67d7-4ac0-8192-65e67b56e465.png)

We already mention datavese-metrics at https://guides.dataverse.org/en/5.10.1/admin/reporting-tools-and-queries.html so perhaps we could consider this issue done.

**Comment by pdurbin** [comment]
> It's powered by the code at https://github.com/IQSS/dataverse-metrics (the "installation-level app").

We moved it here: https://github.com/gdcc/dv-metrics

Closing.
