### ISSUE TITLE
Guestbook - Enabled for Request File Access

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2043]
Users with restricted files would like to enable guestbook like functionality so that they can find out who and why someone would like to access their data. This will help inform the user on whether or not they should grant or reject access to a file.

This suggestion was requested by a user in our Google Community Forum: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/dataverse-community/Xn-SsIEaRf8/LwtvL8exXEAJ

**Comment by sbarbosadataverse** [comment]
@eaquigley 
@pdurbin 

Contact from user today regarding this function. In 3.6, clicking on username allowed admins to see: names, affiliations, and email. Also mentioned they can't grant access to their users until this is resolved which bumps it up to high/critical request
We need a function that resembles this.

**Comment by mcrosas** [comment]
@eaquigley can you this to the In Design milestone, so we can push it to an upcoming release as soon as possible? This is urgent. From users the inability to verify users information is equivalent to the system being down because they cannot process requests.
@scolapasta this is high priority for an upcoming release.

**Comment by eaquigley** [comment]
FRD and mock up needs to be done

**Comment by eaquigley** [comment]
FRD: https://docs.google.com/document/d/1qoDTXXCIBtMgLbh_xSISNkfh5dvh_afB3kDNcEUIOEo/edit?usp=sharing

**Comment by eaquigley** [comment]
FRD has been completed: https://docs.google.com/document/d/1qoDTXXCIBtMgLbh_xSISNkfh5dvh_afB3kDNcEUIOEo/edit?usp=sharing 

Now just needs to be scheduled for development. No need for mockups as it is adding an extra step to an existing workflow.

**Comment by stevenmce** [comment]
Per the community call on 28 Feb 2017, we would like to highlight this issue for possible inclusion in an upcoming release - particularly the requirement above of "having the guestbook recording entries that a dataset owner can review when a restricted file is requested for access." ADA can assist in describing the required workflow for this request process if that would be of assistance - we have an immediate need for this functionality in order to support of a number of data owners who use our service.

Steve McEachern, Australian Data Archive

**Comment by pdurbin** [comment]
@stevenmce yes, thanks for calling in! I'm curious if you've taken a look at the "Guestbook: Use Requesting Access to Files Functional Requirements Document (FRD)" doc listed earlier in this issue: https://docs.google.com/document/d/1vWxBcudr1z2dCJkDwvO4TnJHnBFqmhqNV6Mn0tM_B6E/edit?usp=sharing

That doc hasn't been touched in a year and a half but it might have some ideas you agree with. You'd be welcome to describe the feature you're interested however you'd like. In the [notes][] from the call I seem to have captured that there may be someone at ADA who could make a pull request but perhaps that's wishful thinking on my part. :smile: 

[notes]: https://groups.google.com/d/msg/dataverse-community/6Twh8KLhmQg/rR9TP-cPAQAJ

**Comment by scolapasta** [comment]
Some notes to review when this is being designed / developed:


To use the current Guestbook functionality for Request Access as simple as possible:

- Add a column to guestbook response as a flag to denote whether pre filled or an actual download.
- when request access, if guestbook selected for that dataverse, popup guestbook
- on permissions page add a way to view guestbook response.
- when user downloads, look for pre filled guestbook and if exists, toggle the new flag to show actual download



Issues / nice to have's:
1. if user decides to download the file a 2nd time, they would need to fill out a new guestbook, since they "used" the first guestbook
2. we don'r currently have way to give feedback when rejecting - will be more important to consider when we add this as users will want to explain what was wrong with guestbook.
3. if rejected, do we keep the guestbook entry? If so, we'll need to ave the ability to edit the guestbook, which we currently don't do
4. related to 3, if we do have the ability to edit, do we want the user to review their guestbook when they download?

**Comment by pdurbin** [comment]
> particularly the requirement above of "having the guestbook recording entries that a dataset owner can review when a restricted file is requested for access." ADA can assist in describing the required workflow for this request process if that would be of assistance

@stevenmce I see this issue was mentioned in the notes for the 2017-02-28 Dataverse Community Call at https://groups.google.com/d/msg/dataverse-community/6Twh8KLhmQg/rR9TP-cPAQAJ but can you or @mdmADA please create a new issue that is narrowed down to the scope of what you need? This is on my mind because I'm trying to keep better track of development efforts by the Dataverse community and I'm hoping to write to the Google Group soon about a new spreadsheet I'm working on that lists these efforts: https://docs.google.com/spreadsheets/d/1pl9U0_CtWQ3oz6ZllvSHeyB0EG1M_vZEC_aZ7hREnhE/edit?usp=sharing . For now, in that spreadsheet, I'm linking to this issue but I'll switch it over to the new issue once you've created it. Thanks!

**Comment by stevenmce** [comment]
Hi Phillip

We will write this up next week and post an issue on GitHub

Cheers
Steve

Sent from my iPhone

On 19 Aug 2017, at 12:06 am, Philip Durbin <notifications@github.com<mailto:notifications@github.com>> wrote:


particularly the requirement above of "having the guestbook recording entries that a dataset owner can review when a restricted file is requested for access." ADA can assist in describing the required workflow for this request process if that would be of assistance

@stevenmce<https://github.com/stevenmce> I see this issue was mentioned in the notes for the 2017-02-28 Dataverse Community Call at https://groups.google.com/d/msg/dataverse-community/6Twh8KLhmQg/rR9TP-cPAQAJ but can you or @mdmADA<https://github.com/mdmada> please create a new issue that is narrowed down to the scope of what you need? This is on my mind because I'm trying to keep better track of development efforts by the Dataverse community and I'm hoping to write to the Google Group soon about a new spreadsheet I'm working on that lists these efforts: https://docs.google.com/spreadsheets/d/1pl9U0_CtWQ3oz6ZllvSHeyB0EG1M_vZEC_aZ7hREnhE/edit?usp=sharing . For now, in that spreadsheet, I'm linking to this issue but I'll switch it over to the new issue once you've created it. Thanks!

**Comment by pdurbin** [comment]
@mdmADA hi! I've retired the "dev efforts by the community" spreadsheet I mentioned above and I'm interested in some way of tracking the fact that you and @stevenmce have a solution in production, which Steve presented very well back in June. So I assigned this to you and dragged it to the new "Community Dev" column at https://waffle.io/IQSS/dataverse to remind us to do some housekeeping around the development for what we've called the "requestbook" feature you're running in your fork. Basically, a lot of coordination will be necessary to bring this great feature into the main code base. We can open a fresh issue if you want or change the title of this one.

In addition to the recent retirement of that spreadsheet, yesterday @dconner3 reported "all we get out of using the [Request Access] button is that there is interest in the restricted file" at https://github.com/IQSS/dataverse/issues/3404#issuecomment-429147165 and so is experiencing the same pain you were. For his benefit and others reading this, I'm going to include a few screenshots from Steve's "Updates to Support Request Access Workflows" talk to give a sense of how the "requestbook" works. These are from https://schd.ws/hosted_files/dataversecommunitymeeting20/62/Slides%20-%20Updates%20to%20Support%20Request%20Access%20Workflows.pdf via https://projects.iq.harvard.edu/dcm2018

![screen shot 2018-10-12 at 11 02 55 am](https://user-images.githubusercontent.com/21006/46877260-6db14c00-ce0e-11e8-9d63-feb459882f65.png)

![screen shot 2018-10-12 at 11 03 06 am](https://user-images.githubusercontent.com/21006/46877259-6db14c00-ce0e-11e8-85cd-ad7cb9dc55e2.png)

**Comment by mdmADA** [comment]
Hi Phil - It would be great to have ADA's code in the main code base. I would like to redesign some of it to make it more flexible as my first go at it was simply to quickly implement the functionality ADA needed in order to use Dataverse. Separating the requestbook database records from the guestbook database records, and tracking the full life cycle of a requestbook record would be on my agenda as part of that redesign.

Steve and I will need to discuss the best way forward from ADA's perspective so let's keep the discussion going over the next weeks.

Thanks!

**Comment by pdurbin** [comment]
@mdmADA sounds great. The main thing I wanted to convey is that you're on the right track. There's lot of interest in this feature. Thanks!

**Comment by pdurbin** [comment]
@mdmADA hi! I just thought I'd mention that when I was at LibrePlanet last weekend I talked to a Dataverse user about the "requestbook" you have at ADA. For now, his work around is to make one file unrestricted, a PDF that he asks people to fill out to request access to the data. I think it's this PDF: https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/KFT8EZ/ACLHGA . Anyway, he definitely sounded interested in the feature you have in production. 😄

**Comment by mdmADA** [comment]
Thanks for passing that on, @pdurbin.

ADA has had several organisations express interest in the Request Access feature so it is great to add another to the list! 👍 

M.

**Comment by pdurbin** [comment]
@mdmADA hi! I see that you made pull request #5863 (thanks!) and that you have a number of questions in there so I dragged this to code review. I'm not sure if you're aware of this but we switched from Waffle as our kanban board to GitHub Projects: https://github.com/orgs/IQSS/projects/2

**Comment by djbrooke** [comment]
Thanks @mdmADA - I'll move this back to the Community Dev column and we'll correspond about this in the Pull Request. @scolapasta is reviewing.

**Comment by scolapasta** [comment]
@mdmADA Tania and I reviewed the current state of the demo and the UI looks good for a first pass. You mentioned the idea of differentiating between requests, so one straightforward addition would be to add the date as another column. That way the curator should be able to tell if two requests cam in together.
