### ISSUE TITLE
File Upload: Users have been asking about uploading as zip format

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2055]
We have had at least two users ask about adding upload as zip format as a feature:
RT #196683

**Comment by eaquigley** [comment]
I thought we decided against this because it is a bad format for long term preservation and hides the types of files that are contained within it.

On Apr 21, 2015, at 2:06 PM, Gustavo Durand <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #2055<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2055&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=rxxZ4F10wURB9dbiWs9GMSwUs5cgtVfS5qj5oCZzxig&s=-UD0MyxaPtFOzrNnAuGrDOCgi23SSxW21mLHlrc4Lug&e=> to @eaquigley<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_eaquigley&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=rxxZ4F10wURB9dbiWs9GMSwUs5cgtVfS5qj5oCZzxig&s=LuPpDNh9ukHbr7Lcu-RUKYUcK0bYuDZ_CooUEE7Du_M&e=>.

**Comment by mcrosas** [comment]
Yes, but it's a suggestion now that has come back from our users, it doesn't mean will do it necessarily. We should review it when it's the right time, based on its priority, and decide what's the best solution  without compromising preservation but also understanding why this would be better for some of our users. Maybe there is a clever solution that gives both.

**Comment by scolapasta** [comment]
Can we consider this a duplicate of #2107?

**Comment by mcrosas** [comment]
yes @scolapasta

**Comment by kcondon** [comment]
To close or not to close, that is the question. Closing! Take that Hamlet!
