### ISSUE TITLE
Unable to download files that existed before 4.0

### ISSUE THREAD

**Issue by nicipfeiffer** [IQSS/dataverse#2063]
Trying to download a draft file from https://dataverse.harvard.edu/dataverse/harvard that existed before Dataverse 4.0 changes gives the user:

![screenshot 2015-04-21 13 10 23](https://cloud.githubusercontent.com/assets/9381062/7258016/ca5fa2b0-e827-11e4-9db2-f06008752a22.png)

Related to https://github.com/CenterForOpenScience/osf.io/issues/2547

**Comment by posixeleni** [comment]
@nicipfeiffer we are also seeing this file download issue for other datasets that are in draft so I am reporting this as a critical issue for our developers to look into ASAP. Would you please send me the URL to this dataset when you get the chance?

Thanks!

**Comment by posixeleni** [comment]
Same issue reported by another user in RT: https://help.hmdc.harvard.edu/Ticket/Display.html?id=196710 (developers: please go to this URL to recreate issue with the draft dataset)

The dataset was migrated over as a Draft and when they try to download ANY file it takes them to an HTML version of the page instead of downloading or providing an error message.

**Comment by posixeleni** [comment]
I just tried downloading the files from this draft dataset https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/193ZDD&version=DRAFT again and instead of downloading it takes me to an internal server error page https://dataverse.harvard.edu/api/access/datafile/2546706?format=original

@scolapasta any ideas why this may be occurring still over a week later? 

(reported in RT https://help.hmdc.harvard.edu/Ticket/Display.html?id=196710)

CC/ @kcondon

**Comment by scolapasta** [comment]
The issue had to do with datasets that got reregistered doi's. This has been handled with symblic links, but requires a little bit of cleanup (remove those links and make the file permanent) and generate a report  of dataset that this happened to.

Moving to post curation for this.

**Comment by landreev** [comment]
We are going to close this issue, since there shouldn't be any download issues with the files in this dataset at this point.
I have created a new ticket #2173 for finalizing the resolution of this issue for all the datasets involved.
