### ISSUE TITLE
User Account Information: User asked for link to his dataverse from his account info.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2074]
See RT #214858

 there is no link in my account that leads me to this dataverse. It would be very useful to have link to my dataverses in my account, as the old version used to have.

**Comment by mcrosas** [comment]
Agree completely. I was just thinking the same today. Can review with Elizabeth and Mike.

**Comment by eaquigley** [comment]
Agree as well. We definitely need to rethink the My Unpublished Data tab to make it more useful. CC @mheppler

**Comment by suenjedt** [comment]
If you are considering an ORCID integration, this might be an interesting place to link/offer it - e.g. to push the published DV/DS information. [Sorry, slightly off topic]

**Comment by hamogu** [comment]
I opened a helpdesk ticket today, because I could not find a link to my published dataverses. At first, I thought I had lost the contact to my dataverses during the most recent update. 
Instead, I was referred to this thread.
So, :+1: that the account page definitely needs some kind of link to my published dataverses / datasets.

**Comment by eaquigley** [comment]
Functional Requirements Document for this feature: https://docs.google.com/document/d/1xv_IKS1hWYUzX3GZOjHqGQ3BUBI7QH_2FekP90cexNA/edit?usp=sharing

**Comment by scolapasta** [comment]
I think this is resolved with the way the new My Data page works.

**Comment by kcondon** [comment]
Yes, covered by My Data, closing.
