### ISSUE TITLE
Notification Emails - Improve Email's, From "support"

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#2088]
When I receive dataverse generated emails like, "Dataverse: Your account has been created", and "Dataverse: Your dataverse has been created", in my inbox, all I see is "support". (See attached.)

That From field should be formatted to read "Dataverse Support" or something a little more informative to the user.

![screen shot 2015-04-24 at 12 07 31 pm](https://cloud.githubusercontent.com/assets/687227/7323135/7c0bfc6c-ea7a-11e4-8d40-91f3da0d980a.png)

**Comment by pdurbin** [comment]
I **believe** what's happening here is that only an email address is provided such as "support@dataverse.org" which Gmail shortens to just "support". Probably the fix is to specify both an email address and a "display" name such as "Dataverse Support Team <support@dataverse.org>". We could add a row in the `setting` table for the `systemEmailDisplayName` or something.

**Comment by pdurbin** [comment]
@scolapasta and I decided to continue using the existing `SystemEmail` setting but to allow it to support either of these:

- `support@dataverse.org`
- `Dataverse Support <support@dataverse.org>`

In adf0646 I updated the setup-optional-harvard.sh to use the one with a display name and it seems to work fine:

![email](https://cloud.githubusercontent.com/assets/21006/7573359/21be1f20-f7f3-11e4-89e5-d72c27a78f28.png)

As before, if you omit a value in the `SystemEmail` you should expect no email to be sent (and nothing to be logged about this.) If you put a weird value in that setting, a message about how the value couldn't be parsed will be put in the sever log.

Passing to QA.

**Comment by kcondon** [comment]
OK, says Dataverse Support, closing.
