### ISSUE TITLE
Dataset Metadata - Do Not Pre-populate Depositor if This Field Is Hidden

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2109]
User (RT https://help.hmdc.harvard.edu/Ticket/Display.html?id=214953) wanted to hide the depositor field from showing up on Create, Edit and View since they did not want it to pre-populate with their name for any new datasets they created. However our system automatically pre-populates the field regardless of it being hidden on create and will display the users name as the Depositor even if they wanted this field hidden.

The other confusing part for the user is that it hides the field on Create and Edit but shows up on View.

**Comment by jggautier** [comment]
The user resolved the issue by adding a string with the organization's name to the depositor field in their dataverse's dataset template.

I'd like to find out why someone wouldn't want the name of the depositor in the depositor field (my hunch is it's the same reason the depositor wouldn't want her or his name in the contact name field (#3839): because she or he isn't the best person to contact.) I'm assuming we made the decision to pre-populate the depositor field with the depositor's name because it was the obvious choice (although the depositor tooltip label recommends the name of the person or _organization_). I emailed the user in the RT to ask why she didn't want the name of the depositor in the depositor field.

Instead of allowing dataverse owners to disable the field, maybe we could suggest values for _depositor_ (in addition to letting them enter free text): it could be the first and last name of the account owner or the name of the organization or dataverse affiliation. I haven't looked exhaustively, but I doubt anyone is putting anything else the depositor field. This would require a change in the types of form fields we use, but there are discussions to change that with the expansion of the subject vocabulary.

Is this field important for provenance (in theory, not the provenance project)? Is there another record of who actually deposited the dataset that can be accessed programmatically?

**Comment by jggautier** [comment]
Spoke with the user to ask why she wanted to hide the depositor field. It was because they didn't want people who find and have questions about the datasets trying to contact the person who uploaded the dataset, since that person wouldn't be the best person to contact. That hadn't been a problem for them; trying to hide the field was more of a precaution.

I asked @sbarbosadataverse as well, since the name of the Murray Archive is in the depositor field in its dataverse's dataset template. Sonia said it's because Murray Archive dataverse's terms of use identifies the archive as the depositor, and putting the name of the person uploading the dataset would conflict with those terms.

**Comment by pdurbin** [comment]
@jggautier so should we keep this issue open or should we close it? It sounds like the person in https://help.hmdc.harvard.edu/Ticket/Display.html?id=214953 is happy, at least. 😄

**Comment by jggautier** [comment]
Hey @pdurbin. I'm thinking the solution in this issue's title is not the best solution for the problem, and I'd like to know if others agree before closing the ticket and opening another if we decide the way the user solved the issue could be improved, or just closing it if we decide considering other solutions isn't warranted or worth the trouble.

She said using dataset templates worked well, so that's a solution. @sbarbosadataverse mentioned a while back that she thought people had an easier time finding the dataset templates before 4.x. So perhaps making that functionality easier to find would help.

Another is suggesting multiple values for the depositor field instead of just one (if you think of the way we pre-populate that field as a way of suggesting just one value (i.e. the account owner's name)). That would require more dev work, but it could help improve metadata entry in with other fields (e.g. the contact name) as well. I'm partial to this idea, and there's interest in controlled and suggested values in general.

**Comment by pdurbin** [comment]
@jggautier sure, I'm cool with making templates easier to find.

**Comment by pdurbin** [comment]
Related:

- #2623

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
