### ISSUE TITLE
Support login using email address (as well as username) for builtin/local users

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2115]
We have had several users attempt to login with their email addresses which 4.0 does not currently support. However, many sites support user authentication through email or username so we should look into supporting this in the future.

**Comment by pdurbin** [comment]
This probably goes without saying but this feature only applies to "builtin/local" users, not Shibboleth users.

**Comment by pdurbin** [comment]
Related: Validation Message: Inform user they can't log in with an email address as a username #2908 

@scolapasta do you want the "quick fix"? To simply inform the user they can't use an email address, which is basically what #2908 is about? Please advise.

**Comment by eaquigley** [comment]
@pdurbin we've decided to go ahead and do the logging in via email option instead of the "quick fix".

**Comment by pdurbin** [comment]
@scolapasta can you please review my commit at ff7770b (new branch 2115-email-as-username).

Things to think about (I wrote tests for these in the commit):

- Users **could** have an extremely long email addresses that violate the length constraint on username.
- Email addresses can have a plus sign or an apostrophe in them (now allowed in the commit per the screenshot below)
- Email addresses **could** be just crazy, such as `"very.unusual.@.unusual.com"@example.com` (spaces inside a quote, which I got from https://en.wikipedia.org/wiki/Email_address#Valid_email_addresses ). I'm not allowing this. I'm not allowing `"()<>[]:,;@\\\"!#$%&'*+-/=?^_{}| ~.a"@example.org` either and didn't even write a test for it. (I had to take out a backtick just to write it here.) No one in their right mind should have an email address or username like that. 

Here's what I'm proposing we allow (I'm sort of on the fence about allowing an apostrophe, actually, but I **have** seen it in the wild before):

![screen shot 2016-02-05 at 10 31 05 am](https://cloud.githubusercontent.com/assets/21006/12850769/649f994c-cbf4-11e5-885c-9c4528e28595.png)

@michbarsinai what affect does this change have on permissions? A long time ago I opened the "Stop using `@pete` and `@uma` (strings) in role assignments rather than `@2` and `@3` (database IDs)" issue at #1151 out of concern of how permissions are stored. There's a reason why in Solr I store the integer version of authenticated users and groups rather than their "friendly" identifiers. I don't want my Solr queries to blow up on crazy characters.

**Comment by pdurbin** [comment]
I just spoke with @scolapasta and realize now that when I made my pull request at #2919 I completely misunderstood the requirement. I guess I was thinking too much about "Inform user they can't log in with an email address as a username" at #2908 and thought that the requirement is to allow the characters that are allowed in email addresses to be allowed in usernames. I was mistaken. The idea here is that usernames retain their current constraints (which are much stricter than email addresses) but that a user can log in with **either** their email address **or** their username. I'll update the title to make this clear to me. Back to the drawing board.

Side note that @scolapasta mentioned that part of why we don't want to allow users to enter their email address as their username on signup is that we expose usernames (well, "identifiers" which is what #1151 and #1445 and #1584 are about) when people are assigning permissions and we don't want to expose their email address to others.

**Comment by pdurbin** [comment]
Ok, I just made a new pull request at #2922 with some questions for @scolapasta so I'll assign this issue to him.

**Comment by scolapasta** [comment]
If for some reason this does not get closed for 4.3, let's reopen #2908 and at least get the validation message in.

**Comment by mheppler** [comment]
Cleaned up the UI for the loginpage to make space for the longer "Username/Email" label.

**Comment by kcondon** [comment]
Works, closing.
