### ISSUE TITLE
Support exporting citation to refworks

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2116]
There is a ticket for exporting bibtex #1013 and another ticket for integrating with EndNote #1894 

Other citation export options:
- [ ] Export directly to refworks
- [ ] Export directly to Zotero

**Comment by pdurbin** [comment]
I would hope that export to Zotero would be easier now that #1393 is done. Maybe @adam3smith has more information on this.

**Comment by adam3smith** [comment]
Zotero would actually prefer that you _not_ add a specific export function. It will import datasets automatically using the browser extension.

**Comment by pdurbin** [comment]
@adam3smith thanks!

#1013 is done so bibtex support is in place. #1894 about endnote is still open.

It looks like #881 includes a lot of chatter about refworks. My take on it is that RIS formats works with them.

I thinking we should close this issue.

**Comment by jggautier** [comment]
This issue could be changed to improving RefWorks support, but should we wait until we see or figure out if there's more demand for it?

**Some issues with RefWorks support:**

**Importing from files**: Importing .bib files into RefWorks doesn't work (it says it does, but even importing the same .bib file you can export from RefWorks doesn't work). RefWorks imports Dataverse's RIS files, but not all of the metadata fields are imported, e.g. the dataset description.

<img width="1239" alt="screen shot 2017-06-25 at 4 16 46 pm" src="https://user-images.githubusercontent.com/18374574/27519437-dbf425b0-59c1-11e7-84ca-4c4128c5ba31.png">


**Importing from browser**: RefWorks has a button you can drag to your browser's bookmarks bar. When you're on a webpage with resource metadata and press that button, RefWorks tries to import metadata (a lot like how the Zotero and EndNote browser extensions behave). That doesn't work very well. Looks like only the title is populated.

<img width="1041" alt="screen shot 2017-06-25 at 4 00 53 pm" src="https://user-images.githubusercontent.com/18374574/27519374-9463cfee-59c0-11e7-887c-21822ed30a3f.png">

Another question I'd have is if RefWorks has plans for creating/improving a dataset reference type, like Zotero and EndNote have.

**Comment by jggautier** [comment]
Checked RefWorks recently, and things have improved since late June: RefWorks imports more dataset metadata from Dataverse's RIS and BibTeX file (.bib) and when [using the browser bookmark "tool"](https://refworks-proquest-com.ezp-prod1.hul.harvard.edu/tools/) (at least on Google Chrome; couldn't get it working on Firefox).

<kbd><img width="1064" alt="screen shot 2017-09-03 at 3 50 13 pm" src="https://user-images.githubusercontent.com/18374574/30006173-9476407a-90c0-11e7-8c00-1a7bc359fdd6.png"></kbd>

I'm closing this issue and will open another soon about improving:
- the dataset metadata in the RIS files that Dataverse creates and
- the dataset metadata it puts in the HTML of dataset pages

to try to unify the dataset citation experiences across Zotero, EndNote and RefWorks .

**Comment by pdurbin** [comment]
> the dataset metadata in the RIS files that Dataverse creates

@jggautier thanks for opening this issue: Use unescaped versions of ampersand, greater than and less than symbols in RIS files #4123
