### ISSUE TITLE
Linked Pop Up: In FF, Harvard Dataverse shows up twice in drop down selection list

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2124]
Doesn't behave this way in Chrome though. 

Need to check and see if other dataverses are appearing as duplicates.

**Comment by scolapasta** [comment]
I was not able to reproduce. @eaquigley since you encountered this, can you see if you can, and if so, show me?

**Comment by eaquigley** [comment]
Showed @scolapasta that this is only happening when looking to link a dataset not link a dataverse.

Tested in both FF and Chrome

**Comment by scolapasta** [comment]
The issue here was that there were two dataverses named Harvard. The dropdown for linking for dataverses was (correctly) not showing root, while the dataset one was, so you would see both. We deleted the test harvard dataverse and also adjusted the logic to not show root (or any parent up the tree) for dataset. So now you should not see any "Harvard Dataverse" at either place.

**Comment by dliburd** [comment]
Verified: Root and parent dataverses do not show up on dropdown list.
