### ISSUE TITLE
Error Messages: Have a way to track error messages users encounter

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2130]
We need a way to track:

1) what error messages are being displayed to users
2) how frequently these error messages are being displayed to users

This will help us determine pain points in the application.

**Comment by pdurbin** [comment]
We could consider using something like https://rollbar.com or https://sentry.io for this. There's also Splunk (or open source equivalents), which I've mentioned at https://github.com/IQSS/dataverse/issues/3428#issuecomment-256912150 and https://github.com/IQSS/dataverse/issues/2879#issuecomment-173223134 . I couldn't agree more that it would great to determine pain points in the application so that we can fix them! 😄

**Comment by mheppler** [comment]
Closing this issue in favor of "Error Reporting: Automatically capture user errors and stack traces, send alerts and store them" #2138

Moved the comment from @pdurbin to that issue.
