### ISSUE TITLE
Clickable URLs in description snippets in search results in v4.0

### ISSUE THREAD

**Issue by garthg** [IQSS/dataverse#2144]
In both version 3 and version 4, search results show snippets of the description (which is very helpful!). In version 3, if the snippet included an html link, then it was clickable from the search result page. However, in version 4, the link shows up only as plain text. It would be great if the clickable behavior present in version 3 was available in version 4 as well. See attached screenshots for examples.

Thank you!

![screen shot 2015-05-11 at 9 49 13 am](https://cloud.githubusercontent.com/assets/1354795/7566236/adf39f40-f7c3-11e4-856c-4874f891f36b.png)
![screen shot 2015-05-11 at 9 48 38 am](https://cloud.githubusercontent.com/assets/1354795/7566237/adf619a0-f7c3-11e4-8dbe-cf4e1754d14f.png)

**Comment by pdurbin** [comment]
Just to clarify, this affect browse as well as search. If you navigate to https://dataverse.harvard.edu/dataverse/antislaverypetitionsma for example you'll see URLs in the descriptions in dataset cards that are not clickable. I was aware of this, which is why I wrote, "For example, if you put a link in a dataverse description, you can click it from the dataverse landing page but not from the card for that dataverse" in the ticket where I worked on stripping HTML while indexing: https://github.com/IQSS/dataverse/issues/1332#issuecomment-77451120

From a code perspective, these are not technically search result snippets. When we're browsing like this it's called `result.descriptionNoSnippet`.

As @garthg points out, this seems to be a browsing feature we've lost in the transition from DVN 3.x to Dataverse 4.0.

I'm also aware the search result snippets shown in cards do not contain clickable links, which is really what this ticket seems to be about. Likewise the Search API doesn't do anything in particular with links. It just returns the snippets as is. It would be up to the client (a mobile app or whatever) to decide whether to identify and render links as clickable.

Related to all this is the "support HTML tags" feature, which is still in deveopment: #1320

**Comment by garthg** [comment]
Thanks @pdurbin for those clarifications!

I think this bug/request would apply any time an html link is shown in a "card". That would include browsing when no snippet is available as well as search results snippets when available. Ideally the links would be clickable in both of those cases.

You also mentioned the Search API handling of links, but for me that is NOT a particular problem at the moment. This bug/request is only intended to apply to the Dataverse web UI.

**Comment by pdurbin** [comment]
@garthg are you still interested in this?

**Comment by garthg** [comment]
Yes, still interested!

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
