### ISSUE TITLE
Allow End Users the Ability to Edit Data Citation

### ISSUE THREAD

**Issue by garthg** [IQSS/dataverse#2146]
Hi,

This might be a fix I could make in the 4.0 configuration somewhere, but I couldn't find it, so any help would be appreciated!

In version 3.x in my Dataverse "Antislavery Petitions Massachusetts" every dataset citation includes the label "Massachusetts Archives, Boston MA". This field appears to be missing from the citations in 4.0 after the migration. You can view a before and after migration example at these two URLs:
old: http://thedata.harvard.edu/dvn/faces/study/StudyPage.xhtml?globalId=doi%3A10.7910%2FDVN%2FBS7ZC
new: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/BS7ZC
See also the attached screenshots for that example.

Thanks for any help!

![screen shot 1](https://cloud.githubusercontent.com/assets/1354795/7569309/e8a6a4ea-f7d5-11e4-827d-c95e4029b3f0.png)
![screen shot 2](https://cloud.githubusercontent.com/assets/1354795/7569308/e8a53998-f7d5-11e4-97ec-7466c22fa696.png)

**Comment by posixeleni** [comment]
@garthg thanks for sending this and sorry for the confusion. In order to be compliant with the Joint Declaration of Data Citation Principles (https://www.force11.org/group/joint-declaration-data-citation-principles-final) we modified the Data Citation in 4.0 to list the repository name that is hosting the dataset and is guaranteeing persistence of this dataset through the DOI we minted for it. For more information on this change please check out our best practices section: http://best-practices.dataverse.org/data-citation

Your role in this dataset is still preserved in the "Distributor" metadata field.

Please let us know if you have any concerns or questions about this.

**Comment by garthg** [comment]
Hi @posixeleni ,

Thank you for the reply. Just to make sure I'm understanding correctly, this means that there is no way for me to adjust the citation format to include the "Massachusetts Archives" distributor as part of the citation at the top of the page?

Thanks,

Garth

**Comment by posixeleni** [comment]
@garthg yes you are correct this is something you cannot change in the citation at the top of the page since we want to make sure we are clear on provenance. Will this be an issue for your datasets?

**Comment by garthg** [comment]
@posixeleni This is an issue for us because we are required to include Massachusetts Archives in our citation for these datasets. What would be the best way for us to do that in the new 4.0 format?

**Comment by posixeleni** [comment]
@garthg Good question. Unfortunately, at the moment, without trying to hack your metadata (add Massachusetts Archives as an author which isnt good metadata practice) there isnt much that can be done.  I am submitting this ticket as a "Suggestion" to our Dataverse Development team to review.

**Comment by mcrosas** [comment]
To be reviewed with @thegaryking

**Comment by mheppler** [comment]
Requirement gathering and discussions about the UI and workflows have started on this feature, as it relates to the Widgets project. Notes can be found on the (Custom Citation Format (FRD))[https://docs.google.com/document/d/1m64RUNhvE_78h92VKfNGaCc8mcy6BTfN6XVW5kGcZBw/edit].

**Comment by pdurbin** [comment]
Related discussion: https://groups.google.com/forum/#!topic/dataverse-community/xnB2lComOrs

**Comment by pdurbin** [comment]
@garthg are you still interested in this?

**Comment by pdurbin** [comment]
Back in 2019-09-16 @djbrooke wrote the following at https://groups.google.com/d/msg/dataverse-community/xnB2lComOrs/3jatRS_FBAAJ

"Hey Everyone,

I talked with Mercè about this briefly and I'm going to try and formulate a response here. :)

The root dataverse always needs to be included on the citation, because if we instead used a non-root dataverse, the data could be moved to another non-root dataverse and in that case the citation would change. In the citation, instead of replacing the root dataverse with a non-root dataverse, she suggested a feature request for keeping the root dataverse and recording multiple dataverses for the citation.

If this is a solution that may work for SP, is this something that you can add to github as a feature request so that we can continue the conversation there? 

Thanks,

Danny"

One thing I'll add is that now that we've shipped #3611 in Dataverse 4.7, if we go with the "multiple dataverses for the citation" approach, each dataverse can be branded separately. I mean, they don't have to have the word "Dataverse" at the end until you want. /cc @amberleahey

**Comment by pdurbin** [comment]
Related: Change the publisher name from root #5841

**Comment by djbrooke** [comment]
This is similar enough to #2297 that I'm OK closing this one as a duplicate.
