### ISSUE TITLE
Creating Dataset templates

### ISSUE THREAD

**Issue by chaudj** [IQSS/dataverse#2164]
Tried creating different  data set templates but it wont give any option to add and remove any meta- data fields.

**Comment by posixeleni** [comment]
@chaudj you can hide, make required or set as optional metadata fields but this is now done at the Dataverse-level. To view this feature go to your Dataverse and click on the Edit button and select "General Information" in the dropdown. Once in General Information scroll down to the metadata options and unselect the pre-selected checkbox "Use metadata fields from Harvard Dataverse" then you will see options under each domain and general metadata for you to make certain fields required, hidden or optional. Make sure you click on "Done" to save your changes. Please let us know if this helps.

@eaquigley we need to make sure the documentation makes this clear and the UI messaging makes it more evident that you can also modify which fields show and are required.

**Comment by mheppler** [comment]
When you first go to the Manage Templates page in a dataverse, there is a help section title How To Use Templates (see screenshot) that outlines this feature is in the General Information page.

Also, in the [Dataset Templates](http://guides.dataverse.org/en/4.5.1/user/dataverse-management.html#dataset-templates) section of Dataverse Management page of the User Guide, there is a note pointing out the "ability to choose which metadata fields are hidden, required, or optional is done on the General Information page for the dataverse".

There also a related issue, *Set Required, Hidden & Optional Metadata Fields At the Template Level #2177* that covers the request to move these settings into the dataset template workflow. Because of that, I am closing this issue as a duplicate.

![screen shot 2016-11-10 at 3 31 20 pm](https://cloud.githubusercontent.com/assets/687227/20193474/25147e8e-a75c-11e6-8946-fc49fe34d7e0.png)
