### ISSUE TITLE
Confirm email address on signup and change

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2170]
Most sites confirm your email address on signup and Dataverse should do the same: https://support.twitter.com/articles/97942-confirming-your-email-address

In a [2015-04-30 Dataverse User Accounts and Auth Meeting](https://docs.google.com/document/d/157sw9gaFGwrb0EtCGGlLMxSg0cooHfKEvIsjcebPcA8/edit?usp=sharing) @mcrosas and I talked about where email addresses come from (institution vs. user-supplied). Perhaps we wouldn't need to confirm email addresses from institutions.

User-supplied email addresses should also be confirmed when the user changes them.

**Comment by pdurbin** [comment]
A user reported this issue today at https://help.hmdc.harvard.edu/Ticket/Display.html?id=216399

**Comment by kcondon** [comment]
Needed to prevent using other people's real email address to create fake accounts, see RT 225535

**Comment by bencomp** [comment]
Email addresses are necessary to allow communication with Dataverse users through the application or outside the application (e.g. for special announcements). It is then essential that the address belongs to the person claiming the address.

I trust the IdPs/IdFederation to provide email address(es) that indeed belong to the user, but in other cases confirmation is appreciated, because the information in Dataverse could be sensitive and needs to be handled only by authorised people. Email address confirmation is a small step to aid authentication.

**Comment by posixeleni** [comment]
We should also add upon sign-up that the user must enter their email address twice in the UI to confirm that this is entered correctly. At the moment we only enter an email once and that could allow for people to put in invalid or incorrect email address. 

Cc/ @eaquigley

**Comment by eaquigley** [comment]
@posixeleni where is the entering of an email address twice requirement coming from?

On Jan 26, 2016, at 9:01 AM, Eleni Castro <notifications@github.com<mailto:notifications@github.com>> wrote:


We should also add upon sign-up that the user must enter their email address twice in the UI to confirm that this is entered correctly. At the moment we only enter an email once and that could allow for people to put in invalid or incorrect email address.

Cc/ @eaquigley<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_eaquigley&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=9M_gkToFlyiMNEe6FMhqKgAfW8r52rMvpo7DSiBpO3k&s=GkQloGGVcAZyvOm8Azf5a2UbsX95W46h0hKMz872OL4&e=>

**Comment by posixeleni** [comment]
@eaquigley here are two examples of a Sign Up page (facebook and patreon) which ask you to re-enter your password when creating your account:
![image](https://cloud.githubusercontent.com/assets/5013837/12583231/a7dd570e-c40f-11e5-887b-66d7267d7fd0.png)

![image](https://cloud.githubusercontent.com/assets/5013837/12583189/7e5a234e-c40f-11e5-8423-20c08a91893c.png)

**Comment by eaquigley** [comment]
@posixeleni, this is for password but your comment was about entering email address twice. Dataverse already has the user enter password twice during account creation.

On Jan 26, 2016, at 9:32 AM, Eleni Castro <notifications@github.com<mailto:notifications@github.com>> wrote:


@eaquigley<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_eaquigley&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=Mwezgf5_frHLeMskLprfcxSR03XH0EJ99L2zuF1dR-g&s=KSy7b4U6MhTPsu9R9i8rd1brVXUJ8TduFQY3CSERjAA&e=> here are two examples of a Sign Up page (facebook and patreon) which ask you to re-enter your password when creating your account:
[image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_5013837_12583231_a7dd570e-2Dc40f-2D11e5-2D887b-2D66d7267d7fd0.png&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=Mwezgf5_frHLeMskLprfcxSR03XH0EJ99L2zuF1dR-g&s=PiIn2RzS1wwgXqXMJrbIR8ehDR-S6tTYrMUEGqMnzLk&e=>

[image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_5013837_12583189_7e5a234e-2Dc40f-2D11e5-2D8423-2D20c08a91893c.png&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=Mwezgf5_frHLeMskLprfcxSR03XH0EJ99L2zuF1dR-g&s=imNhnud6_5aUs_eh958FdvKLSq0qLwBuu2fLVI3Smek&e=>

**Comment by posixeleni** [comment]
@eaquigley sorry i just assume since the title was email confirmation that
this would cover it. Want me to create a separate issue?

On Tue, Jan 26, 2016 at 9:34 AM, Elizabeth Quigley <notifications@github.com
> wrote:

> @posixeleni, this is for password but your comment was about entering
> email address twice. Dataverse already has the user enter password twice
> during account creation.
>
> On Jan 26, 2016, at 9:32 AM, Eleni Castro <notifications@github.com
> <mailto:notifications@github.com>> wrote:
>
>
> @eaquigley<
> https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_eaquigley&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=Mwezgf5_frHLeMskLprfcxSR03XH0EJ99L2zuF1dR-g&s=KSy7b4U6MhTPsu9R9i8rd1brVXUJ8TduFQY3CSERjAA&e=>
> here are two examples of a Sign Up page (facebook and patreon) which ask
> you to re-enter your password when creating your account:
> [image]<
> https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_5013837_12583231_a7dd570e-2Dc40f-2D11e5-2D887b-2D66d7267d7fd0.png&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=Mwezgf5_frHLeMskLprfcxSR03XH0EJ99L2zuF1dR-g&s=PiIn2RzS1wwgXqXMJrbIR8ehDR-S6tTYrMUEGqMnzLk&e=
> >
>
> [image]<
> https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_5013837_12583189_7e5a234e-2Dc40f-2D11e5-2D8423-2D20c08a91893c.png&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=Mwezgf5_frHLeMskLprfcxSR03XH0EJ99L2zuF1dR-g&s=imNhnud6_5aUs_eh958FdvKLSq0qLwBuu2fLVI3Smek&e=
> >
>
> —
> Reply to this email directly or view it on GitHub<
> https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2170-23issuecomment-2D175045980&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=Mwezgf5_frHLeMskLprfcxSR03XH0EJ99L2zuF1dR-g&s=Hw6lOU-pQyBMI0SKC_C8oQRcfosJro9mv8KjJPqvsXU&e=
> >.
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2170-23issuecomment-2D175047813&d=CwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=OiTcIL_jSSCUW82Gf-OSkgnZLbG2Yt87eT87BdLiP54&m=BiDMX0V_hXf1NHjKKiiZYBsQHmzAFgyG3NhTArsNKPk&s=NuGbPjGwJzjpY7HJ7PHi8G8Gfv9KRranheVMfy2v8iI&e=>
> .
>



-- 

Eleni Castro
Research Coordinator, Data Curation and Outreach
IQSS, Harvard University
617-496-0703
http://www.iq.harvard.edu/people/eleni-castro
http://orcid.org/0000-0001-9767-8536


~Got Data? Check out the Dataverse Project. <http://dataverse.org/>~

**Comment by eaquigley** [comment]
@posixeleni oh I'm sorry, I wasn't clear, the images you added to the ticket showed password being entered twice examples

On Jan 26, 2016, at 9:38 AM, Eleni Castro <notifications@github.com<mailto:notifications@github.com>> wrote:

@eaquigley sorry i just assume since the title was email confirmation that
this would cover it. Want me to create a separate issue?

On Tue, Jan 26, 2016 at 9:34 AM, Elizabeth Quigley <notifications@github.com<mailto:notifications@github.com>
> wrote:

> @posixeleni, this is for password but your comment was about entering
> email address twice. Dataverse already has the user enter password twice
> during account creation.
>
> On Jan 26, 2016, at 9:32 AM, Eleni Castro <notifications@github.com<mailto:notifications@github.com>
> <mailto:notifications@github.com>> wrote:
>
>
> @eaquigley<
> https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_eaquigley&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=Mwezgf5_frHLeMskLprfcxSR03XH0EJ99L2zuF1dR-g&s=KSy7b4U6MhTPsu9R9i8rd1brVXUJ8TduFQY3CSERjAA&e=>
> here are two examples of a Sign Up page (facebook and patreon) which ask
> you to re-enter your password when creating your account:
> [image]<
> https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_5013837_12583231_a7dd570e-2Dc40f-2D11e5-2D887b-2D66d7267d7fd0.png&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=Mwezgf5_frHLeMskLprfcxSR03XH0EJ99L2zuF1dR-g&s=PiIn2RzS1wwgXqXMJrbIR8ehDR-S6tTYrMUEGqMnzLk&e=
> >
>
> [image]<
> https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_5013837_12583189_7e5a234e-2Dc40f-2D11e5-2D8423-2D20c08a91893c.png&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=Mwezgf5_frHLeMskLprfcxSR03XH0EJ99L2zuF1dR-g&s=imNhnud6_5aUs_eh958FdvKLSq0qLwBuu2fLVI3Smek&e=
> >
>
> —
> Reply to this email directly or view it on GitHub<
> https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2170-23issuecomment-2D175045980&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=Mwezgf5_frHLeMskLprfcxSR03XH0EJ99L2zuF1dR-g&s=Hw6lOU-pQyBMI0SKC_C8oQRcfosJro9mv8KjJPqvsXU&e=
> >.
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2170-23issuecomment-2D175047813&d=CwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=OiTcIL_jSSCUW82Gf-OSkgnZLbG2Yt87eT87BdLiP54&m=BiDMX0V_hXf1NHjKKiiZYBsQHmzAFgyG3NhTArsNKPk&s=NuGbPjGwJzjpY7HJ7PHi8G8Gfv9KRranheVMfy2v8iI&e=>
> .
>



--

Eleni Castro
Research Coordinator, Data Curation and Outreach
IQSS, Harvard University
617-496-0703
http://www.iq.harvard.edu/people/eleni-castro
http://orcid.org/0000-0001-9767-8536


~Got Data? Check out the Dataverse Project. <http://dataverse.org/>~

**Comment by posixeleni** [comment]
@eaquigley images are correct for email being entered twice but I had a typo in my explanatory text. Fixed this.

**Comment by eaquigley** [comment]
Oooohhhh!!! Thanks @posixeleni!

(This is why I shouldn't try to read issues on the T 🙃)

On Jan 26, 2016, at 9:43 AM, Eleni Castro <notifications@github.com<mailto:notifications@github.com>> wrote:


@eaquigley<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_eaquigley&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=C5VdrQKQM-HQXPAevFmdC95ddOsbIhfPsFWUi7v6pA4&s=QneEmFWkiCbXaApS_uJnIt7qV8GTeZw9EFhpe0ynvvU&e=> images are correct for email being entered twice but I had a typo in my explanatory text. Fixed this.

**Comment by pdurbin** [comment]
http://policy.security.harvard.edu/sa6-appropriate-user-acccess says "SA6: Users must only be permitted to access a server or application after their current business need for access has been established" and lists "Review active accounts" and "Disable account access" under "How to Comply". I'm assigned this issue to myself because @mcrosas @kcondon @whorka and I have discussed how the RCE accounts need to be renewed periodically per http://projects.iq.harvard.edu/user-services/rce-account-renewal and we might want to contact Dataverse users in a similar fashion to make sure they still need access to sensitive data. Accurate email addresses on file per user will facilitate this task, should we choose to require access to data to be periodically re-verified, so this issue is a dependency for non-Shibboleth users (local or builtin users).

**Comment by pdurbin** [comment]
@bsilverstein95 I'm assigning this issue to you to start thinking about the implementation details. I'd suggest looking at how the password reset feature was implemented in #416 in the sense that we email a user a link with a unique token in it. You can see the `passwordresetdata` database table at http://phoenix.dataverse.org/schemaspy/latest/tables/passwordresetdata.html

In order to support this feature we'll need to add a column or two to a user-related database table. I **don't** think we should use the `builtinuser` table, which you can see at http://phoenix.dataverse.org/schemaspy/latest/tables/builtinuser.html . Rather, I think you should use the `authenticateduser` instead, which you can see at http://phoenix.dataverse.org/schemaspy/latest/tables/authenticateduser.html

By using the `authenticateduser` table we'll open the door for making this "confirm email" feature available to both Shibboleth and local/builtin users. @bencomp mentioned at https://github.com/IQSS/dataverse/issues/2170#issuecomment-148338112 that he trusts email addresses coming from his Shibboleth Identity Provider (IdP) but over at https://github.com/IQSS/dataverse/issues/2937#issuecomment-224298892 I'm thinking about "what if the Shibboleth Identity Provider (IdP)" doesn't give us an email address? In that case, we'd need to have the Shibboleth user supply the email address, and any user-supplied email address should be verified.

To me it's an open question of what the behavior should be for a user who does not have a verified email address. (This is all users in any production installation of Dataverse at this point.) Should they not be allowed to create datasets? Should they be allowed to create datasets but not get an email notification that they created one? The latter would be easier to implement... the rule would be that email would only be sent to users with verified email addresses. See the "prevent using other people's real email address to create fake accounts" note from @kcondon at https://github.com/IQSS/dataverse/issues/2170#issuecomment-130063631

**Comment by djbrooke** [comment]
Notes from the meeting on 7/5:

- @eaquigley is going to work with @bsilverstein95 to move this through our usual development process, that is - mockups, user testing, then development and usability testing
- We'll plan to not allow unconfirmed users to take action in Dataverse (uploading, creating, etc.) instead of intervening later in the workflow (such as blocking at the publishing step)

**Comment by bsilverstein95** [comment]
The confirm email project has been split into more than one phase. This issue has come to reflect phase I, which is resolved by pull request #3299. Phase II is described in issue #3300. The feature was divided into phases per the discretion of @djbrooke , @pdurbin , & @mheppler in a meeting on 8/18/16. 

@kcondon please note that the pull request includes an update to the installation guide which describes the scope of phase I. Passing this to QA.

**Comment by kcondon** [comment]
Found 4 issues:
1. math challenge in the validate linked timed out banner has no numerals, see #3036 
2. two different versions of "hey, you need to validate your email" banner message, one is yellow and brown, occurs after you change your email addr on account info page. It says to revalidate your email with the link but does not say where to go to do so. The other is a green success banner when you clock on the 

Yellow:
Info – Your account information has been successfully updated. Your email address changed and must be re-confirmed. Also, please note that the link will only work for the next 1 minute before it has expired.

Green:


3. If you are logged out when click on an expired confirm email link, it brings you to the log in page rather than logging you in as I think was intended.

4. If you are logged in and click an expired confirm email link, sends you to page with the error banner, click on go to account info, then the render shows green check and verified, should not be. And db confirms it is not actually confirmed so render issue of some kind.

**Comment by bsilverstein95** [comment]
Regarding QA issues:

1. Math challenge issue deferred to @pdurbin as he is more knowledgable of that feature. Will be remedied before anything is merged.

2. Yellow info message upon changing your email modified to be green success message, now specifies user's email and instructs them to follow the link sent there. New message body:

**Success!** – Your account information has been successfully updated. Your email address has changed and must be re-verified. Please check your inbox at RonaldRayGun@mailinator.com and follow the link we've sent. Also, please note that the link will only work for the next 24 hours before it has expired.

3. Cannot really fix this -- the functionality of the confirmemail.xhtml landing from an expired / deleted URL token essentially means that if the URL's token is expired (expired tokens are subsequently deleted from _confirmemaildata_ table anytime the page is visited by any user) then there is no way to know a user's _authenticateduser_ identifier unless they are already logged in through another browser tab's session. The error message on the landing page reads "Please navigate to your Account Information page and click the "Verify Email" button." which will be there regardless of if they need to log in first or not. Unfortunately if the user doesn't already have a session open and their link's token is not on _confirmemaildata_ they will need to log in and then manually navigate to Account Information.

4. After much impact of head to desk, figured this one out with Phil's help. The case of this issue was:

- Edit email address on an account whose address is verified currently
- Account Information page would show Not Verified correctly 
- After sent URL expires, if user followed link and then clicked Go to Account Info button the page would falsely show "Verified" indicator next to their email (as Kevin mentioned the email was not verified according to postgres)
- Issue would persist after this until logout

Tacked session.setUser(currentUser); onto the end of the emailChanged = true block of _BuiltinUserPage.java_ to refresh the _authenticateduser_ values the app is using, subsequently got the "Not Verified" indicator and "Verify Email" button to render as they would if the user logged in & out while the issue persisted. Deadend eliminated!

**Comment by pdurbin** [comment]
In a sprint planning meeting today we decided we're going to try to get this pull request in 4.5.1 so I'm giving it that milestone.

**Comment by pdurbin** [comment]
> 1. math challenge in the validate linked timed out banner has no numerals, see #3036

I'm having trouble reproducing this bug so I asked @bsilverstein95 to try as well. The fix will likely be something like 083f279

**Comment by pdurbin** [comment]
@bsilverstein95 helped me reproduce the math challenge bug but I don't know how to fix it. The same math challenge bug was found in the harvesting branch at in #3265 but at https://github.com/IQSS/dataverse/issues/3265#issuecomment-239727104 @scolapasta indicated, "This is not related to this release specifically. It is the math challenge for the general exception. The other math challenge issue is still open for this user case." The other open issue is #3036. So it sounds like all of these math challenge bugs will be fixed once #3036 is prioritized. The easiest way to reproduce this class of bug is to type an incorrect username and password, as mentioned at https://github.com/IQSS/dataverse/issues/3036#issuecomment-229424569

@scolapasta do you have any idea of how to fix #3036? @djbrooke should #3036 be worked on for 4.5.1?

**Comment by kcondon** [comment]
OK, all of the above is correct and sounds like math challenge is grouped with another reported issue. So marking as closed.

**Comment by kcondon** [comment]
Please merge confirmemail.sql with the update db script.

**Comment by pdurbin** [comment]
@kcondon done in fe675b7. Passing back to QA. The script is now called "scripts/database/upgrades/upgrade_v4.5_to_v4.5.1.sql".

**Comment by kcondon** [comment]
OK, looks good, ready for merge.

**Comment by amberleahey** [comment]
I everyone, I'd like to confirm can we run a script or API call to turn this feature on in our 4.10.1 instance? We are noticing users can sign up with fake e-mails etc. because verification of e-mail is not required at sign up. Any help or suggestions for us? We'd like to enable this as it is a security risk. Thanks in advance, best, Amber

**Comment by djbrooke** [comment]
Hi @amberleahey - implementation of the verification mail functionality and the infrastructure to track whether or not an email is verified was implemented as part of a intern project a few years ago (hi @bsilverstein), but we have not yet tied it to the permissions system.  It's something we'll need to work on in the future as we move towards sensitive data support.

**Comment by amberleahey** [comment]
gotcha, okay keep us posted! We would love to see this soonish, I'll reach out if there is someone on our team who can work on this.

**Comment by pdurbin** [comment]
@amberleahey great! Please keep us posted. For now, can you please leave a comment on #3300 because we'd love to hear from you and others what the "consequences" should be of NOT confirming your email address.
