### ISSUE TITLE
Add support for additional dcterms fields in SWORD

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2187]
Comment from @pdurbin 

> @posixeleni as a followup to what I wrote in https://github.com/IQSS/dataverse/issues/1077#issuecomment-96677687 I removed the three fields from the XML example and your crosswalk that I feel have undefined behavior:
> 
> dcterms:identifier
> dcterms:spatial
> dcterms:language
> 
> Let's work with @scolapasta on the plan for these fields since they require a change to the SQL reference data at least, possibly a code change, and testing.

**Comment by posixeleni** [comment]
![image](https://cloud.githubusercontent.com/assets/5013837/7733383/a6abc718-fefc-11e4-8ec9-35263a0cc01f.png)

**Comment by posixeleni** [comment]
@scolapasta my mapping instructions are on this comment https://github.com/IQSS/dataverse/issues/2187#issuecomment-103987351 will assign this to you for now since I will not be around for 4.0.2

**Comment by pdurbin** [comment]
@scolapasta as we discussed, this issue unfortunately involves more work than simply updating the SQL reference data. Two of the three fields are problematic.

dcterms:spatial is no problem. We could easily add support for this.

dcterms:language can't be easily supported because it's backed by a controlled vocabulary and I get and `JsonParseException: incorrect  typeClass for field language, should be controlledVocabulary` error when I try to use it. Please see the stack trace at 2d8977e (in new branch for this issue).

dcterms:identifier can not easily have "agency" added as defined at "Other ID's that directly belong to dataset. If attribute="agency" is included map value to otherIdAgency (e.g., DOI, arXiv, handle, etc)" at https://github.com/IQSS/dataverse/issues/2187#issuecomment-103987351 by @posixeleni above because there is a constraint violation: `ERROR: duplicate key value violates unique constraint "unq_foreignmetadatafieldmapping_0" DETAIL: Key (foreignmetadataformatmapping_id, foreignfieldxpath)=(1, agency) already exists`. I'd like to check with @landreev about this so I left a comment at https://github.com/IQSS/dataverse/commit/2d8977ef4cc7d44772327ac4f7c6d14fa3a184de#diff-881fbe6fa56e7d68e53fc8f68f62cd03R19 in ForeignMetadataFieldMapping.java (also in the branch for this issue).

@scolapasta I'm going to give this ticket to you decide how to proceed. I don't know if it's worth adding dcterms:spatial for 4.0.2 or not. I'd recommend simply moving this issue out of 4.0.2 for now but it's up to you.

**Comment by pdurbin** [comment]
Is anyone out there interested in this feature?

**Comment by pdurbin** [comment]
I don't think anyone is interested in this. Closing. I'm happy to re-open if I'm wrong.
