### ISSUE TITLE
Dataset Metadata UI: make text boxes html friendly

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2193]
from Gary:
please make the text boxes turn into rich text with the buttons etc (like
in openscholar).  that way when we enter the citation, etc., we can add
italics, links, etc.

**Comment by mcrosas** [comment]
@thegaryking and @sbarbosadataverse this issue also needs also additional information before it can be reviewed. There are already several issues related to this, so it would help to be more specific. What metadata fields are we talking about? What citation are we talking about? there is a reason why some fields do not accept formatting or html, because they follow a standard metadata schema and structure so the metadata can be interoperable with other systems. Please provide more info.

**Comment by mheppler** [comment]
This is a duplicate of #1320.

**Comment by eaquigley** [comment]
@mcrosas will review metadata fields spreadsheets created by @posixeleni that lists which fields should have html support.

**Comment by sbarbosadataverse** [comment]
duplicate of #1320
