### ISSUE TITLE
Notebook or Labbook for datasets

### ISSUE THREAD

**Issue by mercecrosas** [IQSS/dataverse#2210]
A suggestion from Dustin Tingley (also requested by other users from different scientific domains):

Connect a dataset with a labbook or notebook, or more generally a documentation stream that a researcher produces that documents semi-regularly issues that come up in the research process.

This could be implemented by having a metadata field in the dataset that points to the labbook. It could integrate either with labbok.org or ipython notebook.

**Comment by tingleyd** [comment]
For the persistence issue you point to in your email Merce, my idea there was that DV would just query the text contents of the link so it would be stored on DV side. This was just to make it simple for users to update regularly, but have those updates stored within a DV log. But, if there is an ipython way that would be most robust and get you additional features, that is cool. 

My primary concern here is it has to be hyper easy (as G points to too), Hence, having single sign on type setup for labbook.org. This doesn't exist as a domain name yet but could, allowing you ways to let people use the site for writing their labbook, and then encourage them to setup a DV study so it logs their progress. This may habitualize them to subsequently post their replication data, or use other DV features..... 

dt

**Comment by pdurbin** [comment]
Since IPython Notebook has been mentioned I'd be remiss if I didn't link to the conversation with @fperez over at https://github.com/IQSS/dataverse-client-python/issues/6

What's interesting is that what @tingleyd seems to be describing sounds like Dataverse would **pull** (query) some other system for updates. This sounds a bit like [harvesting](http://en.wikipedia.org/wiki/Open_Archives_Initiative_Protocol_for_Metadata_Harvesting) (#813) or maybe [ResourceSync](http://www.openarchives.org/rs/toc) or [SHARE](https://github.com/CenterForOpenScience/SHARE) (both mentioned in #900). Anyway, I'm curious what the mechanism or protocol would end up being. (The remote lab notebook could always **push** data into Dataverse via [SWORD](http://guides.dataverse.org/en/latest/api/sword.html) if it knows that protocol.)

I'm also curious to hear more about what is being proposed for single sign on. It sounds like good fodder for discussion in the [Dataverse Auth Community Group](http://community.dataverse.org/community-groups/auth.html). :)

**Comment by tingleyd** [comment]
Curious whether this idea is making any progress.

**Comment by mcrosas** [comment]
@tingleyd no progress yet, but will be reviewed soon - @eaquigley and @scolapasta are going through the backlog of issues to prioritize. The process will be to first define well the requirements and come up with a proposal to review.

**Comment by pdurbin** [comment]
@tingleyd RSpace ( https://www.researchspace.com ) is an electronic lab notebook that now integrates with Dataverse:

- screenshots: https://groups.google.com/d/msg/dataverse-community/BDnbtyccFbo/ouaTJ0QYAwAJ
- video: https://www.youtube.com/watch?v=avf3tEbcNvQ
- slides for "RSpace and Dataverse: Integrating an Electronic Lab Notebook with a Data Repository": https://osf.io/xvrk5/ via https://projects.iq.harvard.edu/dcm2017/agenda

Is that enough to close this issue? If not, should we make it more specific? We're trying to work in smaller chunks these days.

**Comment by tingleyd** [comment]
Yes, I'd say this is way more than what I had in mind but it seems to cover
the use case and beyond! Great to see.


Dustin Tingley
Government Department
Harvard University
http://scholar.harvard.edu/dtingley

**Comment by pdurbin** [comment]
@tingleyd thanks for getting back to me so quickly! Since this issue was originally added based on your suggestion, I'm going to close it out but others watching this issue who are interested in specific integrations with software other than RSpace should open a fresh issue mentioning the tool in question. Thanks!
