### ISSUE TITLE
Dynamic Charts for (Tabular) Data Files

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2216]
Visually explore tabular file by creating charts, that can be exported, shared, etc.

FRD: 
https://docs.google.com/document/d/1RzcZ9qaSZauDEKbwO9M3_QAb-qIptk7J0spW1xYu-5o/edit

**Comment by mheppler** [comment]
Mock ups, in progress:
https://iqssharvard.mybalsamiq.com/projects/chartingdata-dataverse/grid

**Comment by eaquigley** [comment]
@raprasad can you move this issue into the data viz github repository and assign to the appropriate intern

**Comment by pdurbin** [comment]
Anyone interested in this issue may want to participate in this Tuesday's community call because Scholars Portal will be giving a demo of their new "DDI Explorer" app. For details on how to call in, please see https://groups.google.com/d/msg/dataverse-community/Zpib-uCIG1g/Rg9tJGieBAAJ

**Comment by pdurbin** [comment]
The code for Data Explorer by @kevinworthington is at https://github.com/scholarsportal/Dataverse-Data-Explorer and he gave a nice talk about it at the community meeting: https://projects.iq.harvard.edu/dcm2017/agenda .

**Comment by kevinworthington** [comment]
Thanks for including these links @pdurbin. The latest Data Explorer can be tested at https://scholarsportal.github.io/Dataverse-Data-Explorer/?uri=https://dataverse.scholarsportal.info/api/access/datafile/47298/metadata/ddi&&locale= which includes cross tabulation :)

**Comment by pdurbin** [comment]
@kevinworthington cool, I'm having fun playing with my "open source at Harvard" dataset at https://scholarsportal.github.io/Dataverse-Data-Explorer/?uri=https://dataverse.harvard.edu/api/access/datafile/3035125/metadata/ddi . Thanks! 😄

**Comment by kevinworthington** [comment]
Hi @pdurbin,
Glad you like it though the cross-tab feature will not yet work when accessing data for Dataverses other than Scholars Portal. This is due to a AJAX tab file net::ERR_CONTENT_LENGTH_MISMATCH error reported in Jan 31, 2017. The short-term workaround for us was the addition of a servlet to enable loading the tab file columns, found here https://github.com/scholarsportal/SP-dataverse/blob/SP_v4.6.1.1/src/main/java/edu/harvard/iq/dataverse/export/ReadFile.java

Here's a bit better example for playing around
https://scholarsportal.github.io/Dataverse-Data-Explorer/?uri=https://dataverse.scholarsportal.info/api/access/datafile/10548/metadata/ddi&&locale=

**Comment by donsizemore** [comment]
@kevinworthington This is wonderful! We've been toying with DDI Explorer on a test machine, and after seeing your comment added ReadFile.java to a 4.7 build. Both table- and chart views are working well. Great work!

**Comment by pdurbin** [comment]
@kevinworthington thanks for opening #4249 about making your Data Explorer tool available from Dataverse.

I'm not sure what this issue is about anymore. Who is the stakeholder? The FRD linked above hasn't been touched since 2015. Vote to close.

**Comment by pdurbin** [comment]
Support for Data Explorer (#4249) was shipped in Dataverse 4.8.6! Closing.
