### ISSUE TITLE
Permissions page: explain relationship between the access settings and the user/groups

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#2255]

**Comment by scolapasta** [comment]
Mentioned by @bencomp during a demo.

**Comment by scolapasta** [comment]
Another coomment - more explanation about the inheritance of role and grouops (through child dataverses)

**Comment by bencomp** [comment]
And @eaquigley was there too :)

As a user managing permissions for a dataverse, I found it not so obvious that the "edit access" section is a shortcut for the more generic role/permission assignment in the second section.

For example, why does the top section only allow the contributor and curator roles? How the top section is expanded by default and the second section is collapsed suggests that the top section is obligatory to use.

**Comment by eaquigley** [comment]
Text for the Permissions tab in the Dataverse permissions page: 

Already know if all users should be able to add to your dataverse or only certain users? Select who should be able to add dataverses and/or datasets by clicking the Edit Access button.

**Comment by mheppler** [comment]
Improved messaging on the dataverse and file Permissions pages. Worked with @eaquigley on an improved placement and wording of the help text, mainly by moving the brief section descriptions to the panel header, so the settings contained in each are more obvious upon first viewing the page.

Committed changes to a new branch titled "2016-01-ux-branch". This is branch is not associated with a milestone, which is why none is selected for this ticket.

![screen shot 2016-01-05 at 3 36 22 pm](https://cloud.githubusercontent.com/assets/687227/12127557/f0de0426-b3c5-11e5-9f0e-86c0dadb1de1.png)

**Comment by bencomp** [comment]
I like the placement of the panel descriptions, but the relation between "Permissions: Current access configuration..." and "Users/Groups: All the users and groups..." is not what I understand to be "Limited options for access control" and "Full options for access control".

You can skip "Edit Access" and go to "Users/Groups" for full control. "Edit Access" only allows to set the DVN3-style access options, whereas I like the role "Dataset Creator" better than "Contributor", which isn't available under "Edit Access".

**Comment by pdurbin** [comment]
I just merged this into the 4.3 branch per my comment at https://github.com/IQSS/dataverse/issues/2852#issuecomment-170628537

**Comment by kcondon** [comment]
OK, I see the added text, same as in the other ticket. Not sure if this can be closed? @eaquigley 

My personal take on the meaning of the two sections are:
permissions: define a general contribution model.
user/groups: assign permissions on an individual user or group basis.

**Comment by bencomp** [comment]
IMHO the meaning of each permission should be very clear and not subject to personal views.

As far as I can tell, for edit access there are the following roles and permissions that allow users to add datasets:

- dataset creator: you can add datasets and edit your own
- contributor: you can add datasets and edit your and others' datasets, submit them for review
- curator: you can add datasets, edit your and others' datasets and publish them

In DVN 3.6 the difference between dataset (well, study) creator and contributor depends on a setting in a dataverse that determines the meaning of the contributor role. I think there is just enough documentation to guide a dataverse admin to make the right choice in DVN 3.6, but I had to find out the differences in permissions for myself in Dataverse 4 (cue "read the user manual" :)).
I find the *Edit access* panel insufficiently clear about this very distinction, or the assumption that users are happy to have their datasets edited by fellow contributors debatable. (You could argue that instead of allowing users to create datasets, they should be allowed to create dataverses, but our partners' data librarians cannot easily track what is going on in subdataverses, per #2447.)

**Comment by kcondon** [comment]
Ben, you yourself are offering a personal opinion in an attempt at arriving at a mutually beneficial solution.
This is how people reason.

________________________________

**Comment by bencomp** [comment]
Fair point, @kcondon. I didn't mean to attack you and I'm sorry for my harsh comment.

**Comment by kcondon** [comment]
It's ok, I'm having a tough morning ;) Gustavo and I were discussing the underlying issues and trying to get at the essential problem: what is  the exact behavior and consequences of making selections in the permissions/edit access panel and then correspondingly how to communicate that well. We do have business cases that require this support, particularly Journal workflows, so we need something like this, at least for our installation.

**Comment by eaquigley** [comment]
@bencomp i wanted to clarify that in the edit access section of this page, by default the configuration is that no one can add dataverses or datasets (as can be seen in the image below). a user will need to go in and select the ability for anyone to be able to add sub dataverses or datasets as well as if they can edit or not.

![screen shot 2016-02-08 at 11 44 40 am](https://cloud.githubusercontent.com/assets/5922904/12892645/129c5f40-ce5b-11e5-86a0-fc401ea765b4.png)

I've been floating around the idea of adding some text at the top of the page (outside of the panels) that gives a little bit more information about this page as well as the purpose of the panels. I think that can help clear up the haziness of the relationship between Permissions and Users/Groups panels. I'll add the text into this issue once I have it written up.

**Comment by eaquigley** [comment]
While reviewing this issue, @mheppler and I have realized there are several issues with the Permissions panel. Inconsistencies with text and nothing alerting a user to the impact of them changing those settings. Will review at a high level and use @mheppler's FRD-lite idea that was created for permissions and file ux issues.

**Comment by bencomp** [comment]
After the [recent conversation in the Community group](https://groups.google.com/forum/#!topic/dataverse-community/G9TMVnhab5A) between @pdurbin and @shlake, I realised this morning that I had overlooked something pretty essential: apart from the roles *dataset creator*, *contributor* and *curator* at the *dataverse* permission level, there are *dataset* level roles called *contributor* and *curator*. And the top panel is *not* the "simple" interface for managing roles in the dataverse - it is essential for managing permissions (when datasets can be added to the dataverse).

I feel a little silly for assuming that the relationship between the top and middle panels was "simple" and "advanced" role management. On the other hand I agree with @eaquigley and @mheppler that the impact of changing these settings could be made clearer. And suddenly I understand @pdurbin's email in the [discussion on role inheritance from dataverse to dataset](https://groups.google.com/forum/#!topic/dataverse-community/XjodQ6bQjFg) too! :)

**Comment by pdurbin** [comment]
@bencomp yes, the top panel is essential because it allows you to choose between "Contributor" (the default) and "Curator" when answering the question, "What should be the default role for someone adding datasets to this dataverse?"

![dv3](https://cloud.githubusercontent.com/assets/21006/15508168/6394d046-219c-11e6-8dd5-a50aef17544c.png)

If there is an API call to control this I'm not aware of it ( @scolapasta or @michbarsinai do you know? ). It would be handy as I write API tests for #1070.

**Comment by mheppler** [comment]
This feature was delivered as part of the pull request [#3346](https://github.com/IQSS/dataverse/pull/3346) and merged into develop.

**Comment by kcondon** [comment]
Looks good, extra text, popup. Closing
