### ISSUE TITLE
Stata: investigate handling of values for factor

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#2262]
Currently, we store the number value for the factor, but Two Ravens needs the label.

Add an API that when getting these values, you can decide for either number or semantic value.

**Comment by landreev** [comment]
Is this still needed? 
Because the conclusion of the meeting we had with Vito was that he was happy with the way it was. 
Once we explained that the numeric values-to-labels mapping was already provided in the DDI metadata. 
Personally, I would hold on implementing this extra API functionality until we have a need/use case for it. 
And as for the ingest aspect of it, I am very confident that this is the right behavior (to save the categorical data vectors as numeric in the tab files). The way it is organized in Stata, it is pretty  clear that these numeric values ARE the data, and the string values are simply added descriptive labels.

**Comment by mcrosas** [comment]
Let's check with @tercer before closing it.

**Comment by tercer** [comment]
As long as, as @landreev says, " numeric values-to-labels mapping was already provided in the DDI metadata. " then we're fine.  We can reopen this if there appears on inspection to be anything askew or missing in what gets into the metadata.  Thanks.
