### ISSUE TITLE
Service to extract data from images and papers and store as dataset in Dataverse

### ISSUE THREAD

**Issue by 4tikhonov** [IQSS/dataverse#2272]
I've discovered the way to extract datasets from almost any scans or printed media in the tabular form. Data can be pushed back to Dataverse storage.

Typical use case: user can upload some image in own dataverse and click on "dataset extract" button. If there are some values in the scan it can convert all data in Excel file (for example) and store it in the same dataverse as separate file with the same name as image.  

Just let me know if you're interested in the implementation of this use case. It can be implemented as separate service that can get image from Dataverse, do extraction and deliver back Excel files.

**Comment by pdurbin** [comment]
When I think of extracting from documents I think of Tika ( https://tika.apache.org ) but the Tika use case, from what I understand, is mostly about extracting text from indexing and search purposes.

This sounds different. You upload a PNG or PDF or Word doc to this service and it gives you an Excel file back. The software finds the tabular data for you. It sounds neat. I do agree that it probably makes sense as a separate service that Dataverse could perhaps call into some day. I've definitely seen cases where tabular data is locked up on page whatever of a Word document.

**Comment by 4tikhonov** [comment]
No, there is Tabula engine and it's working fine. The only task is to build web service around it to upload documents and download tabular data. If community thinks it's good idea to extend the basic functionality with feature like that I can create it.

**Comment by pdurbin** [comment]
@4tikhonov thanks for [clarifying](http://irclog.iq.harvard.edu/dataverse/2015-06-16#i_20914) that you mean https://github.com/tabulapdf

From digging around in old emails I'm realizing that @posixeleni first pointed out a [blog post about Tabula](https://source.opennews.org/en-US/articles/introducing-tabula/) in early 2013! Back then she linked to a demo at http://tabula.nerdpower.org but it seems to have gone dark.

Also, it turns out @kaythaney is familiar with @tabulapdf, saying:

> "would love to hear of people's experiences using that for research" -- http://logs.glob.uno/?c=mozilla%23sciencelab&s=16+Jun+2015&e=16+Jun+2015

**Comment by jeremybmerrill** [comment]
Just wanted to say hello -- I'm one of the maintainers of @tabulapdf, along with @mtigas and @jazzido, which extracts tabular data from PDFs. We're obviously big fans of Moz Science. Let me know if there's anything we can do to help.

Our project is in a bit of flux right now -- we're almost (but not quite!) done replatforming the extraction engine from JRuby to Java. Next on the list after that is splitting the UI into a web API and a JavaScript frontend.

[This HTTP API project](https://github.com/tabulapdf/tabula-api) may be of interest to you. The idea is that you can post a PDF and some coordinates and get your table back without any graphical interaction. We don't have a streaming API, but there's no reason in principle why that wouldn't work. And in fact, it'd be a great fit for the new Java-platformed extraction engine, since streaming APIs seem to be idiomatic in Java.

(I don't *think* we have a working demo of Tabula on the web right now.)

**Comment by pdurbin** [comment]
Related to #3302.

**Comment by pdurbin** [comment]
@jeremybmerrill thanks for commenting.

@4tikhonov are you still interested in this?

**Comment by djbrooke** [comment]
Closing. We will reopen this if we decide to integrate. Note the similar work going on related projects at Harvard: https://github.com/dell-research-harvard/Break-the-Page
