### ISSUE TITLE
Index Utility: Allow (re)indexing of an arbitrary list of dv objects

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2279]
Since indexing can be a costly operation and we occasionally have need of (re)indexing datasets and dataverses such as in moving them, related #2226, #2278, it would be good to also have an index utility that accepts an arbitrary list of dv object ids and it will reindex them.

**Comment by pdurbin** [comment]
The other day @sekmiller asked if this is possible. It is possible but it's not documented. We should add it next to the stuff at http://guides.dataverse.org/en/4.6.1/installation/administration.html#solr-search-index but that whole "administration" page should be absorbed into the Admin Guide. When that page was created there was no Admin Guide.

**Comment by pdurbin** [comment]
I'm not sure what the definition of done is for this issue but I'd like to point out that letting @lmaylein know that he could re-index an individual dataset like this...

curl http://localhost:8080/api/admin/index/datasets/70

... was a good workaround for the production problem he has in #5575.

Also, these days we have http://guides.dataverse.org/en/4.11/admin/solr-search-index.html so that's the page to edit for a pull request. This one: https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/admin/solr-search-index.rst

**Comment by pdurbin** [comment]
@donsizemore and I chatted at http://irclog.iq.harvard.edu/dataverse/2019-03-14#i_88055 and he's going to document how to reindex a dataset by persistent id as well. Thanks! I also pointed out that he's welcome to work on #2593 since he mentioned documenting "destroy" commands.

**Comment by pdurbin** [comment]
More chatter this morning at http://irclog.iq.harvard.edu/dataverse/2019-03-15#i_88073 about how @donsizemore plans to address #2593 in the same pull request.

**Comment by pdurbin** [comment]
Whoops! Never mind! Separate pull requests! My mistake. 😄
