### ISSUE TITLE
VMWare image with preinstalled Dataverse instance

### ISSUE THREAD

**Issue by 4tikhonov** [IQSS/dataverse#2280]
It can be really helpful for the community to provide image that can be downloaded in imported in VMWare (for example). We're busy with testing a lot of features and developing really experimental stuff so this image with installed and configured Dataverse, SOLR, postgresql and other stuff can be really useful for QA testing, also people can test new features in their own sandbox.

I used to contribute to other open source community for library system called Evergreen Open-ILS and they had really nice example how to distribute complete image with some imported records just to make possibility for people to try the system upgraded with new experimental features on their own stuff: 
http://evergreen-ils.org/dokuwiki/doku.php?id=vmware:gentoo

Just let me know if it's possible to create the same image for Dataverse (can be CentOS, Ubuntu, etc).

**Comment by pdurbin** [comment]
Just this week someone was asking about VMWare images at https://help.hmdc.harvard.edu/Ticket/Display.html?id=217494

It sounds like @4tikhonov is willing to make the first one at least: http://irclog.iq.harvard.edu/dataverse/2015-06-18 :)

**Comment by abhiiiss** [comment]
Thanks for starting this thread. Having VM will be great for us as we need not to select Linux Distribution and get rid of looking for several dependency files.
And if we can just press
sudo ./install
its all done...

**Comment by din2011** [comment]
Can somebody provide something like this for Dataverse version 4.0 ? https://github.com/dvn/dvn-install-demo

**Comment by 4tikhonov** [comment]
I also think it will be nice to run demo Dataverse 4.0 instance on Amazon EC2. Something like that:
https://aws.amazon.com/marketplace/pp/B00A6KUVBW/ref=mkt_ste_l2_ec2_f1?nc2=h_l3_c

People can do their tests in the realtime and every day the virtual server can be reset to the initial state.

**Comment by pdurbin** [comment]
> Can somebody provide something like this for Dataverse version 4.0 ? https://github.com/dvn/dvn-install-demo

@din2011 I replied at https://github.com/dvn/dvn-install-demo/issues/4#issuecomment-113098107 as well but this "dataverse" git repo already has a Vagrantfile in the root. That means you should be able to run `vagrant up` and get a working Dataverse installation at http://localhost:8888 per http://guides.dataverse.org/en/4.0/developers/tools.html#vagrant

**Comment by 4tikhonov** [comment]
Well, I've installed Dataverse 4.01 on Ubuntu 14.04 and already did all QA tests. It's working fine so just let me know if you're interested to get the virtual image. Phil, probably you have some special space in the organization where I can upload it or I can just share Dropbox folder?

And second question: I can fill virtual image with some datasets just to make quick demo of the functionality of Dataverse. Do you need something like that or it should be just empty installation from scratch?

**Comment by abhiiiss** [comment]
This is Great!
An empty one will be great...
Love to get Dropbox link...
Regards
Abhi

**Comment by pdurbin** [comment]
@4tikhonov thank you very much for producing a VMWare image of Dataverse! Let me check with @mcrosas and @eaquigley if they think we can stick it somewhere on http://dataverse.org . I assume we'd flag it as "community contributed" or something but otherwise I think we'd be happy to put it somewhere under the main Dataverse domain. I'll give this to @eaquigley for consideration.

**Comment by abhiiiss** [comment]
Hi @4tikhonov,  can u please share Dropbox link to enable  me testing
immediately. Or we need to wait till it gets a place in Dataverse.

@4tikhonov <https://github.com/4tikhonov> thank you very much for producing
a VMWare image of Dataverse! Let me check with @mcrosas
<https://github.com/mcrosas> and @eaquigley <https://github.com/eaquigley>
if they think we can stick it somewhere on http://dataverse.org . I assume
we'd flag it as "community contributed" or something but otherwise I think
we'd be happy to put it somewhere under the main Dataverse domain. I'll
give this to @eaquigley <https://github.com/eaquigley> for consideration.

—
Reply to this email directly or view it on GitHub
<https://github.com/IQSS/dataverse/issues/2280#issuecomment-114110952>.

**Comment by pdurbin** [comment]
I'm fine with @abhiiiss trying out the VMware image @4tikhonov created before we post it somewhere under dataverse.org. It would be a good sanity check. I don't think the Dataverse team has a great way to test a VMware image anyway.

**Comment by 4tikhonov** [comment]
Well, I can upload the image to Dropbox of course, there is no problem. The only thing there is functionality to send different mails around Dataverse and I need to figure out how to make it work after the import of the VMware image.

**Comment by abhiiiss** [comment]
Hi everyone... are we getting VM?

Senior Scientist (Biometrics)|Research Program on Grain Legumes|

International Crops Research Institute for Semi-Arid Tropics (ICRISAT)|

Patancheru| Greater Hyderabad|

Andhra Pradesh - 502 324, India|

* email: a.rathore@cgiar.org | reach2abhi@gmail.com <reach2abhi@gmail.com>

( telephone: +91 (40) 3071 3413 (Office) +91 96 7640 3413 (Mob)| Ê fax: +91(40)
3071 3074/75|

website: www.icrisat.org

**Comment by 4tikhonov** [comment]
Yes, I've shared the VM for the team and already got the results of first QA tests. After we'll fix some small issues it will be open for the public.

**Comment by abhiiiss** [comment]
Thanks a lot. Can I please get even developmental one to have a feel?

**Comment by 4tikhonov** [comment]
Sure, just send me request on 4tikhonov at gmail.com

**Comment by pdurbin** [comment]
How is the testing going? These images came up in [a Google Doc about reorganizing the Installation Guide](https://docs.google.com/document/d/1GLky44JbtCNhGuavLXGEP8WPNdjbyHNxalEGjR78MaA/edit?usp=sharing) but as of this writing these images are not something the Dataverse team at @IQSS can support. We don't have any experience with such things.

**Comment by abhiiiss** [comment]
@pdurbin Creating images are fairly easy job, and this is going to be next hot item as world is heading towards Virtualization and indeed, I am no more installing dataverse on a physical system. We are working on cloud.

**Comment by pdurbin** [comment]
@abhiiiss would you be able to write a script that creates the images? And maintain the script over time?

I'm not opposed to the idea but someone has to commit to the work for it to be sustainable.

**Comment by abhiiiss** [comment]
Dear @pdurbin Presently, I am myself struggling with a clean installation of dataverse 4.x and hence may not do it as of now. I use VMs and OS images for many of our other jobs and found it very useful even for production mode. @4tikhonov is doing great help to me by working on this. He tried to help me, and I am sure he will do it also, but I still feel if it come from dataverse team will be great help to user community who can test and use it just in few clicks and will almost zero knowledge of Linux.

**Comment by eaquigley** [comment]
@pdurbin i don't think this ticket should be assigned to me. i won't have anything to do with the testing of the VMware. I understand there is the need to figure out where to host a link to it on dataverse.org but that and the testing of it are two different things. I don't want the testing to get lost because I have the this.

**Comment by pdurbin** [comment]
@eaquigley yeah, Iet's leave it unassigned, I guess, until there is a VMWare image to link to.

@4tikhonov any plans to post the image you created on Dropbox or similar? If so, a readme with contact information on how to reach you would be appreciated since would be a community-supported effort. Creating and supporting VMWare images is not something the Dataverse team at @IQSS can do at this time. We might need to close this issue as "WON'T FIX" or whatever, depending on the answer from @4tikhonov .

**Comment by pdurbin** [comment]
@kcondon I'm going to send this your way to close if you see fit. I don't think there's anything actionable given available resources. Heads up to @scolapasta 

@eaquigley @mheppler you helped craft the "suggestion" workflow at https://raw.githubusercontent.com/IQSS/dataverse/develop/doc/sphinx-guides/source/img/feature-request-process.png so I don't know if you have any opinions on this. The main reason I'm even looking at this issue is that it's link to from the [Installation Guide reorg](https://docs.google.com/document/d/1GLky44JbtCNhGuavLXGEP8WPNdjbyHNxalEGjR78MaA/edit?usp=sharing) doc I'm using for guidance while working on #2884

**Comment by kcondon** [comment]
Closing this issue but will keep idea of VM as part of future tools discussions.
