### ISSUE TITLE
Dataset File Request Access: Support/integrate custom approval forms into restricted file access workflow.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2281]
MRA and Harvard Population Center/ Work and Family are dataverses that have a lot of restricted files and require a custom form to be approved before access to restricted files can be granted.

Currently, this custom form is external to Dataverse, on their projects' sites, and users are directed to the form via a link in the dataset metadata.

Ideally, these use cases can be integrated into our normal request access model, perhaps via enhancing the guestbook functionality as suggested.

For now, reported UX issues are:
1. Being able to present the friendly message that they need to complete a form elsewhere in a prominent place.
-The current terms of access area is seen as somewhat hidden.
-Using the metadata notes field was seen as not ideal since notes is not a "permanent" part of the DDI and so support for it may change between versions.
-Enabling request access is on the right track but was not recommended since a busy administrator may not realize the form part of the workflow was not completed and could lead to granting access without proper approval (workflow does not integrate the checkpoint for form submission and approval).
1. Disabling allow requesting access presents a misleading message in the field indicating requesting access to files is not allowed.
   -It was suggested that the message in this field be specified by the user rather than automatically generated.

**Comment by sbarbosadataverse** [comment]
From today's meeting, we decided that a "see terms" button feature is recommended to satisfy the workflow for *RESTRICTED data without REQUEST ACCESS enabled because TERMS request some sort of action (application form, email with details, etc...)



![fullsizerender](https://user-images.githubusercontent.com/8322346/30081377-ed224d0a-9254-11e7-9f64-6313b3dcb245.jpg)

**Comment by pdurbin** [comment]
@mdmADA it seems like you're delivering a solution in this issue pull request #5863.

**Comment by mdmADA** [comment]
Hi @pdurbin - Yes, this is the first change towards implementing a solution. The ADA solution I implemented in our fork has the guestbook at 'request access' instead of at 'download' so it doesn't use 'custom approval forms' as indicated in this thread's title, it reuses the guestbook but moves the launch point (and adds functionality to allow decision makers to view the guestbook details). The goal is to make it configurable as to where the guestbook is launched - at request access or at download (anywhere else?).

**Comment by pdurbin** [comment]
> The goal is to make it configurable as to where the guestbook is launched - at request access or at download (anywhere else?).

Users are prompted to sign guestbooks when attempting to download files and the other main time is when they are attempting to explore files with external tools using the "Explore" button: http://guides.dataverse.org/en/4.14/installation/external-tools.html

Thanks for replying so quickly!

**Comment by mdmADA** [comment]
Yes, Explore has to be accounted for as well. 

If a file is set as Restricted, a user would have to request (and be granted) access to be able to explore it, correct?

**Comment by pdurbin** [comment]
@mdmADA right, Here's an example of a restricted tabular file that doesn't show the "Explore" button until one goes through the Request Access workflow: https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/U2BAWN/1ROQV2

Of course, it's also possible for dataset owners to not show the "Request Access" button. Here's an example: https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/EU6DZS/HUDBOP

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
