### ISSUE TITLE
Installation and/or administration guide should list configuration options

### ISSUE THREAD

**Issue by bencomp** [IQSS/dataverse#2283]
To help setup and maintenance of a Dataverse installation, a guide should list and explain configuration items, i.e. settings, paths on the file system, connection strings, passwords, etc.

Some things I came up with for DataverseNL's in-Dataverse settings are:
- API tokens obligatory? #1838 
- who are superusers?
- what email address is behind Dataverse Support
- what to search by default: Dataverses, datasets, files
- facets to show by default at top level
- what roles other than builtin roles must be defined?
- migration decision: what to do about published datasets within unpublished dataverses

Before running the installer, sysadmins should know where to install GlassFish, where to store datasets, what user and password are used for the PostgreSQL connection, etc. These items should probably be listed in the installation guide.

The administration guide (also used by superusers, #1574) would help make sure that no configuration item is forgotten after the initial setup.

Perhaps at some point in the future, this list could be a source for Chef recipes, Ansible playbooks or X Ys for managing a Dataverse installation and configuration.

**Comment by pdurbin** [comment]
> a guide should list and explain configuration items

There's a "configuration" section in the installation guide improvement and reorganisation proposal linked from https://groups.google.com/forum/#!msg/dataverse-community/qujUFJDYXG0/0BhECCp0HQAJ

That would probably be a good place to jot down ideas. Here's a direct link to the doc: https://docs.google.com/document/d/1GLky44JbtCNhGuavLXGEP8WPNdjbyHNxalEGjR78MaA/edit?usp=sharing

> Perhaps at some point in the future, this list could be a source for Chef recipes, Ansible playbooks or X Ys for managing a Dataverse installation and configuration.

Anyone interested in such things should definitely check out the fantastic work by @lwo at https://github.com/IQSS/dataverse-puppet

**Comment by pdurbin** [comment]
> where to store datasets

@bencomp do you mean where the **files** are stored on disk?

I'm looking at feedback from @pameyer that says, "file storage location (which I was able to infer is in the glassfish domain by seeing where new files ended up)". From a quick look at scripts/installer/install it looks like `$FILES_DIR` gets set to `$CONFIG_DEFAULTS{'GLASSFISH_DIRECTORY'} . "/glassfish/domains/" . $ENV{'GLASSFISH_DOMAIN'} . "/files"` which later gets used by scripts/installer/glassfish-setup.sh as `./asadmin $ASADMIN_OPTS create-jvm-options "\-Ddataverse.files.directory=${FILES_DIR}"`.

Maybe the two of you could collaborate on the [reorg proposal](https://docs.google.com/document/d/1GLky44JbtCNhGuavLXGEP8WPNdjbyHNxalEGjR78MaA/edit?usp=sharing) for how you'd like this to be documented.

Since that JVM option is configurable I assume it doesn't really matter where files are stored? Dataverse doesn't care? @landreev would know for sure. In https://github.com/IQSS/dataverse/blob/develop/scripts/deploy/phoenix.dataverse.org/install I use `FILES_DIR=/usr/local/glassfish4/glassfish/domains/domain1/files` but I assume this could go other places.

**Comment by lwo** [comment]
We use it to point to a mount
/data
with the owner set to glassfish

**Comment by bencomp** [comment]
@pdurbin yes, that is what I meant. We also point to a mount at /data, coincidentally. The storage location may not matter to Dataverse (and from comments in the code I infer that @landreev envisions that Dataverse will at some point abstract away from file systems), but you need to plan (and monitor) the size and available space on the data volume(s).

I'll add a comment to the reorg proposal (that really shouldn't be a proposal for much longer).

**Comment by pdurbin** [comment]
In my pull request at #2895 I added many configuration options and you can preview the change at http://guides.dataverse.org/en/2884-install-guide-reorg/installation/config.html

I did omit a couple database settings that are truly developer-only feature flags that people installing Dataverse should ask about before using.

@bencomp I hope these pages help answer your "before running the installer" concerns:

- http://guides.dataverse.org/en/2884-install-guide-reorg/installation/prep.html
- http://guides.dataverse.org/en/2884-install-guide-reorg/installation/installation-main.html

The difference between a superuser and the Admin role is explained at http://guides.dataverse.org/en/2884-install-guide-reorg/installation/config.html#root-dataverse-configuration

System email address: http://guides.dataverse.org/en/2884-install-guide-reorg/installation/config.html#systememail

Facets config: http://guides.dataverse.org/en/2884-install-guide-reorg/installation/config.html#customizing-the-root-dataverse

Migration: http://guides.dataverse.org/en/2884-install-guide-reorg/installation/upgrading.html

Roles should be documented in the User Guide. @eaquigley is there an issue for this?

@lwo has created https://github.com/IQSS/dataverse-puppet and @donsizemore has written https://github.com/IQSS/dataverse-ansible which I mention at http://guides.dataverse.org/en/2884-install-guide-reorg/installation/prep.html#advanced-installation

Passing to QA.

**Comment by kcondon** [comment]
Phil has addressed a majority of the issues with these changes. This is likely to be an ongoing effort as we receive feedback from users. Subsequent changes will be addressed in separate tickets more targeted at specific issues.

Closing.
