### ISSUE TITLE
Stats: Create a way to voluntarily, automatically record when a new Dataverse goes online.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2284]
People have asked about keeping track of Dataverse installations. Why don't we automate this but on a voluntary basis? Perhaps a "join the network" feature or register for news or something like that?

**Comment by eaquigley** [comment]
This could tie in with a request I've received to be able to check off if an installation wants to be harvested or not. If they allow harvesting then we will know about them and be able to aggregate installations that way.

On Jun 18, 2015, at 5:26 PM, kcondon <notifications@github.com<mailto:notifications@github.com>> wrote:


People have asked about keeping track of Dataverse installations. Why don't we automate this but on a voluntary basis? Perhaps a "join the network" feature or register for news or something like that?

**Comment by mheppler** [comment]
Related to: Metrics page for Dataverses #1971; and: Metrics: Display visualizations on dataverse.org #3230

**Comment by pdurbin** [comment]
> This could tie in with a request I've received to be able to check off if an installation wants to be harvested or not. If they allow harvesting then we will know about them and be able to aggregate installations that way.

I like this idea. See also this related thread: https://groups.google.com/d/msg/dataverse-community/fqyVxWZSDRA/q5mf4PvZBQAJ

Also, we'd like a description of the new installations as they come online according to https://github.com/IQSS/miniverse/issues/52 .

**Comment by pdurbin** [comment]
> People have asked about keeping track of Dataverse installations.

Right now installations are tracked in two locations:

- The database behind the map on the https://dataverse.org . The code is in miniverse but I recently copied it over to https://github.com/IQSS/dataverse-installations and believe it should be maintained (hopefully with help from the community) as an independent project, especially since IQSS does not maintain miniverse anymore. The list of installations from this database is also reused for the list of installations at https://dataverse.org/metrics (so that the names match).
- A Google spreadsheet internal to IQSS. This spreadsheet contains not only installations on the map but also installations that are in the processes of going live.

Under the "going live" section of the installation guide, we encourage installations to tell us they'd like to be added to the map: http://guides.dataverse.org/en/4.15.1/installation/config.html#putting-your-dataverse-installation-on-the-map-at-dataverse-org

**Comment by pdurbin** [comment]
https://github.com/IQSS/dataverse-installations is definitely what we're using these days to track installations. In my last comment (from 2019!) I mentioned miniverse but dataverse-installations is completely independent of it and has been for years.

Also, as of 5.8 and e9ea9b4 we started advertising the map (that datavese-installations repo) in all of our release notes.
