### ISSUE TITLE
HTTPS Website Identity -- Murray Dataset Pg "This website does not supply ownership information"

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#2293]
When navigating from the Murray Dataverse page, to a dataset page (https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/01954), I noticed that the https "lock" icon changed to a "warning sign" icon, which when clicked, shows a message of "This website does not supply ownership information."

**Comment by pdurbin** [comment]
The problem is that the `distributorLogoURL` points at a plain HTTP URL rather than HTTPS: http://murray.harvard.edu/files/murray/banner146x48.png

![record_of_american_democracy _all_geographic_boundary_files_-_murray_research_archive_dataverse_-_2015-06-29_13 32 17](https://cloud.githubusercontent.com/assets/21006/8414078/78f83816-1e63-11e5-9441-1c060225c40e.png)

At the very least, in the guides we could encourage the use of HTTPS URLs for `distributorLogoURL`.

**Comment by mheppler** [comment]
This logo image is now showing up as a broken URL for [Murray Research Archive](https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/00235) datasets.

![screen shot 2016-10-12 at 3 07 08 pm](https://cloud.githubusercontent.com/assets/687227/19324037/a09500f0-908d-11e6-9728-7c56b62b8401.png)

**Comment by pdurbin** [comment]
Related: #4428

**Comment by mheppler** [comment]
Closing in favor of #4428.
