### ISSUE TITLE
Versioning: Make "minor" versions view available only to admins and not end users

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2299]
IFPRI would like end users not to see all the "minor" versions that show up under the versions tab; users should only see major version changes. Admins should see all minor version information

**Comment by sbarbosadataverse** [comment]
@scolapasta 
any idea when this will be added to a release milestone? User from harvard inquiring
Thanks

**Comment by pdurbin** [comment]
@sbarbosadataverse are you still interested in this feature?

**Comment by mankoff** [comment]
I feel strongly that this should be an option, not the default. I hope ideas of what is shared have changed since 2017. If something changes about the data, it should be available to end-users, not hidden from them. See also #7202. 

I vote to close this issue - Minor numbers should be in the reference and in the table of versions.

**Comment by poikilotherm** [comment]
This might be addressed someday when the versioning system gets adapted to support custom version as it would be needed for software publications. See also    #7077

**Comment by scolapasta** [comment]
I agree with @mankoff that all versions / changes should be available to end users. That said, I have elsewhere suggested that by default maybe only major version should be shown (where major version is the last with that number, so if v2.0, 2.1, and 2.2 exist, v2 would be represented by 2.2). The user could then click to see the minor versions that got to that major version.

In this way, we focus on the major versions (which should be of more interest since they involve file addiitions / removals, major metadata change, etc), but still leave the ability to see all changes.

**Comment by sbarbosadataverse** [comment]
closing based on feedback
