### ISSUE TITLE
add "is_restricted" to solr cards

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2325]
part of #2302 

---

Logic available in search-include-fragment.xhtml. e.g. ```{result.entity.restricted and !permissionsWrapper.hasDownloadFilePermission(result.entity)}```

**Comment by pdurbin** [comment]
I think being able to facet on if a file is restricted or not would be very interesting! From the home page I mean. /cc @eaquigley @mheppler @scolapasta @mcrosas

**Comment by mcrosas** [comment]
Also, it would be good to carry these facets to File Tabs in a dataset, as discussed with @eaquigley

**Comment by scolapasta** [comment]
This is not realtedto MyData, since in MyData if you see a file card it is because you have the download file permission (i.e isn't restricted).

Whether we want an is restricted facet on the home page is a separate discussion.

**Comment by pdurbin** [comment]
I just discussed this issue with @landreev in the context of perhaps adding a facet for "Access" as "Public" or "Restricted" per [mockups](https://iqssharvard.mybalsamiq.com/projects/filesprovenancefacetsfilter-dataverse40/grid) related to file-level facets as part of #2466:

![dataset_-_files_mybalsamiq_-_2015-08-18_13 59 12](https://cloud.githubusercontent.com/assets/21006/9338152/34521f7c-45b1-11e5-978d-47fdd10c2528.png)

Its turns out this is potentially a complicated check. The permission system may need to be interrogated. I was hoping I could just check the boolean at either the DataFile or FileMetadata object (it's currently unknown why boolean exist on both objects/tables).

**Comment by pdurbin** [comment]
I'm moving this to QA because I did add a new facet called "Access" that shows either "Public" or "Restricted" on the homepage cards in #2466 which is closely related to this issue. @eaquigley and @kcondon perhaps you can summarize what else needs to be done for a future release.

**Comment by kcondon** [comment]
OK, restricted facet works, closing.
