### ISSUE TITLE
Notifications: Add/ remove dataset roles notifications appear as blanks, dates only

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2344]
When I assign a user a contributor role in a dataset, then later remove that role, these 3 entries appear in the notification tab:

July 10, 2015 5:01 PM EDT	
July 10, 2015 5:01 PM EDT	
July 10, 2015 5:01 PM EDT

**Comment by sekmiller** [comment]
@eaquigley - we don't have any text for the notifications tab for gaining/losing a role on a dataverse or dataset.  What should it say?

**Comment by eaquigley** [comment]
Granted: You have been granted the [insert role name] role for [insert dataverse or dataset name as a link].

Revoked: You no longer have [insert role name] role for [insert dataverse or dataset name as a link].

**Comment by sekmiller** [comment]
This has been added and checked in....

**Comment by kcondon** [comment]
OK, the notification messages are working now but seeing multiple notifications for one event and deleting notifications when there are many does not refresh page. Also, when revoke the role, the role name disappears from all notifications.

I can open separate tickets for these issues if needed. Passing back for now.

**Comment by sekmiller** [comment]
When a role is removed from a user we lose the ability to display the name of the role.  I have updated the bundle so that [Unknown] is displayed for the add role notification and the reference to the type of role has been removed from the revoked role notification.  

A remaining issue exists if a user is granted multiple roles on a single object.  This seems to be an outlying case because the assign roles interface uses option buttons not select many check boxes. In other words, the admin would have to visit the add role page multiple times to add multiple roles.  Regardless, there is one notification for each granting of a role and that notification lists all of the roles for a given user on a given object.

**Comment by sekmiller** [comment]
Assigning to @kcondon to verify the completed fixes and to assess the need for the additional "multiple assignment" issue.

**Comment by kcondon** [comment]
This works except I'm getting two online notifications for assigning a single role to a dv.

**Comment by sekmiller** [comment]
It looks like two notifications records are being added; one with emailed=true and the other with emailed=false. @michaelsuo can you take a look at this?

**Comment by sekmiller** [comment]
@michaelsuo - Never mind. I figured it out.

**Comment by sekmiller** [comment]
When Email is enabled, two notifications were being saved to the DB.  Fix has been checked in - new build needed.

**Comment by kcondon** [comment]
Fixed, closing.
