### ISSUE TITLE
Both "Draft" and "Published" dataset cards display on dataverse pg

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2347]
@sbarbosadataverse has been receiving feedback that it is confusing and not necessary to see two different cards for a dataset, the published and the draft. Users want to be able to see only one card per dataset so if there is a published version and a draft version, they would prefer to see the draft version as that is the one they are working on.

**Comment by kcondon** [comment]
Also, a user has requested a report listing the datasets in his collection of dataverses. This was not possible from the UI since the numbers do not add up to the number of datasets, instead they are the number of cards displayed, which includes published and draft versions. Even using the published and unpublished facets do not add up since a dataset can have both a published version and an unpublished draft version.
See RT 229288

**Comment by pdurbin** [comment]
@sbarbosadataverse are you still getting this feedback. It's a bummer because it's all by design. :(

**Comment by djbrooke** [comment]
To get this to happen, generally we'd:

- Create a Dataset
- Publish a Dataset
- Create a Draft Version of the Dataset

Example:

<img width="1237" alt="Screen Shot 2021-08-11 at 5 05 14 PM" src="https://user-images.githubusercontent.com/7773392/129103279-e17920ba-f592-4efa-938a-278444edf624.png">

(it's easier to see if you do it in your own Dataverse collection instead of the root)

**Comment by pdurbin** [comment]
Again, this is all by design. If we don't like the choices we made for 4.0 we can revisit them.

This issue needs a champion or it should be closed. (GitHub offers a "Close as not planned" option these days. 😄 )
