### ISSUE TITLE
dvn-build bug: "draft" link is displaying "published" data page instead of draft page

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2384]
here is the dataset example in build: 

https://dvn-build.hmdc.harvard.edu/dataset.xhtml?persistentId=doi:10.5072/FK2/RLTTIK

If you go into versions and click "draft"-that's what I should be seeing.

**Comment by kcondon** [comment]
Spoke with Sonia, here are the steps to reproduce:
Create a dataset and publish it. Then go in and edit it by adding files--since this is what I did.
When it saved your edit, you should see the url say "draft" but the version will be the published one.

I have not been able to reproduce this with the above steps.

**Comment by kcondon** [comment]
@sbarbosadataverse Can you try this again? I did not see the issue you mentioned.

**Comment by sbarbosadataverse** [comment]
@scolapasta 

yes you can close! haven't seen the related issues in a while, as well.
