### ISSUE TITLE
Index: Index using the mod/ continue command does not continue on repeated runs, possibly due to indextime not being set.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2421]
The mod version of indexing is intended to continue where it leaves off in case it needs to be restarted. That currently does not work, possibly because the index command does not update indextime as it goes along so does not have a reference to begin again from.

**Comment by pdurbin** [comment]
In fdfd818 I wrote to a test that confirms that indextime is not being updated when you reindex an individual dataset manually. updateContentIndexTime gets called though. I'm not sure what's going on.

**Comment by pdurbin** [comment]
@scolapasta I ran my SearchIT tests again and when they work (they still fail maybe half the time due to the database deadlocks I reported in #2460) they indicate that the indextime is now being updated.

This is still quite mysterious to me but I suspect (as I just indicated in 1862654 where I changed the boolean my test expects) that this may have been what happened:

- In 4.1 we merged 75e8dba after discussing it at https://github.com/IQSS/dataverse/issues/2036#issuecomment-122086115 . We thought it was safe, but my guess is that it caused this regression as well as the "index all doesn't just work anymore" regression at #2453
- While I worked on the index all bug in #2453 for 4.2 I merged a4a37b5 yesterday. Did it also fix this issue? I think so. Maybe not but it's a theory!

Passing to QA. The "indextime" column in the dvobject table should be operating as normal again, being updated after indexing is being performed. This should mean that the mod/continue feature @scolapasta added a while back should be working again.

**Comment by kcondon** [comment]
@pburbin, is there a continue argument for index all or do I just run index all and it continues automatically?

**Comment by pdurbin** [comment]
@kcondon no. For "index all" the "skipIndexed" boolean is [hard coded to false](https://github.com/IQSS/dataverse/blob/1f929ba25f0ba7c4da627e8d8bdd323911280145/src/main/java/edu/harvard/iq/dataverse/api/Index.java#L101) which is the opposite of the "continue" method where "skipIndexed" is [hard coded to true](https://github.com/IQSS/dataverse/blob/1f929ba25f0ba7c4da627e8d8bdd323911280145/src/main/java/edu/harvard/iq/dataverse/api/Index.java#L107). So "index all" doesn't continue. It marches through all DvObjects like it always has.

**Comment by kcondon** [comment]
So how do I test continue? using the mod command Gustavo wrote?

**Comment by kcondon** [comment]
Works, continue continues based on indextime. Closing.
