### ISSUE TITLE
Distinguish between "read" and "write" permissions, make the "write" ones apply only to AuthenticatedUsers

### ISSUE THREAD

**Issue by michbarsinai** [IQSS/dataverse#2454]
This would prevent, e.g., creation of DvObjects by the GuestUser when coming from a whitelisted IP address.

This required adding a new type of CommandException, along the lines of "GuestUserNotAllowed".

**Comment by michbarsinai** [comment]
caption on the permissions in Edit Role dialog
dataverse.permissions.roles.roleList.authorizedUserOnly=Will be granted to authenticated users only

**Comment by michbarsinai** [comment]
Implemented. Over to @mheppler for review of the (minor?) UI changes made to the edit role dialog - adding a label for the permissions a guest user cannot be granted.

@kcondon - I've added a script to test this, at `scripts/issues/2454`. We should probably convert that to an automated test at some point.

**Comment by mheppler** [comment]
I've attached a screenshot of what the new labels look like, and will review with @eaquigley for how to improve them. Some initial changes that I'd make, include:

- Instead of a label, just used text, since the Bootstrap label component is already used in this form to display the permission name.
- Use Bootstrap's orange "text-warning" style class, rather than the label's blue "info" style.
- Add period at end of sentence.

I've added a second screenshot of what these changes will look like in the edit role dialog.

![screen shot 2015-09-08 at 9 32 40 am](https://cloud.githubusercontent.com/assets/687227/9735983/9539d86e-560c-11e5-9900-17f4f3dfda03.png)
![screen shot 2015-09-08 at 9 43 37 am](https://cloud.githubusercontent.com/assets/687227/9736255/1566a7b4-560e-11e5-82f4-532ef490f3d1.png)

**Comment by mheppler** [comment]
Changed info text and icon for permissions in the Edit Role popup from the Permissions page.

@michbarsinai -- I am passing back to you, because with the new message (see attached screenshot), that is opposite of the labels you previously had, we need the render logic to be changed.

![screen shot 2015-09-09 at 12 28 05 pm](https://cloud.githubusercontent.com/assets/687227/9767928/b617b01e-56ee-11e5-8c0c-140baecf6c60.png)

**Comment by kcondon** [comment]
UI part verified. Need to verify actual constraint.

**Comment by kcondon** [comment]
Waiting for #1380 to be fixed before we can test.

**Comment by pdurbin** [comment]
Closing per https://github.com/IQSS/dataverse/issues/2454#issuecomment-215573854
