### ISSUE TITLE
Use Solr for file listing on dataset page

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2455]
In the FRD about [improving the organization and display of files](https://docs.google.com/document/d/1v-6WuFyClnAAHqyMf1VsWtCdXDTTR-ikuG6Ou8RtDMM/edit?usp=sharing) as [mentioned on the Google Group](https://groups.google.com/forum/#!topic/dataverse-community/gtz2npccWjU) we've been talking about the possibility of **building the list of files on the dataset page using Solr rather than the database**. Solr provides a better search experience than the database and we could make use of facets at the file level. I'll include a **preliminary** mockup below of how facets might look.

The primary challenge is how to handle files from old published versions of datasets because they are currently not indexed. A switch from the database to Solr should be carefully considered for a few reasons. We have already identified performance problems with indexing production data (#50) and indexing permissions (#2036). In addition, managing the lifecycle of Solr documents and their discoverability rules (#57) is already complex. We don't want to change the rules of when cards are shown on the homepage/dataverse page or in MyData.

![mockup](https://cloud.githubusercontent.com/assets/21006/9255273/2ea0537c-41b6-11e5-9142-38bde6d0ce07.jpg)

**Comment by landreev** [comment]
These are my summarized thoughts on the issue (reposted from the dataverse list): 

After talking offline to some developers about this, I figured I would bring this up one more time.

Namely, I'm talking about switching to using solr for viewing files. (Please read the whole thing before deciding that you hate my idea!)

So far, we have the following good reasons to proceed with this:

1. Duplication of code in the current setup. Search cards on the dataverse page do essentially the same as the file cells on the dataset page. With 2 very different processes of retrieving the data.

Counter arguments:
- it appears that we'll still have to maintain some code that renders file information retrieved from the database: the mydata page. maybe the code could be unified and shared between mydata and dataset pages instead?
- current setup has one big advantage - it's something that's working already more or less.

2. Pagination - something we would get "for free" with solr.

Counter argument:
According to Raman, pagination was fairly straightforward to implement on his mydata page.
In fact, it should be even simpler on the dataset page. Mydata may contain objects combined from different sources. The files on the dataset are just the filemetadatas from a single version, obtainable with a single query. You know right away how many you got. It really is easy to split these into several page chunks.

3. Searching for files/jumping between pages to specific files - straightforward with solr.

Counter argument:
This will be an issue, if and once we extend our metadata blocks to cover files.
As of now, the file metadata come from 2 db tables. Searching these directly in the db would be both straightforward and, likely, faster.

4. Facets. (pro and con same as above)

There is of course also 5., or 0. argument - the current dataset page is a big unmanageable mess that we've been meaning to reorganize and split.
But that is an argument in favor of splitting/reorganizing the page, not going to solr necessarily. We've been meaning to address this anyway, regardless of solr.

So, I'm not arguing for not going to solr. I am proposing to seriously consider not going to solr in 4.2. And, instead, to address that once we have extra metadata on the files level to deal with. Instead, let's set a more manageable, incremental 4.2 goal - separate the current page into view and edit (and upload) components; implement the new edit-on-demand scheme, instead of the current edit-all-files-at once; and add pagination (and, maybe, search) to the view page, while leaving the metadata retrieval as is.

Otherwise, I'm worried that fully reorganizing the page AND switching to solr is too ambitious a goal. That will turn 4.2 into another endless release. With, at best, even if we don't break anything in the process, nothing extra to show to the users for that extra effort.

**Comment by landreev** [comment]
(github messed up the formatting, but should still be readable)

**Comment by pdurbin** [comment]
I agree with everything @landreev has to say. (Oh, I fixed the formatting a bit, by the way.)

No matter what milestone this feature ends up in I think a **user story for using Solr for file listing on dataset page** will help us write an automated test to validate that the feature is working as desired. I just started a [Google doc](https://docs.google.com/document/d/1FzgFkjyZH4NL8Q-6Ytl3l3xWib5qSwH2jhud4H6yM94/edit?usp=sharing) for this and would love feedback (public comments are enabled).

**Comment by pdurbin** [comment]
On Monday afternoon we met and decided that while we are all enthusiastic about the features of Solr we could make use of (especially faceting and nice search) we can't use Solr for files in the 4.2 timeframe because all the data necessary (past versions of published datasets) is not in Solr.

I started writing some tests to illustrate the problem of the data simply not being in Solr there based on scenarios in [a Google Doc](https://docs.google.com/document/d/1FzgFkjyZH4NL8Q-6Ytl3l3xWib5qSwH2jhud4H6yM94/edit?usp=sharing) (more scenarios would be appreciated). My approach would be to keep adding to our test suite before making any changing to indexing. Then start changing the indexing rules (#528 in particular might change) to support this feature.

This is all to say that I'm moving this suggestion out of 4.2 milestone.

**Comment by pdurbin** [comment]
@raprasad said to give this issue to him since he's interested in exploring the idea of using Solr to power the file listing on the dataset page. Below is some whiteboarding we just did:

![img_20150909_122842](https://cloud.githubusercontent.com/assets/21006/9767991/08d23c84-56ef-11e5-8bbd-786ac0d50ecf.jpg)

**Comment by raprasad** [comment]
The attached PDF shows some of the complications of basic filtering without Solr--using SQL queries for facets.   Keep in mind that more facets will likely be added later.   (doc is from 9/3)
[file-filter-notes-db.pdf](https://github.com/IQSS/dataverse/files/108950/file-filter-notes-db.pdf)

**Comment by mheppler** [comment]
A new issue, **Dataset - File UI Improvements #3404**, was created to track the UI improvements related to the files view on the dataset pg. Older feature requests and bug reports like this one will be closed in favor of that new issue.
