### ISSUE TITLE
Add createtime to authenticated user table 

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2470]
(for metrics)

**Comment by raprasad** [comment]
It's not obvious how to get user metrics--e.g. 'date_joined'

@scolapasta

**Comment by bencomp** [comment]
It's in the `ActionLog`, isn't it?

**Comment by pdurbin** [comment]
@raprasad do you remember why you flagged this issue as both High and Critical? I'm tempted to remove both labels. I'm also not sure why you gave it to @eaquigley but maybe there's a project for this on the new spreadsheet? If so I can't find it.

@scolapasta you asked me to look at this issue but I'm not sure if you want to treat this as a bug fix ("just add the missing column to the table") or if you'd like it to be rolled into a larger Shibboleth-related project since it has to do with user accounts. Please advise. For now, I'm adding it to my list of Shibboleth-related issues at https://trello.com/c/uYoH4IOu/117-shibboleth-restore-institution-log-in-to-dataverse-harvard-edu (even though it's not strongly Shibboleth related) so I can find it again. I'll give this issue to you for now for more advice on how to proceed.

**Comment by pdurbin** [comment]
Related: #3246

**Comment by raprasad** [comment]
covered by #3246
