### ISSUE TITLE
Destroy command should unregister dataset from DOI / persistent ID provider

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#2471]

**Comment by bencomp** [comment]
Could you please explain the term "unregister"? The PID provider usually has rules for this and may not even support taking a PID out of the registry.
To my knowledge the best way to take a PID out of the universe is to update it to redirect to a page (perhaps a generic one) explaining what happened to the dataset. This is similar to what happens when you deaccession a dataset.

**Comment by pdurbin** [comment]
@scolapasta @sekmiller @kcondon do you know if this was fixed as part of pull request #3826?

**Comment by djbrooke** [comment]
- we believe we have this in place, but the Datacite API may have not existed at the time. 
- we would want this to work for handles, and EZID-generated DOIs as well 
- we'd want this to work for files as well (this is implemented in the code as a try-catch already and we may want to refactor)

**Comment by sekmiller** [comment]
Neither EZID nor DataCite allow for the deletion of PIDs once they have been made public. EZID allows reserved (non-published) PIDs to be deleted. The current implementation of DataCite does not register PIDs until publication.

So for EZID PIDs, when a dataset is destroyed its PID's status is set of "unavailable, withdrawn by author" and its target url is changed from the Dataverse dataset page to an EZID PID page where the "unavailable" status is displayed. 

For DataCite PIDs, on dataset destroy the status (and for any published files is set to "registered". A "registered" status removes the PID from any DataCite searches.  Also, the target url remains pointing at Dataverse so that anyone with the url will get a 404 - not found error.  (This was deemed appropriate as the dataset is truly gone and not just deaccessioned.)

Handles for destroyed datasets are fully deleted.

**Comment by poikilotherm** [comment]
A quick note from our onboarding session with Datacite: they provide a tombstone mechanism, which should be preferred over a 404.

**Comment by sekmiller** [comment]
Is there documentation of DataCite's tombstone mechanism?

**Comment by landreev** [comment]
If the documentation for this is not readily google-able, we can always ask them. Martin Fenner has been very willing to answer any technical questions (he reads support@datacite.org). 

I don't have a strong opinion though on whether this is something we need - specifically, in the context of this issue, as part of the "Destroy dataset" command. This is kind of a nuclear option, reserved for special situations. And I know in the past some of the people who wanted the functionality were actually interested in erasing all traces of the dataset.

**Comment by sekmiller** [comment]
@landreev the DeleteIdentifier method was already implemented in the HandlenetServiceBean.
