### ISSUE TITLE
Migration: Document and clean up script to update persistent id record target url.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2477]
One post migration step is to update the target url in the persistent id records, both hdl and doi. This was done using a script that drives a purpose built servlet.

This should be documented and the script reviewed for clean up.

**Comment by raprasad** [comment]
@landreev captured the updated needed in a simple curl loop

e.g.
```
cat list_of_db_ids.txt | while read dbid
do
   curl 'http://localhost:8080/api/datasets/'$dbid'/modifyRegistration?key=<ADMIN_API_KEY>'
   echo
done
```

**Comment by pdurbin** [comment]
This falls within Installation Guide territory, I suppose, but I didn't not attempt to document this (I didn't work on it) in my pull request at #2895. Since it's a migration thing I guess it could be documented on the Upgrading page I added. It can be previewed here right now: http://guides.dataverse.org/en/2884-install-guide-reorg/installation/upgrading.html

**Comment by pdurbin** [comment]
Related: #3318.
