### ISSUE TITLE
documentation: geoconnect keeps a list of 'registered dataverses

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2492]
e.g. Geoconnect accepts incoming connections from a list of dataverses

Screenshots are from the geoconnect administrative interface (e.g. basic django):

![select_registered_dataverse_to_change___dataverse_db_site_admin](https://cloud.githubusercontent.com/assets/1036060/9639088/323dc862-5178-11e5-9a8b-6a2d2cae1bef.png)
![add_registered_dataverse___dataverse_db_site_admin](https://cloud.githubusercontent.com/assets/1036060/9639061/1097c730-5178-11e5-9573-bcb225faa682.png)

cc @kcondon

**Comment by kcondon** [comment]
See RT 226605

**Comment by sbarbosadataverse** [comment]
Elizabeth is this info in the guide?

**Comment by eaquigley** [comment]
@sbarbosadataverse what info? what @raprasad has above about the django admin interface?

**Comment by kcondon** [comment]
@eaquigley @sbarbosadataverse @raprasad 
I think she means this explanation from the RT ticket:
The intended model for using GeoConnect is the following:
All instances of Dataverse will connect to a single GeoConnect server, which will in turn connect to a single WorldMap service. The GeoConnect server will be hosted by us and in order for remote Dataverses to use the server, they must be added to a white list of accepted servers. This would be done manually by us upon request.

**Comment by pdurbin** [comment]
I mentioned to @raprasad that in my pull request at #2895 that I direct people to https://github.com/IQSS/geoconnect for more information on Geoconnect. So if it's easier or better, it could be documented there instead.

Here's where you can preview where I mention Geoconnect: http://guides.dataverse.org/en/2884-install-guide-reorg/installation/prep.html#architecture-and-components

**Comment by pdurbin** [comment]
https://github.com/IQSS/geoconnect is now very clear about how Geoconnect is intended to be used for now, saying:

## To use Geoconnect, please email support@dataverse.org with the URL to your Dataverse installation.

### Note: These instructions need to be updated and should not be used if setting up a Dataverse installation because you would also need to install WorldMap, which is being rewritten. You should wait until the WorldMap rewrite is complete before considering installing Geoconnect.

(The rewrite of WorldMap is happening here: https://github.com/cga-harvard/worldmap )

Also, here's a recent thread where someone went through this process of adding their Dataverse to the instance of Geoconnect that Harvard hosts: https://groups.google.com/d/msg/dataverse-community/KgiMIHhuH18/hml1kluXAAAJ

@raprasad is there more you had in mind for this issue? What is the definition of done?

**Comment by pdurbin** [comment]
@raprasad can we close this?

**Comment by pdurbin** [comment]
A while back additional edits were made to the readme at https://github.com/IQSS/geoconnect and I think they're sufficient. Closing.

**Comment by kcondon** [comment]
@pdurbin While the Geoconnect readme does clearly start how to connect a dataverse installation to geoconnect, essentially by contacting support, I think the Dataverse documentation on Geoconnect is a little vague on the subject: http://guides.dataverse.org/en/4.9.1/installation/geoconnect.html 

As of this writing, the README at https://github.com/IQSS/geoconnect recommends not installing Geoconnect at this time due to an ongoing rewrite of the WorldMap code. If you are not deterred by this, read on!

I think both docs kind of obscure somewhat who is responsible for support (geoconnect says dataverse team, dataverse doc pushes to geoconnect project, what the actual supported model is (we   support connecting to our geoconnect instance. not sure who supports setting up geoconnect, maintains code).

I make these points because we get more contacts about setting up geoconnect rather than connecting to our geoconnect, as if the message is not clear.

**Comment by djbrooke** [comment]
Closing some old Worldmap/Geoconnect issues. Will re-evaluate when/if additional Worldmap work gets added to the roadmap. FWIW, I agree it's a little ambiguous. I think there we grander plans for this integration that never came to fruition.
