### ISSUE TITLE
Dataset Page: File Tab Sort Button

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2506]
Sort button based off of this mock up: https://iqssharvard.mybalsamiq.com/projects/filesprovenancefacetsfilter-dataverse40/Dataset%20-%20Files%20-%20Sort

**Comment by pdurbin** [comment]
The Sort button has been available at https://beta.dataverse.org for a while (example dataset at https://beta.dataverse.org/dataset.xhtml?persistentId=doi:10.5072/FK2/KJQUMO ) but hidden behind a feature flag. @eaquigley and I decided to enable the feature (which I'll do in my next commit) so it can go through QA.

Questions I have:

- The mockups do not specify whether "Size" should sort biggest to smallest or smallest to biggest. Should we have both?
- The same is true of "Type" in the mockups. Should we have "Type (A-Z)" and "Type (Z-A)"?

I'm happy to get feedback on the Sort button.

**Comment by pdurbin** [comment]
In d816183 I refactored the code and enabled the Sort button. Please note that I did not get around to making the selected field to be sorted by bold like in the mockups:

![dataset_-_files_-_sort_mybalsamiq_-_2015-09-11_11 38 52](https://cloud.githubusercontent.com/assets/21006/9819050/b54dd910-5879-11e5-97d5-39c2e243d645.png)

I'm a bit concerned with how the Sort button will interact with editing files but since editing is happening in new pages (that I haven't even looked at) maybe this concern is unfounded.

I made it so the Sort button can be easily disabled. On the xhtml side this is `#{DatasetPage.sortButtonEnabled}` and of course there is an equivalent boolean on the Java side.

There's a bit more cleanup I want to do in filesFragment.xhtml before I had this ticket over to @mheppler for proper positioning of the Sort button.

**Comment by pdurbin** [comment]
@mheppler in 35c471f I believe I removed the last of the references to weird rendering booleans. You'll still see one for "sortButtonEnabled" but that's expected, per my last comment. Over to you. Thanks!

**Comment by pdurbin** [comment]
@kcondon noticed a bug with the Sort button that the list was not being updated, especially when he was switching from Newest to Oldest but locally, I found that if a do a lot of sorting (at least five sorts) eventually the Sort button doesn't respond to my mouse clicks.

I don't have time to fix this for 4.2 unfortunately and @eaquigley said she's fine with deferring this feature (so I disabled the Sort button in 5367b8c) and giving this to @sekmiller for 4.3 as part of the "finishing up file features" project.

**Comment by mheppler** [comment]
A new issue, **Dataset - File UI Improvements #3404**, was created to track the UI improvements related to the files view on the dataset pg. Older feature requests and bug reports like this one will be closed in favor of that new issue.
