### ISSUE TITLE
Shibboleth/UI/config: one-click IdP-selection, DiscoFeed-bypass

### ISSUE THREAD

**Issue by bencomp** [IQSS/dataverse#2548]
This is a proposal for changes to the login page and system settings that would fit DataverseNL needs. A functional requirements document can be found here: [FRD Shibboleth federation login](https://docs.google.com/document/d/1RwdGJPQiziMlBLZp8q0Xti190mvM_k0Y3_o4w-MoprI/edit?usp=sharing)

Scenario: DataverseNL has a Dataverse 4 installation with `:ShibEnabled = true` and one IdP, which is a federation. That means that the login page will always show a single "institution" (that is not in fact an institution) whose name may not speak to the end user who wants to log in.

Proposal in short:
- when there is only one IdP, don't show a choice UI
- be aware that the IdP may be a federation (allow different wording of "select your institution")
- add configuration settings:
  - choice of list of IdPs (DiscoFeed) or direct entry of single IdP
  - institute "code" to institute "friendly name" dictionary (because DiscoFeed may not be usable for looking up friendly names)

**Comment by pdurbin** [comment]
@eaquigley you and I discussed this issue a couple weeks ago and you had some ideas. Can you please leave a comment here or on [the FRD](https://docs.google.com/document/d/1RwdGJPQiziMlBLZp8q0Xti190mvM_k0Y3_o4w-MoprI/edit?usp=sharing)?

**Comment by bencomp** [comment]
Curious to hear about your ideas :)

**Comment by djbrooke** [comment]
Closing this in favor of #2974.

**Comment by pdurbin** [comment]
@djbrooke #2974 is quite different than this issue. #2974 is about completely disabling login by local users, something we don't support as of this writing. This issue is about an edge case we didn't anticipate in how DANS uses Shibboleth. They support login from ~18 institutions but from the Dataverse perspective they are hidden behind a single Identity Provider (at https://dataverse.nl you can see this in action). In short the GUI we've created for Shibboleth with the drop down doesn't work for them. These days @jo-pol and @4tikhonov from DANS are actively working on pull requests so perhaps they can make a pull request for this issue some day. I'm not even sure how we'd test it, though. It's a setup that's unique to DANS as far as I know.

**Comment by xibriz** [comment]
Just putting it in here for feature Googler's: The same apply in Norway with FEIDE as Identity Provider.

**Comment by pdurbin** [comment]
@xibriz yep, thanks for leaving a note here after we discussed it at http://irclog.iq.harvard.edu/dataverse/2018-01-10 . Here are screenshots of the user experience at https://dataverse.no where the user always has a single "Your Institution" to choose from and then selects from the real list of institutions afterward:

![screen shot 2018-01-10 at 9 32 43 am](https://user-images.githubusercontent.com/21006/34777795-6e7b0886-f5e9-11e7-86cd-b10ce7140e22.png)

![screen shot 2018-01-10 at 9 33 57 am](https://user-images.githubusercontent.com/21006/34777794-6e718c70-f5e9-11e7-8612-d19e6622f584.png)

**Comment by xibriz** [comment]
I have a support case with FEIDE. There may be a workaround method that I'm going to explore tomorrow.

**Comment by pdurbin** [comment]
@xibriz ok, please note that this issue has been closed. Please open a new issue if you need anything. Thanks!

**Comment by pdurbin** [comment]
Related: #4776

And nice meeting you last week @xibriz ! 😄
