### ISSUE TITLE
Request Access: The Batch request access button does nothing.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2549]
On the Dataset page, the batch request access button does nothing: 
0. It does not pop up terms of access.
1. It does not gray out individual request access buttons for each file checked.
2. It does not actually request access to files on the files permissions page
3. It does not send a notification that access was requested.

**Comment by sekmiller** [comment]
As discussed, the underlying issue was that multiple requests by the same user for the same file where causing a failure. The fix prevents these multiple requests from being sent.  You can still select a file and press "Request Access" in the bulk update button, but nothing will be sent.  Also the page will be refreshed to give the user an indication in the files table that the request has been made - the single file request access button will be disabled.

**Comment by sekmiller** [comment]
New build required for testing

**Comment by kcondon** [comment]
Batch request access is working. Does not have request access popup but will treat as a separate issue. Closing.
