### ISSUE TITLE
Notifications: Publish notification is not sent to a contributor who submitted dataset for review.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2568]
Publish notification is not sent to a contributor who submitted dataset for review.
Tested 4 scenarios:
1. User was dataset creator with contributor role granted on dataset upon create.
2. User had both dataset creator and contributor at dv level
3. User had only contributor at dv level and dataset was created by admin but submitted by contributor.
4. User had contributor role at the dataset level.

**Comment by sekmiller** [comment]
This was caused by the recent change to the publish dataset command.  the command was resetting the in review flag so no notifications were being sent. fix has been checked in.  

Gustavo wants to revisit the issue of publish notifications in general. That should be a separate ticket.

Fix for this one has been checked in.  new build needed for testing.

**Comment by kcondon** [comment]
OK, works now, closing.
