### ISSUE TITLE
Subset: Downloading subset from Dataverse results in error.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2586]
When I choose subset from Dataverse, select variables and download, it results in an error:
/Users/kevincondon/Downloads/x_n71+fm.part could not be saved, because the source file could not be read.

This does seem to work in some cases:
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/26212
    PotalaPalace_obs_replicate.tab
fails:
    results_all_replication.tab

**Comment by pdurbin** [comment]
At https://dataverse.lib.virginia.edu/dataset.xhtml?persistentId=doi:10.18130/V3/HOOJSE if I click "Data Subset" on EmployerData_SCI.tab I see the TwoRavens branding but apparently no data:

![survey_on_humanities_graduate_education_and_alternative_academic_careers_ employer_survey _-_university_of_virginia_dataverse_-_2016-03-27_17 48 22](https://cloud.githubusercontent.com/assets/21006/14068016/2552bb3e-f444-11e5-8444-cb30a743674e.png)
![survey_on_humanities_graduate_education_and_alternative_academic_careers_ employer_survey _-_university_of_virginia_dataverse_-_2016-03-27_17 45 04](https://cloud.githubusercontent.com/assets/21006/14068017/25537632-f444-11e5-82a5-967de86d5244.png)

This was reported by @shlake at on the mailing list at https://groups.google.com/d/msg/dataverse-community/qeM7VxX8e9w/B52iZhwiCgAJ

**Comment by djbrooke** [comment]
Removing from 4.5. This will be re-prioritized for a future release.

**Comment by mheppler** [comment]
To pile on, when it apparently does work for a file, I am seeing variables displayed, but the Summary Stats popover is displayed behind the popup, and when I click over to Plots, there is nothing displayed below the help text.

Going to investigate and hopefully fix the popover display issue as part of the tooltip/popover revisions in #3925.

![screen shot 2019-02-25 at 3 25 45 pm](https://user-images.githubusercontent.com/687227/53367626-b167a680-3914-11e9-99bc-ef554362ea88.png)

**Comment by mheppler** [comment]
Fixed popover + dialog popup layering issue with simple `z-index` CSS fix as part of #3925 efforts.

**Comment by djbrooke** [comment]
Closing this since we removed subsetting in #4933.

**Comment by pdurbin** [comment]
@djbrooke I guess it makes sense to close this but I just looked again at pull request #6098 and I don't believe we ever documented the fact that there *is* still a GUI for subsetting but that now it's in Data Explorer instead of Dataverse. This seems like a pretty easy thing to fix to me. Just a doc change.

**Comment by djbrooke** [comment]
@pdurbin I'm OK not mentioning it because I don't want to set the expectation that we'll mention download formats and other ways of accessing data that are provided by external tools. The argument could be made that since this was a feature provided in the core that we should mention that it's still available in an external tool, but since it didn't work for quite awhile and we didn't hear anything I was OK leaving it be.

**Comment by pdurbin** [comment]
Mostly I'm wondering, "How does the world learn what features Dataverse has?"

I recently breathed new life into https://dataverse.org/software-features which hadn't been updated since 2015.

Maybe the external tool descriptions need to be longer? Some of them are already pretty long. Should we have a "features" page in the guides? I feel like we need something. I keep thinking I should give a talk about the hidden features of Dataverse. I don't want them to be hidden. I want them to be documented.
