### ISSUE TITLE
Deployment: Create static maintenance page served by Apache until we have read only mode.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2588]
Needed to help with deployment friendliness. Issue to track read only mode feature: #2587.

**Comment by mheppler** [comment]
A static maintenance pg has been created, based on input from a quick [FRD](https://docs.google.com/document/d/1lyEnvFzOPfm-GSwzokM9k6rgSJ-cuvV0Sk8iX4oRl60/edit) that outlines the requirements.

Whether anything else is needed for this is up for discussion still. This pg could be stripped to be a more generic template, which we could include in the code source, along with instructions for customizing in the Installation Guide.

![screen shot 2016-05-25 at 4 56 33 pm](https://cloud.githubusercontent.com/assets/687227/15577215/88141d3a-2329-11e6-880b-01cb5349fd20.png)

**Comment by kcondon** [comment]
Maybe change "going through unexpected maintenance" to "undergoing maintenance" so it sounds less like we're out of control.

________________________________

**Comment by pdurbin** [comment]
@kcondon mentioned that we're looking for a place in the git repo to put the maintenance page.

I'd suggest putting it at `doc/sphinx-guides/source/_static/installation/files/var/www/html/maintenance/index.html`

I say this because if you look at https://github.com/IQSS/dataverse/tree/v4.3.1/doc/sphinx-guides/source/_static/installation/files/etc/init.d for example, that's where we put files that we want sysadmins to be able to easily download from the Installation Guide. http://guides.dataverse.org/en/4.3.1/installation/prerequisites.html#solr-init-script says, "You can attempt to adjust [this Solr init script](http://guides.dataverse.org/en/4.3.1/_static/installation/files/etc/init.d/solr) for your needs or write your own." I can imagine similar text (also with a link to a file) for downloading a sample maintenance page.

**Comment by mheppler** [comment]
The [Administration pg](http://guides.dataverse.org/en/4.3.1/installation/administration.html) of the Installation Guide has been suggested as where to link to this file.

**Comment by mheppler** [comment]
Found a [GitHub Help suggestion](https://help.github.com/articles/getting-permanent-links-to-files/) with a solution for permanent file links that is more reliable than RawGit, and less hacky than linking to the commit.

**Comment by mheppler** [comment]
Assigning to @scolapasta to look at in more detail and make a decision on the best technical decision for this project.

**Comment by djbrooke** [comment]
@scolapasta - what are your thoughts here? This is currently marked as 4.5 so I'd like to move it forward. Thanks!

**Comment by pdurbin** [comment]
@mheppler I noticed that the Harvard logo was missing in the 2588-maintenance-pg branch like this...

![screen shot 2016-09-27 at 8 57 25 am](https://cloud.githubusercontent.com/assets/21006/18876422/ac2508cc-8497-11e6-9bb7-936bb18c51aa.png)

... so I made a change at 0230b8c to fix this. Now it looks better:

![screen shot 2016-09-27 at 9 37 03 am](https://cloud.githubusercontent.com/assets/21006/18876443/bcec7a50-8497-11e6-8497-c5b0e092a09d.png)

I had a brain fart while trying to get the "2588-maintenance-pg" branch up to date with develop and ended up merging 2588-maintenance-pg prematurely into develop. I backed this out of develop however and I think we're ready to make a pull request from the 2588-maintenance-pg branch. Any objections? Is there still more you want to do? I'm co-assigning this issue to you.

**Comment by pdurbin** [comment]
@mheppler and I discussed this issue and agreed we should go ahead and make a pull request, which I did at #3385

This issue and the pull request are in Code Review at https://waffle.io/IQSS/dataverse if anyone would like to take a look but I think it's ready for QA. @mheppler mentioned that as customization is worked on for #2003 the header might change to say "Harvard Dataverse" rather than just "Dataverse" or something.

**Comment by kcondon** [comment]
Looks good, closing.
