### ISSUE TITLE
Dataverse Alias: not supposed to be case sensitive, must be unique

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2598]
If you change the case of alias in url, you get an error message

https://dataverse.harvard.edu/dataverse/VPAL
for example, if you use "vpal" instead of VPAL, you get the error, and you can still create another dataverse using same alias in lower case (tested with Phil):

**Comment by eaquigley** [comment]
Moving out of 4.2 as all development for 4.2 has been completed.

**Comment by pdurbin** [comment]
I discussed this with @scolapasta explained the situation. He said we dealt with similar issues in the DVN 3.x days.

**Comment by pdurbin** [comment]
It looks like PostgreSQL supports the idea of a case insensitive uniqueness constraint:

- http://www.postgresql.org/docs/current/interactive/citext.html
- http://shuber.io/case-insensitive-unique-constraints-in-postgres/
- http://stackoverflow.com/questions/16905867/deferrable-case-insensitive-unique-constraint

We might lose some database portability though, which is suboptimal.

**Comment by scolapasta** [comment]
Before applying to production, we need to make sure there are no current dtaaverse aliases in conflict (currently there are 3 sets of conflicts, so 3 aliases will need to change).

**Comment by pdurbin** [comment]
> Before applying to production, we need to make sure there are no current dtaaverse aliases in conflict

Right. As @scolapasta and I discussed, I'll create a "curation" issue for the Harvard Dataverse. I just pushed the SQL script @scolapasta wrote to detect duplicate aliases: https://github.com/IQSS/dataverse/blob/e9b03af0af5c0484817996a2737369e7d707ecfc/scripts/issues/2598/detect-duplicate-dataverse-aliases.sql

Here's the output of the script when I run it locally:

```
murphy:dataverse pdurbin$ psql -f scripts/issues/2598/detect-duplicate-dataverse-aliases.sql dataverse_db
  alias   
----------
 773e0e31
 773E0E31
 5707a1f7
 5707A1F7
(4 rows)
```

(These funny alias names are created by the integration tests I just added to exercise this bug: e9b03af .)

Questions @scolapasta and I have about using the "citext" approach mentioned in http://shuber.io/case-insensitive-unique-constraints-in-postgres/

- Is the alias stored the way you put it in? Some users want uppercase or lowercase aliases specifically.
- Can you **find** the alias using either case with a `SELECT` statement?
- How do we express "citext" in JPA? I'm looking at http://stackoverflow.com/questions/12031613/postgresql-citext-datatype-issue-jpa-hibernate

We'll want an ALTER TABLE script to apply to production after there are no duplicate aliases.

**Comment by pdurbin** [comment]
I pushed a fix in 1ff9974 to make dataverse aliases case insensitive in a separate branch because cleanup of duplicate dataverse aliases must happen **before** the war file is deployed. (For Harvard's installation, see "curation" issue 66 for the status of this cleanup.)

If the cleanup is **not** done first, once you deploy the war file, you will be unable to visit either dataverse that has a duplicate alias because you'll get a 404 page. This means you'll be unable to rename or delete the duplicate dataverse. In Glassfish's server.log if you enable FINE logging with `asadmin set-log-levels edu.harvard.iq.dataverse.DataverseServiceBean=FINE` you'll see this when you get the 404:

> [CLASSNAME: edu.harvard.iq.dataverse.DataverseServiceBean] [METHODNAME: findByAlias] [[ Unable to find a single dataverse using alias "testdv": javax.persistence.NonUniqueResultException: More than one result was returned from Query.getSingleResult()]]

To add the index, run the following script but if it give you an error like this...

`psql -f scripts/database/upgrades/upgrade_v4.2.1_to_v4.2.2.sql dvndb`

```
psql:scripts/database/upgrades/upgrade_v4.2.1_to_v4.2.2.sql:2: ERROR:  could not create unique index "dataverse_alias_unique_idx"
DETAIL:  Key (lower(alias::text))=(testdv) is duplicated.
```

... uncomment the part of the script that will list duplicates and run it again so that you can see them:

```
 alias  
--------
 birds
 BIRDS
 testdv
 TESTDV
(4 rows)
```

Rename or delete all duplicate aliases (dataverses). Then you can deploy the war file. I made this long writeup here while it's fresh in my mind but it might be the sort of thing we add to our release notes.

The alias is still **stored** in the database with the case the user entered (i.e. "testdv") but you can **retrieve** the dataverse based on any variation of case (i.e. "TESTDV"). The user's preferred case will still appear in the URL and in the UI in general.

Incidentally, @scolapasta and I first tried to get the "citext" solution to work but it didn't. I was still able to create duplicate aliases. I left some notes about this in a script called [citext-for-dataverse-alias.sql](https://github.com/IQSS/dataverse/blob/1ff99744d8f10acf21414b1f5fd212773bd02f8b/scripts/issues/2598/citext-for-dataverse-alias.sql) but I didn't like how it's PostgreSQL-specific anyway.

Again, the fix above is in a branch so I'm passing this to @scolapasta to review and to decide if it should land in 4.2.2 or not. Again, the duplicate alias cleanup should be done **before** the war file is deployed so heads up to @sbarbosadataverse about this (issue 66 in the "curation" repo).

**Comment by scolapasta** [comment]
Since, the curation team will make sure all aliases are case insensitive unique by Friday, let's merge this branch and have QA test.

**Comment by pdurbin** [comment]
In 94983e4 I merged the 2598-unique-dataverse-alias branch into the 4.2.2 branch but as discussed this morning I'm going to hold on to this issue to see if I can figure out a way to add the constraint to the entity. If I can't I'll put the constraint in the reference data script.

**Comment by pdurbin** [comment]
@scolapasta it looks like our exact question was asked at http://stackoverflow.com/questions/25743191/how-to-add-a-case-insensitive-jpa-unique-constraint

There's no answer but a comment links to http://stackoverflow.com/questions/4031709/hibernate-annotations-case-insensitive-uniqueconstraint where the accepted answer says...

> With PostgreSQL, you would indeed do something like this to implement your requirement:
> 
> `CREATE UNIQUE INDEX My_Index on Component (lower(name));`
> 
> But there is to my knowledge no way to achieve this using annotations.

... but another answer that's voted up sounds a bit complicated to me. Can you please check it out? I think for the purposes of getting 4.2.2 out the door I would simply add the constraint we got working to the reference data script.

**Comment by scolapasta** [comment]
Good research - seems like it's not possible to do now. The more complicated answers is clever, but seems like overkill when we can add the sql. (one day, when they add it to JPA, we could simplify our code)

**Comment by pdurbin** [comment]
In 1ccac36 I added the new case-insensitive dataverse alias uniqueness constraint to the reference data script to ensure that new installs get it. It's the same as the one I added to the upgrade script.

I also wrote a SQL script to verify that it's working called insert-duplicate-alias.sql: https://github.com/IQSS/dataverse/blob/1ccac3675070488a6761b59342084a4eb5ba20f9/scripts/issues/2598/insert-duplicate-alias.sql

Here are the contents of the script (I have fewer than 100 dvobjects on my laptop):

```
-- This script should fail to insert a duplicate datavers alias (different case)
-- after a constraint has been added in https://github.com/IQSS/dataverse/issues/2598
DELETE FROM dataverse where id = 100;
DELETE FROM dataverse where id = 101;
DELETE FROM dvobject where id = 100;
DELETE FROM dvobject where id = 101;
INSERT INTO dvobject (id, createdate, modificationtime) VALUES (100, NOW(), NOW());
INSERT INTO dataverse (id, alias, name, dataversetype, defaultcontributorrole_id) VALUES (100, 'foo', 'foo is mine', 'UNCATEGORIZED', 1);
INSERT INTO dvobject (id, createdate, modificationtime) VALUES (101, NOW(), NOW());
INSERT INTO dataverse (id, alias, name, dataversetype, defaultcontributorrole_id) VALUES (101, 'FOO', 'uppercase foo', 'UNCATEGORIZED', 1);
```

Here's the "before" output (duplicate alias able to be inserted):

```
DELETE 1
DELETE 1
DELETE 1
DELETE 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
```

Here's the "after" output (no longer able to insert duplicate alias):

```
DELETE 0
DELETE 0
DELETE 0
DELETE 0
INSERT 0 1
INSERT 0 1
INSERT 0 1
psql:scripts/issues/2598/insert-duplicate-alias.sql:10: ERROR:  duplicate key value violates unique constraint "dataverse_alias_unique_idx"
DETAIL:  Key (lower(alias::text))=(foo) already exists.
```

There's also the DataversesIT integration test at 1ff9974 I added that verifies this bug is fixed.

@scolapasta has a potential lead on why the citext solution didn't work for us (and might post a link to the stackoverflow post here) but it's PostgreSQL-specific anyway.

Really what I want it to be able to express the case insensitive uniqueness constraint in JPA but (again) it doesn't seem to be possible. I'm not sure what the process would be to get this added in JPA 2.2 but I made a little noise about it at https://javabot.evanchooly.com/logs/%23glassfish/2015-11-19 and https://twitter.com/philipdurbin/status/667772604070146048

I'm moving this to QA. @kcondon in an upgrade scenario it's pretty important that the database be constraint be applied **before** deploying the new war file for reasons I explained in excruciating detail at https://github.com/IQSS/dataverse/issues/2598#issuecomment-157128524 so if you could mention this in the release notes I'd appreciate it. In production we're planning on applying the constraint as soon as curation issue 66 is closed, which looks like will happen well before we deploy 4.2.2 to production.

**Comment by kcondon** [comment]
OK tested creating two dv's with same alias but for case, prevented.
Tested using different cased alias in url, works.
As a bonus, tested changing alias completely, works.

Closing

**Comment by pdurbin** [comment]
@kcondon I'm re-opening this to make sure the migration script is working fine. Can you or @scolapasta run it in production to apply the case-insensitive uniqueness constraint? @posixeleni reports that all the aliases are unique now (see issue 66 under curation) so it can be applied at any time.

@sekmiller has added additional constraints to the migration script but here's just the part that I added for this issue: https://github.com/IQSS/dataverse/blob/94983e4d13d30d3866bfd339d122366987d10a88/scripts/database/upgrades/upgrade_v4.2.1_to_v4.2.2.sql

**Comment by pdurbin** [comment]
@scolapasta ran the constraint in production and it seemed to work fine.
