### ISSUE TITLE
Documentation: Add guidance on server size and managing file activity limits.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2617]
With more installations, some have asked about recommended server sizes and especially for smaller sizes, some discussion about limiting upload size, ingest size (by file type), download size, pdf size limit, separating out services to other hosts such as for R / analysis, and limiting memory available by R  process. Also, any gfish tuning we provide such as the G1 GC. These are all tactics we have used in production so should be spelled out as guidance to other admins.

See RT 227654 for a sample discussion with a new admin experiencing

**Comment by kcondon** [comment]
1. Limit ingest size (when to perform additional processing for tabular data files: Stata, SPSS, R, CSV)
2. Limit upload size (limit maximum upload size)
3. Rserve memory use (Rserve is used to ingest R data files and run online analysis using Two Ravens)
4. Rapache memory use (used to run online analysis using Two Ravens)
5. Limit download size
6. Limit image thumbnail size
7. Limit PDF thumbnail size

1. Limit ingest size (when to perform additional processing for tabular data files: Stata, SPSS, R, CSV)

The size limit is an application setting. It can be set for a specific supported format, like this:
curl -X PUT -d LIMIT http://localhost:8080/api/admin/settings/:TabularIngestSizeLimit:FORMAT
where LIMIT is the size limit in bytes; and FORMAT is a format identification tag, as reported by the plugin.
The tags for the currently supported format are as follows (case sensitive!):
dta
por
sav
Rdata
CSV
xlsx
So, for example, to set the limit for R files to 1000 bytes, the API call will be
curl -X PUT -d 1000 http://localhost:8080/api/admin/settings/:TabularIngestSizeLimit:Rdata

Also, it is possible to set a "blanket" size limit, that will apply to all tabular format - that would be simply
curl -X PUT -d LIMIT http://localhost:8080/api/admin/settings/:TabularIngestSizeLimit
(i.e., with no FORMAT tag).
Please note that different formats may have different thresholds. This coudld it also be used to disable tabular data ingests on a system - by enabling it and setting the value to zero.

We currently set all types to 2GB (2000000000) and then override just RData to be 1MB (1000000)

2. Limit upload size (limit maximum upload size)
curl -X PUT -d LIMIT http://localhost:8080/api/admin/settings/:MaxFileUploadSizeInBytes

3. Rserve memory use (Rserve is used to ingest R data files and run online analysis using Two Ravens)
Rserve memory limit:
Edit
/etc/init.d/rserve
Add the following, set the size to some appropriate number, leaving memory for the OS and other processes:
ulimit -v 4194304

4. Rapache memory use (used to run online analysis using Two Ravens)
This has not been tested but you could follow a similar approach to step3 but for the httpd process.

5. Limit download size
The current limit is 10GB. This will be tuneable but currently is not.

6. Limit image thumbnail size
        <jvm-options>-Ddataverse.dataAccess.thumbnail.image.limit=5000000</jvm-options>

7. Limit PDF thumbnail size
        <jvm-options>-Ddataverse.dataAccess.thumbnail.pdf.limit=500000</jvm-options>

These values do not need to be set but if you find your service is running out of memory while doing any of the above operations, experiment with these settings.

**Comment by pdurbin** [comment]
> Limit download size
> The current limit is 10GB. This will be tuneable but currently is not.

In the code I found a setting called "ZipDonwloadLimit" \[sic] documented as "Download-as-zip size limit. returns 0 if not specified; (the file zipper will then use the default value) set to -1 to disable zip downloads." I'm going to encourage @pameyer to play with this since he asked about it. That said, if it does work properly (#2686 makes me wonder), we should fix the spelling and document it (see also #2661 and #2283).

**Comment by pdurbin** [comment]
In my pull request at #2895 I attempted to address at least some of this issue. To preview the parts I worked on you can look here:

- http://guides.dataverse.org/en/2884-install-guide-reorg/installation/config.html#maxfileuploadsizeinbytes
- http://guides.dataverse.org/en/2884-install-guide-reorg/installation/config.html#tabularingestsizelimit
- http://guides.dataverse.org/en/2884-install-guide-reorg/installation/config.html#zipuploadfileslimit
- http://guides.dataverse.org/en/2884-install-guide-reorg/installation/config.html#dataverse-dataaccess-thumbnail-image-limit
- http://guides.dataverse.org/en/2884-install-guide-reorg/installation/config.html#dataverse-dataaccess-thumbnail-pdf-limit

I didn't really cover the Rserve stuff at all because I'm honestly quite confused about how it even works. This is probably evident by how I documented http://guides.dataverse.org/en/2884-install-guide-reorg/installation/config.html#dataverse-rserve-host and related JVM options. @landreev is the expert in this area.

Passing to QA.

**Comment by kcondon** [comment]
Looks good, closing.
