### ISSUE TITLE
Installation Guide: Document how to configure DOI and Handles.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2632]
Installation Guide does not mention doi and handle support and how to configure it. Also see RT 227504:

We currently support creating DOIs through EZID (http://ezid.cdlib.org/). You
would need to purchase a DOI namespace through them, then add credentials and
URL as JVM options to the domain.xml file and namespace information to the
settings table:

1. Add credentials and URL as JVM options to the domain.xml:
<glassfish install dir>/glassfish4/glassfish/domains/domain1/config/domain.xml

search for jvm-options and add the following to the same section:

<jvm-options>-Ddoi.password=your password</jvm-options>
<jvm-options>-Ddoi.username=your username</jvm-options>
<jvm-options>-Ddoi.baseurlstring=https://ezid.cdlib.org</jvm-options>

2. Add namespace information to the settings table
A note on DOI namespace, we try to use the format <authority>/DVN . You may
need to ask EZID for this form.

Add the following rows to the settings table:

thedata=# select * from setting where name like '%Doi%' or name=':Protocol' or
name=':Authority';
name | content
---------------+-------------
:Protocol | doi
:DoiProvider | EZID
:DoiSeparator | /
:Authority | 10.7910/DVN
(4 rows)

**Comment by kcondon** [comment]
Another customer wrote in with a support issue:

https://github.com/IQSS/dataverse/issues/2783

**Comment by bencomp** [comment]
Relates to configuring anything #2283

**Comment by pdurbin** [comment]
In my pull request at #2895 I took a quick swing at documenting this. The changes can be previewed in these areas:

- http://guides.dataverse.org/en/2884-install-guide-reorg/installation/config.html#doi-baseurlstring
- http://guides.dataverse.org/en/2884-install-guide-reorg/installation/config.html#doiprovider

@sekmiller is actively working on DataCite support in #24 so I'd recommend having him rewrite what little I wrote after he has merged in his code.

Passing to QA.

**Comment by kcondon** [comment]
OK, basics are documented, will update with DOI project. Closing.

**Comment by shlake** [comment]
One thing we encountered after doing the above configurations.... we had to restart glassfish. May suggest adding that instruction at the end - 

Once the domain.xml file has been edited, restart glassfish.

**Comment by pdurbin** [comment]
@shlake good suggestion. Thanks! I just added "Explain that rather than using `asadmin`, one can edit `domain.xml` but that this requires restarting Glassfish" to the list at #2944. In the DVN 3.x days we didn't promote `asadmin` and we typically mentioned that restarts are required when editing `domain.xml` by hand, such as here: http://guides.dataverse.org/en/3.6.2/dataverse-installer-main.html#google-analytics

**Comment by pdurbin** [comment]
@shlake actually, as it turns out I already documented this at http://guides.dataverse.org/en/4.2.4/installation/config.html#jvm-options which says "It’s also possible to change these values by stopping Glassfish, editing glassfish4/glassfish/domains/domain1/config/domain.xml, and restarting Glassfish."
