### ISSUE TITLE
Email Dataset Contact: Missing success message that email was sent

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2638]
Their is no "success" notification when someone uses the "email icon" contact in a dataset. The page refreshes leaving the user wondering if an email was sent.

**Comment by pdurbin** [comment]
Yeah, I just tried the "Email Dataset Contact" button for the first time at http://dx.doi.org/10.7910/DVN/8ZT5KF and it kind of feels like whatever I wrote went into a black hole since I didn't get any confirmation that an email was sent. I wasn't logged in and I'm not sure if that makes a difference or not.

Also, I was tripped up that "From" was asking for my email address rather than my name:

![screen shot 2016-10-24 at 9 13 51 am](https://cloud.githubusercontent.com/assets/21006/19647092/82910aea-99ca-11e6-9636-2eec355fa4f5.png)

I also sort of wonder what would have happened if I typed my email address wrong. I assume I would just never get a reply from the author. It's on me to type my own email address correctly, of course! 😄

**Comment by pdurbin** [comment]
The person who just filled out the form and clicked "Send Message" should see a success message saying something like "Your message has been emailed to the dataset contact and you have been emailed a copy of the message." This fixes a couple things:

- There's no more wondering if the message was sent or not because you see a success message.
- You get a copy of the message you wrote for your records (helpful if you put a lot of thought into what you wrote) or to remind you to follow up.

I still think that "From" should be more clear that it wants your email address, not your name. See the screenshot above.

This is on my mind because as I was telling @jggautier yesterday, I'm thinking about clicking "Contact" on http://dx.doi.org/10.7910/DVN/Y3WOOE to suggest that we add the related publication to that dataset.

**Comment by cmbz** [comment]
2023/10/02: Moving to Needs Sizing.

**Comment by scolapasta** [comment]
Tested; and the issue still exists - did not see any message of it being sent.

**Comment by pdurbin** [comment]
This just in from @Falco-KUB at https://groups.google.com/g/dataverse-community/c/LBrYAAIfCBo/m/KQxty6KbCAAJ 

"I have a related (but much more simple) question/request:
When using the contact form, offer to send a copy of the mail to the sender as well."

@Falco-KUB (or anyone reading this), if you have thoughts on what we should implement for this issue, please let us know! ❤️

**Comment by Falco-KUB** [comment]
Thanks, I suggest to always send a copy of the request by email to the person that fills out the form.

Add a short text below the "From" field in the contact form (or as mouseover):
"Enter your email address here. You will receive a copy of your message to this address."

There could be a checkbox to opt out from this default behaviour ("Do not send a copy of the message.").

Btw. when you are logged in, the email address is automatically added to the "From" field,

**Comment by qqmyers** [comment]
If someone who isn't logged in can add any mail address, this could potentially be used to spam people. Would it make sense to limit it to logged in users?

**Comment by Falco-KUB** [comment]
How else would non-registered users be able to contact dataset owners?

**Comment by qqmyers** [comment]
They can now, but if we add cc'ing the originating address, I can fill out the form using your address and have Dataverse send you an email asking you to come to my website.

**Comment by pdurbin** [comment]
I hate to bring this up but if we let logged in users receive a copy of the email, spammers could sign up for an account with someone else's email address (!) and spam people that way.* That is, until we finally get around to making email validation meaningful:

- #3300

(Currently when you validate your email, nothing really happens except for the fact being recorded in the database. In the future, after the issue above is address, Dataverse should ONLY send email to validated email addresses.)

\* very unlikely!

**Comment by Falco-KUB** [comment]
> If someone who isn't logged in can add any mail address, this could potentially be used to spam people. Would it make sense to limit it to logged in users?

Considering your comment, this might actually the best option.

**Comment by pdurbin** [comment]
For now I've made the smallest change possible (thank you @sekmiller for the assist with JSF):

- #10188

Please leave feedback here or there. I put a screenshot in the pull request above.

**Comment by sekmiller** [comment]
Looks good. I would just suggest a little more detail maybe "Message sent to Dataset Contact" or something

**Comment by cmbz** [comment]
202/12/15: Cleaning up status following move to V2 project. Appears that this issue is still "In Progress"? @sekmiller please confirm.

**Comment by pdurbin** [comment]
@cmbz I just removed it from the board because there's an open PR that will close this issue automatically when it is merged:

- #10188

**Comment by cmbz** [comment]
@pdurbin sorry, just noticed this one too. Apologies /0\
