### ISSUE TITLE
File Downloader notifications

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2654]
When the File Downloader role/permission is assigned at the dataset level, a notification is sent with a link to a dataset that the user is unable to view ("Not Authorized") is sent:

<img width="1218" alt="notify" src="https://cloud.githubusercontent.com/assets/21006/10589585/17cce496-767a-11e5-828a-2aabbdb2194b.png">

We'd like some sort of fix for 4.2.1. See also discussion at #2645 where this bug was originally reported.

**Comment by eaquigley** [comment]
Workflows for when the file downloader role notification should be sent to an end user:
- [ ] Published Dataset: Assign Role->Notification happens immediately
- [ ] Unpublished Dataset: Assign Role->Publish Dataset->Notification sent to user then (Currently notification is being sent as soon as it is assigned for an unpublished dataset).

**Comment by sekmiller** [comment]
This issue is handled correctly when you are assigning the downloader role on a given file.  It is not currently being handled when the file downloader permission is granted at the dataset level.

**Comment by sekmiller** [comment]
I have coded the notifications so that they will not be sent on an unpublished dataset and dataverse.

Currently there is a generic notification that applies to all role assignments.

You have been granted the <b>File Downloader</b> role for<b> Child of AKK Dataverse</b>.

@eaquigley  if you want there to additional verbiage associated with the granting of specific roles additional logic will have to be added. At this point I'm not sure how much work this will be.

**Comment by eaquigley** [comment]
@sekmiller I'd like to add in at the end, "You now have access to all restricted and unrestricted files in this dataverse.

Thanks!

**Comment by sekmiller** [comment]
Disclaimer per Liz added to File downloader notification and emails

**Comment by kcondon** [comment]
Notification now only sent when published for file downloader. Extra text added. Closing.
