### ISSUE TITLE
Assign Role Pop Up: File Downloader Assignment Confirmation

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2657]
Assign Role pop up: If someone is assigning file downloader role at the dataverse or dataset level, when they click Save Changes, we need to add a pop up that says, “Assigning file downloader role means the user(s) will be given access to all restricted and unrestricted files for all versions of this dataset.”

**Note**: Do we need a confirmation for other roles?

**Comment by mheppler** [comment]
Added static placeholder `confirmFileDownloader` dialog as a confirmation popup to the roles-assign pg for the dataverse/dataset permissions pg.

**Comment by mheppler** [comment]
Proposal to change the confirmation popup to additional help/info text in the Assign Role popup.

The original proposed text was:

“Assigning file downloader role means the user(s) will be given access to all restricted and unrestricted files for all versions of this dataset.”

Which can be generically/dynamically changed to:

“Assigning this role means the user(s) will _be given access/have this role applied_ to all _child objects/"dynamic list of objects"_ within this _dataverse/dataset_.”

**Comment by mheppler** [comment]
Added warning/info text to Assign Role popup on Dataverse/Dataset Permissions pg.

Passing to @sekmiller to wire up the object types.

![screen shot 2016-02-19 at 12 14 01 pm](https://cloud.githubusercontent.com/assets/687227/13182931/4a65fbb6-d702-11e5-98ab-e9c4b44a4a77.png)

**Comment by sekmiller** [comment]
Fix applied and checked into branch

**Comment by kcondon** [comment]
This fix is in branch 2572 according to Stephen: It's in the permissions branch 2572
It has not yet be made into a pull request.

**Comment by kcondon** [comment]
Leaving in QA but removing my name until I receive pull request.

**Comment by kcondon** [comment]
Reassign it to the person and say it needs CR before QA as was agreed upon by the team, move it back into the development column

**Comment by djbrooke** [comment]
@scolapasta - sounds like this needs CR - assigning to you! Thanks!

**Comment by djbrooke** [comment]
To be moved along with #2572.

**Comment by kcondon** [comment]
Variable text is in place but when assigning roles at the dataset level, the text in some cases also says, Dataverses: Assigning the Member role means the user(s) will have the Member role applied to all Dataverses, Datasets, Files within this Dataset.

Since this at the dataset level, dataverses should not be in the message. Not all roles includes dataverses, why?

Roles including dataverses at dataset level: admin, curator, member

**Comment by sekmiller** [comment]
Fixed the logic that displays the types of objects that a user will be granted permission on.

**Comment by kcondon** [comment]
The issue I previously reported was fixed but found one more, sorry!
When you assign roles at a dataverse, any sub dataverses do not automatically get those perms since currently dataverses are "permission root" meaning they define their own perms and do not inherit.
So, messages at dv level should also not include dataverses.

**Comment by kcondon** [comment]
Works, closing.
