### ISSUE TITLE
installer script is not stopping if the war file hasn't been deployed (and it does not say so)

### ISSUE THREAD

**Issue by ataturk** [IQSS/dataverse#2660]
When I try the "install" script (v 4.2), the script runs through saying: 
"
Setup done. Consider running post-install-api-block.sh for blocking the sensitive API.
ok!
"
even though the setup-all.sh script encounters errors, and the war file is not deployed:
"
/usr/local/glassfish4/glassfish/bin/asadmin list-applications
Nothing to list.
No applications are deployed to this target server.
Command list-applications executed successfully. 
"

**Comment by pdurbin** [comment]
I believe the fix is to work on this part of the code: https://github.com/IQSS/dataverse/blob/v4.2/scripts/installer/install#L1036-L1038

```
# FIXME: don't just sleep... figure out if the app is up yet.
print "\n--Sleeping for 3 minutes--\n";
sleep 180;
```

Higher up we copy the war file the the "autodeploy" directory: https://github.com/IQSS/dataverse/blob/v4.2/scripts/installer/install#L974

Instead, we should probably run `asadmin deploy` like this: https://github.com/IQSS/dataverse/blob/v4.2/scripts/deploy/apitest.dataverse.org/rebuild#L11 but then run `asadmin list-applications` in a loop for a few minutes to make sure the war file was deployed. The script should quit after a few minutes of trying and report if the war file couldn't be deployed.

**Comment by pdurbin** [comment]
@ataturk were you setting up a dev environment? @oscardssmith was having this trouble so we sat together and added 3c0c538 to the dev guide. I hope it helps.

**Comment by pdurbin** [comment]
I'm closing this in favor of #2443 where there is a lot more discussion. @ataturk please feel free to leave a comment on that other issue. Thanks!
