### ISSUE TITLE
can't restrict files, NullPointerException in populateDatasetUpdateFailureMessage(DatasetPage.java:2247)

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2668]
A regression was introduced recently in the 4.2.1 branch wherein it is impossible to restrict files. This has been reproduced independently by me and @sekmiller on out laptops. The stack trace below is from my laptop running 3ae2013 as originally reported at https://github.com/IQSS/dataverse/issues/2648#issuecomment-150238972

[stack.txt](https://github.com/IQSS/dataverse/files/18580/stack.txt)

@sekmiller said he'd take a look.

**Comment by bencomp** [comment]
Optimistic locking is a strategy for handling concurrency. As the message says, it appears that an object is changed or deleted by one process while at the same time another process tries to save a modification of the object.

I see a connection with #2460 in that concurrency is not implemented correctly.

**Comment by landreev** [comment]
@sekmiller - Steve, I should probably take this, because this has defintiely been caused by my changes from yesterday. (I know for the fact that we were able to restrict files yesterday; a few of us were able to that is).

**Comment by landreev** [comment]
This should be working now. 
However, the evil wrong file bug (which I believe is unrelated to this) may strike back without a warning. 
If you are observing it, comment out the versions tab, and try again (as described in my email earlier). 
I'm not suggesting disabling the versions tab as a reliable workaround. Just so that you may be able to test other issues. 
I'm hoping for some  insight from Steve and Gustavo - as to what could be happening in that tab to cause this.

**Comment by kcondon** [comment]
This is now working. Will separately test wrong file bug and open ticket as needed.
