### ISSUE TITLE
File Download: Sometimes getting the wrong file on download.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2677]
This bug has resurfaced. I will add steps to reproduce but it doesn't difficult to do: add multiple files to a dataset, download a file, get the wrong one.

**Comment by landreev** [comment]
@ekraffmiller 
@scolapasta 
@pdurbin 
@kcondon 
Here's another way to "fix" the "wrong file" bug: 
rather than commenting out the versions fragment in the xhtml, you can comment these 2 lines in the init() method of the DatasetPage: 

   setVersionTabList(resetVersionTabList());
   setReleasedVersionTabList(resetReleasedVersionTabList());

- so yeah, it is something in how this version differences tab is populated that messes up the order of an already rendered table...

**Comment by landreev** [comment]
@ekraffmiller
@scolapasta
@pdurbin
@kcondon
Actually, it appears to be enough to just comment out this one line: 

//setVersionTabList(resetVersionTabList());

- at least it fixes it for me, for a dataset where i'm consistently getting wrong files otherwise.

**Comment by landreev** [comment]
(of course it breaks the versions tab - it's rendered empty)

**Comment by landreev** [comment]
So, yeah - that was equivalent to disabling the versions tab fragment. 
Nevermind.

**Comment by landreev** [comment]
OK, I still own the ticket - but @sekmiller appears to have fixed the bug!
I have just merged Steve's changes in with some fixes I've been working on. (We were making a lot of changes to the same files). So it should be ready for testing.

**Comment by kcondon** [comment]
Works, closing
