### ISSUE TITLE
Files Tab: File count does not indicate how many files are currently displayed from total.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2681]
Infinite scroller maybe should be showing how many files are currently being displayed out of total. I have 1023 files, I am on the first or second page, how many are currently displayed?

**Comment by eaquigley** [comment]
Additionally, there needs to be a way to see how many files have been selected using the select all checkbox. Currently the only way to find out is to wait till you have selected files and then clicked Edit Metadata.

**Comment by sekmiller** [comment]
As we discussed in the meeting we're not going to deal with the number selected for now, but if there's some relatively easy way to get the number of files currently in the scroller to display that number to the user, that should be enough for now

**Comment by eaquigley** [comment]
why aren't we dealing with this now? with the scroller, i think it is necessary to show the number selected because you can't see all of the files anymore



On Oct 26, 2015, at 11:48 AM, Stephen Kraffmiller <notifications@github.com<mailto:notifications@github.com>> wrote:


As we discussed in the meeting we're not going to deal with the number selected for now, but if there's some relatively easy way to get the number of files currently in the scroller to display that number to the user, that should be enough for now

**Comment by sekmiller** [comment]
We aren't dealing this now because there is no way to capture the select and deselect file on the click event without using an ajax event which we removed because it was taking too long to refresh the page.  it's the same reason all of the buttons are active and only checked for validity when you click on it.

**Comment by pdurbin** [comment]
> if there's some relatively easy way to get the number of files currently in the scroller to display that number to the user

I looked through [the PrimeFaces 4.0 documentation ](http://primefaces.googlecode.com/files/primefaces_users_guide_4_0_edtn2.pdf) linked from http://www.primefaces.org/documentation and I'm not saying there isn't a way, but I couldn't find it.

The area of the code in question is in filesFragment.xhtml (near the top) and the size indicates the **total** number of files in the dataset version.

```
<div id="filesHeaderCount" class="col-xs-6 text-left">
    <!-- Files Count -->
    <h:outputFormat value="#{bundle['file.count']}" styleClass="highlightBold">
        <f:param value="#{DatasetPage.fileMetadatasSearch.size()}"/>
    </h:outputFormat>
</div>
```

So it's showing "33 files"...

![screen shot 2015-10-26 at 3 47 44 pm](https://cloud.githubusercontent.com/assets/21006/10740516/0d4ddc8a-7bf9-11e5-9a83-453e5f0ddae0.png)

... when what we want it to show is "25 of 33 files", similar to these mockups:

![screen shot 2015-10-26 at 3 49 40 pm](https://cloud.githubusercontent.com/assets/21006/10740552/3edb1ede-7bf9-11e5-942b-8166d751037a.png)

@sekmiller I'm passing this back to you since I couldn't find an answer quickly. Sorry. I did write a little script at scripts/issues/2681/create-files to create a zip file with an arbitrary number of files. Call it with `scripts/issues/2681/create-files 33` to create /tmp/33files.zip for example.

**Comment by pdurbin** [comment]
Yesterday @raprasad suggested using jQuery to count the number of visible rows. This is if we can't find a way for PrimeFaces to report the number of currently displayed files.

**Comment by sekmiller** [comment]
The problem here is that there's no event to trigger the update of the counts.  PrimeFaces has a new feature ticket to do so:

https://github.com/primefaces/primefaces/issues/65

**Comment by sekmiller** [comment]
@mheppler Thanks for offering to take a shot at this.  Not sure how to do it without some kind of triggering event.  See my notes above and the prime faces issue.

**Comment by eaquigley** [comment]
Related to #2716 as there needs to be a counter in that workflow as well. We need to figure out a solution.

**Comment by mheppler** [comment]
A new issue, **Dataset - File UI Improvements #3404**, was created to track the UI improvements related to the files view on the dataset pg. Older feature requests and bug reports like this one will be closed in favor of that new issue.
