### ISSUE TITLE
Privacy Error: dvn.iq.harvard.edu URLs not redirecting to dataverse.harvard.edu 

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2694]
To recreate:

I tried clicking on an old Dataverse URL http://dvn.iq.harvard.edu/dvn/dv/JAngrist from this website: http://economics.mit.edu/faculty/angrist/data1/data

And it takes a long time to load anything and when it does I am taken to a Privacy Error page.

This is not an isolated incident since I tried multiple dvn.iq.harvard.edu dataverse URLs and all of them had the same issue.

**Comment by pdurbin** [comment]
I think the problem is that the certificate has "**iq.dvn**.harvard.edu" (highlighted in blue in the screenshot below) rather than "**dvn.iq**.harvard.edu"

![screen shot 2015-10-26 at 2 00 20 pm](https://cloud.githubusercontent.com/assets/21006/10737799/942ec30e-7bea-11e5-98cd-f84c3d9eae24.png)

You can see from the screenshot above that I tested in on "kirk" but I get the same results on "picard".

@posixeleni do you have a sense of how long this has been a problem? I thought this was working. This should be the kind of thing we can monitor so at least we'll know if/when it stops working.

**Comment by kcondon** [comment]
Opened issue with LTS

**Comment by posixeleni** [comment]
@pdurbin I just found this issue today and had thought everything was
re-directing correctly since the Spring.

On Mon, Oct 26, 2015 at 2:26 PM, kcondon <notifications@github.com> wrote:

> Opened issue with LTS
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2694-23issuecomment-2D151237691&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=OiTcIL_jSSCUW82Gf-OSkgnZLbG2Yt87eT87BdLiP54&m=r2Z_u5SLNpYUd_NTykpCbxQDCI6k1Kn7-bE1PslTYYg&s=1-Rei-tz1oeSmjClJmS_9p0Jjn9LOfeY6l6apfN1zOY&e=>
> .
>



-- 

Eleni Castro

Research Coordinator, Data Acquisition and Archiving, Data Science

IQSS, Harvard University

http://www.iq.harvard.edu/people/eleni-castro

http://orcid.org/0000-0001-9767-8536


~Got Data? Check out the Dataverse Project. <http://dataverse.org/>~

**Comment by kcondon** [comment]
Your reference number for this matter is: INC01479262.

**Comment by posixeleni** [comment]
This is now working as expected. Thanks for the timely fix!
