### ISSUE TITLE
Saved Search : CommandException

### ISSUE THREAD

**Issue by Grimaldum** [IQSS/dataverse#2718]
Hi !

I just tried the "Saved Search" functionality and had a CommandException (attach file showing the problem) : Error – null edu.harvard.iq.dataverse.engine.command.exception.CommandException: Command edu.harvard.iq.dataverse.engine.command.impl.CreateSavedSearchCommand@187cb2e5 failed: null 

This happened in a dataverse organized like this : 
src:
Root => dataverse1 (Unpublished)=> dataverse2 (Unpublished) => Dataset (Unpublished)
target:
Root => dataverse3 (published)

I'm logged in as Admin (superuser). All this dataverses and the dataset has been made with this account.
Version is:  v. 4.2 build 92-d6443eb

Here is what I did:
I do a search in dataverse2 with the word "politique" (in the search field, not in Advanced Seach). Found one dataset (the one you see in the picture). I then click on "Link to your dataverse" => Link Search. Your dataverses : I select the dataverse3 => Save Linked Search, and then here is the exception.

![errorsavedsearch](https://cloud.githubusercontent.com/assets/14806890/10911118/87f1e18e-8243-11e5-8563-e8df0eedf2c7.png)

**Comment by pdurbin** [comment]
@Grimaldum thanks [spotting this](http://irclog.iq.harvard.edu/dataverse/2015-11-03#i_26575) for creating such a detailed issue! I can easily reproduce this in the 4.3 branch (I'm on 6fae1a9).

I went to http://localhost:8080/dataverse/finches and searched for "darwin" and clicked "Link Search", changed the target to "Trees Dataverse" and clicked "Save Linked Search":

![screen shot 2015-11-03 at 10 15 32 am](https://cloud.githubusercontent.com/assets/21006/10911828/abb7bbcc-8214-11e5-99ad-79b28c849943.png)

![screen shot 2015-11-03 at 10 20 55 am](https://cloud.githubusercontent.com/assets/21006/10911833/b10912ce-8214-11e5-8668-9f236d96687a.png)

Angry red: "Error – null edu.harvard.iq.dataverse.engine.command.exception.CommandException: Command edu.harvard.iq.dataverse.engine.command.impl.CreateSavedSearchCommand@4fc691dd failed: null Please contact support."

Something about "IllegalStateException: Not inside a request scope"...

Caused by: java.lang.IllegalStateException: Not inside a request scope.
        at jersey.repackaged.com.google.common.base.Preconditions.checkState(Preconditions.java:149)
        at org.glassfish.jersey.process.internal.RequestScope.current(RequestScope.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.findOrCreate(RequestScope.java:156)
        at org.jvnet.hk2.internal.MethodInterceptorImpl.invoke(MethodInterceptorImpl.java:74)
        at org.jvnet.hk2.internal.MethodInterceptorInvocationHandler.invoke(MethodInterceptorInvocationHandler.java:62)
        at com.sun.proxy.$Proxy482.getHeader(Unknown Source)
        at edu.harvard.iq.dataverse.engine.command.DataverseRequest.<init>(DataverseRequest.java:23)
        at edu.harvard.iq.dataverse.search.savedsearch.SavedSearchServiceBean.makeLinksForSingleSavedSearch(SavedSearchServiceBean.java:146)

... and toward the end of the stacktrace...

[2015-11-03T10:15:36.072-0500] [glassfish 4.1] [SEVERE] [] [edu.harvard.iq.dataverse.DataversePage] [tid: _ThreadID=133 _ThreadName=http-     listener-1(1)] [timeMillis: 1446563736072] [levelValue: 1000] [[
  There was a problem linking this search to yours: edu.harvard.iq.dataverse.engine.command.exception.CommandException: Command edu.harvard.  iq.dataverse.engine.command.impl.CreateSavedSearchCommand@4fc691dd failed: null]]

[2015-11-03T10:15:36.072-0500] [glassfish 4.1] [WARNING] [] [edu.harvard.iq.dataverse.util.BundleUtil] [tid: _ThreadID=133 _ThreadName=http-  listener-1(1)] [timeMillis: 1446563736072] [levelValue: 900] [[
  Could not find key "dataverse.saved.search.failure" in bundle file.]]

Here's the full stacktrace:

[stactrace-2718-6fae1a9.txt](https://github.com/IQSS/dataverse/files/26202/stactrace-2718-6fae1a9.txt)

**Comment by pdurbin** [comment]
@michbarsinai can you please take a look at this issue? @sekmiller @scolapasta and I are wondering if it's related to c10cbd9 as part of #1257 (when DataverseRequest object was introduced), which was part of 4.2.

Also, I spoke with @sbarbosadataverse and it sounds like she'll need this functionality working in the near future. (@sbarbosadataverse please feel free to mention RT ticket numbers if they exist.) I'm going to mark this High for now.

**Comment by pdurbin** [comment]
Ok, I'm more and more convinced this regression has something to do with the introduction of the DataverseRequest object. I can make the bug go away if I comment out the following lines from DataverseRequest.java:

```
murphy:dataverse pdurbin$ git diff
diff --git a/src/main/java/edu/harvard/iq/dataverse/engine/command/DataverseRequest.java b/src/main/java/edu/harvard/iq/dataverse/engine/command/DataverseRequest.java
index d0c08cd..b61ffa0 100644
--- a/src/main/java/edu/harvard/iq/dataverse/engine/command/DataverseRequest.java
+++ b/src/main/java/edu/harvard/iq/dataverse/engine/command/DataverseRequest.java
@@ -20,14 +20,14 @@ public class DataverseRequest {
         this.user = aUser;
         String remoteAddressStr = null;
         try {
-            remoteAddressStr = aHttpServletRequest.getHeader("X-Forwarded-For");
+//            remoteAddressStr = aHttpServletRequest.getHeader("X-Forwarded-For");
         } catch ( NullPointerException _npe ) {
             // ignore
         }
         
         if ( remoteAddressStr == null ) {
             try {
-                remoteAddressStr = aHttpServletRequest.getRemoteAddr();
+//                remoteAddressStr = aHttpServletRequest.getRemoteAddr();
             } catch ( NullPointerException _npe ) {}
         }
         
murphy:dataverse pdurbin$ 
```

**Comment by pdurbin** [comment]
@michbarsinai thanks for pointing this out: fix for batch migration to create DataverseRequest and then pass it along 2a8291e . I'm stealing this issue to see if I can figure out a similar fix.

**Comment by pdurbin** [comment]
Note to self and other developers that because it's impossible to delete links other than through direct database calls (#1364), my old scripts below (followed by an "index all") are coming in handy for me in dev for deleting links: 

```
murphy:dataverse pdurbin$ scripts/search/dblinks
+ /Users/pdurbin/.homebrew/bin/psql -c 'select * from dataverselinkingdataverse order by id;' dataverse_db
 id | linkcreatetime | dataverse_id | linkingdataverse_id 
----+----------------+--------------+---------------------
(0 rows)

+ /Users/pdurbin/.homebrew/bin/psql -c 'select * from datasetlinkingdataverse order by id;' dataverse_db
 id |     linkcreatetime     | dataset_id | linkingdataverse_id 
----+------------------------+------------+---------------------
  1 | 2015-11-05 14:17:30.19 |         11 |                   7
(1 row)

+ exit
murphy:dataverse pdurbin$ scripts/search/dblinks-delete
+ /Users/pdurbin/.homebrew/bin/psql -c 'delete from dataverselinkingdataverse;' dataverse_db
DELETE 0
+ /Users/pdurbin/.homebrew/bin/psql -c 'delete from datasetlinkingdataverse;' dataverse_db
DELETE 1
murphy:dataverse pdurbin$ 
murphy:dataverse pdurbin$ curl http://localhost:8080/api/admin/index
{"status":"OK","data":{"availablePartitionIds":[0],"args":{"numPartitions":1,"partitionIdToProcess":0},"message":"indexAllOrSubset has begun of 9 dataverses and 2 datasets."}}
```

**Comment by pdurbin** [comment]
Also useful when working on this issue are API calls like `curl http://localhost:8080/api/admin/savedsearches/list` and `curl -X PUT http://localhost:8080/api/admin/savedsearches/makelinks/all` as documented at http://guides.dataverse.org/en/4.2.1/api/native-api.html#saved-search . (There's a nice writeup there about just how experimental this feature should be considered.)

The way the "Link Search" feature works is by persisting a Saved Search and then running a method to make links (followed by indexing). This was all developed in #90.

**Comment by pdurbin** [comment]
I just pushed a fix at 6f8ee3a into the 4.3 branch.

@scolapasta I'm giving this issue for you to review the commit before passing to QA. I also added this issue to the 4.2.2 milestone since @sbarbosadataverse has [a need](https://github.com/IQSS/dataverse/issues/2718#issuecomment-154147324) to use this ([experimental](http://guides.dataverse.org/en/4.2.1/api/native-api.html#saved-search)) feature in production.

@michbarsinai you are welcome to look too! Perhaps there is a better fix but this is what I could get working without breaking `curl -X PUT http://localhost:8080/api/admin/savedsearches/makelinks/all` . I *think* it's fine.

**Comment by pdurbin** [comment]
One more thing. There's a messaging component that isn't fixed yet, even with the main backend fix at 6f8ee3a .

I'm still seeing 'Could not find key "dataverse.saved.search.success" in bundle file.' in the logs. I assume this is easy to fix but I don't want to forget about it. @mheppler or @eaquigley do you know if the name of the key changed or something? I'm pretty sure the failure message isn't working either since above the stacktrace said 'Could not find key "dataverse.saved.search.failure" in bundle file.'

**Comment by eaquigley** [comment]
@pdurbin I've checked the bundle and dataverse.saved.search.success does not exist in it so it looks like the success and error messages for this feature were never created.

**Comment by pdurbin** [comment]
@eaquigley as we discussed, this issue is primarily about fixing the regression so the "Link Search" feature works again. It's slated for 4.2.2 and we don't want to hold up that release fiddling with these messages. We plan to do a full feature review at some point and I just left a reminder about this specific messaging problem on that issue: https://github.com/IQSS/dataverse/issues/1840#issuecomment-154695111

@scolapasta the status of this issue is that I'd still like you to review the bug fix I made at 6f8ee3a

**Comment by pdurbin** [comment]
@scolapasta and I just discussed 6f8ee3a and I think we agree on the following:

- the bug fix it's probably good enough to ship (it was the first thing I got to work)
- we'd like @michbarsinai to weigh in, ideally, in case there's a better/cleaner fix

**Comment by pdurbin** [comment]
@scolapasta as I mentioned in our meeting this morning, @michbarsinai popped into http://chat.dataverse.org this morning and took at look at 6f8ee3a. If you would please review his comments I would appreciate it: http://irclog.iq.harvard.edu/dataverse/2015-11-13#i_26977

I'll put them below as well:

13:00 pdurbin_m    michbarsinai: dunno. hey, can I please get some code review of https://github.com/IQSS/dataverse/commit/6f8ee3a00d1915f3f3d2a2cb0e019812a91f10fe
13:01 michbarsinai Sure
13:02 michbarsinai OK, I'm there
13:06 pdurbin_m    michbarsinai: is that how you'd fix the regression?
13:07 michbarsinai That
13:07 michbarsinai 's one way of doing it. I think I might have gone with another way,
13:07 michbarsinai as this one is very state-ful
13:08 michbarsinai so, the httprequest is kept around in a field. I don't see how it can be exploited, though.
13:08 michbarsinai But still, even if there's no security issue it cannot be garbage collected.
13:09 michbarsinai Can you add the HttpRequest as a parameter to the method the client code is calling?
13:09 michbarsinai This way, the service bean won't need to refere to JSF context
13:10 michbarsinai Basically, the same logic (JSF gets special treatment) but with the if and state removed.

**Comment by pdurbin** [comment]
@scolapasta something else I just remembered is that my fix (6f8ee3a) is in the 4.3 branch (the 4.2.2 branch didn't exist back then): https://github.com/IQSS/dataverse/issues/2718#issuecomment-154432109

**Comment by eaquigley** [comment]
@pdurbin 

Success: The saved search has been successfully linked to {insert Dataverse name here with link}.

Error: The saved search was not able to be linked to {insert Dataverse name here with link}. Please contact support@dataverse.org for assistance (I believe there is a way in the messaging to have this appear without having to type it in…I feel like @scolapasta  knows about this.)

Misc: Why are the facets in a saved search pop up (image attached) the robot way and not the plain text we see in the facets?

![screen shot 2015-11-19 at 1 39 05 pm](https://cloud.githubusercontent.com/assets/5922904/11280629/dda9cc62-8ec4-11e5-8788-7be53c154c22.png)

**Comment by pdurbin** [comment]
> Misc: Why are the facets in a saved search pop up (image attached) the robot way and not the plain text we see in the facets?

@eaquigley the robotic look of the facets is already filed as in this issue: #1890. I think this is all "Linked/Saved Search: Review Functionality + Usability Test" territory per #1840.

Thanks for the messaging text! I'm working on putting it in now.

**Comment by pdurbin** [comment]
@kcondon pointed out that it's awfully nice to have some messaging on success or failure so I added some in b6cd847 based on @eaquigley 's input above. Here's how they look:

![screen shot 2015-11-19 at 3 23 44 pm](https://cloud.githubusercontent.com/assets/21006/11283351/3d9c04f2-8ed2-11e5-968b-d9468928b6b8.png)
![screen shot 2015-11-19 at 3 16 08 pm](https://cloud.githubusercontent.com/assets/21006/11283352/3d9e3fc4-8ed2-11e5-9c11-6605ab8cfe45.png)

Sadly, the success message is a half-truth. The links are made when you click the button (which can be slow if there is a lot of content per #1939), but per #2531 and #2543 new links are not automatically added when new content is added that matches the saved search. I want to write, "Go have your sysadmin set up a cron job like the one in #2531" but this is obviously ridiculous.

The error message has been simplified a bit but at least it exists. Again, this feature is quite experimental: http://guides.dataverse.org/en/4.2.1/api/native-api.html#saved-search

@scolapasta @kcondon as we've discussed the fix I mentioned at 6f8ee3a **is** in the 4.2.2 branch afterall (sorry for the confusion). @kcondon has already confirmed the regression is fixed.

@scolapasta I'd like to move this issue into QA. It's still in your name because you were hoping to chat with @michbarsinai .

**Comment by pdurbin** [comment]
@kcondon the status on this issue is that @scolapasta and I are planning to talk to @michbarsinai about it on Monday at 2pm.

**Comment by pdurbin** [comment]
@scolapasta and I Skyped with @michbarsinai and I'm going to try a better fix. Like in f3cac1c I'll be removing `@Context HttpServletRequest httpRequest` from a service bean.

**Comment by pdurbin** [comment]
In e058a91 in a new "2718-refactor" branch I changed the `makeLinksForSingleSavedSearch` method to take a `DataverseRequest` object. @scolapasta @michbarsinai and I think this is a much cleaner solution than the hack I put in at 6f8ee3a, which I took out. However, I put the code in a new branch and will give this to @scolapasta to think about because it will change the solution (the cron job) we put in for #2531 to make new links (future dev will be in #2543). We would need to create a "system user" with superuser powers.

It's probably easiest to give an example.

Here's how I tested the code, which is pretty specific to the birds and trees dataverses I have on my laptop:

First, I repeated the "search for 'darwin' and create a Linked Search in 'Trees'" scenario described at https://github.com/IQSS/dataverse/issues/2718#issuecomment-153388982 and confirm  that "Darwin's Finches" appears under "Trees". (There's a handy link to follow now that messaging has been improved in b6cd847 ).

Then I ran `curl -s http://localhost:8080/api/admin/savedsearches/list | jq .` to take a look at the saved search I just created, which looked good:


```
{
  "status": "OK",
  "data": {
    "saved searches": [
      {
        "query": "darwin",
        "filterQueries": [
          "dvObjectType:(dataverses OR datasets OR files)",
          "subtreePaths:\"/2/3\""
        ],
        "id": 1,
        "definitionPointId": 7,
        "definitionPointAlias": "trees",
        "creatorId": 1
      }
    ]
  }
}
```

Now, imagine a new dataset is created called "Darwin's Goldfinches" right next to "Darwin's Finches". #2531 was about putting a cron job in production so that the Linked Search picks up and links the new dataset (since it has "darwin" in it) in 24 hours or whenever the cronjob runs. However, `curl -X PUT http://localhost:8080/api/admin/savedsearches/makelinks/1` with no API token doesn't "just work" anymore. You get the error '{"status":"ERROR","message":"Please provide a key query parameter (?key=XXX) or via the HTTP header X-Dataverse-key"}'

The question becomes, whose API token should I use? Making these links on a periodic basis is very much a **system** thing. Would we create a special **system user** with superuser powers to periodically execute the saved searches and create new links? This is the question for @scolapasta @michbarsinai (I chatted with @sekmiller about this as well).

We can't just use the "Guest" user (when creating the DataverseRequest inside the "makelinks" API call, I mean) because you get `Can't execute command edu.harvard.iq.dataverse.engine.command.impl.LinkDatasetCommand@d205a70, because request [DataverseRequest user:edu.harvard.iq.dataverse.authorization.users.GuestUser@7@0:0:0:0:0:0:0:1] is missing permissions [PublishDataverse] on Object Trees`.

**Comment by pdurbin** [comment]
I refactored the code again to avoid needing to add "system" account but to achieve the goals that @scolapasta and @michbarsinai have explained to me, which are:

- Remove `@Context HttpServletRequest httpRequest` from SavedSearchServiceBean to avoid stale state.
- Pass a DataverseRequest object to the "make links" method rather than having the method construct the DataverseRequest object.
- Set the HttpServletRequest in the DataverseRequest object to null for better security.

It all seems to work so I pushed

into 4.2.2 and am moving this to QA (but @scolapasta and @michbarsinai or anyone should feel free to grab it out of QA if they disagree with what I've done!).

Here's how I tested the code, which is pretty specific to the birds and trees dataverses I have on my laptop:

First, I repeated the "search for 'darwin' and create a Linked Search in 'Trees'" scenario described at https://github.com/IQSS/dataverse/issues/2718#issuecomment-153388982 and confirmed that "Darwin's Finches" appears under "Trees". (There's a handy link to follow now that messaging has been improved in b6cd847 ).

Then I ran `curl http://localhost:8080/api/admin/savedsearches/list` to take a look at the saved search I just created. It looked fine, like this:

```
{
  "status": "OK",
  "data": {
    "saved searches": [
      {
        "query": "darwin",
        "filterQueries": [
          "subtreePaths:\"/2/3\"",
          "dvObjectType:(dataverses OR datasets OR files)"
        ],
        "id": 3,
        "definitionPointId": 7,
        "definitionPointAlias": "trees",
        "creatorId": 1
      }
    ]
  }
}
```

Then I created a dataset called "Darwin's Goldfinches" next to "Darwin's Finches". As expected, it wasn't linked immediately (this is what #2543 is about).

To link the new dataset I just created, I ran the following curl command:

`curl -X PUT http://localhost:8080/api/admin/savedsearches/makelinks/3`

This is the output I got, which is normal and expected:

```
{
  "status": "OK",
  "data": {
    "hits for saved search id 3": [
      {
        "definitionPointAlias": "trees",
        "savedSearchId": 3,
        "hitInfo": [
          {
            "name": "Darwin's Finches",
            "dvObjectId": 11,
            "result": "Skipping because dataverse [Dataverse id:7 name:Trees] already links to dataset [Dataset id:11 ]."
          },
          {
            "name": "Darwin's Goldfinches",
            "dvObjectId": 14,
            "result": "Persisted DatasetLinkingDataverse id 6 link of [Dataset id:14 ] to [Dataverse id:7 name:Trees]"
          }
        ]
      }
    ]
  }
}
```

Then both datasets were linked:
![screen shot 2015-11-24 at 2 14 13 pm](https://cloud.githubusercontent.com/assets/21006/11378238/3643a64e-92b8-11e5-818d-78904a43eda6.png)

(As I was saying to @kcondon I didn't test what happens if you remove superuser powers from the user who created the search before you run this "makelinks" command but I expect it to fail.)

I also ran `curl -X PUT http://localhost:8080/api/admin/savedsearches/makelinks/all` and it worked fine.

Passing to QA. I would suggest testing what I've described above and also Saved Search in general. Once again, this feature should be considered quite experimental, especially since you can't delete links (#1364)! See also warnings at http://guides.dataverse.org/en/4.2.1/api/native-api.html#saved-search

**Comment by kcondon** [comment]
Tested, it works with one edge case: if the creator no longer has publish dv permission as in the case of some larger dv's where admins move on, then the saved search  makelinks command would fail, the link would have stale content.

This may or may not be easily detectable and would require a support ticket and someone to update the db to change the link creator to another user with publish dv permission. 

After discussing with Phil, I'm opening a separate ticket for this issue and closing this one.

**Comment by pdurbin** [comment]
> if the creator no longer has publish dv permission as in the case of some larger dv's where admins move on, then the saved search makelinks command would fail, the link would have stale content

Right. We'll work on this in #2770. I'll explain the work around there.

**Comment by pdurbin** [comment]
> In e058a91 in a new "2718-refactor" branch

I'm just noting here that since we didn't go with that commit as a solution I'm going to delete that branch.
