### ISSUE TITLE
Linking to large external datasets

### ISSUE THREAD

**Issue by mutanthumb** [IQSS/dataverse#2728]
We have a  server for archived data (large files) and the plan is to use a Globus link to connect our data repository (currently DSpace) to the file. The majority of our datasets will be a reasonable size and can exist within a system such as Dataverse but some will be larger than Dataverse (or DSpace) will allow. For these large files ideally the metadata for the data file would exist within the Dataverse interface but the file will actually reside elsewhere and will be linked via a Globus link. So rather than uploading a file to Dataverse when the file metadata is entered a link would be entered instead. 

We will be running our instance of Dataverse.

**Comment by pdurbin** [comment]
@mutanthumb thanks for opening this issue! I thought I'd link the discussion on the mailing list for some additional context: https://groups.google.com/forum/#!topic/dataverse-community/Pe6znGA000Y

In that thread @eugene-barsky mentioned https://www.computecanada.ca/research-portal/national-services/globus-portal/ and said he'll be able to report back to the Dataverse community with more information.

There are actually a lot of projects in the air related to large files such as https://hms.harvard.edu/news/dropbox-structural-biologists

I also can't resist uploading a quick doodle (just an idea!) by @michbarsinai about large files:

![largefileservice](https://cloud.githubusercontent.com/assets/21006/11152310/c0d357da-89ff-11e5-83ae-cf556eb13e77.png)

**Comment by eugene-barsky** [comment]
Yep, I plan to work on Globus/Dataverse integration maybe in Q1 2016 with
Compute Canada

E

**Comment by posixeleni** [comment]
Just in case we want to consolidate this ticket this appears to be related to #1347

**Comment by pdurbin** [comment]
This issue is at least somewhat related to "Support The Ability To Resume Disrupted File Downloads" at #2960. Mostly because of the LargeFileService diagram that appears here. @michbarsinai when you get a chance can you please attach the plantuml file for that diagram?

**Comment by michbarsinai** [comment]
1 diagram, coming up.
[fileMicroService.txt](https://github.com/IQSS/dataverse/files/149562/fileMicroService.txt)

**Comment by pdurbin** [comment]
@mutanthumb @eugene-barsky what are your current thoughts on this issue? I wanted to point out that Globus is part of the plan for #3403.

**Comment by pdurbin** [comment]
I'd like to point out that the way our support for large file via rsync is working out, we are effectively creating more or less the "link" @mutanthumb wants for Globus but for rsync.

Here's how the new special data file with a custom MIME Type of `application/vnd.dataverse.file-package` in our new world of rsync (screenshot taken from https://github.com/IQSS/dataverse/issues/3725#issuecomment-302399257 ):

![screen shot 2017-05-17 at 5 08 25 pm](https://cloud.githubusercontent.com/assets/21006/26208367/e06efeb2-3bb7-11e7-8f45-2e0ca30b5d81.png)

Relevant to this issue, this new `application/vnd.dataverse.file-package` file differs from ordinary files in that it's really just a representation of a set of files. In Slack yesterday we heard, "Again, the (current) purpose of the "package" is to represent a set of files that are individually meaningless."

@mutanthumb @eugene-barsky do you have any thoughts on this? Is this the direction you're looking for but for Globus instead of rsync?

**Comment by mutanthumb** [comment]
Yes, Phil that's exactly right.  I just want say that I appreciate all of your work on this, unfortunately we will not be proceeding with a data repository.

- susan

**Comment by pdurbin** [comment]
@mutanthumb oh! In that case I'm going to close this issue. Please let us know if you change your mind. 😄 

@eugene-barsky or anyone else listening, if you're still interested in Globus support, please open a fresh issue. Thanks!

**Comment by mutanthumb** [comment]
Thanks Phil sorry to drag it out like this!
