### ISSUE TITLE
Pin footer to the bottom of the viewport

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2747]
In the app, the footer moves around if a page has less content or no content. 

Pages experiencing this where it is really noticeable:
- My Data (when there is nothing or not many)
- Notifications (when there are none or not many)
- Account Information
- Permissions Pages (Dataverse, Dataset, Files)
- Templates (when there are no templates or not many)
- Groups 
- Manage Dataset Guestbooks

Note: When I say really noticeable, I am referring to how when you move from one page to the other the footer moves and is distracting, sometimes you see it, sometimes you don't.

**Comment by TaniaSchlatter** [comment]
Pinning the footer to the bottom of the viewport will address the issue of the footer jumping around.

**Comment by pdurbin** [comment]
Is the idea that the footer will **always** be visible? If so, I'm concerned about Dataverse installations with tall footers such as https://data.cifor.org will lose a lot of valuable screen real estate. Mockup below.

![screen shot 2019-02-13 at 9 09 59 am](https://user-images.githubusercontent.com/21006/52717494-3810a100-2f6f-11e9-86f9-40d582f11096.png)

**Comment by TaniaSchlatter** [comment]
That’s a good point @pdurbin. Can we make it configurable/easy to turn off?

**Comment by mheppler** [comment]
Added some CSS to make the footer sticky to the bottom of the browser window if the content is short, or the bottom of the content if it's longer than the browser window.

Made sure the footer for widgets still is `fixed` as intended by design. Looked at some customization as well, like the one pointed out above, and that will require some CSS tweaking but is still achievable.

**NOTE:** This feature will require release notes instructions to update any current custom CSS associated with the footer.

![screen shot 2019-02-19 at 3 17 56 pm](https://user-images.githubusercontent.com/687227/53044952-63592b80-345a-11e9-9321-f7fc0f399248.png)
