### ISSUE TITLE
Extend SWORD API to work with ScholarOne Journal Publishing System, and others

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2748]
At the moment ScholarOne is reviewing our API documentation and once they begin development work we will work with them to tweak the API to work for their system as well.

This is just a high-level placeholder ticket for the moment but is part of grant project deliverable.

**Comment by sbarbosadataverse** [comment]
@scolapasta 
@mcrosas 

I'm trying to get an update on what we are doing with scholar one API integration---this seems to fall short of a decision on our end or theirs?

**Comment by sbarbosadataverse** [comment]
Just adding additional notes to this:

"ScholarOne submitted their proposal for implementing integration to OUP and the ball is in OUPs court to give them the greenlight to begin development. Eleni will follow-up with both ScholarOne and OUP to see if any agreement has been made and if there is a timeline for this feature being enabled." (OUP is Oxford University Press.)

From Harvard-Odum Sloan Project Meeting Minutes 2015-10-28 https://docs.google.com/document/d/1Q1-67oeOaIwiSaYksrTB7rP9GYDGeIenIN-haHpZZEk/edit?usp=sharing

Merce was there so I'll add her to cc.

That was a follow up to call we had with ScholarOne on 2015-09-22: https://docs.google.com/a/harvard.edu/document/d/10pw2PGwOuugzCqdni7cHLDiKtiMBmG7WzU59UPfq31k/edit?usp=sharing

**Comment by pdurbin** [comment]
> OUP ticket is closed, they will not use scholarone API

Maybe we should close this issue too, then.

**Comment by jggautier** [comment]
Since there isn't a use-case anymore for this method of integration with ScholarOne I'll close this issue.

There is interest from Cambridge University Press in a "lighter-weight" method of integration (see [Merce's comment](https://github.com/IQSS/dataverse-curation/issues/49#issuecomment-252320322) at https://github.com/IQSS/dataverse-curation/issues/49), so we can create a new issue if/when that work is planned.
