### ISSUE TITLE
Groups - User name dropdown list width inconsistent

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2768]
When  creating a group under permissions, after adding the first account name, the user name dialogue box doesn't expand to show all account info available for a user (name/affiliation/username).

**Comment by kcondon** [comment]
Had Sonia demo the issue:
1. On dataverse permissions page, create a group.
2. Select one user and in the same dialog session, select a second user.

Notice with the first user, the select user drop down is the width of the entire edit text field and so can see all the columns: name, affiliation, username but when you add a second user, it is much narrower and you can't see all the columns: anchored on the left side by the position of the second username and anchored on the right by the right side of the edit text box.

Gustavo asked that @mheppler take a look at it.

**Comment by mheppler** [comment]
Looked at this issue in 4.2.2 locally and on dataverse-internal, as well as in 4.2.3 locally and on dvn-build. The upgrade to PrimeFaces 5 in 4.2.3 seems to have done away with this issue on the Create Groups popup because I am seeing a different behavior, that displays the dropdown list in fully.

I am sending this issue back to QA, and I recommend closing it, as it will be fixed in the upcoming 4.2.3 release. Also, from what I can tell with the data locally and on the two test environments, the user information is still being fully displayed in both columns of the skinnier dropdown, so the component is still usable.

**Comment by kcondon** [comment]
Looks good, closing.
