### ISSUE TITLE
Manage Templates: Clicking edit dropdown button on last template in list displays below the fold and creates scrollbars.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2769]
On the manage templates page, the edit button displays a drop down list for metadata and terms. In v4.2.3, this displays inside the table below the line for the template. So, for the last one in the list the edit button displays below the fold and causes scroll bars to appear. This does not happen in v4.2.2.

**Comment by mheppler** [comment]
Fixed overflow style issue with dropdown buttons in datatables. Check other manage-type pages, like Groups and Guestbooks, and those pages do not have dropdown buttons in the datatable.

Going forward, anytime a dropdown button is used in a datatable, we'll have to apply these new style class to the markup in order to resolve this layout issue with PrimeFaces + Bootstrap.

**Comment by kcondon** [comment]
Works, closing
