### ISSUE TITLE
Themes & Widgets: When selecting rectangular layout for image, logo alignment select box is sized too small.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2771]
The logo alignment select box for rectangular logo format is sized too small: less than one character so "Left" is the top choice and you barely see "L". Once selected they appear correctly as a list.

This does not happen in v4.2.2.

**Comment by mheppler** [comment]
Removed panelGrid components from themeAndWidgets form that was causing layout issues.

The validation error messages, as well as the form input components on the page, were inside of a PrimeFaces panelGrid component. Since those weren't necessary, I removed them, and that resolved the sizing issue for the select menu.

**Comment by kcondon** [comment]
No longer an issue, closing.
