### ISSUE TITLE
Add "Relation Type" to related publication metadata fields to send DataCite related publication metadata

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2778]
comment from @bencomp in #2774 

> the DataCite metadata schema v3.1, if a related identifier is included (e.g. for publications that build on the dataset), a relation type must be given.

**Comment by augustfly** [comment]
commenting for reasons of tracking this thread and opinion, but jumping on board with DOI/DataCite relation types is something Dataverse really should do. the controlled vocab and use cases are there for the reuse. i'm sure there are UI issues downstream from implementing it though.

**Comment by jggautier** [comment]
In the article "Pre-Metadata Counseling: Putting the DataCite relationType Attribute into Action" ([PDF](https://www.ideals.illinois.edu/bitstream/handle/2142/95785/Curating%20Research%20Data_v2_Case%20Study_Pre-Metadata%20Counseling.pdf?sequence=3&isAllowed=y)), the team behind [Illinois Data Bank](https://databank.illinois.edu/) write about using DataCite's relationType terms. They decide in their longer ["overly honest" article](http://journal.code4lib.org/articles/11980) about the repository's development that the terms are too difficult to use (hard to define, too much overlap) to expect depositors to apply them consistently, so their curators apply them after dataset publication and they use only six of the 25.

This makes me think it would be a good idea to lessen the confusion when this is implemented by:
- Starting with a limited number of relationType terms available in the deposit form
- Letting depositors choose multiple relationTypes (considering the overlap in terms)

**Comment by pdurbin** [comment]
> they use only six of the 25

The six seem to be "Article, Code, Dataset, Presentation, Thesis, or Other" unless I misunderstand. This issue may be a candidate for adding a user story (as discussed in retrospective this afternoon) because I'm getting a little lost on who wants what and why.

**Comment by augustfly** [comment]
Those are the object types, Phil. The 6 relations are IsSupplementTo, IsCitedBy, IsNewVersionOf/IsPreviousVersionOf and the IsPartOf/HasPart pair. 

I think narrowing terms/relations is wise; it has always felt like the DataCite list was made to appear to cover edge cases, which leads to unnecessary confusion. I don't see much overlap in those 6 relations though someone who hasn't thought it through for a particular object might.  

I think enabling the addition of multiple relations in a single UI click by a depositor isn't solving an actual problem. Allowing a 1 click addition of 3 relations between Object A and Object B would be allowing a depositor to think they are confused by the terms and giving them a quick out from their confusion. And it adds pure noise on the resulting network graph. 

Instead, defining what Dataverse thinks the relationTypes it supplies mean and giving examples of how to use them would be a better solution to the problem of depositor confusion.

**Comment by jggautier** [comment]
Thanks @augustfly. Looks like the [Scholix metadata schema (page 8-9)](http://doi.org/10.5281/zenodo.1120265) also limits the relationship types (IsReferencedBy, References, IsSupplementTo, IsSupplementedBy) and adds a catch-all (IsRelatedTo).

> I think enabling the addition of multiple relations in a single UI click by a depositor isn't solving an actual problem. Allowing a 1 click addition of 3 relations between Object A and Object B would be allowing a depositor to think they are confused by the terms and giving them a quick out from their confusion. And it adds pure noise on the resulting network graph.

Ah, I didn't mean to suggest enabling the addition of multiple relations in a single UI click (writing "considering the overlap in terms" does make it seem like this is what I was getting at). I meant that as a depositor, I might want to say that dataset A is related to article B in two or more distinct ways (ex. the dataset supports findings in my article, and I also cite the dataset in my article). This is what the Illinois Data Bank folks decided to do:

pg. 214 ([PDF](https://www.ideals.illinois.edu/bitstream/handle/2142/95785/Curating%20Research%20Data_v2_Case%20Study_Pre-Metadata%20Counseling.pdf?sequence=3&isAllowed=y))
> Use two instances of <RelatedIdentifier> for the same identifier when the data set whose conclusions support the paper is also formally cited in the paper.

Is including these two, or multiple relationship types, in the metadata important enough for these knowledge graphs?

I agree that defining what Dataverse thinks the relationTypes it supplies mean and giving depositors examples of how to use them is a great way to go about it.

Lastly, I've been working on mapping Dataverse metadata to DataCite 4.1 so that OAI-PMH harvesting can be done using DataCite (#4318). If we want relatedPublication metadata to be included in the DataCite xml, the DataCite schema requires relationType. Since this isn't something Dataverse requires, I'm wondering if, until depositors are able to choose a required relationType(s) in the UI, it's okay to make one relationType default. @juancoor, is this what https://edatos.consorciomadrono.es/ does, using isCitedBy for every related publication?

If it's safe to choose a default now for related publications that weren't assigned relationship types when published, is it safe to make that relationship type the default choice in an adjusted dataset create/edit form?

**Comment by RightInTwo** [comment]
I would love to see this, as our primary publication target is DataCite-based and mints new DOIs for new versions of publications. Without the relationType IsNewVersionOf/IsPreviousVersionOf, I can't think of a way to accurately describe this.

All the best
Jonas

**Comment by jggautier** [comment]
Thanks @RightInTwo! When you write "publications", I'm assuming you mean published datasets. (Let me know if that's inaccurate :) So it will be helpful if depositors are able to say that the dataset they're depositing IsNewVersionOf/IsPreviousVersionOf another dataset. This also makes me realize that not all of the relationships, however many we choose, will be appropriate options for describing the relationship between two research objects. For example, there's no reason to give dataset depositors the option of saying that the dataset they're depositing IsNewVersionOf an article they've published.

This work is being considered as part of Dataverse's current grant-funded commitment to publish data use and citation metrics following the [Code of Practice for Research Data Usage standard](https://doi.org/10.7287/peerj.preprints.26505v1) (Make Data Count), since the [Event Data service](https://support.datacite.org/docs/eventdata-guide) that's aggregating the metadata in order to generate citation counts needs the "relatedIdentifier" metadata, which Dataverse needs to send to DataCite when registering DOIs (or updating the metadata of already registered DOIs, https://github.com/IQSS/dataverse/issues/5144).

Could we update the dataset metadata form to let depositors say how the research object is related to the dataset they're depositing, maybe using a new metadata field? That would mean a fifth field, maybe a dropdown menu, in the "Related Publication" compound field, and a second field for "Related Datasets" (which would become a compound field).

Of the six relations that the [Illinois Data Bank settled on](http://journal.code4lib.org/articles/11980), I'm proposing using:

For "Related Publication":
- IsSupplementTo
- IsCitedBy

For "Related Dataset":
- IsSupplementTo
- IsCitedBy
- IsNewVersionOf
- IsPreviousVersionOf
- IsPartOf
- HasPart

(I'm not recommending that Dataverse display those phrases in the UI. Zenodo tries to clarify with longer phrases:

<img width="1098" alt="screen shot 2018-11-30 at 6 26 52 pm" src="https://user-images.githubusercontent.com/18374574/49321364-eeb6c680-f4d4-11e8-9cb8-5fa0b851bfcd.png">

**Comment by pameyer** [comment]
@jggautier Any thoughts on `IsSourceOf` for "Related Dataset"?  

I'm a little confused about how a dataset would cite another dataset, but that's likely because I haven't looked at the spec for a while.

**Comment by RightInTwo** [comment]
@jggautier yes, i am talking about published datasets

In regards to the relation types, Datacite defines a whole bunch of them:


- IsCitedBy
- Cites
- IsSupplementTo
- IsSupplementedBy
- IsContinuedBy
- Continues
- IsDescribedBy
- Describes
- HasMetadata
- IsMetadataFor
- HasVersion
- IsVersionOf
- IsNewVersionOf
- IsPreviousVersionOf
- IsPartOf
- HasPart
- IsReferencedBy
- References
- IsDocumentedBy
- Documents
- IsCompiledBy
- Compiles
- IsVariantFormOf
- IsOriginalFormOf
- IsIdenticalTo
- IsReviewedBy
- Reviews
- IsDerivedFrom
- IsSourceOf
- IsRequiredBy
- Requires

They are described in the appendix of [the version 4.1 specification](https://schema.datacite.org/meta/kernel-4.1/doc/DataCite-MetadataKernel_v4.1.pdf).

**Comment by jggautier** [comment]
Thanks @RightInTwo. I mentioned 25 in an earlier comment; didn't realize so many more had been added since version 3.1!

I hadn't considered the whole list yet, just wanted to get the conversation started (but I agree isCitedBy doesn't make sense to me right now). Maybe we could get more feedback from depositors and curators of different types of datasets.

IsSourceOf makes me think of one dataset being derived from another. "Here's a dataset that was used to create this one, but it's not a new version or a part of that first dataset."

**Comment by pameyer** [comment]
@jggautier That's the exact usage of `IsSourceOf` that I was thinking of - it seems to me like a better framework than mixing inputs and outputs in the same dataset.

**Comment by RightInTwo** [comment]
@jggautier what would happen in the case that i import metadata from another source that actually uses IsSourceOf (for whatever reason) and it's not implemented in dataverse?

**Comment by jggautier** [comment]
One idea would be to map the types we don't use to the types we do. Would probably be helpful to consider the types different repositories use now. And later if changes are asked for by people importing metadata with the types that Dataverse doesn't use, we can reconsider adding/changing types.

**Comment by RightInTwo** [comment]
@jggautier so the import would fail in that case? as long as it does not just ignore that field or silently fail, that sounds good

**Comment by RightInTwo** [comment]
Could you support all types defined in Datacite and just display a subset in the UI? Wouldn't that be less hassle?

**Comment by adam3smith** [comment]
I've been pestering @mfenner about this for years now and we're very eager to see this happen. Here's what he wrote to my request to clarify relation types back in 2016:

> Sebastian,
> 
> the "Is supplement to" relation type seems to be the most widely used when describing datasets associated with an article. 
> 
> The second most common relation type between Crossref and DataCite DOIs is "Is referenced by", which in my mind is a very generic one. It could be used when the dataset generated as "Is supplement to" is later reused by another publication.
> 
> "Is cited by" is very similar, but some people like to limit the latter to citations by scholarly articles and appearing in the reference list.
> 
> "Is supplement to" and "Is referenced by" together probably cover the two most common scenarios linking articles and data. And as you say, it is important to distinguish between the two. Some of the other relation types are used to describe relations between data (e.g. "Is new version of", "Is part of").
> 
> I would be happy with fewer relation types, that would then make it easier for everyone to use them consistently.
> 

Given this, I 
a) agree that the Dataverse GUI should be expose a limited subset of relation types but
b) would argue for the more widely used and broader `isReferencedBy` over `isCitedBy`

**Comment by mfenner** [comment]
@adam3smith you can see the actual numbers of relation types used in DataCite metadata in our Event Data service, e.g. the 1.1 million relations from DataCite DOI to Crossref DOI: https://api.datacite.org/events?page[size]=0&source-id=datacite-crossref

You can see that `IsDocumentedBy` is the third highly used relation type, and is what ICPSR uses by default.

I am getting increasingly less convinced that the inverse relationships (e.g. IsReferencedBy vs. references) rather create confusion than provide value. Backlinks are complicated topic already for web links, and I am not sure what the value is of using for example `IsReferencedBy`.

I would second the idea of simplifying the relation types made available in the UI.

**Comment by adam3smith** [comment]
> You can see that IsDocumentedBy is the third highly used relation type, and is what ICPSR uses by default.

With all respect to ICPSR, I think `isDocumentedBy` is terrible choice for how they use it. You end up with obviously absurd statements like this GSS wave https://search.datacite.org/works/10.3886/icpsr07527.v1 being documented by this Science article (which just happens to reference it): doi.org/10.1126/science.2740913 

> I am getting increasingly less convinced that the inverse relationships (e.g. IsReferencedBy vs. references) rather create confusion than provide value. Backlinks are complicated topic already for web links, and I am not sure what the value is of using for example IsReferencedBy

So are you saying as data repositories we shouldn't try to link datasets to publications at all and just rely on publishers to get that right, or am I misunderstanding you? That'd seem risky to me both because I'm not convinced publishers are as diligent about this as we'd want them to and because we're capturing this information in our metadata and so we should as well display it, no?

**Comment by mfenner** [comment]
Regarding "IsDocumentedBy`, this is mainly about what is just most often, not whether I would do the same.

Regarding directionality of relation types: of course data repositories should link to the scholarly literature. But I would be careful with the semantic meaning you put into the relation type, and make sure it is not confusing to users.

**Comment by adam3smith** [comment]
> Regarding directionality of relation types: of course data repositories should link to the scholarly literature. But I would be careful with the semantic meaning you put into the relation type, and make sure it is not confusing to users.

ah I get it -- you're saying that people are likely using `references` where `isReferencedBy` would be more appropriate, etc. That makes a lot of sense.

FWIW, I like the way Zenodo attempts to clarify the directionality, 
![image](https://user-images.githubusercontent.com/128986/49957697-9de09e00-fed6-11e8-9d21-4a702edb500a.png)

but I doubt there's any way to get end users to get this right other than to simply remove one direction (e.g. just allow `isReferencedBy` and `isSupplementTo`, but not their reverses, for the related publication field), which may not be a bad idea for Dataverse and I think what Julian is proposing above.

**Comment by jggautier** [comment]
I changed the title to refocus this issue to just working on relation types between datasets and related publications. (More work would need to be done so that Dataverse could send DataCite metadata about how one dataset is related to another research object, like another dataset.)

Comments from @adam3smith, @mfenner, and @RightInTwo have been incredibly helpful for considering how best to narrow the list of relation types so that depositors can use them confidently and consistently.

We plan to summarize the conversation, get answers to a few more questions (see below), and test and propose something that tries to satisfy the different use cases of the repositories using Dataverse (like QDR and Repositorio de Datos del Consorcio Madroño, the two already doing this in some way).

- DataCite uses related publication metadata in order to help generate citation counts as part of the Make Data Count work. What relation types, if any, does DataCite Hub care about?
- ...

**Comment by doigl** [comment]
We would like to use the relation to other datasets to link the (datasets of the) individual steps in the creation process of a data record and therefore record the provenance.

**Comment by jggautier** [comment]
Hi @doigl. For now, I created a new GitHub issue about letting a depositor indicate how other datasets are related to the one she's depositing: https://github.com/IQSS/dataverse/issues/5998.

**Comment by jggautier** [comment]
@djbrooke, @scolapasta and I discussed how some Dataverse admins will want to use different relationTypes, some will want to use only one or a few and some will want to use many, so it would be best if Dataverse admins are able to choose how their depositors define the relationships between their datasets and other research objects, in this case "publications," and how admins could control how those relationships map to DataCite's relationTypes.

As of 14.5.1 the only way to customize the metadata in "out of the box" metadata blocks like the citation metadata block, and control how Dataverse metadata is mapped to other metadata standards, is to fork Dataverse. So first the community needs to figure out how Dataverse admins can customize their metadata without forking Dataverse, which is part of what https://github.com/IQSS/dataverse/issues/6030 is about.

In the meantime, I plan to share a proposal that I'm hoping that the Dataverse community can agree on about which of DataCite's relationTypes make the most sense to use when describing the relationship between datasets and publications, and how to define each of those terms, recognizing that some Dataverse repositories will want to support only one or a few terms and some will want to use many.

**Comment by jggautier** [comment]
I'm wondering if we could agree on how Dataverse would be configured "out of the box" to let depositors define the relationship between their dataset and "related publication". For everyone who's interested, please feel free to leave comments on [this proposal](https://docs.google.com/document/d/1hc3Pa9fNJdEecKzxi1QkwCZLdciQjxv45eYZCvBKmeE).

**Comment by marcomarsella** [comment]
I went through the thread and it seems to me that an important dimension is missing in the discussion. Beside the relationships of the dataset to other datasets and publications, we need to model the relationship(s) of the dataset to the original samples, materials or other entities whose properties are measured in the dataset.

In our use case, for example, we assign DOIs to Plant Genetic Resources (PGRs). When our stakeholders deposit a dataset on Dataverse, it would be critical to be able to say "this dataset references these PGRs" by listing the corresponding DOIs. The relational operator to be used should be, IMHO, "References" that seems the most appropriate.

Please keep in mind that a single dataset might reference dozens or hundreds of PGR DOIs as it is common practice to run the same experiment on a group of samples. Therefore, adding a single referenced DOI at a time would not be practical. A text area or a file upload function would be much more appropriate whereby the depositor can upload or paste a text file with the referenced DOIs, say, each on a separate line or any other simple format.

I think it would be very good if Dataverse would consider this aspect and push it up on the implementation priorities list...

**Comment by janetm** [comment]
Hi All
I've only just skimmed through the thread.  Is this still under discussion?
thanks
Janet

**Comment by marcomarsella** [comment]
I hope Dataverse would reconsider their priorities and push this up the list. In my opinion it is an important issue to address.

**Comment by mfenner** [comment]
I second that.

**Comment by LauraHuisintveld** [comment]
Hello all, 
I also received a request from users of our Dataverse installation (DataverseNL) to send more data to Datacite when a DOI is registered. Especially the related publication information. Is there any development going on for this issue at the moment? 
I also saw a related, newer issue  [https://github.com/IQSS/dataverse/issues/7072](url), created by @philippconzett. Maybe you have an update about this?

**Comment by eugene-barsky** [comment]
Do we have any updates on this issue? Here is what Datacite recommends us to do - https://support.datacite.org/docs/contributing-citations-and-references

**Comment by jggautier** [comment]
Hey @eugene-barsky. Thanks for pointing that page out!

There's more recent discussion about this issue in the broader GitHub issue at https://github.com/IQSS/dataverse/issues/8108, where @KellyStathis from DataCite offered advice about using relationTypes and pointed to https://support.datacite.org/docs/connecting-to-works, which now eventually leads to https://support.datacite.org/docs/contributing-citations-and-references

Folks at Harvard that are part of the [NIH's Generalist Repository Ecosystem Initiative (GREI)](https://datascience.nih.gov/news/nih-office-of-data-science-strategy-announces-new-initiative-to-improve-data-access) need this issue resolved, too. @KellyStathis, in email discussions in July with Harvard members of the GREI group, also pointed out https://support.datacite.org/docs/contributing-citations-and-references and made some general recommendations. And in meetings coming up this month, the GREI groups will be joined by one or more folks from DataCite who will be able to help with metadata questions like this one.

But I think no decision has been made and implemented because even the incredibly helpful guide at https://support.datacite.org/docs/contributing-citations-and-references leaves enough room for debate and the community hasn't found the time to build consensus.

I've been imagining that as the GREI work continues, the Harvard folks in the working groups, including me, can learn from more of the Dataverse community (something @qqmyers also [recommended in a related pull request](https://github.com/IQSS/dataverse/pull/8357#issuecomment-1092805294)), and what we learn can inform the GREI work (and perhaps DataCite's recommendations).

@amberleahey and @philippconzett asked in [a Google Groups thread](https://groups.google.com/g/dataverse-community/c/gbRz1VseiFw/m/YayS3ac2BgAJ) last week if a Dataverse Metadata WG/IG meeting could be scheduled to discuss this. I'll also ping @mreekie, who is catching up on this and other related issues.

**Comment by eugene-barsky** [comment]
Thanks so much, Julian. I will also be delighted to join the Dataverse
Metadata WG/IG meeting when it meets to discuss this.

E.

**Comment by philippconzett** [comment]
@jggautier Should we schedule a Metadata WG/IG meeting on Thursday October 6? I think we could discuss several related issues:
- relationType (see this GitHub issue)
- resourceType (see [https://github.com/IQSS/dataverse/issues/5086](https://github.com/IQSS/dataverse/issues/5086))
- rightsList (see [https://github.com/IQSS/dataverse/issues/8512](https://github.com/IQSS/dataverse/issues/8512))
+ probably other issues

I'll be out of office in a couple of hours and until Tuesday, but if you and @qqmyers and others are available, I could join you after 1500 CEST. Thanks!

**Comment by marcomarsella** [comment]
I think that would be very useful. I would be happy to join.

M

**Comment by poikilotherm** [comment]
I'd second that idea of having a meeting!

**Comment by jggautier** [comment]
Hey @philippconzett. Sorry for the delay in replying. For a few reasons I've been hesitant to agree that a meeting should be scheduled, but I'd be happy to help promote one for this Thursday, Oct 6. 2pm UTC ([time converter](https://savvytime.com/converter/utc-to-edt/2pm)). I made a Google Doc at https://docs.google.com/document/d/1tNnvVh8jYY1g53BEwpJmMmm9w6Vgy_Q7RrmFjGnYOyA for note taking.

Looks like we need a new Slack link. The one in the calendar invite doesn't work. Was probably Danny Brooke's.

**Comment by eugene-barsky** [comment]
It is too early for me on the Wst Coast and I will rely on @Amber Leahey
***@***.***> to attend :)

E.

**Comment by amberleahey** [comment]
Count me in, let's build some consensus on DataCite mappings and put it to a community vote!

**Comment by philippconzett** [comment]
Thanks, @jggautier! I have posted a message in #ig-metadata on Slack. Are you going to create a Zoom link, or do you want me to do that?

**Comment by jggautier** [comment]
Thanks for posting in Slack. I created a Zoom link and updated the event on the Dataverse Community Calendar.

**Comment by marcomarsella** [comment]
Please forward the Zoom link, just in case I can join…

Thank you!

M

**Comment by jggautier** [comment]
Join Zoom meeting
https://harvard.zoom.us/j/9368020057
Join by telephone (use any number to dial in):
- +1 646 931 3860
- +1 929 436 2866
- +1 301 715 8592
- +1 309 205 3325
- +1 312 626 6799
- +1 564 217 2000
- +1 669 444 9171
- +1 669 900 6833
- +1 719 359 4580
- +1 253 215 8782
- +1 346 248 7799
- +1 386 347 5053

International numbers available: https://harvard.zoom.us/u/a3oPwvAlb
One tap mobile: +16469313860,,9368020057# US
Join by SIP conference room system
Meeting ID: 936 802 0057
9368020057@zoomcrc.com

**Comment by KellyStathis** [comment]
Apologies for the delay weighing in here; I had missed a few notifications and then was out of office last week! 

I've reviewed the notes from the metadata interest group call and support the idea of having a user-selectable relation type, rather than assuming all "Related Publications" are citations of the dataset (for example). A couple thoughts on this:

* I would recommend only including a subset of relationTypes so it isn't overwhelming for users. An example of this is [FRDR](https://www.frdr-dfdr.ca/repo/?locale=en) in Canada, which has [these options (under "Relation types)"](https://www.frdr-dfdr.ca/docs/en/describing_your_data/#recommended-metadata). (Note these definitions/examples haven't been reviewed by DataCite, but they should be compatible.)
* For the UI, the directionality can sometimes be confusing - one approach is to have a sentence, e.g. "This dataset is cited by _____".

On DataCite's side: we're looking at producing better guidance and examples in the near term; this will involve analyzing existing usage and community consultation, and we definitely want to hear from the Dataverse community. Will keep you updated as that work gets underway!

**Comment by pdurbin** [comment]
I just linked to this issue as "under development" in a agenda/notes doc from today's GREI Metrics Sub-Committee Meeting:

<img width="719" alt="Screen Shot 2023-03-31 at 11 07 17 AM" src="https://user-images.githubusercontent.com/21006/229158708-8b35e380-68fa-4471-a57d-bd697df4f0a8.png">

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Comment by pdurbin** [comment]
The original idea in this issue... `Add "Relation Type" to related publication metadata fields to send DataCite related publication metadata` is being addressed by this PR:

- #10632

There's lots of other chatter in this issue that may not be addressed by it. Please feel free to open new issues for the rest! 😅
