### ISSUE TITLE
Privacy Policy - Disappeared from dataverse.harvard.edu

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2781]
There used to be a link in the footer to the privacy policy and it now is not there. According to #1547 there is a script that needs to be run for it to appear. Assigning to @pdurbin to get that done ASAP.

**Comment by pdurbin** [comment]
https://github.com/IQSS/dataverse/blob/v4.2.1/scripts/api/setup-optional-harvard.sh#L10 is where the URL is set. I have no idea why it's gone from production but we can re-run that part of the script.

**Comment by pdurbin** [comment]
@kcondon offered to investigate and fix this so I'm assigning it to QA. This is not a code change but rather a setting that needs to be populated.

Because the setting is in the "optional Harvard" script people who have been installing Dataverse have had a little difficulty finding it: https://groups.google.com/d/msg/dataverse-community/ziGFSMCmEDA/OAMRMTKICQAJ

We **could** move it to the main setup-all script but I don't think we want a new installation of Dataverse to link to Harvard's privacy policy at http://best-practices.dataverse.org/harvard-policies/harvard-privacy-policy.html

**Comment by pdurbin** [comment]
Oh, also, it's unlikely that the setting truly disappeared from the "setting" table (we'd have to go to database backups to confirm this, which would be time consuming) but anything's possible, I guess. It's quicker to just add the setting of course.

**Comment by kcondon** [comment]
OK, policy is in place, closing.
