### ISSUE TITLE
Thumbnails: Image file thumbnails are no longer generated after optimization.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2791]
When I upload a known good image file no thumbnail is generated.

**Comment by mheppler** [comment]
Related #2792

**Comment by landreev** [comment]
OK, so it looks like that may have been a false alarm. Because we have real-time thumbnail generation disabled on both vm4 and vm5. (we disabled it because we didn't want the app to waste any time trying to do so - as we didn't have any files locally on either box).
I'll re-enable it and re-test, and confirm.

**Comment by landreev** [comment]
Please retest this on vm4; thumbnails should now be generated.
Same on vm5. Also, on vm5 I copied the image files from production for the first 10 pages-worth of search results (with or without file search cards) - so you should be seeing thumbnails there as well.

**Comment by kcondon** [comment]
OK, works. Closing.
