### ISSUE TITLE
Files Card: Tabular data tags do not appear on files card in v4.2.2.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2802]
Tabular data tags do not appear on file cards in v4.2.2. but do appear in v4.2.1.

**Comment by landreev** [comment]
Interestingly, we have the total of 200 tabular files with "data tags"; in 16 distinct datasets.
So that's only 16 datasets to reindex; if we were to start indexing these.
Which I am really going to do!

**Comment by landreev** [comment]
("we have ... in production" that is)

**Comment by landreev** [comment]
Tabular data tags are now being indexed and displayed.
The attached screen shot is from dvn-vm5. The data tags are being shown for existing files there because I updated the solr schema on vm7 and reindexed the datasets that had tab files with tags. 
Any other solr instance will need to have the schema updated; and any existing tagged files will need to be reindexed. (this will need to be done in production too; as I said earlier, as of now there are only 16 datasets that need to be reindexed).

![screen shot 2015-12-07 at 7 10 44 pm](https://cloud.githubusercontent.com/assets/737558/11644038/979d0de6-9d16-11e5-9083-1d6dc6f24996.png)

**Comment by kcondon** [comment]
OK, works, closing.
