### ISSUE TITLE
Persistent Identifiers: Update forwarding URLs to reflect current Dataverse production URL

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2809]
For both DOI and Handles the identifier records need to be reviewed holistically and updated to reflect the current production URL so we do not need to rely on rewrite rules indefinitely to resolve them.

**Comment by landreev** [comment]
This was largely done, for both the handles and dois. 
We still have a few handles that are somehow corrupted, so that they can't be re-registered. 
but they are still pointed to the old production , which redirects to the new... so they are working. 
the way to fix them for real, i'm guessing, would be to delete them completely, then create them again.

**Comment by pdurbin** [comment]
@kcondon @landreev can we close this issue? It sounds like a problem with data, not with the code.
