### ISSUE TITLE
Dataset Summary: Related Publication URL should display if no identifier

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2814]
Confirmed with @scolapasta that this is a bug. On the Dataset Summary the URL will not display in the Related Publications if there is no identifier filled in for it. The expected behavior is that the URL should display if there is no identifier.

![image](https://cloud.githubusercontent.com/assets/5013837/11717176/a89d0b3e-9f1c-11e5-980b-0b9a03f6d9f0.png)

**Comment by amberleahey** [comment]
I think users are easily confused by this limitation as they aren't realizing the ID Number is required / confused with URL etc. It would be great to tackle related publication fields to make them more easily accessible for users and for display in the data summary page.

**Comment by jggautier** [comment]
The GitHub issue https://github.com/IQSS/dataverse/issues/5277 is related.

**Comment by pdurbin** [comment]
As of 7e0738e this is fixed in the new React UI. Closing.

## New React UI
![Screenshot 2023-10-08 at 05-17-24 Dataverse](https://github.com/IQSS/dataverse/assets/21006/1f25dfb4-3546-46ae-89ee-6dee665b4504)

## Old JSF UI

![Screenshot 2023-10-08 at 05-17-16 Replication Data for Advancing Computational Reproducibility in the Dataverse Data Repository Platform](https://github.com/IQSS/dataverse/assets/21006/3f1f9ad1-60c5-4a46-bbc5-d665a422ab1d)
