### ISSUE TITLE
Publish Dataset: During service instability, dataset was published, not indexed, doi not made public/

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2828]
This is a real life service issue that points to the need for more defensive coding around publishing a dataset: RT 230496

There were 2 issues:
1. The dataset was published but not reindexed so the dataset card showed draft unpublished when the dataset page itself showed published. Reindexing solved this.
2. The DOI was registered but not made public. This should never happen: when the dataset is published, the DOI should be made public and if not, not. This was fixed by manually making the DOI public from the EZID interface.

**Comment by pdurbin** [comment]
I explained my theory to @kcondon that perhaps something went wrong in the ~30 lines of code that get executed in the PublishDatasetCommand **after** the call to reindex the dataset. Since this issue happened in 4.2.2 I'll link to that version below.

My question to @sekmiller and @scolapasta is if there is any problem with me moving the call to "indexDataset" to the very bottom of the "execute" method:

https://github.com/IQSS/dataverse/blob/v4.2.2/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/PublishDatasetCommand.java#L162

Note that currently `ctxt.doiEZId().publicizeIdentifier(savedDataset)` gets called last rather than indexing. I wonder if something failed with the DOI registering? And yet the dataset was still published.... Very strange.

**Comment by kcondon** [comment]
We have greatly improved system stability and have not seen these issues. Closing unless this becomes an issue.
