### ISSUE TITLE
Dataverse Category: Add Department

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2829]
During a demo, it was mentioned how being able to create a sub dataverse for an institution that was categorized as a department would be really helpful.

@posixeleni could you add Department as an option to the Dataverse Category dropdown? 

If possible, @scolapasta, could this be added in for the first release of the new year? Thanks!

**Comment by posixeleni** [comment]
Hi Elizabeth,

Unfortunately, this is not something I have edit abilities to do since it
is at the Dataverse-level rather than the dataset metadata level. So it
needs to be edited in the code rather than in the metadata tsv's.

Cheers
Eleni

Eleni Castro
Research Coordinator, IQSS
Harvard University

**Comment by pdurbin** [comment]
Yeah, it's an enum in "Dataverse.java":

```
    public enum DataverseType {
        RESEARCHERS, RESEARCH_PROJECTS, JOURNALS, ORGANIZATIONS_INSTITUTIONS, TEACHING_COURSES, UNCATEGORIZED
    };
```

**Comment by pdurbin** [comment]
@bmckinney is in this part of the code in pull request #3070.

**Comment by pdurbin** [comment]
Related: #3681.

**Comment by rbhatta99** [comment]
I just made pull request #3983 and moved it to code review

**Comment by rbhatta99** [comment]
@jggautier i put department right above uncategorized in categories. Is that fine? Or should i put it in a different order?

**Comment by jggautier** [comment]
Thanks @rbhatta99! I thought about this since we talked earlier today. They're probably in the order that they were added (except for keeping "uncategorized" last).

I think they should be ordered alphabetically.

(If changing the order of everything else in the list doesn't seem worth the amount of work it would take, my thinking is that "Department" should go after "Organization or Institution", before "teaching category", since "teaching category" is and will probably remain the least used, and department is related to "Organization or Institution". Of course, then I'm imposing my own understanding of these categories to how they're ordered, and my understanding isn't always how they're used, which is why alphabetically seems like the better option.)

**Comment by pdurbin** [comment]
@rbhatta99 while you're in this part of the code I thought you might be interested to know that we expose the "dataverses by category" data at https://services.dataverse.harvard.edu/miniverse/metrics/basic-viz/last12-dataverse-org?iframe=true

Here's the code which I don't believe needs any modification, but you are welcome to take a look: https://github.com/IQSS/miniverse/blob/0.3/dv_apps/metrics/stats_util_dataverses.py#L218

Here's what the graph looks like, also displayed at https://dataverse.org/metrics (but it should probably be https://metrics.dataverse.harvard.edu or something:

![screen shot 2017-07-06 at 2 31 19 pm](https://user-images.githubusercontent.com/21006/27927048-753cfad2-6258-11e7-8ca0-02092af8b026.png)

**Comment by rbhatta99** [comment]
Sure! il take a look!
