### ISSUE TITLE
Move Dataverse: Moving dataverse appears to leave children behind but has just misplaced them.

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#283]
---

Author Name: **Kevin Condon** (@kcondon)
Original Redmine Issue: 3697, https://redmine.hmdc.harvard.edu/issues/3697
Original Date: 2014-03-12
Original Assignee: Philip Durbin

---

Tested on 3/12

I moved a Dataverse, Friday 1:33pm, which has a dataset, I Like Pizza. However, once moved, the landing page showed an empty dv and browsing to the dv yields no results.

Searching on Pizza shows dataset which still thinks it belongs to that dv (it does). So I think this is a case where the dv is not reindexed on moving and so the search and browse is confusing.

**Comment by pdurbin** [comment]
I think this ticket was assigned to me because re-indexing must happen when dataverses or datasets are moved but the [Implications of moving dataverses and datasets](https://docs.google.com/document/d/1W8AXMtFJ32XCILCe1PX2BTIER6hxGiOLZMLhbFPQe7A/edit?usp=sharing) Google doc is the place for noting other areas of the system (permissions, metadata blocks, groups, etc.) that are affected by dataverse and dataset moves.

**Comment by scolapasta** [comment]
Closing this issue as we currently don't have move. The issue of reindeing all child objects is covered in issue #2278.
