### ISSUE TITLE
Edit Files: No Batch Tag Button on Edit Files Metadata Page

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2842]
According to the mockups for Files, there should be an Edit Tags button at the top of the Edit Files Metadata page like there is for restrict and delete.

Carrying this over from #2511 so #2511 can be passed to QA to close.

**Comment by shlake** [comment]
Want to give a plug for "fixing" this.

Use case - since there is now a way to filter tags on a dataset page, tagging files is more useful. I can see a use where a researchers wants to upload files in groups - where each group gets a specific tag.

Currently, only groups of files can bet tagged AFTER they have been saved to a dataset. There is no batch tag button on upload, see screen shot below:

![Screen Shot 2020-01-14 at 3 23 53 PM](https://user-images.githubusercontent.com/3809325/72460723-58f2ff00-379b-11ea-91b3-b955ac2e2db6.png)

**Comment by valentinapasquale** [comment]
Hi, I also think this could be a very useful feature! I have more or less the same use-case as Sherry.

**Comment by scolapasta** [comment]
closing until we determine design from #7376
