### ISSUE TITLE
4.2. to 4.2.1 upgrade instructions appear incorrect

### ISSUE THREAD

**Issue by ajirnyi** [IQSS/dataverse#2854]
Hi -- the upgrade instructions at https://github.com/IQSS/dataverse/releases/tag/v4.2.1 seem to have a couple problems:

-  the undeploy instruction says "undeploy the current application /glassfish4/bin/asadmin list-applications /glassfish4/bin/asamin undeploy dataverse-4.1" -- I assume this should read "4.2" rather than "4.1"?
- run the upgrade psql script provided: upgrade_v4.1_to_v4.2.sql restart glassfish: this also looks copied from the previous one, as there is no script provided for upgrade to 4.2.1

Also, is it possible to skip the upgrade to 4.2.1 entirely, and go 4.1 -> 4.2 -> 4.2.2?

**Comment by pdurbin** [comment]
Hmm. I think @ajirnyi is on to something. @kcondon can you please take a look? I guess I'll assign this to the milestone under development (4.2.3).

> Also, is it possible to skip the upgrade to 4.2.1 entirely, and go 4.1 -> 4.2 -> 4.2.2?

Generally speaking, no. When upgrading Dataverse versions you have to do all the upgrades in between. It typically comes down to whether there are database schema updates to run or not. Or Solr schema updates to be aware of.

**Comment by ajirnyi** [comment]
Thanks!
BTW, a stupid question: what exactly is the recommended procedure for
running the SQL updates? I have not worked with Postgres before, but it
seems that the default settings prevent password logins from command line.
What I ended up doing (after quite a bit of exploration) was

runuser -l postgres
psql -d dvndb -a --file=/tmp/upgrade_v4.1_to_v4.2.sql


but somehow this doesn't seem like the intended way to me...

--aj

**Comment by kcondon** [comment]
Good catch. Updated instructions. Closing

**Comment by kcondon** [comment]
There are several ways you can run a postgres script:
1. Switch to user postgres, then run psql as you have done, we use su - postgres.
2. Pass user info on psql command line with -U option, I am not always able to get that to work.
3. Log on to db using psql in interactive mode, connect to the db wih \c, then run the script with \i 

There is not a preferred way, just what works for you.

**Comment by ajirnyi** [comment]
Thanks for clarifying this!
A couple more things though:
- "deploy the new war file /glassfish4/bin/asadmin deploy dataverse-4.2.war" -- I guess this should read "4.2.1"?
- There is a schema.xml file in 4.2.1. release downloads; does this mean that an extra step to update schema.xml in Solr, similar to the one listed in the 4.1 -> 4.2 upgrade instructions needs to be performed?

Also:
- Does the schema.xml upgrade step need to be performed at the 4.2 -> 4.2.1 upgrade stage, if it is to be immediately followed by an upgrade to 4.2.2., or can it be skipped?
- Is there any difference between deploying from command line as in instructions, and using autodeploy functionality as the omnibus install script does? And can I do `asadmin deploy dataverse.war ` from any place, such as a home directory of an arbitrary user, or does the .war file need to be copied somewhere?

**Comment by kcondon** [comment]
Thanks, we should probably remove version specific info from the instructions and simply specify whether war file, schema, update script, etc should be part of the upgrade since conceptually the steps are the same. I will check on schema.xml.

**Comment by ajirnyi** [comment]
Thanks! That would make it easier, especially if there was a separate section on how exactly to perform each corresponding step, as some (e.g. the sql script) are not obvious.

What is your recommendation on autodeploy though? e.g. if I have used the omnubus script originally, the asadmin undeploy command leaves the original .war (which was named dataverse.war for version 4.1) in the /autodeploy directory -- what I've been doing was to delete it and replace it with the new .war, since (having no prior experience with glassfish) I wasn't sure if leaving it there and following instructions literally might lead to conflicts of some sort.

**Comment by pdurbin** [comment]
@ajirnyi I very much appreciate your fresh eyes on this. Can you please take a look at the "Dataverse 4 Installation Guide Hierarchy and Reorganization" proposal https://docs.google.com/document/d/1GLky44JbtCNhGuavLXGEP8WPNdjbyHNxalEGjR78MaA/edit?usp=sharing started by @bencomp at https://groups.google.com/forum/#!msg/dataverse-community/qujUFJDYXG0/0BhECCp0HQAJ ?

I feel like many of your suggestions could find a home in that Google Doc for now, as comments at first but if you request write access I'd be happy to give it to you!

**Comment by kcondon** [comment]
@ajirnyi Thanks for pointing out these issues. I'll try to answer your remaining questions but for support questions please open a ticket by sending an email to support@dataverse.org.

Regarding reindexing, you should only need to reindex at the very end of your upgrades, though if you want to confirm each upgrade worked by viewing content, you should probably index at each step and do it as explained in the v4.2.2 instructions.

As for the schema in v4.2.1 and reindexing that version, the schema changes in v4.2.1 were for a custom metadata block that is only used internally here at IQSS. It would not be needed by any other installation so you should not need to do anything for it specifically.

As for using autodeploy as a means of upgrading, autodeploy is intended as a convenience for developers. Since we name our war files with versions, typically, they need to be removed by name -autodeploy will not replace dataverse-4.2.1 with dataverse-4.2.2 but would replace dataverse.war with another dataverse.war. There is a performance cost to having autodeploy enabled.

So, you should first do an asadmin list-applications to see the name of the currently running application, then do an asadmin undeploy myapplication, where my application is the name from list-applications. If you do not remove the currently running application you will have trouble deploying the new one.

I hope this helps.

**Comment by ajirnyi** [comment]
Thanks!

As for deployment, what I mean is that it would be nice if upgrade
instructions (which do not use autodeploy, and have the file named
"dataverse-x.x.x.war") were consistent with the omnibus installation script
(which uses autodeploy, and have the file named "dataverse.war" -- or at
least in version 4.1 it did).

--aj
