### ISSUE TITLE
File Download: Logging reports not recording downloading of unpublished dataset files as a severe error but should be info.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2857]
Download a file from an unpublished dataset and the log prints this:
[2016-01-11T14:48:10.969-0500] [glassfish 4.1] [SEVERE] [] [edu.harvard.iq.dataverse.DatasetPage] [tid: _ThreadID=146 _ThreadName=jk-connector(3)] [timeMillis: 1452541690969] [levelValue: 1000] [[
  No Silent/Default Guestbook response made. No response to save - probably because version is DRAFT - not certain ]]

Since not logging downloads while a draft is expected behavior, it should be at most info if logged at all.

**Comment by bencomp** [comment]
Are you sure this only happens when the downloaded file is from a draft dataset version? The author of this log message apparently wasn't. It it logged [here](https://github.com/IQSS/dataverse/blob/4.3/src/main/java/edu/harvard/iq/dataverse/DatasetPage.java#L2684) (links to 4.3 branch).

The message would be more useful if it reported some context, like the file ID and dataset (version) ID.

**Comment by kcondon** [comment]
Still happens.
Gustavo indicated the issue is really about having better error trapping -probably because version is DRAFT - not certain is not super helpful, why don't we know.
For the case I reported, it should not be logged at all since it is expected behavior. For me it was about cleaning up the log file so additional context like ID, etc is unimportant. However, if there are additional error cases that are not identified, then having additional context may be useful to back check stats, etc.
Still a bug.

**Comment by pdurbin** [comment]
In e8a9116cab0ccaddde378687425e229ec690f2b2 this the block containing this line was moved:

`logger.severe("No Silent/Default Guestbook response made. No response to save - probably because version is DRAFT - not certain ");`
