### ISSUE TITLE
Create Dataset: Delete file on create dataset does not delete.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2862]
This happens in v4.2.2, 4.2.3.
You may ask yourselves who in their right mind would delete a file on creating a dataset?
1. It's possible so it should work.
2. Someone uploading some files but notices one they do not want.
3. Me.

**Comment by pdurbin** [comment]
As I mentioned to @kcondon this morning, I think you get similar problems trying to restrict a file when you're in the initial workflow of creating a dataset.

**Comment by kcondon** [comment]
Restrict works, delete continues not to work.

**Comment by mheppler** [comment]
Tried to replicate this 4 yr old issue on demo (4.20) in order to see if it was resolved, since I was looking at another file delete related issue. Was able to replicate it with the following steps:

- create new dataset, fill out required metadata, add files...
- select one file, and delete it
- if you add that same file again during this create process, it successfully gets added but with the "-1" suffix added to the file name

@kcondon if I have misrepresented this issue, let me know and I can retest and revise my comment.

<img width="1169" alt="Screen Shot 2020-05-20 at 1 17 10 PM" src="https://user-images.githubusercontent.com/687227/82476658-677c5a80-9a9c-11ea-8c93-54763c22e2b5.png">

<img width="1162" alt="Screen Shot 2020-05-20 at 1 17 41 PM" src="https://user-images.githubusercontent.com/687227/82476669-6ba87800-9a9c-11ea-8d23-fde3bf210727.png">

<img width="1160" alt="Screen Shot 2020-05-20 at 1 18 20 PM" src="https://user-images.githubusercontent.com/687227/82476685-706d2c00-9a9c-11ea-9634-dcc40badbb44.png">

**Comment by kcondon** [comment]
@mheppler I would say my original issue was resolved but you have found a different one. I would have provided additional steps if it was in any way tricky.

**Comment by mheppler** [comment]
OK. Going to close this issue. Will continue to look into how the system renames files and handles deleted files in other design and development efforts. If any issues are discovered, new issues can be created to report them.
