### ISSUE TITLE
Guides - Developers vs. Developers'

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#2864]
The use of Developers vs. Developers' for the guides is inconsistent across the application.

Since "User" and "Installation" are singular, I suggest we put this debate to rest once and for all by changing all instances and references of the guide that is to be used by a developer to the "Developer Guide".

**Comment by pdurbin** [comment]
:+1: good idea, @mheppler 

I'm on board with changing it to "Developer Guide" (singular). The only place we won't change is the URL which will still have "developers" ( http://guides.dataverse.org/en/latest/developers ) but that's fine.

**Comment by pdurbin** [comment]
I just merged the fix into the 4.2.3 branch (will set the milestone to this) in 6fe7c3a since this looks fine on my laptop (Developer Guide "singular"):

![screen shot 2016-01-14 at 4 25 06 pm](https://cloud.githubusercontent.com/assets/21006/12338099/e7cb9e4e-badb-11e5-995a-9ec9746dc891.png)

Passing to QA. @mheppler if you have any particular testing instructions, please comment.

**Comment by kcondon** [comment]
Closing
