### ISSUE TITLE
Request Access: User Should Get Pop Up with Terms of Use + Terms of Access when clicking Request Access button

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2872]
In the original FRD for all things files: https://docs.google.com/document/d/1v-6WuFyClnAAHqyMf1VsWtCdXDTTR-ikuG6Ou8RtDMM/edit?usp=sharing, there is a requirement that was never implemented:

Clicking Request Access button pulls up terms of access and terms of use

This is needs to be added in where the Request Access button would be there, and when a user clicks on it, a pop up with the Terms of Use and Terms of Access would appear for them to learn what they need to do to gain access to the file(s).

**Comment by sbarbosadataverse** [comment]
@eaquigley @mheppler 
FYI HBS complained about this again today, because the have the contact person and email listed in the Terms of use, but "request access" is of course not functioning as described above. There is no good or acceptable work around at the moment. I'm going to add to my github review list to prioritize. Any reason we shouldn't? How long would this take to develop? I see no milestone has been added at all but this was part of original FRD?
feedback appreciated.

**Comment by djbrooke** [comment]
Removing from 4.5. Will be re-prioritized for a future release.

**Comment by pdurbin** [comment]
Heads up to @sbarbosadataverse and anyone else following this issue that I'm closing it in favor of #3997.

**Comment by mheppler** [comment]
Here is the mockup to the [Request Access popup](https://iqssharvard.mybalsamiq.com/projects/filesallthings-enduser-dataverse42andbeyond/Dataset%20-%20Files%20-%20Guestbook), with Terms of Access displayed.

![dataset - files - guestbook](https://user-images.githubusercontent.com/687227/28937947-7ea7a0d2-785a-11e7-96a6-722e5cfe44d0.jpeg)

**Comment by sekmiller** [comment]
I don't think that we want to include the guestbook in the popup. At least in the context of this issue.  There should be another issue where the user can be required to fill out a questionnaire when requesting access to a file. If we want to include the questionnaire for request access on this ticket, then it's way more than a "3".

**Comment by stevenmce** [comment]
Hi folks, we have worked on this for our own purposes here at Aust. Data Archive, that has done some of the work described here - @mdmada developed the code for this. We are planning to show what we have done at an upcoming community meeting soon - per discussions with @djbrooke and @scolapasta

**Comment by djbrooke** [comment]
Good morning @stevenmce !

@sekmiller - this will show terms only for now.

**Comment by mheppler** [comment]
Here is a mocked up screenshot of what the missing Request Access w/ Terms of Access popup should look like. The [datasets used to create this mockup](https://dvn-build.hmdc.harvard.edu/dataverse/guestbook) were set up on dvn-build.

![request-access-terms](https://user-images.githubusercontent.com/687227/29078983-ea9a44ac-7c29-11e7-9e49-3340cb9a3600.png)

**Comment by sekmiller** [comment]
The Request Access Popup is shared by the Dataset Page and the File Page so I put the guts into file-request-access-popup-fragment.xhtml and used a ui:include. If it is decided that we need to add the additional TOU/Access, they would go here. Also there is a new boolean on FileUtil for isRequestAccessPopupRequired. It will be true if the TOU are not CC0 and/or there are custom Terms of Access.

There are "double" request access buttons on the FileFragment and file-download-button-fragment which render only one depending on the value of isRequestAccessPopupRequired.

The popup is in place on the Dataset Page for single and multiple file requests and on the file page. One known issue is that on the Dataset Page the Request Access buttons are not refreshing to "disabled" on a successful request. Manually refreshing the page returns the buttons to their proper state.

**Comment by matthew-a-dunlap** [comment]
Also worth noting that my commit for "fixing" the notifications may have made them worse.

**Comment by sekmiller** [comment]
The request access popup will appear when the dataset version has Terms of Use other than CC0 and/or Terms of Access set. The popup will display the custom Terms of Use/Access for the dataset. (There is no support for guestbook/custom questions in this ticket) On the popup the user may click "Accept" to continue with the request or "Cancel" and the Request will not happen. If the user clicks the "Request Access" button above the files list then any files that have been selected (via the checkboxes in the file list) will have a Request Access submitted for them. If none of the files have been selected, the user will get a "Hey Dummy, Select some files" popup. If the user is not logged in he/she will get a "please log in before requesting access" popup.

**Comment by kcondon** [comment]
I have 2 observations/ questions:
1. Terms of use are presented every time a file is downloaded. I thought this used to be once per session per dataset. Did this change? Intentionally?
2. TOA appears twice when downloading the same restricted file, 1ce when requesting access, another when downloading file after being granted access. Feels like overkill and see #1.

**Comment by sekmiller** [comment]
Responses:

1. That was 3.x behavior. It has not been rebuilt for 4.x. There is probably a ticket for it in the backlog.

2. It was decided to do it like this, but I could be persuaded to change it. Note that it would take a bit of infrastructure to keep track of who had seen the TOA via request access since not all downloaders would need to request access.

**Comment by jggautier** [comment]
Are the instructions still "Please confirm and/or complete the information needed below in order to request access to files in this dataset"?

If so, is the part about completing "the information needed below..." part referring to the guestbook (which doesn't appear when requesting access but does appear when downloading the file if there's a guestbook)? Is it appropriate to include that part of the instructions on file request when there is no guestbook?
