### ISSUE TITLE
Deaccession: forwarding URLs with ? don't seem to work

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#2881]
I attempted to deaccession a dataset with a forwarding URL like:

https://dataverse.harvard.edu/dataset.xhtml?persistentId=XXXXXX

and it gave a validation error for the forwarding URL.

Switching to a URL with out the "?" worked.

**Comment by scolapasta** [comment]
@bradleycaccivio you should be allowed to do a ?, of course. Let me know if you need any guidance on how to fix this.

**Comment by bradleycaccivio** [comment]
@scolapasta @mheppler Right now the forwarding URL, along with the reason for deaccessioning and deaccession text, is being validated by javascript on the dataset.xhtml page. I want the validation for all of these fields to occur on the DatasetPage.java page via bean validation. I think the way to go about this would be to use @Range for the deacession reason, since making a selection from the dropdown menu returns an integer value, @Length for the deaccession reason to limit the input to 1000 characters, and @URL for the forwarding URL. I can then assign a message to display for each validation. I'm having an issue now with getting the beans to validate the fields when I want them to. Mike saw that, with the way I have the @Range annotation written now, the reason is being validated before the user even tries to deaccession the dataset. This is because the default value is 0, but the acceptable range is 1-7, so I'm wondering if there is either another way to validate this field or if there is a way to only run the validation when the user tries to deaccession. I have been able to get the validation to work; right now if you try to deaccession when any of the fields are incorrect the page will reload and the banner appears at the top of the page saying there was a validation error. Then, when the user reopens the deaccessioning popup the messages saying exactly what is wrong are under each field; however, if the deaccession text exceeds 1000 characters only that message pops up even if there are problems with the other fields. The messages for the URL validation and reason will display together. I think this is fine, unless you think it would be better if when the page reloads the popup stays open. Also my render logic is having issues. I've attached pictures of what I'm seeing on my local host.
![screen shot 2016-08-30 at 12 20 51 pm](https://cloud.githubusercontent.com/assets/20206696/18097622/8f398f36-6eac-11e6-82b6-a14cde9526a3.png)
![screen shot 2016-08-30 at 12 21 48 pm](https://cloud.githubusercontent.com/assets/20206696/18097625/97496cdc-6eac-11e6-9d21-8e32fd1fbaef.png)
![screen shot 2016-08-30 at 12 22 19 pm](https://cloud.githubusercontent.com/assets/20206696/18097631/9fbbd9c2-6eac-11e6-85b4-defada0ece9d.png)
![screen shot 2016-08-30 at 12 22 47 pm](https://cloud.githubusercontent.com/assets/20206696/18097633/a2cba570-6eac-11e6-92fd-878901a43724.png)

**Comment by bradleycaccivio** [comment]
@scolapasta @mheppler I forgot to mention that I have the deaccession button opening the confirmation popup, and then if you select yes the page will reload to what I show in the screenshots.

**Comment by djbrooke** [comment]
@bradleycaccivio and @scolapasta - I'm going to move this to the "backlog" column  if there's not active development on it at this time.  Feel free to move it to the correct column on https://waffle.io/IQSS/dataverse if this is not correct.

**Comment by pdurbin** [comment]
@djbrooke and I discussed this issue this morning. Sounds like this isn't low hanging so we'll unassign @bradleycaccivio and put him to work elsewhere. 😄

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
