### ISSUE TITLE
cannot enable access request for individual restricted files

### ISSUE THREAD

**Issue by eijoac** [IQSS/dataverse#2902]
cannot enable access request for individual restricted files even though I only select one of the restricted files to apply "Edit Files - Restrict" (all restricted files will have access request enabled). Is this an expected behavior? If so, i should not be allowed to select individual restricted files and to apply "Edit Files - Restrict" button.

also related, once having Terms of Access for restricted files, even downloading unrestricted files need to accept Terms of Access. Is this an expected behavior?

**Comment by pdurbin** [comment]
@eijoac thanks for the suggestion!

**Comment by PaulBoon** [comment]
This is a usability issue; users expect to be able to set the 'access request' on each file separately. Also, besides the green lock icon on the files, there is no indication of the setting when you are the owner of the dataset.  

We get feedback from our customers about this, so we would really like to have this fixed in the next version.

**Comment by pdurbin** [comment]
@PaulBoon thanks for commenting. It helps us understand which of the hundreds of open issues the community wants us to focus on! 😄 

I haven't played with this feature in a while but is it possible to enable "access request" on an individual file from the file landing page?

Also, to give you some insight into our process, the next release is expected to be 4.8 but as we said on the community call on Tuesday we are strongly considering shipping all the 4.9 features we've been working on with it. So the next release will probably be a big one and this issue hasn't been prioritized. By that I mean it's in the "Inbox" at https://waffle.io/IQSS/dataverse rather than being in the backlog or a sprint. You can find our roadmap at https://dataverse.org/goals-roadmap-and-releases and the notes from that community call at https://groups.google.com/d/msg/dataverse-community/Njy9b-jVJ9Q/Sy4IAY7-BwAJ

**Comment by PaulBoon** [comment]
Unfortunately it doesn't work via the 'file landing page' either. Could investigate the code to get an indication how difficult it would be to fix, but that would take a while since this code is all new to me.

**Comment by pdurbin** [comment]
@PaulBoon I am certainly happy to help you dive into the Dataverse code if you would like to contribute! Recently I posted about how we're try to better track and assist with supporting the community in their development efforts that may not align perfectly with our roadmap and priorities based the timetable for grant deliverables: https://groups.google.com/d/msg/dataverse-community/X2diSWYll0w/ikp1TGcfBgAJ

**Comment by sbarbosadataverse** [comment]
Just checking if this is the same issue I reported to Tania and the
usability group, just recently.
1-yes, correct, request access will show up for all restricted files.
2-as an admin or curator, when you set the request access feature, you
can't see it next to the file name, until you log off and look at the
dataset from the viewpoint of a user without a role in your dataverse. So
it leaves you guessing if the feature was actually enabled because it
doesn't show up in "edit" mode, or read mode. Hope that makes sense. Hope
it's the same issue.

On Thu, Sep 14, 2017 at 10:15 AM, Philip Durbin <notifications@github.com>
wrote:

> @PaulBoon
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_paulboon&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=9vanJTIWJgYzLCLZtSh-SM0ehFXO0aWpoNZ5braYHwU&s=l9iQd0x9FZg_I6OYYQMs3cNwZwFjO96ZtJ3ANg22AGg&e=>
> I am certainly happy to help you dive into the Dataverse code if you would
> like to contribute! Recently I posted about how we're try to better track
> and assist with supporting the community in their development efforts that
> may not align perfectly with our roadmap and priorities based the timetable
> for grant deliverables: https://groups.google.com/d/
> msg/dataverse-community/X2diSWYll0w/ikp1TGcfBgAJ
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__groups.google.com_d_msg_dataverse-2Dcommunity_X2diSWYll0w_ikp1TGcfBgAJ&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=9vanJTIWJgYzLCLZtSh-SM0ehFXO0aWpoNZ5braYHwU&s=_T8mZaJ5lNL0Mk6zX5XzMXnVVqZHHb4JNvZxjsVCnyA&e=>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2902-23issuecomment-2D329495877&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=9vanJTIWJgYzLCLZtSh-SM0ehFXO0aWpoNZ5braYHwU&s=2_FZWNx6R5Q11HgPx_lTkIV-ts-J8sRveEDN4V3YUbo&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AH79KgF-5FGU7g0hA6twJ2tVoGc0CGn1S6ks5siTUbgaJpZM4HQ0-5Fq&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=9vanJTIWJgYzLCLZtSh-SM0ehFXO0aWpoNZ5braYHwU&s=3TCRzjR3kYqak8q6_j0vWU8y1LFJZYeaBg2atp8NOME&e=>
> .
>



-- 
Sonia Barbosa
Manager of Data Curation, The Dataverse Project
Manager of the Murray Research Archive, IQSS
Data Science
Harvard University

all Harvard Dataverse Repository inquiries should be sent to:
support@dataverse.org

Dataverse 4.0 is now available for use!
http://dataverse.harvard.edu

All test dataverses should be created  in 4.0 Demo!
http://dataverse-demo.iq.harvard.edu/

Join our Dataverse Community!
https://groups.google.com/forum/#!forum/dataverse-community

**Comment by pdurbin** [comment]
I'm pretty sure this issue came up in our design meeting this morning. Right now (4.8.5) enabling the Request Access button is for **all** restricted files. Reviewing this issue reminds me that there's demand for more granularity.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
