### ISSUE TITLE
Create Group: After adding a group for the first time, there is a success message but the welcome page needs to be refreshed to see group added.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2930]
When I first add a group, there is a success message but the page remains on the initial welcome page. Refresh shows the created group. Adding a second group shows group list and success message as expected.

**Comment by mheppler** [comment]
Took a quick look at the `update` attribute on the save button for the Create Group popup on `explictGroup-new-dialog.xhtml`. I was able to easily fix the Mange Groups page's automatic refresh to show the newly created group. I am leaving this ticket open though, because there is an additional bug with the validation error messages not displaying in the popup, but instead display on the page behind it.
![screen shot 2016-02-09 at 5 16 18 pm](https://cloud.githubusercontent.com/assets/687227/12932496/0adc6628-cf51-11e5-8cd2-f9616b0871b4.png)

**Comment by mheppler** [comment]
Other related issues for the Groups workflow: #2240, #2393, #2394, #2408, #2413.

**Comment by pdurbin** [comment]
I noticed this today and I feel like the wording is odd. "Refresh to update your page" makes me feel like we're trying to make users hyper-conscious that this is a web page they are looking at. Something like "Click refresh to see the group" might be better. Here's a screenshot of the current user experience as of 4.8.4:

![screen shot 2017-12-15 at 11 57 53 am](https://user-images.githubusercontent.com/21006/34058626-af91a676-e1a9-11e7-9c56-d1cd7f03545d.png)
