### ISSUE TITLE
Shibboleth: Review Text For Converting an Account/Creating an Account

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2950]
- [ ] Review, and if necessary change, text on Create Account + Terms of Use page to only be Agree to Terms of Use

![screen shot 2016-02-23 at 3 03 58 pm](https://cloud.githubusercontent.com/assets/5922904/13265914/854d452e-da43-11e5-8818-b8305e6ba4bc.png)

- [ ] Review, and if necessary change, text on Welcome, Me, Myself, and I text; Success Message for converting account (what does this mean to the user? rather than what has happened in the back end)

![screen shot 2016-02-23 at 3 41 29 pm](https://cloud.githubusercontent.com/assets/5922904/13266003/f0a7c7ae-da43-11e5-9984-8711e55a39b2.png)

**Comment by eaquigley** [comment]
New text for the two items listed above! Woo!

- Accept Terms and Create Account page:
      - For consistency, it should be Create Account which is what is on the Sign Up page under all the fields. Users are accepting terms by clicking on the checkbox
- Welcome page: 
       - Question: why is email not displayed as it is in the other workflow?
       - Change to be: Your institutional log in matches an email address already being used for a Dataverse account. By entering your current Dataverse password below, your existing Dataverse account can be converted to use your institutional log in. 
       - Change button to be: Convert Account

**Comment by mcrosas** [comment]
@eaquigley agree with the proposed changes.

**Comment by eaquigley** [comment]
@mheppler I'll write up some updated text for the blue info box in the first screenshot and add it to this ticket. missed that my previous go around.

**Comment by mheppler** [comment]
Cleaned up layout of the Shib and Account Information pgs and updated help/info/validation messages.

Here is a detailed breakdown of those changes.

*loginpage, shibb enabled*
- Added "Leaving your institution?..." text with "Dataverse Support" link to shibb login block

*shib*
- Removed "Accept Terms and" from "Create Account" and "Convert Account" action buttons
- Updated "Welcome..." help/info message
- Updated "Account Information" help/info message for create account workflow
- Styled "passwordRejected" validation error message
- Added email to "Welcome..." convert account pg

*dataverseuser, view + edit account information*
- Cleaned up layout by removing unnecessary style classes and ui:fragment components
- Added "Account Information" tab header to bundle

*termsofuse*
- Cleaned up layout by removing unnecessary style class

Passing back to @pdurbin to looking into:

*shib*
- Add empty render logic to Affiliation form-group so that we don't have to display the "Affiliation not provided by institution log in" message

**Comment by pdurbin** [comment]
> Added "Leaving your institution?..." text with "Dataverse Support" link to shibb login block

@mheppler I'm passing this back to you because I deploy the latest (204831d) to https://shibtest.dataverse.org and now it ain't right:

![log_in_-_root_dataverse_-_2016-02-25_14 10 21](https://cloud.githubusercontent.com/assets/21006/13331045/a5f37726-dbc9-11e5-8778-e9fc9c5f3f34.png)

To make that shib login block appear in your dev environment please run this...

    curl -X PUT -d true http://localhost:8080/api/admin/settings/:ShibEnabled

... per http://guides.dataverse.org/en/4.2.4/installation/shibboleth.html#enable-shibboleth (I should add this to http://guides.dataverse.org/en/4.2.4/developers/dev-environment.html#shibboleth .)

**Comment by mheppler** [comment]
Fixed HTML rendering issue with help text in Institution Log In block on Log In pg.

**Comment by pdurbin** [comment]
@mheppler lookin' good. Thanks. I just deployed aa5391a to https://shibtest.dataverse.org

**Comment by pdurbin** [comment]
I've deployed f901d9f to https://shibtest.dataverse.org and now plan to vet all the changes @mheppler mentioned at https://github.com/IQSS/dataverse/issues/2950#issuecomment-188470277 .

**Comment by pdurbin** [comment]
@mheppler I found a little bug where affiliation was not being displayed for Shib users so I fixed this in 66c4777.

> Add empty render logic to Affiliation form-group so that we don't have to display the "Affiliation not provided by institution log in" message

As I mentioned in person, I think we displayed "Affiliation not provided by institution log in" for a reason, that it was a design decision, but I can't find anything backing this up so I removed it in 58ed4f8 . The point of having that text in there is that we are relying on the affiliation coming from the Identity Provider (IdP) but I can understand if users don't care about that. That text is only seen during the create/convert workflow anyway.

I deployed the latest to https://shibtest.dataverse.org if @eaquigley or others want to check out the revised messages this issue is about. I believe we're done code-wise for this issue. I still need to write a summary for QA.

**Comment by pdurbin** [comment]
Passing to QA. Mostly my role in this issue was to make sure no regressions were introduced as text was changed. @eaquigley and @mheppler defined what the text should actually say. The changes are in pull request #3025.

**Comment by kcondon** [comment]
@mheppler @eaquigley Can I close this? Hard for me to validate based on comments.

**Comment by eaquigley** [comment]
@kcondon Looks good to me. Thanks! Closing ticket.
