### ISSUE TITLE
Installer: configure :SystemEmail in the Dataverse settings. 

### ISSUE THREAD

**Issue by Grimaldum** [IQSS/dataverse#2980]
We ran unto a problem with our dataverse : no emails were sent for any actions (reset, publish, etc). We had no logs useful.

After chatting with @pdurbin, we figured out that the problem was that SystemEmail wasn't set. Following the documentation that described the problem (here : http://guides.dataverse.org/en/4.2.4/installation/config.html#systememail), we had to run this command (of course, change the value in quotes by your own):
 curl -X PUT -d "Support <support@example.edu>" http://localhost:8080/api/admin/settings/:SystemEmail

This solved the problem. In order to prevent this kind of problem to other users, we suggest that Dataverse's logs should indicate that SystemEmail wasn't set.

**Comment by pdurbin** [comment]
Right. They had to turn up logging as explained at http://guides.dataverse.org/en/4.2.4/installation/administration.html#glassfish and http://guides.dataverse.org/en/4.2.4/developers/debugging.html to see this error:

"Email will not be sent because the :SystemEmail setting is null"

I suggested to @landreev that perhaps the installer should prompt for this value. I also added a note that we could emphasize the importance of this setting in the Installation Guide at #2944.

See also http://irclog.iq.harvard.edu/dataverse/2016-03-01#i_31901 for more discussion.

**Comment by bickyii** [comment]
I nearly spent a day to figure this out. Should have searched this sooner. 
It will be good idea to set this value in installer. 
Thanks for solution.

**Comment by landreev** [comment]
I'm cleaning up the installer now - will make sure the system email is configured there.

**Comment by landreev** [comment]
OK, the installer is now taking care of the admin email. 
(about to make a pull request for my installer fixes)

**Comment by landreev** [comment]
The installer is now asking for the admin email for the installation. 
The entry is validated for looking-like-a-legit-email-address. But I'm not testing if mail can actually be sent to and from the address - maybe in a next release. 
This is reflected in the Installation guide, under "New in 4.3". But the option is pretty self-explanatory, so I'm not saying much about it.  (I'm going to go ahead and tag it 4.3 - because, why not)

**Comment by landreev** [comment]
No, actually, I'm not going to set the milestone on the installer related tickets; the final decision on this was going to be made next week - right?

**Comment by kcondon** [comment]
OK, installer prompts for and configures system email and support email works afterward. Closing.
