### ISSUE TITLE
Files Tags: Adding a custom tag removes all but one existing tags.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3005]
Tested with FF.
On a draft dataset, edit file metadata, then edit tags. Select all existing category tags, then add a custom tag. When you click apply, all but one category tag appear to be removed. You can reselect all, they appear, but add another custom tag and apply, same thing happens except all custom tags stay and one (first) category tag stays. This is all in the popup before saving.

**Comment by mheppler** [comment]
@kcondon -- passing this back as Cannot Reproduce.

This is the part that I am not seeing.

> Select all existing category tags, then add a custom tag. When you click apply, all but one category tag appear to be removed.

**Comment by mheppler** [comment]
Revised description of the workflow in order to reproduce:

1. Draft version of a dataset with **tabular data files**
2. Select tabular data file, click Edit Files button, select Metadata from dropdown
3. Apply a File Tag(s) by checking one from the dropdown
4. Apply a Custom File Tag by typing it into the input field and clicking "Apply"
5. Notice that the File Tag(s) that were previously applied were removed, and only the Custom File Tag is displayed.

I am passing this to @sekmiller as he wired up that "Apply" button for the Custom File Tag.

**Comment by sekmiller** [comment]
Fixed in the 2391 File Tags Edit Branch

**Comment by kcondon** [comment]
Tested with FF, Chrome, MSEdge, both batch and edit files popups using tabular files. Works, closing.
