### ISSUE TITLE
Contributors to a Dataverse Should Not Be Able to See Other Contributors Unreleased Studies or Restricted Files

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#301]
---

Author Name: **Eleni Castro** (@posixeleni)
Original Redmine Issue: 3715, https://redmine.hmdc.harvard.edu/issues/3715
Original Date: 2014-03-14
Original Assignee: Gustavo Durand

---

Contributors who can create and edit their own studies SHOULD NOT be able to see OTHER contributors unreleased or restricted studies/data.

From Sonia's email to Janina from GSD:
-------- Original Message --------
Subject:    Re: question on this contributor role
Date:   Fri, 14 Mar 2014 10:41:25 -0400
From:   Durand, Gustavo gdurand@iq.harvard.edu
To: Barbosa, Sonia sbarbosa@hmdc.harvard.edu

I don't think should be able to. We can try to test this and see what happen, but getting a fix in might be a challenge.

We can definitely make sure we define this correctly for 4.0 (permissions will be one of the higher priorities in the next few weeks!)

On Thu, Mar 13, 2014 at 1:12 PM, Barbosa, Sonia sbarbosa@hmdc.harvard.edu wrote:
Can contributors in the role below see restricted data?

From Janina at GSD:
I noticed that although the cataloging info in one of our studies is set to restricted, a contributor to the same dataverse (but who is not the creator of that study) can still see that info. 

Contributors can create and edit their own studies.

**Comment by jggautier** [comment]
In Dataverse 4.10.1, (and maybe earlier versions?) if someone is assigned the "Contributor" role at the dataverse level, that person has edit access to all datasets, published and unpublished, created in that dataverse (that person is able to edit even datasets that she didn't create or wasn't given access to on the dataset level).

Is this intentional? Do we think that if someone gives another person the "Contributor" role on her dataverse, she expects that person with the "Contributor" role to be able to view and edit all published and unpublished datasets in that dataverse?

I ask because @sbarbosadataverse let me know that recently a Harvard Dataverse user reported getting email notifications about the publications of datasets that he or she didn't create and wasn't given roles for on the dataset level. She was given a "Contributor" role on the dataverse level, 
and roles on the dataverse level get applied to the datasets within them, but he or she doesn't expect to get notifications every time a dataset in that dataverse is published. People with the Contributor role get dataset publish notifications because the role has the "Edit Dataset" permission, right, so it seems like email notifications are tied to this issue about editing datasets.

It looks like, at least for Harvard Dataverse, this is not causing a lot of email spam or causing a lot of people to have access to datasets that they shouldn't: Only about 60 **published** dataverses have people with "Contributor" roles assigned at the dataverse level, most of those dataverses have just one or two people with the Contributor role, and not all have published datasets.

But if it's intentional, this could be a symptom of unclear role descriptions (https://github.com/IQSS/dataverse/issues/4389).

**Comment by scolapasta** [comment]
Yes, this is intentional. Assigning a role at a higher level means you inherit that role on the lower levels. More specifically assigning Contributor at the dataverse means that user will be a Contributor on every dataset in that dataverse. (in fact, this is the reason, you would assign this Contributor, or other dataset level permission) at a dataverse level; to not have to manually assign to each dataset.
