### ISSUE TITLE
Add Piwik Analytics Support

### ISSUE THREAD

**Issue by jri-sp** [IQSS/dataverse#3018]
Hi all,

Google Analytics is already supported by Dataverse, but Piwik is not. 
I've implemented a new Snippet like the Google one and included it to the dataverse template. 

It seems to work well for me, I would like to show you that in Pull Request. So I'm creating this issue to respect the Feature Request Process.
It could be useful for other users.

Some issues are related to this: #1594  #2729
Quick discussion on IRC: http://irclog.iq.harvard.edu/dataverse/2016-03-15#i_32730

My commits are visible here: 

- https://github.com/jri-sp/dataverse/commit/56cf01f93f6d0e1d09c71a08c5fcd82e145c19d8
- https://github.com/jri-sp/dataverse/commit/b7c96830bef0d3f7b38ac91a7702ed5e40bf8784
- https://github.com/jri-sp/dataverse/commit/d195f883d0fa819713829789a57f3d8ecf8565e3

Regards,

**Comment by pdurbin** [comment]
@jri-sp it was nice chatting with you yesterday about this. Not all of us are familiar with http://piwik.org but as you indicated, it's been mentioned as an alternative to Google Analytics (by @bencomp ) in #1594 and at https://github.com/IQSS/dataverse/issues/2729#issuecomment-154369405

I just left you a tiny comment at https://github.com/jri-sp/dataverse/commit/b7c96830bef0d3f7b38ac91a7702ed5e40bf8784#commitcomment-16727570 .

I think you should go ahead and make a pull request, especially since you said it's working for you: http://irclog.iq.harvard.edu/dataverse/2016-03-15#i_32743

**Comment by bencomp** [comment]
We are looking at using Piwik for several of our services and out-of-the-box support in Dataverse would be great.

Do I understand correctly that this snippet only tracks page views, no other fancy things like actions (e.g. downloads) or searches? (I do need to get my hands dirty with Piwik, as searches might automatically be tracked - I don't know that yet :))

**Comment by sgrunt91** [comment]
Hi, @pdurbin and @bencomp ,

Yes, for now this code only tracks page views. Here is some examples:
![capture d ecran 2016-03-22 a 12 48 34](https://cloud.githubusercontent.com/assets/6524655/13950790/3b2e6194-f02d-11e5-9ede-29b84330e710.png)
![capture d ecran 2016-03-22 a 12 49 39](https://cloud.githubusercontent.com/assets/6524655/13950791/3b2ee8a8-f02d-11e5-94cb-bee69322e41d.png)

In the screenshot `dataset.xhtml?persistentId=doi:10.5072 > FK2 > 6WM7RL` is a download of a .jpg but it's not in the Piwik's download section because of the Dataverse download mecanism through `dataset.xhtml`.

To add download support I think we need to add a CSS class, more info on http://piwik.org/faq/new-to-piwik/faq_47/

Am I wrong ?

**Comment by pdurbin** [comment]
@jri-sp just made pull request #3374 and I left a comment at https://github.com/IQSS/dataverse/pull/3374#issuecomment-248905817

I have encouraged @jri-sp and @rmo-cdsp to call in via http://dataverse.org/community-calls to see if the issue can be moved out of "Backlog" at https://waffle.io/IQSS/dataverse

See our full conversation at http://irclog.iq.harvard.edu/dataverse/2016-09-22

**Comment by mheppler** [comment]
Reviewed the code with @pdurbin, and all looks good. We agreed that we'd like @raprasad to also take a peek, in regards to the render used, which was based on his code for Google Analytics.

**Comment by mheppler** [comment]
Received confirmation from @raprasad that everything looks good.

**Comment by djbrooke** [comment]
I'm going to add some documentation for this.

**Comment by djbrooke** [comment]
Oops - verified that documentation has been added as part of #3374

Awesome!
