### ISSUE TITLE
Files need to have categories (or labels)

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#303]
---

Author Name: **Gustavo Durand** (@scolapasta)
Original Redmine Issue: 3717, https://redmine.hmdc.harvard.edu/issues/3717
Original Date: 2014-03-14
Original Assignee: Leonid Andreev

---

None

---

Redmine related issue(s): [3385](https://redmine.hmdc.harvard.edu/issues/3385)

---

**Comment by kcondon** [comment]
Tested, works if the dataset has already been created but does not work if you add categories while creating the dataset -no category appears or is saved.

**Comment by eaquigley** [comment]
While in the Edit Categories pop up, if you enter in a category, then hit Enter, the pop up closes and it freezes the entire page. A user cannot click on any of the buttons on the Upload + Edit Files page.

@landreev @mheppler

**Comment by landreev** [comment]
Should be working now, please re-test. 
(new build needed, if testing today)

**Comment by kcondon** [comment]
OK, the case I reported is fixed: I can now add categories on dataset create.
The case Liz reported is not really fixed:
When adding a new category, if you hit return instead of clicking save changes, nothing is saved and the page is broken (no buttons work). On looking at firebug output for both scenarios, hitting return, at least using Firefox, throws a browser error and from experience that breaks the page.

**Comment by landreev** [comment]
I disabled return in the popup altogether.

**Comment by kcondon** [comment]
OK, works, closing
