### ISSUE TITLE
Permissions: List roles in order of power of permissions

### ISSUE THREAD

**Issue by bencomp** [IQSS/dataverse#3040]
When assigning roles to users or groups, the list of available roles is currently ordered alphabetically:

![screen shot 2016-03-29 at 12 53 18](https://cloud.githubusercontent.com/assets/1303898/14105741/ad65a12a-f5ad-11e5-9ecc-e6bae618f8e3.png)

Our users indicated that it would make more sense to order them by the power that their permissions have, i.e. Admin first (or last), then Curator, then Dataverse + Dataset Creator, ..., File Downloader last (or first). (I find it hard to come up with the best order, as the roles have different permissions, not just more or fewer.)

Newly defined roles (see also #2454) should blend in based on their permissions.

**Comment by bencomp** [comment]
It appears from `DataverseRole` that roles can currently only be sorted by name (and subsorted by the ID of the dataverse in which they were defined).

**Comment by pdurbin** [comment]
I guess you could try sorting by `permissionbits` since more bits means more power: http://phoenix.dataverse.org/schemaspy/latest/tables/dataverserole.html

![schemaspy_-_table_dvndb public dataverserole_-_2016-05-03_08 24 11](https://cloud.githubusercontent.com/assets/21006/14983005/7493d9fe-1108-11e6-8134-90df7ffda193.png)

**Comment by pdurbin** [comment]
Closing. I left a reminder at https://github.com/IQSS/dataverse/issues/2653#issuecomment-311848682
