### ISSUE TITLE
Metadata Blocks: Change from "showabovefold" to "displayoncreate"

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#3073]
This change would not require any code change or solr reindexing so I recommend that once I check this in it can be pulled into the dev branch for 4.4 release. 

This needs to be changed because it is causing confusion with dataverse installation users since it actually is a boolean to tag any metadata fields you want to show when you create a dataset and not show above the fold.

**Comment by bencomp** [comment]
@tdilauro suggested `displayDuringCreate` instead of `displayOnCreate`. Are you sure that it doesn't need any code changes? How does Dataverse decide which fields to show during creation of a dataset?

**Comment by posixeleni** [comment]
@bencomp I will be modifying this ticket to use @tdilauro suggestion.

Apologies for the confusion:

I am sure that the script that reads the tsv's does not actually look at
the names in that row. Those are solely there for humans to see.
@scolapasta can provide further technical details if this is not sufficient.

@tdilauro
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tdilauro&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=OiTcIL_jSSCUW82Gf-OSkgnZLbG2Yt87eT87BdLiP54&m=SBhNRIKNH6B8RH92ES4U3eh35RU32BPziW2ln_dINFA&s=TM97VcB3TaUYI3UXO2pl0MlhF3nzn_ngTT2oscxQZH8&e=>
suggested displayDuringCreate instead of displayOnCreate. Are you sure that
it doesn't need any code changes? How does Dataverse decide which fields to
show during creation of a dataset?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_3073-23issuecomment-2D209834885&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=OiTcIL_jSSCUW82Gf-OSkgnZLbG2Yt87eT87BdLiP54&m=SBhNRIKNH6B8RH92ES4U3eh35RU32BPziW2ln_dINFA&s=y7g2hmziI06zapPN8gBghZyQ_oK-QocYEAntxkQ-7Jc&e=>

**Comment by tdilauro** [comment]
Thanks for the reminder, @bencomp. And thanks for the update, @posixeleni.

Rationale from my comment in the [metadata block document](https://docs.google.com/document/d/1idh4wvCcoxSo7rPkolOkTD5Wvn6PQO__uXqkf7eQujA):
I would suggest renaming this variable to "displayDuringCreate", rather than "displayOnCreate". The "On" in the latter is too much like "Upon", which might be interpreted as "OnceCreateIsCompleted".

**Comment by pdurbin** [comment]
The field on the table is currently called "displayoncreate" which you can see at http://phoenix.dataverse.org/schemaspy/latest/tables/datasetfieldtype.html

Here's the Java side, which has a decent comment on what the field is for: https://github.com/IQSS/dataverse/blob/v4.3/src/main/java/edu/harvard/iq/dataverse/DatasetFieldType.java#L243

(Mental note that we should work on Publish Javadoc as HTML #2513 at some point.)

Anyway, I think it would be preferable to keep it as "displayoncreate" rather than "displayduringcreate" in the database table since they're almost the same. A change here would require a database upgrade script. It would probably be nice if the TSV file had the same label as what appears in the database.

**Comment by tdilauro** [comment]
@pdurbin Okay. I don't feel that strongly about it. But let's finish up this document and make it available so that there can be some prose explanation to clarify its function.

**Comment by posixeleni** [comment]
Sent the pull request so @scolapasta should be able to merge this.

**Comment by kcondon** [comment]
Works, closing
