### ISSUE TITLE
Shibboleth: "Allow me to type the name of my institution" option dropdown looks bad

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3091]
The "Allow me to type the name of my institution" option dropdown looks bad as originally noted in #3085 which included a screenshot of a gap:

![6eb93ab2-0891-11e6-8bbc-0284d48cee30](https://cloud.githubusercontent.com/assets/21006/14821352/705b84d8-0b98-11e6-917a-c39a05cd4b33.png)

Text also tends to run out of the box, like this:

![screen shot 2016-04-26 at 10 18 15 am](https://cloud.githubusercontent.com/assets/21006/14821383/8774bf68-0b98-11e6-8a76-ce022192d5c0.png)

The Shibboleth login is powered by the Embedded Discovery Service (EDS) from https://shibboleth.net/products/embedded-discovery-service.html which we've made some local modifications to when we introduced in in #794. @sekmiller is going to take a first swing at this. I'll assign it to 4.4 as a "nice to have" before we merge pull request #3025. The main reason I am creating this issue is that it will allow me to put #3085 through QA.

**Comment by sekmiller** [comment]
This feature is implemented purely in .js (idpselect.js)  - I don't have any experience in trouble shooting this.

**Comment by pdurbin** [comment]
For examples of EDS in action on other sites:

- http://issues.shibboleth.net
- http://wiki.shibboleth.net
- http://carmenwiki.osu.edu

Here's a screenshot from http://carmenwiki.osu.edu from Chrome:

![screen shot 2016-04-27 at 4 31 44 pm](https://cloud.githubusercontent.com/assets/21006/14867288/d1501a08-0c95-11e6-81c6-c920fc3c94d4.png)

I'm not the first to speculate that something in our CSS is causing the bug.

**Comment by mheppler** [comment]
Fixed CSS and tweaked the idpselect.js to fix the layout issues with the select dropdown menu on the login pg.

![screen shot 2016-05-16 at 4 50 30 pm](https://cloud.githubusercontent.com/assets/687227/15303627/b8840a48-1b86-11e6-9697-c729bcbd8122.png)

**Comment by mheppler** [comment]
In the absence of an FRD for these minor UI issues, I have added a bulleted outline of development here.

**Log In Pg**
- [x] Fix layout issue with dropdown list of suggested items in the "Allow me to type the name of my institution" workflow under the Institutional Account section.
- [x] Changed error text to read "Internal Error" instead of "FATAL - DISCO UI:" when there is a problem with the environment. #1762 
- [x] Stretched panel wrapper around both log in options, rather than just the one Institutional Account option, with conditional render logic that shrinks the width of the panel wrapper if there is only one log in option to display.
- [x] Change the header text for each option to be more consistent and concise, "Dataverse Account" and "Institutional Account", removing "Log In".
- [x] Style and improve layout of the help text for the Institutional Account section to be cleaner
- [x] Fixed layout of "previous selections" logo/title blocks under the Institutional Account section on login pg so that they float next to and not on top of each other.
- [x] Removed text above "previous selections" logo/title blocks under the Institutional Account section on login pg, and below, use the original help text associated with the form.

**Comment by kcondon** [comment]
These issues have been addressed. Closing.
