### ISSUE TITLE
Can't easily navigate to draft after deaccessioning

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3092]
Tested on https://demo.dataverse.org running v. 4.3 build 22-1e451ff

![screen shot 2016-04-26 at 3 11 13 pm](https://cloud.githubusercontent.com/assets/21006/14830970/6d426ca2-0bc1-11e6-9b99-7c121d35dcac.png)

![screen shot 2016-04-26 at 3 12 03 pm](https://cloud.githubusercontent.com/assets/21006/14830969/6d426a90-0bc1-11e6-8f5e-750ff18fd106.png)

"No records found." To navigate to the draft you have to leave the dataset page.

**Comment by eaquigley** [comment]
@pdurbin yup, this is happening because of the removal of the Versions dropdown that used to appear in the upper left of a dataset page but now is an easter egg that only appears after:  clicking the versions tab-> navigating to another version. Which is a not great workaround and actually, not even a workaround for deaccessioned datasets with a draft as you point out.

This relates to #2782

**Comment by mheppler** [comment]
Since this is a symptom of #2782, I am closing this issue in favor of that older one.
