### ISSUE TITLE
Ability to add a controlled vocabulary list using Templates

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#3107]
Meeting with a user today they asked if it was possible to enter a controlled vocabulary list using our templates feature. Since this was supported in 3.6 I am adding it here so that we can discuss how feasible this would be. This would especially help increase the curational quality of the keywords, topic classifications (depending on which discipline).

**Comment by bencomp** [comment]
As far as I know, in DVN 3 it's only possible to *select* an existing (but unconnected) CV for use in a field. In Dataverse 4 controlled vocabularies are strongly connected to a field type which is 'installed' service-wide and selected for use in the dataverse settings. I support the idea of the user you met.

I have said before that the current way of having a one-to-one connection between a metadata field type and a controlled vocabulary is weird, because you need separate lists for e.g. author and contributor even though you'd expect these lists to be the same.

**Comment by tlchristian** [comment]
Especially since Dataverse 4.x uses facets, it would be nice to be able to limit some metadata field inputs to controlled vocabulary terms.

**Comment by pdurbin** [comment]
@tlchristian interesting idea. Currently this is supported by `allowControlledVocabulary` being either true or false. When it's set to true, the data under `#controlledVocabulary` is used. Here's a screenshot from the citation metadata block linked from http://guides.dataverse.org/en/4.6.2/user/appendix.html

<img width="1433" alt="screen shot 2017-06-16 at 2 17 57 pm" src="https://user-images.githubusercontent.com/21006/27239407-c50e3090-529e-11e7-8391-61dd88ea232e.png">

**Comment by pdurbin** [comment]
Hmm, can people use https://github.com/gdcc/dataverse-external-vocab-support instead?

I hope so. Maybe we can close this issue.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
