### ISSUE TITLE
File Ingest: Make file object creation an atomic operation, dependent on verification of completed file upload.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3110]
To ensure data integrity, we should make sure file upload and ingest is atomic: the file object is not created/ retained unless the file is confirmed to have been uploaded completely and accessible by the application.

**Comment by pdurbin** [comment]
This sounds quite similar to what @raprasad was saying last week as we talked about file replace (#2290). We were talking about what happens when a user uploads a file but then decided to cancel. The file needs to be deleted from its temporary location on the filesystem and nothing should be persisted to the database. We talked a bit about adding a new table where information would be stored temporarily, until the user commits to keeping the file (clicks "Save"). Of course, I may be misunderstanding what this issue is about.

**Comment by raprasad** [comment]
Let's wait for @landreev investigation.  My prelim. notes are below in the gist.  After @landreev looks at it, there's probably a slightly different solution: 

https://gist.github.com/raprasad/1de7c53092c50adc1c21b35fd29471f3

**Comment by pdurbin** [comment]
@raprasad @landreev @djbrooke what is the status of this issue? I assume it's out of scope for #2290 and the 2290-file-replace branch.

**Comment by djbrooke** [comment]
Correct - out of scope for 2290 and not part of current sprint
