### ISSUE TITLE
Add support for different types of descriptions

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#3127]
A user just requested that in the description compound field we add description type which is supported in DataCite:

“If Description is used, descriptionType is mandatory.
Controlled List Values:
Abstract
Methods
SeriesInformation
TableOfContents
Other”

**Comment by pdurbin** [comment]
It's been over six years. Does anyone want this?

I checked. It's a thing ("TechnicalInfo" was added): https://support.datacite.org/docs/schema-optional-properties-v43#17a-descriptiontype

Vote to close.

**Comment by jggautier** [comment]
The Dataverse software's OpenAIRE export, which uses the DataCite standard, maps some of the Dataverse software's existing fields to DataCite's Description property using different descriptionTypes. For example, what's entered in the Dataverse software's "Series Information" field is put in the OpenAIRE export's Description property with descriptionType being "SeriesInformation". Other fields are mapped to the Description property using the "Methods" descriptionType. Software name is mapped to the Description property using the "TechnicalInfo" descriptionType.

<img width="1083" alt="Screen Shot 2022-10-05 at 1 46 59 PM" src="https://user-images.githubusercontent.com/18374574/194127020-fbdff399-7b2a-4d09-8090-46f5c008ba0c.png">

So this might be a case where:
- The Dataverse software has fields for at least some of this information, e.g. Series Information, but the user wanted to be able to add information in an interface whose design more closely follows how DataCite organizes information. Others have expressed something similar when talking about other standards, such as DarwinCore.
- The user wanted to be able to add information that could go in a field specifically for that information, like Table of Contents. I would guess that most depositors who want to add a Table of Contents are putting it in the Dataverse software's Description field.

So to figure out if anyone wants this, I would ask the community about these two points individually and explore how people depositing and looking for data benefit from the fields that the Dataverse software has, such as the Description and Series Information fields. For example, are depositors adding information about methods in the Description field instead of using some of the fields related to methods, such as Origin of Sources and Characteristic of Sources Noted? Would people searching for data more easily find data if those methods-related fields were used more often?

**Comment by pdurbin** [comment]
@jggautier wow, I had no idea. Thanks!

At the very least we should let people know what mappings are already going on. I guess we could start by updating the guides. Perhaps we could also put something in the UI.

Ok, maybe I had an idea but I forgot. I can see now that we put a blurb in the 4.16 release notes, at least:

https://github.com/IQSS/dataverse/blob/835ce5c25573d2b66b63576d08db819c696234a0/doc/release-notes/4.16-release-notes.md#openaire-export-changes

Information like this should also go in the guides.

It seems like we have at least partial support for the original request. Great! Now we just need to figure out what the next steps are. What's the definition of done for this issue, given we don't know the identity of the user who requested this issue be opened?

Related:

- #6062
- #6116

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
