### ISSUE TITLE
Widgets: Download citation, BibText shows spinner, does not go away.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3135]
BibText citation format opens in the browser and displays the animated spinner. It does not go away even after displaying the citation.

Happens in both Chrome and FF.

**Comment by mheppler** [comment]
Added target attribute to anchor link for BibTeX format of dataset citation in the Cite Data dropdown on dataset pg. That fixed the problem with it opening within the widget, and the blue spinner being displayed (it was there because it is the background image of the widget's iframe).

This issue raised another issue, where I noticed the URL of the BibTex version was just the dataset URL, and not a URL that makes that BibTeX version regularly accessible. Because of this, I have opened a new issue (#3140) to address this missing feature.

**Comment by kcondon** [comment]
Works, closing
