### ISSUE TITLE
Missing root dataverse results in uncaught exception and opaque HTTP 500 message page

### ISSUE THREAD

**Issue by tdilauro** [IQSS/dataverse#3148]
Absence of the root dataverse results in an uncaught exception and internal server error, which is displayed roughly as below. This error does not give a clear indication of what might be going wrong.

```
**HTTP Status 500 - Internal Server Error**
**type** Exception report

**messageInternal** Server Error

**description** The server encountered an internal error that prevented it from fulfilling this request.

**exception**
javax.servlet.ServletException

**root cause**
javax.ejb.EJBException

**root cause**
javax.persistence.NoResultException: getSingleResult() did not retrieve any entities.

**note** The full stack traces of the exception and its root causes are available in the GlassFish Server Open Source Edition 4.1.1 logs.
```

And here are a couple key lines from the mentioned domain server log, server.log:

```
at com.sun.proxy.$Proxy259.findRootDataverse(Unknown Source)
at edu.harvard.iq.dataverse.__EJB31_Generated__DataverseServiceBean__Intf____Bean__.findRootDataverse(Unknown Source)
```

It would be useful to catch this exception and display a more helpful error message.

This could be done in a manner similar to the way SolrServerException is caught in [SearchServiceBean.search()](https://github.com/IQSS/dataverse/blob/235eaa65cec8ce93a5aff9d52b4321038117a9a6/src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java#L335) and displayed by [search-include-fragment.xhtml](https://github.com/IQSS/dataverse/blob/2935cdedcd2f907d9b44356410d5139cfaf19062/src/main/webapp/search-include-fragment.xhtml#L60-L72), which results in a much more targeted message:

![screenshot-dv4 3 1-solrserverexception-ui-display](https://cloud.githubusercontent.com/assets/1247047/15680791/f903c8b6-2724-11e6-9831-b2ae48b8aebb.png)

**Comment by pdurbin** [comment]
@tdilauro thanks for creating this issue. As I was [saying in IRC](http://irclog.iq.harvard.edu/dataverse/2016-05-31#i_35770) we could also have the installer do a sanity check at the end to make sure that doing a `curl` of the homepage doesn't result in a 500 error. Belt and suspenders. 😄 

See also: Datavere 4.3.1 installation problems - getSingleResult() did not retrieve any entities. - Google Groups - https://groups.google.com/forum/#!msg/dataverse-community/xq1le9c8RmQ/0yhYe4dLLQAJ

**Comment by tdilauro** [comment]
@pdurbin I think that would be good to do a check during installation, as well, and perhaps as a first step. But I think it would be good to have this in the interface, as well.

**Comment by pdurbin** [comment]
@tdilauro yep. The change to https://github.com/IQSS/dataverse/blob/develop/scripts/installer/install (checking for a 200 response rather than 500 at the end) might be lower hanging fruit, depending on one's love of Perl, and could be done by a non JSF-hacker. 😄 

Here's how I do something similar in bask with curl at https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-deploy-develop/ as a test at the end of a successful deployment:

```
STATUS_CODE_FROM_DOWNLOADING_PUBLISHED_FILE=$(curl --insecure --write-out %{http_code} --silent --output /dev/null https://phoenix.dataverse.org/api/access/datafile/$FILE_ID_OF_A_PUBLISHED_FILE)
echo $STATUS_CODE_FROM_DOWNLOADING_PUBLISHED_FILE
if [[ "$STATUS_CODE_FROM_DOWNLOADING_PUBLISHED_FILE" != 200 ]]; then
  exit 1
fi
```

**Comment by pdurbin** [comment]
We just saw another case of this at https://groups.google.com/d/msg/dataverse-community/Esuj7HxZiF4/s3MUjtnzBgAJ

**Comment by PaulBoon** [comment]
Today I discovered the same problem on my Vagrant + Ansible test VM. 

Last week I had a working 4.8.6 based fork on the VM and I saw this problem sometimes but thought is was because of my own work in a local branch. Today I discovered that even after undoing my changes and clan VM ('vagrant destroy', 'vagrant up'), It now always shows this white page and that missing root in the logs. 

I will change back to my master branch and take a closer look, but it seems to be some external dependency because I am sure that it did work correct before with the 4.8.6 install.

**Comment by pdurbin** [comment]
@PaulBoon huh, if `vagrant up` is broken on either the "master" branch or the "develop" branch, please open a new issue. We don't have any automated tests to ensure that Vagrant is working but we want it to stay working. Thanks!

**Comment by PaulBoon** [comment]
At DANS we have our own (private) GitHub repo with the Vagrant+ansible code, on which I made a branch for a small addition.  
I think it's based (copied initially) on other existing code ;-) and using "geerlingguy/centos7".

**Comment by PaulBoon** [comment]
Ok, I seem to have fixed it on my side. Took  a lot of time doing 'vagrant destroy' and 'vagrant up'. 
In our Ansible code there was this 'pause' just before the 'setup-all.sh'. 

```
- name: Give glassfish 60 seconds to wake up
  pause: seconds=60
```

At first I changed this to 120 seconds, just to get confirmation that this was the problem and it worked. 
But it's an ugly thing, so I used the code from https://github.com/IQSS/dataverse-ansible/blob/064a8fa47b5f5283446191ab7bb1dbdbbbeef774/tasks/dataverse-postinstall.yml#L15

With a slight twist: 
```
- name: Wait for glassfish to become ready
  wait_for:
    port: 8009
    state: present
    delay: 30
```

This looks better, also note that the default timeout is 300 seconds, which seems much saver than 180. 

Hope that this might help the others with the getSingleResult() error.

**Comment by otheus** [comment]
I should note, I had this problem because the `setup-all.sh` script failed to set up the "root dataverse", and it failed to do so because `localhost` was being proxied (!). The proxy server had no idea what to do with `localhost` so all the REST-based setup requests failed.

**Comment by diego-guillen** [comment]
Friends, I'm a newbie trying a Dataverse 5.11 installation on a Rocky 8 VM (REHL8-compatible), for evaluation purposes.

I had a similar problem, when trying to access the dataverse page, I got the 500.xhtml error: getSingleResult() did not retrieve any entitites.
I verified the absence of the root dataverse, because the following query on `dvndb` is not returning any value:
```
select * from dataverse where alias = 'root';
```
I'm not sure how to proceed from here.  Any advice is welcome.

**Comment by diego-guillen** [comment]
> 

Solved it. To run the installation need to do it with the `dataverse` user, so the `dvinstall` folder, and the `dataverse.war` file deployed during the installation, must be visible and owned by this user. 

Follow the "fresh reinstall steps" from here: https://guides.dataverse.org/en/5.11/installation/installation-main.html#fresh-reinstall.

Then, copy everything from `/home/rocky/downloads` to `/home/dataverse/downloads`, and made the `dataverse` user its owner.

Finally run the perl script in `/home/dataverse/downloads/dvinstall/install`. It completed flawlessly.

**Comment by pdurbin** [comment]
@diego-guillen I'm glad you got it working! Thanks for reporting back!

**Comment by diego-guillen** [comment]
Hi QSS Dataverse team . 

In this opportunity I have a few technical questions.

Q1 -  We noticed that when creating a Dataset, we cannot save it if the compulsory metadata fields are not filled in. Is it possible to change some settings so that the Dataset could be saved even if the metadata fields are not fully complete? 

 The reason for this, is that we’re creating a customized Metadata template, which is long and takes time to fill. Users would probably prefer to save the dataset draft first, and then come back and fill in the metadata information later.

Q2a – Is the Datacite DOI prefix that we associate the Dataverse installation with, one per installation? 
If we host datasets from several universities, are we limited to produce datasets with only one common DOI prefix? 

Q2b - Would we need to install several QSS Dataverse applications (on various VMs) if we wanted to have separate DOI prefixes, one for each customer?

 Q2c – A DOI is generated automatically when we create a Dataset. Can we change the DOI to one preferred by each customer? Suppose we are hosting it for G-uni at Q-uni, but G-uni wants to use its own DOI prefix, not Q’s.

Q3 – Once the dataset is published, I noticed there are several options to export the metadata in various formats (Datacite, JSON, etc)  How can we customize an option that will allow us to export metadata from our own template?  I noticed that the JSON option lists all the metadata fields from our template. Is it possible to code/extend that feature to produce a different JSON export? 

Our experience so far, is that Dataverse seems to be a closed system, so it is cumbersome to extend it.

Thank you, in anticipation for your kind help.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
