### ISSUE TITLE
Expose Customized Publish Popup Message through API-Publish

### ISSUE THREAD

**Issue by shlake** [IQSS/dataverse#3156]
UVa has a configured popup message (thanks to the resolution of the following issue: https://github.com/IQSS/dataverse/issues/2833).

Our configured popup message needs to pass through when a "publish" request is sent via the API. For UVa, it is OK to expose this popup without an API token.

**Comment by pdurbin** [comment]
@jacksonokuhn and I discussed this issue briefly on Friday as I was heading out the door and he seemed eager to work on it, which is fantastic, so I'm assigning it to him.

On a dev box we want `curl http://localhost:8080/api/system/settings/:DatasetPublishPopupCustomText` (no authentication) to return a JSON representation of that database setting.

The API endpoint should be documented in the API Guide on the "native" page under a new "System" heading.

A REST Assured test should be included to exercise and validate the code: http://bl.ocks.org/pdurbin/raw/814fd29916749523db9a

See also https://github.com/CenterForOpenScience/osf.io/pull/5344 about how the reason for this feature is so that https://dataverse.lib.virginia.edu can be integrated with https://osf.io , a very noble cause! 😄 

As I was saying to @djbrooke I'll probably take the pull request for this issue (once it exists) and merge it with the branch from pull request #3137 for deployment to https://dev1.dataverse.org so that @shlake and @mfraezz can test both changes at once.

I'm sort of wondering how often @shlake intends to change the text and how often @mfraezz will configure OSF to poll for it. I assume the text won't change very often. Unfortunately, there's no "last updated" column on the `setting` table: http://phoenix.dataverse.org/schemaspy/latest/tables/setting.html T-T . Adding this is out of scope for this issue, I'd say.

**Comment by pdurbin** [comment]
@shlake thanks for opening this issue. At https://github.com/CenterForOpenScience/osf.io/pull/5344#issuecomment-225607309 I'm asking if you can help us test a fix by @jacksonokuhn on a dev server.

Either way, I'll go ahead and pass this issue to QA. @kcondon you can test the fix in isolation at https://github.com/IQSS/dataverse/pull/3166 or combined with the SWORD auth bug fix in https://github.com/IQSS/dataverse/pull/3167

**Comment by kcondon** [comment]
Leaving in QA but removing my name until I get pull request.

**Comment by pdurbin** [comment]
We discussed the pull request at #3166 and decided to use "info" rather than "system" in the URL of this API endpoint. I just created a new pull request at #3219 to address this change.

Passing to QA.

**Comment by kcondon** [comment]
Reassign it to the person and say it needs CR before QA as was agreed upon by the team, move it back into the development column

**Comment by pdurbin** [comment]
@scolapasta please code review pull request #3219 and if you're ok with how it looks, please move this issue through the pipeline to QA.

**Comment by kcondon** [comment]
The actual command is: curl http://localhost:8080/api/info/settings/:DatasetPublishPopupCustomText

The solution is instead of displaying this tou during a publish api call, instead make the tou text accessible by the above api call so the OSF/DV integration and implement business rules of fetching, displaying, and requiring agreement to the custom tou.

Docs are also in place.
