### ISSUE TITLE
Add dev mode option to installer

### ISSUE THREAD

**Issue by jacksonokuhn** [IQSS/dataverse#3163]
It would be good to include the option to enable dev mode on install so that the test suite works out of the box.

**Comment by pdurbin** [comment]
When in dev mode the installer should run `setup-all.sh --insecure` like we do at https://github.com/IQSS/dataverse/blob/v4.3.1/scripts/deploy/phoenix.dataverse.org/post

Otherwise, the expected "burrito" string is deleted: https://github.com/IQSS/dataverse/blob/v4.3.1/scripts/api/setup-all.sh#L83

Without the "buritto" string, integration tests fail to create temporary users with which to run the tests. For example: https://github.com/IQSS/dataverse/blob/v4.3.1/src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java#L34

**Comment by pdurbin** [comment]
Highly related to #3431.

**Comment by pdurbin** [comment]
Related: #3937

**Comment by pdurbin** [comment]
> so that the test suite works out of the box

Thanks to @bsilverstein95 we now have http://guides.dataverse.org/en/4.7/developers/testing.html#getting-set-up-to-run-rest-assured-tests

I'm closing this in favor of #2443.
