### ISSUE TITLE
Widgets: Conditional display of "Producer" or "Distributor" text

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#3180]
If a Dataset specifies ONLY ONE metadata field of type URL: 
e.g.
- Producer URL  
- Distributor URL

then the Dataset Citation widget will NOT display the respective title of the field in the widget and will only display "URL"

If a Dataset specifies multiple metadata fields of type URL:

then the Dataset Citation widget will display the display name of the field, e.g. "Producer URL" along with the specific URL.

**Comment by djbrooke** [comment]
@scolapasta - feel free to edit this one up if it does not reflect the desired changes!

**Comment by kcondon** [comment]
@djbrooke I was not aware of the second requirement regarding multiple citation field URL labels.
@scolapasta Did you code for the multiple citation URL case?

**Comment by scolapasta** [comment]
Yes, it checks count of URLs and only substitutes the name if there is only one URL.

**Comment by kcondon** [comment]
Yes, verified with 1, 2, and 3 different url fields. Waiting final tweak, passing back to Gustavo to fix generalization issue.

**Comment by pdurbin** [comment]
In e62d5a2 I updated the Solr schema for the alternativeURL field added in e10ab1e but I thought I'd mention that it seems a little strange to me that this field appears even above "title" when updating metadata:

![screen shot 2016-06-28 at 1 56 48 pm](https://cloud.githubusercontent.com/assets/21006/16426906/0620297a-3d39-11e6-83ee-fe2ed8db2558.png)

Also in in e10ab1e the tsv was edited directly rather than applying to change first to what I thought was the source of truth for the citation metadata block, the spreadsheet tab at https://docs.google.com/spreadsheet/ccc?key=0AjeLxEN77UZodHFEWGpoa19ia3pldEFyVFR0aFVGa0E#gid=0 linked from http://guides.dataverse.org/en/4.3.1/user/appendix.html#metadata-references . If we are abandoning those spreadsheet tabs as the source of truth for our metadata blocks we should stop linking to them from the User Guide. #3168 is related.

A side note is that the way I update the Solr schema is by loading *all* the metadata blocks, running `curl http://localhost:8080/api/admin/index/solr/schema >> conf/solr/4.6.0/schema.xml` and then editing schema.xml by hand to update the two sections (field and copyField), replacing the content that was there with the content that was in the script. For now this process is documented at the top of https://github.com/IQSS/dataverse/blob/v4.3.1/src/main/java/edu/harvard/iq/dataverse/search/SearchFields.java

**Comment by scolapasta** [comment]
That location was the first suggested location from @mcrosas but after further review (seeing it here) we moved it between alternativeTitle and OtherId.

**Comment by scolapasta** [comment]
Also, I went ahead and updated that doc with this new field; however I don't think it has been kept up to date for other changes. (For example, these were removed: contributorAffiliation, contributorIdentifierScheme, contributorIdentifier, but are still there)

These changes are from before, and outside the scope of this issues.

**Comment by kcondon** [comment]
Works! Closing.
