### ISSUE TITLE
Restore `/account/apitoken` url

### ISSUE THREAD

**Issue by felliott** [IQSS/dataverse#3204]
Hello!

My name is Fitz Elliott and I'm a programmer with the [Center for Open Science](https://cos.io).  We provide an addon to the [Open Science Framework](https://osf.io) (OSF) that allows Dataverse users to connect their Dataverse and OSF accounts, enabling the simple transfer of research materials into Dataverse.  The v4.4 release of Dataverse changed the url for a logged-in user to get their API token from `/account/apitoken` to `/dataverseuser.xhtml?selectTab=apiTokenTab` (see commit 0e08dca4d1bd).  This broke the links we give to users to get their tokens.

It's easy for us to update the url, but we will soon be supporting the University of Virginia's Dataverse instance, which is running v4.3.  We're also planning to support other institution-specific Dataverses in the future, and if possible we'd like to avoid having to keep track of version-specific urls.  Would it be possible for you to restore the `/account/apitoken` route as a redirect to the new url?  Thank you very much and have a great day!

Cheers,
Fitz

**Comment by pdurbin** [comment]
@felliott before UVA can integrate with OSF, they will need to be running a version higher than 4.4 that includes the following fixes:

- #3156 (pull request #3166)
- #1070 (pull request #3137)

Thank you very much for the fix at https://github.com/CenterForOpenScience/osf.io/pull/5957 and sorry that I didn't give you a heads up that this URL was changing.

https://github.com/CenterForOpenScience/osf.io/pull/5344 is about integrating a second Dataverse installation with OSF (woo-hoo!). That second installation is UVa so again, since they need to upgrade anyway, no one will need the old API token URL. If a third Dataverse installation comes along asking to integrate (and I hope they do!), please tell them that they should be running Dataverse 4.4 or newer.

**Comment by felliott** [comment]
Oh!  I didn't realize that UVa was going to be upgrading.  Then can I modify my request?  When an OSF user is connecting their DV account, we give them a link to `/dataverseuser.xhtml?selectTab=apiTokenTab` that they can click on and go directly to the token tab.  If they haven't logged in yet, they are sent to a login screen.  The redirect function of the login page strips the query parameter from the original url, so after a successful login they are sent to `/dataverseuser.xhtml`, but not the token tab.  It's a minor thing, but would it be possible to preserve the query parameter or provide some way to send them straight to the token tab after login?  Thank you!

**Comment by pdurbin** [comment]
@felliott sure! Please update the subject/title of this issue to better reflect what you want.

**Comment by felliott** [comment]
Thanks, @pdurbin!  I've created a [new issue](https://github.com/IQSS/dataverse/issues/3207), without the irrelevant information.
