### ISSUE TITLE
Types parameter in the URL

### ISSUE THREAD

**Issue by Venki18** [IQSS/dataverse#3253]
This is part of a series of issues raised by NTU libraries as discussed with @pdurbin 

NTU Central IT division did an Appscan on dataverse application installed in the development server and found few issues. Please refer to the section below on Appscan and what is it and how its being done. 

The types parameter in the URL (_GET /?q=& types=%28select+datasets%29 &sort=dateSort&order=desc&page=1_) was flagged as high vulnerability and identified as Blind SQL injection. During our one to one session with Phil in IQSS on 14th July, Phil mentioned that the Types parameter is used to query Solr indexes and nothing to do with Postgres database. NTU libraries need to clear this with our IT division before we can go ahead with making the application public. We would like to request Harvard to reply to this as "False Positive" or no Blind SQL injection is possible to this issue. Which would help us to clarify with our IT division.

**How does AppScan work?**
- Scope = web application only, not the OS
- Intrusive and thus can mess up the target web application server, e.g. SQL injection messing up DB, etc.
- Traverse and try to attack a web application
- Approaches an application as a black-box
- Tests by sending modified HTTP/HTTPS requests to probe and attack the web application
- Read http://www-03.ibm.com/software/products/en/appscan-enterprise (tool used for appscan) for details

**Comment by pdurbin** [comment]
Right, https://demo.dataverse.org/?q=&types=%28select+datasets%29 is a simplified example and results in a poor user experience in that none of the "types" (dataverses, datasets, and files) are selected (screenshot below from that server, which is running v. 4.4 build 132-47b04ed) but this **this is a usability bug rather than a security bug**. (The GUI itself should never yield a URL like this but these URLs can be manipulated manually, of course.) As @Venki18 and I discussed, this "types" query parameter drives a query to Solr, not PostgreSQL. Here is where the "types" query parameter is used as of Dataverse 4.4:

- `types` in https://github.com/IQSS/dataverse/blob/v4.4/src/main/webapp/dataverse.xhtml#L27
- `selectedTypesString` in https://github.com/IQSS/dataverse/blob/v4.4/src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java#L222

![screen shot 2016-08-19 at 1 59 15 pm](https://cloud.githubusercontent.com/assets/21006/17819487/1ba5dfa0-6616-11e6-8205-24b184541d68.png)

**Comment by pdurbin** [comment]
Again, this is not a security bug and the GUI doesn't ever produce the problem above. You have to hack on the URL. Vote to close.
