### ISSUE TITLE
Error Page showing Glassfish error

### ISSUE THREAD

**Issue by Venki18** [IQSS/dataverse#3256]
This is part of a series of issues raised by NTU libraries as discussed with @pdurbin

Refer to other issues - #3253, #3254, #3255 

When the URL parameter is changed to null for example in the following url
/dataverseuser.xhtml?editMode=CREATE& redirectPage=\
the redirectPage parameter was set to "\" and the error page is shown as seen in the image.
![image](https://cloud.githubusercontent.com/assets/19611506/17542483/bae2023c-5efb-11e6-86cf-09897763d625.png)

Its good to have a default error page that says " Sorry an internal application errror has occured. Try sometime later", etc.... The default or standard error page would help the application to fail gracefully.

**Comment by pdurbin** [comment]
Yuck. Yes I can reproduce this as of v. 4.4 build 132-47b04ed at https://demo.dataverse.org/dataverseuser.xhtml?editMode=CREATE&redirectPage=\

I don't believe this is a security issue. In the stacetrace (attached) it seems like "\" simply isn't a valid character in a URL: `Caused by: java.net.URISyntaxException: Illegal character in query at index 40: /500.xhtml?editMode=CREATE&redirectPage=\`

[issue3256.txt](https://github.com/IQSS/dataverse/files/427638/issue3256.txt)
![screen shot 2016-08-19 at 2 19 01 pm](https://cloud.githubusercontent.com/assets/21006/17819943/5a337834-6618-11e6-91fa-20938c0a7546.png)

**Comment by pdurbin** [comment]
@Venki18 I just went to https://demo.dataverse.org/dataverseuser.xhtml?editMode=CREATE&redirectPage=\ and can't reproduce this anymore as of 4.9.1 build 876-7237517. Closing. Please let us know if you can still reproduce this. Thanks!
