### ISSUE TITLE
Harvest: Automatically update manage client page as harvesting completes.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3260]
Currently when you run a harvest client, the UI has a message indicating you need to refresh the page to see the status. Although as designed, It would be nice if this happened automatically in a future release.

**Comment by djbrooke** [comment]
Removing from 4.5, possibly will be added in a future release.

**Comment by landreev** [comment]
Adding my comment I added earlier to Kevin's "test checklist" document: 

I'm afraid we'll have to live with this in 4.5. That's why the message says "refresh the page to see the results..." This approach is being used in other pages... so it's ok, right?

(end of quote)

Yeah, it's ugly... But it's not as trivial as it one would expect... It took some effort to make the tabular ingest status of a file auto-update on the files page. I want to put some thought into designing this properly... And yeah, the fact that some other pages (such the group page) use this "refresh the page to check on the progress..." message solution makes me feel a tiny bit better about this.

**Comment by pdurbin** [comment]
Pull request #5248 just came in from @tcoupin and I believe he is addressing this issue so I moved it to code review.

**Comment by pdurbin** [comment]
Pull request #5248 was merged as part of 4.10 but #5735 (Manage Harvesting Client page keeps refreshing. Unable to add or edit clients) cropped up and pull request #5926 was just merged to revert the original pull request.
