### ISSUE TITLE
Harvest: Update sets to handle deaccessioning of published dataset version where previously published version exists.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3263]
When an entire dataset, meaning all versions, is deaccessioned then it is not harvested, or if deaccessioned after harvesting, it is then handled as a deletion.

We also allow deaccessioning of individual versions of datasets. If older versions of datasets are deaccessioned, then the set is unaffected. If the latest published version is deaccessioned but there exists a previously published version, then the next latest published version effectively becomes an update to the set. That is how deaccessioned versions are handled by dataverse.

**Comment by landreev** [comment]
OK, here's how I'm handling it now: 

Deaccessioning a version now triggers a re-export of the last previously released version (if available). Any OAI sets that the dataset is part of are NOT automatically updated. 
So this means that in the meantime, before the set is rebuilt (manually or by a scheduled job), the following takes place:

- if a brand new harvester comes in, they will get the correct, updated metadata;
- if a regular harvester comes in, the dataset will NOT be listed as updated, so it will not be harvested. (but they will harvest it tomorrow, or whenever their next scheduled harvest is; because the oai record will be updated by that time)

It IS possible to automatically update any existing OAI records that belong to datasets that are being published or deaccessioned... I'm just not doing it as of now. (don't feel comfortable introducing too much new functionality at this point). 

So please retest.

**Comment by kcondon** [comment]
Works now, thanks. Closing.
