### ISSUE TITLE
Export: Dublin Core format is missing language tag.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3271]
Elen's metadata mapping spreadsheet specifies language as a required field for Dublin Core export but it is not included.

**Comment by djbrooke** [comment]
Stephen - can you please take a look at this issue? The spreadsheet is here:

https://docs.google.com/spreadsheets/u/1/d/10Luzti7svVTVKTA-px27oq3RxCUM-QbiTkm8iMd5C54/edit?usp=sharing

**Comment by sekmiller** [comment]
Fix is checked in.  The surefire way to test is to republish a dataset that has an entry in the list of languages - the manually export.

**Comment by sekmiller** [comment]
@djbrooke - not sure why you assigned this back to me.  I just looked on as @kcondon verified the fix on Build. Do I need to do something in Waffle?

**Comment by djbrooke** [comment]
Beh. Waffle thing. Sorry about that!

**Comment by landreev** [comment]
@kcondon @djbrooke 
It looks like Steve has fixed it in his export util - great!
Do you want me to fix this on the import side too then? Or are you less concerned with the import? 

I believe the fix is trivial - it'll just require an extra mapping line in the reference_data.sql; and an extra line in upgrade_v4.4_to_v4.5.sql, for the existing nodes upgrades... But you would have to re-test it... So, please advice - fix now? Or fix in the next release?

**Comment by djbrooke** [comment]
Let's fix this for 4.5.

**Comment by landreev** [comment]
The solution in #3272 should take of this as well.

**Comment by landreev** [comment]
Kevin, I added some code to the DC import to handle controlled vocab. fields. So it should be working for "dc:language" now. 
![screen shot 2016-08-15 at 9 39 59 pm](https://cloud.githubusercontent.com/assets/737558/17685333/ffae5f58-6330-11e6-9a5f-c9580ca8af4f.png)

**Comment by kcondon** [comment]
Works, closing.
