### ISSUE TITLE
Harvest: Dublin Core, publisher (producer) not searchable/ imported.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3272]
According to Eleni's metadata mapping spreadsheet, the publisher should be imported and therefore searchable after harvest. It is not. Not sure where the breakdown is but it appears to be exported and might be in import.

**Comment by landreev** [comment]
Could you add a link to Eleni's spreadsheet please? - I can't find it. 
It doesn't get imported, no - we don't provide a DC -> dataverse metadata mapping for this field... 
Looking at the DC export code it's not clear how to import it either. Because when we export, apparently we just push the name of the owner dataverse into the field... We obviously can't reverse this when we import... 
Yeah, I kinda feel this is out of scope for this release.

**Comment by djbrooke** [comment]
Spreadsheet is here: 

https://docs.google.com/spreadsheets/d/10Luzti7svVTVKTA-px27oq3RxCUM-QbiTkm8iMd5C54/edit#gid=0

**Comment by djbrooke** [comment]
@kcondon - thanks for offering to provide some more details here!

**Comment by kcondon** [comment]
Discussed with Leonid. The metadata mapping spreadsheet can be somewhat ambiguous, especially when, for a given dc terms field, publisher, has a different export and import field source and destination.

In this particular case, literally the dc field publisher should map to the Dataverse field producerName.

**Comment by landreev** [comment]
OK, so I believe adding these 2 lines to the database should make DC import handle both the "publisher" and "contributor" fields correctly, as described above:

INSERT INTO foreignmetadatafieldmapping (id, foreignfieldxpath, datasetfieldname, isattribute, parentfieldmapping_id, foreignmetadataformatmapping_id) VALUES (18, ':publisher', 'producerName', FALSE, NULL, 1 );

INSERT INTO foreignmetadatafieldmapping (id, foreignfieldxpath, datasetfieldname, isattribute, parentfieldmapping_id, foreignmetadataformatmapping_id) VALUES (19, ':language', 'language', FALSE, NULL, 1 );

(dc import is programmatic, defined by these entries in the database...)

**Comment by kcondon** [comment]
Works, closing.
