### ISSUE TITLE
Harvest: Exporting all IQSS datasets has several failures.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3276]
I've created a set that includes all of the IQSS handle and doi domains and see from the set status the following results:

19,734 datasets (19,726 records exported, 0 marked as deleted)

so, 8 datasets failed export, pretty good record! This ticket is to investigate the 8 failing cases.

**Comment by djbrooke** [comment]
@sekmiller - can you take a look at this with @kcondon to determine that the failures were reasonable and accurately counted?

**Comment by sekmiller** [comment]
Added more logging; haven't seen any failures

**Comment by kcondon** [comment]
Was able to do an export all against prod db and it completed without failures. The source of the failures was the export stats on the All_local set for prod db on vm5. So, the issue may be with how the stats are reported. We should retest.

**Comment by djbrooke** [comment]
We need to retest this.

**Comment by kcondon** [comment]
Still happens when I export the set, same message:
All_local
all local
dsPersistentId:"hdl:1902.1" OR dsPersistentId:"doi:10.7910"	19,734 datasets (19,726 records exported, 0 marked as deleted)

**Comment by landreev** [comment]
@sekmiller 
@kcondon 
Actually, no, I don't know of an easier way to find these 8 datasets that are failing export - than to re-run exportAll on vm5; and then to look at the harvest log. But we need a new build on vm5 for that. Kevin, could you please update vm5? - Thanks.

ExportAll should not take long either, because it should only attempt to reexport the still unexported datasets... and that's the failures we are looking for.

AND this is our chance to test that my latest code is actually logging the exceptions... Please let me know if it isn't. (there's a separate ticket for export logging)

**Comment by sekmiller** [comment]
Inspecting one of these datasets in production shows no version on the versions tab:
<record>
  <date>2016-08-19T13:51:15</date>
  <millis>1471629075104</millis>
  <sequence>2036</sequence>
  <logger>edu.harvard.iq.dataverse.harvest.client.DatasetServiceBean.ExportAll2016-08-19T13-40-13</logger>
  <level>INFO</level>
  <class>edu.harvard.iq.dataverse.DatasetServiceBean</class>
  <method>exportAllDatasets</method>
  <thread>1673</thread>
  <message>Error exporting dataset: Voting then, voting now: The long term consequences of participation in South Africa's 
                                                                                                                           rst democratic election doi:10.7910/DVN/GOLMTC; Caught XMLStreamException performing DCTERMS export</message>
</record>

**Comment by landreev** [comment]
OK, here's the ticket I was talking about:
https://help.hmdc.harvard.edu/Ticket/Display.html?id=236623

- the version tab (and lots of other things) were failing on the page, because there were binary characters x0A, x0B, x0C and x0d in some metadata field. The fix was to remove the offending characters, and then update the field value:

UPDATE datasetfieldvalue SET value='We investigate whether mining affects local corruption in Africa...etc.' WHERE id=2711378"

**Comment by djbrooke** [comment]
@sekmiller - you mentioned you were going to take a look at this and add some additional logging for these binary characters so I'm going to assign it to you. 

However, due to the numbers here (8 of 19,734), I don't feel this should be a blocker for release.

**Comment by djbrooke** [comment]
Removing from the 4.5 milestone as this was a nice-to-have and the release is nigh.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
