### ISSUE TITLE
Index: Index all fails on migrated harvested content other than Odum

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3278]
If performing an index all, it will halt when it encounters IQSS migrated legacy harvested content from places other than Odum: ICPSR, Roper.

This did not happen in builds prior to 4.4, though the underlying condition may have existed.

A temporary workaround is to bypass indexing these datasets by setting the last harvest date and doing an incremental index but it would be good to be able to index all without constraint. Also, why did it begin happening recently if it was always there?

**Comment by landreev** [comment]
@kcondon 

For the sake of accuracy, we don't know that indexing is failing on harvested datasets from everywhere but Odum. We don't know if it's failing on the datasets from ICPSR and Roper either. 
Because we gave up on reindexing  harvesting datasets as soon as we saw the first exception from a non-Odum harvested dataset. Which happened to be a Nesstar one. (We are not likely to go back to harvesting from Nesstar nodes any time soon). 

if we are specifically interested in Roper, let's try and re-index Roper specifically. It may actually work for all we know.

**Comment by landreev** [comment]
OK, roper datasets ARE failing to index too. It's unrelated to/different from #3197 - the citation code doesn't like something about their global ids. Could be easy to fix, I'll take another look. 
(for the record, being able to index these old, grandfathered Roper datasets may not in any way help us to start harvesting new records from new Roper. I can explain if needed. But as I said, probably easy to fix, regardless)

**Comment by landreev** [comment]
Kevin, I fixed that global identifier thing in the citation code that I talked to you about. 
Roper datasets appear to be indexing now; though I only indexed the first 100. Also tried some Nesstars, worked too. Let's try and run it on all of them, and see how it goes (no guarantees some other datasets  aren't going to bomb on something else). But I'll reindex the local holdings first. 

Also, the whole thing about not showing the handles for some of the harvested datasets: this by itself is not new. This how their citations are indexed in production now (for example, check out roper: https://dataverse.harvard.edu/dataverse/roper). 
It was just that that minor bug was introduced when the citation code was rewritten recently.

**Comment by landreev** [comment]
OK, went through 30K harvested datasets (we have 38K total). Then died on the first ICPSR dataset. (ok, that really means we've gone through everything harvested, except for the ICPSR). 
Will take a look. 

(it looks like our DataCitation parser just doesn't like their DOIs.. probably because they have these dot-separated suffixes - as in doi:10.3886/ICPSR24006.v2... and the parser expects them to only contain alphanumerics...)

**Comment by landreev** [comment]
icpsr has finished indexing... Kevin, if you want to re-test one reindex of everything, one more time - it's all yours.

**Comment by kcondon** [comment]
This is now working, too 6hours, 43 mins:

  3832 dataverses and 68481 datasets indexed. index all took 24182515 milliseconds. Solr index was not cleared before indexing.

Closing.
