### ISSUE TITLE
Harvest: Deleted datasets do not remove associated file cards.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3283]
While testing set redefinition behavior, I found that a dataset that was marked for deletion because it was no longer part of the set (but still existed, though probably not related) resulted in the dataset being removed but its file cards remaining.

**Comment by landreev** [comment]
OK, this is a serious issue... I'll have to fix this tomorrow (I mean, on Monday).
I can see now why it's happening. I thought deleting a dataset "document" in SOLR was supposed to automatically delete all the file entries belonging to the dataset... But no, it appears I'm supposed to specifically delete all the individual file documents too - otherwise they stick around...
There's a "nuclear" workaround - to do "clear" and "index all"... but we need a fix.

**Comment by landreev** [comment]
Should be fixed now. 
harvested files should no longer stick around in search results, after you delete their parent datasets.

**Comment by kcondon** [comment]
File cards are now removed. Closing.
