### ISSUE TITLE
Harvest: When harvesting a set that has been deleted, client reports success though set not accessible.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3284]
Was investigating behavior of client when set is deleted. Found that the client reports success but nothing harvested, no error in logs, etc. 

Would be nice to know something happened. On server, in logs it reports that a set does not exist anyway.

**Comment by djbrooke** [comment]
The desired behavior would be for a message to display with more accurate information - specifically, that the set is no longer available.

**Comment by landreev** [comment]
Actually, for this one I'd like to petition that we leave it as is for now. 

This is how it is implemented in XOAI-dataprovider - the OAI library/implementation we are using. They really do return a "nothing found" response, when you ask for records from a non-existing set; that's indistinguishable from a response you get when you don't get back any records because nothing has changed since the last time you checked. 

Furthermore, this is how it is implemented in OAIcat (the library DVN3 was using) as well. I just tested it with Odum production server - same deal, "nothing found". 

You can't even say that it is a "bug" necessarily... The OAI spec doesn't say explicitly how it should be handled. And there is no reserved "No such set" error code (even though there are codes for "No such metadata format" and "No such identifier"). 

Common sense-wise, I agree this should be treated as an error. I could overwrite their implementation somehow to return a generic "BadArgument" error code with a "no such set" message... But at this point it feels like an amount of pain in the butt disproportionate to any benefit we would get out of it... Seeing how this can't possibly cause any real harm to anyone.

**Comment by djbrooke** [comment]
Leonid - thanks for the research. Sounds good to me.

**Comment by kcondon** [comment]
Could you not apply logic outside of oai library that says, if this has never been successfully harvested and you are receiving no reponse, likely this means set does not exist? Could be a warning in the UI with that note.
