### ISSUE TITLE
Installer - Remove creation of "reference_data_filtered.sql" file

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#3285]
In a new installation, the installer created the "reference_data_filtered.sql" file locally, and it is no longer in use, and can be removed from the installation.

**Comment by landreev** [comment]
i pushed in a fix earlier today.

**Comment by pdurbin** [comment]
@landreev @kcondon can you please look at pull request #3292 by @telnoratti which fixes #3291 and see if it makes sense to merge it (or make the equivalent change to the 4.5-export-harvest branch since the pull request is against "develop") before testing this issue about reference_data_filtered.sql?

**Comment by kcondon** [comment]
That issue has nothing to do with the issue in this ticket. The pull request you mention addresses a bug with install but it is a separate issue.

**Comment by kcondon** [comment]
The file was removed, closing.
