### ISSUE TITLE
Advanced search - for a specific dataverse

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#331]
---

Author Name: **Gustavo Durand** (@scolapasta)
Original Redmine Issue: 3746, https://redmine.hmdc.harvard.edu/issues/3746
Original Date: 2014-03-20
Original Assignee: Philip Durbin

---

Right now advanced search works for the root dataverse, but once we get the alias concept working, we'll need it to work for a specific dataverse.

This will include logic to determine which metadaablocks to show.

---

Related issue(s): #48
Redmine related issue(s): [3455](https://redmine.hmdc.harvard.edu/issues/3455)

---

**Comment by eaquigley** [comment]
Mockups for this: https://iqssharvard.mybalsamiq.com/projects/advancedsearchperdataverse/grid

**Comment by eaquigley** [comment]
Have only the metadata blocks enabled for the dataverse appear on the advanced search page.

**Comment by scolapasta** [comment]
#1302 covers the case of child dvs and is for post 4.0

**Comment by pdurbin** [comment]
Being able to use the Advanced Search page on a particular dataverse subtree has now been implemented. As shown in the [mockups](https://iqssharvard.mybalsamiq.com/projects/advancedsearchperdataverse/grid), the way you enter into Advanced Search is by first navigating to the dataverse in question and then clicking "Advanced Search". You can't switch which dataverse you're searching from the Advanced Search page. This is how Advanced Search works in DVN 3.x as well.

Note that as requested, only the metadata blocks for the selected dataverse are shown.

As before, the Advanced Search page really is just constructing a URL to pass to the dataverse page (where searching happens) with "q" and other parameters. It's the equivalent of typing in same query in from basic search (if you knew all the field names).

Please note that after discussing URLs with @mheppler and @eaquigley we've gotten rid of http://localhost:8080/search/advanced as a URL. Rather, you see the dataverse alias/identifier in the URL followed by "/search" like this:

- http://localhost:8080/dataverse/root/search
- http://localhost:8080/dataverse/birds/search
- http://localhost:8080/dataverse/trees/search

(I had to do a undeploy/deploy to get the URLs to update after this PrettyFaces config change.)

@mheppler has lots of ideas for how URLs and breadcrumbs should look for search but I didn't get a chance to look into this. Maybe he'll create a ticket. I do understand that after you click "Find" from the Advanced Search page, the URL gets uglified into something like http://localhost:8080/dataverse.xhtml?q=dvDescription_en%3Afoo&id=1 . For now this is expected behavior. The focus here is the functionality.

Moving to QA.

**Comment by kcondon** [comment]
OK, tested scope, objects, blocks, URL, all works as described. Closing.
