### ISSUE TITLE
Breaking change to API?

### ISSUE THREAD

**Issue by felliott** [IQSS/dataverse#3326]
Hello!

Starting yesterday, the OSF integration with Dataverse broke because some fields in the file metadata response were renamed.  `datafile` became `dataFile`, and `dataFile.name` became `dataFile.filename`.  This happens even when using the versioned api url (`https://demo.dataverse.org/api/v1/datasets/1665/versions/`).  From [this issue](https://github.com/IQSS/dataverse/issues/411), I thought a change like this would require a version change in the API url.  Is that correct?  And if so, how long do you maintain old versions of the API?  Apologies if this is already documented somewhere, most of what I found pertained only to the SWORD api.  I'll update our code to handle both versions in the meantime.

Cheers,
@felliott

**Comment by pdurbin** [comment]
@felliott thanks for opening this issue. From looking at https://github.com/CenterForOpenScience/waterbutler/commit/1d803b14a678ee88e599bf25809d890cbfe0d612 I see what you mean. I appreciate you jumping on this and fixing it!

**Comment by pdurbin** [comment]
@djbrooke as @sekmiller and I discussed this morning, I was hoping that running the "phoenix" API tests would have caught this change to the API but I just ran them against the develop branch, which hasn't changed since 4.5 was tagged and the existing API tests must not exercise the change that @felliott has reported in this issue because all the tests passed: https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/43/

The solution is probably to write more automated tests, work that we started in #2746.

@sekmiller can you please look at the fix by @felliott at https://github.com/CenterForOpenScience/waterbutler/commit/1d803b14a678ee88e599bf25809d890cbfe0d612 and see if it rings a bell? I wonder if the change was made as part of #2608.

**Comment by sekmiller** [comment]
@pdurbin I did not make any changes to the json export.  Leonid may have changed the file handling and/or attachments.

**Comment by pdurbin** [comment]
@sekmiller ah, yes, in dfcece1 (part of 4.5) I see 'Cleaned up JSON export and import (got rid of the inconsistencies with the "datafile" vs. "dataFile" naming)'

@scolapasta you had some opinions about this, right? You wanted to know if it was an intentional change, I believe. Right now if applications like OSF want to integrate with Dataverse, they need to look for the key `datafile` for Dataverse 4.4 and lower and `dataFile` for Dataverse 4.5 and above. This is suboptimal. Should we duplicate the data in both places in the next release? Should we revert from `dataFile` to `datafile`? It looks like the new code by @felliott now looks in both places.

Perhaps we should assert in the API Guide what the expected JSON should be for various endpoints? That's what GitHub does for their API, such as at https://developer.github.com/v3/issues/assignees/#list-assignees . For the Search API we provide a couple JSON output examples, starting at http://guides.dataverse.org/en/4.5/api/search.html#basic-search-example

**Comment by djbrooke** [comment]
I'm going to close this as this particular issue has been addressed by changes made by CoS. We'll keep this as `dataFile` for now. 

To prevent this happening again, we need to provide version support for our API and build up additional capacity for automated testing. These are called out:

- Versioning our API (#1885)
- Automated tests of our API (#2746)
