### ISSUE TITLE
4.5 requires timers, add to upgrade instructions

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#3336]
Hello,

My in-place upgrades from 4.4 to 4.5 didn't pick up the new dataverse.timerServer=true jvm-option. It's in the Sphinx documentation and the install script will add it to a new installation, but there's not a mention of it in the 4.5 upgrade instructions. I think a note to this effect would be very helpful for your admins.

Thank you,
Donald

**Comment by kcondon** [comment]
Done

**Comment by pdurbin** [comment]
Ever since 4.5 came out when I attempt to run https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-deploy-develop/ I'm getting "EJB Timer Service is not available". My solution has been to ssh into the box and move the "generated" directory aside like this (after stopping Glassfish first):

    mv /usr/local/glassfish4/glassfish/domains/domain1/generated /tmp

This allows the next build (deployment) to complete but then if I come along and trigger **another** build after the successful build it aways fails with the same "EJB Timer Service is not available" error and I have the pleasure of intervening manually again to get deployment working again.

I'm hoping that some sort of fix to the scripts at https://github.com/IQSS/dataverse/tree/develop/scripts/deploy/phoenix.dataverse.org will help. Or maybe there's a better way? @donsizemore if you have any ideas, I'm all ears. Here's an example of a failed build/deployment where you can see the error: https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-deploy-develop/48/console

**Comment by donsizemore** [comment]
Phil, I've started performing
`$ sudo rm -rf /usr/local/glassfish4/glassfish/domains/domain1/generated/
$ sudo rm -rf /usr/local/glassfish4/glassfish/domains/domain1/osgi-cache/felix/`
as a part of any redeployment, upgrade or (recently) downgrade.

Do you just want to add it to your scripts (or am I mis-reading the question)?

**Comment by pdurbin** [comment]
@donsizemore that's exactly what I was thinking a fix or a work around would be and I've just encapsulated this in pull request #3361 which I'm associating with this issue since it's so closely related. I'm reopening this issue and putting it in QA in https://waffle.io/IQSS/dataverse

**Comment by pdurbin** [comment]
@djbrooke and I confirmed that builds 49 and 50 executed just fine after pull request #3361 was merged: https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-deploy-develop/

Once again we can simply click "Build" and it "just works". 😄
