### ISSUE TITLE
Administration Changes to Support rsync

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#3347]
We'll need to make changes at the Installation and the dataverse level to support the new options available for rsync. Two that were discussed were:
- Administrators able to define the file transfers/uploads available (dropbox, rsync, UI)
- Setting the Data Capture Module (#3145) URL in the installation configuration settings

**Comment by pdurbin** [comment]
During the 2016-09-08 SBGrid Sprint Planning meeting ( https://docs.google.com/document/d/1wWSdKUOGA1L7UqFsgF3aOs8_9uyjnVpsPAxk7FObOOI/edit ) this issue was given an effort level of "3" because code has already been written.

We're using `:DataCaptureModuleUrl` as the setting key in the database in the standard way.

With regard to administrators being able to define the file transfers available we have defined an enum called `FileUploadMechanism` on the `Dataset` entity: https://github.com/bmckinney/dataverse-canonical/blob/b280c34fcc231b41cf9e801aff992e3858c17775/src/main/java/edu/harvard/iq/dataverse/Dataset.java#L43 . I'm fine with the approach (I added it) and I think @bmckinney and @pameyer are fine with it as well but during the meeting I got the impression that @scolapasta wanted to weigh in on the design before we commit to this approach so I'm assigning this issue to him, me, and Bill to discuss.

**Comment by pdurbin** [comment]
@bmckinney @djbrooke and I discussed this and we moved it to "Ready" at https://waffle.io/IQSS/dataverse

@bmckinney and I are fine with the approach so I believe the next step is to make a pull request based on the code mentioned above.

**Comment by djbrooke** [comment]
- Is any of the code mentioned above helpful for #3725 or #3724? 
- Can this be closed? 

@pdurbin @pameyer

**Comment by pdurbin** [comment]
@djbrooke this issue is one of eight created last September in our attempt to break #3145 into smaller chunks: https://github.com/IQSS/dataverse/issues/3145#issuecomment-246757258

Yes, the code mentioned above is helpful, especially #3724. There's still an open question of if @scolapasta wants to weight in on the approach before we commit to it, as mentioned at https://github.com/IQSS/dataverse/issues/3347#issuecomment-246699973 . In #3724 this is described as "Binary configuration items (on/off switch), or lists (native/http,dcm/rsync+ssh, etc)? Additional implementation complexity and/or performance of lists vs binary hasn't been evaluated." A decision still needs to be made.

For now I'll link to this issue from #3724.

**Comment by pdurbin** [comment]
I'm closing this because #3724 is done and #3942 is in the works.

**Comment by pdurbin** [comment]
#3348 is still open as well so we can circle back to anything written back above, if necessary.
