### ISSUE TITLE
Viewing files uploaded using rsync

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#3349]

**Comment by pdurbin** [comment]
During the 2016-09-08 SBGrid Sprint Planning meeting ( https://docs.google.com/document/d/1wWSdKUOGA1L7UqFsgF3aOs8_9uyjnVpsPAxk7FObOOI/edit ) this issue was given an effort level of "3" because from my understanding @bmckinney and @pameyer are happy with the status quo in terms of how files are viewed. In the platform they are migrating from ( https://data.sbgrid.org ) users don't have any file view at all. Users get instructions on how to download the files instead (see https://data.sbgrid.org/dataset/1/ ).

If we are **not** ok with the status quo someone with a better memory of this meeting should fill in the details on what the scope of work is exactly, what the "3" represents. @djbrooke I'm actually going to assign this to you to help figure out. Thanks. I'll assign myself as well.

**Comment by djbrooke** [comment]
Let's keep the status quo as it will make SBGrid users happy and will not require any custom handling that differs rsync files from other files. Can this issue be closed?

**Comment by djbrooke** [comment]
Closing in favor of #2249.

**Comment by pdurbin** [comment]
As @pameyer pointed out, #3247 is also related.
