### ISSUE TITLE
Custom File Handling - rsync files

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#3351]
Certain buttons or other options may be disabled for files added to dataverse using rsync.

**Comment by pdurbin** [comment]
During the 2016-09-08 SBGrid Sprint Planning meeting ( https://docs.google.com/document/d/1wWSdKUOGA1L7UqFsgF3aOs8_9uyjnVpsPAxk7FObOOI/edit ) this issue was given an effort level of "5" but I feel like this issue is highly intertwined with #3350 with regard to "download all as zip".

This issue raises several concerns I expressed at the 2016-09-07 demo because those buttons we're talking about hiding do very important things in the system such as versioning of files and restricting files. I called this "Tradeoffs" during the talk.

**Comment by pdurbin** [comment]
@bmckinney @scolapasta @djbrooke and I discussed this issue today but decided to leave it in the backlog for now. We still need to figure out what the plan is for changing the code.

**Comment by djbrooke** [comment]
Closing. Changes will be made in #3348 or in issue spawned from there.

**Comment by pdurbin** [comment]
All the non-restricting of files is part of #3776 as well.
