### ISSUE TITLE
Allow customizable copyright footer

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#3379]
Thu-Mai would like for us to be able to protect the Odum and UNC names and logos, in addition to anything that doesn't have established user terms. This may better be tacked on to issue #2905.

**Comment by pdurbin** [comment]
#2003 is related and currently has a milestone of 4.6. When @tdilauro visited a few months back he talked about how he tweaked the footer to add information that presumably currently lives in their DVN 3.x instance at https://archive.data.jhu.edu/dvn/ (he also added a Johns Hopkins banner to the top, he said).

**Comment by pdurbin** [comment]
I made a minimal pull request at #3379 to show the part of the code that needs to change. Docs and tests need to be added.

**Comment by pdurbin** [comment]
@mheppler and I discussed 242080d this morning and there a few things we'd like to address:

- Roll in a fix for #2905 to make the copyright date dynamic
- Have "Copyright © 2016, " be system generated but have "The President & Fellows of Harvard College" be configurable.
- For performance use `settingsWrapper.get` rather than `systemConfig.footerCopyright`
- Document the new setting.

**Comment by djbrooke** [comment]
@pdurbin @mheppler

May we just do the final bullet and call this done instead of expanding this?

**Comment by pdurbin** [comment]
I just rolled the dynamic copyright year issue (#2905) into my pull request for this issue (#3380) since they are so closely related. @djbrooke indicated that if the fixes are trivial they could be given a milestone of 4.5.1, which I just did. I also documented the setting in the installation guide.

I didn't address the performance concern. I'm not actually sure if settingsWrapper.get performance stuff is compatible with how I'm doing things. @scolapasta would know.

At https://waffle.io/IQSS/dataverse I'm moving this to QA since I'm happy with the solutions.

**Comment by mheppler** [comment]
Discussed with @pdurbin and @djbrooke on moving the dynamic copyright features developed as part of this issue, into issue #2905 and send that to QA for 4.5.1.

Then, this issue will remain open for a later release, so that we can gather additional input from other installations on how they'd like to further customize the footer with custom text, images, layout, etc.

**Comment by pdurbin** [comment]
@mheppler sounds fine. I'll unassign myself from this one so anyone can pick it up to work on logos, etc. Pull request #3380 only handles changing the text (so it doesn't have "Harvard" in it).

**Comment by mheppler** [comment]
This issue is being closed in favor of a new issue, so that it can be easily tracked through development.
- *Footer Customization - Logo, Name, Nav links for About and Guides #3638*

Thank you for your input @donsizemore! Please check those new issues to make sure that we are covering your requested features.
