### ISSUE TITLE
Embargo Period for Releasing Datasets & Dataverses

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#343]
---

Author Name: **Elizabeth Quigley** (@eaquigley)
Original Redmine Issue: 3758, https://redmine.hmdc.harvard.edu/issues/3758
Original Date: 2014-03-25
Original Assignee: Michael Bar-Sinai

---

Ability to set a certain time period during the creation of a Dataverse or dataset, i.e.-one week, two weeks, before it is released.
[Eleni: Could we add a notification in there so that people can be made aware when the dataset is available? Or would this be unreleased so no one else would see it till the embargo ends?]

**Comment by pdurbin** [comment]
#934 is related.

**Comment by pdurbin** [comment]
There's some nice discussion about the need for an embargo feature at https://groups.google.com/d/msg/dataverse-community/tw3qLvS6POo/jPRxnWbyAAAJ . @philippconzett since you kicked off that thread, you would be very welcome to create a fresh GitHub issue explaining how you'd like an embargo feature to work from your point of view. This issue as it stands is a bit light on requirements.

**Comment by philippconzett** [comment]
Thanks, Phil. I have now create a new issue about the embargo feature; cf. issue [#4052](https://github.com/IQSS/dataverse/issues/4052).

Best,
Philipp

**Comment by pdurbin** [comment]
@philippconzett thanks! #4052 has a ton more detail about embargo requirements so I'm closing this issue in favor of that one.
