### ISSUE TITLE
Dataverse: script to verify WorldMap links are valid

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3480]
Dataset metadata will contain links to WorldMap layers.

Verify that the WorldMap links are valid--e.g., that the layers still exist.

Run this check via GeoConnect:
- [ ] Get all map layer metadata links via API call
  - [ ] Add Dataverse API call to return list of ```MapLayerMetadata``` objects. Started in f0cec55.
- [ ] Check against WorldMap, delete non-existent links
- [x] ~~Run reverse check.  For Layers with DataverseInfo objects, make sure Dataverse still has the file/dataset.  Delete the WorldMap _DataverseInfo object_ but not the Layer itself.~~
  - should rarely happen

---

### Notes

- New API endpoint needed in *Dataverse* codebase
- Originally geoconnect issue: IQSS/geoconnect#12

**Comment by djbrooke** [comment]
We discussed this in the Sprint Planning meeting yesterday. We decided on the following approach:

- We'll add an API endpoint to Dataverse
- We'll add a script to run in Geoconnect to verify the mapping in Dataverse (using the new endpoint) and the the endpoint in Worldmap (existing endpoint)
- We'll Update the Geoconnect documentation to inform users what happens when a mapping is deleted

**Comment by raprasad** [comment]
Question in gist for tomorrow:  https://gist.github.com/raprasad/b69dcd0549e78837cb29b90e07244b7b

**Comment by pdurbin** [comment]
I'd like to point out that from the WorldMap side, when you delete a map (WorldMap calls it a "layer"), you get no indication that you're leaving cruft behind in Dataverse. This is what the WorldMap user sees:

![screen shot 2017-03-24 at 9 49 54 am](https://cloud.githubusercontent.com/assets/21006/24296971/86fe7594-1077-11e7-9af9-9451429f5774.png)

The cruft left behind in Dataverse is the "Explore" button. When anyone comes along and clicks the Explore button...

![screen shot 2017-03-24 at 9 53 33 am](https://cloud.githubusercontent.com/assets/21006/24297103/e13f8d0e-1077-11e7-9e29-b021130a06e8.png)

... they see "Page Not Found" on the WorldMap side:

![screen shot 2017-03-24 at 9 54 54 am](https://cloud.githubusercontent.com/assets/21006/24297122/f5674858-1077-11e7-8f21-fbcdad970b5e.png)

This issue is about deleting the cruft from Dataverse, specifically the `MapLayerMetadata` entry in the Dataverse database, so that the "Explore" button goes away when it has been detected (nightly or whatever) that the map/layer in WorldMap no longer exists.

**Comment by pdurbin** [comment]
I just opened https://github.com/cga-harvard/cga-worldmap/issues/214 asking for the WorldMap "delete" interface to say something like, "this layer is in use by a dataset with a published DOI."

**Comment by pdurbin** [comment]
This morning @scolapasta @raprasad and I talked about a SQL update to the `maplayermetadata` table. We're adding `lastverifiedstatus` and `lastverifiedtime`, which I included it in 29fb6e2.

**Comment by pdurbin** [comment]
@scolapasta @raprasad I just made pull request #3721 in an attempt to rough out the approach we agreed to this morning. There's still cleanup to do but I'm moving this to Code Review in https://waffle.io/IQSS/dataverse

**Comment by raprasad** [comment]
for anyone testing this, there is quick script here:

https://github.com/IQSS/dataverse-helper-scripts/blob/master/src/issue_3480/test_3480.py

**Comment by pdurbin** [comment]
Ok, as of 2ca06dc I believe I'm done with the code. That's where I documented the 5 new API endpoints and explained what a sysadmin should do to clean up the dead links. Endpoints have been secured, and bugs have been fixed.

@scolapasta indicated he's fine either way, truly, with the names of the database fields I added or with changing them to `lastcheckedtime` and `lastcheckedstatus`. I just kept them as-as. There's good javadoc anyway.

Moving to Code Review in https://waffle.io/IQSS/dataverse

**Comment by pdurbin** [comment]
In 06e97c6 I implemented the changes @scolapasta and I agreed to. Heads up to @raprasad that the implementation is more simple. Moving to QA at https://waffle.io/IQSS/dataverse

@kcondon I added the "per id" check you requested. A good starting point will be the page I added to the Admin Guide: https://github.com/IQSS/dataverse/blob/06e97c67b839a3044c53a32836e2515091019409/doc/sphinx-guides/source/admin/geoconnect-worldmap.rst

**Comment by pdurbin** [comment]
@kcondon also, please note that scripts/database/upgrades/upgrade_v4.6.1_to_v4.6.2.sql has been updated

**Comment by kcondon** [comment]
After deleting map on Worldmap side, there is stale data on Dataverse, ie. the explore button, but also stale data on GeoConnect. This ticket does address the Dataverse stale data but trying to remap the deleted map from the Dataverse side fails for shape files and has a workaround for tabular data.

**Comment by raprasad** [comment]
@kcondon I put in a fix for stale *tabular* file data.  The updated geoconnect code is available via dvn-build.  note: they're in the process of restarting worldmap which is down right no.

**Comment by raprasad** [comment]
Geoconnect pull request:  https://github.com/IQSS/geoconnect/pull/125

**Comment by pdurbin** [comment]
I just reviewed https://github.com/IQSS/geoconnect/pull/125 and it looks good so I'm sending this issue to QA at https://waffle.io/IQSS/dataverse

@kcondon I'd say you can go ahead and merge pull request #3721  into the Dataverse code base because the branch (`3480-worldmap-links`) hasn't changed since you tested it yesterday and @raprasad and I are not planning on touching it. Basically, further improvements are being worked out in the geoconnect code base at this point.

**Comment by kcondon** [comment]
@pdurbin I'd still like to test it again, thanks for the heads up.
