### ISSUE TITLE
Tooltips: Implement different method for displaying URLs in hover tooltips

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#3501]
The URLs in the tooltips for some elements in the dataset metadata blocks can't be clicked on. We should use another method for displaying those URLs.

![screen shot 2016-12-01 at 5 20 07 pm](https://cloud.githubusercontent.com/assets/18374574/20816958/ff4e1dd4-b7f2-11e6-92eb-b98bf1516875.png)

**Comment by jggautier** [comment]
Linking related issue: #3500

**Comment by pdurbin** [comment]
Related: #3925

**Comment by jggautier** [comment]
I'm going to close this issue. This is the only tooltip with a URL we expect people to click on, and it would be much better if people could choose terms from that controlled vocabulary right from within the application, which other issues cover in various ways: #1815, #3107, etc.

**Comment by pdurbin** [comment]
Pull request #6434 contains a solution used in Make Data Count for #6209 to have a link in the tooltip. Note that the behavior is a little different. Usually we roll over tool tips to see them. For the Make Data Count one, you click it to get the popup to come up and it stays up until you click elsewhere. Otherwise you can't click the link. You can play around with this on datasets at https://data.qdr.syr.edu where Make Data Count is enabled. It looks like this (I hovered over the link to make it blue):

![Screen Shot 2021-12-02 at 2 36 32 PM](https://user-images.githubusercontent.com/21006/144490935-4a1d8910-b30c-4e24-8e88-fcb430663de3.png)
