### ISSUE TITLE
Documentation: When content is wide enough to require horizontal scroll, content scrolls but left nav outline does not.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3577]
Example: Go to Shibboleth section or R/Two Ravens sections, scroll down to where a line is long enough to enable horizontal scrollbar and then scroll horizontally, notice content scrolls on top of nav outline block on left. If you scroll horizontally when such a line is not present (headers seem to allow horizontal scrolling due to white space), then both content and nav outline block scroll as a single piece.

http://guides.dataverse.org/en/latest/installation/r-rapache-tworavens.html
http://guides.dataverse.org/en/latest/installation/shibboleth.html

This exists in 4.6 but was found when testing Oauth in 4.6.1.

**Comment by pdurbin** [comment]
@dlmurphy and I just talked about this. Here's how it looks:

![screen shot 2017-06-06 at 2 35 01 pm](https://user-images.githubusercontent.com/21006/26845703-5e212576-4ac5-11e7-82a6-881d7f783241.png)

The cause is a long line of code. To trigger the bug, scroll horizontally.

**Comment by dlmurphy** [comment]
This issue came up today because @bsilverstein95 was trying to use a literal to show a line of code that was long enough to extend the page width. It was impossible for a reader to see the entire length of the line of code without breaking the page, but including any line breaks in that code would break it when the reader copied and pasted it.

**Comment by mheppler** [comment]
Found this writing documentation for #6919, so I found a quick fix and shot off a PR.

The problem was a result of the `::caption::` option for code-block. Remove that option by moving the caption into the page content text, and the scrolling horizontal over the sidenav bug goes away.

**Admin Guide**
- Mail Domain Groups
    - [x] code-block caption, wrote file name into text
**Installation Guide**
- OpenID Connect Login Options
    - [x] code-block caption, wrote file name into text
