### ISSUE TITLE
Guestbook: Count of Guestbook varies from displayed count.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3582]
While troubleshooting a guestbook download issue (RT 245614) I discovered a discrepancy in the number of 
guestbook records from the downloaded files versus the db and the UI.

https://dataverse.harvard.edu/dataverse/CCAFSbaseline
There is only one guestbook defined.

DB and UI agree:
select count(id) from guestbookresponse where guestbook_id=3;
count: 6730 

Download all responses, which includes the default or "no" guestbook shows also shows 5195 for guestbook 3
View responses->Download responses shows 5195

Where did the rest disappear to?

**Comment by jggautier** [comment]
I think the number of responses in the table on the Manage Dataset Guestbooks page

<img width="1150" alt="screen shot 2018-01-07 at 7 20 03 pm" src="https://user-images.githubusercontent.com/18374574/34655929-db965e2c-f3df-11e7-8049-a7e33ac6f757.png">

is not counting responses that are recorded in the "Default" guestbook:

In the table on that page, the number of responses in the [CCAFS Dataverse](https://dataverse.harvard.edu/dataverse/CCAFSbaseline) is 15940 now. When I download the guestbook, the number of responses in the csv is 20802. But when I remove the responses from the "Default" guestbook, there are 15940 left.

The query `select count(id) from guestbookresponse where guestbook_id=3;` matches what's in the table because it's also counting only what's in the CCAFS Dataverse guestbook (guestbook_id=3) but not what's in the default guestbook (guestbook_id=1). (Using a query that searches by dataverse id instead, like [the recursive query in the database queries doc](https://docs.google.com/document/d/1-Y_iUduSxdDNeK1yiGUxe7t-Md7Fy965jp4o4m1XEoE/edit#heading=h.4xk2kirzt0qp), should get the right number.)

So if people need to know the number of "downloads" in their dataverses are they're looking at the table on the Manage Dataset Guestbooks page, maybe that number should include responses from the default guestbook, too.

**Comment by jggautier** [comment]
Just noting that the dataverse in question has a comma in its name, so downloading the guestbooks using Google Chrome won't work. This bug is reported in #3581.

**Comment by jggautier** [comment]
I think that the relationship between the "Guestbooks from Harvard Dataverse" (aka the "default" guestbook) and any guestbooks created for a Dataverse Collection could use some clarification in the UI, e.g. on the guestbook management page.

For example, the guestbook management page at https://dataverse.harvard.edu/manage-guestbooks.xhtml?dataverseId=3679836 doesn't list its user-created guestbook until the checkbox for "Include Guestbooks from Harvard Dataverse" is selected. I think this is pretty confusing, and this confusion might be causing people to think that because no guestbook has been created for the collection, it's not possible to get the information available in the "default" guestbook.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
