### ISSUE TITLE
Provide Download URL for Public Files

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#3584]
If a file has no Terms of Use and there is no guestbook associated with the dataverse, provide a download URL on the file page.

**Comment by pdurbin** [comment]
This issue reminds me a lot of #2416.

**Comment by djbrooke** [comment]
Some tasks coming out of our sprint planning meeting today:

- Determine where this link will appear
- On those files where it is not available, some information should be provided to the user about why it's not there.

**Comment by pdurbin** [comment]
I created pull request #3608 and put it in Code Review at https://waffle.io/IQSS/dataverse

I believe there's an existing bug with the download popu but it's tricky to pull off in the GUI. Here's how:

- Set waiver to non-CC0
- Fill in Terms of Use
- Save Changes
- Click "Edit Terms Requirements" again.
- Change waiver to CC0.
- The Terms of Use are still in the database so they should be respected, perhaps. However, no popup is shown. Perhaps in the case above the Terms of Use should be deleted from the database after the user confirms this is the desire.

Anyway, I found this because the the logic to show the file download URL or not piggybacks off the logic to show the pop or not. @sekmiller and I agreed on this approach. I also wrote a lot of tests. 😄 

Below are some screenshots of how it looks as of a1ebe6e if @mheppler would like to jump in.

![screen shot 2017-01-31 at 1 48 03 pm](https://cloud.githubusercontent.com/assets/21006/22479513/02b74e02-e7bc-11e6-9eb9-fc9240f2a4b5.png)
![screen shot 2017-01-31 at 1 47 52 pm](https://cloud.githubusercontent.com/assets/21006/22479515/02ba882e-e7bc-11e6-89b0-187c9ea904cc.png)

**Comment by mheppler** [comment]
Yes, I will need to address the UI for this feature. Please do not move it to QA until I have had that chance.

**Comment by pdurbin** [comment]
Oh, one wrinkle I'd like to bring up is that **tabular** files that have gone through ingest actually have **multiple** download formats. You can see this in the screenshot below (original vs. tab-delimited vs. RData) or on this live server where I deployed the code: https://dev1.dataverse.org/file.xhtml?fileId=377&version=1.1

Are we fine with just showing the one link under "Download URL" for tabular files?

![50by1000 tab_-_tabular_dataverse_-_2017-02-01_10 08 57](https://cloud.githubusercontent.com/assets/21006/22512428/fc078378-e866-11e6-9bc9-b61fb921347d.png)

**Comment by djbrooke** [comment]
Let's provide only the .tab download for now.

**Comment by sekmiller** [comment]
I would point out that the multiple download types and the detour into guestbook are the main reasons we didn't just put the download url into the page in the first place.

**Comment by djbrooke** [comment]
Note that this issue is only for files without TOU and Guestbook.

**Comment by pdurbin** [comment]
@scolapasta here are the changes you requested:

- eb40c73 - remove todo that's probably not actionable #3325
- c65a0df - versionState should never be null

Anything else before we move this issue to QA?

**Comment by kcondon** [comment]
I'm not seeing the download urls for public files, no guestbook.

**Comment by pdurbin** [comment]
@kcondon it work on my machine. 😄 I just tried it again. I'm probably not understanding what the bug is. I'll probably need a demo.

**Comment by kcondon** [comment]
Link appears in draft then disappears in published version due to following popup rule as proxy for biz rules. Popups do not appear by design in Draft however.

**Comment by pdurbin** [comment]
> Link appears in draft then disappears in published version due to following popup rule as proxy for biz rules. Popups do not appear by design in Draft however.

Good catch. I added a todo in the code for the "disappearing Download URL" scenario described above: ed8e8b5
