### ISSUE TITLE
View File Version Difference Details

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#3593]
breaking out #3241 into smaller stories

This issue is to track the popup for "View Details" between different file versions.

**Comment by mheppler** [comment]
Initial mockup of the file level version details to give development a starting point. We can review and revise the layout as development is able to demo a functional table and we get a chance to look at it in more detail with production data.

<img width="843" alt="screen shot 2017-01-27 at 9 30 11 am" src="https://cloud.githubusercontent.com/assets/687227/22406095/0773cd74-e61a-11e6-9b3d-babbabb0a55a.png">

**Comment by mheppler** [comment]
Mercè has asked about showing additional file version details -- like variables and observation counts for tabular files -- when a file is replaced. Discussed with @landreev @scolapasta @sekmiller  and will review in further detail when this issue is picked up for development.

![screen shot 2017-02-16 at 4 57 33 pm](https://cloud.githubusercontent.com/assets/687227/23043114/3aa53c48-f469-11e6-8115-c2a6d35216a9.png)

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
