### ISSUE TITLE
Support Large Guestbooks

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3609]
This comes up from time to time when a user with a very large guestbook wants to download it but can't. See RT 246137 for an example of a repeating request. So for now this requires us to run a database query and send the results to the user whenever they need updated info.

Please note this is separate from the bug where some guestbooks can be downloaded in FF and Safari but not Chrome ( #3581  ) . At first glance they seem the same but they are not.

**Comment by landreev** [comment]
I'd like to quickly review (with @scolapasta?) the plan for the guestbook-responses page.

**Comment by landreev** [comment]
Going to make a PR and move this into code review. Will add a few more lines here explaining what's been done, how it's supposed to be working now and how to test stuff. 
Will need to review with some specific members of the team whose areas of expertise are affected.

**Comment by landreev** [comment]
@mheppler  passing this to you for a quick prettyfication - thanks!

The 2 new help tips in the bundle are dataset.manageGuestbooks.tip.downloadascsv and dataset.guestbooksResponses.tip.downloadascsv respectively. 

The new display limit logic is in guestbook-responses.xhtml. The default limit is 5000. (*In order to test it in your local build*, with a smaller guestbook, add ":GuestbookResponsesPageDisplayLimit" to your setting table in the database, and set it to some small number.) Let me know if you need anything from me. 

Thanks, to @TaniaSchlatter and you for finding time to review this quickly. Yes, it'll be awesome if we can move into QA today.

**Comment by landreev** [comment]
@dlmurphy The 2 help tip messages I mentioned are the ones shown in blue on these pages: 
(you'll need the dataverseAdmin password)
http://dvn-vm5.hmdc.harvard.edu:8080/manage-guestbooks.xhtml?dataverseId=99
http://dvn-vm5.hmdc.harvard.edu:8080/guestbook-responses.xhtml?dataverseId=99&guestbookId=165

the actual messages in the resource bundle are dataset.manageGuestbooks.tip.downloadascsv and dataset.guestbooksResponses.tip.downloadascsv respectively.

It's very little text; but it's kinda kludgy - and there's probably a better way to say it. The main message that I'm trying communicate is, what you download is going to be a CSV file; this CSV file is importable into Excel, Google Sheets or similar; and that - Excel, etc. - is the recommended way to go, if you want to somehow reorganize this statistics/select specific datasets, files, users, etc. 

The branch is 3609-large-guestbooks. 

Thanks!

**Comment by mheppler** [comment]
Cleaned up layout of various buttons, popups and text in Manage Dataset Guestbook and Guestbook Responses pgs.

@dlmurphy -- help/info and warning text messages are ready for you to review. I have attached a screenshot of the warning msg to help in your review.

@landreev -- I have discovered that the navigation logic for guestbook-responses.xhtml does not check if you are logged in.

![screen shot 2017-08-14 at 11 58 13 am](https://user-images.githubusercontent.com/687227/29280257-816c894a-80e8-11e7-94ce-f8300d672508.png)

**Comment by landreev** [comment]
good catch. (it looks like it's been like this since we introduced the page and nobody noticed). 
fixing...

**Comment by dlmurphy** [comment]
Made minor edits to the following messages in my most recent commit. Here's the updated text, please review for accuracy.

Manage Dataset Guestbooks page: _Click \"Download All Responses\" to download all collected guestbook responses for this dataverse, as a CSV file. To navigate and analyze your collected responses, we recommend importing this CSV file into Excel, Google Sheets or similar software._

View Guestbook Responses page: _Click \"Download Responses\" to download all collected responses for this guestbook, as a CSV file. To navigate and analyze your collected responses, we recommend importing this CSV file into Excel, Google Sheets or similar software._

Warning: _Note: this guestbook has too many responses to display on this page. Only the most recent {0} responses are shown below. Click \"Download Responses\" to download all collected responses ({1} total) as a CSV file._

**Comment by landreev** [comment]
(checked in the fix for unauthorized users; forgot to reference the issue in the checkin. i'm a terrible member of the society, i know)

**Comment by pdurbin** [comment]
I assigned myself to do some code review of pull request #4057 and my first questions are:

- How large is a large guestbook?
- How can one programmatically (or otherwise) create a large guestbook for testing?

Judging from https://help.hmdc.harvard.edu/Ticket/Display.html?id=246137 a large guestbook is 1288 rows (`select * from guestbookresponse where dataset_id=REDACTED;`).

For testing, it'll be easiest to just use a production database.

**Comment by pdurbin** [comment]
As of b05a026 I noticed some "???" next to "Collected Data" when you preview a guestbook:

![screen shot 2017-08-15 at 9 56 52 am](https://user-images.githubusercontent.com/21006/29318983-42d15766-81a0-11e7-8008-186a978b0357.png)

**Comment by mheppler** [comment]
@pdurbin -- good catch, I missed that popup on the dataset pg. I will get a fix in ASAP.

**Comment by pdurbin** [comment]
I wrote a little script in e869900 to help me create two thousand guestbook entries, which I was able to download just fine as of b05a026 from the pull request. Then I went back and tested dd55c08 on the develop branch and I was able to download them there too. I haven't noticed anything objectionable in the pull request apart from a where logging could be reduced. It sounds like @mheppler is going to fix the "???" I found above. @landreev if there's anything specific you want a code reviewer to look for, please let us know. Thanks.

**Comment by pdurbin** [comment]
To do list:

- [ ] fix "???" described above
- [ ] document new setting: `:GuestbookResponsesPageDisplayLimit`

**Comment by landreev** [comment]
@pdurbin 
Answering the question "how large is a large guestbook". These ones are large: 
https://dataverse.harvard.edu/manage-guestbooks.xhtml?dataverseId=99

the one with 150K responses may be the largest we have. "Download All" button on that page will try to download the guestbook entries for the entire dataverse, meaning about 180K responses. You cannot do that in production currently (will get a 500 error), and you cannot download the results for either of these guestbooks. 

I tested my patch with the prod. database on vm5; you can now download the results for these largest guestbooks in fairly reasonable time. 

As for the 1288 rows - note that that was the result of the query that Kevin ran for them *on one specific dataset*. The manage-guestbooks and guestbook-results pages operate on entire dataverses.

**Comment by landreev** [comment]
Summary of the changes, for QA: 

The download-as-CSV functionality has been optimized, for both the "download all (responses for the dataverse)" and "download the results for the given dataverse and guestbook"; on the manage-guestbooks and guestbook-results pages, respectively; 

Added help tip text to both pages that explains that the downloaded results are going to be in CSV; that they are importable into Excel/Google Sheets; and encouraging them to use this method if they need to further reorganize the results and/or select the results for specific datasets, files, etc.

Fixed the filename for the download function (it was getting chopped on the first space in the name of the dataverse, losing the ".csv" extension in the process). 

Also, for very large guestbooks (for example: https://dataverse.harvard.edu/guestbook-responses.xhtml?dataverseId=99&guestbookId=9), with the current implementation you cannot even get to the "download button". The page will take a long time to load, then finally fail with a 500. That is because the current implementation tries to *display* all the guestbook entries on the page as well. Part of the failure is because the retrieval was not very efficient. But even with that optimized, loading 150K entries on the page is still not a good idea: It will take a long time for the browser to render, no matter what you do; and it's probably not very useful to a user either. 
So the agreed upon solution was to add a configurable limit on how many entries to show. By default, only the most recent 5000 entries are shown (in reverse chronological order); with a message explaining what's going on. The 5000 is a somewhat arbitrary number, but the page is usable with that many entries (takes some seconds to load). The limit is configurable as a standard Dataverse setting (documented in the Configuration->Database Settings section of the guide).
