### ISSUE TITLE
Customizable dataverse names

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#3611]
When a new repository is created (whether is the root repository/Dataverse installation or a sub-repository formerly called sub-dataverse) the user/admin can enter any name for the repository. For example, the root repository in the Harvard installation will still be called "Harvard Dataverse". However, the help text should encourage to provide a repository name that identifies well that repository and doesn't necessarily add "Dataverse" as part of the name. For example, the "Murray Research Archive" doesn't need Dataverse at the end, or "Merce Crosas Datasets" or "Merce Crosas Lab Data".

**Comment by djbrooke** [comment]
We attempted to estimate this on 2/1 but were unable to do so. We need to revisit this to determine:

- What the names would change to (would we just remove Dataverse?)
- How we would message this to users

**Comment by djbrooke** [comment]
- Dataverse would populated, but editable

**Comment by philippconzett** [comment]
As someone mentioned earlier on Dataverse Google Group, for multi-institutional installations it is quite essential to be able to display the sub-dataverse name in the dataset reference. We are now running a multi-institutional test installation. In addition we have one operative thematic sub-dataverse. So, I hope that this is what is meant by "Customizable dataverse names" in the 4.7 point on the roadmap. We also support to drop "Dataverse" as part of the name. In our case, this would make the names of our dataverses less cumbersome, e.g. UiT Open Research Data Repository instead of UiT Open Research Data Dataverse; The Tromsø Repository of Language and Linguistics instead of The Tromsø Repository of Language and Linguistics Dataverse.

Best,
Philipp

**Comment by pdurbin** [comment]
@philippconzett please see comments from @jggautier at https://groups.google.com/d/msg/dataverse-community/A2XFIKqnsTA/qTuHN2XUAgAJ where he tries to differentiate between this issue and #2297.

@philippconzett also, when you say "dataset reference" I think you mean what we call a "citation" for a dataset. Does that sound right? The citation looks like this:

## The citation on a dataset "search card":

![screen shot 2017-03-23 at 1 51 53 pm](https://cloud.githubusercontent.com/assets/21006/24262261/ee4224ba-0fcf-11e7-9d64-37a4c57321ab.png)

## The citation on a dataset page:

![screen shot 2017-03-23 at 1 53 02 pm](https://cloud.githubusercontent.com/assets/21006/24262325/12b11b26-0fd0-11e7-87a9-e1d6fedb632a.png)

#2297 is much more about the citation than this issue.

**Comment by pdurbin** [comment]
I just made pull request #3880 and discussed it with @mheppler who volunteered to do code review and make any other tweaks. I **think** I found all the places we needed to change, which I listed in 6375f9e as the following:

- header
- breadcrumbs
- search cards
- in-app notifications
- widgets footer
- MyData cards

I also discussed the SQL upgrade script I added at `scripts/database/upgrades/upgrade_v4.6.2_to_v4.7.sql` with @kcondon and we agreed that while Harvard Dataverse wants to append " Dataverse" to the `name` column in the `dataverse` table to preserve the names of the dataverses as they look in production, such as "Harvard Dataverse" and "Murray Research Archive Dataverse", other installations may not want this behavior so in the script the `UPDATE` statement is commented out with a note about its purpose, which we should also mention in the release notes. Also in the release notes we should mention that reindexing is required because the citation on the search cards come from Solr.

@dlmurphy heads up that I took a quick look at the User Guide but I don't think any changes are necessary. You're welcome to take a look.

**Comment by pdurbin** [comment]
For the curious, here's how the app looks as of a517e18:

![spruce_-_2017-06-02_14 30 03](https://cloud.githubusercontent.com/assets/21006/26739521/1aebff7e-47a0-11e7-9846-1ae7c7d0a937.png)

**Comment by pdurbin** [comment]
The status of this issue is that as of 55e5053 I'm happy with the code. I'm slightly concerned that some URLs that appear in plain text emails will break because I'm seeing `(view at {1})` rather than `(view at {1} )` with a space to prevent the URL from breaking. I'm not sure what the behavior is of the common email clients out there.

@bsilverstein95 plans to increase the code coverage in `MailUtil.java`. With or without that improvement, this issue is ready for Code Review, so I'll move it along at https://waffle.io/IQSS/dataverse

Note that the pull request () includes some fixes for #2710 but not a complete fix since I believe @shlake wants complete control over the messaging she sends to her users. The focus for this issue is to take the root dataverse name and call the support team "LibraScholar Support" instead of "Dataverse Support". So the name is take from the root dataverse rather than being hard coded as "Dataverse Support". Even this can be overridden via the `:SystemEmail` setting when you supply an optional string for the email address.

**Comment by pdurbin** [comment]
@landreev gave a positive review of pull request #3880 which was enough for me to move this issue to QA. @mheppler had noticed a few remaining instances of "Dataverse Support", which I fixed at eec5a2e.

**Comment by kcondon** [comment]
Issues:
-Dataverse name initial text should be real, not watermark, per G.D./M.C.
-

**Comment by kcondon** [comment]
Issues:
-Dataverse name initial text should be real, not watermark, per G.D./M.C.
-

**Comment by pdurbin** [comment]
> Dataverse name initial text should be real, not watermark, per G.D./M.C.

@kcondon @scolapasta @mheppler fixed in 4f131f0

**Comment by pdurbin** [comment]
The Dataverse for Android app was appending "Dataverse" to dataverse names in search results. I just fixed this in https://github.com/IQSS/dataverse-android/commit/37b0e473f53da48654eac1ebb4bd785285c9cc00 .
