### ISSUE TITLE
adminEmail field invalid in OAI-PMH Identify response

### ISSUE THREAD

**Issue by tdilauro** [IQSS/dataverse#3619]
Unless the _:SystemEmail_ setting contains only a mailbox addr-spec (just the address, no spaces or angle brackets), the Dataverse 4 OAI-PMH provider will return an invalid value for the _adminEmail_ field, since that field should not contain a mailbox display name.

For example, the sample command in the [:SystemEmail section](http://guides.dataverse.org/en/4.6/installation/config.html#systememail) of the Configuration section of the Installation Guide:
> curl -X PUT -d "Support \<support@example.edu>" http://localhost:8080/api/admin/settings/:SystemEmail

would result in this error.

Ideally, the OAI-PMH provider code would check for a value ending in "\<.\*>" and, if present, emit only the string between the angle brackets (i.e., like to sed -e 's/^[^<]*<\\([^>]\*\\)>$/\1/ ').

**Comment by pdurbin** [comment]
Ah, `.withAdminEmail(settingsService.getValueForKey(SettingsServiceBean.Key.SystemEmail))` at https://github.com/IQSS/dataverse/blob/v4.6/src/main/java/edu/harvard/iq/dataverse/harvest/server/web/servlet/OAIServlet.java#L186 should probably call `parseSystemAddress` at https://github.com/IQSS/dataverse/blob/v4.6/src/main/java/edu/harvard/iq/dataverse/util/MailUtil.java#L12 instead to get back a `InternetAddress` object from which just the email address can be extracted for use in an OAI-PMH context.

**Comment by pdurbin** [comment]
As of 4.7 we are further promoting the addition of a name to the email address. For now, see "Branding Your Installation" at https://github.com/IQSS/dataverse/blob/a7242a92eb5173977fff6eadc984ce22ec55f3ba/doc/sphinx-guides/source/installation/config.rst#id75

**Comment by pdurbin** [comment]
I just noticed the post by @poikilotherm about Hacktoberfest ( https://hacktoberfest.digitalocean.com ) at https://groups.google.com/d/msg/dataverse-community/ootwCQL-4K4/00QO3__8CQAJ and the fact that he started using the label "hacktoberfest" over at https://github.com/IQSS/dataverse-kubernetes/issues

He's inviting IQSS to use this label as well and this issue seems to meet "Choose issues that have a well-defined scope and are self-contained" guidance at https://hacktoberfest.digitalocean.com/details

First, it's easy to see that Harvard Dataverse is returning an invalid response (red ERROR at the bottom of the screenshot below) by going to http://oval.base-search.net and entering https://dataverse.harvard.edu/oai

![Screen Shot 2019-10-01 at 11 46 30 AM](https://user-images.githubusercontent.com/21006/65978606-fff89880-e441-11e9-9f58-5f19382163da.png)

I **think** the fix could be a one line change (plus adding an import statement). Maybe something like the untested diff below:

```
$ git diff
diff --git a/src/main/java/edu/harvard/iq/dataverse/harvest/server/web/servlet/OAIServlet.java b/src/main/java/edu/harvard/iq/dataverse/harvest/server/web/servlet/OAIServlet.java
index 555e5a996..8b3fe0cdd 100644
--- a/src/main/java/edu/harvard/iq/dataverse/harvest/server/web/servlet/OAIServlet.java
+++ b/src/main/java/edu/harvard/iq/dataverse/harvest/server/web/servlet/OAIServlet.java
@@ -38,6 +38,7 @@ import edu.harvard.iq.dataverse.harvest.server.xoai.XitemRepository;
 import edu.harvard.iq.dataverse.harvest.server.xoai.XsetRepository;
 import edu.harvard.iq.dataverse.harvest.server.xoai.XlistRecords;
 import edu.harvard.iq.dataverse.settings.SettingsServiceBean;
+import edu.harvard.iq.dataverse.util.MailUtil;
 import edu.harvard.iq.dataverse.util.SystemConfig;
 import org.apache.commons.lang.StringUtils;
 
@@ -184,7 +185,7 @@ public class OAIServlet extends HttpServlet {
                 .withBaseUrl(systemConfig.getDataverseSiteUrl()+"/oai")
                 .withCompression("gzip")        // ?
                 .withCompression("deflate")     // ?
-                .withAdminEmail(settingsService.getValueForKey(SettingsServiceBean.Key.SystemEmail))
+                .withAdminEmail(MailUtil.parseSystemAddress(settingsService.getValueForKey(SettingsServiceBean.Key.SystemEmail)).getAddress())
                 .withDeleteMethod(DeletedRecord.TRANSIENT)
                 .withGranularity(Granularity.Second)
                 .withMaxListIdentifiers(100)
```

The starting point for anyone picking this up should be the Dataverse Developer Guide at http://guides.dataverse.org/en/4.16/developers/index.html

I'm happy to answer questions here or at http://chat.dataverse.org or at https://groups.google.com/forum/#!forum/dataverse-dev

I'd like to note that this bug affects on just Harvard Dataverse. It was also reported here: https://github.com/ualbertalib/dataverse/issues/63

**Comment by pdurbin** [comment]
This bug was also noticed by @shlake at https://groups.google.com/d/msg/dataverse-community/C-HLdPQwf70/I9SgmsPECAAJ

**Comment by pdurbin** [comment]
I just made pull request #6513 to fix this.

**Comment by pdurbin** [comment]
Shoot. I made a mistake in pull request #6513 and now we're seeing errors in "develop" at

https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/lastBuild/edu.harvard.iq$dataverse/testReport/edu.harvard.iq.dataverse.api/HarvestingServerIT/testOaiFunctionality/

![Screen Shot 2020-01-17 at 9 41 15 AM](https://user-images.githubusercontent.com/21006/72620596-9c6d7a80-390d-11ea-9ce8-5478d4aa9a9c.png)

I'm reopening this issue and will submit another pull request.

**Comment by pdurbin** [comment]
I just made pull request #6538 to fix the error above. A null pointer exception was being thrown.
