### ISSUE TITLE
invalid schema and metadataNamespace fields in OAI-PMH ListMetadataFormats response

### ISSUE THREAD

**Issue by tdilauro** [IQSS/dataverse#3621]
The _metadataFormat_ chunk for prefix _dataverse_json_ looks like:
```
<metadataFormat>
   <metadataPrefix>dataverse_json</metadataPrefix>
   <schema>JSON schema pending</schema>
   <metadataNamespace>Custom Dataverse metadata in JSON format (Dataverse4 to Dataverse4 harvesting only)</metadataNamespace>
</metadataFormat>
```
The value for  _metadataNamespace_ should be a URI and the value for _schema_ should be a URL, but any URI will validate. In the short term, it might be reasonable to make up values in the http://dataverse.org namespace, so that the responses comply with the [OAI-PMH 2.0 schema](http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd).

**Comment by pdurbin** [comment]
Another place where I thought about using a namespace for Dataverse was in the context of SWORD. I ended up using `new QName(UriRegistry.SWORD_STATE...` instead to yield `<dataverseHasBeenReleased xmlns="http://purl.org/net/sword/terms/state">true</dataverseHasBeenReleased>` but at the time I was wondering if we should have a URL under purl or under dataverse.org, like @tdilauro suggests.

**Comment by pdurbin** [comment]
These days we're using URLs like https://dataverse.org/schema/citation/... in our experimental Semantic Metadata API.

See this pull request for examples:

- #8592

**Comment by sekmiller** [comment]
@tdilauro we are reviewing old tickets related to Harvesting.  I was hoping that you could answer the following questions to help us determine if this issue is still open and if so, how to go about fixing it. Thanks!

What steps does it take to reproduce the issue? 

	•	When does this issue occur? 
	•	Which page(s) does it occurs on? 
	•	What happens? 
	•	To whom does it occur (all users, curators, superusers)? 
	•	What did you expect to happen? 

Which version of Dataverse are you using?

**Comment by sekmiller** [comment]
I've reached out to the author of the ticket for more information, but it's possible that this is not applicable to DV 5.x since there's a reference in the original post to "(Dataverse4 to Dataverse4 harvesting only)"

It's difficult to estimate the effort without additional information, as I have not been able to reproduce the error state.
<metadataFormat>
   <metadataPrefix>dataverse_json</metadataPrefix>
   <schema>JSON schema pending</schema>
   <metadataNamespace>Custom Dataverse metadata in JSON format (Dataverse4 to Dataverse4 harvesting only)</metadataNamespace>
</metadataFormat>

**Comment by poikilotherm** [comment]
Sorry to chime in, stumbled over this one.

Looking at https://demo.dataverse.org/oai?verb=ListMetadataFormats, it looks like we still are sending out that information.

It should be a very simple fix, looking at https://github.com/IQSS/dataverse/blob/8b9d7f5f45d87f96f46b382f52dec6485a6f9e8e/src/main/java/edu/harvard/iq/dataverse/harvest/server/web/servlet/OAIServlet.java#L168-L174 and https://github.com/IQSS/dataverse/blob/8b9d7f5f45d87f96f46b382f52dec6485a6f9e8e/src/main/java/edu/harvard/iq/dataverse/harvest/server/web/servlet/OAIServlet.java#L100.

**Comment by sekmiller** [comment]
Thanks, Oliver.

**Comment by mreekie** [comment]
sizing: This is part of the OAI servlet. This could be possibly just changing static strings. There are two strings.We should put it in the bundle. This will not be coding. We just need to decide how to change the string to make it more appropriate.
This seems trivial so sized low

**Comment by mreekie** [comment]
Daily
- Originally we thought this would be just adding a URL to the metadata namespace.
- We don't have the same setup for the JSON schema however.
- We will need to make a sample, add it to the environment, and add the URL here.
- This impacts the size of this, possibly significantly.
