### ISSUE TITLE
File Replace: the UNF of the version doesn't get recalculated, when replacing a tabular file with a non-tabular.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3625]
Found using new data integrity endpoint, thanks Phil!

If I use the new file replace feature to replace a tabular file with non-tabular file, ie. .txt file, the UNF remains in the citation when it shouldn't and gets picked up by the data integrity endpoint.

If the file is replaced by a different tabular file the UNF is recalculated.

Putting in v4.6.1 for consideration

**Comment by landreev** [comment]
created a pull request: https://github.com/IQSS/dataverse/pull/3664

**Comment by landreev** [comment]
@kcondon 
Notes on QA for this issue: 
The fix is very straightforward. But since this has to do with UNFs, it needs to be tested extra carefully. I tried to test all sorts of different scenarios - for example, replacing 1 of many tabular files with a non-tabular, making sure the UNF goes to what it should be for the remaining files; replacing the single tabular file with a non-tabular - making sure the UNF changes to null. Also, like with pretty much everything else all the test scenarios have to be tried *separately*, once on a published dataset with no drafts, and once on a published dataset with a draft version already existing... Please re-test all these, and whatever other scenarios you can think of, in case I still missed anything...
