### ISSUE TITLE
Edit Dataverse: Validate all fields 

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#364]
---

Author Name: **Kevin Condon** (@kcondon)
Original Redmine Issue: 3779, https://redmine.hmdc.harvard.edu/issues/3779
Original Date: 2014-03-26
Original Assignee: Steve Kraffmiller

---

Validated all fields.

**Comment by kcondon** [comment]
OK, other issues aside, basic validation is in place. Email validation is only intended to be basic, structural, rather than comprehensive. 

Alias as a number is logged in another ticket.
Duplicate ids are flagged and invalid chars are too.
Can create duplicate dv names. I know this has come up in the past but not sure if we decided anything, will check. 

Closing this ticket.
