### ISSUE TITLE
geoconnect documentation guide

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3643]
The guide should include some of the info in the geconnect wiki:

  - See links on the sidebar:  https://github.com/iqss/geoconnect/wiki

There's a diagram at https://github.com/IQSS/dataverse/issues/3495#issuecomment-291612958

**Comment by raprasad** [comment]
Add this gist info about switching geoconnect servers:

https://gist.github.com/raprasad/4f65e67a392e4ec0b3975a0b3597627a

**Comment by pdurbin** [comment]
I just discovered that there is a ton of end user documentation already at http://worldmap.harvard.edu/static/docs/WorldMap_Help_en.pdf which is linked from http://worldmap.harvard.edu as "Need Help?" Here's a screenshot:

![screen shot 2017-04-11 at 12 42 48 pm](https://cloud.githubusercontent.com/assets/21006/24920253/91e5b5e4-1eb4-11e7-84c6-a3d9167644b9.png)

We should at least link to this resource. Right now http://guides.dataverse.org/en/4.6.1/user/data-exploration/worldmap.html is quite sparse and there are no screenshots.

**Comment by dlmurphy** [comment]
@raprasad The gist info you linked in your earlier comment seems like it'd fit more in the Installation Guide than the User Guide. Does this ticket include both, or am I focusing only on the User Guide?

**Comment by mheppler** [comment]
Recommendations from @raprasad and @pdurbin to include links to:

- https://github.com/IQSS/geoconnect/blob/master/heroku_setup.md (Installation)
- https://github.com/IQSS/geoconnect/blob/master/local_setup.md (Developer)

**Comment by mheppler** [comment]
Added Geoconnect info to Admin, Developers and Installation guides. Reviewing with team.

**Comment by dlmurphy** [comment]
Added user guide for GeoConnect. Awaiting review by @raprasad to ensure that I got all the technical details correct.

**Comment by dlmurphy** [comment]
Just proofread the Admin, Developer, and Installation guides. Lookin' good!

**Comment by pdurbin** [comment]
Here's the branch: https://github.com/IQSS/dataverse/compare/3643-geoconnect-guide

**Comment by raprasad** [comment]
Notes for admin, installation, and developer guides:  https://gist.github.com/raprasad/a0bf36cd08ece1b282eb14ce0ba2a9b2

**Comment by raprasad** [comment]
Note for user guide: https://gist.github.com/raprasad/8c34c6ee8b5c5bf5e227747775341e78

**Comment by pdurbin** [comment]
I just made some improvements in aea9ccf and left a review in pull request #3792 but I'll repeat the feedback here.

Great work. Much improved from what's in production now.

## User Guide

What percentage of users are going to be viewing maps versus creating them? My guess is that more people will be viewing maps since you don't even need to create a Dataverse account to view a map. You just click the button on the dataset or file page. Given this, before we even talk about creating maps, can we have a short section on viewing maps?

Maybe some tips on finding maps to look at as well. 

## Admin Guide

In the Geoconnect README we say, "You should wait until the WorldMap rewrite is complete before considering installing Geoconnect." Should we explain on this page that people installing Dataverse are welcome to use the two servers below that are hosted by Harvard?

## Dev Guide

All of this detail here and below about Geoconnect is great but I'm thinking we should have a separate page for it. This page is getting long and the focus should be about setting up a development environment, not a relatively deep dive into a specific feature. I would suggest following the pattern established by UNF, which is even split into multiple pages:

- http://guides.dataverse.org/en/4.6.1/developers/unf/index.html
  - http://guides.dataverse.org/en/4.6.1/developers/unf/unf-v3.html
  - http://guides.dataverse.org/en/4.6.1/developers/unf/unf-v5.html
  - http://guides.dataverse.org/en/4.6.1/developers/unf/unf-v6.html

I don't think we want all that detail about UNF on this "Development Environment" page.

**Comment by pdurbin** [comment]
I ran a build so you can see my changes immediately at http://guides.dataverse.org/en/3643-geoconnect-guide/user/data-exploration/worldmap.html but builds continue to run every hour.

**Comment by mheppler** [comment]
Revisions to Geoconnect documentation in Developer Guide, moved most info into new Geospatial Data pg.

**Comment by pdurbin** [comment]
@dlmurphy thanks for corresponding with @bglewis about the WorldMap PDF at https://github.com/cga-harvard/cga-worldmap/issues/227
