### ISSUE TITLE
file.xhtml restrict/Unrestrict not working after publish

### ISSUE THREAD

**Issue by kevinworthington** [IQSS/dataverse#3653]
From the file page, if a dataset owner attempts to restrict a file, the action doesn't take effect. This seems to only happen after a dataset has been published.

It seems the fix will simply require a change event from being triggered as occurs when setting a file to restricted from the dataset.xhtml page.

**Comment by pdurbin** [comment]
@kevinworthington thanks for the bug report. Can you please tell me which version of Dataverse you're running?

**Comment by kevinworthington** [comment]
This issue was noticed with v. 4.6

**Comment by pdurbin** [comment]
I just suggested at https://github.com/IQSS/dataverse/issues/3776#issuecomment-310650312 that we re-test this issue when #3776 hits QA.

**Comment by jggautier** [comment]
In Dataverse 4.13, this bug seems to be fixed for restricting and unrestricting files from the file page:
- In a published dataset, go to file page of a file that is not restricted
- Click Edit > Restrict
- See File Restrictions window and press Continue 
- Draft is created (Success message and green lock on file icon appear)
- Go to dataset page and publish draft

Similar steps work for unrestricting files (no File Restrictions window, of course, and the lock disappears). I'm going to close this issue, but if I misunderstood what the bug is, please feel free to reopen.
