### ISSUE TITLE
Document the EJB timer issue workaround in the admin guide

### ISSUE THREAD

**Issue by shlake** [IQSS/dataverse#3669]
Dataverse 4.5.1:

After yum update within OS version, part of quarterly patching, On deploy of 4.5.1 war file got the error:

_remote failure: Error occurred during deployment: Exception while loading the app : EJB Timer Service is not available. Please see server.log for more details._

dataverse would not deploy/start

**Fix was as follows:**

- Remove all rows from EJB__TIMER__TBL
- undeploy dataverse
- stop glassfish
- remove "generated" directory
- remove "osgi-cach"   
- restart glassfish
- deploy dataverse war file

**Comment by pdurbin** [comment]
@shlake thanks for opening this issue and for all the chatter in http://irclog.iq.harvard.edu/dataverse/2017-03-06 ! This issue is related to #3336 and the task should be to document these steps, especially the bit about the `EJB__TIMER__TBL` table, which isn't documented at all. I see that @pameyer is also working on a related script in #3670. Good stuff.

**Comment by landreev** [comment]
Since no one objected on slack - I went ahead and merged in Pete's PR with the sample cleanup script. This way I'll add a doc section that will have a link to it.

**Comment by pdurbin** [comment]
@landreev I'm glad you went ahead and merged #3670 but I wonder if we should `git mv` the file to somewhere in the source tree that mirrors when we'd want the new `clear_timer.sh` script on the file system. For example, I keep the Glassfish init script at `_static/installation/files/etc/init.d/glassfish`. Maybe we could put the script at `_static/installation/files/usr/local/dataverse/sbin/clear_timer.sh` or something. We could also tackle this when there are more files in play. There are other files that might be useful to a Dataverse admin such as `scripts/search/query` and my personal favorite `scripts/database/homebrew/kill9glassfish`. ;)

**Comment by landreev** [comment]
Pete put the script there because he meant it to be an example. Something that they can copy and paste and use as the base of their own script that will actually work on their system. I support that. It's not a ready-to-run script; unlike, say, the scripts that come with the installer. It really is an example; with absolutely no promise that it will work as is. (mostly because of how it relies on su postgres to run a psql command)

**Comment by landreev** [comment]
not sure why this was already in code review... but I've checked in the doc, so it should go into review now.

**Comment by landreev** [comment]
PR: https://github.com/IQSS/dataverse/pull/3674

**Comment by pdurbin** [comment]
@landreev pull request #3674 looks great. I made a few minor tweaks in 4a0a7e2. Thanks for the script @pameyer ! I just moved this issue to QA in https://waffle.io/IQSS/dataverse

**Comment by pameyer** [comment]
@pdurbin - if there's a better place for example utility scripts to go, please feel free to move it there.

**Comment by pdurbin** [comment]
@pameyer meh, let's wait until we create an rpm or a deb of Dataverse scripts and such. Not that we're working on that. 😄
