### ISSUE TITLE
Add "Theme" to list of Dataverse categories

### ISSUE THREAD

**Issue by philippconzett** [IQSS/dataverse#3681]
Would it be possible to add "Thematic" to the list of Dataverse categories? This would e.g. apply for our [TROLLing Dataverse](https://opendata.uit.no/dataverse/trolling), and probably also for other dataverses.

Best,
Philipp

**Comment by pdurbin** [comment]
@philippconzett thanks for opening this issue. I flagged it as a suggestion and the community should discuss here or in the original thread on the dataverse-community list: https://groups.google.com/d/msg/dataverse-community/EYfTHeaqoeQ/vlupYrikAwAJ

By looking again and the current list of categories (screenshot below), I think "Theme" would be a better word than "Thematic."

![screen shot 2017-03-09 at 9 05 52 am](https://cloud.githubusercontent.com/assets/21006/23753501/b7f59f1e-04a7-11e7-99b6-b2e6b42c2f26.png)

I noticed that your TROLLing Dataverse uses "Uncategorized." Which of the existing categories is closest to what you want? Organization?

**Comment by philippconzett** [comment]
"Theme" works fine.
I'm not sure, maybe Organization og Research Project is closest, but none of them are really satisfying.

**Comment by pdurbin** [comment]
@philippconzett ok, for now I changed "Thematic" to "Theme" in the title. I wonder if others in the community are interested in this category. Obviously, we don't want the list to be overly long. I think the existing categories are fairly self-explanatory. If you were to write a tool tip that popped up to explain what is meant my "Theme" what would the tool tip say?

(I also sort of wonder if "Organization" and "Institution" should be separate categories, but that should be a separate GitHub issue if anyone is also wondering about this.)

**Comment by philippconzett** [comment]
Tool tip: Maybe just "E.g. disciplinary, geographical, etc."?

**Comment by pdurbin** [comment]
Hmm, I like "Disciplinary" as a potential category but I don't know if you'd still prefer "Theme" (or would want both). A word like "Topical" might work as a category as well.

I know we're talking about **Dataverse Category** but let's not forget the interplay with **Subject**. Your TROLLing Dataverse gets tagged as "Arts and Humanities" because of the datasets within in. What if you could hide the "Dataverse Category" facet and move the "Subject" facet to the top? What if **Subject** were more granular and you could give datasets a subjects like "Language" and "Linguistics"? The parent dataverse (TROLLing) would be given these subjects as well, based on the datasets. I only bring this up because there is work going on to make **Subject** more granular. See https://groups.google.com/d/msg/dataverse-community/uDl01J8qMbg/68G6om-BAQAJ and https://groups.google.com/d/msg/dataverse-community/TNRb7hoJd8Q/j8bCRRZNAwAJ and https://trello.com/c/x10i7aaB/2-harvard-dataverse-hmpg-4-7 for more on the work going on around the **Subject** field.

Or we could just add a new **Dataverse Category** or two, if that's what people really want. It's easy. :smile:

**Comment by philippconzett** [comment]
I just meant "E.g. disciplinary, geographical, etc." as a tool tip for the proposed dataverse category "Theme".
I'm glad to hear that there are plans for making Subject more granular. A lot of researchers in our research data management courses are asking for more options in the Subject field.

**Comment by pdurbin** [comment]
@philippconzett it's good to know that our work on the Subject field will benefit your users. I'm sure @jggautier would love to hear your thoughts on Subjects. At https://groups.google.com/d/msg/dataverse-community/TNRb7hoJd8Q/j8bCRRZNAwAJ he said he's looking forward to hearing people's thoughts.

**Comment by jggautier** [comment]
Yes, definitely. Please feel free to share your thoughts  comments there in the google groups thread. We'd like to learn how different types of researchers would use the vocabulary we're considering, and more broadly

**Comment by jggautier** [comment]
Yes, definitely! Your suggestions about the Dataverse Category have already been very helpful, and we'd love your feedback on the work being done to improve the terms used for Subjects. I agree that both topics seem related, and we'll need to take a closer look at how the categories are being used (for describing and searching), and how, as @pdurbin wrote, our work on Subject terms will affect that.

Please get in touch with us if you and the researchers you work with would like to test what we're considering currently and in the future to help make datasets more findable.

Best,
Julian
juliangautier@g.harvard.edu

**Comment by pdurbin** [comment]
Related: #2829.

**Comment by djbrooke** [comment]
I'm going to close out this issue as it sounds like we'll implement a broader solution when we improve subject terms. As mentioned, please feel free to join us for discussion on the Google Group or by getting in touch with Julian.

**Comment by pdurbin** [comment]
@djbrooke the same logic could be applied to #2829, right?
