### ISSUE TITLE
Users should be able to download DataCite metadata from Export Metadata pulldown

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#3697]
Users should be able to download DataCite metadata from the Export Metadata pulldown in each dataset Metadata tab:

![screenshot 2017-03-15 21 53 03](https://cloud.githubusercontent.com/assets/18374574/23978375/1ad16fe2-09ca-11e7-9098-398a18be065b.png)

connects to #4257

**Comment by jggautier** [comment]
This was originally included in  #907 (Export Descriptive Metadata From Dataset). Was it postponed because Dataverse doesn't support certain metadata fields (e.g. relation types (#2778, #2917))?

**Comment by pdurbin** [comment]
Any developer working on this issue should look at some unmerged code that has already been written for #2917:

- https://github.com/sbgrid/sbgrid-dataverse/blob/098b56b531f0c3e5cad689ef39eb54d321071587/mod-sbgrid/src/main/java/edu/harvard/iq/dataverse/export/DataciteExporter.java
- https://github.com/sbgrid/sbgrid-dataverse/blob/098b56b531f0c3e5cad689ef39eb54d321071587/mod-sbgrid/src/main/java/edu/harvard/iq/dataverse/export/datacite/DataciteTemplateWriter.java
- https://github.com/sbgrid/sbgrid-dataverse/blob/098b56b531f0c3e5cad689ef39eb54d321071587/mod-sbgrid/src/main/java/edu/harvard/iq/dataverse/export/datacite/DataciteDataModel.java

**Comment by juancorr** [comment]
We have use the sbgrid code and expand it to have our Dataverse compliant with the European OpenAIRE guidelines (https://guidelines.openaire.eu/en/latest/data/index.html) : https://edatos.consorciomadrono.es/oai?verb=ListRecords&metadataPrefix=oai_datacite
https://edatos.consorciomadrono.es/api/datasets/export?exporter=oai_datacite&persistentId=doi%3A10.21950/MJFJM2 .

  We are updated our Dataverse fork (based in v4.6) https://github.com/Consorcio-Madrono/dataverse , but we have tested it only in e-cienciaDatos environment.

  If you want develop this feature we can collaborate.

**Comment by pdurbin** [comment]
@juancorr thanks for getting in touch!

@pameyer what's the status of the sbgrid-dataverse code above? Is it part of your installation? Or are you waiting for #2917 to be picked up again?

**Comment by pdurbin** [comment]
Here's how it looks, by the way:

https://edatos.consorciomadrono.es/dataset.xhtml?persistentId=doi:10.21950/MJFJM2

<img width="1197" alt="screen shot 2017-11-02 at 8 04 20 am" src="https://user-images.githubusercontent.com/21006/32325233-859801ac-bfa4-11e7-88e6-cc506c1e2a3f.png">

@jggautier do you happen to know what other installations of Dataverse are interested in this feature?

**Comment by jggautier** [comment]
In a discussion in the Dataverse Google Group (https://groups.google.com/forum/m/#!searchin/dataverse-community/Openaire/dataverse-community/lgSTeI-0zkQ) @philippconzett has asked about exporting OpenAire compliant metadata, specifically for UiT, but any repository in Europe would be interested.

**Comment by philippconzett** [comment]
Yes, we are definitely interested in this feature! Right now this would help us to mint DOIs manually for those datasets in our Dataverse repo that only have handle. By now, the feature would have to support the newest version of DataCite Metadata Schema, which is 4.1 :)

**Comment by jggautier** [comment]
@pdurbin to answer the question I realize you were actually asking, I'm not aware of any other installations interested in letting users download DataCite metadata from the Export Metadata pulldown.

But there is interest in openAIRE complaint metadata, which I've made a new issue for at #4257.

**Comment by juancorr** [comment]
We have use some ugly tricks to have the OpenAIRE compatibility because Dataverse has not all  metadata that need OpenAIRE. You can see them in the file https://github.com/Consorcio-Madrono/dataverse/blob/v4.6WithOpenAIRE/src/main/resources/templates/datacite_40.ftl .

  - In e-cienciaDatos there are only open access data. We put the field &lt;rights rightsURI="info:eu-repo/semantics/openAccess" /&gt; in all oai records. We should need a field with the right access in Dataverse to map it in a clear way.
  - In Dataverse, there are not a "Grant Agency Identifier" field. We have adapted the  file https://github.com/Consorcio-Madrono/dataverse/blob/v4.6WithOpenAIRE/src/main/resources/templates/datacite_40.ftl  to include the 
agency identifiers by the name. It is possible for us because we have a few records with a few funders. Example:  
          <#if funder.name == "Ministerio de Ciencia y Tecnología" || funder.name == "Ministry of Science and Technology" || funder.name == "Spanish Ministry of Science and Technology" || funder.name == "MICYT">
            <funderIdentifier funderIdentifierType="Crossref Funder ID">http://dx.doi.org/10.13039/501100006280</funderIdentifier>

**Comment by pdurbin** [comment]
I was just talking to @Thalia25 over at http://irclog.iq.harvard.edu/dataverse/2018-05-17#i_67198 about how she is interested in exporting metadata in DataCite format and I told her that it seems like this is going to be delivered in pull request #4664 by @abollini so I went ahead and added the "connect to" syntax to that pull request so that the pull request is associated with the issue at https://waffle.io/IQSS/dataverse?search=3697 and so that we remember to test this issue once the pull request reaches QA. Judging from the pull request, right now the string that will appear in the dropdown is "DataCite OpenAIRE".

**Comment by pdurbin** [comment]
This issue should be tested along with issue #4257 and pull request #4664 which are now in QA.

**Comment by jggautier** [comment]
This was delivered with Dataverse 4.10 in the issue https://github.com/IQSS/dataverse/issues/5043 (woo!). Closing this ticket.

**Comment by pdurbin** [comment]
@jggautier nice! I just noticed that "OAI_ORE" was added in the same pull request (#5047):

![screen shot 2019-01-25 at 12 39 10 pm](https://user-images.githubusercontent.com/21006/51762703-761c5280-209e-11e9-84f4-a7f83ea931a1.png)

Some day it would be nice to update the list at http://guides.dataverse.org/en/4.10.1/admin/metadataexport.html#automatic-exports which looks like this currently:

![screen shot 2019-01-25 at 12 39 40 pm](https://user-images.githubusercontent.com/21006/51762733-83394180-209e-11e9-8fee-df5c73dd526b.png)

**Comment by jggautier** [comment]
That page in the Guides and http://guides.dataverse.org/en/latest/user/dataset-management.html#supported-metadata. It's on @dlmurphy's radar

**Comment by pdurbin** [comment]
... and this page: http://guides.dataverse.org/en/4.10.1/api/native-api.html#export-metadata-of-a-dataset-in-various-formats

![screen shot 2019-01-25 at 1 20 15 pm](https://user-images.githubusercontent.com/21006/51764762-fc876300-20a3-11e9-8f48-34c557540b96.png)

**Comment by dlmurphy** [comment]
Just made these fixes on another branch!
