### ISSUE TITLE
Dataverse -> DCM APIs

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#3725]
Distinct from https://github.com/IQSS/dataverse/issues/3353 (roughly DCM -> DV APIs, in this context).  This is a dependency for DCM UI implementation, but doesn't include UI.

Create dataset function/command needs to:
 - send a message to the DCM requesting setup for a data deposition (for dcm/rsync+ssh, creation of either a transfer script or auth payload)
 - asynchronously check if the setup has been done, and if so return/present the script/auth payload to the depositor

Some configuration (DCM url, etc) will be needed.

**Comment by pdurbin** [comment]
See #3352 for links to code that's already been written. I'm still partial to https://github.com/pdurbin/dataverse/tree/3145-dcm which has `RequestRsyncScriptCommand` and other goodies.

**Comment by pameyer** [comment]
failure modes / open questions:
 - DCM down (create dataset command fail?)
 - upload script expires (script tells depositor to contact support via email)
 - possible interactions with workflows (RSAL)

**Comment by pdurbin** [comment]
@sekmiller and I are talking about this. I'm sure the screenshots in "2017-05-02 Review rsync prototype (Bill's UI changes)" at https://docs.google.com/a/harvard.edu/document/d/1Mi7I2w2FVYbN1Qb9oWLik3UsU2oPY3Wn9Z6_5JXrEAY/edit?usp=sharing will be helpful. They're oriented toward building a UI some day which is not in scope for this issue but will help give some background. I believe this meeting with @pameyer was even recorded.

**Comment by pdurbin** [comment]
Here's some whiteboarding I just did for @sekmiller .

I tried to focus on what the end user will see, even without the fancy UI work that will come in a future issue (if anyone know the issue number please advise):

- create dataset
- download rsync script
- run script
- look for single "data package" file

On the back end, here's roughly what we want to happen:

- On dataset creation, Dataverse asks DCM for an rsync script.
- DCM replies with the rsync script (original prototype) or a URL to the script (proposed, but be careful of security since the script contains credentials).
- User downloads the rsync script.
- User runs the rsync script, which creates a manfest file of checksums and then transfers the manifest and the files themselves to the DCM.
- The DCM verifies the checksum and notifies Dataverse that they're fine, passing JSON with the dataset ID and "validation passed".
- Dataverse kicks off the importer/crawler developed in #3353 (pull request #3497) which will create a single DataPackage file.

That's the happy path. If the DCM tells Dataverse that the checksum fail, Dataverse sends a notification to the user via the normal Dataverse notification system.

Here's the (fugly) whiteboarding of the above:

![issue3525](https://cloud.githubusercontent.com/assets/21006/26077721/1681e2f0-398b-11e7-85f5-819d2cf247ce.jpg)

**Comment by pdurbin** [comment]
@raprasad @sekmiller to get ready for development, please install and run the Data Capture Module (DCM) on your laptops. Instructions are at https://github.com/sbgrid/data-capture-module and @pameyer can help field questions since he wrote the code! 😄

**Comment by pdurbin** [comment]
It just hit my radar that there are many additional resources that are sure to be helpful to developers that are being gathered by the design team in a folder called "rsync" https://drive.google.com/open?id=0B3A1TxMQgvUVa2ltQjc4cmliTTg including:

- A video of the "2017-05-02 Review rsync prototype (Bill's UI changes)" doc I mentioned above which features @pameyer walking through the workflow.
- Notes and questions from the design team about rsync: https://docs.google.com/a/harvard.edu/document/d/1EYC_qa0a4XmKkjbo0--rJZwihrZlwS17N7FCRdk7350/edit?usp=sharing
- Notes on an interview with @pameyer on why rsync is used: https://docs.google.com/document/d/1USZ_AzrR6deaeImRigiOWuwHutbWDPEF8MhQ_8nRUac/edit?usp=sharing

There's also a wealth of information at https://trello.com/c/Nbte37k1/9-rsync-file-upload-download-4-8

**Comment by pdurbin** [comment]
I took code I wrote a year ago at https://github.com/pdurbin/dataverse/tree/3145-dcm and pushed it into a new branch after getting it up to date with the "develop" branch: https://github.com/IQSS/dataverse/tree/3725-dcm-apis

I'm realizing that some of my unanswered questions will be resolved once #3724 has passed through Code Review. I'll keep an eye on that issue as well as its pull request at #3830 to make sure I'm being consistent with whatever decisions are made there especially with regard to the rules for when Dataverse should ask the DCM for an rsync script. @pameyer made the pull request and should be able to fill me in.

**Comment by raprasad** [comment]
removed assignment after ticket scope changed

**Comment by pdurbin** [comment]
@raprasad thanks. Yes, complete scope change as of yesterday afternoon's sprint planning meeting. In the morning I was sketching diagrams like this...

![img_20170517_120629](https://cloud.githubusercontent.com/assets/21006/26203163/20755bba-3ba8-11e7-8974-e926c1db8973.jpg)

... which give a more complete picture of what's called "Large Data Upload Integration" at http://dataverse.org/goals-roadmap-and-releases and hints at the work @michbarsinai is doing in #3561 but this current issue has been clarified to be much smaller. Above I had stated that the definition of done is seeing a data file with a MIME Type of `application/vnd.dataverse.file-package` in the UI like this on the dataset page:

![screen shot 2017-05-17 at 5 08 25 pm](https://cloud.githubusercontent.com/assets/21006/26203310/bb952c1a-3ba8-11e7-9c5f-79dd89fdfd70.png)

The clarified definition of done is this:

**Assuming the `vagrant up` has been run on https://github.com/sbgrid/data-capture-module and Dataverse has been configured to use that host as the Data Capture Module (DCM) and configured site-wide with rsync as a supported upload method, a user who has sufficient permission on a dataset `Permission.AddDataset` as of this writing) should be able to download an rsync script from the DCM via Dataverse using an API Token, as verified by API tests and documented. Additionally, since #3724 has been closed, at least enough configuration options to support the story above will be implemented and documented. Additionally, even though `:RepositoryStorageAbstraction LayerUrl` and `:DownloadMethods` config options are necessary for this issue, they were mentioned in #3724 so we'll add them as well, but perhaps not document them until they are meaningful. It would be more meaningful to document them as part of #3561, I believe.**

**Comment by pdurbin** [comment]
I'm still working away on my `3725-dcm-apis` branch but I'm thinking I'll make a fresh one with a single commit once I'm done. Good progress today. Thanks to @pameyer and @kcondon for talking through the issues.

Here are some requirements for testings we talked about:

- Shared filesystem between Dataverse and Data Capture Module (DCM)
- The server that the DCM is running on may need to be wiped periodically because it creates Unix accounts.

**Comment by pdurbin** [comment]
I just made pull request #3851 and put this issue in the Code Review column at https://waffle.io/IQSS/dataverse

**Comment by pameyer** [comment]
I took a quick look at the code/doc changes:
 - `data-capture-module.rst` should probably refer to the transfer protocol as "rsync over ssh" instead of just "rsync" (aka - there's auth and encryption for these uploads)
 - I couldn't figure out where the logic for "check upload settings on dataset creation" lives; any pointers?

**Comment by pdurbin** [comment]
@pameyer I added "over ssh" in e102835. The place to look would be `CreateDatasetCommand.java` but no need to bother looking because right now the logic is only in `Datasets.java`. I don't think we need it in the command yet.

**Comment by pameyer** [comment]
@pdurbin I'm relatively sure that this was the place to make the changes to the create command (I know we cut the scope a bit for this issue, but I didn't think we cut it that far).

**Comment by pdurbin** [comment]
Ok, I'll add it in. Thanks.

**Comment by pdurbin** [comment]
@pameyer ok, you can now see it at https://github.com/IQSS/dataverse/blob/4df9336b6aee6b31adddb8210269bf565e3b189f/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDatasetCommand.java#L193

@kcondon this is ready for QA.

**Comment by pdurbin** [comment]
Whoops, @pameyer would like to code review the pull request before it gets merged so I assigned it to him and pulled it out of QA.

**Comment by pameyer** [comment]
@pdurbin - looks good to me.

One question - what does `{identifier}/dataCaptureModule/rsync` return if `sr.py` doesn't have a script to return?

**Comment by pameyer** [comment]
@pdurbin  Intentionally breaking the DCM (or just changing the DCM URL to something nonexistent) might be one way to test it.  It'll fail either way; I'm just thinking about an end user seeing an error message that doesn't tell them anything useful.  I'm ok deferring that (into another issue) if that makes more sense.

**Comment by pdurbin** [comment]
@pameyer it's a good point and as luck would have it my installation of DCM is hosed right now so it was easy to test the case of when it doesn't return an rsync script to Dataverse. 😄 

I just pushed 4126ad1 which gives the API user a better clue as to what went wrong:

`{`
`    "status": "ERROR",`
`    "message": "Something went wrong attempting to download rsync script: User id 305 had a problem retrieving rsync script for dataset id 452 from Data Capture Module. The script was null or empty."`
`}`

**Comment by pameyer** [comment]
@pdurbin thanks

**Comment by pdurbin** [comment]
@pameyer I made a few more improvements, ending with 087f876, to increase code coverage etc. I'm done. Ready for QA.

**Comment by pameyer** [comment]
Just noticed the intersection with DV sending `dataset.id` to ur.py; and expecting `dataset.identifier` in batch-import.

**Comment by pdurbin** [comment]
@pameyer to me, an identifier is a DOI and an id is a database id.

**Comment by pameyer** [comment]
@pdurbin - the database and native API both have something called "identifier"; what should I be calling it?
