### ISSUE TITLE
Documentation: Fix very minor but important doc issue regarding blocking API endpoints.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3728]
Reported by a partner, see RT 247958 for details

Under the :BlockedApiPolicy section of http://guides.dataverse.org/en/latest/installation/config.html#

the example specifies the wrong setting name. It says,
curl -X PUT -d localhost-only http://localhost:8080/api/admin/settings/:BlockedApiEndpoints
when it should say:
curl -X PUT -d localhost-only http://localhost:8080/api/admin/settings/:BlockedApiPolicy

**Comment by dlmurphy** [comment]
Looked this over and it's definitely an important fix. I've made the proposed change.

**Comment by pdurbin** [comment]
I'm taking a look at pull request #3827.

**Comment by pdurbin** [comment]
@dlmurphy and I discussed this issue this morning. The pull request #3827 actually has two fixes: 

- fixing the doc to say :BlockedApiPolicy 
- in the README.md file, "make the links look better (remove spaces between `[]` and `()`)" from #3729 which is also being fixed in pull request #3822. There's a potential for a merge conflict here, but I guess we'll see what happens.

Both fixes look good. Passing to QA at https://waffle.io/IQSS/dataverse
