### ISSUE TITLE
BibTex Improvements

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#3759]
- Clicking "BibTex" under "Citation Type" downloads a .bib file. Instead of downloading a .bib file, we should open a new browser tab with the BibTex citation. 
- In a BibTex citation, we should include all of the information that's shown in the Dataverse citation. Currently, UNF and version are left out of BibTex. 

Example: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/QSZMPD

**Comment by pdurbin** [comment]
Related: #3140

**Comment by pameyer** [comment]
Two questions about the first bullet point?
 - why is a new tab preferable over downloading a file?  If a user is going to import it into a reference manager (which I'm relatively sure is the usual case), they'll need to download a file: so "new tab" -> "download" vs "download" is an extra step?
 - is there / should there be an API endpoint (or content-negotation) for downloading the citation?

**Comment by TaniaSchlatter** [comment]
Hi Danny,

Can you add a few words about why it should work differently/where this
idea/proposal/requirement came from?

Thanks!

- Tania

**Comment by djbrooke** [comment]
This is a request from Gary. Other applications (Google Scholar) provide the .bib in a new tab and this preferable.

**Comment by jggautier** [comment]
To the second point about including more info. in the bibtex, these fields aren't showing up when importing citation into latex using standard bibtex setups:
- UNF
- Version
- Publisher

UNF and version number aren't being exported at all.
The repository name is, in the _publisher_ field, but seems to be ignored.

Exported bibtex from dataset in Harvard @djbrooke linked to in Harvard Dataverse:
```
@data{QSZMPD_2017,
author = {King, Gary and Pan, Jennifer and Roberts, Margaret E.},
publisher = {Harvard Dataverse},
title = {Replication data for: How the Chinese Government Fabricates Social Media Posts for Strategic Distraction, not Engaged Argument},
year = {2017},
doi = {10.7910/DVN/QSZMPD},
url = {http://dx.doi.org/10.7910/DVN/QSZMPD}
}
```

**Comment by thegaryking** [comment]
Please also remove the abstract field. it is a nice bit of metadata, but it is never used as part of a citation and just fills up your bibtex file with a lot of extra text.

these tickets should be attached to some planned release with a date.  this is an old ticket.

**Comment by djbrooke** [comment]
I moved this to the "Ready" column so that we can get this estimated in sprint planning next week. This one fell through the cracks, my fault. 

@thegaryking - I'll stop by to learn more about your thoughts on the release planning process.

**Comment by djbrooke** [comment]
@thegaryking We have a PR up for review with changes for everything requested except the abstract part. Can you provide a few more details about where you're seeing the abstract show up in BibTeX (or elsewhere)? Thanks!

**Comment by thegaryking** [comment]
sometimes there's an extra field that looks like this:

abstract = {We clarify the theoretical foundations of partisan fairness standards for district-based democratic electoral systems, including essential assumptions and definitions that have not been formalized or in some cases even discussed. We pare assumptions down to their minimal essential components and add extensive empirical evidence for those with observable implications. Throughout, we follow a fundamental principle of statistics too often ignored --- defining the quantity of interest separately so its measures are vulnerable to being proven wrong, evaluated, and improved. This enables us to prove which approaches --- claimed in the literature to be estimators of partisan symmetry, the most widely accepted standard --- are statistically appropriate and which are biased, limited, or not measures of symmetry at all. Because real world redistricting involves complicated politics with numerous participants and conflicting goals, measures biased for partisan fairness sometimes still provide useful descriptions of other aspects of electoral systems.}

i'd drop that field. I don't see that it would ever be useful for a reference.

Gary
--
Gary King - Albert J. Weatherhead III University Professor - Director, IQSS<http://iq.harvard.edu/> - Harvard University
GaryKing.org<http://GaryKing.org> - King@Harvard.edu<mailto:King@Harvard.edu> - @KingGary<https://twitter.com/kinggary> - 617-500-7570 - Assistant<mailto:king-assist@iq.harvard.edu>: 617-495-9271


On Tue, Dec 4, 2018 at 11:36 AM Danny Brooke <notifications@github.com<mailto:notifications@github.com>> wrote:

@thegaryking<https://github.com/thegaryking> We have a PR up for review with changes for everything requested except the abstract part. Can you provide a few more details about where you're seeing the abstract show up in BibTeX (or elsewhere)? Thanks!

**Comment by sekmiller** [comment]
Abstract ("description") is not part of the BibTex citation, but per Gary's comments above I have removed it from RIS and EndNote XML versions.

**Comment by pameyer** [comment]
On 2cd3a2a35; unable to reproduce this behavior (no quotation marks seen in exported bibtex):

``
@data{FK2/HUBG7P_2018,
author = {Finch, Fiona},
publisher = {Root},
title = {Darwin's Finches},
year = {2018},
version = {V1},
doi = {10.5072/FK2/HUBG7P},
url = {https://doi.org/10.5072/FK2/HUBG7P}
}
``

**Comment by djbrooke** [comment]
Hi @thegaryking, can you please link me to the citation where you're seeing this behavior? Thanks!

**Comment by jggautier** [comment]
So in the title field for bibtex files, Dataverse needs to turn open quote characters into two back ticks (``) and closed quote characters into two apostrophes ('').

This is because when LaTex sees the regular quote character next to some letters, like `"A`, it turns that string into a letter with a diaeresis, like `Ä`. Is that right? (That's what I understand from [this stackoverflow question](https://stackoverflow.com/questions/3901180/how-to-preserve-quotes-in-bibtex).)

**Comment by thegaryking** [comment]
that's right
Gary
--
Gary King - Albert J. Weatherhead III University Professor - Director, IQSS<http://iq.harvard.edu/> - Harvard University
GaryKing.org<http://GaryKing.org> - King@Harvard.edu<mailto:King@Harvard.edu> - @KingGary<https://twitter.com/kinggary> - 617-500-7570 - Assistant<mailto:king-assist@iq.harvard.edu>: 617-495-9271


On Mon, Dec 17, 2018 at 11:13 AM Julian Gautier <notifications@github.com<mailto:notifications@github.com>> wrote:

So in the title field for bibtex files, Dataverse needs to turn open quote characters into two back ticks (``) and closed quote characters into two apostrophes ('').

This is because when LaTex sees the regular quote character next to some letters, like "A, it turns that string into a letter with a diaeresis, like Ä. Is that right? (That's what I understand from this stackoverflow question<https://stackoverflow.com/questions/3901180/how-to-preserve-quotes-in-bibtex>.)

**Comment by pdurbin** [comment]
> So in the title field for bibtex files, Dataverse needs to turn open quote characters into two back ticks (``) and closed quote characters into two apostrophes ('').

@jggautier created #5424 for the issue above about backticks.

**Comment by thegaryking** [comment]
no. that's not quite right.  at the start it is too of these `` and at the end of a quote it is two of these ''.  They are different.
Gary
--
Gary King - Albert J. Weatherhead III University Professor - Director, IQSS<http://iq.harvard.edu/> - Harvard University
GaryKing.org<http://GaryKing.org> - King@Harvard.edu<mailto:King@Harvard.edu> - @KingGary<https://twitter.com/kinggary> - 617-500-7570 - Assistant<mailto:king-assist@iq.harvard.edu>: 617-495-9271


On Fri, Dec 21, 2018 at 11:32 AM Philip Durbin <notifications@github.com<mailto:notifications@github.com>> wrote:

So in the title field for bibtex files, Dataverse needs to turn open quote characters into two back ticks (``) and closed quote characters into two apostrophes ('').

@jggautier<https://github.com/jggautier> created #5424<https://github.com/IQSS/dataverse/issues/5424> for the issue above about backticks.
