### ISSUE TITLE
UX and Dataset page checkbox woes

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3770]
**Page**: Dataset page
**Action**: Attempting to select checkboxes next to multiple files
**Problem**:  Clicking and "Missing" a checkbox unchecks any previously selected checkbox
  - e.g. If you're not clicking exactly in the checkbox--other checkboxes are cleared

(Note: I run into this often when testing--including just now.  Yesterday noticed another developer will go to the File page rather than work with the checkboxes on this page)

![test_delete_map_-_dvn-build_2_dataverse](https://cloud.githubusercontent.com/assets/1036060/25012900/d9ae32c0-203f-11e7-80c1-f8f33c981bf7.png)

**Comment by jggautier** [comment]
Interesting!

Seems like selecting behaves like radio buttons when clicking the area of the cell outside of the checkbox, and, of course, behaves like checkboxes when clicking the checkboxes. Is this duel functionality intentional, maybe to make it easier for people to select just one file (and deselect everything else)? I wouldn't think it was conventional enough to not have a stronger indication of this behavior.

**Comment by djbrooke** [comment]
Discussed briefly in the sprint planning meeting 8/2. Closing this, as it is a Primefaces issue and could not be addressed without quite a bit of code.
