### ISSUE TITLE
Provide a working dataset URL in the Dublin Core metadata record

### ISSUE THREAD

**Issue by 4tikhonov** [IQSS/dataverse#3809]
We're experiencing some problems with identifiers in OAI-PMH.

We have harvester for narcis.nl research portal and it's not resolving identifiers (to http) for records harvested from DataverseNL as http missing in the current OAI-PMH output.

We think that

<dc:identifier>hdl:1902.29/10438</dc:identifier>
should be changed to
<dc:identifier>http://hdl.handle.net/1902.29/10438</dc:identifier>

Is it possible to fix that?

**Comment by landreev** [comment]
Hmm. We've never promised that our OAI identifiers would be resolvable http urls. It is not required by an OAI spec (an OAI identifier is just a unique string). And for as long as we've provided OAI service, it was always built on the idea that the global id of a Dataset is also used as the OAI identifier. And that's what our global ids have always looked  - "PROTOCOL:"+"AUTHORITY"+"/IDENTIFIER"  - "hdl:1902.1/XXXX" or "doi:10.7910/YYYY", etc. 

You can still convert this format to a resolvable http://hdl.handle.net url, with a simple regex - right?

So, honestly, I don't feel comfortable changing this, at all.

**Comment by landreev** [comment]
BTW, sorry I missed your first comment in the #3687 issue. 
But, I may still be missing something - why was that a problem, why was it needed, that the OAI identifiers could be used as working URLs?

Do I understand correctly that we are talking about a non-Dataverse harvesting client harvesting from a Dataverse? So, is this just a matter to be able to redirect back to the Dataverse page, that corresponds to the harvested dataset? You don't even need to go to hdl.handle.net. If you have a harvested record with the Identifier hdl:1902.29/10438, the direct dataset url at the Dataverse installation where it was harvested from is 
http://DATAVERSEADDRESS/dataset.xhtml?persistentId=hdl:1902.29/10438. So generating this URLs is a straightforward and unambiguous affair. 

(and if it's one Dataverse harvesting from another Dataverse,  you of course don't need to worry, or know about this - as the client Dataverse will generate this redirect links for its users automatically...)

**Comment by 4tikhonov** [comment]
No, it's really big problem if you're harvesting by other clients and it's not really straightforward to get right URL to resolve. At the moment we just did quick fix to adjust client to generate URLs for handles but probably someone else will complain about the same issue soon.

**Comment by pdurbin** [comment]
@4tikhonov is your quick fix a change you made to the Dataverse code? In your fork, I mean.

**Comment by 4tikhonov** [comment]
No, it's external client for narcis.nl

**Comment by landreev** [comment]
Oh, ok, I can finally see what's going on...
You were NOT talking about the OAI identifiers... i.e., the identifiers used in the OAI exchange:
```
<ListIdentifiers><header><identifier>hdl:1902.1/BNCOWNVERH</identifier><datestamp>2017-05-01T03:18:45Z</datestamp><setSpec>king</setSpec>
<setSpec>everythingplusking</setSpec>
</header>
</ListIdentifiers>
```

these identifiers are indeed supposed to be opaque strings, without any extra meaning attached to them... 

BUT you were talking about the identifiers in the actual metadata; like the identifier field in the oai_dc: 

```
<dc:identifier>hdl:1902.29/10438</dc:identifier>
```

You did correctly specify the name of the field - "dc:identifier" in your original description; but then github ate the angle brackets around it, so I didn't catch it right away... Most importantly, since this came up in the context of another OAI-related ticket, I was already assuming this is directly related to our implementation of the OAI protocol... when, in reality, this is a matter of how we export our metadata. 

So, all you want is a resolvable, working URL in the DC metadata that we produce. We should be able to do that. We just need to decide whether we do this by putting an "http://hdl.handle.net" url in the "dc:identifier" field, or whether it should be a url of the dataset.xhtml page on the Dataverse site; (or whether it should be a different DC field somehow?). 

Sorry for being a bit of a dumbass; but, as I said, there were some confusing elements there. :)

**Comment by rmo-cdsp** [comment]
Hello !
We are experiencing the same situation with DOI and our harvester (we are not in charge of it), which does not guess the url.

**Comment by pdurbin** [comment]
@rmo-cdsp are you interested in making a pull request?

**Comment by rmo-cdsp** [comment]
I may take a look and see what I can do :)

**Comment by pdurbin** [comment]
@rmo-cdsp thanks for making pull request #3833 and discussing the changes you made to tests at http://irclog.iq.harvard.edu/dataverse/2017-05-16#i_52751

I moved this issue to Code Review at https://waffle.io/IQSS/dataverse

**Comment by landreev** [comment]
We've reviewed the pull request, and requested a small change (it's in the PR https://github.com/IQSS/dataverse/pull/3833).

@4tikhonov: we should be able to put this fix into the version 4.6.2, that's coming shortly.

**Comment by landreev** [comment]
Requested changes made; thank you @rmo-cdsp. 
Pushing the issue into QA.

**Comment by landreev** [comment]
Just adding this, for posterity: one thing I wanted to discuss before incorporating this change was whether we wanted this URL to be a) the handle resolver url, for ex., http://hdl.handle.net/1902.1/XYZ (as requested) OR b) direct url to the dataset page in dataverse, for ex., https://dataverse.edu/dataset.xhtml?persistentId=hdl:1902.1/XYZ. 
This discussed by the dev. team on Monday, and everybody appeared to be in favor of a). This is how it was implemented in the contributor's PR, so - all's good.

**Comment by kcondon** [comment]
Changes works as described but uncovered a logic issue in harvest: fails when harvesting new metadata with this error: Caused by: javax.ejb.EJBException: Failed to find a global identifier in the OAI_DC XML record.

**Comment by landreev** [comment]
DOH!! 
yeah, our handle parser only recognizes the "hdl:..." format. 
Will fix shortly... 
(for anyone else following this issue: we have satisfied the needs of some third-party, non-Dataverse harvesting clients; but broken Dataverse-to-Dataverse harvesting in the process... Dataverses should not really use DC to harvest from each other - but then, it still shouldn't be broken outright...)

**Comment by landreev** [comment]
@kcondon: please use the following pull request, and the corresponding branch for further testing: 
https://github.com/IQSS/dataverse/pull/3844

This is my fork of the contributor's branch, with the DC parser fix, pushed back into the IQSS source tree.

**Comment by jggautier** [comment]
It seems that this issue was resolved so that in the oai_dc that Dataverse publishes, the value for dc:identifier should be a URL. So:
`<dc:identifier>http://dx.doi.org/10.7910/DVN/QWXPUA</dc:identifier>` instead of `<dc:identifier>doi:10.7910/DVN/QWXPUA</dc:identifier>`

Is that right? Or did we decide not to make this change? In Dataverse 4.8.6 and earlier versions, the dc:identifier is not a URL: https://dataverse.harvard.edu/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=doi:10.7910/DVN/QWXPUA
