### ISSUE TITLE
Contact Name should be required metadata field in Dataverse?

### ISSUE THREAD

**Issue by philippconzett** [IQSS/dataverse#3839]
I just got a DataCite related error message when trying to publish a dataset in Dataverse. After a lot of trial and failure I found out that the metadata field "Contact Name" has to be filled in in order for the dataset to be published. I don't know the reason for this - I couldn't find any information about this field to be obligatory in DataCite Metadata Scheme V 4.0. By default, the contact email address is required by Dataverse, but not the contact name. We have now added this field as obligatory in our Dataverses. Maybe the field should be required by Dataverse.

Best,
Philipp

**Comment by jggautier** [comment]
When the contactName is empty, is there a way we could populate the field with one of DataCite's "standard values for unknown information"? (the values on page 45 of the schema, [(PDF)](https://schema.datacite.org/meta/kernel-4.0/doc/DataCite-MetadataKernel_v4.0.pdf))?

Page 10:
> If one of the required properties is unavailable, please use one of the standard (machine‐recognizable) codes.

**Comment by pdurbin** [comment]
@jggautier you seem to be talking about these values for unknown information on page 45:

<img width="719" alt="screen shot 2017-05-24 at 2 47 24 pm" src="https://cloud.githubusercontent.com/assets/21006/26420213/f7cdf950-408f-11e7-919a-a19ca60e5a8a.png">

For searchability, here's the text:

Code Definition
(:unac) temporarily inaccessible
(:unal) unallowed, suppressed intentionally
(:unap) not applicable, makes no sense
(:unas) value unassigned (e.g., Untitled)
(:unav) value unavailable, possibly unknown
(:unkn) known to be unknown (e.g., Anonymous, Inconnue)
(:none) never had a value, never will
(:null) explicitly and meaningfully empty
(:tba) to be assigned or announced later
(:etal) too numerous to list (et alia)

**Comment by jggautier** [comment]
That's it! Thanks! I ask because that field is pre-populated when datasets are created, but the majority of datasets at Harvard's installation have no contactName, so depositors are removing their names. Knowing the name is helpful for getting in touch with whoever's responsible for the data. How valuable is that info. when people don't want to share it?

Wondering if this is an option. I wouldn't want to mandate another field just because it's technically necessary.

**Comment by jggautier** [comment]
> the majority of datasets at Harvard's installation have no contactName, so depositors are removing their names

Looks like most of the non-harvested datasets in Harvard Dataverse created after 4.0 have contactName filled ([1167](https://dataverse.harvard.edu/dataverse/harvard?q=datasetContactName%3A*&fq1=publicationDate%3A%222017%22&fq0=metadataSource%3A%22Harvard+Dataverse%22&types=dataverses%3Adatasets%3Afiles&sort=score&order=desc) of [1351](https://dataverse.harvard.edu/dataverse/harvard?q=&fq1=publicationDate%3A%222017%22&fq0=metadataSource%3A%22Harvard+Dataverse%22&types=datasets&sort=dateSort&order=desc) in 2017; [3525](https://dataverse.harvard.edu/dataverse/harvard?q=datasetContactName%3A*&fq1=publicationDate%3A%222016%22&fq0=metadataSource%3A%22Harvard+Dataverse%22&types=dataverses%3Adatasets%3Afiles&sort=score&order=desc) of [4315](https://dataverse.harvard.edu/dataverse/harvard?q=&fq1=publicationDate%3A%222016%22&fq0=metadataSource%3A%22Harvard+Dataverse%22&types=datasets&sort=dateSort&order=desc) in 2016), and it's most of the datasets _before_ Dataverse 4.0 that don't have contactName. So pre-filling that field has really helped, and most depositors since haven't removed their names. So mandating that field doesn't seem so problematic for Harvard Dataverse, either, although I'm still curious why depositors removed their names 200 times so far this year.

I'd like to find out why you're getting that DataCite related message. I couldn't find any information in the DataCite scheme about DataCite requiring the contact name, either. Are other installations minting DOIs directly from DataCite? And would they get the same errors trying to publish a dataset without a contact name?

**Comment by jggautier** [comment]
I contacted the folks on the DataCite forums to ask if EZID might be doing something differently with dataset metadata when registering DOIs. I was told no, and they recommended we take a closer look at what metadata Dataverse is sending.

@philippconzett, I'm weary about making the field mandatory at the installation level, where we would basically be taking away the choice to make the field optional or mandatory in these settings:

![screen shot 2017-07-14 at 1 35 25 pm](https://user-images.githubusercontent.com/18374574/28223503-aa61e528-6899-11e7-9aac-62bf26893761.png)

I'd like to make it easier for depositors to provide more appropriate contact info. Of course, that's why Dataverse pre-populates the field the depositor's name.

**Comment by pdurbin** [comment]
Related: #5559

**Comment by jggautier** [comment]
I'm going to close this issue. But @philippconzett, please let us now if DataverseNO is not okay with making Contact Name a required field. I assumed your team is okay with this, and as you wrote, making the field required seems to have resolved DataverseNO's problem of not being able to publish datasets (although no one's sure why)

**Comment by pdurbin** [comment]
@jggautier huh. I have this issue on the board I use to track issues I'd like to prioritize to push through the sausage factory: https://trello.com/b/YI9EbqGz/backlog-grooming-for-dataverse-pdurbin-edition

The reason this issue is on my radar is that as installations of Dataverse move from EZID to DataCite (like Harvard Dataverse did relatively recently), they will get bit by this bug as well. DataverseNO was one of the early adopters of DataCite. I'm not sure if they were ever on EZID.

**Comment by pdurbin** [comment]
@philippconzett I know your workaround has been to make Contact Name required but last week @jggautier was able to publish a dataset without a Contact Name in Harvard Dataverse (which is using DataCite rather than EZID these days). For details, please see https://github.com/IQSS/dataverse.harvard.edu/issues/4#issuecomment-497868990

@jggautier and I are speculating that something changed but we don't know what. I'm closing this issue.
