### ISSUE TITLE
Native API: Missing indexing of draft metadata version created by HTTP PUT to existing dataset

### ISSUE THREAD

**Issue by asconrad** [IQSS/dataverse#3842]
HTTP PUT to an existing dataset has been found to work - status 200 and a DRAFT version visible on the Versions tab of the dataset.
It would seem, however, that a draft version created this way through the native API is not being indexed by Solr. The draft version is not visible through search or on the Drafts facet, even for an administrator - only on the Versions tab of the dataset landing page.
Dataverse 4.6.1 running under RHEL 7/Solr 4.6.0.

**Comment by pdurbin** [comment]
@asconrad thanks for the bug report. I love it when people include the version they're testing on. 😄 

This reminds me of #3243 but is clearly a different issue. The next step is to confirm the bug. @asconrad since https://demo.dataverse.org is running 4.6.1 as of this writing can you please test there and let us know the DOI of the dataset you created?

**Comment by asconrad** [comment]
I have uploaded a dataset, Hokus Pokus, with doi:10.5072/FK2/4IORXB, Id=16431.
Same behaviour in the Demo dataverse: only the Published version is showed in listing and search, but the new draft version is visible under Versions tab of published version.
Hope this helps...

**Comment by asconrad** [comment]
Addition to previous comment: The updated draft version was created by the command:
curl -H "Content-type:application/json" -X PUT -d @hv_16431.json https://demo.dataverse.org/api/datasets/16431/versions/:draft?key=xxxxx

**Comment by pdurbin** [comment]
@asconrad thanks, there are two kinds of drafts:

- a draft that represents a brand new, **unpublished dataset**
- a draft of a **published dataset**

Are you saying that the dataset isn't indexed in both cases of when drafts are created?

**Comment by asconrad** [comment]
@pdurbin no, the situation I am talking about is the situation of the new draft of the already **published dataset**. 
I have not tested the other one with this perspective in mind so I can't say how that one works.

**Comment by pdurbin** [comment]
@asconrad ok, thanks for the clarification!

**Comment by mohammadsalem** [comment]
Dear @pdurbin, 
For versions 4.8.5 and 4.14 this is still an issue, is there a plan to solve it soon? or do you have any suggestions to overcome it (clearing solr and re-index works but it is not an efficient solution)?
Thanks.

**Comment by pdurbin** [comment]
@mohammadsalem hi! Unfortunately, the is no plan for the team at IQSS to resolve this issue anytime soon. If you look at https://github.com/orgs/IQSS/projects/2 you can see that this issue isn't on our kanban board yet.

If you or @asconrad or others would like to contribute a bug fix, I am happy to explain what part of the code to look at.

Another workaround instead of completely clearing Solr and doing a "reindex all" is to reindex just the one dataset. Reindexing a single dataset has been available since Dataverse 4.0 I believe but it was only recently documented: http://guides.dataverse.org/en/4.14/admin/solr-search-index.html#reindexing-datasets

I hope this helps. Thanks for confirming that this is still a bug!

**Comment by mohammadsalem** [comment]
@pdurbin Yes please it would be great to guide me where to look.

**Comment by pdurbin** [comment]
@mohammadsalem sure! Here's a COMPLETELY UNTESTED "diff" that I hope gets you started:

```
$ git diff
diff --git a/src/main/java/edu/harvard/iq/dataverse/api/Datasets.java b/src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
index f538d3696..3a6637f44 100644
--- a/src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
+++ b/src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
@@ -545,6 +545,7 @@ public class Datasets extends AbstractApiBean {
         });
     }
   
+    // Docs at http://guides.dataverse.org/en/4.14/api/native-api.html#update-metadata-for-a-dataset
     @PUT
     @Path("{id}/versions/{versionId}")
     public Response updateDraftVersion( String jsonBody, @PathParam("id") String id,  @PathParam("versionId") String versionId ){
diff --git a/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDatasetVersionCommand.java b/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDatasetVersionCommand.java
index 24d957968..3d629db79 100644
--- a/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDatasetVersionCommand.java
+++ b/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/CreateDatasetVersionCommand.java
@@ -53,9 +53,10 @@ public class CreateDatasetVersionCommand extends AbstractDatasetCommand<DatasetV
         }
         newVersion.setFileMetadatas(newVersionMetadatum);
         
-        // TODO make async
-        // ctxt.index().indexDataset(dataset);
-        return ctxt.datasets().storeVersion(newVersion);
+        DatasetVersion storedVersion = ctxt.datasets().storeVersion(newVersion);
+        boolean doNormalSolrDocCleanUp = true;
+        ctxt.index().indexDataset(storedVersion.getDataset(), doNormalSolrDocCleanUp);
+        return storedVersion;
         
     }
     
diff --git a/src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java b/src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
index 9b4e92ca4..7dc403c34 100644
--- a/src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
+++ b/src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java
@@ -1705,5 +1705,11 @@ public class DatasetsIT {
         logger.info("datasetPersistentId: " + datasetPersistentId);
 
     }
+
+    @Test
+    public void testUpdatingMetadataForPublishedDataset() {
+        //TODO: Write test
+        //Response updateTitleResponseCuratorViaNative = UtilIT.updateDatasetMetadataViaNative(datasetPersistentId, pathToJsonFile, apiToken);
+    }
     
 }
diff --git a/src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java b/src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
index f23d48063..eb65904d7 100644
--- a/src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
+++ b/src/test/java/edu/harvard/iq/dataverse/api/UtilIT.java
@@ -409,6 +409,7 @@ public class UtilIT {
                 .header(API_TOKEN_HTTP_HEADER, apiToken)
                 .body(jsonIn)
                 .contentType("application/json")
+                // FIXME: Support non-draft versions by removing hard coded ":draft" and making it a method parameter.
                 .put("/api/datasets/:persistentId/versions/:draft?persistentId=" + persistentId);
         return response;
     }
```

Please let me know if you have any questions! A good place to reach me is http://chat.dataverse.org 😄

**Comment by pdurbin** [comment]
I'm sitting next to @asconrad at PIDapalooza and he said this issue is opened is from some old testing they did and he's not actively looking for a fix.

@mohammadsalem (or anyone else reading this), please open a fresh issue if you're still having this problem in Dataverse 4.19 (the latest) or whatever version you're running. Thanks!
