### ISSUE TITLE
Customization - Harvard Dataverse logo

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#3872]
With the configurable custom content settings added in #3639, we will need a home page, header and footer built for the Harvard Dataverse installation.

**Comment by TaniaSchlatter** [comment]
Attaching the most recent mockups for reference. 

[HP_comps_viz_approaches.pdf](https://github.com/IQSS/dataverse/files/1089243/HP_comps_viz_approaches.pdf)

**Comment by TaniaSchlatter** [comment]
As a first step:
• change the Harvard logo on the home page to the official version. This logo should appear on the home page only. No Harvard logo on other pages. 
• put "Harvard" in the Dataverse logotype that is in the header. See screen shot:
![custom_hp_1](https://user-images.githubusercontent.com/15386424/31507500-e8b6435a-af48-11e7-9cd0-8b3c93aad2af.jpg)

**Comment by mheppler** [comment]
Before we add this new homepage to the Harvard Dataverse installation, we should look into solving this root dataverse URL consistency issue (Root Dataverse URL + Pretty Faces -- Unecessary? #1519) for analytics and SEO improvements.

**Comment by mheppler** [comment]
Prioritizing the first step mocked up above, and separating out the homepage, header and footer into a new issue, Customization - Harvard Dataverse branding #4399.

Will need to use the recently released `:DisableRootDataverseTheme` feature from #4197, as well other customization options like `:StyleCustomizationFile` and `:LogoCustomizationFile`.

**Comment by mheppler** [comment]
Related to #3694, [README](https://docs.google.com/document/d/1tHwp9mmMeVRI2X_MY70Jp8rZqdkYDWWUcqywlwEUigU/edit#heading=h.32p51im12ty7) created to outline required customization options setup.

**Comment by mheppler** [comment]
README updated, as well as resource files revised, based on demo feedback last week. Ready for application to production server.

**Comment by TaniaSchlatter** [comment]
Reopening issue to change the Harvard Dataverse logo to the small shield version. This change is being made to deemphasize the Harvard Shield, so that the Dataverse name has a bit more prominence. 
Replace the logo with the file "Harvard-Dataverse_SmallShield” 
<img width="940" alt="h_dv_small_logos_compare" src="https://user-images.githubusercontent.com/15386424/37978689-98fcc2dc-31b4-11e8-8186-2614ef3e503a.png">
![harvard-dataverse_smallshield](https://user-images.githubusercontent.com/15386424/37978729-bb9d5c34-31b4-11e8-93e9-46e2967c21dc.png)

**Comment by mheppler** [comment]
Closed this old issue in favor of #4546 and moved recent comment from @TaniaSchlatter over there.
