### ISSUE TITLE
API: allow file restriction through API

### ISSUE THREAD

**Issue by mdmADA** [IQSS/dataverse#3873]
The new Native API call in Dataverse 4.6.1 to add datafiles to a dataset is very handy but it would be even handier if the file could also be set to restricted (or not) through the call.

POST http://$SERVER/api/datasets/$id/add?key=$apiKey

As Phil indicated after my initial post, providing an API call that can restrict a given file after it has been uploaded would also be helpful.

Thanks!

**Comment by pdurbin** [comment]
@mdmADA I'm so glad to hear this suggestion from a user that I'm going to close the equivalent issue I opened at #2497.

I would say that instead of limiting this functionality to just "add", one should be able to add first and then decide to restrict later (just like in the GUI) before publishing. So, if you want to tweak the title of this issue a bit to reflect this broader scope, please go ahead! 😄

**Comment by mdmADA** [comment]
Sorry - I should have searched for the issue first before posting my own version - overzealous I guess!

**Comment by djbrooke** [comment]
This is being worked on as part of #3776. Thanks @ferrys! I'm going to close this out as a separate issue so that we can track it in one place.

**Comment by pdurbin** [comment]
#4645 is about wanting to be able to tell if a file is restricted or not via API. This was delivered in fa3ca3f and perhaps other commits in pull request #3967 which landed in 4.8.
