### ISSUE TITLE
"Guides" and "Username" in the main navigation are not accessible through keyboard tabbing

### ISSUE THREAD

**Issue by kaitlinnewson** [IQSS/dataverse#3890]
When tabbing through Dataverse on a keyboard, I'm not able to access the "Guides" or "username" dropdown items. This can hinder accessibility for users navigating with a keyboard.

**Comment by jggautier** [comment]
Hi @kaitlinnewson. Thanks for opening this issue. Might be a good candidate for tackling during the hackathon at the Dataverse Community Meeting next week!

**Comment by pdurbin** [comment]
I'll take a look at pull request #4033 by @jacobmakar

**Comment by pdurbin** [comment]
Pull request #4033 looks good. Passing to QA at https://waffle.io/IQSS/dataverse . 

One slightly odd thing to me is that in Chrome, when I hit "tab" the blue box moves until I get to the login box. Then the blue box disappears but it works find to hit "enter" to bring up the dropdown under the login area. I'm just glad it works. At least you can tab to the login area now.

![screen shot 2017-07-31 at 2 34 10 pm](https://user-images.githubusercontent.com/21006/28792433-96c1a2bc-75fd-11e7-8186-9524c444663b.png)

**Comment by djbrooke** [comment]
Hey @kaitlinnewson, I spoke with @kcondon about this briefly, and the behavior is better across several browsers, so I asked him to merge this in and mark it as done for now, since it's incrementally better and the additional cases/fixes are hard to track down. We're going to be taking on some accessibility improvements in the future, and I'd like to revisit tabbing and other issues at that time.

**Comment by kcondon** [comment]
Testing status:
Works on Chrome on both Windows and Mac
Works on FF on Windows with some extra tabs required due to hidden? objects
Does not work on FF or Safari on Mac

See this discussion for how tab index works differently on different browsers and OS:
http://www.alexlande.com/articles/cross-browser-tabindex-woes/
