### ISSUE TITLE
Uploading a file to data set through native api

### ISSUE THREAD

**Issue by omaralsoudanii** [IQSS/dataverse#3891]
I am trying to a upload a file through curl with PHP to an existing data set (server on my local machine)
http://localhost:8080/api/datasets/$datasetid/add?key=$api_key
where $datasetid is the database id of the dataset, But the curl URL doesn't work and keeps returning 404 not found 

> Page Not Found - The page you are looking for was not found. To contact support, please press the Support link above.

> 
i am using the documentation provided here : 
http://guides.dataverse.org/en/latest/api/native-api.html
database version : 
v. 4.2.3 build 55-6561f58  on my local machine

my php code : 
     $postFields=array('file'=>'@'.$file);
        $ch = curl_init($curl_url);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
        curl_setopt($ch, CURLOPT_POSTFIELDS, $postFields);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $result = curl_exec($ch);
        var_dump($result, curl_error($ch));
        die;

trying from terminal returns the same 404 not found page aswell

**Comment by pdurbin** [comment]
@omaralsoudanii hi! The "Support uploading and replacing files with Native API" feature was added in Dataverse 4.6.1 as seen at https://github.com/IQSS/dataverse/releases/tag/v4.6.1 which is why it doesn't work on your 4.2.3 installation. You have two options:

- Upgrade to 4.6.1 or newer.
- Upload files via SWORD instead: http://guides.dataverse.org/en/4.2.3/api/sword.html#add-files-to-a-dataset-with-a-zip-file

**Comment by omaralsoudanii** [comment]
@pdurbin I see ,Thanks for the fast response.

**Comment by pdurbin** [comment]
@omaralsoudanii sure. I realized recently that the API Guide doesn't explain how to get support. I would recommend emailing https://groups.google.com/forum/#!forum/dataverse-community or support@dataverse.org

**Comment by pdurbin** [comment]
@omaralsoudanii oh, since you're using PHP, you might find https://github.com/swordapp/swordappv2-php-library useful. It's listed at http://guides.dataverse.org/en/4.6.2/api/sword.html#client-libraries

In addition, https://github.com/pkp/ojs/tree/ojs-stable-2_4_6/plugins/generic/dataverse might have some interesting code as well. It's used in production in integrate OJS 2 with Dataverse. We list this under http://guides.dataverse.org/en/4.6.2/api/apps.html#php

**Comment by omaralsoudanii** [comment]
@pdurbin Thank you , I already implemented my own code using the native API to manage dataverses,data sets.
The only problem i am facing is clear guide to the JSON parameters of adding/editing a data set .
e.g: what's the required parameters ? where can i find a full list of these parameters and their structure?
Appreciate the help !

**Comment by pdurbin** [comment]
@omaralsoudanii the API Guide needs to be improved. For now, please see discussion in these issues help:

- #3859 API Guide should provide more examples of required JSON payload
- #3777: Native API: attempting to update metadata of a dataset using JSON is confusing and poorly documented, easily resulting in 500 errors (Internal Server Error) and two cases of a NullPointerException
