### ISSUE TITLE
installer assumes postgresql admin user name is 'postgres'

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#3905]
Installer fails when the administrative user is not 'postgres' (as is the case for home-brew installation on OS X).  Can be worked-around by creating appropriate user manually; may be worth fixing in installation script.

**Comment by pdurbin** [comment]
@pameyer as part of this, should what's currently at http://guides.dataverse.org/en/4.6.2/_downloads/default.config be updated to include a new configuration option for the administrative user for postgres? Thanks again for adding the non-interactive installation method in #3799.

**Comment by pameyer** [comment]
@pdurbin It would make sense to me to put it there, but the installer will need to be modified to do anything with it.  Lower-hanging fruit might be to mention in the installation guide that the admin user is assumed to be named `postgres`.

**Comment by pdurbin** [comment]
@pameyer yeah, agreed. Let's figure out the scope of this issue before we estimate it.

**Comment by pdurbin** [comment]
While I was dinking around with upgrading to Glassfish 5 for #4217 I thought "Now that our official installer no longer requires root to run, maybe I'll try setting up Glassfish with the official installer rather than using my own script." Unfortunately, I ran into this issue since I don't have a "postgres" user on my Mac. I started hacking on a solution which is mixed in with Glassfish upgrades at https://github.com/pdurbin/dataverse/commit/d757099c7aefd080f47fcf13f14a8406b42b3e76 but hopefully it will be helpful to someone in the future.

**Comment by pdurbin** [comment]
Fixed in pull request #4244. Moved to Code Review at https://waffle.io/IQSS/dataverse

**Comment by djbrooke** [comment]
@pameyer - is this something that you have interest in code reviewing?

**Comment by pameyer** [comment]
@pdurbin the installer in https://github.com/IQSS/dataverse/pull/4244 is still using `psql -U postgres` in a few places.

**Comment by pdurbin** [comment]
@pameyer and I talked this out after standup (thanks!) and sure enough, there are still some cases of `-U postgres` in https://github.com/IQSS/dataverse/blob/153027390a701e0a54ce71f3249173de2a5993a5/scripts/installer/install

Now I need to decide what I want to do with this issue. It turns out @pameyer opened this issue for someone else during the hackathon and isn't personally invested in it. As far as I know, I may be the only person at IQSS installing postgres with homebrew so I may be the only one affected. http://guides.dataverse.org/en/4.8/developers/dev-environment.html#postgresql continues to be quite light on how developers should install postgres.

I still think back to the "pick your poison" slide I made for http://bl.ocks.org/pdurbin/raw/7847a0642f8bd6601a07c3619b4a35f6/#2

![screen shot 2017-11-01 at 12 19 34 pm](https://user-images.githubusercontent.com/21006/32284878-01482698-beff-11e7-92fd-7041582d47ec.png)

This was my first attempt to use the official installer now that it has two critical features:

- doesn't require root
- works non-interactively (mostly)

For now I'm going to pull this issue and #2443 out of code review. We should probably decouple any effort to improve the installer for developers from Glassfish 5 upgrades. Here are the main things I fixed:

- postgres admin user can be anything (partial fix, per above)
- insecure mode so REST Assured tests will run.
- better at being non-interactive

I think about it some more.

**Comment by pdurbin** [comment]
See https://github.com/IQSS/dataverse/issues/2443#issuecomment-341478282 for an update about some code I pushed that I hope we can return to some day.

**Comment by pdurbin** [comment]
On a related note, there's a new bug report that a custom postgres port doesn't work either: #4365

**Comment by pdurbin** [comment]
> As far as I know, I may be the only person at IQSS installing postgres with homebrew so I may be the only one affected.

For what it's worth, while working on pull request #4721 I switched away from postgres installed by homebrew in favor of the enterprisedb version we recommend in the dev guide.

**Comment by donsizemore** [comment]
This isn't just a homebrew problem; a lady just hit this installing against RDS. Her work-around was to make the RDS admin user `postgres` but as more installations will move to some cloud or another, we might want to allow a configurable Postgres admin user, or at least document the RDS case in prerequisites.rst.

**Comment by pdurbin** [comment]
"1) The PostgreSQL administrator's name is hard-coded in the script but may vary. It should default to "pgadmin" but should be overrideable with a variable." -- @orazionelson at https://groups.google.com/g/dataverse-community/c/koHCFkUw2kw/m/e15be2hgAgAJ

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
