### ISSUE TITLE
Add pop-up preview of PDF Files 

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#3914]
We currently show a pop-up image of files (such as .png, jpg etc.) on the home page and dataset page. The request is to extend this functionality to pdf files.

**Comment by djbrooke** [comment]
From @sekmiller:

There are (at least) 2 things that may prevent it:
1) The Dataverse installation requires the ImageMagick plug-in which it uses to create the preview image.
2) There is a size limit on pdf files which may be transformed. (This limit is a setting which may be changed.)

**Comment by landreev** [comment]
@sekmiller and I spoke about this via email yesterday; 
So yes, there was some initial confusion: 
We already support previews and thumbnails for pdf files; in general, and in our production in particular. 

This particular request came from a specific user, who has a bunch of large PDF files, that are above the size limit we use. (the size limit that we use to determine whether to generate thumbnails and previews, or not). 

We purposefully use a 10x lower limit for PDFs than for regular images; because PDF is generally more expensive to process. 

Steve asked if we could increase that limit. It is true that the current limit is not based on any particularly scientific research. So yes, we could probably increase it somewhat... Still, it wouldn't solve it for everybody. Somebody's files will always be above that limit. Just like somebody's JPEGs will always be above the image size limit... So I always assumed that the way to really solve this would be to a) Keep the limits somewhat low, to prevent the system from being overloaded in real time by having to do all this extra processing, while blocking pages, but b) Have an outside-the-application process - a cron job, or something of that nature - to generate thumbnails and previews that were not generated by the Dataverse; it could be run under a high nice level; or otherwise in a way that would only utilize extra CPU cycles, when available. So all the previews, even for larger files, will eventually get cooked; without subjecting the application to performance hits in real time. 

That would mean that they would not see the previews immediately after uploading the images. But I feel that that's still better than to have a page blocked/frozen while the thumbnails are getting generated in real time.

**Comment by sekmiller** [comment]
Closing. This is a known behavior and Sonia had already discussed it with the requester before he brought it up with me.
