### ISSUE TITLE
Develop S3 storage driver

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#3921]
This came up during the meeting with the LTS, when the plans of moving the Dataverse production onto a cloud were discussed. S3 will have to be supported as the main production storage mechanism, since local disk space will no longer be available. 

The existing swift driver can be used as a basic model. 

#3919, just opened, is not a direct dependency, but, for the purposes of this production move both of the issues will need to be addressed at the same time. As we will not be able to continue storing the dataset-level files, like cached exports, etc., for the same reason as the above - as local file system space will no longer be there.

**Comment by matthew-a-dunlap** [comment]
Here are some notes on the state of the S3 code as I leave for vacation:

The code is definitely far far from complete, but I was able to port over some sample code from the S3 example and get it working in S3AccessIO.java. You should be able to upload a data file and have it show up in the S3 bucket (naming is not correct tho). Right now the code deletes the bucket before every upload, which obviously needs to change.

Note in the pom that the import is for <artifactId>aws-java-sdk-bom</artifactId> . This version takes all the aws sdk dependencies and has renamed them so there are no package conflicts. We were having issues with Glassfish's version of jackson conflicting with minimum aws requirements. There may be a version of this dependency that only pulls in the S3 code, I didn't get to check.

I'm not certain what approach we should take in regards to folder structure. AWS has a limit of 100 buckets per account so we probably only want one bucket for the full dataverse application (you can apply for an increase tho). There are no true folders in AWS, but if you name things with folder structure they show up as folders.

**Comment by pdurbin** [comment]
@ferrys and I just discussed the code as of 39375c8. We found `~/.aws/credentials` which is what @matthew-a-dunlap must have been talking about when told me that AWS has a place it expects to find credentials. We might consider moving this to `/usr/local/glassfish4/glassfish/domains/domain1/config/s3.properties` to match `swift.properties` as documented at http://guides.dataverse.org/en/4.7.1/installation/config.html#file-storage-local-filesystem-vs-swift . She seems to agree that 1 bucket per installation of Dataverse makes sense in an S3 world but that we should continue to use 1 container per dataset in the Swift code. Folder structure is out of scope for this issue but we did discuss #2249 a bit and would like to use @leeper 's folder hierarchy example from https://osf.io/xfj5h/ via https://projects.iq.harvard.edu/dcm2017/agenda as a use case in the future. Here's how it looks:

![screen shot 2017-07-28 at 1 46 08 pm](https://user-images.githubusercontent.com/21006/28729644-27456efa-739b-11e7-8276-410830204221.png)

@ferrys is pretty sure that for Swift we should continue to store files in a single container rather than using Swift's folder structure features, which are complicated. I'm just concerned about having someday having duplicate file names that are in different directories. We don't know a lot about how S3 works but she said Swift also will have files show up in folders if you name them with slashes in them.

**Comment by ferrys** [comment]
I looked into both Swift and S3 in terms of folder structure and it seems like you can store multiple of the same file in the same bucket/container IF they are in different folders. So, we shouldn't have a problem there. 

@pdurbin I think we could definitely research altering the implementation of Swift as well, but I don't know much about how the Swift API deals with folders within containers, so I would say it is also out of scope.

**Comment by ferrys** [comment]
In order to configure the credentials for AWS, you need access to your AWS Access Key ID and your AWS Secret Access Key. Once you have them both, you should run `pip install awscli` (or if you have the Anaconda version of Python, `pip install -i https://pypi.anaconda.org/pypi/simple awscli`) and then `aws configure` and enter your credentials.

**Comment by ferrys** [comment]
In order to run this branch now, you will need to set the jvm option for the bucket name. You can do this with the command `asadmin create-jvm-options "-Ddataverse.files.s3-bucket-name=your_bucket_name` and then restarting glassfish.

**Comment by bsilverstein** [comment]
Quick progress report / next steps forward for this issue:

As @ferrys mentioned, to configure your Dataverse installation to use S3, there are two jvm options to configure. There is also the database update script from 3919's branch, which has been renamed. Hence, you'll need to run:
`/scripts/database/upgrades/upgrade_v4.7.1_to_v4.8.sql`

and from glassfish4/glassfish/bin:

`./asadmin $ASADMIN_OPTS delete-jvm-options "\-Ddataverse.files.storage-driver-id=file"`
`asadmin create-jvm-options "-Ddataverse.files.storage-driver-id=s3"`
`asadmin create-jvm-options "-Ddataverse.files.s3-bucket-name=your_bucket_name"`

Note that for work on this issue we are using the bucket: _testiqss-1239759fgsef34w4_

**Still to do:**

- [ ] Bug: Manually uploaded dataset thumbnails are not displayed on dataverse.xhtml page while configured for S3. Easily repeated to produce stacktrace, starting with `SearchIncludeFragment`
- [ ] Bug: Dataset thumbnails generated from image formatted datafiles are also not being displayed on dataverse page, but _are_ displayed on dataset page.
- [ ] Bug: Ingested tabular files are not having their contentType set properly (returned as null). @rbhatta99 has been delving into this.
- [ ] Documentation: Need to properly document in installation guide how to configure the JVM options mentioned above for installations using S3 storage. Hoping @dlmurphy can review before finalizing.
- [ ] Testing: I've made an integration test named `S3AccessIT.java` which currently just tests the storageIdentifier prefix (s3://) for a new datafile while S3 storage is configured. Not sure how this can be expanded to test more functionality as Amazon is very... proprietary? Same goes for JUnit tests (which don't exist yet for S3AccessIO).

Feel free to expand on any other remaining work for this issue I may be forgetting!

**Comment by pdurbin** [comment]
Pull request #4042 was just made and I'm assigning myself to this issue to code review it.

**Comment by pdurbin** [comment]
I just requested a number of changes to pull request #4042.

**Comment by matthew-a-dunlap** [comment]
I (along with Brian & Rohit) have been looking into an issue where javax.mail breaks when using the AWS SDK bundle. We were originally using the whole SDK bundle as AWS specifically created this with its dependencies renamed, and we were having dependency issues with Jackson/glassfish. Importing only the required portions of the SDK still causes the Jackson issue, and there is not a prepared "bundle" for only AWS S3/Core. I have also tried using a sufficiently old version of the AWS SDK may not cause these dependency issues, but our S3 driver was written for the current SDK.

There are 3 possible solutions I can think of:
1. We can build our own version of the SDK, only pulling S3/Core and creating a version of bundle only with Jackson inside. Some details on this (as well as other info on the bundle) are documented here: https://aws.amazon.com/blogs/developer/java-sdk-bundle/ 
2. Rewrite our code to use an older version of the SDK that we know does not blow up. I do not think this is a great solution if we want to have a healthy codebase
3. Dig deeper into either the javax.mail or jackson issue and see if there is another option to work around it in Maven. I have no idea how feasible this is.

On Monday I plan to dig deeper into this and try building the SDK, unless someone else with more Maven experience wants to grab it.

**Comment by bsilverstein** [comment]
Still in the process of resolving the dependency mishap, but while reading through the [AWS dev guides](http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/setup-project-maven.html) I did notice that in the `aws-java-sdk-bom` the _bom_ is "bill of materials" and having that allows you to cherrypick individual [Amazon] SDK modules and ensure their compatibility with each other.

Moreover, that portion of the guide (linked above) reads:

 _"You can now select individual modules from the SDK that you use in your application. Because you already declared the SDK version in the BOM, you don't need to specify the version number for each component."_

and subsequently shows the following example of having two of Amazon's SDK modules managed by the bom module:

```<dependencies>
  <dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-java-sdk-s3</artifactId>
  </dependency>
  <dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-java-sdk-dynamodb</artifactId>
  </dependency>
</dependencies>

Note the `aws-java-sdk-s3` artifact! We may be able to resolve things once we know exactly which modules (besides S3) we will need in tandem with the bom. Could only be the S3 module for all I know, but that's to be determined.

**Comment by bsilverstein** [comment]
Regarding the dependency showstopper, we've seemingly resolved the problem after a couple days of trying inconsistently-working fixes across four or five unique environments.

The issue stems from the `aws-java-sdk-bundle-1.11.172.jar` [any version] roping in Amazon Simple Email Service, which duplicates some components of javax.mail including a rogue `javamail.providers` file. Using a maven plugin in `pom.xml` called TrueZip the app will now remove the file from the sdk-bundle jar within both the project's  `dataverse/target/dataverse-4.x.x.war/WEB-INF/lib/aws-java-sdk-bundle-1.11.172.jar/META-INF/` and also the exploded `dataverse/target/dataverse-4.x.x/WEB-INF/lib/aws-java-sdk-bundle-1.11.172.jar/META-INF/` -- though I believe the .war is the important one to remove.

The plugin is appended at the bottom of `pom.xml` on this branch.

**Comment by kcondon** [comment]
-Dataset directory is still created locally when s3 configured though it is empty.

**Comment by kcondon** [comment]
Issues:
-Cannot delete an s3 file when configured for local file, works on s3
-Downloading many files in zip fails due to putting 1000 file ids on url.
