### ISSUE TITLE
Tooltips - Field name hover text more visible

### ISSUE THREAD

**Issue by CCMumma** [IQSS/dataverse#3925]
4.6.1, TDR, U of Houston UI request:

"It is not obvious that hovering over field names gives hints, but they are very helpful.  How can we make them more visible?"

The team at TDR use a little 'i' for information next to places where hover text is available in Vireo, but we are not UI experts...

**Comment by pdurbin** [comment]
@CCMumma I can imagine what the "i" might look like but please feel free to attach a screenshot to this issue.

**Comment by CCMumma** [comment]
![vireo_i_1](https://user-images.githubusercontent.com/12702471/27386543-d0f271f8-565b-11e7-9744-1ec0c2c20bec.JPG)
![vireo_i_2](https://user-images.githubusercontent.com/12702471/27386544-d10ed6e0-565b-11e7-935a-f45504788b7a.JPG)
![vireo_i_3](https://user-images.githubusercontent.com/12702471/27386545-d1288856-565b-11e7-94a2-e77df8de2ced.JPG)

**Comment by TaniaSchlatter** [comment]
Thanks for posting, @CCMumma. We started to look at how we display text (help text, messages, alerts) overall, and have been reconsidering how we use the "i" symbol (to emphasize informational text). On forms like the create dataset page, all headers have tool tips on rollover, so using a symbol like TDL probably isn't the right approach, but this is good info to have.

**Comment by pdurbin** [comment]
#3501 is about tool tips as well.

**Comment by TaniaSchlatter** [comment]
Elevating the importance of this issue. Per meeting with @sbarbosadataverse, data depositors are not seeing rollover tool tip messages when they are creating datasets, and it is reducing the quality of the titles and other metadata requested when creating a new dataset, and to a lesser degree, a new dataverse. 

In some cases users are putting a file name in the "title" field of a dataverse. 

Sonia mentioned that in addition to titles, there is evidence of confusion about roles that would likely improve if users saw the tool tips with role descriptions.

**Comment by dlmurphy** [comment]
I looked into best practices for displaying tooltips in non-mobile applications. The most common solution I saw was to use a dedicated tooltip icon that displays the tooltip when hovered over. 

There are three predominant styles of tooltip icon:
1. ![tooltip2](https://user-images.githubusercontent.com/22962740/31033232-4243d228-a52d-11e7-9e60-e0abf1429127.PNG)
Question marks, usually contained in a circle.

2. ![tooltip3](https://user-images.githubusercontent.com/22962740/31033256-58ff256c-a52d-11e7-8daa-716a5d43d6ed.PNG)
Cartoon speech bubbles, usually containing lines or ellipses to represent text.

3. ![tooltip4](https://user-images.githubusercontent.com/22962740/31033283-6ee24de6-a52d-11e7-8ee4-03b74b17cc60.PNG)
"i" for information, usually contained within a circle or speech bubble. Meant to reference signs typically seen above information desks in the real world. Usually serifed, often italicized, as seen here:
![tooltip5](https://user-images.githubusercontent.com/22962740/31033373-c46963d0-a52d-11e7-9248-1a2c616b356f.PNG)

While downloading icons, I saw a good example of the question mark tooltip icon in action on the [Noun Project's download page](https://thenounproject.com/search/?q=tooltip%20text&i=205325):
![tooltip0](https://user-images.githubusercontent.com/22962740/31033442-0fcae088-a52e-11e7-936d-a532e4c899e7.PNG)
![tooltip1](https://user-images.githubusercontent.com/22962740/31033443-116d45fc-a52e-11e7-9fa8-d0deb3a69439.png)

**Comment by jggautier** [comment]
Here are some other ideas:

@TaniaSchlatter mentioned that the tooltip on the page's first field label could display when the page loads, to make the user aware that the tooltips exist and where they exist. Maybe the tooltip is shown for several seconds then disappears, or stays until the mouse moves.

Another idea is having a tooltip on the text box, where users are more likely to hover in order to start typing, in addition to on the field labels (or on an icon like those suggested).

![0-aeeoqfpy0bqcshxz](https://user-images.githubusercontent.com/18374574/31033956-0d18a7b0-a530-11e7-9a01-38ff911d0831.png)

**Comment by TaniaSchlatter** [comment]
Here's a little more research from the IxDA list. Hoober is a recognized expert on this topic: 

Steven Hoober: 

> Redesign your page/app/flow so as to not leave any doubt in user's minds, so they won't NEED to hover over anything.

Seriously, that's my advice, and how I design everything. I do not even include help, FAQs (ugh, a whole other topic: ask me sometime), in page help, app tours, etc. when planning for design. No help. It just works or you failed. 

And, this works! The basic tactics (clarity, brevity, no jargon, label all icons) works and with a bit of actual u-test so you have real customer feedback, you can make products that are used e.g. 100 million times a day and are not even tracked by Customer Care as they never cause a problem.

>

**Comment by pdurbin** [comment]
Something to think about: Does the hover text work from mobile?

**Comment by TaniaSchlatter** [comment]
Hover text does not work on mobile @pdurbin.

**Comment by TaniaSchlatter** [comment]
Add a "?" symbol to indicate when tooltips are present, as shown to stakeholders in Dataset page mockups. Rolling over the symbol should replace rolling over text, and trigger the display of tool tips.

Appearance:
Bootstrap question-sign symbol. Standard link color for the symbol, or ghost to 50%, with full color on rollover.

Behavior:
Rolling on the symbol reveals the tooltip. Rolling off hides it. On mobile, click the symbol to reveal the tool tip. Click off to hide it. 

![screen shot 2019-02-20 at 12 09 14 pm](https://user-images.githubusercontent.com/15386424/53110158-60b50f80-3508-11e9-84d0-2c0f2cf6c945.png)

**Comment by mheppler** [comment]
Got most of the heavy lifting done. Putting up a checklist to review progress and outstanding tasks.

- [x] Add new `glyphicon-question-sign` icon next to label text, and move tooltip to that `span`
- [x] Fix popover layering issue when used in `dialog` popup (related to #2586)
- [x] Remove old, unused javascript from dv_rebind_bootstrap_ui.js (there is still more...)
- [ ] Remove tooltips from view mode that do not provide value (e.g. manage-templates.xhtml)
- [ ] Determine what colors are required if gray from `text-muted` style class is not satisfactory
- [ ] Remove unnecessary style class `tooltiplabel`
- [ ] Review use of other `i` and `?` icons (e.g. dataset citation block)
- [ ] Update example code provided in Style Guide > Patterns > Form section
- [ ] Return `initPopover()` back to dataverse pg to fix (?) broken "HTML tags" popover on mobile, determine why it's broken on dataset pg
- [ ] Refactor many (9?) `post_edit_dv_general_info()` type functions in dv_rebind_bootstrap_ui.js to use `bind_bsui_components()` in various btn `oncomplete` attributes in XHTML
- [ ] Create tooltip inventory doc

**Comment by mheppler** [comment]
Should be done here. Just have the documentation left. I had pointed out to @TaniaSchlatter that the issue #3865 basically asks for documentation in the Style Guide of the tooltip, icons and help-block text, so I will make sure that the documentation covers everything requested in that issue.

>Document the existing types of messages from the visual UI standpoint.

>Review existing forms of system feedback and guidance, focusing on documenting the current intention for:
>• error messages
>• system/status messages
>• help/directive messages
>• tool tips
>• + any other types

**Comment by mheppler** [comment]
Moved form label tooltips onto `?` icons next to the label text. Outlined these changes in the Style Guide. Also expanded the changes in the Style Guide to increase the documentation of the various message types across the UI. Applied some of these style guidelines to pages that did not have the appropriate icon or style classed. (Related to #3865.)

These various changes have been applied to the following pages:
- dashboard.xhtml
- dataset-citation.xhtml
- dataset-license-terms.xhtml
- dataset-versions.xhtml
- dataset-widgets.xhtml
- dataset.xhtml
- dataverse.xhtml
- dataverseuser.xhtml
- editFilesFragment.xhtml
- editdatafiles.xhtml
- explicitGroup-new-dialog.xhtml
- file-configure-dropdown-fragment.xhtml
- file-data-access-fragment.xhtml
- file-download-button-fragment.xhtml
- file-download-popup-fragment.xhtml
- file-request-access-popup-fragment.xhtml
- file-versions.xhtml
- file.xhtml
- filesFragment.xhtml
- guestbook.xhtml
- harvestclients.xhtml
- harvestsets.xhtml
- loginpage.xhtml
- manage-groups.xhtml
- manage-guestbooks.xhtml
- manage-templates.xhtml
- metadataFragment.xhtml
- mydata_fragment.xhtml
- /oauth2/convert.xhtml
- /oauth2/firstLogin.xhtml
- package-download-popup-fragment.xhtml
- permissions-manage-files.xhtml
- permissions-manage.xhtml
- roles-assign.xhtml
- roles-edit.xhtml
- search-include-fragment.xhtml
- /search/advanced.xhtml
- /subset/gui_subset.xhtml
- template.xhtml
- termsofuse.xhtml
- themeAndWidgetsFragment.xhtml

**Comment by pdurbin** [comment]
It looks like the Style Guide has been significantly rewritten. For example, "Alerts" looks like this for Dataverse 4.11 at http://guides.dataverse.org/en/4.11/style/patterns.html#alerts

![screen shot 2019-03-05 at 1 20 35 pm](https://user-images.githubusercontent.com/21006/53827593-7afbde00-3f49-11e9-96ad-1ab38df4e588.png)

Now, in pull request #5596 the "Alerts" page looks like this with a new "Message Classes" section added:

![screen shot 2019-03-05 at 1 19 24 pm](https://user-images.githubusercontent.com/21006/53827517-50aa2080-3f49-11e9-8f21-e9c06c1b59df.png)

There are probably a lot of other changes to the Style Guide beyond this "Alerts" change but that's the one that jumped out at me.

Unfortunately, I can't build the guides because IQSS Jenkins is not well: #5602 

I hear that @TaniaSchlatter is interested in seeing the guides as well so I guess this issue should stay in code review until Jenkins is fixed? I'm not sure.

The code changes themselves look fine. @mheppler has provided a list of the many xhtml pages he has improved above. Or one can look at the pull request. It's a pretty big "diff" but nothing scary jumped out at me.

**Comment by pdurbin** [comment]
@TaniaSchlatter you can see the new version of the Style Guide at http://guides.dataverse.org/en/3925-tooltip-icons/style/patterns.html

**Comment by TaniaSchlatter** [comment]
The example in the guides (see image) that shows the tool tips should look and work as is intended on the site. 
<img width="668" alt="screen shot 2019-03-05 at 4 17 54 pm" src="https://user-images.githubusercontent.com/15386424/53838211-742d9500-3f62-11e9-9f7b-651e3f4c439d.png">

**Comment by mheppler** [comment]
Fixed tooltips functionality in guides as requested (see screenshot below), removed outdated analytics code (related to #4660).

![screen shot 2019-03-05 at 5 36 16 pm](https://user-images.githubusercontent.com/687227/53842345-33874900-3f6d-11e9-8454-00741f8f489a.png)

**Comment by mheppler** [comment]
Confirmed with @TaniaSchlatter that the Style Guide improvements requested in _Style guide – document messaging text and visual styles #3865_ are covered here in this issue. I have closed that issue.

**Comment by kcondon** [comment]
@mheppler Change password page tool tips have no text

**Comment by mheppler** [comment]
Looked into the issues reported by Kevin in my iOS browsers (Chrome, Firefox and Safari) and was able to replicate them, so thankfully it wasn't a browser/OS issue.

The edit btn on the account pg, and the template select dropdown were missing the necessary `oncomplete="javascript:bind_bsui_components();"` attribute in order to rebind the javascript functionality of the tooltips to the elements on the page, after the page loads.

Kevin also dug a little deeper (thank you) into the metadata blocks issue and discovered it's an issue in `develop` as well as a similar issue in 4.11, so he opened a new issue #5613 to track that.

Passing back to QA.
