### ISSUE TITLE
Make dev guide standalone guide and reorganize 

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#3936]
Current you have to switch back and forth between dev guide and installer guide and that has been a challenge for people. This ticket is to have the dev guide be standalone to make the process more straightforward - provide distinct clear instructions for Mac vs Linux.

**Comment by scolapasta** [comment]
related #3905

**Comment by pdurbin** [comment]
http://guides.dataverse.org/en/4.7/developers/dev-environment.html needs works. People find it confusing.

**Comment by djbrooke** [comment]
There are (at least) two ways to approach this and we should discuss the best solution for each.

- As a developer, I want to go to one place and only review the information that I need to set up a development environment so that I can contribute to Dateverse.
- As a Dataverse Installation Administrator, I want to go to one place and only review the information that I need to set up a production instance of Dataverse at my institution.

**Comment by pdurbin** [comment]
I'm closing this in favor of #4419 where I verified that the "dev environment" page doesn't refer to the installation guide at all. I also explained what Linux users need to do to get set up and asked Windows users to comment on #3927.
