### ISSUE TITLE
TwoRavens can't work when the dataset’s metadata contains non-English character.

### ISSUE THREAD

**Issue by pengchengluo** [IQSS/dataverse#3968]
Hi, I installed dataverse 4.7 along with TwoRavens on CentOS 7. When I test the function of TwoRavens with 50by1000.dta provided by the manual, I find that TwoRavens seems  don't support non-English characters.

For example, when the metadata of dataset contains Chinese characters, The rApache will return "500 Internal Server Error" (see below figure). And the Apache log file will contain "Error : is.character(txt) is not TRUE". I think the reason is that the R code don't support  non-English characters. 
When I change all metadata into English, it works correctly.
![image](https://user-images.githubusercontent.com/7343585/27668731-5c72b8be-5cb5-11e7-9927-f50c3f889b77.png)

**Comment by pdurbin** [comment]
@pengchengluo hi! Thanks for including screenshots! Can you please tell me which version of Dataverse you're running? Also, is the bug triggered by clicking the "Estimate" button?

**Comment by pengchengluo** [comment]
I used the Dataverse 4.7 and TwoRavens from https://github.com/IQSS/TwoRavens/archive/a6869eb.zip. 
The problem triggered by the first load of TwoRavens, i.e. when I click the "explore" button in dataset page and follow the link enter into TwoRavens.  

I also try it in harvard dataverse repository, but there is no problem! Maybe it is caused by some configuration reasons. @pdurbin Thanks !


![image](https://user-images.githubusercontent.com/7343585/27716142-c82bc294-5d6e-11e7-8899-463a0f7af1d9.png)

**Comment by pdurbin** [comment]
@pengchengluo I was playing soccer with @tercer tonight and he said the folks at http://dvn.fudan.edu.cn/dvn/ might know the fix. Are you in touch with them?

Also, rather than "master" you should be using https://github.com/IQSS/TwoRavens/archive/a6869eb.zip . We recently rewrote the installation guide for TwoRavens and that's the specific version that's required. For details, pleas see http://guides.dataverse.org/en/4.7/installation/r-rapache-tworavens.html#install-extra-r-packages .

**Comment by djbrooke** [comment]
Hi @pengchengluo - I'm going to close this out as it appears to be a TwoRavens issue. The folks on that team should be able to help you out if you create an issue at https://github.com/TwoRavens/TwoRavens
