### ISSUE TITLE
Allow file restriction in a Swift installation 

### ISSUE THREAD

**Issue by ferrys** [IQSS/dataverse#3977]
We want to allow users of a Swift backend to restrict their files. Validated users will be able to access files through a temporary URL as well as through the Dataverse UI.

**Comment by ferrys** [comment]
To provide access to compute through Sahara using temporary URLs, we need to provide the compute environment with the signature and expiration time alongside the container name. Also, @jeremyfreudberg is working to enable temporary URLs in Hadoop.

**Comment by TaniaSchlatter** [comment]
Compute on private data will work for one file if the user has permission. Keep the "Compute" button on both the dataset and the file page for private data. Add popups that explain the situation to the user.
Dataset page: Access to compute for this dataset is at the file level and determined by permission. 
File page: Access to compute on this file is restricted. 
Is there text we can provide that instructs users on how or where they can review access for a file? @dlmurphy to review.

**Comment by dlmurphy** [comment]
On the Dataset page, when a user selects a restricted file and clicks the Compute button, we can display a popup that's almost identical to this popup that is currently in place for the Download button:
![requestmessage](https://user-images.githubusercontent.com/22962740/28838164-7e8864fe-76bd-11e7-92d8-d553110ca0d7.PNG)
(replace "downloaded" with "computed on")

Here's a view of what a dataset with restricted files looks like in Harvard Dataverse currently:
![request2](https://user-images.githubusercontent.com/22962740/28838232-c1439df4-76bd-11e7-8f90-d20f9b1483bd.PNG)

On the file page, the download button is completely replaced by the Request Access button, which displays this message when clicked:
![request3](https://user-images.githubusercontent.com/22962740/28838440-52bed67c-76be-11e7-8b25-aa39fb4a7d98.PNG)

If we decide to have the Request Access button replace BOTH the download AND compute button, then this message would still work.

**Comment by djbrooke** [comment]
Thanks @TaniaSchlatter @ferrys @dlmurphy for the discussion and the next steps. Is this something that's available for other team members to pick up or is @ferrys working on this?

**Comment by landreev** [comment]
@dlmurphy @ferrys Hey, I tried reading through the last messages, but it's not immediately clear as to what needs to be done. 

Like, what's up with the "if we decide ..." - has it been decided or not? 

Am I reading it right, that the compute button is always there, whether the files are downloadable or not... So, we no longer require that all the files are downloadable.  And, if we find at least one file that's downloadable, the compute button redirects to the compute button with the url for this unrestricted file; otherwise, if all the files are restricted, the compute button instead shows the popup informing the user that the file is restricted. (?)

This thing about "request access" replacing the "download" button... Note that this does not happen for every restricted file automatically; the "request access" feature needs to be specifically enabled. If it's not enabled, the download button just disappears. 

OK, this is what I'm going to do: I'll modify the file page (not the dataset page). It sounds like it's more straightforward there -  if the file is downloadable to the user, the compute button does what it's doing now; if not, the button is still there, but it shows the popup instead. (is this correct?)  So I'll add that popup, and then you can use it as a model to modify the dataset page as well. 

I don't think we need to say anything about requesting access in that "compute" popup; because if requesting access is an option, the button for it it will be shown clearly further down the page. I'll just make it say "... because you don't have the permission to download the file" - feel free to modify it as needed.

**Comment by ferrys** [comment]
@landreev sure, sounds good. I can configure when the pop-up needs to be shown if you are able to create a model on the file page. 

Currently, I created a function called showComputeButton() which determines whether the compute button should show up, but I should probably alter it to just determine if there are any swift files and then the access pop-up will be rendered if the user doesn't have access to them. 

An additional note is the lack of a compute button on the dataset page if there is only one data file. I believe this is because the compute button is in the same div as the download button that only appears if there are two or more files.

**Comment by landreev** [comment]
@ferrys
OK, I've added the popup to the file page. The popup is defined in file.xhtml ("computeAccessDeniedPopup"), it's called from file-download-button-fragment.xhtml. 
I'm assuming you'll want to create a popup like this in dataset.xhtml; (should be easier, rather than trying to have the same popup to be used by both pages...)

I haven't looked at the compute button on the dataset page not showing up when there's only 1 file... but sounds like the button just needs to be moved out of the div - ?

**Comment by ferrys** [comment]
@landreev good call. I'll check it out & add the popup for the dataset page.

**Comment by ferrys** [comment]
From what was discussed yesterday with @TaniaSchlatter and @dlmurphy, we've come up with two options for the compute pop-up display. Either we can do what was suggested above and implemented by Leonid:
<img width="1192" alt="screen shot 2017-08-03 at 10 06 12 am" src="https://user-images.githubusercontent.com/15023025/28936876-11ba43d8-7857-11e7-9742-4ab9a5daeaa6.png">

<img width="632" alt="screen shot 2017-08-03 at 10 06 20 am" src="https://user-images.githubusercontent.com/15023025/28936880-16da2bbc-7857-11e7-8967-8d2aeb33e121.png">


OR, we can make the compute button shaded and "unclickable" unless a user has access:
<img width="1199" alt="screen shot 2017-08-03 at 2 19 40 pm" src="https://user-images.githubusercontent.com/15023025/28936940-37eec088-7857-11e7-8cc6-38d6dbc61a80.png">

<img width="1207" alt="screen shot 2017-08-03 at 2 20 04 pm" src="https://user-images.githubusercontent.com/15023025/28936958-482c98f8-7857-11e7-90b9-1ea128b06dc7.png">

So @TaniaSchlatter @mheppler @dlmurphy which option would you prefer to implement?

**Comment by ferrys** [comment]
Some updates -
We decided to scrap the pop-ups and instead only show the compute button on the file level on the dataset page, similar to the download button (thanks @mheppler!) :
<img width="1158" alt="screen shot 2017-08-04 at 2 34 49 pm" src="https://user-images.githubusercontent.com/15023025/28982418-c15af4aa-7923-11e7-8c5c-34713b6469a8.png">

<img width="1163" alt="screen shot 2017-08-04 at 2 37 38 pm" src="https://user-images.githubusercontent.com/15023025/28982419-c3af729e-7923-11e7-9607-62b416536ac0.png">
<img width="1171" alt="screen shot 2017-08-04 at 2 53 06 pm" src="https://user-images.githubusercontent.com/15023025/28982678-b548e234-7924-11e7-8635-e14baf2cdd4f.png">


Additionally, on the file page :

<img width="1173" alt="screen shot 2017-08-04 at 2 51 54 pm" src="https://user-images.githubusercontent.com/15023025/28982683-bc1e4f72-7924-11e7-91ae-e8adaab45765.png">
<img width="1208" alt="screen shot 2017-08-04 at 2 49 54 pm" src="https://user-images.githubusercontent.com/15023025/28982681-b9782fe0-7924-11e7-80cc-60c3fcf0e72d.png">

**Comment by pdurbin** [comment]
I assigned myself to code review pull request #3989.

**Comment by kcondon** [comment]
-Info level in server.log when create dataset with local files:
  FilePage: Failed to cast storageIO as SwiftAccessIO (most likely because storageIO is a FileAccessIO)]]
