### ISSUE TITLE
disabling harvesting schedule doesn't disable harvesting schedule

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#3985]
Tested on 4.5 and 4.7. Walk through admin dashboard wizard to edit harvesting client settings. Set schedule to "None" and save changes, but the schedule remains in place.

Setting harvestingclient.scheduled to 'f' and refreshing the page appears to disable it.

**Comment by djbrooke** [comment]
Thanks @donsizemore. We'll take a look.

**Comment by kcondon** [comment]
Tested the fix and the UI state is now corrected due to this fix. However, there is an underlying timer and harvesting status issue that also needs to be addressed to make this work well -when the web server running the harvest is restarted, any current harvest job is halted. So, upon restart, any running harvest job needs to have the flag harvestingnow in the table harvestingclient set to 'f' . There also seems to be a proliferation of timer jobs in the EJB__TIMER__TBL which likely means they are not being cleaned up when deleted/disabled. This may need a separate ticket, will discuss in standup.
