### ISSUE TITLE
scrolling on UI not working in firefox for datasets with 25+ files

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#3990]
https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/00097-8

as far as I can recall this was working fine but trouble shooting for a user today discovered we can't scroll past the first set of 20 or so files in firefox for this dataset. Chrome tested and works fine.

**Comment by jggautier** [comment]
Just FYI, it's working on my copy of Firefox, 54.0.1 (64 bit) for OS X.

**Comment by mheppler** [comment]
Was not able to replicate this bug for this dataset on production in Firefox, Chrome or Safari.

@sbarbosadataverse if this is still an problem, let us know, and provide any additional information we may be missing. Otherwise, if there is no longer a bug for this dataset, I would suggest closing the issue.
