### ISSUE TITLE
rdata ingest defaults

### ISSUE THREAD

**Issue by acoppock** [IQSS/dataverse#3999]
Would suggest the following logic:

if .rdata contains 1 and only 1 data.frame --> ingest
otherwise do not ingest and simple post the file unmolested.

crucially, if .rdata contains > 1 data.frame, it's odd to ingest the "first" one, however that is determined (alphabetical?)

also, since .rdata files can include other objects beyond data.frames that are very useful, seems best to leave them be.

**Comment by djbrooke** [comment]
Thanks @acoppock. We're finishing up a big push on improving ingest now (#3767), but we'll revisit the ingest behavior in the future and I hope that we can work with you to make this better.

Note to future self: consider the messaging about how we'd potentially handle ingest differently based on number of data.frames

**Comment by pdurbin** [comment]
> if .rdata contains 1 and only 1 data.frame --> ingest otherwise do not ingest and simple post the file unmolested.
> 
> crucially, if .rdata contains > 1 data.frame, it's odd to ingest the "first" one, however that is determined (alphabetical?)

@shlake has the same suggest for Excel ingest. Instead of ingesting the first sheet, like we do now, she thinks ingest should not proceed and the depositor should see a message about this: https://github.com/IQSS/dataverse/issues/8518#issuecomment-1272673522

Also, these issues are related:

- #6985
- #6678
- #7249 
- #8526

@acoppock I remember your excitement over opening #4000 (a nice round number and we fixed it). Before long our issues will have five digits. 😄 

Please keep the suggestions coming!

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
