### ISSUE TITLE
Batch Delete: Batch delete of files fails for non super user if dataset has thumbnail. 

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4024]
Reported by a user, see RT 251413

User reported that they could not delete all files from a dataset using the top select all checkbox.
This happens if the user is not a superuser and at least one of the files generates a thumbnail that becomes the dataset thumbnail, such as an image file or pdf. It can happen with a single image file if it is the one used for dataset thumbnail but will prevent the batch from deleting. The server log error is:

Caused by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: update or delete on table "dvobject" violates foreign key constraint "fk_dataset_thumbnailfile_id" on table "dataset"
  Detail: Key (id)=(216596) is still referenced from table "dataset".
Error Code: 0
Call: DELETE FROM DVOBJECT WHERE (ID = ?)
	bind => [1 parameter bound]
Query: DeleteObjectQuery([DataFile id:216596 name:null])

Note, there is a workaround: mark all for delete, deselect the one file used as thumbnail, batch delete, then delete the last file.

**Comment by djbrooke** [comment]
@rbhatta99 - going to move this back to not started for now, feel free to pick it up once the Primefaces spike is moved on!

**Comment by landreev** [comment]
I've pulled this one back into dev., to quickly resolve the controversy with unintercepted exceptions, when things go wrong trying to delete physical files.

**Comment by landreev** [comment]
OK, I reorganized some old code on the inside. 
Tested like this: added a file to a draft version; removed the write permission on the dataset directory;  tried to delete the file on the dataset page. (it's important that the file is unpublished - otherwise we never try to remove the physical file - we'll be only removing it from the new draft...)

Now I'm getting a proper error message: 

![screen shot 2017-08-24 at 7 22 22 pm](https://user-images.githubusercontent.com/737558/29693320-ea9e91e8-8902-11e7-96a2-1e1e83dee0da.png)

**Comment by landreev** [comment]
Back into code review it goes...
