### ISSUE TITLE
invalid xml from add dataset page

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4047]
nbsp from metadataFragment.xhtm ; unescaped ampersand from javascript in dataset.xhtml.

To reproduce:
- login, click add dataset
- save page (xhtml only)
- `xmllint --noout $add_dataset_page.xhtml`

`Entity 'nbsp' not defined` ; `parser error : xmlParseEntityRef: no name                               │                            } else {
ar urlregex = new RegExp("^(http|https|ftp)\://([a-zA-Z0-9\.\-]+(\:[a-zA-Z0-9\.&`

---
CDATA should handle the javascript regex; not sure where the nbsp's coming from yet.

**Comment by mheppler** [comment]
Looking at demo (v. 4.14 build 1326-57a392d), I found three examples of the `nbsp` character entity in the source code for the Add New Dataset pg. They all are a result of the PrimeFaces `p:selectOneMenu` component.

```
<label id="..." class="ui-selectonemenu-label ui-inputfield ui-corner-all">&nbsp;</label>
```

This component is used to select a dataset template at the top of the form, or by any dynamic metadata field that uses a controlled vocabulary. We do not have control of this element which is generated by the PrimeFaces framework to produce the UI component.

There are no examples of the `&nbsp;` entity name anywhere in code currently. Instead you will find we use the XML properly parsing entity number examples `&#160;`.

All that said. I wonder if saving the source code as `.xhtml` was the root cause of the problem here. I believe that our JSF-based PrimeFaces framework uses XHTML files to ultimately produce HTML for our browsers. So the source code should be saved and validated as `.html`.

Maybe @scolapasta can chime in here with some further clarification on what's going on here from the JSF side.
