### ISSUE TITLE
Encrypt Storage on AWS

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#4113]
Make sure we handle storage in an encrypted fashion for support of Orange DataTags.

**Comment by djbrooke** [comment]
We tried to estimate this on the 8/30 sprint planning meeting. We didn't get firm numbers, but it was determined that encrypting everything would be easier than encrypting only some items (such as only orange data). Will revisit in a later backlog grooming.

**Comment by matthew-a-dunlap** [comment]
Have we decided how we are going to go about this encryption? Are we just going to do the encryption ourselves or use something built into the AWS? If we go with something built into AWS, are we looking to do the encryption on the client side or the server side?

http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingEncryption.html

FWIW, the AWS SDK 2.0 supposedly has support for easy client-side encryption. But it is still not released and there is no defined time window.

**Comment by pdurbin** [comment]
We talked about this yesterday in sprint planning and learned from @djbrooke that there is no extra change from AWS for encryption. So we plan to use that for Harvard Dataverse as we move to AWS. I hope this helps.

**Comment by matthew-a-dunlap** [comment]
Started work on this today, specifically setting up server-side encryption on an S3 bucket and trying to upload following these docs http://docs.aws.amazon.com/AmazonS3/latest/dev/SSEUsingJavaSDK.html . I'm getting back an access error, guessing my account needs special permissions to upload to the encrypted bucket. Will continue on Monday.

**Comment by matthew-a-dunlap** [comment]
Turns out encryption is very easy, my issues were due to missing a needed code change and documentation confusion.

The minimum bar would be to just turn on Server-Side encryption for all S3 installations as the code is now. This may not be wanted tho if there is added cost I am not aware of or the extra access time is too much. The current code encrypts our metadata as well, which may be even slower and could be undone.

Tomorrow I plan to at write documentation around S3 encryption.

**Comment by matthew-a-dunlap** [comment]
Lastly, an important line from the S3 Server-Side Encryption documentation:

"Server-side encryption encrypts only the object data. Any object metadata is not encrypted."

While this likely does not matter for the main goal of going to the cloud, it may matter down the road for relying on this encryption for securing data at different levels (https://policy.security.harvard.edu/view-data-security-level)

**Comment by pdurbin** [comment]
@matthew-a-dunlap and I just discussed this issue and we agreed that there should be a setting to opt out of encryption if you want. @rsteans do you know if you want encrypted AWS or not?

**Comment by rsteans** [comment]
I think we do not.  At least right now.  But, man, that sounds appealing as we consider working with medical  and other privacy-related areas.

**Comment by pdurbin** [comment]
> we agreed that there should be a setting to opt out of encryption

Implemented in a13ada7 so I'm moving this issue to Code Review at https://waffle.io/IQSS/dataverse

Thanks for your input, @rsteans !

**Comment by djbrooke** [comment]
From our standpoint, this code is done and the code review is done. I'm working with our partners at HUIT to determine if they have feedback on this, as we are moving Harvard Dataverse to S3.

**Comment by djbrooke** [comment]
I talked with Sharon at HUIT about this. They are prioritizing the work needed for the move of dataverse.harvard to S3, and this is something that's not required for that move, but is required to support sensitive data in 5.0. If they have time, they'll check it out before the move to S3, but otherwise, we'll let this sit until later. 

Moving to the Inbox for now.

**Comment by djbrooke** [comment]
Closing this, as the current plan is to handle sensitive data storage through TRSAs.
