### ISSUE TITLE
workflow steps don't roll back cleanly

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4124]
splitting off from #3561 :

More investigation:
- create external workflow with `http/sr` stepType for pre-publish
- create dataset
- submit for review
- turn off the system listening at the `url` for the `http/sr` step.
- admin user published dataset (through UI)
- server log shows workflow engine rolling back workflow; dataset page shows (new) message about publication workflow in progress, de-activated publish button, no return to author button.

Same behavior seen for publishing without a submit for review step; also seen with publishing through API.

**Comment by pdurbin** [comment]
As discussed in standup, there are merged conflicts between branch `4124-workflow-clean-rollback` (pull request #4165) and branch `4139-curator-edits-in-review` (pull request #4208) and I have just resolved conflicts between the two branches and created a new branch called `4124-4139-locks` that is now pull request #4216. Both #4124 and #4139 will be tested against this new pull request. I'll close the old pull requests. There was a bug in pull request #4165 where the lock was not being removed when a dataset was returned to the author but this is fixed in the new pull request.

@sekmiller and I plan to poke around at the new branch a bit and then move both issues to QA.

@kcondon mentioned that a test environment is required to test this issue. I'm unclear how to test this issue myself so if anyone knows, please leave a comment. I'm not sure if the first comment/description of this issue lays out the steps or not. It says "more investigation".

**Comment by pdurbin** [comment]
@sekmiller and I believe we're done messing with the code in pull request #4216 so I'm moving this to Code Review at https://waffle.io/IQSS/dataverse

**Comment by kcondon** [comment]
This works, tested against RSAL mock.
