### ISSUE TITLE
Remove references from NDS Labs Workbench from Dataverse guides

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#4152]
In #4040, the [NDS Workbench](http://www.nationaldataservice.org/projects/labs.html#workbench) is mentioned a few times. 

We should consider putting this into the Dataverse Guides, because it's really cool, but we should understand it a bit first.

**Comment by pdurbin** [comment]
Yes, thanks for opening this issue. I just pushed 43d3844 for #4040 to at least put NDS Labs Workbench on the radar of people who are installing Dataverse. I should follow up with @CCMumma to see if she has tried it yet. @jonc1438 talked about it at https://projects.iq.harvard.edu/dcm2016 and probably elsewhere. The commit above includes a shout out to @craig-willis for adding Dataverse to the workbench!

**Comment by pdurbin** [comment]
In sprint planning last week @pameyer mentioned that NDS Labs Workbench allows users to spin up Dataverse in the cloud, which is great to know. Also, 43d3844 is now part of pull request #4168 so assuming it get merged, we'll be able to change the title of the issue, since the workbench will already be mentioned. This issue is about revising what was stubbed out after being informed by experience with the workbench.

**Comment by pdurbin** [comment]
For anyone wanting to pick this up, here's what's written as of 4.8.6: https://github.com/IQSS/dataverse/blob/v4.8.6/doc/sphinx-guides/source/installation/prep.rst#nds-labs-workbench-for-testing-only

**Comment by pdurbin** [comment]
@craig-willis you comment at https://github.com/whole-tale/whole-tale/issues/49#issuecomment-439451644 about giving this issue some attention is enough for me to assign it to you and drag it to "Community Dev" at https://waffle.io/IQSS/dataverse 😄

**Comment by pdurbin** [comment]
@craig-willis that makes total sense. If you need any help getting the other issues unblocked please let us know.

**Comment by pdurbin** [comment]
@craig-willis hi! I'm just checking to see if you know about https://github.com/IQSS/dataverse-kubernetes

It's new, created by @poikilotherm 

Also, I'd like to pick your brain about if the "create" SQL scripts we started creating are useful to you or not. For example, you can look at https://github.com/IQSS/dataverse/blob/v4.11/scripts/database/create/create_v4.11.sql

The reason I ask is that because we recently started using Flyway to execute database migrations, we are thinking of no longer making those "create" scripts.

**Comment by craig-willis** [comment]
Thanks for the nudge @pdurbin.  As discussed on Slack, due to resourcing constraints it looks like we will no longer be able to support the running Workbench instance.  So, it will make sense to remove references from your documentation going forward.  

Also, this means that we will no longer be making use of the DDL scripts, which were certainly useful.

**Comment by pdurbin** [comment]
@craig-willis thanks for the update! I'm sorry to hear that the instance won't be available in the future but it sounds like we shouldn't be guiding future sysadmins to it so I just opened pull request #5711 to remove references from out guides.

Please ping us if workbench or something like it comes back! 😄
