### ISSUE TITLE
Regular Download to Storage for Backup (or other?) Purposes

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#4157]
When Harvard Dataverse moves to S3 this fall, we'll need to set up a way to keep a copy of the files at [FAS Research Computing](https://www.rc.fas.harvard.edu/) for backup purposes. We don't want to just have files on AWS. :)

For Harvard Dataverse, it could be as simple as a script that runs regularly and downloads/exports data/metadata, but if there's some other way to set it up that would have use more broadly in the community (thinking for those folks who want to integrate with archival systems), we should consider.

**Comment by djbrooke** [comment]
Some useful information may be here:

https://wiki.archivematica.org/Dataverse

**Comment by landreev** [comment]
We discussed this yesterday briefly; there are some questions: 

1. Most important - decide if we want to integrate this into the Dataverse application; or if it should be done outside the app. Personally, I'm feeling increasingly strongly that it should be done externally. Some cronjob/similar timer-run job that monitors all the files in the database, and makes sure all have been copied to the secondary storage (in our case, RCE). Once the file is copied, it verifies the checksum and makes a record of it; so that during the next run we only copy the files that haven't been backed up yet. I feel we can think of integrating the functionality in the Dataverse once we have an actual use case, for the Dataverse to do something with these secondary copies. 

2) Whether we implement it internally or externally, we need to know how to write onto this RCE storage. I believe it was supposed to be a swift node (?). So we need the location/credentials. Unix-hackers may be the right place to ask the question. Any volunteers to be responsible for this part? 

3) The issue Matthew brought up - encryption? The current plan is to use the internal S3 encryption; this means Dataverse only sees the files in plain, unencrypted form. Do we re-encrypt the files before putting them on RCE? Or should we just not bother for now, and revisit the issue when we have to deal with sensitive data? Alternatively, this discussion can happen in the issue dedicated to the encryption requirement, or the new iteration of that issue. 


(Maybe, as one extra question - why are we doing this again? Is it just because we don't fully trust Amazon and their backup system (Glacier?); specifically, how did it become a requirement for moving to AWS/S3? - after all, as of now we appear to be happy with having all the files on just one storage subsystem. And it's unlikely that the LCS storage is more reliable overall than Amazon - ?)

**Comment by pdurbin** [comment]
> why are we doing this again?

One thing to keep in mind is the following text at https://dataverse.org/best-practices/harvard-dataverse-preservation-policy

> ### Data Backup & Preservation Terms
> 
> Harvard University Information Technology (HUIT) in collaboration with Harvard Library, and the Institute for Quantitative Social Science (IQSS) hosts Harvard’s Dataverse repository and maintains a full backup of all data and directories. This means that there is always a full, recent off-site copy of the Harvard Dataverse repository.
> 
> ### Backup Schedule
> 
> HUIT backs up all of the application/system files and databases nightly. It is stored off-site in Carlstadt, New Jersey for 45 days.
> 
> All research data files in the repository are replicated every 4 hours to a second off-site storage array at 1 Summer St, Boston, MA. Since March 2013, HUIT incorporated the data content of the Harvard Dataverse repository into the DRS Storage Infrastructure. This makes use of the storage management software to create a tape copy of the data to be stored for the long-term at the Harvard Depository.

If we aren't doing these things anymore with the move to S3 we should update that site.

**Comment by landreev** [comment]
OK, I'm not sure if the unix-hackers list is necessarily the best place to ask about the specifics of accessing the storage facility at FAS RC. 
Maybe contacting Sharon's small group directly is a better way - ?

**Comment by djbrooke** [comment]
@pdurbin - good catch - that text is currently the truth, but once we move to S3 it will need to be updated.

**Comment by landreev** [comment]
My understanding is that once we move to AWS, the longer-term backup/preservation process described in that text will be replaced by backing it all up on Amazon's Glacier. So I'm not sure it answers the "why are we doing this" question... Generally, yes, more backups is better than fewer backups. I just wasn't sure why we were assuming that this issue was a hard requirement, something that needed to be addressed before we can move to AWS. Because to me it feels like the combination of S3 + Glacier offers the level of reliability and preservation that's equal to or greater than what we are getting now.

**Comment by djbrooke** [comment]
@landreev 

Sorry, I meant to respond earlier - backing up the data on Glacier (which we will do as well) is still on AWS, and we need a copy outside of the AWS infrastructure in order to meet our preservation policy. There may be some interpretation of that policy in which having the data across multiple AWS regions or different types of AWS infrastructure would satisfy the "multiple locations" piece, but we don't want to be solely dependent on AWS. I had some of these same questions about what was driving this, so I re-confirmed with @mercecrosas.

**Comment by pdurbin** [comment]
As I mentioned at standup this morning, the bare minimum to move forward is getting credentials to write to the backup storage server:

- username
- password
- hostname

@landreev mentioned there has been some internal chatter.

**Comment by landreev** [comment]
status update:

The solution I'm putting together is a fairly simple python program, that runs on schedule on the Dataverse side. Meaning, somewhere with access to the Dataverse database - I'm using Psycopg2 to talk to Postgres from Python - and the files. In our production case the files will
be living on S3, so I'll be using the AWS SDK for Python for read access. But I'm going to make the code generic enough so that another Dataverse should be able to use it to backup their filesystem storage onto the secondary volumes of their choice as well. At the moment I'm focusing on this "Dataverse side" of things. 

It appears that there are still issues of policy regarding getting that storage volume on RC that are being discussed. (whether it's ok to eventually store confidential data there, etc.) I trust this will all be resolved and we'll be given write access to the volume eventually. I'm assuming it's going to be Swift auth credentials (I asked Brian White directly; will add more info as it becomes available). Will use python-swiftclient to write. But, again, I'll try to keep it somewhat generic, and make it easy/possible to use other types of storage for this "secondary volume". (that is, other than Swift  - a filesystem volume; scp? rsync maybe?  and S3 as well - for another Dataverse to be able to back up their filesystem-stored data on AWS?)

I'll push in my branch shortly, once I have it somewhat working. If anyone has any issues with this approach/any other feedback, please speak up.

**Comment by pdurbin** [comment]
@landreev sounds like a nice, generic re-usable solution.

**Comment by landreev** [comment]
This is going to code review. 
As for QA, we'll probably have to wait until we get a VM on RC (this host will have direct access to the backup file system; and this backup module will be copying files there via ssh/sftp). Or we can test it with one of our dev. boxes. 
The files README_HOWTO.txt and README_IMPLEMENTATION.txt contain some info on how the module is implemented and how to configure and run it.

**Comment by pdurbin** [comment]
I assigned this to myself to at least review the documentation in pull request #4271.

**Comment by djbrooke** [comment]
assigning @pameyer as an additional reviewer since he was tagged as the local python guru in standup this morning. :)

**Comment by pdurbin** [comment]
I just left a review in pull request #4271 and am going to put this back in development since I requested changes.

I'm glad @pameyer is looking at the Python code itself. I focused on the docs.

**Comment by pameyer** [comment]
General suggestions / changes:

 - `requirements.txt` is the usual place for listing dependencies; added one (without `swiftclient`, since I don't know where it's coming from)
- from skimming the code, I'm assuming this is python 2 only - but it would be good to list which python version(s) this is known to work with (aka - 2.6, 2.7, etc)
- `pylint` (https://www.pylint.org/) finds a few errors (in addition to the usual warnings, mostly unused imports); minor code changes to remove the errors

Feel free to revert these changes if there's something I'm missing.

**Comment by oscardssmith** [comment]
I can't see anything that would break in python 3. if there is, though, there shouldn't be. No reason not to have compatibility since it would be easy.

**Comment by pameyer** [comment]
@oscardssmith there were a few `print foo` instead of `print(foo)` that made me think python3 would be unhappy there.

**Comment by landreev** [comment]
Some relevant status info: 
The RC VM has been created (I have the IP address). 
For now it will be allowing ssh connections from our test server range; it sounds like we'll be using dataverse-internal.iq (aka dvn-vm4.hmdc) as the test system. 
Ssh key auth will be supported (I have the private key; the public key has been passed to RC). The username on RC system is "dataverse"; it will have full write access to the storage volume, mounted as "/dataverse_backup" locally on the VM.

**Comment by landreev** [comment]
Also of interest - Wes Dillingham at RC who's working on setting up the VM mentioned this: 

As a note we are 
building an S3 compatible endpoint here at RC so that you will be able
to interact with your data as objects using S3 client tools. This may 
change your backup ideas going forward, but until that is built, lets 
get a filesystem setup.

**Comment by kcondon** [comment]
Issues found:
-remove S3bucketName from how to file.

**Comment by landreev** [comment]
@kcondon 
A couple of extra things to clean up, as identified today: 
- we identified the external reasons it failed initially (no destination directory; wrong permissions in the destination directory;). But the behavior of the script was still unsatisfactory - the failure should be reported in a more graceful way (and not a hard exit with a stack trace). 
- need to document the destination directory setting.

**Comment by landreev** [comment]
Please get the latest of backup_ssh.py and retest on dvn-vm4.

(if you update the entire directory - make sure you don't overwrite your config file...)

**Comment by kcondon** [comment]
not sure why but when I run this on a clean, new db with 4 datasets of 3 files each, I get 4 failed to backup. I do have a mix of published, unpublished and one restricted file but some unpublished files were backed up and some published ones were not:

./run_backup.py 
No time stamp! first run (or a full re-run).
10.5072/FK2/PBNDCW/1605c44be84-883ea8eb4969, MD5: 539aed1a281c58fa736e21b9d77fda70
SSH Host: dvn-build
SSH Port: 22
SSH Username: kcondon
Connected!
ssh client is not defined
File transfered.
backed up file 1605c44be84-883ea8eb4969
10.5072/FK2/PBNDCW/1605c44c062-f22e67b70836, MD5: 1007330fd9c833d2aac518bbbb5354d9
reusing the existing ssh client
File transfered.
backed up file 1605c44c062-f22e67b70836
10.5072/FK2/PBNDCW/1605c44bb2b-4b1a899187ce, MD5: 003b8c67fbdfa6df31c0e43e65b93f0e
reusing the existing ssh client
File transfered.
failed to back up file 1605c44bb2b-4b1a899187ce
10.5072/FK2/JOIIVD/1605c455a6b-c3f1121cef67, MD5: 1007330fd9c833d2aac518bbbb5354d9
reusing the existing ssh client
File transfered.
backed up file 1605c455a6b-c3f1121cef67
10.5072/FK2/JOIIVD/1605c455916-d02917d88a4a, MD5: 539aed1a281c58fa736e21b9d77fda70
reusing the existing ssh client
File transfered.
backed up file 1605c455916-d02917d88a4a
10.5072/FK2/JOIIVD/1605c4557bb-05364437a9a6, MD5: 003b8c67fbdfa6df31c0e43e65b93f0e
reusing the existing ssh client
File transfered.
failed to back up file 1605c4557bb-05364437a9a6
10.5072/FK2/OKASGW/1605c462a1b-ed75a483b02d, MD5: 1007330fd9c833d2aac518bbbb5354d9
reusing the existing ssh client
File transfered.
backed up file 1605c462a1b-ed75a483b02d
10.5072/FK2/OKASGW/1605c46274a-e87014ea21c2, MD5: 003b8c67fbdfa6df31c0e43e65b93f0e
reusing the existing ssh client
File transfered.
failed to back up file 1605c46274a-e87014ea21c2
10.5072/FK2/OKASGW/1605c4628a9-6de7d65ff240, MD5: 539aed1a281c58fa736e21b9d77fda70
reusing the existing ssh client
File transfered.
backed up file 1605c4628a9-6de7d65ff240
10.5072/FK2/ZKED7A/1605c46a5d5-0d6c158eed75, MD5: 1007330fd9c833d2aac518bbbb5354d9
reusing the existing ssh client
File transfered.
backed up file 1605c46a5d5-0d6c158eed75
10.5072/FK2/ZKED7A/1605c46a337-4625a558c8f2, MD5: 003b8c67fbdfa6df31c0e43e65b93f0e
reusing the existing ssh client
File transfered.
failed to back up file 1605c46a337-4625a558c8f2
10.5072/FK2/ZKED7A/1605c46a491-3d67f2038043, MD5: 539aed1a281c58fa736e21b9d77fda70
reusing the existing ssh client
File transfered.
backed up file 1605c46a491-3d67f2038043
backup script run report: 12 files processed; 8 success, 4 failed


I'll try the rerun option to see whether that backs up the ones not caught the first time around.

**Comment by kcondon** [comment]
OK, this works for both file and s3 sources.
Also check error handling and --rerun correction for bad md5 and missing physical file.
One proposed enhancement: add an extension to target backup copy of bad md5 file indicating it is bad rather than only relying on db if leaving bad copy in place at target for diagnostic purposes.
