### ISSUE TITLE
S3 Support: Missing thumbnail for map files, works for swift, local files.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4185]
For the s3 driver only, geomapped files do not have their map displaying as their thumbnail on either the file landing page or dataset page but it does appear for Swift and local files.

**Comment by matthew-a-dunlap** [comment]
Example not working dataset (s3):
https://dataverse-internal.iq.harvard.edu/dataset.xhtml?persistentId=doi:10.5072/FK2/ZPWEMC

Example working dataset (swift):
https://dataverse-internal.iq.harvard.edu/dataset.xhtml?persistentId=doi:10.5072/FK2/498H2W

Underlying error message (tho possibly not the original problem):
[2017-10-13T15:59:25.764-0400] [glassfish 4.1] [WARNING] [] [edu.harvard.iq.dataverse.dataaccess.ImageThumbConverter] [tid: _ThreadID=56 _ThreadName=jk-connector(5)] [timeMillis: 1507924765764] [levelValue: 900] [[
  caught IOException trying to open an input stream for worldmap .img file (s3://iqssqa:15f1751b834-a3caef65ea4d). Original Error: java.io.IOException: Failed to open auxilary file img for S3 file]]

**Comment by matthew-a-dunlap** [comment]
This is the real error:
`[2017-10-13T17:28:44.287-0400] [glassfish 4.1] [WARNING] [] [edu.harvard.iq.dataverse.MapLayerMetadataServiceBean] [tid: _ThreadID=54 _ThreadName=jk-connector(3)] [timeMillis: 1507930124287] [levelValue: 900] [[
  Failed to save WorldMap-generated image; Data read has a different length than the expected: dataLength=0; expectedLength=184317; includeSkipped=false; in.getClass()=class com.amazonaws.internal.ReleasableInputStream; markedSupported=false; marked=0; resetSinceLastMarked=false; markCount=0; resetCount=0]]`

The first half of this error is from dataverse, the second half is an aws error. This forum post is helpful: https://forums.aws.amazon.com/thread.jspa?threadID=181397

Leads back to saveInputStreamAsAux in S3AccessIO. I tried a few quick fixes that did not work. One was to stop specifying the size for the thumbnail input stream, which solved the above error but now it looks like an image is saved with a size of 0. Will continue on Monday.

**Comment by landreev** [comment]
It's just bombing because we are trying to save an empty InputStream. 
We've already read the entire stream when we did 
byte[] bytes = IOUtils.toByteArray(inputStream);

I never looked closely at this line that follows before: 

s3.putObject(bucketName, destinationKey, inputStream, metadata);

- but yes,  we are trying to save this same inputStream, that we've already gotten to the end of. Hence - zero bytes read. 
I was assuming we were reading the inputstream into a buffer, to determine the size (which was pretty awful as it was...), then saving the buffer. 

I'm not immediately seeing an S3 method for saving a byte[] buffer; putObject() only exists for InputStream, File and a String. I don't think we want to convert byte array to a String... 

So it really looks like the only practical way to implement SaveInputStreamAsAux for S3 is to read the InputStream into a temp file, then use putObject(File). 

It's bulky, but it would also solve the issue with the current implementation, where it needs to buffer the entire stream in memory - which will fail on large enough streams.

In practice, SaveInputStreamAsAux() is only used for saving that WorldMap-generated image. For all other types of aux files we are using savePathAsAux(), or writing into an Aux OutputStream() - when supported, meaning, only for FileAccessIO objects.

**Comment by matthew-a-dunlap** [comment]
That's the direction I was heading towards as well. I think its a reasonable solution for the reasons stated: Its only used for WorldMap so creating a temp does not seem to be a bad solution. We should leave a comment noting the weird implementation though.

**Comment by landreev** [comment]
Another way to go about it would be to NOT implement SaveInputStreamAsAux in S3, and have it throw the "not supported" exception instead. So then it would be the responsibility of the programmer to do something similar that what we are doing when saving other thumbnails, when we try to open an OutputStream, if it works - we write into it, if "not supported"- we save the output into a temp file, then run savePathAsAux on it... 

I feel that implementing it with an internal (internal to the S3 driver) temp file is an acceptable solution though.

**Comment by matthew-a-dunlap** [comment]
I have committed code for supporting S3 by saving the inputstream to a file. It is untested tho, tomorrow I will either create a testing project to do a test without worldmap, or work with @kcondon . Alternatively, a solution that stores the inputstream to memory is in 1ac9518 , but this will break if we end up using saveInputStreamAsAux for large files.

**Comment by matthew-a-dunlap** [comment]
The solution for this saves the size-unknown streams to a tempfile and then uploads that tempfile to S3. This currently only happens with worldmap, and I was not able to test the code directly as worldmap would use it (tho I did test it being called by other file uploading methods). There is potential that there may still be a bug in this until @kcondon is able to deploy it again (thanks again for all the deployments!)

**Comment by landreev** [comment]
Reviewing the PR, a couple of things:

1. I've added javadoc-style comments to StorageIO and S3AccessIO, warning the potential users of the method of the limitations of the current S3 implementaiton.

2. getTempPath() method - I don't see a problem with having the "/tmp" hard-coded (it is indeed only used if the files directory is not specified in the configuration; which should not really happen, because the installer sets the default value for it). 
But it may not be the best practice to use the "dataverse.files.directory" directory itself for the temp files. Our normal practice is to keep temp files in "dataverse.files.directory"/temp. See the static getFilesTempDirectory() method in FileUtil. I would recommend to simply call FileUtil.getFilesTempDirectory(), and then convert the resulting String into a Path. (note that the method in the utility also creates the directories in the path, if they don't yet exist). 

3.  The SaveInputStream() method - the equivalent method for the main file associated with the DataFile - still has the same issue, reads the InputStream into a buffer, then tries to save the, now empty, InputStream on S3. It's not causing problems, because the method isn't being used anywhere as of now. But I feel we should probably fix it now as well, while we're at it. 

4. Just want to state that I think it was the right choice, to implement it with the temp file, instead of a memory buffer. It's going to be a bit slower, but will work on much larger streams. Which I feel is a sensible tradeoff.

**Comment by kcondon** [comment]
Found a couple things:
-on S3 only, when a shape file is mapped and first returns to file landing page, thumbnail and icon are both present and overlapping.
-on S3 only, when a shape file mapping is deleted from WorldMap, thumbnail is not removed and so when remap not replaced.

**Comment by landreev** [comment]
@kcondon 
The 2nd issue above ("thumbnail is not removed") - that was due to a bug in the S3 driver. Should be fixed now, please retest. (great catch!)

**Comment by landreev** [comment]
OK, pushed in a fix for the 1st issue too. You should not be seeing BOTH the default icon, and the 400 pixel preview, overimposed.
