### ISSUE TITLE
File download: Data subset not working, does not list variables in popup.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4186]
When selecting data subset for a tabular file a popup appears but has only a title and does not offer the ability to choose a subset of variables to download. Note, this does not work on the files tab of the dataset page but does work on the file landing page.

**Comment by landreev** [comment]
I traced this to this line in dataset.xhtml, inside "downloadDataSubsetPopup", from a commit on Sep. 1:

```
1211   <div class="form-inline clearfix" jsf:rendered="#{!(empty DatasetPage.guestbookResponse.dataFile or !settingsWrapper.rsyncDownload) and DatasetPage.guestbookResponse.dataFile.tabularData}">
```

It appears to have an extra logical NOT in the rendered logic. (i.e. it says "show IF rsync download is configured", instead of "show IF NOT configured")

Changing it to

```
 jsf:rendered="#{!(empty DatasetPage.guestbookResponse.dataFile or settingsWrapper.rsyncDownload) and DatasetPage.guestbookResponse.dataFile.tabularData}"
```

fixes it. That said, that rsync download check appears to be unnecessary there. Since when rsync download is enabled, the user should never get to this popup in the first place. So it may be safe to just revert the Sep. 1 change and go back to 

```
#{!(empty DatasetPage.guestbookResponse.dataFile) and DatasetPage.guestbookResponse.dataFile.tabularData}"
```

**Comment by mheppler** [comment]
After looking over the most excellent comment from @landreev and the code on the dataset pg, I believe his last solution proposed of just removing the render logic is best since that button is not displayed due to render logic higher up in the tree.

Fixed render logic bug for download subset on dataset pg. Also, moved popup header text to bundle. Moving to Code Review.

**Comment by pdurbin** [comment]
> I believe his last solution proposed of just removing the render logic is best

Pull request #4194 contains this fix. Approved. Moving to QA.
