### ISSUE TITLE
Submit for Review - Provide msg to user they can't edit dataset after it's submitted

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#4188]
Users are no longer be able to edit datasets that are under review, as those datasets will be locked. 

We should provide some messaging about this. The current message is simply:

"Submit this dataset for review by the curator of this dataverse for possible publishing."

**Comment by dlmurphy** [comment]
Proposed text for this:

> Submit this dataset for review by the curator of this dataverse for possible publishing. You will not be able to make further changes to this dataset until the curator approves or rejects your submission. 

Screenshot of how the modal window would look in action:

![submit_for_review2](https://user-images.githubusercontent.com/22962740/31465955-851dc804-aea3-11e7-907f-1e6fa4aa0875.PNG)

Folks, let me know if you have any thoughts/proposed edits, otherwise I'll commit this change to the bundle tomorrow morning.

**Comment by dlmurphy** [comment]
Based on some good suggestions from @jggautier and @pameyer, I'm changing the message to:

> Submit this dataset for review by the curator of this dataverse prior to publication. You will not be able to make further changes to this dataset until the curator approves your submission, or returns it for further edits.

Also, I'm currently talking with @TaniaSchlatter about potentially changing the form of the text from the red error style to a more fitting style.

**Comment by dlmurphy** [comment]
Looks like this issue is the same as #4144

**Comment by dlmurphy** [comment]
Talked with @TaniaSchlatter and @jggautier this morning about this message and we decided to radically shorten it, including fewer specifics on the review process. There's a wide variety of ways that different curators/admins might conduct their review process, and the feature itself is still in flux (as seen in #4139 and #4143), so it makes sense for our message to be more general to encompass all use cases. Plus it's nice to be concise.

Here's the new message we're planning on going with:
> You will not be able to make changes to this dataset while it is in review.
<img width="628" alt="screen shot 2017-10-12 at 11 55 06 am" src="https://user-images.githubusercontent.com/22962740/31507244-f789072e-af47-11e7-8a48-8fd86aef7899.png">

Paging @pameyer and @sbarbosadataverse, would love to get your thoughts on this message.

**Comment by mheppler** [comment]
Since we're changing the color style of the message on this confirmation popup (see screenshot above), I have searched through the app and found a few other instances that also needed to be changed from red to yellow. I have index them here by the page they're found on, as well as the popup's header text.

**dashboard-users**
- Edit Superuser Status
- Remove All Roles

**dataset**
- Submit for Review
- to be continued...

**dataverse**
- Publish Dataverse
- Delete Dataverse
- Reset Modifications

**editFilesFragment**
- Delete Files

**file**
- Delete Files

In addition to correcting these style inconsistencies, I have found a few instances of msg's that were  were not warnings, but notifications you could NOT do an action, and were styled with the red "danger" text color, but had the "warning-sign" icon. To differentiate these, I kept the red text color, and changed the icon to the "exclamation-sign" icon.

![screen shot 2017-10-12 at 4 53 32 pm](https://user-images.githubusercontent.com/687227/31518638-ef1701ba-af6d-11e7-95ec-fe6f0f8fac9e.png)

**dataverse**
- Featured Dataverses
- Publish Dataverse (cannot publish because parent is not published)
- Link Search/Link Dataverse (cannot link without owning a dataverse)

**file**
- Edit File (Replace)
- File Restricted

**Comment by pdurbin** [comment]
I just left a review on pull request #4195 and it looks good so I moved it to QA. Please not the extensive comment @mheppler left on what to test above.
