### ISSUE TITLE
In OAI exported xml https is hard-coded 

### ISSUE THREAD

**Issue by solhm** [IQSS/dataverse#4191]
We tried to export ddi via oai with
 `http://dvServer/oai?verb=GetRecord&identifier=hdl:xxxxx/xxxxx&metadataPrefix=oai_ddi` all `otherMat` URIs came with https like `<otherMat ID="f4256" URI="https:` 
But if we use the api 
`http://dvServer/api/datasets/export?exporter=ddi&persistentId=hdl%3Axxxxx/xxxxx` it uses the correct value from jvm-options siteUrl

**Comment by pdurbin** [comment]
@solhm as I've been saying at http://irclog.iq.harvard.edu/dataverse/2017-10-12 I'm grasping at straws because I didn't write this but I would suggest doing a "find usages" of `getDataverseSiteUrl` in `DdiExportUtil.java`.

I'm seeing three usages in the java file that do something like this:

    writeAttribute(xmlw, "URI", dataverseUrl + "/api/access/datafile/" + fileDTo.getDataFile().getId());

Maybe you could start by printing out `dataverseUrl` to see if it's http or https. Here's the file:

https://github.com/IQSS/dataverse/blob/v4.8.1/src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java#L1192

I asked @sekmiller about this but he's not sure. Pleas remind me to ask @landreev when he's back.

**Comment by pdurbin** [comment]
@solhm and I talked this out at http://irclog.iq.harvard.edu/dataverse/2017-10-13 and the reason why changes to the `dataverse.siteUrl` JVM option were not being reflected on exports of older datasets is that the XML is cached on disk in files like this for example: `/usr/local/glassfish4/glassfish/domains/domai​n1/files/10.5072/FK2/PTXXFK/export_ddi.cached`. Deleting the files allows the changes to `dataverse.siteUrl` to be changed. I'm going to go ahead and close this issue but if @solhm or others can suggest where in a guide this information could be effectively communicated, I'm happy to re-open it so a pull request can be made to improve the guides.
