### ISSUE TITLE
ORCID API upgrade

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4218]
The existing OAuth2 code for the ORCID authenticate provider needs to be upgraded from 1.2 to 2.0 (https://members.orcid.org/api/news/xsd-20-update; https://github.com/ORCID/ORCID-Source/tree/master/orcid-model/src/main/resources/record_2.0#calls).

Biggest complexity change (currently) appears to be change in message format from the API endpoints, potentially also storing full response from token exchange; there are also changes to the scopes.  HTTPs requirements (endpoints, redirect URIs, etc) appears to be already met by existing code.

**Comment by pdurbin** [comment]
@pameyer thanks for the heads up. The timing is unfortunate because pull request #3539 was merged on 2017-01-20 and according to https://members.orcid.org/api/news/xsd-20-update 2017-02-14 was the day the default switched from 1.2 to 2.0. I can't tell when 2.0 was available for testing, but I guess it doesn't matter.

That page goes on to say that "v1.2 is expected to be sunset in the fourth quarter of 2017." That's pretty soon. I'm not sure how many installations of Dataverse are using the ORCID login feature but as of this writing there are 66 users of https://dataverse.harvard.edu that use ORCID for login (`select count(id) from authenticateduserlookup where authenticationproviderid = 'orcid';`). If we don't address this issue by then, they will need to be converted to a non-ORCID login: http://guides.dataverse.org/en/4.8/installation/oauth2.html#converting-oauth-users-to-local

http://guides.dataverse.org/en/4.8/_downloads/orcid.json via http://guides.dataverse.org/en/4.8/installation/oauth2.html#dataverse-side is where the version is stored (`userEndpoint: https://api.orcid.org/v1.2/{ORCID}/orcid-profile`). We'll also need to change code in `OrcidApi.java` ,`OrcidOAuth2AP.java` and `OrcidOAuth2APTest.java` and perhaps elsewhere.

**Comment by pameyer** [comment]
@pdurbin we're planning to fix it before v1.2 is sunset (I'm looking into the details now), so it hopefully won't be necessary to convert existing users.

**Comment by pameyer** [comment]
- [ ] check that API calls are using https
- [ ] switch to v2.0 API endpoints
- [ ] update code handling values from API endpoints to use v2.0 message schema 
- [ ] check that `/read-limited` is the only scope being used
- [ ] store full response from token exchange (access and refresh tokens, scope, scope expiry)
- [ ] (recommendation) use `/authenticate` token instead of `/read-public` (or `/read-limited`)
- [ ] update ORCID related messaging to meet current recommendations

**Comment by djbrooke** [comment]
@michbarsinai may pick this up. Please check in with @pameyer or @djbrooke before starting on this.

**Comment by pameyer** [comment]
Screenshots for two (of the three) messaging changes, for a starting point
Login page (button text change; 2nd paragraph about why the repository is using ORCID):

![screen shot 2017-11-01 at 1 41 48 pm](https://user-images.githubusercontent.com/10261853/32296310-4625d148-bf22-11e7-8bfc-097f83fa8f72.png)

Workflow for user denying authorization in ORCID (add link to user guide for more information about what the information the repository is requesting from ORCID)
![screen shot 2017-11-01 at 4 31 58 pm](https://user-images.githubusercontent.com/10261853/32296322-4bd4a772-bf22-11e7-8a0d-b4c4fb9c917e.png)

Third change was adding ORCID logo to page footer (in custom block).  Not sure of the best way to generalize (an installation isn't required to enable ORCID, etc).

**Comment by dlmurphy** [comment]
The first of those two messages looks good to me!

The second one needs some help: 

-It refers to itself as an error message twice, and then says "If you believe this to be an error, please contact..." The user's going to be like, "I thought you just told me this was an error!"
-"OAuth2 Error" is a bit jargony, I'd like to make this more clear
-This message appears to contain two different ways of explaining the same error - the layman's way and the technical way. I'd like to try and bring these together into one  explanation.

So, with those thoughts in mind, here's a rewrite of the message. Please make sure it's still accurate, because I'm coming at this without a ton of background knowledge.

> **Authentication Error** - Dataverse could not authenticate your ORCID login. Please make sure you authorize your ORCID account to connect with Dataverse. For more details, please see the User Guide.
> For further assistance, please contact SBGrid Data Bank Support.

**Comment by dlmurphy** [comment]
Per discussion with @pameyer, I've implemented _most_ of my suggested messaging. Right now it should look like:

> Authentication Error - Dataverse could not authenticate your ORCID login. Please make sure you authorize your ORCID account to connect with Dataverse. For more details, see the User Guide.
> 
> error message: Remote system did not return an authorization code.
> 
> If you believe this is an error, please contact SBGrid Data Bank Support for assistance.

We discussed changing the last line of that message to what I'd suggested before ("For further assistance, contact SBGrid Data Bank Support."), but that'd involve creating a new entry in the bundle and we've decided to save that for later.

**Comment by djbrooke** [comment]
Thanks @dlmurphy! 

@dlmurphy and/or @pameyer - is this ready for code review?

**Comment by pameyer** [comment]
@djbrooke looks that way to me

**Comment by dlmurphy** [comment]
Agreed. I'll move it into code review.

**Comment by pdurbin** [comment]
I'm doing some code review of pull request #4280.

**Comment by pdurbin** [comment]
The pull request looks good. I'm glad to see that the unit tests are still in place and updated. I left some developer-oriented feedback for @michbarsinai in the pull request (basically, that we now have a Style Guide and that we should amend it, if necessary). He did some nice cleanup of the code. Moving to QA at https://waffle.io/IQSS/dataverse
