### ISSUE TITLE
APIs for external PSI (Privacy Preserving Metadata tools) to call

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#4232]
Once a user completes their work in PSI, the PSI application will send back the "fuzzy" summary statistics to Dataverse. Dataverse needs (at least) one new API endpoint in order to accept these.

**Comment by djbrooke** [comment]
Candidates for API endpoints:

- Summary Stats API (or a change to a current endpoint)
- List of Summary Stats available (or a change to a current endpoint or just use the API above to determine this)

**Comment by pdurbin** [comment]
Anyone working on this issue will want to read the "PSI Integration Tech Design" doc at https://docs.google.com/document/d/1XoS7kMwvZ-Ml1uIoWDClB3nj4lg06dMz9Ou6X9krVHo/edit?usp=sharing

Please note that #4231 is highly related.

**Comment by pdurbin** [comment]
I just made pull request #4300 after some consultation with @landreev and would like some feedback on the direction I'm going, some code review.

**Comment by landreev** [comment]
btw,
@pdurbin kudos for bringing up the question of terminology during the planning meeting. "SummaryStats" may not be the best way to describe these metadata fragments; because a) strictly speaking, that json contains other things - some descriptive metadata plus plot values - in addition to the summary statistics... and b) we are already using "summary statistics" in the code, to refer to the database entities that store the mean, median, standard deviation etc. values that we generate ourselves...
So anyway, I'm going to talk to James some more about this tomorrow. Ideally, I would like to come up with something better than "preprocessed metadata". "descriptive summary"? "tabular data summary"? hmm. 
(that said, we are already using "preprocessed" to refer to this format elsewhere in the API; and coming up with a better name should definitely not be the priority before the PSI demo). 

So please don't change/rename anything. But as I'm merging your branch with mine, I may rename the API there. I'll try to finalize it tomorrow.

**Comment by pdurbin** [comment]
@landreev that's fine. I certainly don't mind if you change what I called "SummaryStats" to something else. There's already a lot of confusing terminology in Dataverse, which is why @dlmurphy and I are (off and on) coming up with a glossary in #4274.

**Comment by landreev** [comment]
The glossary is a great idea, yes. 
I'm pulling this issue back into dev for a quick switcheroo - to merge your branch into mine, and then link both issues to the same combined branch. 
So yes, I may rename something in the process. And/or move some code around. One thing I just realized yesterday, instead of maintaining its own, dedicated API for processing this sumstat/preprocessed fragments, it would probably be cleaner to utilize the same Access API that is currently serving them. I.e., use the same REST node for both read and write. As in, by a POST on "access/datafile/{fileId}/metadata/preprocessed"
Again, I'll finalize this today.

**Comment by landreev** [comment]
Please note that the PR referenced above is a combined branch with the code for this and also #4231 and #4307 issues. The branch previously associated with this issue (4232-psi-api) and the corresponding pull request (4300) should be discarded.

**Comment by landreev** [comment]
All the code created as part of the original branch (4232-psi-api) should now be included in this PR, as part of the 4231-psi-metadata-infrastracture branch (very heavily  refactored for the most part). 
Functionality-wise everything should be working now. 
Except this:
@pdurbin you provided a skeleton for a RestAssuered test of a data summary fragment upload. It now resides in .../dataverse/api/WriteAccessIT.java. I've updated the corresponding method in  UtilIT.java (to properly use multipart Post parameters of the API, as currently implemented). However, the RestAssured test is still not going to work as written. As your comment there says, you need to create/upload a file, before you can test uploading the extra metadata.
Not just that, it must be a tabular file, for the API to work. So I'm not sure this functionality can be tested via RestAssured easily.

**Comment by landreev** [comment]
This is how the API currently implemented: 

To store the externally generated data summary fragment, we use a POST on the same REST node used to download it: 

/api/access/datafile/{file id}/metadata/preprocessed
the API key of the admin user must be supplied (per implementation by @pdurbin in 4232-psi-api. review?)

PSI will need to supply the following, as POST multipart parameters:

metadata: {JSON of the "preprocessed" fragment};
diffPrivate: true (optional, as it currently defaults to "true")

For example: 

curl -X POST -F metadata=@example.prep -F diffPrivate=true http://localhost:8080/api/access/datafile/12345/metadata/preprocessed?key=...

Since this API is still very experimental and is likely to change after the PSI demo, I don't think we should be documenting it in the guides just yet.

**Comment by landreev** [comment]
Made a change in the branch changing the authorization as discussed; edited the API specification, above, to reflect the change.

**Comment by pdurbin** [comment]
At standup I said I'd try to get some REST Assured tests working in `WriteAccessIT.java` so I assigned myself to this issue. Swarm! 🐝 🐝 🐝

**Comment by pdurbin** [comment]
Ok, I fixed up the tests in 16bc624. @landreev my only feedback is that when you pass an invalid file id to the GET and POST methods, one returns 404 and the other returns 400. Also, because these tests are in a new "IT" file, they won't automatically be run on the phoenix server unless we add them to comma separated list. The list is maintained at https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/configure and as of this writing the list is this:

`test -Dtest=DataversesIT,DatasetsIT,SwordIT,AdminIT,BuiltinUsersIT,UsersIT,UtilIT,ConfirmEmailIT,FileMetadataIT,FilesIT,SearchIT,InReviewWorkflowIT -Ddataverse.test.baseurl='http://phoenix.dataverse.org'`

Here's how it looks in the Jenkins UI:

![screen shot 2017-12-04 at 3 32 32 pm](https://user-images.githubusercontent.com/21006/33574802-6b29a73a-d908-11e7-9cbb-b543f0775094.png)

**Comment by kcondon** [comment]
Issues found:
-Need to document api endpoint

**Comment by landreev** [comment]
And the API for download the prep/summary metadata:

GET /api/access/datafile/{file id}/metadata/preprocessed
(raw version)

GET /api/access/datafile/{file id}/metadata/preprocessed?diffPrivate=true

("noisy")

**Comment by djbrooke** [comment]
Closing this issue for now. We'll pick this back up when we have DataTags support. 

The branch and issues will remain:

https://github.com/IQSS/dataverse/tree/4231-psi-metadata-infrastracture
https://github.com/IQSS/dataverse/issues/4231
https://github.com/IQSS/dataverse/issues/4232
https://github.com/IQSS/dataverse/issues/4307
