### ISSUE TITLE
Trailing spaces creating extra entries in facets

### ISSUE THREAD

**Issue by jonathanbohan** [IQSS/dataverse#4235]
When cutting and pasting information from our current database into Dataverse, I noticed that occasionally I would pick up a stray space at the end of the cut, and I noticed that this was creating new entries in the facets on the left of the main Dataverse page, can this be fixed? Thanks!
![trailingspaces](https://user-images.githubusercontent.com/33063235/31998142-b6f08d4e-b95c-11e7-8d68-e343518cf039.jpg)

**Comment by pdurbin** [comment]
@jonathanbohan thanks for the bug report. I was just checking out https://dataverse.cornell.edu since it's in your screenshot and I don't see your installation listed at on the map of https://dataverse.org . Would you like it to be? 😄  If so, please get in touch! Instructions can be found at http://guides.dataverse.org/en/4.8/installation/config.html#putting-your-dataverse-installation-on-the-map-at-dataverse-org

That said, let's move on to your actual problem. 😄 

You could use the facets to find the datasets with a trailing space and fix the data (remove the trailing space) and republish a new minor version. Is this an acceptable solution?

Are you look for the application to automatically trim whitespace before it goes into the Dataverse database? Do you have a solution in mind? Thanks.

**Comment by jonathanbohan** [comment]
Second question first - Yes, ideally it would ignore the trailing space - I
did republish the one that I've found so far, but it seems more prudent (to
me, at least), to implement it throughout Dataverse - I'm sure there will
be exceptions where someone actually wants the space, but I'd guess in most
cases it would be the other way around. It looks like this was done
previously - https://github.com/IQSS/dataverse/issues/242 - but it mus have
been reintroduced somehow. I should mention that I've been working on an
installation that was several versions out of date, we just updated it but
I haven't tried to recreate the issue, I'll try today.

As for the first question, I'll bring it up to our director when he gets
back from a conference in Germany, and will get back to you. Thanks!

- Jonathan

**Comment by pdurbin** [comment]
Huh, thanks for the link to #242. I had completely forgotten about that issue. It looks like @sekmiller worked on it so we'll have to ask if he know why the fix was reverted. I agree that in most cases, leading or trailing whitespace is unintentional. We could even write a utility to check the database for cases where this whitespace has slipped in while trimming hasn't been happening. I'm not sure if this is on topic for #4169 but @dlmurphy and @jggautier would know.

No rush on the map thing. We just like to highlight people who are using Dataverse. Also, Harvard Dataverse and other installations might be interested in harvesting your metadata. There's a spreadsheet linked from https://groups.google.com/d/msg/dataverse-community/dknlvOQ0oT4/A2Naqez2AQAJ with links to OAI-PMH sets. No pressure!

**Comment by jggautier** [comment]
I queried for this a few days ago on Harvard Dataverse and could add the query to that queries doc if you'd like to get a sense of how prevalent this is in your repository.

I'm curious to know why a depositor would want a leading or trailing space, and if that's the case, I think it would be safer if any solution to fix these entries in bulk involves a new dataset version being created, right?
