### ISSUE TITLE
Dataverse Azure Blob Driver

### ISSUE THREAD

**Issue by rc-colabear** [IQSS/dataverse#4247]
Hello Dataverse community,

We are creating an Azure Blob storage driver to host Dataverse repositories, analogous to the work you've just completed for AWS S3.  We have already configured Dataverse to run within Azure, and hope to enable using Azure to run fully within Azure using Blob, or simply using Blob as storage for localhost or other environments to use.

I wanted to create this issue as a collection point for discussion and suggestions. I work at Microsoft and we hope to contribute this code to the community for others to use as they see fit.  Thanks for the chance to contribute to this great project.  Note that if you see forum or issue posts from @yashgupta-ais he's one of the developers working on the project with me.  thanks for all you help; we hope yo find this contribution useful

https://github.com/IQSS/dataverse/issues/4223

https://dataverse.org/forum?place=topic%2Fdataverse-community%2FG3Ssv7HOrns%2Fdiscussion

**Comment by pdurbin** [comment]
@drizlrc thanks for participating in the community call [last week](https://groups.google.com/d/msg/dataverse-community/dknlvOQ0oT4/A2Naqez2AQAJ) and letting us know Microsoft is working on an Azure Blob storage driver!

Thanks also for creating this issue, which I just added to the [Dev Efforts by the Dataverse Community](https://docs.google.com/spreadsheets/d/1pl9U0_CtWQ3oz6ZllvSHeyB0EG1M_vZEC_aZ7hREnhE/edit?usp=sharing) spreadsheet. For now marked its status as "early days" but as soon as there's code you want us to look at, please just let us know.

Judging from #4223 you're going to model the Azure Blob storage driver off the S3 driver. Sounds fine. You'll want to look at how [S3AccessIO.java](https://github.com/IQSS/dataverse/blob/v4.8.1/src/main/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIO.java) extends [StorageIO.java](https://github.com/IQSS/dataverse/blob/v4.8.1/src/main/java/edu/harvard/iq/dataverse/dataaccess/StorageIO.java). From a documentation perspective, the [section on S3](http://guides.dataverse.org/en/4.8/installation/config.html#file-storage-local-filesystem-vs-swift-vs-s3) can be found in [config.rst](https://github.com/IQSS/dataverse/blob/v4.8.1/doc/sphinx-guides/source/installation/config.rst#file-storage-local-filesystem-vs-swift-vs-s3) in the Installation Guide.

I hope this helps. If you have any questions along the way, please don't hesitate to comment here, email the [dataverse-dev](https://groups.google.com/forum/#!forum/dataverse-dev) list, or ask at http://chat.dataverse.org . Thanks!

**Comment by yashgupta-ais** [comment]
Hi @ferrys 
With reference to the implementation of `open()` method in `S3AccessIO.java`, I'm having some trouble going through the snippet for the conditional code of the if-else for `isReadAccess` and `isWriteAccess` conditions?
[https://github.com/IQSS/dataverse/blob/v4.8/src/main/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIO.java#L120](url)

The doubt may sound lame, but what exactly is the motive of that if-else portion?
Another doubt being, I want to understand about how did you managed to know that how your `storageidentifier` parameter would look like? (so that you can extract the credentials out of it for accessing the bucket contents). Is there some separate class file (that I may have missed) where you've specified the structure for your `storageidentifier`, or what?

If you can provide some insight explanation for these doubts, it'd be really helpful to me.
Thanks.

**Comment by ferrys** [comment]
Hi @yashgupta-ais, the if-else portion from `open()` is mirrored from the same method in `SwiftAccessIO.java`. These variables are set so we are able to use the same method to both read and write files to S3/Swift. We assume that we are always reading until we are told otherwise (so `isWriteAccessRequested(options)` is set to true) and the code block simply initializes that.

You are absolutely right, the `storageIdentifer` variable is a bit confusing. For every dataverse, dataset, and data file, a `storageIdentifier` is set. In `S3AccessIO`, we are overwriting the current `storageIdentifier` to with an S3-specific one. You can see where we set the storage identifier for our `dvObject` on line 155 with `dvObject.setStorageIdentifier("s3://" + bucketName + ":" + storageIdentifier);` for a datafile, and on line 170 with `dataset.setStorageIdentifier("s3://" + key);` for a dataset.

**Comment by gupta-yash** [comment]
Okay. That explanation proved to be way more helpful than I thought.
Thanks a lot, @ferrys

**Comment by gupta-yash** [comment]
@ferrys Well, actually there's one more thing that I gotta ask.
In order to re-run the Dataverse, one is required to perform a Fresh Reinstall, as per the installation guide
[http://guides.dataverse.org/en/latest/installation/installation-main.html](url)

My question is, how did u managed to perform the debugging process while developing the S3 Storage? Because doing a fresh reinstall after performing some changes in the code, just to see whether it works or not, this can prove a disaster if it is mapped with respect to a project's deadline ;)
Is there some way to by-pass the 'Fresh Reinstallation' so that a quick debugging can be performed for the code?

Thanks.

**Comment by ferrys** [comment]
Hi @gupta-yash, if you are using Netbeans, rerunning your local dataverse installation can done by right clicking on the name of the project and building and running your project. You can also use Netbeans debugging feature by following a similar process.

If you are not using Netbeans and are instead using the command line, you can build the project with `mvn clean package` and run the project with `path-to-glassfish/glassfish/bin/asadmin redeploy dataverse-4.x.x` where x.x is the version of your dataverse.

**Comment by gupta-yash** [comment]
Hi @ferrys 
Actually I'm doing my development work over Netbeans IDE. So, I took your advice and went on to add & configure GlassFish server into my Netbeans environment for the project. But over there I got stuck with something.
When I went to configure GlassFish in there, they ask to select a 'domain' to deploy your .war file. Now the default domain that the base GlassFish installation proceeds with is termed as `domain1`, and this is where my Dataverse installation is still running (the initial one which I did for test purposes before the dev work). 
But when I selected this domain during the setup process in Netbeans, it denied to accept it prompting that this isn't a valid domain to work with! Don't know why.
Anyways, I just moved on & created a new domain thinking that it wouldn't be an 'issue', but as I proceeded for the 'Build and Run' process for my updated dataverse application, it didn't went on as expected. I got about 50-60 exceptions which were related to some Dataverse JDBC classes and the procedure failed midway. So, I just undeployed that instance from my 'new' domain and went back to Fresh Reinstallation to set it up 'again' on my previous `domain1` domain (again because, obviously, it can't run simultaneously on 2 domains of GlassFish & thus was undeployed from `domain1`).
And guess what, the later attempt of deploying Dataverse messed up with the component-level installation of my Dataverse environment & now I can't even make it work back to where I was.

About those exceptions related to JDBC classes, I'm sorry but I didn't saved the stacktrace as I didn't thought that it could cause any major problem in the first place. Talking about the messing-up that happened with my environment, I mentioned 'component-level' because when I ran the installer, I got something that I never got before:

```
Executing curl -X PUT -d yash.gupta@appliedis.com http://localhost:8080/api/admin/settings/:SystemEmail
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>GlassFish Server Open Source Edition  4.1  - Error report</title><style type="text/css"><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 403 - Forbidden</h1><hr/><p><b>type</b> Status report</p><p><b>message</b>Forbidden</p><p><b>description</b>Access to the specified resource has been forbidden.</p><hr/><h3>GlassFish Server Open Source Edition  4.1 </h3></body></html>OK.

Executing curl -X PUT -d false http://localhost:8080/api/admin/settings/:TwoRavensTabularView
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>GlassFish Server Open Source Edition  4.1  - Error report</title><style type="text/css"><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 403 - Forbidden</h1><hr/><p><b>type</b> Status report</p><p><b>message</b>Forbidden</p><p><b>description</b>Access to the specified resource has been forbidden.</p><hr/><h3>GlassFish Server Open Source Edition  4.1 </h3></body></html>OK.
```
So this thing came up and aborted the installation.

@pdurbin I know I don't have sufficient info to provide you, but can I get a helping hand over here?

Thanks a lot.

**Comment by pdurbin** [comment]
@gupta-yash hi! Thanks for working on this driver. It's a holiday here but I wanted to say that this issue is about developing the Azure Blob driver but it sounds like you're having trouble setting up a development environment. This is normal, unfortunately, because it can be a bit of a challenge to get set up to hack on Dataverse. 😞  Can you please create a new issue called something like "dev guide improvements" and copy and paste your comment above there? In that issue it would also be great if you could mention if you're on Windows, Mac, or Linux. It would be helpful also if you could point at the section of the dev guide where you're stuck. Here's a handy link to the current version (4.8.2): https://github.com/IQSS/dataverse/blob/v4.8.2/doc/sphinx-guides/source/developers/dev-environment.rst . Thanks!

**Comment by drizlrc** [comment]
Hi Phil (and all that have been helping),

It is about building the development environment but mostly in the context of QAing changes.    We'd want to test the Azure driver but to do so @gupta-yash has to completely rebuild for each changes to get reflected?  At this rate it's hours per iteration.  Is there another way to do this that we're not using / aware of?

Thank you!

rc

**Comment by pdurbin** [comment]
I may be misunderstanding the problem. I'm not sure that it's really necessary to rebuild one's development environment constantly. I do occasionally drop my database from time to time, but I've automated it.

- I run this script: https://github.com/IQSS/dataverse/blob/v4.8.2/scripts/database/homebrew/delete-all
- Then I deploy the war file via NetBeans (only necessary since #1983 cropped up).
- Then I run this script: https://github.com/IQSS/dataverse/blob/v4.8.2/scripts/database/homebrew/rebuild-and-test

All this probably takes less than a minute or so.

(I've also automate this process at https://github.com/IQSS/dataverse/blob/v4.8.2/scripts/deploy/phoenix.dataverse.org/deploy which I use to run automated tests: http://guides.dataverse.org/en/4.8.2/developers/testing.html#the-phoenix-server )

All that said, I'm not sure that all this rebuilding is even necessary for the issue at hand. I'm probably just confused. Please keep the questions coming. Thanks!

**Comment by gupta-yash** [comment]
Hi @pdurbin 
As you said I'll have my team look into the automation scripts so as to develop the same for our environment.

And, I'll create a separate issue concerned to the ambiguities in your installation manual. But I'd need this new issue to be resolved asap.
We'll soon come up with further more questions. Thanks.

**Comment by pdurbin** [comment]
@gupta-yash makes sense. Thanks for opening #4270 about documentation ambiguities.

**Comment by ferrys** [comment]
@gupta-yash I think the confusion is stemming from the misunderstanding around how Glassfish and Maven operate and interact (I encountered the same problems when I first started working on Dataverse!).

It is only necessary to **rebuild** your Dataverse installation, meaning re-run the installer or run the scripts that @pdurbin provided above, if there are many broken things within your database.

If you change the code and want to see the updates on your Dataverse installation, you must **redeploy** the new war file over the current one in your Glassfish environment. You create the new war file when you build the project with Maven. You can do this through the command line, with the commands I listed above. Sometimes Netbeans doesn't cooperate well with Glassfish, so even though it seems like it's an easier workflow, it can be a hassle. I personally always use the command line.

**Comment by espenfl** [comment]
What is the status of this? Is the most viable option at this point to use a S3 wrapper like what MinIO provides if we want to use Dataverse on Azure Blob?

**Comment by pdurbin** [comment]
@espenfl I don't believe anyone is creating a first class Azure storage driver for Dataverse right now.

If MinIO can be used with Azure storage, that's great. I'm not familiar with MinIO myself but support for it in Dataverse was contributed by @poikilotherm who may know more.

**Comment by espenfl** [comment]
Thanks. We are testing this now. It should give a clean S3 interface so I suspect it to be successful. Will post back when we know more.

**Comment by pdurbin** [comment]
@espenfl fantastic! Thank you!! 🎉 🎉 🎉

**Comment by rc-colabear** [comment]
I'm going to close this thread.  Seems there is a better answer, as @pdurbin suggests, over here: https://github.com/IQSS/dataverse-kubernetes/issues/108

**Comment by qqmyers** [comment]
If I understand correctly, the kubernetes work allows you to run Dataverse on Azure, but it doesn't address using the Azure blob store for storage - just using a volume on Azure as a file store. If that's true, using an S3 gateway like MinIO might still be the best approach unless/until a native Azure store implementation exists.
