### ISSUE TITLE
User Guide - Create a Glossary of Terms

### ISSUE THREAD

**Issue by dlmurphy** [IQSS/dataverse#4274]
It would be valuable to have a Glossary of Terms in the User Guide. The Dataverse application and documentation is full of high-level, domain-specific terminology that might be unfamiliar to some users. Furthermore, some of our terminology ("admin", for example) has a specific meaning within Dataverse, but can carry different meanings in the broader world. A Glossary page would list all potentially difficult or confusing terminology and provide brief definitions. Each term would have its own header, allowing other documentation pages to link directly to that term's Glossary entry when needed.

A key inspiration and a great model to work from is @shlake 's [Glossary of Terms](http://uvalib.github.io/dataverse-docs/en/current/user/glossary.html) for the Libra Data Dataverse.

Additionally, @pdurbin has started this [shared doc](https://docs.google.com/spreadsheets/d/1xje8FADNjCKNBNExXjKQXrmRgc-WQxEv7jKJrDOuuLA/edit?usp=sharing) to gather terminology that could be included in a glossary.

**Comment by pdurbin** [comment]
At https://aussda.at/en/news/news/dataverse-datasets-files-for-download/ I just spotted a description of Dataverse vs. dataverse (the software vs. a folder):

<img width="578" alt="screen shot 2019-02-14 at 7 16 17 am" src="https://user-images.githubusercontent.com/21006/52786313-8cc42280-3028-11e9-8fb7-f08aa0bfd53f.png">

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Comment by pdurbin** [comment]
@danielEbanks just referred to a definition at https://support.dataverse.harvard.edu/harvard-dataverse-general-terms-use

This could be a good resource for us. Here's a snapshot of what's there now:

## Definitions

Account – A User-controlled means of access to Harvard Dataverse that is protected by a User-created login username and password, with which Users can obtain access to Harvard Dataverse’s uploading and downloading functionalities.

Administrator – The User who created, controls and is the main organizer, curator, and manager of a particular dataverse.

Agreement – The General Terms of Use in its entirety.

Author – The person(s) from whom the data within the dataset originated; the person(s) who conducted the research that led to the creation of the dataset. This person can but need not be the same as the Depositor.

Content – Any information, data, text, software, scripts, graphics, and interactive features found on the Harvard Dataverse application.

Curation – The actions of any User on the Harvard Dataverse application that organize, shape, or otherwise edit the state, status, configuration, or content of any datasets or dataverses.

Data Use Agreement – This is the restricted data usage license agreement option that Harvard Dataverse offers. If applied to a User Submission, the Data Use Agreement will be a legally-binding license contract between the Depositor and any Downloader of that User Submission.

Data Usage License Agreement – The license agreement between a Depositor and a Downloader governing the limits and restrictions (or lack thereof) of how the downloaded User Submissions can be used.

Dataset – A study, experiment, set of observations, or publication that is uploaded by a User. A dataset can comprise a single file or multiple files.

Dataverse – A virtual container with which to store research data studies (including datasets and other dataverses) that can be customized and managed by its owner.

Depositor – The User who uploads a collection of data files as a dataset to a dataverse on the application.

Download Data – Information collected whenever a dataset is downloaded, including but not limited to user account name, time of download, and downloaded file name.

Harvard Dataverse – The repository application server as a whole, including all Services, Content, and related features, but not including any separate Dataverse sites created using Harvard Dataverse’s source code and managed by independent outside parties who are unaffiliated with Harvard Dataverse.

Metadata – Accompanying information, either in a separate file or otherwise included in the dataset materials, about a particular dataset or dataverse, including but not limited to Author’s name, publishing date, title of data contents, description of contents, and other such related information.

Publish – A function available for User Submissions by which Users can make their dataverse and/or their dataset containing data files publicly available and publicly searchable on the Harvard Dataverse application search engine and third-party search engines (e.g., Google Search or Bing Search).

Registration Information – Information required to register for an Account, including but not limited to name, email, institution, position, and phone number.

Restricted User Submissions – Any User Submissions that are published with either Harvard Dataverse’s Data Use Agreement or with a customized data usage license agreement that the Depositor drafts and/or designates for the Submission.

Service – the Harvard Dataverse application and all of the available services, functions, and capabilities afforded on the application.

Site – the Harvard Dataverse application and server.

Spamming – Any unauthorized or unsolicited advertising, junk or bulk e-mail, messages, comments, or other communications directly or indirectly stemming from use of the Harvard Dataverse application, including but not limited to comments posted to Author’s dataset pages and messages or other communications sent to User’s email addresses, accounts, or other means of contact.

Sufficient length of time – Any period of time as obligated by any pre-existing legal contract, such as with the subjects concerned in the research data, or with the institution that is sponsoring or that sponsored the research undertaking. If no such obligation exists, then the requisite length shall be any reasonable amount of time as designated by Harvard Dataverse’s administrators in its sole discretion.

Unpublished Dataset – An uploaded dataset that has not yet been made available to the public and is viewable only to the Depositor or other users to whom the Depositor has granted access.

Unrestricted User Submissions – Any User Submissions that are published with a default CC0 default public domain dedication waiver agreement.

Use of Service – Any access to, use of, or other action involving the Harvard Dataverse application’s functions, services, resources, and repository of datasets, including but not limited to any uploading, posting, submitting, storing, searching for, downloading, distributing, facilitating distributions, and otherwise utilizing any Content found on the Harvard Dataverse application.

User – Any individual or entity who owns and/or controls a registered account on Harvard Dataverse.

User Submissions – Uploaded dataverses and datasets.

User Uploads – Any uploaded, submitted, disclosed, distributed, or otherwise posted content by a User, including but not limited to new dataverses, new datasets, Metadata information, custom data usage license agreements, descriptive information for dataset download pages, user guides, and other contributions either originating from the User or originating from a third-party author who gave permission to the User to disseminate on the Harvard Dataverse application.
