### ISSUE TITLE
Sort and filter functionality on User Administration

### ISSUE THREAD

**Issue by solhm** [IQSS/dataverse#4285]
Manage Users table lists all user accounts in table form.
If sort functionality and filter by fields or either of them can be available, it would make the user management much easier.

**Comment by pdurbin** [comment]
@solhm thanks for opening this issue. For others, this came out of our discussion at http://irclog.iq.harvard.edu/dataverse/2017-11-15#i_60310 and holds as of Dataverse 4.8.2. Here's the feature as documented: http://guides.dataverse.org/en/4.8.2/admin/user-administration.html#manage-users

It looks list the question of sorting was raised at https://github.com/IQSS/dataverse/issues/3614#issuecomment-305276658

@solhm since you mentioned "filter by role or filter superusers" in chat I'll mention that detail here to give a little more direction of filters you're interested in.

**Comment by pdurbin** [comment]
@solhm thanks to @pkiraly's great work in the following pull request we have robust sorting of users

- #6848

Here's a screenshot:

<img width="205" alt="Screen Shot 2022-10-08 at 10 31 15 PM" src="https://user-images.githubusercontent.com/21006/194734835-134c55ae-ab56-4f26-acee-df0172939c58.png">

In addition, you can filter users:

<img width="683" alt="Screen Shot 2022-10-08 at 10 33 09 PM" src="https://user-images.githubusercontent.com/21006/194734872-b8add623-aebd-42ab-848b-d6ec289d8e45.png">

I'm going to go ahead and close this issue but if there are more features you're interested in, please feel free to open a fresh issue. Thanks!
