### ISSUE TITLE
Navigation - Harvested file landing page?

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#4288]
From a dataverse results card for [harvested files](https://dataverse.harvard.edu/dataverse/harvard?q=&fq0=metadataSource%3A%22Harvested%22&types=files&sort=dateSort&order=desc), you can navigate to a file landing page for a harvest file by clicking on the file name link. This was found on production.

Because it is harvested and not local, this link should point to the external file pg, or if that doesn't exist, the external dataset pg.

<img width="709" alt="screen shot 2017-11-17 at 11 42 22 am" src="https://user-images.githubusercontent.com/687227/32958414-68f247bc-cb8c-11e7-89b6-fea91f1456a9.png">

<img width="990" alt="screen shot 2017-11-17 at 11 39 16 am" src="https://user-images.githubusercontent.com/687227/32958288-05ef7e6e-cb8c-11e7-9c24-432393b7aea9.png">

**Comment by mheppler** [comment]
There is also a minor UI styling inconsistency between the harvested message on the file results card and the dataset results card.

<img width="714" alt="screen shot 2017-11-17 at 11 45 04 am" src="https://user-images.githubusercontent.com/687227/32958525-cac429d8-cb8c-11e7-8bec-d3f77a3467af.png">

**Comment by djbrooke** [comment]
Thanks, good details. Moving to backlog for estimation and possible inclusion in a future sprint.

**Comment by jggautier** [comment]
The files of more recently harvested datasets are in an unpublished state, but datasets harvested in April 2015 were "published". This is inflating miniverses uploaded files count.

**Comment by pdurbin** [comment]
> Because it is harvested and not local, this link should point to the external file pg, or if that doesn't exist, the external dataset pg.

I agree that this is a bug (good catch, @mheppler ) and that the link the in search card should not keep the user on the installation of the Dataverse that has done the harvesting, but I suspect that it will be difficult to know if the remote harvested file has a file landing page or not so we should probably just link to the dataset landing page of the remote dataset. That is to say, it's possible to harvest from non-Dataverse systems that may not have a file landing page. Every system should have a dataset landing page.

**Comment by pdurbin** [comment]
Related (as @mheppler pointed out): #4771

**Comment by landreev** [comment]
I was assuming this was being fixed on the card level; i.e. by modifying the search card so that it doesn't try to send the user to the file page. But as I was working on the file page for the ids-for-files branch, I figured I would add a redirect there, just in case somebody tries to open the file landing page for a harvested file. The code I added there (see below) is 100% copy-and-pasted from the dataset page; where it's working just fine. I have no idea why it's resulting in an error. But yeah, since the card is still not fixed, we now have even more spectacular errors, when people try to click on the cards for harvested files. 

The fix should be very straightforward though. Note that for harvested files we still redirect to the remote *dataset-level* url; (since most harvested files are not going to have dedicated file-specific pages on the original end). So all we need to do in the xhtml of the search fragment, is modify it so that it clicking on the file name does the same thing it's already doing when clicking on the dataset name... 

Here's the code I copy-and-pasted from datasetPage.java and into filePage.java; if anyone knows why it's working in the former, but bombing in the latter - I'd be curious to know:

```
// Is the Dataset harvested?
            if (file.getOwner().isHarvested()) {
                // if so, we'll simply forward to the remote URL for the original
                // source of this harvested dataset:
                String originalSourceURL = file.getOwner().getRemoteArchiveURL();
                if (originalSourceURL != null && !originalSourceURL.equals("")) {
                    logger.fine("redirecting to "+originalSourceURL);
                    try {
                        FacesContext.getCurrentInstance().getExternalContext().redirect(originalSourceURL);
                    } catch (IOException ioex) {
                        // must be a bad URL...
                        // we don't need to do anything special here - we'll redirect
                        // to the local 404 page, below.
                        logger.warning("failed to issue a redirect to "+originalSourceURL);
                    }
                }

                return permissionsWrapper.notFound();
            }
```

**Comment by landreev** [comment]
@mheppler 
Since I was already there, and the fix was only 2 xhtml lines - I went ahead and made a PR (https://github.com/IQSS/dataverse/pull/4787). I'm leaving it up to the team to decide what to do with it.

Also, since it was just one xhtml file, I took the liberty to just patch it in prod. Since those broken pages were kind of annoying. If that's a problem for whatever reason - it's just one file to un-patch: domain1/applications/dataverse-4.9/search-include-fragment.xhtml
