### ISSUE TITLE
As a data owner, I want to download a differentially private metadata file so that I can analyze it

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#4307]
In previous issues we've added the ability to configure tools (#4230, #4233) that allow for the creation of differentially private metadata and then added the ability for that information to be sent back (#4232) to Dataverse for storage (#4231).

To complete the workflow we'll need to provide a way to download the differentially private metadata.

**Comment by djbrooke** [comment]
In Sprint Planning 11/27, we decided to take on this instead of the more ambitious #4234. We'll take that on in a later sprint.

**Comment by mheppler** [comment]
After team discussions, we've added new "Data Summary" and "Data Summary (Differentially Private)" options to the Download dropdown button.

![screen shot 2017-11-30 at 1 21 49 pm](https://user-images.githubusercontent.com/687227/33447563-b34581fe-d5d1-11e7-9c35-98b909440605.png)

(Final link text to be reviewed and potentially revised.)

**Comment by pdurbin** [comment]
In b0918a5 I stubbed out the UI above. There's more work to do on this issue (see FIXMEs in the code) once #4231 and #4232 are complete. In short, this issue is about the UI. The backend needs to be built before the UI can be made real. I suspect we'll want to QA it all at once in a single branch.

@mheppler I guess I'm confused about what "Data Summary" is and if it's possible to download it now. Maybe it's the "prep" file? Over at http://guides.dataverse.org/en/4.8.3/api/dataaccess.html#parameters for "prep" it says, "“Pre-processed data”, in JSON. (TODO: get a proper description of the feature from James/Vito)". Either way, we probably shouldn't name @vjdorazio and @tercer right in our guides:

![screen shot 2017-11-30 at 2 36 52 pm](https://user-images.githubusercontent.com/21006/33451122-f63d86dc-d5db-11e7-932d-52b6465606a8.png)

**Comment by landreev** [comment]
@pdurbin we'll come up with a better name for/document the contents of the "prep file", eventually. 
We'll keep "preprocessed" as the supported format name in the API, for backward compatibility, etc. 
Please note that I've been trying to promote the alternative API method for getting the prep file (alternative to the /access/datafile/{id} with the "format=prep" argument, as described in the doc above); this:

/access/datafile/{id}/metadata/preprocessed

I believe TwoRavens is already using this method. 
(because, strictly speaking, this file is not a copy of this datafile in a different format - but a chunk of *metadata* describing the contents of the data file)

**Comment by landreev** [comment]
Please note that the PR referenced above (4338) is a combined branch with the code for this and also #4231 and #4232 issues. The branch previously associated with this issue (4307-download-psi-file)  should be discarded.

**Comment by landreev** [comment]
All the code created as part of the original branch (4307-download-psi-file) should now be included in this PR, as part of the 4231-psi-metadata-infrastracture branch (as is or refactored). 
@sekmiller I prefer not to keep the "isDifferentiallyPrivateMetadataAvailable()" method in the DataFile, for various reasons; so I refactored the pages accordingly.

**Comment by landreev** [comment]
As currently implemented, the differentially private version of the data summary fragment is shown in the download pulldown, if available. The raw, complete version is shown always, providing the user has permission to download the full data file. 
We may want to briefly discuss this tomorrow, just to make sure we know/are on the same page how that download menu should behave, for the demo, and in the longer run.

**Comment by landreev** [comment]
Specifically, I didn't get the part as to why "!hasDifferentiallyPrivateFile" was added to other types of downloads in that pull down. I don't think it was necessary. If this is a Sensitive data file, whether the differentially private summary has been generated or not, nobody accept the authorized users (nobody except the owner of the dataset, most likely) will be able to download the data, in any form. But that will be handled by the authorization; i.e. "fileDownloadHelper.canDownloadFile(fileMetadata)" will prevent the link for the download of raw tabular data from being rendered. But yes, we can review this tomorrow.

**Comment by pdurbin** [comment]
@landreev showed to the code to me @scolapasta and @sekmiller during tech hours. He's going to switch the hard coded `/api` in the xhtml to go through a service bean but otherwise we all seem to agree it's ready for QA.

**Comment by landreev** [comment]
Fixed the bug where the diffprivate download option was showing, even when it wasn't available.

**Comment by landreev** [comment]
@kcondon 
Fixed the label for the diff private metadata (the bug: when a guestbook is specified for the dataset, the "(privacy-preserving)" part was missing from the label). 

Download counts: as of now, both raw and diff.private metadata downloads ARE counted as downloads (with or without a guestbook defined for the dataset!)
This is how we've been handling downloads of variable-level DDIs all along (apparently) - which are also metadata.

**Comment by landreev** [comment]
@kcondon 
Also, I wasn't able to reproduce the part where a full file download wasn't counted; appears to be working for me - I'm seeing a new raw in the GuestbookResponse table consistently, whether there is a guestbook or not, whether I'm logged in or not, etc.

**Comment by landreev** [comment]
I'm going to add, as a separate comment, the 2 things that still need to be decided on: 
- Whether to add any authentication mods as part of this issue (such as what was done on beta, as part of the PSI demo, where the diff private metadata was shown for restricted files to users otherwise unauthorized to download the file); 
- Whether to count metadata (DDI, "data summary"), in the download count. 

Gustavo was going to facilitate finalizing these 2 things.

**Comment by kcondon** [comment]
I tested your fix and updated the list above.

**Comment by djbrooke** [comment]
Closing this issue for now. We'll pick this back up when we have DataTags support. 

The branch and issues will remain:

https://github.com/IQSS/dataverse/tree/4231-psi-metadata-infrastracture
https://github.com/IQSS/dataverse/issues/4231
https://github.com/IQSS/dataverse/issues/4232
https://github.com/IQSS/dataverse/issues/4307
