### ISSUE TITLE
Slow Page Load: Some dataset pages are slow to load, resulting in a timeout error.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4319]
Reported by a user, see RT 255773
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/PL2XFD&version=DRAFT
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/NRAQRH&version=DRAFT

When accessing these datasets, they are slow to load but at first glance there is nothing unusual about them.
For a superuser they do load but slowly. For a non-superuser with only curator perms they result in an apache timeout. After checking the apache log this is a garden variety timeout and increasing ProxyTimeout in httpd.conf and restarting allowed page to load for those users.

Page load comparison by role: 
Superuser: 37 seconds
Curator: 66 seconds.

The temporary workaround is to boost the Apache timeout to 2 mins but we really need to understand and fix what is causing the slowness.

**Comment by kcondon** [comment]
Additional observations that may be useful:
1. One of the slow datasets above became faster once it was published.
2. Unpublished datasets that are in review with double digit files appear to be slowest.
3. Unpublished draft only datasets not in review with double digit files load normally/fast.
4. Code relating to in review/ review workflow was recently changed.

**Comment by djbrooke** [comment]
Thanks for the details - moving to Backlog for estimation

**Comment by matthew-a-dunlap** [comment]
https://github.com/IQSS/dataverse/issues/1664 may be connected to this issue

**Comment by matthew-a-dunlap** [comment]
Info from earlier testing: The second dataset listed in this ticket (https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/NRAQRH&version=DRAFT) also exists on dvn-vm5 in what looks like the same state, so I have compared the load times across the two machines:

vm5 (with full db logging on, which may cause slowness):
load as Admin: 8 seconds
load as Contributor: 16 seconds

prod:
load as Admin: 38 seconds
load as Contributor: 80 seconds

I can see how prod would be slower due to load, but 5x slowness seems pretty extreme. I'm digging into the queries on vm5 now, but this is smells (at least somewhat) like a machine issue.

**Comment by matthew-a-dunlap** [comment]
Looking at the logs on vm5, they are twice as long in that time period when a contributor accesses the page.

Specifically:
admin calls _select .* from roleassignment where ..._  673 times
contrib calls _select .* from roleassignment where ..._ 2176 times

May be worth comparing vm5 logs to prod logs, tho I still suspect a machine issue for the speed difference. Next step is to run a profiler on my local and see what is being called for how long...

P.S. I noticed that SET application_name = '' is run before every query. It doesn't look instantaneous either (tho not especially slow). Seems unnecessary.

**Comment by matthew-a-dunlap** [comment]
I have fixed what slowdown I think I can for in review. Beside that, I fixed an issue with the dataset page file table calling the database once per file.

All of these issues I ended up fixing related to calling the permissionServiceBean instead of the permissionsWrapper. The calls to this bean always(?) hit the database and really add up on repeated calls. I wonder what we can do to ensure folks in the future work through the wrapper and not going directly to the service. There are a few other instances of us calling permissionServiceBean from the xhtml that should be cleaned up, tho likely none are this taxing on the system. 

I'm still curious about why prod is ~5x slower than vm5. Even if this is mainly due to prod being under load, we should know better to ensure performance for our end users.

**Comment by matthew-a-dunlap** [comment]
Performance for loading an in review dataset on my local machine with 60 files:

original: ~7.5 seconds
in review fixes: ~4.5 seconds
all fixes: ~3.5 seconds

I really hope we get more cycles to improve performance especially as we move towards 5.0, I think there are some fairly low hanging fruits there.

**Comment by pdurbin** [comment]
Pull request #4376 looks pretty good to me. I did leave this comment:

I've always thought of the `PermissionsWrapper` as UI-only feature that we only call from JSF backing beans but if we are able to use it in commands, that means that the API can benefit from the speed up as well! This is great. My only wonder is if we should `@Inject` `PermissionsWrapper` into individual commands like this. It might be better to weave `PermissionsWrapper` into the "engine` @michbarsinai built. I suppose this could be a future endeavor. I don't want to hold up progress.

I'm not going to drag it to QA because I want others to have time to take a look.

**Comment by matthew-a-dunlap** [comment]
@pdurbin Yea I'm not 100% sure about injecting into the commands as well. It worked without any issues I could tell but I am curious if there is a better solution as well.

**Comment by matthew-a-dunlap** [comment]
I am detaching myself from this story for now, as I going to wrap up #4343 first as I am pretty deep. I would be interested in picking this up when I am done but this could also be worked on my someone else.

**Comment by kcondon** [comment]
OK, retested performance on vm5:
user role, dataset id, published state, no fix time, fix time
super user, PL2XFD, in review, 17s, 6s
curator, PL2XFD, in review, 27s, 4s
super user, NRAQRH, in review, 13s, 4s
curator, NRAQRH, in review, 23s, 4s
super user, D5DEHM, published, 4s, 4s
curator, D5DEHM, published, 3s, 2s
super user, QO6EMT, published, 3s, 4s
curator, QO6EMT, published, 3s, 3s

Also did a brief smoke test of perms.
