### ISSUE TITLE
Move to AWS: Validate delivered AWS architecture

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4320]
1. Compare delivered vms against list of vms in proposed architecture. Check mem/cpu/storage. 
2. Check access to internal staff
3. Check firewall rules and port access for various services
4. Do a basic dataverse installation and test:
-core functionality
-basic storage performance
-load test

**Comment by landreev** [comment]
The LTS have just un-firewalled the nodes to be accessible from 140.247.116.* (the local subnet where our wired personal environments are). 
The test node currently set up is https://dvn-cloud-app-1.lib.harvard.edu (note: running with a self-signed cert; the existing prod. cert will be used eventually, once we cut over). 
All the other nodes will be cloned from this one. 

The instance is currently in the brand new, empty mode. It should be ready for a basic smoke test and poking. It is currently configured to use local storage - just so that we could run a basic smoke test on an out-of-the-box configuration. Once that passes, it can be switched to use S3 with the 2 JVM options.

**Comment by kcondon** [comment]
-Basic smoke test ok
-Cannot publish dataset due to connectivity issue to EZID
-Ringest not working (rserve not running)
-Explore buttons n/a, needs 2 Ravens reenabled.
