### ISSUE TITLE
Data Access API file download problem

### ISSUE THREAD

**Issue by conjugateprior** [IQSS/dataverse#4373]
I've been trying to figure out how to download one of my own data files (say id 109356) from [http://hdl.handle.net/1902.1/FYXLAWZRIA](http://hdl.handle.net/1902.1/FYXLAWZRIA).

The `dataverse` R package fails to let me do this. Bug report [here](https://github.com/IQSS/dataverse-client-r/issues/17). (tl;dr the metadata downloads but the requesting the file itself gives a 503 error.)

So I turned to the docs to see if I could get a working it working with curl. The introduction suggests a line of the form 
```
curl -H "X-Dataverse-key: MYKEY" https://demo.dataverse.org/api/datasets/:persistentId?persistentId=hdl:1902.1/FYXLAWZRIA
```
using the key MYKEY I generated. This failed with message
```
{"status":"ERROR","message":"Bad api key 'MYKEY'"}
```
which seemed odd since I just generated that key and pasted it out of my own user account. So I generated a fresh one and got the same error.
```
curl "https://demo.dataverse.org/api/datasets/:persistentId?persistentId=hdl:1902.1/FYXLAWZRIA&key=MYKEY"
```
also fails.

**Comment by pdurbin** [comment]
@conjugateprior thanks for opening this issue as well as the one about the documentation being confusing: #4374

> how to download one of my own data files (say id 109356)

This question has come up so often that for #3584 we started showing "Download URL" on file landing pages. It looks like this for the file id you mentioned above:

<img width="1203" alt="screen shot 2017-12-10 at 7 42 42 am" src="https://user-images.githubusercontent.com/21006/33804974-aea0fc3c-dd7e-11e7-9778-e3e633cdab16.png">

Once you have the download URL for a file you can just paste it into your browser...

<img width="1180" alt="screen shot 2017-12-10 at 7 43 46 am" src="https://user-images.githubusercontent.com/21006/33804976-aeb6bb62-dd7e-11e7-913e-7a3631bca07b.png">

... and the file should begin to download, like this:

<img width="554" alt="screen shot 2017-12-10 at 7 44 04 am" src="https://user-images.githubusercontent.com/21006/33804975-aeac3548-dd7e-11e7-8826-57093bb94b13.png">

This should work fine from the command line with `curl` but I thought screenshots like this would be easier to follow.

Please note that if you're actually using curl, you'll need to add `-J` or `--remote-header-name` to have curl save the file with the name that shows in Dataverse (1995-1999 Levels of Source _ Target.tab) rather than the file id (109356):

`curl -O -J https://dataverse.harvard.edu/api/access/datafile/109356` shows "curl: Saved to filename '1995-1999 Levels of Source _ Target.tab'".

**Comment by conjugateprior** [comment]
Great, thanks.

From this I conclude that:

- the Data Access API is not actually necessary for this kind of data access. 
- files get an id that is not relative to the DV they are in.
- it is still unclear why API access does not work for my repo, relatedly why the API does not believe in my token.

The first two would great things to have, or have more prominently, in the API documentation.

Re #3584, I didn't know how public the file was, having previously been obliged to click through some T&Cs in the browser.

For reference, I was planning to embed the data request in an R package. That now works as
```
> library(httr)
> resp <- GET("https://dataverse.harvard.edu/api/access/datafile/109356")
> content(resp)

No encoding supplied: defaulting to UTF-8.
Parsed with column specification:
cols(
  CODE = col_character(),
  LEVEL = col_character(),
  DESCRIPT = col_character()
)
# A tibble: 17 x 3
     CODE                       LEVEL
    <chr>                       <chr>
 1 <CAPI>                    Capitals

[snip]
``` 
which is perfect. 

So, this fixes the immediate problem and resolves the ticket. Thanks again.

**Comment by pdurbin** [comment]
@conjugateprior sure, but you mentioned a 503 before and when I did in a bit more I think you're onto something. Check this out.

I go to the file landing page at https://dataverse.harvard.edu/file.xhtml?fileId=109356 and click "Download" and then "Original File Format (UNKNOWN)" (seeing "UNKNOWN" here is already someone suspicious to me):

<img width="1140" alt="screen shot 2017-12-10 at 9 25 01 am" src="https://user-images.githubusercontent.com/21006/33805793-50e3cc42-dd8c-11e7-987b-1b1e9e2bc098.png">

Then, I get a 503 error at when `format=original`) at https://dataverse.harvard.edu/api/access/datafile/109356?format=original&gbrecs=true (last I checked `gbrecs=true` doesn't actually do anything):

<img width="1635" alt="screen shot 2017-12-10 at 9 25 21 am" src="https://user-images.githubusercontent.com/21006/33805792-50d3964c-dd8c-11e7-9133-ad39bbc8b2bf.png">

So there's something strange going on.

**Comment by pdurbin** [comment]
The "original file" download option is no longer available via the dataset above because worked on this issue: Make "download as original" disappear from download options, when there is no saved original. #4796 

Here's how it looks now:

<img width="291" alt="screen shot 2018-07-12 at 10 34 33 pm" src="https://user-images.githubusercontent.com/21006/42669548-09431b40-8624-11e8-956a-f241cf6dd4fb.png">

@conjugateprior , who opened this issue, seems fine with using the tab-delimited version of the file so I think it's safe to close this issue. It's specific to a file for a particular installation of Dataverse (Harvard Dataverse).
