### ISSUE TITLE
Data Access API docs

### ISSUE THREAD

**Issue by conjugateprior** [IQSS/dataverse#4374]
At the request of @pdurbin I'm noting here some ambiguities in the API documentation [here](http://guides.dataverse.org/en/4.8.3/api/dataaccess.html).

- What is the endpoint for these verbs? [This introduction](http://guides.dataverse.org/en/4.8.3/api/intro.html) suggests that the API can be tested using `https://demo.dataverse.org`. Is this also what should be used for production?
- When it says the basic download file access API is `/api/access/datafile/$id` how does this look in a call? Does it require `:persistentId?persistentId=doi:TEST/12345` to be appended as in the introduction? Is $id the integer identifier or the name of the resource?
- When documenting the `vars` parameter there is an example, but its access API is different: `http://localhost:8080/api/meta/datafile/6?vars=123,127`. Obviously the `localhost:8080` is a typo, but there is now `meta`. Is this intended? Is it the same for parameters like `format` that do not have examples?
- The bottom of the page states that "All of the API verbs above support the key parameter key=...". Do the verbs all require this or not? How do we tell?

**Comment by pdurbin** [comment]
@conjugateprior hi! We've made a number of tweaks which are reflected in the docs for 4.9.

http://guides.dataverse.org/en/4.9/api/intro.html#testing says "Rather than using a production installation of Dataverse, API users are welcome to use http://demo.dataverse.org for testing."

For your other points, can you please take a look at http://guides.dataverse.org/en/4.9/api/dataaccess.html and see if you're happier with what's written there? If we've missed anything, please let us know! Thanks!
