### ISSUE TITLE
As a researcher, I want my provenance to be made available to other researchers at publish time so that they can make better use of my data

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#4381]
In #4343, we've added the ability to add Provenance files/freetext to Dataverse. 

When this story is done, we'd expect those files to be sent to the provenance system and saved.

**Comment by djbrooke** [comment]
ping @mklau

**Comment by jacksonokuhn** [comment]
On the upload page, can we refer to the provenance as "Documents" rather than "Bundles"? We're storing the data as bundles on the backend, but they're gonna be uploaded as standard PROV-JSON docs. The current wording may confuse people.

**Comment by mheppler** [comment]
@jacksonokuhn Your suggested revisions for the label/help text in the UI has been committed by @matthew-a-dunlap as part of issue #4343 b058423d8caba0db73f9b1bda2a41fd96b2e3d94. @dlmurphy was going to address the User Guide revisions in that branch as well.

**Comment by dlmurphy** [comment]
Update: instead of "bundle file", we're using "provenance file" as our terminology to describe the JSON file that users upload which contains provenance information about their data.

**Comment by mheppler** [comment]
Updated the mockups link in the first comment from @djbrooke to point to the mockups that include the Provenance tab on the file page, as opposed to the file upload workflow, which is covered in issue #4343.

Included in that 4343 issue is a comment of mine that outlines ["what we are building"](https://github.com/IQSS/dataverse/issues/4343#issuecomment-350782107). Here is an outline for this preview issue.

**What we are building**

File Pg
- New Provenance tab, in between Metadata and Versions
- Add Provenance button that links to Provenance popup
- Provenance option in Edit button dropdown menu that links to Provenance popup
- "Why Use Provenance?" info text if provenance does not exist
- Info text if provenance exists
- Description label and provenance free-form text value displayed if it exists
- Graph (from info in Provenance system) if provenance info exists from JSON file upload and/or system transformations
- Export Provenance button if provenance exists

**Comment by jacksonokuhn** [comment]
so here's basically what needs to happen on publish as a series of api calls:
- create a bundle
- create an activity called something like "[dataset-id]-publish"
- add the property "generatedAtTime" to that activity
- lookup or create the user who's publishing the dataset
- connect the publish activity to that user
for each datafile:
  - create an object called "[datafile-id]" for each datafile that isn't in the prov system
  - connect each of those datafiles to the publish activity
  (we might also want to connect each datafile to its contributors, although strictly speaking 
  this is a property of datasets not datafiles and might wait until we start making dataset prov)
  for any datafile that's a replacement:
    - lookup or create the previous datafile
    - connect the current datafile to its predecessor

**Comment by jacksonokuhn** [comment]
to connect the prov generated by publish to user uploaded prov, we do the following:
- upload the json with anchor_objects:{[id: internal id of datafile, name: name of datafile in uploaded json]}

**Comment by matthew-a-dunlap** [comment]
During our weekly technical meeting we identified an additional need for dataverse communicating with the provenance system (CPL). Specifically, we identified that CPL needs us to combine our uploading of provenance json into one call in cases where the provenance json is the same. To do this, we will need to look at all the provenance json being sent to CPL when we publish and see if any of the bundles match. In cases where they do match, we will need to tell CPL that that bundle points to multiple DataFiles and provide those files in a list. (Note: this description is a tad vague as I do not understand Prov syntax and the CPL apis well enough to give better details.)

Someday this could be improved with a UI enhancement to allow the user select for one DataFile a prov.json file already uploaded for another file.

Open questions:
- What happens if a user uploaded a prov json file in the last published version of the dataset and then needs to use that same json file with new DataFiles in a subsequent dataset version? Is there something special we need to do in this case or can CPL handle us re-uploading the same json.

**Comment by pdurbin** [comment]
Hopefully b23c396 gives a sense of what I've been working on lately, which is the "automatic" creation of prov data based on normal, boring interactions that Dataverse has supported since the beginning of time. That is to say, all I'm doing is creating a dataset, uploading a file, and publishing the dataset (all in `ProvIT.java`). The difference is that I stubbed out a new API endpoint that is supposed to represent what happens when the user clicks "Export Provenance" as in the screenshot below from #4346, which is that some JSON is supposed to be downloaded. You will notice many FIXMEs in the code because I'm not sure how the JSON is supposed to look. @jacksonokuhn will be able to advise on this.

![export-prov](https://user-images.githubusercontent.com/21006/36327448-aec84542-132c-11e8-8237-394f15d44fb2.png)

After looking at that commit and seeing that I was starting to implement something that's different than what @jacksonokuhn had in mind, he updated his comment at https://github.com/IQSS/dataverse/issues/4381#issuecomment-364790503 to put in more detail (thanks!) of the REST API endpoints that should be called into from the `FinalizeDatasetPublicationCommand`. Those endpoints are documented at https://github.com/ProvTools/prov-cpl/blob/master/bindings/python/RestAPI/rest-docs.txt and on the Dataverse side I'm using `ProvenanceRestServiceBeanIT.java` to test calling into them statically before moving the logic into the publish command above.

To work on this issue, one must have the prov system running, which @matthew-a-dunlap and @sekmiller have done following instructions in pull request #4461. In #4364 @jacksonokuhn is working on moving the config from the Dataverse git repo to the cpl-prov repo but for now those configs in the pull request work fine. You download a couple files and spin up an Ubuntu VM in Vagrant running prov.

I'm on vacation next week so I'll take myself off this issue.

**Comment by jacksonokuhn** [comment]
So @matthew-a-dunlap and I were talking and it looks like there was a bit of confusion around order of operations. We should generate the automatic publish PROV and THEN upload the PROV bundle. I can talk about it more with whoever is working on this.

**Comment by djbrooke** [comment]
Will close for now, will reopen if we decide to take on a similar approach with further provenance work.
