### ISSUE TITLE
Guestbook responses aren't always being recorded

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#4394]
For several guestbooks on Harvard Dataverse, but not all guestbooks, when people download files in datasets with enabled guestbooks, a record of that download is not showing in the UI (where dataverse owners can preview or download responses).

**Comment by pdurbin** [comment]
Since we are seeing a mix of guestbook responses being recorded or not, I thought it would be helpful to provide id numbers of the guestbooks in Harvard Dataverse for troubleshooting purposes. These IDs refer to the `guestbook` database table.

- Guestbook IDs where responses **are** being recorded: 13, 18
- Guestbook IDs where responses **are not** being recorded: 80, 204

From the perspective of the person filling out the guestbook, you can tell whether or not your guestbook response has been recorded by observing if the download count increments or not. Here's an example from http://dx.doi.org/10.7910/DVN/WS9OUR which uses guestbook ID 80:

![screen shot 2018-01-03 at 12 30 05 pm](https://user-images.githubusercontent.com/21006/34531866-dc5c26d6-f081-11e7-8539-b4fdbc454621.png)


From the perspective of the person with access to the guestbook entries, you can see if they have been recorded or not by looking in the UI or by downloading the responses and opening them in Excel or similar. (@jggautier indicated he tried both.)

Sysadmins can check the `guestbookresponse` database table. They would also do well to see if there is an exception appearing in Glassfish's server.log when responses are not being recorded.

We've only see this problem in production. I have been unable to replicate it on my laptop as of 530377d on the develop branch.

**Comment by jggautier** [comment]
I'm not able to reproduce this bug anymore on Harvard Dataverse using the guestbooks I looked at yesterday (01/02/2018). Closing this ticket.

But here's what I did for the guestbooks (13 and 18) referenced in Phil's comment above:

- Download file from a dataset that has a guestbook enabled
- Check the Manage Dataset Guestbooks page of that dataset's dataverse
  - View guestbook responses table to see if download was recorded
  - Download All Responses to see if download was recorded
