### ISSUE TITLE
Sorting guestbook responses by date doesn't sort chronologically

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#4395]
When viewing guestbook responses in the table, clicking on the Date header doesn't sort guestbook responses by date chronologically.  Seems like it's sorting the characters alphabetically by month, then numerically by date and year.

I could see this on Harvard Dataverse and Demo Dataverse.

![screen shot 2018-01-03 at 1 05 19 pm](https://user-images.githubusercontent.com/18374574/34533157-02243246-f087-11e7-9d61-8c4dea33c3fc.png)

Sorting by other columns does seem to work.

**Comment by pdurbin** [comment]
This issue was estimated as a "1" and the easiest one-line I could come up with is in pull request #4400 which is to simply use ISO 8601 format (i.e. 2018-01-08) and continue to sort by strings.

It looks like this:

<img width="483" alt="screen shot 2018-01-08 at 3 06 10 pm" src="https://user-images.githubusercontent.com/21006/34690226-4f1cd262-f486-11e7-81f6-e6d302912b5b.png">


ISO 8601 is the XKCD way! https://xkcd.com/1179/

![iso_8601](https://user-images.githubusercontent.com/21006/34690218-484fb45e-f486-11e7-98fc-86149416917e.png)

**Comment by mheppler** [comment]
Highly related to **Date/Time Stamp Format - Consistency Across App #1391**.

**Comment by mheppler** [comment]
In today's status mtg I proposed apply the same sort bug fix to the table on the Manage Templates pg. If it is a similar one line fix, we should try to kill two birds. (See my comment above for link to related issue about the inconsistent date display formats.)

![screen shot 2018-01-09 at 12 37 56 pm](https://user-images.githubusercontent.com/687227/34734535-15f12402-f53a-11e7-902b-34ac3d60a251.png)
