### ISSUE TITLE
Spike - Support for Stata versions 14 and 15

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#4408]
In Backlog Grooming 1/10, we tried to estimate #2301 and we weren't able to do so. The suggestion was to create a 1 point Spike with the goal of being able to estimate (together as one issue or as separate issues):

- Stata 13 (may work in certain cases)
- Stata 14
- Stata 15

**Comment by landreev** [comment]
Once again, we DO support Stata 13 already. Rather than "may work in certain cases" it's the other way around - there may be instances of Stata 13 files that we can't ingest. Whether because there's a bug in our implementation; or because something was missing from their documentation that was used to implement the ingest plugin - so we may be coming across some data encoding that we don't know how to handle. We can handle such cases as bug fixes/improvements of the Stata 13 ingest plugin. (we have a record in the prod. database of every Stata 13 file that failed to ingest and the files themselves - so it should be easy to diagnose and fix any such issues). 
I used to say that we should always be careful to create realistic expectations; by communicating to the users that we cannot promise that we'll ever be able to ingest 100% of files in a certain format. By nature of working with somebody else's proprietary formats. But we can definitely work to make the success rate higher. 
However, with Stata in particular, since they have been doing an exceptionally good job documenting their formats, it appears to be possible to achieve a success rate that is close to 100%.

**Comment by djbrooke** [comment]
Updated #2301 and #3339, closing.
