### ISSUE TITLE
Dataset Linking: As a dataverse owner, I want to link a related dataset to my dataverse to help relevant researchers find it.

### ISSUE THREAD

**Issue by dlmurphy** [IQSS/dataverse#4410]
This issue is narrowed down from the earlier, broader issue #2053.

Currently, only Super Users have the ability to link other users' datasets to their dataverses. This functionality used to be available to all users before Dataverse 4.0. Let's restore this functionality so all users are able to link others' datasets to their dataverses.

Issue #1840 also seems relevant.

**Comment by pdurbin** [comment]
Huh, I didn't realize this was a feature of DVN 3.x but sure enough "Link Datasets/Studies" appears on the "3.6 & 4.0 Feature Comparison" spreadsheet at https://docs.google.com/spreadsheets/d/1ftHM6E4b9Dft_AvA6KTzeklJyLguItz2_0hNAFL8-VM/edit?usp=sharing

Please note that even superusers cannot delete links. That's what #1364 is about.

**Comment by mheppler** [comment]
Today in Slack @thegaryking brought up this feature, requesting:
>trying to add an existing data set to my dataverse... the options here are new dataverse and new data set. can we add ‘existing dataverse’ and ‘existing dataset’?

Also, related to the feature's name, "link" he said:
>‘add’ sounds more coherent to the user i think. i’m just adding to my dataverse

All good feedback to consider when adding this feature for all dataverse admin's. Bonus feature request, also from Gary, to have the system suggest datasets to dataverse admin's:
>“we found this data set that’s like the ones in your dv, would you like to add it?“

Some related issues to also consider:
- Linked/Saved Search: Review Functionality + Usability Test #1840 
- Saved Search - Improve Performance & User Experience #1939 
- Linked Search: Creating linked searches fails in production with blank popup due to timeout. Works on smaller db's like demo. #2167

**Comment by dlmurphy** [comment]
After much deliberation, some updates to this issue:

- This issue will cover dataset linking. There will be a separate issue to cover dataverse linking soon.

- The main impact of this issue is to open up dataset linking to all users, not just superusers.

- A user creating a new link will need their account to have a role that includes the "Add Dataset" permission on the dataverse that is doing the linking.

- A user creating a new link will not need any special permissions on the dataset BEING linked.

- Any user can link to any published dataset.

- For now, there will not be a way to remove links in the UI, but there is a currently existing way to do it via API.

- This feature will use the existing linking UI, with one exception: On the "Link Dataset" modal, we will replace the "Your Dataverses" drop-down list with a type-ahead box.

For future reference, this is our document where the design team deliberated on this feature. Keep in mind that it is not 100% up to date, especially regarding permissions: https://docs.google.com/document/d/14J8uBV4kNPHDfbiumNNKb01tdEksPpnfbRklrY1KhAc/edit

**Comment by sekmiller** [comment]
@mheppler as Derek noted above, the linking popup now contains a type ahead box for dataverse names (the dataverse you want to link to) If you type in a partial name you'll get all of the dataverses you have permission on. If there are none you'll get "No dataverses available for linking" The code is in dataset.xhtml Any suggestions on format or bundle messages are welcome.

**Comment by mheppler** [comment]
Final to-do's:

- [x] Clean up layout
- [x] Return and improve messaging from previous version of popup
- [ ] Form does not validate if you have entered anything, returns to dataset with success msg
- [ ] Autocomplete component was not working for dataverseAdmin, plus two other users on multiple datasets, when entering the first 3+ characters for multiple dataverse names

**Comment by kcondon** [comment]
Issues found:
1. Can link a published dataset to an unpublished dataverse. Should not be able to according to logic we used in api.

**Comment by dlmurphy** [comment]
I added sections on the dataset and dataverse linking command to the Native API page of the API Guide, since these two commands are now accessible to non-superusers. I left those sections in their original place in the Admin Guide too, since they're still useful there alongside the Move and Unlink commands that are still necessary in that guide.

**Comment by dlmurphy** [comment]
Whoops, I got ahead of myself, this issue is just about dataset linking. Putting the dataverse linking section back in its original place in the guides for now.

**Comment by sekmiller** [comment]
After discussion we will allow links to be added to unpublished dataverses. Also I updated the success message to reference the email address, @dlmurphy is updating the guides.

**Comment by dlmurphy** [comment]
Greatly expanded the user guide section for dataset linking in commit baa12d8

I think this is ready for code review, but @sekmiller is welcome to pull it back if I'm sending it over prematurely.

**Comment by mheppler** [comment]
Discussed with UX team, will revise `dataset.message.linkSuccess` message to not include the support email. Instead will move the "to remove this link..." msg to a help msg that is displayed in the Link Dataverse/Dataset popup, and will have it open the support popup like we do for other msgs.

**Comment by jggautier** [comment]
Just adding here for posterity the decisions made about how the type-ahead field works for dataset linking through the UI: Dataverse allows users to create dataverses with names that are 1 or more characters. But when the user starts typing in the type-ahead field to look for a dataverse to add a dataset link into, the field will start displaying matching dataverse names after 3 characters have been entered into the field. (The component used for the type-ahead field has a default character limit of 2 characters.) Which means that the user won't be able to find dataverses that have names that are fewer than 3 characters. This is fine for Harvard Dataverse because all published dataverses have names (display names, not aliases) that are more than 3 characters (and the unpublished dataverses that have names with fewer characters are obviously test dataverses).

Open questions we've decided to address later:
- Is it reasonable that dataverse names in other languages could be fewer than 3 characters?
- Should Dataverse enforce the number of characters that users can enter for dataverse names (e.g. through field validation), and should setting this character limit be an easily configurable setting?

**Comment by mheppler** [comment]
Added configurable support team name and text link to contact popup to dataset linking popup help msg, removed it from success msg.

Sending back to @sekmiller for a bug fix.

- [ ] When using capitalization in the autocomplete input, it can not find the same results that using lower case returns.

![screen shot 2018-09-20 at 10 56 23 am](https://user-images.githubusercontent.com/687227/45827514-938e7980-bcc4-11e8-89fe-9d0571878700.png)
![screen shot 2018-09-20 at 10 56 40 am](https://user-images.githubusercontent.com/687227/45827523-96896a00-bcc4-11e8-90e0-17e31883001a.png)

**Comment by kcondon** [comment]
@dmurphy @scolapasta @sekmiller
Noticed a couple things that may or may not require a change but does need a ruling so I'm passing back to Dev for comment:
1. Note above says UI linking a published dataset only but API allows unpublished dataset linking (the original implementation) as long as you own it/ have perms on it. Might be useful in the prepublication author/project dataverses scenario.
2. Dataset Unlinking API exists, why isn't it available to the end user like create link API is? Seems like it would not take much effort. Plus, it would enable users to remove their own links rather than having Support do it.

**Comment by dlmurphy** [comment]
Just talked about that first point with Danny - let's have both the UI **and** API require that a dataset is published in order to link it.

We talked about the second point too. For now let's leave the unlinking API as it is, and if we end up getting a ton of support tickets we can revisit.
