### ISSUE TITLE
Terms of use for Native API

### ISSUE THREAD

**Issue by solhm** [IQSS/dataverse#4431]
Terms of use already added to API https://github.com/IQSS/dataverse/issues/1718 but it is only for SWORD, it would be great if it is available via the native API in JSON format too. It can go into "info"  http://guides.dataverse.org/en/4.8.5/api/native-api.html#info

**Comment by pdurbin** [comment]
@solhm nice chatting with you at http://irclog.iq.harvard.edu/dataverse/2018-01-24 and thanks for opening this issue. As I mentioned, I'd be happy to advise you if you'd like to make a pull request.

Please look at how ServiceDocumentManagerImpl.java calls this...

systemConfig.getApiTermsOfUse()

... over at https://github.com/IQSS/dataverse/blob/v4.8.5/src/main/java/edu/harvard/iq/dataverse/api/datadeposit/ServiceDocumentManagerImpl.java#L77

The Java file you would edit for your pull request is this one:

https://github.com/IQSS/dataverse/blob/v4.8.5/src/main/java/edu/harvard/iq/dataverse/api/Info.java

`systemConfig` is already being used. I would suggest using `@Path("getApiTermsOfUse")`

The rst file to edit is this one:

https://github.com/IQSS/dataverse/blob/v4.8.5/doc/sphinx-guides/source/api/native-api.rst#info

If you feel like writing tests, this is the file to edit:

https://github.com/IQSS/dataverse/blob/v4.8.5/src/test/java/edu/harvard/iq/dataverse/api/InfoIT.java

I hope this helps.

**Comment by pdurbin** [comment]
@solhm just mentioned in IRC that he'd like to work on a pull request. Thanks!

**Comment by pdurbin** [comment]
@solhm thanks for making pull request #4436! I just approved it but did make a couple suggestions.

I move this issue to Code Review at https://waffle.io/IQSS/dataverse in case other developers want to take a look. They'll see it at standup a a few hours.

I also just added this to "Dev Efforts by the Dataverse Community" at https://docs.google.com/spreadsheets/d/1pl9U0_CtWQ3oz6ZllvSHeyB0EG1M_vZEC_aZ7hREnhE/edit?usp=sharing . Thanks for this contribution!

**Comment by djbrooke** [comment]
Thanks @solhm and @pdurbin !

**Comment by pdurbin** [comment]
At standup, developers were fine with my code review, so I'll move this to QA.

@jggautier @dlmurphy @djbrooke and I talked a bit after standup. They wanted to know the link for Harvard Dataverse's API Terms of Use and it looks like it's at http://best-practices.dataverse.org/harvard-policies/harvard-api-tou.html according to https://github.com/IQSS/dataverse/blob/v4.8.5/scripts/api/setup-optional-harvard.sh#L11 . This in an example of "[flagship bias](https://docs.google.com/document/d/1-LtDv_Yaf_3EPuMWcg5ZxH7M2ACrmCzPzgmbwbt8gMQ/edit?usp=sharing)" in the sense that Harvard-specific information like this should be hosted somewhere under "harvard.edu" rather than "dataverse.org" (unless we plan to allow other installations of Dataverse to host content under "dataverse.org", which I doubt). In the future, when this content is hosted somewhere under "harvard.edu", we could update that `setup-optional-harvard.sh` script.
