### ISSUE TITLE
do not require log in for Restricted Access request

### ISSUE THREAD

**Issue by CCMumma** [IQSS/dataverse#4444]
University of Texas Austin liaison from the Texas Data Repository (4.8.4) requests that login not be required to request access to a restricted file. Her user plans to use the guestbook feature, as well, to track the user requests, but the requirement that the requester login is prohibitive since he expects requests for download to come from people from outside of the TDR Dataverse institutional member community.

**Comment by pdurbin** [comment]
@CCMumma thanks for opening this issue. It reminds me a lot of #2043 and the demo that @stevenmce and @mdmADA gave a few months ago of some code they are working on. Instead of a guestbook we were somewhat jokingly referring to it as a "requestbook" because the idea the person requesting access to the data fills out a form as they are requesting access. I'm not sure if you have to be logged in to fill out this "requestbook" or not but perhaps they can give you a demo. (Actually, judging from Steve's writeup at https://groups.google.com/d/msg/dataverse-community/5NBM1jdGZTw/g3URrTzOAgAJ ADA's "requestbook" feature requires login.) If your liason's main requirement is not requiring login (I assume some way to get in touch, such as an email address, would be required) maybe it's different enough from the ADA work that the requests shouldn't be conflated, but I thought I'd make sure it's on your radar.

Would this be a global setting? The "Request Access" button would never require a login for the whole installation of Dataverse?

When people come along and click "Request Access" without logging in, would there be required fields such as email and name? Would there be a CAPTCHA? I'm thinking about the support form, which doesn't require login either:

![screen shot 2018-01-31 at 9 34 03 am](https://user-images.githubusercontent.com/21006/35628450-ed35a1aa-0669-11e8-920a-c15fb1cef7c0.png)

**Comment by TaniaSchlatter** [comment]
Hi @CCMumma, in this scenario of use, I assume the data would always be non-confidential/CCO?

**Comment by trelogan** [comment]
Hi all – I’m the UT-Austin TDR liaison who requested this. Many thanks @CCMumma for opening up the issue, and to @pdurbin for your swift reply! 

I’m imagining this, as you suggest, @pdurbin: A global setting that would not require a login for anyone in our Dataverse installation, and that the alternative would be exactly like the support form you suggested (and it would go directly to the email of the contact person for that dataset, not to me!). I am fairly sure that any of our researchers who publish restricted data are thinking of a wider requesting community than just within our institution. He’s certainly hoping to disseminate his work more widely than just to UT—this is his dissertation research and he’s moving on to a faculty position elsewhere. 

@TaniaSchlatter, the data are confidential (i.e. de-identified), but the researcher wants to be extra cautious to avoid any potential re-identification. He’s working with a vulnerable Latin American population. He has opted to use a Data Use Agreement based on the Harvard example instead of CC0. He’s also using a guest book, but still wants to control the access, just in case.

**Comment by CCMumma** [comment]
Hi all,

At TDL, we have closed this issue since we've implemented the Google OAuth login option. This way, outside researchers can create accounts and be given specific permissions from the TDR-affiliated researchers with whom they work.

I think we can close this issue.

Courtney Mumma, TDR

**Comment by pdurbin** [comment]
Thanks, @CCMumma . I think I recall Jessica Trelogan or Anna Dabrowski mentioning Google OAuth in their "Inside-Out Impact of the Texas Data Repository" last week: https://projects.iq.harvard.edu/dcm2018/agenda

I'm glad you've figured out a work around. Thanks for helping with the backlog grooming of our issue tracker!
