### ISSUE TITLE
head.meta.description configurable

### ISSUE THREAD

**Issue by lmaylein** [IQSS/dataverse#4468]
Is it possible to make head.meta.description configurable?

Google use the description for the snippet in its search result:

![heidata](https://user-images.githubusercontent.com/7468155/36249061-d3a349dc-1239-11e8-8df6-54f8c71ab4d6.png)

At the moment I have managed that by editing Bundle.properties

**Comment by pdurbin** [comment]
@lmaylein good idea. It's not only in Google searches where this hard-coded text appears. I also see it all the time in Slack when I link to an installation of Dataverse. I agree that it would be nice for this to be configurable. I assume only supporting plain text is fine. I expect the pull request would be fairly small and look something like pull request #3380.

For developers, here's where the line in question is: https://github.com/IQSS/dataverse/blob/v4.8.5/src/main/java/Bundle.properties#L89

**Comment by mheppler** [comment]
Thank you for opening this issue, @lmaylein. 

Rather than just editing the description text in the `Bundle.properties` file with a configuration setting, the `<meta name="description" content="#{bundle['head.meta.description']}"/>` facet in the `dataverse_template.xhtml` file will need to be more dynamic in order to better improve the use of that meta value.

As recently pointed out by @jggautier, @bencomp and @borsna in development for dataset meta tags, issue #1393, that software description is not only on the installation's root dataverse pg, but is also on all other dataverse pgs, all dataset pgs, and every other pg of the app.
> the existing static description meta tag on landing pages... should describe the dataset instead of the software

To be optimize the the description, it should be dynamic enough of a solution to work for every page, as it is part of the template. This feature was original adding in 4.0 as part of issue #1802, and we should update it, along with the `<link type="image/png" rel="image_src" href="#{resource['images/dataverseproject.png']}" />` image that gets displayed along with the description in when links are shared on Twitter, Facebook and other social platforms.

**Comment by pdurbin** [comment]
@lmaylein are you interested in making a pull request or do you have access to a developer who can? Making the change I suggested above would be pretty straightforward and I'd be happy to help coach someone on what to do.

**Comment by pdurbin** [comment]
@lmaylein oh, I thought you wanted to set head.meta.description once for the whole installation. That, to me, would be good progress, just to have the text **not** be hard coded, to have the text be about your installation of Dataverse, rather than being about the project. Now you seem to be saying that the text would vary based on where in the tree of dataverses one has navigated to. Do keep in mind that descriptions are optional for dataverses so you'd need to decide what the text would be in this case.

**Comment by lmaylein** [comment]
@pdurbin I wasn't sure if a temporary solution really is okay because of the problem described by @mheppler 

Maybe a dataverse without any description could inherit it from a parent dataverse? Or we could suppress the meta tag if there is no description?

I thought it could even be easier to use the same template variable for the description within the meta tag and within the displayed description. Maybe we need a second template variable with eliminated tags.

**Comment by pdurbin** [comment]
@mheppler is thinking holistically, which is extremely valuable. I'm thinking about the smallest change possible to get the description of the Dataverse project out of head.meta.description. I mentioned how no matter which installation of Dataverse I link to in Slack, I always see the description of the project, like this:

<img width="547" alt="screen shot 2018-07-17 at 10 08 25 am" src="https://user-images.githubusercontent.com/21006/42822624-85cc4d20-89a9-11e8-8305-716a1317aa3a.png">

When I link to any page under https://heidata.uni-heidelberg.de in Slack, I'd like to at least see a description of your installation, @lmaylein , rather than a description of the Dataverse project.

**Comment by lmaylein** [comment]
This is the part of dataverse.xhtml which is responsible for the description display:
```
<div id="dataverseDesc" style="margin-bottom:1em;">
   <h:outputText value="#{MarkupChecker:sanitizeBasicHTML(DataversePage.dataverse.description)}" escape="false"/>
</div>
```
Wouldn't it be a very small change to use something like
```
#{MarkupChecker:sanitizeBasicHTML(DataversePage.dataverse.description)}
``` 
within dataverse_template.xhtml instead of
```
<meta name="description" content="#{bundle['head.meta.description']}"/>
```

**Comment by pdurbin** [comment]
@lmaylein you're right. That would be a nice small change. Do you want to go ahead and make a pull request for this?

**Comment by pdurbin** [comment]
@lmaylein thanks for making pull request #4879! I tried it out on my laptop and it seems to work fine. If the dataverse doesn't have a description (it's not a required field), the meta description is simply blank (`<meta name="description" />`) which I think is just fine. I'm moving this to QA. Thanks!

**Comment by kcondon** [comment]
Discussed with Julian and Tania. Fine with current scope but should open a new ticket covering dataset and file pages, seek out community input on what it should entail.
