### ISSUE TITLE
Maintaining documentation for older versions of Dataverse - make it less confusing 

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#4476]
Gary brought up this specific example: 
If you Google for the UNF documentation, the (current) top result on the page is a link to the Dataverse 4.5.1 version of the document. That has some information that's no longer the most accurate/up-to-date, plus the copyright 2016. It is not immediately obvious to the user that they are looking at a version of the document that's no longer the most recent/up-to-date. 

Multiple things going on/multiple ways to address this: 

- We want to continue providing documentation for the older versions of the documentation; it probably makes sense to continue treating them as "frozen in time" and not mutable. 
- But maybe we could make it more obvious to the reader that they are looking at a version that's no longer the latest release. (a header added to every guide page, "you are looking at the version N.M, released in YYYY-MM; click here to see the latest version ...?)
- Let's investigate the best way to make Google show the most recent versions of the docs. It should be possible to purge their cache of guides.harvard.edu; and maybe modify the robots file there to instruct the google bot to only crawl the /latest - ?

**Comment by mheppler** [comment]
Found a simple solution for the `robots.txt` file in this (Stack Overflow answer)[https://stackoverflow.com/a/19869586].

```
User-agent: *
Allow: /en/latest/
Disallow: /en/
```

This tells the robot crawlers to only index the `/latest/`and ignore the rest of the versions. While it does not remove the old versions from the search results index, they will eventually be removed when the robots no longer have access to them.

While this technically delivers what was asked in this issue, I went a little a further to improve the guides for future version. It turns out that there is an `index.rst` for [every version of the guides](http://guides.dataverse.org/en/latest/) that claims, "These guides are for the most recent version of Dataverse", which only true for a few months until we release the next version. So I have changed that line, as well as the next line.

```
These guides are for the 4.8.6 version of Dataverse. To find guides belonging to previous versions, Dataverse Guides Versions has a list of all available versions.
```

There is also a link for "Dataverse Guides Versions" to a new page that links to all the previous versions. When releasing, it appears that Kevin had been editing this `index.rst` to add the new versions numbers and update the link to the previous versions. Now, those edits can be done on the new `versions.rst`. (FYI, the version number in the title and first sentence on `index.rst` has been changed to be dynamic, pulling the version number from `config.py`.)

![screen shot 2018-04-24 at 3 02 03 pm](https://user-images.githubusercontent.com/687227/39210222-1488574a-47d6-11e8-9ec0-38a5ad9bf566.png)

The new Dataverse Guides Versions pg has also been linked to in the footer. This way it is clear which version of Dataverse these guides are associated with, and how to get to the latest and greatest version.

![screen shot 2018-04-24 at 3 43 51 pm](https://user-images.githubusercontent.com/687227/39210302-4f185bbc-47d6-11e8-95ee-285278966846.png)

**Comment by kcondon** [comment]
OK, put robots.txt up on guides.dataverse.org

**Comment by mheppler** [comment]
Cleaned up the new versions pg in the guides based on feedback from Phil and Kevin, adding a brief paragraph to the top of the page with a link the Releases pg in our GitHub repo. Updated the release process documentation in `making-releases.rst`. Commented out the following line in there until we have a commit with the new process to link to.

> Here's an example commit where all three files were updated at once: https://github.com/IQSS/dataverse/commit/813b66a6077e8f94026a8db5320cceffefc10e11
