### ISSUE TITLE
Create a configurable, scheduled process for the BARI researchers to process and deposit ("stream") Analyze Boston data into their dataverse automatically.

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#4530]
(See the discussion/emails below for more details; note that we are designing this as a potential basis for a future framework that can be utilized by other researchers and applied to raw data coming from sources other than BARI. Which could include "real" streaming of aggregate raw data - from experimental instruments, social media, etc. etc.)

The BARI group currently has researchers that run scripts to get the data from a preexisting API, process the output using a script, and then deposit that data into Dataverse using existing deposit APIs. We should provide a way for these scripts to be run in a different place and take into consideration the following:

- This should be a new Github repository outside of Dataverse or provide the script(s) in another project location
- Command line only is OK
- Will need to support an API token and a way of defining where the data will be deposited
- Will need to support a way of scheduling the script to be run at certain intervals 
- The BARI researchers that have immediate need for this use R, so that should be first case we support

**Comment by scolapasta** [comment]
For now, the idea is to have a script that takes in the needed inputs:
• data source
• script source
• dataset (which would include info on the Dataverse installation)
• API token
and works as a one time operation.

It will be able be scheduled as a cron job.

**Comment by landreev** [comment]
In addition to the above, a couple of extra assumptions my implementation is based on: 
- "data source" is an http(s) url pointing to a web directory where 1 or more files can be found. the depositor script crawls the location and selects the files that are newer than the time of the last successful job run for this deposit location (if available; unless this is the first crawl that is). So this works similar to harvest in other words. 
- 1:1 relationship is assumed between the source files and the deposited datafiles; i.e. the script downloads a file and runs the configured processing script on it, expecting to get one output file. if this works, the resulting output file is deposited as a datafile in the specified dataset. 
- the result of the process - how many files found, how many were successfully processed, how many were successfully deposited - is emailed to the configured address(es). (the owner of the dataset; and maybe to the dataverse admin too?)

**Comment by landreev** [comment]
Here's an update on the status of the project; also clarifications and corrections of some of the assumptions above. 

1. I have been in touch with Justin and Nolan; got some sample R code from them and some clarifications on what we are trying to achieve. Will add some of the emails to the issue. 

2. The "API" for downloading the data from the Analyze Boston initiative is quite simple. They (currently) provide 134 "datasets". Each dataset can be downloaded an HTTP GET on "https://data.boston.gov/dataset/" + specific dataset id (obtainable from the list returned by package_list query in the API). For example: 
```
"https://data.boston.gov/dataset/cd1ec3ff-6ebf-4a65-af68-8329eceab740/resource/6ddcd912-32a0-43df-9908-63574f8c7e77/download/buildingpermits.csv"
```
for the "building permits" dataset. This produces a CSV file, that is in turn generated on the fly from the database; which in turn is being updated in real time as new permits are issued. Each time you download the dataset you get the complete dump of the records starting in 2006 and up to the current time. (TODO: find out if it is possible to narrow the output by date range)

3. I still want to implement this such that for each of the dataset we want to be monitoring and auto-depositing, there will be a config file entry specifying the following: 
-the location URL, as above; 
-the processing script that will take the raw data, above, and produce one or more output files (note that the script may be a single R script; or a shell script that in turn calls multiple R scripts and other programs... it's just something that can take input and produce output); 
-the names of the expected output file(s); 
- the identifier of the dataset (or dataverse) into which the produced files should be deposited; 
- the API key;
-the "style" of handling these incremental data snapshots (for example - in a new version of the existing dataset, via file replace; in a new version of the existing dataset, via delete and upload new; into a new dataset  in the specified dataverse every time... etc.) 
So basically I want this to be as configurable as possible. 

4. All the software involved, scripts and configuration, will be maintained in its own github project tree (owned and/or maintained by the BARI researchers). The scheduled jobs run on our servers will be self-updating every time they run; thus the researchers have full control of the process and can make changes, configuration and otherwise, by updating the files on github. 

5. I'm assuming that we will want to monitor and update these different datasets at different scheduled intervals. This can be handled by either maintaining its own crontab schedule for each dataset; or running the top-level scheduler job at a fixed, hourly schedule, with each individual dataset config file specifying how often we should check Analyze Boston for updates (Daily/Monthly/Weekly/etc.)
 
6. The sample R scripts supplied by the BARI researchers attempt to do everything - downloading the raw data, processing and uploading into their Dataverse via our API - in R. I've been strongly recommending that we only use R for the actual processing (statistical staff, geocoding, etc.) And offering to script everything else around it as needed. I'm getting some amount of pushback (?) - but we should be able to figure it out. 

7. I maintain that once I got may hands on a complete, working set of R scripts that process the raw data and produce the correct output files, at least for some of the datasets - or even just one dataset, as a proof of concept! - I could wire together a  a working harvest-and-deposit framework in a day or less. 

8. Potential ambiguity alert: note that in the paragraphs above the word "dataset" is used in two distinct meanings: 1) a Dataverse Dataset and 2) a "dataset" as in, a distinct type of statistical data, available from Analyze Boston, as a single CSV file, as described in the paragraph 1., above. For example, the "building parameters" data in the example there is a "dataset".

**Comment by landreev** [comment]
```
From:  de Benedictis-Kessner, Justin <j.debenedictiskessner@northeastern.edu>

I’m attaching a sample script for grabbing, processing, and posting one dataset (though it gets posted as several different aggregations) that we’re going to want to have “streaming” eventually. Unfortunately, it’s a work-in-progress at the moment due to a couple problems with the Dataverse API that I’ve had, though those may be solved now. But I think it might be helpful in thinking through some of the things we’d like to accomplish with this DV feature.
 
Quick breakdown of what these two scripts do
First file (Permits.Syntax.Records):

    Grab raw data from the Analyze Boston data platform via url
    Do some geocoding of it by referencing with crosswalk files and geo shapefiles that we have on our Google Drive
    Add some new variables via our classifications of individual data records
    Outputs a records-level longitudinal file (csv) – which would eventually then update to dataverse via the API (not currently working)

Second file (Permits.Syntax.Ecometrics):

    Creates geographic aggregations of the records-level dataset
    Adds new variables to those aggregations and breaks them into yearly chunks
    Outputs files for each year in several different geographic aggregations
    Updates the corresponding aggregate-level files on our BARI dataverse using the keys from the DV API (currently somewhat-working)

 
If there are additional files I could provide that would be helpful in coming up with this functionality, please let us know! I know these scripts reference other ones (including large geographic shapefiles) but I didn’t want to overwhelm you at the moment. It’s also probably an open question of whether we actually want to be able to update these scripts semi-frequently, so a more sustainable situation might be to have this on Github.
 ```

**Comment by landreev** [comment]
```
From: leonid

Hi Justin (and Nolan),

A few things:

> Unfortunately, it’s a work-in-progress at the moment due to a couple problems with the Dataverse API that I’ve had, though those may be solved now.

I can definitely help with scripting anything that has to do with communicating with the Dataverse API. And I don't think this needs to be implemented in R either. Early on I assumed that we'd be using R only for processing of the raw data. And then I would add some (shell?) code around it, that would do everything else - download the raw data from Analyze Boston, call R to process it, and then upload the resulting output into the appropriate dataset in the BARI dataverse. I suggest that we stick with this model. So as long as I have working R script, with all the dependencies, that I can feed the raw csv and have it output the file that is ready for ingest into Dataverse, I can set up everything else.

I am creating a github project for this. If you already have github accounts, please send me the names, and I'll give you write access to it.

My main question at this point is about the "streaming" aspect of the whole thing - how exactly do we want it to work? - Looking at the code in Permits.Syntax.Records.2018.R, it looks like every time it runs, it processes everything in the raw data file, producing the data that covers "from 2006-09-26 to ... Sys.Date()". And then it creates a brand new dataset, and adds the file to it.

- So, how often do we need to run it? (how often does the city of Boston update the database - is it real time, as new permits are issued... or is it a daily/weekly/monthly data dump?)

- And do we want to keep using this model, that uploads everything into a brand new dataset every time?
Some alternatives could be - upload the file into the same dataset every time, but create a new version of the dataset, replacing the file with the newly generated copy every time. This way the latest/current version of the dataset always contains the most up-to-date copy of the data. But a user can go to the previous versions to look at the history of it (I don't know how useful that would be).
This would also depend on how often this scheduled deposit job will be running; if we do this runs daily, I don't think we want to create a new datasetversion every day - that may not be the best curation style.
And/or we could explore creating incremental chunks of the data. Meaning, for example, we run this deposit job once a month, and every month it outputs just one month worth of incremental data ("permits-boston-April-2018.csv"), which is added as another file to the dataset... (With this permits data specifically, it doesn't look like the entries change at all once issued; but may not be the case with other data they provide?)

We can definitely make it configurable too; using different models of incremental updates for different types of data we harvest from data.boston.gov. 

```

**Comment by landreev** [comment]
```
From: "Phillips, Nolan Edward" <nolanephillips@xxx.edu>



Hi Leonid,


Thanks for all your work on this.  Below are responses to the questions you raised:


For GitHub my account is nolanphillips.


Dataverse API:  Justin and I discussed the pros/cons of using a shell to deposit versus having the API deposit within the R script.  Perhaps there are aspects we are overlooking, but we think it would be better to have the entire process contained within the R script so that we can flexibly update it as needed.  I don't have a strong preference on using a shell or having everything contained within a R script.  Either way, the system will need to be able to link to other files for processing and for some datasets, more than one file is generated by the script.


Streaming aspect:  The datasets are updated at different intervals.  For example, the 311 and building permits data are updated daily while the ACS are annually.  Even for those that are updated daily, we would only want to update the dataverse about every 6 months (but we need to double check with Dan on that).  


Updating:  Replacing the dataset with a new version makes the most sense to us.  For many of the files, we will want to make annual versions as well as add onto the files that cover larger periods of time.  For example, the first 6 months of 2018 would create a new file for 2018, but would also be added to the 5 year file (e.g.; 2016-2020).  Then after the second update of the year, the 2018 file would be replaced by all the data for 2018, and the additional 6 months of data would be added to the 5 year file.


I believe that covers all of the questions in your email.  Please let me know if not or if new ones emerge.

-Nolan & Justin

```

**Comment by landreev** [comment]
The code for the current auto-deposit prototype is on github at https://github.com/IQSS/BARI-autodeposit. The repository is private (at least for now). If anyone who needs access to it still doesn't have it, please let me know. (@nolanphillips is also an admin). As of now, the only existing branch is "develop". 
The whole thing is pretty compact. All the R code needed for the two currently supported processing jobs is checked in. (Including the extra R files from HG-Functions on Google Drive; the idea is that all the R code should be in github). The 2 main scripts, Permits.Syntax.Ecometrics.2018. and Permits.Syntax.Records.2018.R are almost identical to the copies I initially got from you, with very minor modifications. For example, they get the location of the local copy of the data drive from the environment variable BARI_DRIVE, instead of a defined constant; and the code that downloads the initial raw data from Analyze Boston, and the code that deposits the end result into Dataverse have been commented out. (this is all done by the top-level job running scripts now). 
The shell scripts are somewhat messy. Ideally, you should not have to make any changes to that shell scripting - my plan is that you should be able to make any changes to the processing and deposit workflow just by adding more processing code (R or otherwise), and modifying the job configuration. 

The directory conf.d contains the individual job configuration files. The scheduled top level job on our server goes through conf.d, and looks at every config file in there, selects the jobs that are scheduled to be run and tries to execute them. These files should have ".conf" extensions; everything else will be ignored. 

Looking at the conf.d/conf.d/buildingpermits.conf as an example. This job does the stage 1 of the Building Permits processing - downloads the dataset, runs scripts/R/Permits.Syntax.Records.2018.R  on it, and deposits the result  (Permits.Records.Geocoded.%DATESTAMP.csv) into the specified dataset. (In this case: https://demo.dataverse.org/dataset.xhtml?persistentId=doi%3A10.5072%2FFK2%2FQ1RSNG)

The line specifying the data source: 
```
# Data Source Configuration (this is the dynamic data that we are "streaming")
# This can be a remote source (for example, a dataset from Analyze Boston); or a 
# file produced by another job, and already cached on disk here. 
DATA_SOURCE_REMOTE="https://data.boston.gov/dataset/cd1ec3ff-6ebf-4a65-af68-8329eceab740/resource/6ddcd912-32a0-43df-9908-63574f8c7e77/download/buildingpermits.csv ${BARI_DRIVE}/Permits/Data/buildingpermits.csv"
```

The external data dependencies: 
```
# Extra data files dependencies:  
DEPENDENCY_DATA_FILE=gdrive://GeoInfrastructure2017/roads_updated.csv
DEPENDENCY_DATA_FILE=gdrive://GeoInfrastructure2017/sam_wGeos.csv
DEPENDENCY_DATA_FILE=gdrive://GeoInfrastructure2017/LandParcels.2017.csv
DEPENDENCY_DATA_FILE=gdrive://GeoInfrastructure2017/IDConnector.2017.csv
DEPENDENCY_DATA_FILE="gdrive://GeoInfrastructure2017/Tracts_Boston_2010_BARI/Tracts_Boston BARI.sbn"
DEPENDENCY_DATA_FILE="gdrive://GeoInfrastructure2017/Tracts_Boston_2010_BARI/Tracts_Boston BARI.shp"
DEPENDENCY_DATA_FILE="gdrive://GeoInfrastructure2017/Tracts_Boston_2010_BARI/Tracts_Boston BARI.sbx"
... etc. 
```
note that I'm listing every single file - including the individual files for the shapes. I can't think of a better way (?). 

The following section defines the "data processor". Doesn't have to be an R program. Can be any executable - for example, it can be a script that in turns calls other programs and scripts (as long as all of the needed components are checked into the github project). 

```
# DATA PROCESSING SCRIPT: 
DATA_PROCESSOR=./scripts/R/Permits.Syntax.Records.2018.R
```

Expected data output, schedule and the deposit configuration: 

```
# EXPECTED DATA OUTPUT: 
DATA_OUTPUT_PROCESSED=${BARI_DRIVE}/Permits/Data/Permits.Records.Geocoded.csv
# SCHEDULE: 
# This is a crontab-like schedule definiton ("min., hour, dayofmonth, month, dayofweek")
# For example:
# "0 9 1 * *" - monthly, run at 9AM on the 1st of every month; 
# "30 17 * * 1" - weekly, run at 5:30PM every monday. 
# This job is configured to run every day at 9PM:
RUN_SCHEDULE="0 21 * * *"
# DATAVERSE DEPOSIT CONFIGURATION:
DEPOSIT_DATAVERSE="https://demo.dataverse.org/"
DEPOSIT_DATASET_ID=29480
DEPOSIT_API_KEY=2987f179-bc83-44fd-bcc4-ca99e749176b
DEPOSIT_STYLE=UPLOAD_AND_PUBLISH
# NOTIFICATIONS CONFIGURATION
CONTACT_EMAIL=leonid@hmdc.harvard.edu
```

There's definitely more that we should discuss... But that's the idea  - this is a working prototype, and we should experiment with it, and work out something that works for everybody.

**Comment by landreev** [comment]
Some extra bits of status info:
The 1st Building Permits autodeposit job is now scheduled to run every day (at 9pm; this is the schedule line in the job configuration, conf.d/buildingpermits.conf:
```
# This is a crontab-like schedule definiton ("min., hour, dayofmonth, month, dayofweek")
RUN_SCHEDULE="0 21 * * *"
```
The produced csv files get deposited into this dataset:
https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.5072/FK2/Q1RSNG
This is kind of a waste of course, to be producing and depositing these files every day; but this is just a proof of concept. 
Also, if the job runs, but the actual data on the Analyze Boston server hasn't changed since last night, and the produced geocoded csv file is identical to the last one, Dataverse refuses to accept it - because the file is already in the dataset. So it's kind of self-regulating this way. 
Once again, the way it's done, The top level cronjob on the server runs *every hour*. It refreshes the local checkout of the project from github, then goes through the all the job configuration files in conf.d, checks their individual run schedules, and executes the ones that are scheduled to run now.

The second job (the one based around the "Ecometrics" R script) is not scheduled to run as of now. (the "RUN_SCHEDULE" line in the config is left blank). 
Question about this job - it produces so many output files (99 by my count); do all of these need to be deposited? 

There are two "deposit styles" supported as of now (DEPOSIT_STYLE setting in a job config); with one the results are uploaded into an existing, specified dataset. Which creates a new version, which is then published. The other style creates a new dataset, in the dataverse specified in the config.
We will most likely have to add more deposit types. Just need to figure out what they should be. Neither of the above solves the problem of producing ever-growing output files, that are still for the most part the same (except for the added most recent changes). So Dataverse probably does need a concept of a "growing file" - a mutable file that can be modified/added to.

**Comment by landreev** [comment]
@nolanphillips @djbrooke 
I'm trying to put together a single checklist for everything, in one place, that needs to be done/figured in order to wrap up this first stage of the collaboration. For the sake of doing things in manageable increments. There is not much left, really. If you think it'll help to figure it out in another meeting, let's schedule one. 

To rehash, we decided to start with setting up an automated processing and deposit job for the "Building Permits" dataset; using the R code already created by the BARI side. 
The draft implementation is on github, in its own project: https://github.com/IQSS/BARI-autodeposit/tree/develop (no master branch at this point - develop only).
The first R processing job (based on  the R program Permits.Syntax.Records.2018.R) has been running on a regular schedule (every day at 9PM) and depositing the produced output into this dataset: https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.5072/FK2/Q1RSNG (if different from the last successful deposit); 32 files have been deposited since June 22. (At this point I'm going to start trimming the older files, since it's already using too much disk space on the demo server).
Once again, the idea is that if you need to change anything about this process, you'll be doing it by making the changes directly on github; and the automatic scheduler running on our server will detect the changes, as if by magic (on the next hourly run that is). 
For example: 
- If you need to make a fix in the R code, you modify it here: https://github.com/IQSS/BARI-autodeposit/blob/develop/scripts/R/Permits.Syntax.Records.2018.R (and commit the fix back into the develop branch)
- if you want to change the run schedule, you modify the following line: 
```
# This job is configured to run every day at 9PM:
RUN_SCHEDULE="0 21 * * *"
```
in the file https://github.com/IQSS/BARI-autodeposit/blob/develop/conf.d/buildingpermits.conf
etc. 
Outstanding issues:
- Are you ok with this method of operating the deposit jobs?
- Are you ok with the current format (plain text) of the job config file? (I've been thinking of changing it to json, maybe?)
- Does it need more documentation, or was there enough information in the previous comments in this issue?
- Is there anything I'm missing? - is there anything else that you may need, in terms of control of this processing, that this draft implementation doesn't cover? 

The second Building Permits job (based around the R program https://github.com/IQSS/BARI-autodeposit/blob/develop/scripts/R/Permits.Syntax.Ecometrics.2018.R): 
The code works and produces output correctly (Assuming the job is properly scheduled, since it relies on the output that needs to be produced by the previous job). This job however is NOT currently scheduled to run automatically. 
Outstanding issues:
- What should we be doing with the output, how should it be deposited into the Dataverse? - Unlike the first job, this one produces a lot of files (99 total), so it doesn't seem to be practical to be using the same approach - to deposit them all every time the Permits dataset changes in the city database; that will quickly make the dataset unmanageable... Should we create a new dataset each time the job runs (and only run it on demand, with no automated schedule?) Should some output files be skipped?

**Comment by landreev** [comment]
I made a pull request in the "BARI-autodeposit" github project: https://github.com/IQSS/BARI-autodeposit/pull/1

I cannot link it here, but the Dataverse dev team has been given access to the project. So everybody should be able to review PRs and/or contribute the development.

**Comment by matthew-a-dunlap** [comment]
Its not obvious from waffle but I have looked this over and think that someone else should also give it a look. Seems good but I'm not that experienced with scheduled bash jobs.

**Comment by pdurbin** [comment]
@landreev I just looked over the code and made pull request https://github.com/IQSS/BARI-autodeposit/pull/2 to make the docs more discoverable. As long as the code works as described I think it's find (I'm treating it as a black box, to be honest). I'm wondering what the definition of done is for this issue. I assume that after put the code into production with datasets being created in https://demo.dataverse.org and emails going to you, we will follow up with a small change to have the datasets deposited in https://dataverse.harvard.edu and the emails going to someone other than Leonid.

**Comment by kcondon** [comment]
OK, test datasets seem ok on demo, all code is just calling existing apis. Talked about large number of version number as possible future issue.
