### ISSUE TITLE
Guides - Improve Customization + Theme Sections

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#4555]
While working on updating the Harvard Dataverse customization for issue #4546, I was using the [Configuration pg of the Installation Guide](http://guides.dataverse.org/en/4.8.4/installation/config.html) and noticed the organization of the branding and customization information should be improved to better help sysadmin's.

The sections to improve include:

Installation Guide > Configuration
- Root Dataverse Configuration > Customizing the Root Dataverse
- Branding Your Installation

**Comment by mheppler** [comment]
Cleaned up branding and customization info in Configuration pg of Installation Guide.

- Retitled the "Root Dataverse Configuration" section to "Root Dataverse Permissions" since I removed the "customization" information here.
- Moved pertinent info from "Customizing the Root Dataverse" to the "Branding Your Installation" section where all that info belongs.
- Improved organization of information in "Branding Your Installation" section after the addition of information about the dataverse theme and link to "Dataverse Management" pg of User Guide.

**Comment by mheppler** [comment]
Built the Sphinx guides locally and confirmed the formatting looked kosher, as well as built without errors or warnings. Creating a pull request and passing to Code Review.

**Comment by pdurbin** [comment]
I just reviewed pull request #4556 and left these comments:

The pull request is fine but at some point we should consider the user experience of someone who is setting up Dataverse for the first time. There's a lot of optional configuration that should be presented in a more clear manner to get an installation off on the right foot. I left a comment about this:

I'm fine with how the title of this section is not called "Root Dataverse Permissions" but I'm afraid that it reads as a merciless wall of text, starting out with lots of detail on the plumbing rather than stating clearly why the reader should care about any of this. This section is probably the place where we should help the person installing Dataverse avoid several pitfalls. Here are the pain points an solutions:

- I just installed Dataverse and none of my users can do anything. 
  - Publish the root dataverse and configure permissions in order for non-superusers to create dataverses or datasets. See #4515 for an example of this confusion.
- I've been using Dataverse for a little while and I'm not happy with how things are organized.
  - API endpoints to move datasets and dataverses around are being developed. Meanwhile, before you allow lots of dataverses and datasets to be created, you should about what sort of organizational hierarchy of dataverses you want under the root dataverse and adjust the permissions to achieve that goal.
- It's not obvious to me that metadata fields need to be configured.
  - Give your local metadata experts the "Admin" role on various dataverses and have them configure metadata fields. Consider using templates. Notice that you can benefit from facets if you configure them.

There are probably more pain points but these are the ones that come immediately to mind.

**Comment by pameyer** [comment]
@pdurbin "Why don't my datasets show up in google?" seems like a question that comes up relatively commonly (but completely out of scope for this issue).

**Comment by djbrooke** [comment]
If this is incrementally better and the information is correct, let's move it along without further changes.

**Comment by pdurbin** [comment]
@djbrooke ok, I moved it to QA.
