### ISSUE TITLE
Contact Us Email: Set the reply to address to be from the user, from address from dataverse. Otherwise email blocked.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4580]
Currently the email sent from the contact icons/ popup sets the from address to be the email address of the user account sending the email. It is my understanding this is bad practice and would result in the email being blocked by many/default email server configs. Instead, set the reply to field to be from the user and the from address from the dataverse app.

**Comment by pdurbin** [comment]
@kcondon please see also https://help.hmdc.harvard.edu/Ticket/Display.html?id=260778

**Comment by kcondon** [comment]
Phil, this was discussed in standup (you were out) and I was only recording what was discussed there.

**Comment by pdurbin** [comment]
@qqmyers has reported that Contact and Support emails aren't going through after switching to Amazon Simple Email Service (Amazon SES) and he volunteered to do a little investigation (thanks!) so I'm assigning this issue to him.

**Comment by mheppler** [comment]
As part of the work done in for the issue ** As a researcher, I want to know what dataset/dataverse a contact email is referring to so that I can follow up #1916 **, changes were made to the message text in the email template for the Support contact form.

```
From: {contactForm.email}

{systemSettings.supportEmail.brand},

The following message was sent from {contactForm.email}.

---

{contactForm.message}

---

Message sent from Support contact form.
```

In addition to resolving the `from` and `reply-to` we should consider improving the email template to reflect any changes. Also, review why the "From: " label and user email was added to the message text by @scolapasta in commit 6678f4491a846ea3373cb247fcffba12d4f665ec from Jul 16, 2014.

Lastly, make sure to consider various use cases for the system support email from various installations, as our RT system changes how emails are received in the inbox of our support team, compared to system support emails that go directly to an inbox and not through a tracking system.

**Comment by qqmyers** [comment]
I've verified that sending all emails from the systemAddress with a reply-to the sending user's email works in that the email is no longer blocked on AWS with SES and hitting the reply button in a mail client creates a mail to the sender. 

The one side effect is that mail clients show the from address, so there is, without additional changes, no way to see that the email is from the sender. I did a quick test to change our default system email personal name ('QDR') to 'QDR on behalf of <x>' which shows OK in my client. One could also just reply on including the sender's email in the body of the mail itself.

In terms of the choice between this approach and, for example, sending from the system address and cc'ing the sender (reply-to not set so there aren't separate from and reply-to addresses, but recipients would have to know to reply all to not just send back to the system): As I read more, with security now focused on matching the from address with allowed addresses from a given host, there doesn't seem to be much concern about from and reply-to not matching as an indicator of spam and its use seems widespread. It also seems less confusing for users as long as the from name (discussed above) and/or message body note that the system is forwarding on behalf of the sender. Both approaches should work, but I'd expect many more replies mistakenly sent to the system with the second approach, so I'm inclined to suggest that we go ahead with the first. (At QDR, we thought the potential for QDR to stay in the loop on emails to contact could be a benefit. If that's desired, I think the first approach could be modified to have a system or user controlled option to cc the system (or other email) - it's not limited to being available only with the second approach.)

I did my testing off 4.8.6, but, in looking at the changes for #1916, I see they all call the MailServiceBean methods, so the changes are largely orthogonal. The change here does switch the from field seen in the user's mail client from the sender's address to the system one (or the ' on behalf of ' mod suggested above), which could be something that the new contact form templates might be updated  to explain, or to provide guidance that reply works to reply to the sender.  Beyond that, in quickly looking over the updated mail templates, I don't see anything that isn't applicable because of the change here.

W.r.t. the 2014 change, it looks to me like it was switching to sending from the system if the sender's address was invalid. Given that the contact form now appears to require a valid email address when that field is shown (for anonymous users), I don't know if there is a way to submit an invalid address that would trigger this code. It is straight-forward to work around here (always set the from address to system and only set reply to if the from address is valid), but if the new mail templates already include the from address (even if its not a valid one), then the line that adds a 'From <invalid sender address":' wrapper to the message could be deleted (technically that's related to #1916 rather than this issue, but it's in the MailServiceBean class being modified here).

One more minor note - in MailServiceBean, there are two sendMail methods (three but one of those just calls another). For now, I've modified both, but I don't see any use of the first one, which includes the 'host' as a first parameter. If its not used, perhaps it could be deprecated/deleted?

**Comment by pdurbin** [comment]
@qqmyers I just left a review on pull request #4600 with some comments. Thanks for the pull request. As I said there, I think I may need to think about all this a bit more but this seems like good progress. "no longer blocked on AWS with SES" is great to hear. Yes, we should reduce the number of these "sendMail" methods and delete some if we can!

**Comment by pdurbin** [comment]
@qqmyers oh, one more thing is that we just today merged pull request #4571 for #1916 so before we pass this issue to QA, we'd want to merge the latest from the "develop" branch into your branch. Sometimes contributors give maintainers access to push to their branches and if this is the case, I can merge the latest for you, if you want.

**Comment by pdurbin** [comment]
@qqmyers thanks for making the changes I suggested. I spoke with @djbrooke about this issue this morning and we decided to go ahead and move it to QA.

In parallel I went ahead and just deployed the latest code in the pull request (d25e354) to https://dev1.dataverse.org so @mheppler and I can play around with it a bit.

**Comment by kcondon** [comment]
Basic from/reply to works fine. RT system behaves well. 
I did find gmail does not seem to honor reply to but instead sends it back to the from address. Will test some more.

**Comment by qqmyers** [comment]
Hmm - my umich gmail account put a mail from our server to junk/spam, but  mail.google.com replies to the reply-to address for it...

**Comment by kcondon** [comment]
merged and thanks again.
