### ISSUE TITLE
MojoFailureException: CSVFileReaderTest.testVariableUNFs test failing

### ISSUE THREAD

**Issue by Thalia-Uranga** [IQSS/dataverse#4584]
Hello everyone, at the moment of running the project of dataverse send me a message of "BUILD FAILURE" and a link of error of MAVEN. Someone knows how to solve it.

Thank you very much to all.
![captura de pantalla 2018-04-13 11 06 53](https://user-images.githubusercontent.com/31660882/38745802-43e87494-3f0b-11e8-9af6-8472b416070a.png)

**Comment by pdurbin** [comment]
@Thalia25 thanks for opening this issue and it's been nice chatting with you at http://irclog.iq.harvard.edu/dataverse/2018-04-13

`CSVFileReaderTest.testVariableUNFs` was also failing for @domingoscisci who opened #4482
after discussion at https://groups.google.com/d/msg/dataverse-community/haxkesa5Jic/dCOPI3CPAwAJ and I thought pull request #4483 by @pameyer fixed it.

The first question I have is, which commit are you on? You can find this by typing `git log`. Thanks!

**Comment by pameyer** [comment]
#4482 was only fixed in docker-aio; but the same fix (run tests in en_US.UTF-8) should work in other cases.

I suspect the idea approach would be to make UNF calculation $LANG independent (in case someone installs dataverse on a server with a non-english character set?); but I don't know enough about UNF to know one way or the other.
