### ISSUE TITLE
Internationalization : Move English strings from xhtml and java to bundle.properties

### ISSUE THREAD

**Issue by JayanthyChengan** [IQSS/dataverse#4634]
Find and move all the english strings from xhtml files related to user interface to bundle. properties. This will centralize the words and make it easier to translate into other languages going forward.

**Comment by pdurbin** [comment]
@JayanthyChengan thanks for creating pull request #4643! I looked it over and move it to QA at https://waffle.io/IQSS/dataverse

Hopefully, by looking at the "diff" it's easier enough to figure out what to test but if you feel like adding a list here, I'm sure it would be appreciated.

**Comment by mheppler** [comment]
Approving for QA to merge. Reviewed the UI on the dvn-build test server and confirmed all the moving pieces looked good. Confirmed via ssh that the latest and greatest `Bundle.properties` was there, serving the text.

As I commented in the PR #4643 there is more bundle text additions to be made.

```
/src/main/webapp/dataset-versions.xhtml [Line 27, 42] -- javascript, display:none
/src/main/webapp/dataset.xhtml [Line 471] -- display:none
/src/main/webapp/dataverse_header.xhtml [Line 20] -- toggle nav
/src/main/webapp/dataverse_template.xhtml [Line 56] -- default body
/src/main/webapp/dataverseuser.xhtml [Line 533] -- Password/New Password label attribute

/src/main/webapp/editFilesFragment.xhtml [Lines 402-542] -- Select Language Encoding...

/src/main/webapp/editdatafiles.xhtml [Line 70] -- KB
/src/main/webapp/file-versions.xhtml [Line 27, 41] -- javascript, display:none

/src/main/webapp/harvestclients.xhtml [Line 78] -- Filter
/src/main/webapp/harvestsets.xhtml [Line 104] -- Filter

/src/main/webapp/loginpage.xhtml [Line 162, 197] -- shib:no javascript, ORCID
/src/main/webapp/permissions-manage-files.xhtml [Line 53, 99] -- requests, users/groups
/src/main/webapp/roles-edit.xhtml [Line 74] -- cancel

/src/main/webapp/superuser.xhtml [Line 23, 26] -- index all, check status

/src/main/webapp/resources/js/mydata.js [Line 318-322] -- View Next... Results...
```
That list has been updated with two additional finds from my final QA review. It includes text found in `mydata.js` which won't be a straight forward copy+paste over the bundle because you can not deliver text from the bundle to a javascript file. It will require refactoring the javascript code in order to pass the dynamic text from the bundle as a variable to the function in the javascript file.
