### ISSUE TITLE
SchemaDotOrgExporter.java doesn't close jsonReader 

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#4669]
Pull request forthcoming.

**Comment by pdurbin** [comment]
Pull request #4673 looks good to me. Standard `try-with-resources` syntax. Should work. Moved to QA at https://waffle.io/IQSS/dataverse

**Comment by kcondon** [comment]
How to test?

**Comment by donsizemore** [comment]
Kevin, we have a 4.8.6 warfile which includes the #4669 and #4653 patches if you'd like it. I hadn't had enough coffee this morning, stopped glassfish to apply security patches to a test box, and wiped out our local test here (well, reset it really).

To trigger this you might set up a 4.8.6 Dataverse configured as a harvesting server, and look for an accumulation of export_* file descriptors beneath /proc/gfish pid/fd (our production Dataverse is hovering around 11,000). Downloading metadata might test just as well?

We've been harvested pretty heavily / near constantly by a group in Europe, so I thought harvesting might make a convenient test.

**Comment by pameyer** [comment]
The same `ls -l1 /proc/$glassfish_pid/fd | grep schema` (modifying the grep as needed) approach used for https://github.com/IQSS/dataverse/pull/4654 might be helpful here too.

**Comment by kcondon** [comment]
Thanks guys. I guess what I was asking is two fold:
1. How to check whether the close is helping
2. What specific functionality is affected by the change so I can regression test it.

For the first ticket it dealt with a straight export so I did an reexportall and used Pete's open file descriptor count and that answered q 1. Running export all and spot checking a couple export files, checking the completion message in the logs (failed due to out of mem btw) and checking db export time showed q 2. was basically still working (mem issue predated change).

So, for this one, the fd already seem to be controlled for export all and I'm not 100% sure what the functionality is except to likely generate the exported schema.org format. 

I don't know how harvesting comes into the picture for the export functionality except for when generating a set, which is similar to running export all but for a selected batch of datasets, and uses a slightly different format so good to test also. I'll try it but not sure I would see any additional improvement in count since the first one already controlled things. I'll at least confirm functionality still works.

@donsizemore  Would you mind refreshing this branch from /develop since the db schema has changed due to file doi merge? I could borrow your war file but like to build myself to make sure I know it is reproduceable.

Thanks and sorry it has taken so long but have had some other issues to deal with.

**Comment by donsizemore** [comment]
@kcondon merged! so, the reason i suggested harvesting is that running our patched warfile on a test box, i see dataverse opening (and holding open) an export_ FD equal to the number of records harvested. they haven't been released or garbage collected in the past 24 hours, i can harvest some more sets from this server or let things marinate over the weekend.

our production dataverse is holding open just under 11,000 FDs, but that number stopped climbing when at Jon's suggestion I disabled our harvesting server. in between the spring semester and summer session we haven't seen much active publishing, so... Akio is tracing code and i'm collecting numbers.

and thank you for your help!

**Comment by kcondon** [comment]
@donsizemore  Thanks! Will get right on it. I get it: harvesting server getting clobbered and accumulating fds.

**Comment by donsizemore** [comment]
@kcondon well, that's my unscientific intuition, nothing more. I appreciate your looking into it, and more importantly enjoy your weekend!

**Comment by kcondon** [comment]
@donsizemore  Thanks, you as well! We (Leonid) might have some further insight into export behavior and harvesting but looking at it now. I did notice a new export schema.org fd on dataset page load each time, even on your new branch, and inquired about this. Seems maybe a read descriptor rather than write and maybe something like that happens with harvest.
