### ISSUE TITLE
API test suite failing after "file DOIs" branch was merged

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#4675]
Pull request #4350 about file DOIs was just merged so I kicked off the API test suite on the phoenix server as described at http://guides.dataverse.org/en/4.8.6/developers/testing.html#the-phoenix-server

This is as of commit 8c00625

Unfortunately, there was a failure at the second step where the war file is deployed and we ensure that we can download a file that we have published. Below is a screenshot from https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-deploy-develop/192/console

![screen shot 2018-05-15 at 3 49 01 pm](https://user-images.githubusercontent.com/21006/40079957-86ec3018-5857-11e8-9ba4-7d17d91fd45d.png)

We expect a 200 response but we get a 404. Because this failed, the next Jenkins job of actually running the API test suite wasn't triggered. We should investigate the error above and make sure the API test suite can be run again and passes.

**Comment by pdurbin** [comment]
Ah, hopefully this is only the fact that I need to update the Solr schema. In server.log I'm seeing this:

`Caused by: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://localhost:8983/solr/collection1: ERROR: [doc=datafile_12_draft] unknown field 'filePersistentId'`

```
[2018-05-15T15:44:48.875-0400] [glassfish 4.1] [SEVERE] [] [edu.harvard.iq.dataverse.datasetutility.AddReplaceFileHelper] [tid: _ThreadID=27 _ThreadName=http-listener-1(1)] [timeMillis: 1526413488875] [levelValue: 1000] [[
  Failed to add file to dataset.]]

[2018-05-15T15:44:48.875-0400] [glassfish 4.1] [SEVERE] [] [edu.harvard.iq.dataverse.datasetutility.AddReplaceFileHelper] [tid: _ThreadID=27 _ThreadName=http-listener-1(1)] [timeMillis: 1526413488875] [levelValue: 1000] [[
  Command edu.harvard.iq.dataverse.engine.command.impl.UpdateDatasetCommand@472d2b04 failed: null]]
```

**Comment by pameyer** [comment]
`develop-8c00625`

`Tests run: 72, Failures: 1, Errors: 0, Skipped: 0`

`Failed tests:   testCreateAndDeleteDatasetInRoot(edu.harvard.iq.dataverse.api.SwordIT)`

**Comment by pdurbin** [comment]
> PSQLException: ERROR: function concat(character varying, unknown, character varying, character varying, character varying) does not exist Hint: No function matches the given name and argument types. You might need to add explicit type casts.

Our working theory is that I'm seeing this failure on the phoenix server because it's running CentOS 6 and the "postgresql-server" RPM from yum is version 8.4.  Since the `concat` function wasn't added until 9.1 ( https://www.postgresql.org/docs/9.1/static/release-9-1.html ) @sekmiller is going to take a swing at rewriting the SQL statement in question.

@sekmiller is going to

**Comment by pdurbin** [comment]
I just deployed pull request #4677 to a server running postgres 8.4 (dev1) and now I can upload a file. I moved this to QA at https://waffle.io/IQSS/dataverse

Please note that after this is merged we will still need to make sure that the API test suite runs. The pull request above is a prerequisite for even running the test suite on the phoenix server, which also runs postgres 8.4.

As I wrote at http://guides.dataverse.org/en/4.8.6/developers/testing.html#the-phoenix-server ...

"A server at http://phoenix.dataverse.org has been set up to test the latest code from the develop branch. Testing is done using chained builds of Jenkins jobs:

-    A war file is built from the latest code in develop: https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-build-develop/
-    The resulting war file is depoyed to the Phoenix server: https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-deploy-develop/
-    REST Assured Tests are run across the wire from the Jenkins server to the Phoenix server: https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/ "

... and the goal of the pull request above is to get the second job (deployment) to complete so that the API test suite can be run.

**Comment by pdurbin** [comment]
> Failed tests: testCreateAndDeleteDatasetInRoot(edu.harvard.iq.dataverse.api.SwordIT)

On my laptop running 5f2fbed I can reproduce the failure above that @pameyer reported.

This is the assertion that's failing (lines 464-467):

```
Response rootDataverseContents = UtilIT.showDataverseContents(rootDataverseAlias, apiTokenContributor);
rootDataverseContents.prettyPrint();
logger.info("We expect to find \"" + identifier + "\" from the persistent ID to be present.");
assertTrue(rootDataverseContents.body().asString().contains(identifier));
```

Here's the error shown from the `rootDataverseContents.prettyPrint()` method above:

```
{
    "status": "ERROR",
    "message": "Command edu.harvard.iq.dataverse.engine.command.impl.ListDataverseContentCommand@79a663bb failed: null"
}
```

**Comment by pdurbin** [comment]
In 4622e0a I fixed the failing assertion in SwordIT but I don't feel great about it. Previously we were able to use a contributor's API token with the "contents" API but now a `PermissionException` gets thrown and ignored. The quick fix is to use a superuser API token instead. If anyone knows why the behavior of the "contents" API changed, please speak up.

I'm moved this issue to code review.

**Comment by scolapasta** [comment]
@pdurbin I don't see a change in the way permissions are handled in ListDataverseContentsCommand. You do need the ability to view an unpublished dataverse if the dataverse you are trying to view is unpublished. Is it possible that the scenario in the test changed and the dataverse is, in fact, unpublished?

**Comment by scolapasta** [comment]
The other note is that the command does call getDataset and getDataverse for each dvobject it includes and purposefully ignores permissionExceptions that get thrown for those objects. This is how it checks to see if you have permission and only returns those for which you do. It has always worked this way, as far as I know.

**Comment by scolapasta** [comment]
So, from what I can tell the ListDataverseContentsCommand hasn't changed since 2015:
https://github.com/IQSS/dataverse/commits/develop/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/ListDataverseContentCommand.java

It calls GetDatasetCommand and GetDataverseCommand which also haven't changed since 2015:
https://github.com/IQSS/dataverse/commits/develop/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/GetDataverseCommand.java
https://github.com/IQSS/dataverse/commits/develop/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/GetDatasetCommand.java

and those are both just simple wrappers around the dvobjects in order to check permissions.

That's why I was trying to figuring out if maybe something in the test had changed.

I agree that changing the test to use a superuser token is not the solution we want. 

We did make a change to handle CommandExceptions in embedded commands in the engine (in the file doi branch). I wonder if somehow that is affecting it...

**Comment by pdurbin** [comment]
Right, it looks like 7eec754 is the main commit where we changed the command engine.

**Comment by scolapasta** [comment]
Have confirmed that the cause of the failure is due to those changes - and am getting a better understanding of why. Am working with @sekmiller to find a fix, even if it's just a temporary one for now, and later we work on making the engine work more smoothly for these kinds of cases.

(the root cause is we added code to make sure if something in a nested command fails, that the transaction fails. Generally that is what we want, since usually commands are about editing. In this case, however, we were using commands to check permissions and wanting to ignore the permissions exceptions).

**Comment by pdurbin** [comment]
I just wanted to mention that the API test suite on the "develop" branch is passing now. Phew.
