### ISSUE TITLE
published dataset thumbnail shows UNpublished image

### ISSUE THREAD

**Issue by shlake** [IQSS/dataverse#4689]
Tested all of this on Demo dataverse:

https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.5072/FK2/KW6RPL

The thumbnail image on this dataset is from a file in a "draft" version of the dataset. It is not yet published. 

The file is not in the published version, so it should not be a thumbnail (publicly displayed) on the published version.

**Comment by pdurbin** [comment]
@shlake bummer, I see what you mean:

![screen shot 2018-05-17 at 4 51 02 pm](https://user-images.githubusercontent.com/21006/40203164-63b3be12-59f2-11e8-96af-34c509213bf2.png)

Thanks for bringing this to our attention!

**Comment by landreev** [comment]
@shlake
Hi Sherry,
I'm already working on this, and it doesn't seem to be super difficult to fix. But, how much of a real problem is this really? - Considering that there's a very easy workaround for the author/owner of the dataset - to select a different image to be the thumbnail (if available), or to choose the "no thumbnail for this dataset" setting?

**Comment by landreev** [comment]
Implemented the fix as discussed this morning - unpublished (draft-only) image files are excluded when we try to auto-select the thumbnail for the dataset.

**Comment by landreev** [comment]
(moved into code review)

**Comment by pdurbin** [comment]
I just approved pull request #4705 and moved it to QA.
