### ISSUE TITLE
Code Cleanup - better handling of external links

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4717]
Splitting out from https://github.com/IQSS/dataverse/issues/3337#issuecomment-391737405 :

Short version - it would probably be a good idea to add `rel="noopener"` to external links, in addition to `target="blank"`.

Another thought that's almost certainly out of scope for this issue, but related to the discussion of consistency with handling external links, would be adding rel="noopener" to external links (recommended by lighthouse for performance / security - https://developers.google.com/web/tools/lighthouse/audits/noopener).

**Comment by mheppler** [comment]
As @pdurbin noted in his PR comment, we have started to address this issue in _adds rel="noopener" attribute to the link formatting in citation.tsv_ #6249. I will be diligent when reviewing PR that include UI changes which will provide an opportunity to add these `rel="noopener"` attribures.

I will start a checklist of the places it has been address here, so that if/when this issue gets picked up, we know where this is already done.

- [x] citation.tsv (#6249)
