### ISSUE TITLE
Provenance: Error on creating dataset and when publishing if add prov file to tabular file on upload.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4731]
Found 2 issues when uploading a provenance file to a tabular data file on upload:
1. On dataset creation, add a tabular data file and an associated provenance file, save. See failure message relating to provenance file, notice prov file not saved.
2. On creation of a draft from a published dataset, add a tabular data file and an associated prov file, save, publish, nothing happens in UI (not published) but log shows optimistic lock error. Happens when creating draft by uploading tabular file & prov and to existing draft if upload tab file & prov and set file category tag.

I do not yet know whether the size of the tabular data file makes a difference (affects timing).  I have been testing with tiny tabular files.

**Comment by matthew-a-dunlap** [comment]
Thanks for the info on these @kcondon ! I seem to be unable to reproduce either on my dev machine tho

1. Creating of the initial draft goes through correctly without error, and the prov file remains in place. Worked with both prov file and prov freeform. One of the times I noticed my ability to edit was greyed out but I'm assuming that was due to ingest, it went away on a page refresh.

2. I took a blank published dataset and added one of the provided csvs and a prov file, saved and published. No errors and the prov file still remains. I tried the same thing but also adding freeform prov and a tag and it still seemed to save and publish ok.

Maybe there is some other step I am missing that is getting things in a weird state. Its also possible something else was having issues with locks and prov was just the next thing to stumble across them?

**Comment by kcondon** [comment]
It is possible it is a timing issue and so the conditions are different on your machine. Maybe we can sync up on Monday to reproduce?

**Comment by matthew-a-dunlap** [comment]
@kcondon Sounds good! Have a good weekend

**Comment by matthew-a-dunlap** [comment]
After a fair bit of discussion and research:

We have been unable to reproduce #1 with a fair number of tests, and is likely a weird environment issue. #2 seems to be more related to uploads of small tabular files and has been captured in the story above.
