### ISSUE TITLE
Open "Explore" applications in a new tab so I can get back to Dataverse

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#4742]
When exploring a tabular dataset, such as https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/DBW86T, the application opens in the same window as Dataverse, forcing the use of the "back" button in the browser to return to Dataverse.

The expected behavior for Data Explore is to open in a new window, as on Scholar's Portal. For an example, see:
https://dataverse.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5683/SP/MFIWHE

**Comment by pdurbin** [comment]
Yes. Thanks for opening this bug @TaniaSchlatter 

I'd like to point out that when there is no popup required, such as with https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/TJCLKP , Data Explorer opens in a new tab, as desired.

So the difference is whether or not a popup (to agree with Terms Of Use, for example) is required. Note that the Scholars Portal dataset mentioned above also does not require a popup.

Back at https://github.com/IQSS/dataverse/issues/3657#issuecomment-359862931 I described this as a known issue with these words:

"When you launch an external tool from a popup the tool will take over the browser window rather than opening in a new tab. When there is no popup, the tool launches in a new tab, which is the desired behavior. This bug exists in production for TwoRavens and has been discussed with Gustavo, Steve, and Mike but we don't have a fix. The inconsistency is unfortunate."

But I didn't create an issue to track this so thank you very much for creating it!

I'd also like to note that the current version of Dataverse is 4.8.6 for both examples above from Harvard Dataverse and Scholars Portal.

**Comment by scolapasta** [comment]
This issue already existed at #1564. As @pdurbin the issue is when there is a popup. 

@TaniaSchlatter I'll let you decide which issue you'd prefer to keep open and which to close  (or correct me if I'm wrong, and this is a different issue)

**Comment by mheppler** [comment]
Ah, when @TaniaSchlatter mentioned this issue to me, I did not think of the terms/guestbook popup issue. This has been a [known issue](https://github.com/IQSS/dataverse/issues/1564) for a while. In a [comment of mine](https://github.com/IQSS/dataverse/issues/1564#issuecomment-190803119), I suggested a possible solution. Not sure if it was investigated or not.

>Found another reference on [StackOverflow](http://stackoverflow.com/questions/14584187/how-to-use-target-blank-only-if-validation-successfully) suggesting to use PrimeFace's RequestContext#execute() with window.open().

**Comment by TaniaSchlatter** [comment]
Thanks for the comments @scolapasta, @mheppler and @pdurbin. I'm closing in favor of #1564, noting that I see this as a bug and not a feature.
