### ISSUE TITLE
R 3.5 requires corresponding R-apache module

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#4753]
A placeholder for me to rebuild against 3.5 and hopefully offer an RPM.

**Comment by pdurbin** [comment]
I moved this issue from QA to Development at https://waffle.io/IQSS/dataverse because @donsizemore wants to work on it some more. See http://irclog.iq.harvard.edu/dataverse/2018-06-19

**Comment by donsizemore** [comment]
update: on our production Rserver I've excluded R-*, libRmath* and openblas* from the EPEL repo yum conf file to lock us at 3.4. Akio continues to experiment with file format conversion (tab->Rdata) and suspects R version incompatibility may cause some of the discrepancies he's finding.

**Comment by djbrooke** [comment]
Hey @donsizemore - we'll be cutting a release once the fix for #4783 is in. Do you have a fix for this that you'd like us to try and include? Thanks!

**Comment by donsizemore** [comment]
@djbrooke so far my fix has been to lock in at 3.4. Let me get with Akio and see if we have anything further to report, but you might just ignore this for the release.

**Comment by pdurbin** [comment]
At standup this morning there was a suggestion that maybe the Dataverse guides could simply be updated to say that a certain version of R is required, pinning the version basically. It turns out that the guides already **strongly** recommend a specific, even older version:

<img width="663" alt="screen shot 2018-06-27 at 8 35 27 pm" src="https://user-images.githubusercontent.com/21006/42006774-e3695df2-7a49-11e8-9ada-14f99de3cea5.png">

That's from http://guides.dataverse.org/en/4.9/installation/r-rapache-tworavens.html

I guess I'm wondering if what's written there is no longer accurate in terms of which version of R comes from EPEL but I don't know.

**Comment by donsizemore** [comment]
@pdurbin 3.5 is in EPEL 7 as of this month — I vote to lock in at 3.4 for the short term.

**Comment by pdurbin** [comment]
@donsizemore that's fine. Do you want to make a new pull request to update that page in the installation guide?

**Comment by pdurbin** [comment]
Some discussion in IRC this morning if anyone's interested: http://irclog.iq.harvard.edu/dataverse/2018-06-28

**Comment by pdurbin** [comment]
@donsizemore and I have been discussing how he reworked pull request #4754 in IRC this morning: http://irclog.iq.harvard.edu/dataverse/2018-07-09

To summarize, he has updated the documentation to offer a variety of options depending on one's interest in upgrading to R 3.5. Moving to QA.

**Comment by landreev** [comment]
@kcondon IMO, we should just go ahead and merge this PR as is. Because Don's changes appear to be working as advertised - you can follow them to configure Dataverse/TwoRavens combo to work with R 3.5,*when running CentOS/RedHat 7*. 
Tinkering with our test servers that are still running RH6 however, I discovered building all the packages that TwoRavens needs, under R 3.5, is still problematic. To the point that it doesn't look like it's really worth the effort. 
I feel like we should simply say that if you insist on running RH6, you must stick with R 3.4 (for which we have an installation setup that's more or less guaranteed to work). 

(this should be part of our general move in the direction of discontinuing support for RH6 and its derivatives). 

Another problem with the current R installation instructions is that it bundles everything needed both for TwoRavens, and Rserve (used for ingesting R files, and conversions to R), as a single piece. The latter is much easier to install; and now that TwoRavens is even more of an optional component (we are not even running it ourselves; and many other installations will likely follow suit and replace it with the DataExplorer, at least for the foreseeable future), we should really separate these two things. So I will open a new issue for that.

**Comment by donsizemore** [comment]
agree to prefer R-3.4. Jon ran into missing variable metadata in Data Explorer on Friday, and happened to be hitting our one R-3.5 service. I pointed that Dataverse instance at an older, 3.4 R server: everything was good.

**Comment by landreev** [comment]
@donsizemore I was about to ask you to confirm that everything was actually working for you properly, specifically, TwoRavens, once you have upgraded to R 3.5... The fact that you saw some problems with Data Explorer (its needs are much simpler than those of TwoRavens) is a bit alarming. 

Did you try and rebuild all the 3rd party R packages? (this is the r-setup.sh step in our installation guide). On my boxes, the rpm upgrade of R 3.4 to R 3.5 preserved all the previously installed R libraries (in /usr/lib64/R/library) - but they stopped working for the most part. For example, package Rserve could still be loaded, and the Rserve daemon could still be started - but incoming Rserve connections from Dataverses were failing with segfaults in some linked libraries, almost immediately past the authentication and login. So I had to erase and rebuild it.

**Comment by donsizemore** [comment]
@landreev post RPM upgrade, I did try to rebuild all packages in place (though I didn't explicitly run the r-setup.sh script, just kept calling update.packages() as root in R. I also tried a clean 3.5 install. Odum is sticking with 3.4 until we can get a better handle on what's going on.

**Comment by landreev** [comment]
OK, so it sounds like we are not merging this PR for now. 

BTW, did you downgrade to R 3.4, or did you simply have a 3.4 installation preserved on some server(s)? 
I seem to have the older, 3.4 epel rpms preserved. But they likely require extra dependencies that are no longer available on epel. (though Harvard may have a local mirror of an older epel snapshot, that was providing 3.4)

**Comment by donsizemore** [comment]
@landreev We happened to have 3.4 servers preserved. Probably the safest thing to recommend is that new instances compile 3.4 from source (only my opinion, others may have a better experience with 3.5).

**Comment by landreev** [comment]
OK. 
I've just taken another shot at rebuilding all the required libraries explicitly, under R 3.5, and was more successful this time around. Will report on whether TwoRavens and/or Data Explorer are working properly...

**Comment by landreev** [comment]
@donsizemore Predictably, I can't install your rapache-1.2.9_R-3.5 rpm on a RH6 system. Could you share the spec file you used to build it? - I'd like to try and build a RH6 version... Thanks!

**Comment by donsizemore** [comment]
[rapache.spec.txt](https://github.com/IQSS/dataverse/files/2202657/rapache.spec.txt)
@landreev attached!

**Comment by landreev** [comment]
Thanks Don!
Was able to build the rpm, installed it on one of my RH6 boxes;
will try to retest the whole TwoRavens/Data Explore mess, will report on the results.

**Comment by landreev** [comment]
It looks like I was able to get TwoRavens to work, under R 3.5 and RH6. I will try and test data explorer now. 
@donsizemore , when you mentioned the problem with missing variable metadata, how severe was that? Just some pieces of the metadata missing, for specific files... vs. no tabular metadata shown for any files?

**Comment by landreev** [comment]
Data Explorer appears to be working too. 
The test system is https://dvn-build.hmdc.harvard.edu

**Comment by landreev** [comment]
Going to try it on an RH7 system next.

**Comment by landreev** [comment]
@donsizemore 
I looked at the file in the dataset you created (https://dvn-build.hmdc.harvard.edu/dataset.xhtml?persistentId=doi%3A10.5072%2FFK2%2F1QHHUT) - and to me both the Data Explorer and TwoRavens appear to be working properly. (definitely no blank pages; though I haven't closely inspected every variable). 
Could you please take another look and confirm? 

(please let me know via email if you still can't add comments here...)

**Comment by donsizemore** [comment]
@landreev you are correct! and yes, this morning they're both responding for me. yesterday evening i only got a blank page from Data Explorer. so... even though we tested file ingest against a squeaky-clean 3.5 R server, for production, would we want to nuke all .prep files, and/or other filetypes per dataset?

**Comment by landreev** [comment]
No, I don't think you need to nuke either your .prep files, or your saved .RData files; they should really be exactly the same, whether produced by R 3.4 or 3.5. 

When you say "this morning they're both responding for me", you mean both Data Explorer and TwoRavens, *on dvn-build.hmdc*, correct? (NOT both my 3.5 server and yours?) - I'm assuming your 3.5 instance is still not working as it should... 

I don't have an RH7 or CentOS7 box ready to try this on right now. But on dvn-build, the key to getting everything to work was rebuilding all the required third party R libraries from scratch. Not just building the required packages, but building the specific, known-to-work-together versions of them (i.e. re-running the r-setup.sh script from scratch). 
I believe the safest/surest way to go about it would be to 1) uninstall R 3.5 2) delete everything left in /usr/lib64/R/library 3) reinstall R 3.5 and 4) run the r-setup.sh as described in the guide. 
On dvn-build I had to install these extra rpms in order to get them all built (this is something that was not needed to build them under R 3.4, apparently): R-Rcpp, R-Rcpp-devel (from epel) and openssl-devel. But your mileage may wary(?)

r-setup.sh will exit if it can't build a library; then you can inspect the build .LOG file - and more often than not you can decipher the error messages there and figure out what it needs in order to complete the build...

**Comment by donsizemore** [comment]
@landreev want me to stand up a box here and open a firewall punch for a given harvard ipv4? i'm happy to do the legwork; i don't have the expertise to troubleshoot R/ingest and akio is tied up with another project...

**Comment by landreev** [comment]
@donsizemore Yes, that would definitely work. (Somehow missed your last comment yesterday)
My harvard ip is 140.247.116.170.

**Comment by landreev** [comment]
@donsizemore @kcondon 
We've determined that R 3.5 works, under RH/CentOS 6 and 7, both. So I propose that we merge this branch asap - moving it back into QA - and then I'll quickly sync up my other branch (for #4878), add a couple of small changes, and move that one along as well. 
Don, the "couple of small changes" I want to make, to the section that you have updated - I want to add the rApache rpm, that I built for R 3.5 and RH/CentOS7 (thanks for the spec again). 
I'm also thinking of further simplifying the R versions paragraph. I would drop any mention of 3.3 altogether. 
And maybe just say - "get it from EPEL; currently offered version is 3.5. 3.4 was known to work too."

Thanks for bringing all this to our attention - it all needed to be addressed.
