### ISSUE TITLE
Guides process

### ISSUE THREAD

**Issue by matthew-a-dunlap** [IQSS/dataverse#4755]
There are a few guides and release related discussions going around right now, I am collecting them here so we can discuss this process:

- If you go to guides.dataverse.org, it redirects to latest. However we reference this, it should be the latest released (this is proposed).
- Furthermore, there would be some benefit in building the development (truly latest) guides and linking to them in some places so everyone contributing is on the same page as to what the code expects. We may even want certain pages of our latest guides to point to the develop-branch version as those are the ones developers should be using. This would probably only be worthwhile as an automated process (Jenkins job?). 

An approach to these issues may also tie into discussion around our release process in general.

**Comment by oscardssmith** [comment]
for the Jenkins piece, I would propose dev as the name.

**Comment by matthew-a-dunlap** [comment]
I want to capture a specific "users" issue around this. During the community meeting I was asked about the state of file provenance in our code base. Turns out the user had thought we hadn't actually implemented anything because our latest guides did not provide any info about provenance. But this was because our latest guides were for 4.8.6 not 4.9 .

**Comment by pdurbin** [comment]
Speaking of developers, if we're going to start the "develop" branch nightly, http://guides.dataverse.org/en/develop/developers/intro.html would probably be a better destination for the "Developers" link at https://dataverse.org because the page it links to now ( https://dataverse.org/developers ) is not being maintained. It's sort of a brain dump from me when Liz asked me about it over two years ago. As developers, we could probably better maintain this information in the dev guide.

Here are screenshots of the current user experience of clicking "Developers" from the project page:

![screen shot 2018-06-18 at 1 53 23 pm](https://user-images.githubusercontent.com/21006/41553419-c4151348-72ff-11e8-9a85-1eb298e8e7e3.png)

![screen shot 2018-06-18 at 1 53 37 pm](https://user-images.githubusercontent.com/21006/41553418-c407d002-72ff-11e8-99b5-ffeb283abf28.png)

**Comment by pdurbin** [comment]
I just clicked "build now" at https://build.hmdc.harvard.edu:8443/job/guides.dataverse.org-develop/ to build the latest version of the guides on the "develop" branch because I'm tired of building them locally as I wait for the next release.

**Comment by pdurbin** [comment]
These days, thanks to @poikilotherm we can preview the "develop" branch of the guides at https://preview.guides.gdcc.io/en/develop/

I'd say that's enough to close this old issue unless anyone objects. 😄
