### ISSUE TITLE
File Upload - Delete warning message incorrectly displayed

### ISSUE THREAD

**Issue by oscardssmith** [IQSS/dataverse#4758]
Steps to reproduce:

1. Add 4 ingestable files to a dataset (should work with 1, but slower delete speed with 4 aids reproduction)
2. Delete those file, and upload a new file before the changes fully process

This results in a message `Partial success: only -3 files out of 1 have been saved. Please try uploading the missing file(s) again`.

This message occurs because the order is

1. ask for file deletion
2. ask for file upload
3. files are deleted
4. ingest completes

As a result `save` in `EditDatafilesPage` sees that there were more old files than new files, causing the error message.

To solve this, we could either do a better job of tracking the files, or simply prevent uploading files until deletions are fully processed.

**Comment by oscardssmith** [comment]
Alternatively for the reverse bug:
In two separate windows upload several files at the same time.

This produces the same message, except it will be `6 out of 5` or something similar.

**Comment by mheppler** [comment]
@oscardssmith changed your issue title to be a little more specific to the workflow you are reporting an issue for.

**Comment by mheppler** [comment]
@kcondon, I was not able to replicate this issue locally in develop.

In the 4.12 (#5535) and 4.15 (#5550) releases, there were improvements to how the system handles dataset edits and deleting files. Specifically, "add editInProgress lock" changes (2e2e0ef0a6b6bfaef134062476a6b3d505261b17) from @qqmyers to the `save` command in EditDatafilesPage.

Maybe I was missing something in my attempts to replicate, but I have a feeling that all the piping behind these features has been recently refactored and this bug was squashed.

**Comment by kcondon** [comment]
@mheppler, still happens:
![Screen Shot 2019-06-19 at 12 53 48 PM](https://user-images.githubusercontent.com/4983816/59784809-5c6be980-9291-11e9-9604-11999b7d98a6.png)

**Comment by mheppler** [comment]
@kcondon ahhhh, you're better at replicating bugs than I am. Sorry for the noise.

Also, thank you for the screenshot. That is an oddly styled and formatted message text.
