### ISSUE TITLE
Redesign install for OpenShift containers

### ISSUE THREAD

**Issue by thaorell** [IQSS/dataverse#4764]
Problems: When a container starts up, installer/install is called on ENTRYPOINT. Under an installation on containers, a default.config file is used for user configurations for Glassfish, Solr and Postgres.
Ideally, we want to move the parts that take care of installing and deploying Glassfish to ‘docker build’. User inputting their config should be defined before containers start up, where a user can inject using ConfigMap or Secrets. 
By moving Glassfish setup to ‘docker build’ phase, we would save, on average, 100.5 seconds on start up time

**How should it work?**

New versions of the install script should follow this diagram
![image](https://user-images.githubusercontent.com/25762021/41736416-652879ee-755a-11e8-8969-b88c4c165809.png)

Some background information: 
**ConfigMaps** is a feature which enables config items to be decoupled from image content to keep containerized applications portable.

- In this case, we want the users to keep generic, non security intensive information in ConfigMaps

**Secrets** are used for info that needs to be made private. POSTGRES_ADMIN_PASSWORD and POSTGRES_USER, POSTGRES_PASSWORD should be kept here.

**Init containers** are containers which run before app containers and can contain setup scripts not included in the app image. 

- PostgreSQL database setup can be in init container. 

Design options:
**Option 1** (more preferable): keep the current script intact, but changing a couple features:
Instead of calling ‘install’ at entrypoint after ‘docker build’, move parts 2, 3, 4b, 5, 6 to Dockerfile. It will also require following components:

- Predefined ConfigMap for user configs 
- An init container will take care of Postgres operations and application testing
- The current install file cannot be used since Dockerfile already takes care of starting Glassfish domain and deploying. The suggestion would be moving parts of ‘install’ to a new script for the init container.

     Else: run the regular install by using the existing install script
     Advantage: not required to rewrite the whole script

Option 2: break the install script down and rewrite to 3 different scripts. Then, call the new scripts from the current script, which is kept for backward compatibility:

- Script A takes care of parts in ‘ConfigMap/ Secrets’: Database name, emails, usernames, etc.
- Script B takes care of parts in ‘docker build’ (diagram): Glassfish configuration and testing
- Script C takes care of parts in ‘init container’: Starting and populating PostgreSQL and check if Dataverse is running properly

    Advantage: Once the problems are broken down, writing the new scripts would be easier, i.e.: in Ansible. 
    Note: backward compatibility has to be taken into consideration

**Comment by pameyer** [comment]
@thaorell Very glad to see you're looking into this; I suspect that the startup speedup may be more than ~100s (I'm usually seeing ~10-20m, but hardware/infrastructure may be a factor).

Two initial questions:
- what's the thinking for using an init container for postgres, but not for glassfish/dataverse?
- could you suggest any resources for more information on ConfigMaps and init containers (for folks with less background, like me)?

**Comment by thaorell** [comment]
@pameyer right now I am just basing this measurement on the current openshift configuration. I recorded the timestamp when running installs and the longest processes took 100s in total. Under what situation would it take ~20 mins?
To answer your questions:
1. The initial thought is that during container startup in OpenShift, we want most of the tools/environments to be in place, so that we have a more sufficient start up time. When spinning up a dataverse container, GlassFish takes a long time deploy the war file, so that piece should be in docker build. The init container, then, will have the job of setting up postgres env, populating the database.
2. I hope these articles are helpful:
https://docs.openshift.com/enterprise/3.2/dev_guide/configmaps.html
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/

**Comment by thaorell** [comment]
Instead of deploying dataverse.war during docker build, moving dataverse.war to /glassfish/domains/domain1/autodeploy seems to get the job done.

**Comment by danmcp** [comment]
@pameyer I believe the init container is part of the glassfish pod.  It's purpose would be to wait for postgres to start among other things.

**Comment by pdurbin** [comment]
@thaorell it was great to meet you at last week's Dataverse Community Meeting! Thanks for opening this issue and working on it!

Thank you to @danmcp for foreshadowing this work during the Community Meeting. Here's a screenshot of slide 8 from his "Dataverse + OpenShift/Kubernetes" talk: https://schd.ws/hosted_files/dataversecommunitymeeting20/b2/Slides%20-%20Dataverse%20%2B%20OpenShift%252FKubernetes.pdf

![slides - dataverse openshift 2fkubernetes](https://user-images.githubusercontent.com/21006/41802521-4fced16a-764f-11e8-94d3-7ec37f0163ac.png)

@thaorell @pameyer @donsizemore and I had a nice chat about this issue today at http://irclog.iq.harvard.edu/dataverse/2018-06-22 and others are welcome to catch up on the conversation there and check out the progress at https://github.com/thaorell/dataverse/tree/4764-openshift-install-redesign

Personally, I'd be inclined to do a proof-of-concept within docker-aio because it's so much simpler, not requiring Minishift, but I'm fine with whatever approach and I'm happy to lend a hand.

I don't think it would hurt to look at the great Java EE and Docker work that @AdamBien has described at http://www.adam-bien.com/roller/abien/entry/java_ee_and_docker_quickstart and other places. Rather than using "fat wars" this issue might be our opportunity to slim down our Docker images to be based on Docker images from Glassfish or Payara.

Also, for anyone interested in a little history, I posted a timeline of Dataverse and Docker at https://github.com/IQSS/dataverse/issues/4665#issuecomment-391926503

For the current state of Dataverse and Containers, I recommend reading http://guides.dataverse.org/en/4.9/developers/containers.html

The only new addition is the work by @4tikhonov at https://github.com/IQSS/dataverse-docker

**Comment by pdurbin** [comment]
> I don't think it would hurt to look at the great Java EE and Docker work that @AdamBien has described at http://www.adam-bien.com/roller/abien/entry/java_ee_and_docker_quickstart and other places.

This was easy to get working and I just pushed a new repo at https://github.com/pdurbin/javaee-docker

**Comment by pdurbin** [comment]
@thaorell thanks for creating pull request #4805! I just move it into code review at https://waffle.io/IQSS/dataverse

**Comment by pdurbin** [comment]
@thaorell I just added a code review to pull request #4805. I didn't execute any of the code yet and I'm out the rest of the week. Please take a look at what I wrote. The biggest problem I see is all the code duplication, which will introduce a maintenance burden. I thought the idea was to break down the existing scripts into smaller scripts that call each other, kind of like how the "install" Perl script calls the "glassfish-setup.sh" shell script.

**Comment by thaorell** [comment]
![Final Design](https://lh3.google.com/u/0/d/1rj58Ia_oDEA7zH_OGDVutZoFFIWtDvXwGrsJ107StbU=w1920-h980-iv10)

PR #4805 does the following things:
now install script is split into 3 scripts: install, postgres-setup and glassfish-startup.
1. Install will process user inputs
2. Postgres setup creates Dataverse Database and user, and prepopulate Postgres DB after deployment
3. Glassfish-startup takes care of glassfish configurations: setting memory, set JVM options

For container users: 
1. During docker build, glassfish-setup.sh will be call to set up JVM options.
2. An init container will set up Postgres database and create Dataverse Postgres user.
3. During startup, glassfish-startup is the main script that will run

**Comment by pdurbin** [comment]
@thaorell thanks for the detailed summary. I made some fixes in 8be1695 b9c534f and 49e0bed that I'd like you to review. At the bottom of `conf/docker/build.sh` I added a TODO to run `docker build` on `conf/docker/dataverse-glassfish/init-container/Dockerfile`. Unless you have this in some other script can you please add it? Or let me know if you'd rather have me add it. Thanks!

**Comment by pdurbin** [comment]
I should mention that as of 49e0bed I tested the following and they all work:

- docker-aio (all API tests pass)
- vagrant (can log in as dataverseAdmin)
- minishift (can log in as dataverseAdmin)

I've been chatting with @thaorell in Slack and he's going to look into the TODO above. If it's to hard or weird to add it, I'm happy to do it since it's my ugly script.

Apart from that, I think I'm ready to move this issue to QA. @landreev is back tomorrow and might want to see the fairly massive changes made to the installer, through. Others are welcome to take a look as well, of course!

**Comment by pdurbin** [comment]
@thaorell implemented the extra build step in 3bb3cb8 and I think pull request #4805 is in good shape so I moved it to QA.
