### ISSUE TITLE
Metrics Aggregator

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#4766]
Now that we have metrics endpoints (#4527), we should use them. :slightly_smiling_face: Instead of modifying the Miniverse application to go against the new endpoints, we should investigate some other options for aggregating the metrics from all the Dataverse Installations for use in a visualization on the dataverse.org/metrics site, or allowing other institutions or groups to pull metrics from several installations.

A lightweight way to visualize the metrics, such as http://metricsgraphicsjs.org/ or something similar, will be handled separately from this and possibly by a different group. This is just for something to collect, aggregate, and make available the metrics from a group of installations.

**Comment by pdurbin** [comment]
We discussed this issue last week at backlog grooming. We didn't assign a size, an estimate. There are still a lot of open questions:

- Where will the code be deployed? AWS? HMDC VM? Heroku? Other?
- What programming language will the metrics aggregator be written in? Should we improve any of the existing API client libraries that exist for Dataverse to make them capable of handling the new metrics endpoints?
- Will a database be used? If so, will it have anything to do with the database that is used to power the map on the project site?

**Comment by scolapasta** [comment]
So the approach we agreed in is that the script will accept any arbitrary call to the metrics API and try it. Assuming success it will write the values to a cache (and use that on subsequent calls within a certain time period).

This keeps a relatively light approach (rather than having wrappers of each individual API), while still allowing these APIs to be pinged "on demand".

**Comment by jggautier** [comment]
Just noting here that for Harvard Dataverse the total download count that the API reports, https://dataverse.harvard.edu/api/info/metrics/downloads/toMonth, won't match the total shown on the  https://dataverse.harvard.edu homepage (root). I think this is because of the appx. 600k guestbook records in the database that don't have timestamps (https://github.com/IQSS/dataverse/issues/3324).

**Comment by pdurbin** [comment]
I just made pull request #4973 which is mostly a pointer to the git repo for the metrics aggregator, which is https://github.com/IQSS/metrics.dataverse.org

In the other repo I made pull request https://github.com/IQSS/metrics.dataverse.org/pull/1 so that's where code review of the metrics aggregator should happen.

I knocked together a quick visualization for the data in the six TSV files that the metrics aggregator creates:

![screen shot 2018-08-17 at 2 28 50 pm](https://user-images.githubusercontent.com/21006/44283375-366a5880-a22c-11e8-9f4e-469a0b4959c1.png)

- [dataverses-byCategory.html.txt](https://github.com/IQSS/dataverse/files/2298347/dataverses-byCategory.html.txt)
- [datasets-bySubject.html.txt](https://github.com/IQSS/dataverse/files/2298348/datasets-bySubject.html.txt)
- [index.html.txt](https://github.com/IQSS/dataverse/files/2298349/index.html.txt)

Moving to code review at https://waffle.io/IQSS/dataverse

**Comment by pdurbin** [comment]
@kcondon I see you closed this issue. Does that mean you're happy with the code in https://github.com/IQSS/metrics.dataverse.org/pull/1 (the pull request in the new git repo)? If so, can we merge it?

**Comment by pdurbin** [comment]
@kcondon indicated he tested the code on Python 2 and that it seemed fine so I went ahead and merged https://github.com/IQSS/metrics.dataverse.org/pull/1 and cut a release at https://github.com/IQSS/metrics.dataverse.org/releases/tag/v0.1.0
