### ISSUE TITLE
Add RelatedIdentifier of Dataset to File Metadata sent to DataCite

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#4782]
The metadata sent to DataCite for files should include the Dataset identifier with a relationType of IsPartOf 

`    <relatedIdentifiers>
        <relatedIdentifier relationType="IsPartOf" relatedIdentifierType="DOI">${datasetIdentifier}</relatedIdentifier>
    </relatedIdentifiers>`

see file workingDataCiteMetadataTemplate.xml 
It should be referenced in DOIDataCiteRegisterService.java

Also, should there be references to the file DOIs in the Dataset metadata passed?

**Comment by pdurbin** [comment]
I just made pull request #4795. Moving to code review at https://waffle.io/IQSS/dataverse

**Comment by sekmiller** [comment]
At this point we don't want to add the relatedIdentifier to Datasets
![screen shot 2018-06-29 at 4 23 58 pm](https://user-images.githubusercontent.com/2364928/42113900-0651f6b8-7bbb-11e8-94e0-480030843dd0.png)

**Comment by pdurbin** [comment]
> add file DOIs with a tag of something other than "isPartOf"

@sekmiller indicated that this is a suggestion from @scolapasta so I'm assigning this issue to him to make a decision or provide further guidance on the definition of done for this issue.



https://github.com/IQSS/dataverse/pull/4795/files#r199499888

> We shouldn't add an empty relatedIdentifier to Datasets:

@sekmiller and I discussed this issue this morning and I voice general grumpiness with the brittleness of the code, how it does a "find and replace" of and how the template has been dumped into the main "dataverse" package rather than being placed in a subpackage ( https://github.com/IQSS/dataverse/pull/4795/files#r199499888 ). The quick fix would be to make a second version of the XML file we do the "find and replace" on and only have that file include the new `IsPartOf` concept. Unless, of course, the definition of done turns out to be that `IsPartOf` is sent for both datasets and files.

**Comment by jggautier** [comment]
The relationship type is HasData. (This is what Dryad uses and the DataCite Search portal interprets it correctly.) See more here: https://docs.google.com/document/d/1tevjRIX96EFCYzAgw7KU-bmKT_kabyZb-ilMHxyb5dc/edit?usp=drivesdk

**Comment by pdurbin** [comment]
In 1c4313c I helped @benjamin-martinez resolve some merge conflicts. He's going to re-test to make sure the code still works. @sekmiller heads up that some comments you added got lost during merge conflict resolution. I don't know how important they are.

**Comment by pdurbin** [comment]
@benjamin-martinez the pull request has merge conflicts again. Can you please resolve them? Thanks! Here's that page we were looking at yesterday if it helps: http://guides.dataverse.org/en/4.9.1/developers/version-control.html#how-to-resolve-conflicts-in-your-pull-request

**Comment by kcondon** [comment]
OK, in addition to Leonid's comments on how it works, the scope is both EZID and DataCite but not Handles.
