### ISSUE TITLE
as a Dataverse Developer, I'd like the existing automated tests to run without human intervention

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4812]
From discussion with @pdurbin (both in person and in irc); the existing integration tests run on the IQSS jenkins server still require human intervention (aka - push the button).  These are composed of three dependent jobs (build, deploy, test).

Specific changes:
- [ ] Primary improvement: Add daily annotation to jenkins job(s) config (or cron w\ jenkins CLI, but from discussions the annotation would be preferable).
- [ ] Slight enhancement: modify the deploy job to check the commit hash from the build job with the `api/info/version` endpoint to ensure that the correct build has been deployed.
- [ ]  Possible enhancement: have the automation report when there are test failures.  Some discussion of how (email to dataverse list, create github issue, etc), would need more discussion.

Some additional discussion of larger-scale improvements, to be deferred to later issue.

**Comment by djbrooke** [comment]
Thanks @pdurbin and @pameyer! Moved to Backlog column for discussion.

**Comment by pdurbin** [comment]
#4332 is related, a fancier way to raise awareness that tests are failing that what is suggested above.

**Comment by pameyer** [comment]
I'm wondering of doing a local cron job that automatically creates issues might be another way of addressing this.

**Comment by pdurbin** [comment]
@donsizemore @scolapasta and I just met to talk about https://jenkins.dataverse.org and https://github.com/IQSS/dataverse-jenkins

@scolapasta and I decided to use this issue to track getting the API test suite running on that new Jenkins server.

**Comment by donsizemore** [comment]
Woo woo! Tried @pdurbin's IQSS-dataverse-api-test-suite-docker-aio-develop job this morning and only one test failed:
https://jenkins.dataverse.org/job/IQSS-dataverse-api-test-suite-docker-aio-develop/14/console

Interestingly, glassfish didn't fall over — I bet I was hitting the DatasetPage bug. Will trigger a build on my old job next.

The failed test, BTW:
```
DataversesIT.testMoveDataverse:364 JSON path data.total_count doesn't match.
Expected: <1>
  Actual: 0
```

**Comment by pdurbin** [comment]
@donsizemore and I are actively troubleshooting (for examples, Dataverse falling over with 500 errors in the middle of an API test suite run: http://irclog.iq.harvard.edu/dataverse/2019-08-19#i_102629 ) so I dragged this to to IQSS Team Dev.

@scolapasta @donsizemore and I talked about spinning up a test Jenkins server using the INSTALL.md writeup I added to https://github.com/IQSS/dataverse-jenkins but I haven't done this yet.

@donsizemore for the record, @djbrooke is fine with us spinning up EC2 instances for API testing rather than using Docker on the Jenkins server itself. I know this costs more but it's worth it. I'm also happy to continue troubleshooting docker-aio but we might want to see if @pameyer has a little time to help us.

**Comment by pdurbin** [comment]
Good meeting with @donsizemore and @scolapasta today. As promised, I just ran the docker-aio tests on my Mac as of e093c0f which amounts to these two commands from the readme:

- ./conf/docker-aio/prep_it.bash
- ./conf/docker-aio/run-test-suite.sh

The full test suite passed:

```
[INFO] Results:
[INFO] 
[WARNING] Tests run: 97, Failures: 0, Errors: 0, Skipped: 4
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:55 min
[INFO] Finished at: 2019-08-22T16:53:14-04:00
[INFO] ------------------------------------------------------------------------
```

For the record, there's a null pointer exception showing up in server.log about OAI-ORE exports failing but we must not have an integration test for this because this failure doesn't cause the test suite to fail. We're tracking that OAI-ORE issue at #6100.

**Comment by pdurbin** [comment]
As I mentioned at standup yesterday, there has been a major breakthrough thanks to the herculean efforts by @donsizemore in https://github.com/IQSS/dataverse-ansible and https://github.com/IQSS/dataverse-jenkins

I just created pull request #6272 to close this issue and add a button/badge/shield to the README so we can easily see if the API test suite is passing.

**Comment by djbrooke** [comment]
Thank @donsizemore !!!
