### ISSUE TITLE
As a dataverse curator, I need researchers to re-submit for review datasets that have been returned to them in a timely manner, so that datasets are available as soon as possible

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#4824]
@sbarbosadataverse recommended in https://github.com/IQSS/dataverse/issues/2128 that Dataverse send to depositors, whose datasets were returned, "an automated email every week or so" until the depositor "does something," to remind depositors that they need to act on the dataset.

https://github.com/IQSS/dataverse/issues/3702 is related, in that depositors will receive, in the same email notification that the dataset was returned, a reason from the curator about why it was returned, which might streamline the workflow and make it easier for authors to act.

**Comment by jggautier** [comment]
It's been a while since we opened this GitHub issue and I'm not sure if dataset authors are still taking too long to respond to datasets that have been returned to them.

To determine this, we could reach out to Dataverse collection managers who often return datasets to authors and ask them if those authors take a long time to take action and why that is.

**Comment by pdurbin** [comment]
Sure, sounds good. It might also be interesting for collection managers to see some sort of report or dashboard about which datasets have been sitting in "returned to author" state the longest.

**Comment by DS-INRA** [comment]
I think both of these suggestions (1. reach out to Dataverse collection managers, 2. have information on datasets sitting in "returned to author") are great.

1. To preemptively give a feedback on our collection, yes, dataset authors are still taking too long to respond to datasets :disappointed: but we are curating after the datasets publication, which makes returning to the curator and publishing the new version less attractive for the depositor.

2. The duration of draft or unpublished status would also be very interesting for us, we currently check this with a script because we try to make sure datasets do not remain unpublished after 12 months without reason (e.g. pluriannual research project)

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
