### ISSUE TITLE
Harvard Dataverse: Mint DOIs for datasets that currently have handles

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#4832]
With the new addition of PIDs for files, we ran into an issue with older datasets that have handles and given them DOIs. While it is possible to have mixed, it doesn't make sense in the case where you use "dependent" file PIDs, as we do at Harvard.

This issue is for tracking what is needed to Mint DOIs for those Datasets and track the handle elsewhere.

Note: we'll still need to maintain the handle server for existing citations to these datasets

**Comment by scolapasta** [comment]
The original idea I had was place the handle in the Other ID metadata field. We could then choose display this metadata field in the summary section.

A few issues with this:
1. We won't know for sure that the other id is the old handle or something else, so all Other Ids would show in the summary. This is possibly a non issue.
2. @mercecrosas  also suggested "And Ideally there would be some text that explains next to the 'other id' that this is the ID used in the old citation". This would be a challenge for the same reasons in #1.
3. Other id is versioned metadata, and it may not make sense to version the handle (i.e. it should belong to all versions).

Given those issues, I'm now leaning towards storing it somewhere more dedicated (and not versioned). But I'm open to hearing others' thoughts so we can properly design this.

**Comment by djbrooke** [comment]
I brought this to backlog grooming today thinking there would be no UI implications but that's not case. Since it is the case, we should work this through our usual design process. We'll get a better idea of what's needed and bring it to a future planning meeting.

Thanks @landreev for offering to put in notes from yesterday's meeting and to put in some further thoughts.

**Comment by landreev** [comment]
The only thing I wanted to add, from the planning meeting - let's make sure to run this by Gary (and maybe other owners of datasets with handles?) and see if they are really ok with this; seeing how assigning new main identifiers to their studies will change the citations and the dataset urls.

**Comment by landreev** [comment]
Maybe we should have put in a quick patch, for now, to simply skip the file-level registration, if the dataset global name protocol does not match the current protocol.

**Comment by scolapasta** [comment]
Given that we plan on supporting optional file PIDs, I think this would be a good idea. Am discussing UI / UX with @djbrooke and @TaniaSchlatter this afternoon, will suggest this.

**Comment by landreev** [comment]
Oh, another thing: this solution - registering the DOIs for all the older datasets - it may work for us, but we should probably not assume that all the other installations are going to like that idea. Didn't Odum also switch from handles to DOIs at some point? I don't think we want to enforce something like this on everybody. We need to think of some other solution for this scenario. (and I still think we want to at least provide a switch for turning off file-level registration completely...)

**Comment by pdurbin** [comment]
> (and I still think we want to at least provide a switch for turning off file-level registration completely...)

That's being tracked in #4929

**Comment by kcondon** [comment]
Note that while testing #4941  I've found that for a dataset registered with handle, :DataFilePIDFormat='INDEPENDENT', server log still indicates it is trying to register handles for files, when doi is configured and registration URL (callback/resolution) has hdl in the PID portion of the url in the logs. Was not able to confirm at EZID since it was not showing actual doi as registered.

**Comment by landreev** [comment]
@sekmiller @scolapasta 
I just saw the commit that modified the getFileSystemDirectory() method in Dataset.java, to use an alternative global id for the dataset directory - that looks great!

But please note that this method is only used by the filesystem DataAccessIO driver. The S3 and Swift drivers (S3AccessIO and SwiftAccessIO) access the global id of the dataset directly in order to create the storage container name; like this: 
String baseKey = this.getDataFile().getOwner().getAuthority() + "/" + this.getDataFile().getOwner().getIdentifier();
(this is from the S3 driver)
- so it'll need to be modified there too. 

Maybe it would be better to add some extra methods to the dataset - dataset.getIdentifierToUseForStorage() ?

**Comment by TaniaSchlatter** [comment]
In the discussion August 9 with @scolapasta and @djbrooke we decided to add “Previous Identifier   [handle ID]” to the metadata block.

**Comment by kcondon** [comment]
-Endpoint should say POST in guides
-error when minting doi on published dataset wit hdl.
