### ISSUE TITLE
Alphabetical sort of dataset templates in pull-down menu

### ISSUE THREAD

**Issue by philippconzett** [IQSS/dataverse#4848]
For user convenience, please apply alphabetical sort of dataset templates in pull-down menus; cf. screenshot:

![image](https://user-images.githubusercontent.com/21955790/42722868-0c644502-8754-11e8-8ae1-38040026409d.png)

Best,
Philipp (DataverseNO)

**Comment by landreev** [comment]
This is what I was talking about during the standup: 
The templates pulldown has this custom converter attribute defined: 
```
<p:selectOneMenu value="#{DatasetPage.selectedTemplate}" onchange="updateTemplate()"
                                                 converter="templateConverter"
```

This converter is implemented as this java class: src/main/java/edu/harvard/iq/dataverse/TemplateConverter.java

I suspect that, because it uses the database id of the template, PrimeFaces ends up re-sorting the list automatically by that numeric id (??). 
(that would be easy to prove - are the templates appearing in the database order?) 
This is a pretty random idea, that may be off - it's just that we are out of any other ideas...
@sekmiller wrote that converter class; Steve do you have any ideas/suggestions? Would it be possible to change the converter to use the name instead (are the template names guaranteed to be unique?)

(once again, the issue is that even though Ben forces Collections.sort(...) on the list of templates, the order never changes...)

**Comment by benjamin-martinez** [comment]
I made a custom sorter that alphabetizes templates, but it is very inefficient. Even if I made it more efficient, I'm not sure if we want to add a custom sorter to our source code. If someone can figure out why the line: 

`Collections.sort(dataverseTemplates, (Template t1, Template t2) -> t1.getName().compareToIgnoreCase(t2.getName()));` doesn't work, that would be ideal.

**Comment by sekmiller** [comment]
Very strange. And here's an even weirder thing. It's not ordering them by template.id The ordering seems to be related to which one was updated most recently. Whenever you create a dataset with a template we increment a usage count. As near as I can tell if I use a template, the next time I go to create a dataset the most recently used template is pushed to the bottom of the list. And this is even after I try to sort the Collection.

**Comment by matthew-a-dunlap** [comment]
It looks like the problem was due to the ArrayList being passed back via `dataverseService.find(ownerId).getTemplates()` . It had no problems adding elements to it but just did not want to be sorted. Adding its elements to a fresh ArrayList allowed sorting via @benjamin-martinez 's 1-liner.
