### ISSUE TITLE
Guestbook: User should be able to associate a guestbook with a template in a dataverse

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#4889]
I'd like the ability to associate any given guestbook with a "Template" I create for a dataverse

**Comment by mheppler** [comment]
This issue seems simple enough. If you look at the render logic `#{!settingsWrapper.rsyncOnly and (managePage==false or datasetPage == true)}` on the Guestbook panel in dataset-license-terms.xhtml it is missing the necessary `!empty editMode` to show in the template workflow. That said, there is a bunch of render logic for `editMode` for the content inside panel, and that will need to be massaged to properly render for the correct workflows.

Also of note, in the Terms of Access panel, there appears to be some contradictory render logic `!empty editMode or empty editMode` that most likely means it can be removed entirely to simplify the logic necessary to display this panel in the various workflows this panel is used in.

**Comment by mheppler** [comment]
Apparently @sbarbosadataverse REALLY wants this feature. She requested the exact same change in _Guestbook: Guestbook added to option when creating templates, under "terms of use" section #4029_. I will close that one as a duplicate.

**Comment by jggautier** [comment]
This issue came up in a Dataverse demo today. While demonstrating metadata templates, @sbarbosadataverse thought it was  already possible to specify in the template which guestbook should be enabled in datasets that use the template.

The goal of this suggestion is to make it easy for dataverse admins to have a guestbook applied to all datasets that will be published in their dataverse.

I think it was suggested that metadata templates be used to do this because it seems like a natural extension of the template feature:
1. If the dataverse admin chooses a default metadata template, the template's metadata will be applied to all datasets that will be published in that dataverse. If that template includes a guestbook, dataset depositors don't have to remember to enable the guestbook for their dataset. (If a default template is not chosen, depositors will have to choose a template, and if the template they choose includes a guestbook, that guestbook will be applied to the dataset they are depositing/curating.)
1. Guestbooks and Terms metadata are already coupled conceptually. The page where dataset depositors enter Terms metadata also includes the option to add a guestbook to a dataset, in a third panel labelled "Guestbook" :

   <img width="1148" alt="Screen Shot 2020-07-15 at 12 01 55 PM" src="https://user-images.githubusercontent.com/18374574/87568108-1e5b1800-c693-11ea-94c6-e3250b06991a.png">

   So @sbarbosadataverse and perhaps other Dataverse users would expect to see the same panel when creating or editing the Terms metadata in dataset templates. But the "Guestbook" panel isn't there:

    <kbd><img width="959" alt="Screen Shot 2020-07-15 at 11 44 28 AM" src="https://user-images.githubusercontent.com/18374574/87568149-2d41ca80-c693-11ea-9553-cff923a94a34.png"><kbd>

Adding a "Guestbook" panel in the metadata template creation form so that a guestbook can be applied to any datasets that use the template would enable a workflow where:
- The dataverse admin creates a guestbook
- The dataverse admin creates one or more metadata templates for that dataverse and adds the guestbook to at least one template
  - If the admin sets a template as the default template (to be used for all datasets that will be published in the dataverse), when a depositor creates a dataset, Dataverse always applies the template's metadata and guestbook to datasets created in the dataverse, so no one needs to go to the datasets' Terms page to add the guestbook.
  - If the admin doesn't set a template as the default template, dataset depositors will have to choose a template that has a guestbook. Dataverse would apply the template's metadata and guestbook to those datasets, so that it won't be necessary to go to the datasets' Terms page to add the guestbook.

We spoke briefly about looking for evidence that dataverse admins need an easier way to enable guestbooks in their dataverse's datasets. Are there admins of dataverses whose datasets don't have a guestbook enabled because of a problem with the current workflow for adding guestbooks to datasets? We could get info from Dataverse installations about datasets that we think should have guestbooks (e.g. get the number of datasets with no guestbooks enabled that are within dataverses  that do have their own guestbooks), and contact those dataverse admins to confirm that those datasets should have guestbooks and ask why guestbooks haven't been added. This might help surface other solutions and test the idea of using metadata templates.

**Comment by shlake** [comment]
Yes!! for I would love this one!!!! Am just getting around needing a guestbook for a collection and need to have the guestbook enabled for every dataset.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
