### ISSUE TITLE
As a data curator, I need other discovery systems (search engines, social media platforms) to display description metadata for my datasets and files so that the data is easier to find

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#4894]
This github issue is about making sure that search engines display what's in the description field when displaying datasets and files, similar to the work done for making sure that search engines display dataverse descriptions (https://github.com/IQSS/dataverse/issues/1802).

_Google uses the meta.description tag (`<meta name="description" content="" />`) to display dataverse descriptions in search results:_
<kbd>![screen shot 2018-07-25 at 3 26 28 pm](https://user-images.githubusercontent.com/18374574/43222788-20e05af6-901f-11e8-9b4a-396f80590795.png)</kbd>

_Datasets don't have meta.description tags but do have dc.description tags (`<meta name="DC.description" content="" />`). But it seems that Google does **not** use the dc.description tags to display dataset descriptions in search results:_
<kbd><img width="582" alt="Screen Shot 2019-03-14 at 11 54 42 AM" src="https://user-images.githubusercontent.com/18374574/54371599-07945380-4650-11e9-86ef-a3fa179c8945.png"></kbd>

 There are also remaining questions about dataverses and using other types of tags, some brought up in https://github.com/IQSS/dataverse/issues/4468:
- Should file pages have meta.description tags so that search engines display the file description?
- For files, what, if anything, should be displayed when there is no file description?
- For datasets, what, if anything, should be displayed when there is no dataset description? (It's a required metadata field now, but some datasets, like [this dataset](https://doi.org/10.7910/DVN/GBHYFB), have been published without descriptions.)
- For dataverses, what, if anything, should go in the meta.description tag when there is no dataverse description? (In https://github.com/IQSS/dataverse/issues/4468 for Dataverse 4.9.2, nothing is entered.) There're also some discussion in comments in #5605.
- ~~Should we consider other meta tags (e.g. Twitter seems to ignore meta tags but uses the standard Open Graph tags `og:description` or its own Twitter cards `twitter:description`)?~~ (implemented in #5640 and investigating further support in #5641)

**Comment by adam3smith** [comment]
> Should we consider other meta tags (e.g. Twitter seems to ignore meta tags but uses the standard Open Graph tags og:description or its own Twitter cards twitter:description)?

I was just looking at this because Dataverse links on Twitter are sad. I think adding Open Graph tags for Twitter and Facebook would be great.

I don't have answers or even opinions on most of the other questions except that, if there is no description given e.g. for a file, the metadata for description should be empty. I think it's bad practice to put some default text in the description instead.

**Comment by pdurbin** [comment]
@adam3smith can you please post a screenshot of a sad Dataverse link on Twitter? https://twitter.com/BrianAmos/status/1034081533227937793 doesn't look bad but maybe they added an image separately? Here's a screenshot:

![screen shot 2018-10-04 at 12 49 40 pm](https://user-images.githubusercontent.com/21006/46489697-17bc2300-c7d4-11e8-9b1a-aee20c663443.png)

**Comment by adam3smith** [comment]
yeah, that looks like an image to me. Tweet: https://twitter.com/qdrepository/status/1046796917013975040 (contrast with the CUP article below). 

Screenshot: 
![image](https://user-images.githubusercontent.com/128986/46490762-daa56000-c7d6-11e8-9ff0-c8802b7b9d6d.png)

**Comment by pdurbin** [comment]
@adam3smith thanks. Good examples.

You and @qqmyers might want to look at pull request #4879 to see how small the fix was for #4468 and I wonder if a fix for this issue would be similarly small.

@lmaylein made that excellent contribution by the way. Thanks again!

**Comment by qqmyers** [comment]
FYI - PR5600 has Open Graph metadata for datasets. @adam3smith created the basics and I added a 150 char truncation of long descriptions and a pointer to the favicon. I think it would be striaght forward to add similar info the dataverse and file pages (if similar metadata can be found). 

The one thing we didn't do was to use a thumbnail of the dataset as the image - Open Graph requires a full URL for links and I didn't find any API/URl for the dataset thumbnail. Does such a thing exist and I just missed it? If not, is there a reason not to have one to use in this way?

**Comment by pdurbin** [comment]
@qqmyers 4 years ago when I created https://github.com/IQSS/dataverse-android over the winter break we had downloadable thumbnail images via the Search API that I could use in that Android app. I opened #3616 about this but ultimately closed it due to lack of interest. Thumbnails are actually downloadable via a different mechanism these days but I don't believe it's documented. Please see

- testDatasetThumbnail in SearchIT.java: https://github.com/IQSS/dataverse/blob/v4.11/src/test/java/edu/harvard/iq/dataverse/api/SearchIT.java#L230
- getDatasetThumbnail in Dataset.java: https://github.com/IQSS/dataverse/blob/v4.11/src/main/java/edu/harvard/iq/dataverse/Dataset.java#L763

I mostly added that code so I could test thumbnails back when I worked on pull request #3703 for #3559. There be dragons. Help wanted. I went ahead and moved pull request #5600 but please let me know if you'd like to poke at thumbnails before it's tested by QA. Thanks!

**Comment by qqmyers** [comment]
@pdurbin - thanks. My initial try was to just put the base64 encoded data:image/png;base64,... info that's used in the page as the URL for Open Graph, but it doesn't support that.  So it seems I need a real, full URL.  I was thinking that just having a .../dataset/<id>/thumbnail endpoint that streams what you'd get from getThumbnail() would be a simple way to do it.  I hadn't considered search. Do you see dragons just adding  dataset/<id>/thumbnail endpoint versus trying to restore what used to work via search? Any reason not to try this?

I guess if there are dragons, we shouldn't hold up the current PR. If it is just adding an API call, I could probably try that quickly...

**Comment by pdurbin** [comment]
@qqmyers hopefully the dragons are small and can be slain. 🐉 ⚔️ If you restore, real downloadable thumbnails, maybe I'll crack open that old Android code (but no promises). 😄 Are you thinking you'd want to add that into this issue or a new issue? Small chunks are usually better for us. And in our experience, whenever we touch thumbnails the chunk is not small.

**Comment by qqmyers** [comment]
@pdurbin - lets do it in pieces so this can get out as is...

**Comment by pdurbin** [comment]
@qqmyers I just spoke with @matthew-a-dunlap and he said we played around with showing dataset thumbnails on the custom homepage for Harvard Dataverse. The API for showing thumbnails is not documented but you can see it being called from some HTML at db87186

**Comment by qqmyers** [comment]
@pdurbin - Thanks for the info - I missed that call. I've updated the logic to use the thumbnail in the OG metadata, iff it exists, favicon otherwise. I'll submit a PR...

**Comment by djbrooke** [comment]
@jggautier I moved the Open Graph support to other issues (#5640 and #5641) and crossed it out on the list above. I'm going to move this issue to the inbox because I think it needs further discussion before implementation, but let me know if you think it should be prioritized sooner and want to discuss.

**Comment by landreev** [comment]
FWIW, to me it looks like Google does index our dataset descriptions just fine. See the screenshots of the two recent datasets - both are showing parts of the description:

![Screen Shot 2019-03-11 at 7 57 12 PM](https://user-images.githubusercontent.com/737558/54558212-88768680-4993-11e9-9956-c87d52dc03a8.png)
![Screen Shot 2019-03-11 at 11 12 57 AM](https://user-images.githubusercontent.com/737558/54558225-92988500-4993-11e9-9946-ac31f199177d.png)

**Comment by jggautier** [comment]
Met with @scolapasta and @mheppler to discuss how to make search engines show dataset and file descriptions. We agreed on next steps:

- Dataset and file pages have empty`<meta name=description />` tags because Dataverse only adds the description metadata to the tag if the page is dataverse page. So change metadata description tag on dataverse_template page to accept a parameter.
- Add dataverse description to parameter for `<meta name=description />` tag in dataverse pages.
- Add dataset description to parameter for `<meta name=description />` tag in dataset pages.
- Add file description to parameter for `<meta name=description />` tag in file pages. (Harvard Dataverse's robot.txt is telling Google not to index file pages for now, but that may not be the case for all installations.)
- Research SEO best practices for truncating description in metatags. Search engines might not like really long descriptions.

We discussed ideas about what search engines and social networks should show when there is no metadata in the dataverse/dataset/file description field. A nice to have feature, which we'll discuss in detail later, would be for Dataverse to generate descriptions that include information about the dataverse/dataset/file, e.g. subject metadata for dataverses and file types/download counts for files.

**Comment by landreev** [comment]
@mheppler (I'm hoping this is the right issue) About the dataset logos: 
Unlike the file thumbnails, dataset thumbnails are hardcoded at 48 pixels; they were never meant to be blown up - so they look terrible when these other sites try to do that in their preview cards. 
It should be easy to add a size parameter to this API call - let's open an issue for it. 
But, as I mentioned earlier, I was afraid it would not work as easily for the dataset thumbnails that are made from specially uploaded images ("logos"). Because I thought we might be resizing them to 48 pixels on upload, and discarding the originals... But no - it looks like we generate and save the thumbnail as "dataset_logo.thumb48"; but also save the original - as "dataset_logo_original". So we can make copies at different resolutions later on - and we can do that for the already existing logos as well.

**Comment by mheppler** [comment]
The Google results for [IMDB pages](https://www.imdb.com/title/tt0093378/) was mentioned as an explain of metadata passed in the source code using Schema.org JSON formatting. I took a look at the source code for one of their pages and found the description was included as:

```
<meta name="description" content="Directed by Luis Valdez.  With Lou Diamond Phillips, Esai Morales, Rosanna DeSoto, Elizabeth Peña. Biographical story of the rise from nowhere of early rock and roll singer Ritchie Valens who died at age 17 in a plane crash with Buddy Holly and the Big Bopper." />
```

```
<meta property="og:description" content="Directed by Luis Valdez.  With Lou Diamond Phillips, Esai Morales, Rosanna DeSoto, Elizabeth Peña. Biographical story of the rise from nowhere of early rock and roll singer Ritchie Valens who died at age 17 in a plane crash with Buddy Holly and the Big Bopper." />
```

```
<script type="application/ld+json">{
  "@context": "http://schema.org",
  ...
  "description": "La Bamba is a movie starring Lou Diamond Phillips, Esai Morales, and Rosanna DeSoto. Biographical story of the rise from nowhere of early rock and roll singer Ritchie Valens who died at age 17 in a plane crash with Buddy Holly and..."
  ...
}</script>
```

**Comment by djbrooke** [comment]
Hey @jggautier - can we estimate the first four bullets in https://github.com/IQSS/dataverse/issues/4894#issuecomment-474073181 ? Seems like a discrete, clear chunk.

**Comment by djbrooke** [comment]
We should implement these:

- Dataset and file pages have empty<meta name=description /> tags because Dataverse only adds the description metadata to the tag if the page is a dataverse page. So change metadata description tag on dataverse_template page to accept a parameter.
- Add dataverse description to parameter for <meta name=description /> tag in dataverse pages.
- Add dataset description to parameter for <meta name=description /> tag in dataset pages.
- Add file description to parameter for <meta name=description /> tag in file pages. (Harvard Dataverse's robot.txt is telling Google not to index file pages for now, but that may not be the case for all installations.)

**Comment by scolapasta** [comment]
FYI, the performance gains mentioned above are because the template is instantiating the DataversePage backing bean every time, even for other pages:

See line 26 of:
https://github.com/IQSS/dataverse/blob/develop/src/main/webapp/dataverse_template.xhtml

```<meta name="description" content="#{MarkupChecker:stripAllTags(DataversePage.dataverse.description)}"/>```

**Comment by mheppler** [comment]
Added new `meta_header` param to dataverse_template, and dataverse, dataset and file pgs.

Example from dataset.xhtml:

```
<ui:define name="meta_header">
<meta name="description" content="#{DatasetPage.description}"/>
</ui:define>
```

![Screen Shot 2019-08-13 at 1 34 00 PM](https://user-images.githubusercontent.com/687227/62963446-09b13880-bdcf-11e9-9b11-721a49f11624.png)
