### ISSUE TITLE
Dataverse header: Additional css class in dataverse_header.xhtml

### ISSUE THREAD

**Issue by lmaylein** [IQSS/dataverse#4917]
I would like to suggest an additional css class for

` <div id="dataverse-header-block">`

depending on the dataverse which is displayed.

For example:

` <div id="dataverse-header-block" class="dv-alias-#{dataverse.alias}">`

This would allow administrators to use individual css styles for dataverses.

**Comment by pdurbin** [comment]
@lmaylein sounds fine to me. How do you feel about making a pull request?

**Comment by lmaylein** [comment]
I do it with pleasure. Is there any naming convention for ids or class names in dataverse?

**Comment by pdurbin** [comment]
I suppose you're asking if we use BEM or OOCSS or SMACSS or some other CSS naming convention. I don't know and I don't see anything about this in the Style Guide: http://guides.dataverse.org/en/4.9.1/style

**Comment by djbrooke** [comment]
@lmaylein @pdurbin I'd like to get the design team's feedback on whether or not we want to allow this before any PRs are made. I'll check back in soon.

**Comment by djbrooke** [comment]
Hi @lmaylein, we talked about this briefly in the design meeting earlier this week. 

Can you let us know a bit more about the user request here, such as what the person is trying to accomplish? 

Also, are you aware of the currently existing theming options  (http://guides.dataverse.org/en/latest/user/dataverse-management.html#theme)? If so, it would be good to know where these theming options are falling short so that we can evaluate this request within that context. 

Thanks!

**Comment by lmaylein** [comment]
It isn't easy to bring the design of a dataverse close to the corporate design of the corresponding institution or journal. For example, even the possibilities to scale a logo are limited.
Therefore we have inserted the suggested class definition in our templates.

Example:

https://heidata.uni-heidelberg.de/dataverse/archber

```
#dataverse-header-block.archber .dataverseHeaderLogo img {
    width: 100%;
    max-width: 100%;
}
```

**Comment by mheppler** [comment]
Thank you for providing more feedback, @lmaylein. I believe this layout issue can be addressed by improving the CSS for the dataverse theme feature, rather than adding a special custom solution.

If it's a problem for one dataverse, then it is most likely a problem we should solve for other dataverses. We should look into improving the dataverse theme CSS to be more flexible.

**Comment by lmaylein** [comment]
It would be nice, if there will be possibilities to use different (arbitrary) CSS formattings for single dataverses of the same instance. The additional class-attribute seemed to me the easiest way. But if you plan to revise the dataverse theme feature anyway, that's of course also right for me.

**Comment by philippconzett** [comment]
More css flexibility at sub-dataverse level would also be useful for our Dataverse installation. Thanks!

**Comment by eugene-barsky** [comment]
Just seconding this request for a second logo option, as we have many multidisciplinary teams that want to deposit data and are coming from many institutions...

**Comment by djbrooke** [comment]
We revisited custom dataverse-level footer CSS in #6156, discussed it with the design team, and added some information to that issue. We were hesitant to add this level of customization as it would make it more challenging to design in the future and may have other impacts. Based on the outcome of that discussion from a few months ago, I'm going to close this issue. 

@TaniaSchlatter - please let me know if I'm missing something and let me know if this is a different enough request that we should discuss in more detail.
