### ISSUE TITLE
Script to switch production file dois from reserved to public

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4927]
There was/is a bug in the register single file doi endpoint which resulted in file dois that were retroactively created to remain in reserved state even when published. The net result is the dois are not resolvable. We need a way to preserve the dois that were created but switch them to public.

**Comment by pdurbin** [comment]
This issue got a "1" during sprint planning but I have questions:

- Is there an existing script that we can use as a starting point?
- Is the plan to hit the EZID API directly? My understanding is that https://ezid.cdlib.org/doc/apidoc.html are the docs.
- If we don't hit the EZID API directly, is the plan to add a feature to Dataverse? I guess we'd call the feature "make reserved DOIs public" or something.

**Comment by pdurbin** [comment]
I spoke with @sekmiller about this issue this morning and now I have another question:

- Do we have a list of DOIs that we need to fix? Or is part of the scope of this issue coming up with a list? It's my understanding that if we don't have a list we'll need to conduct an audit of all of our DOIs (we have 403,918 files and 78,757 datasets published in Harvard Dataverse) and call out to the EZID API over and over to determine which ones need to be fixed. Or I guess we could just iterate through all the DOIs that should be public and make sure they are public.

**Comment by landreev** [comment]
@pdurbin This affects every file-level DOI that was registered using the API. So the list of files on which we ran that registration script is the list of the DOIs that need to be fixed. 

Some portion of them may have been fixed since then, if the dataset owner has published it again. But it must be easier to just run it on every DOI from the original list.

**Comment by landreev** [comment]
The list of the 197404 database ids of the production files for which we ran the DOI registration script lives in 
/usr/local/dataverse-admin/files_unregistered_doi_datasets.txt
on dvn-cloud-app-1

The list of the DOIs registered for these files: 
/usr/local/dataverse-admin/files_dois_doi_datasets.txt

**Comment by landreev** [comment]
Status update: 
The registration script is running;  taking 1.4 sec. per DOI (this includes sleeping for 1 sec. between calls). 
The total number of the DOIs that needed to be fixed is ~200K; there's still >100K to go. Should be finished by the end of the week. 

I guess I'm just going to leave this issue parked in the dev. column until then - while I'm working on other things.

The script itself is very simple; it's based around a command line python script provided by EZID (https://ezid.cdlib.org/doc/ezid.py). 

Do we want/need to check in this script or otherwise pass it to the community? I'm guessing no - because I don't think anyone else has tried registering their DOIs for their legacy files yet (but please correct me if I'm wrong).

**Comment by pdurbin** [comment]
@landreev maybe you could attach the script in a comment on this issue. Please note that you might need to add ".txt" to the filename.

**Comment by landreev** [comment]
I ended up checking the scripts in, just in case they can be of some use to other members of the community.

**Comment by landreev** [comment]
The script has finished (on Sat.); all the ~200K registered datafile DOIs have been switched to public.

**Comment by djbrooke** [comment]
Thanks @landreev - what's needed to move this to done?
