### ISSUE TITLE
Investigate and fix if needed, bug in register single file api endpoint that leaves file dois as reserved.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4928]
When we retroactively registered file dois using the single file registration endpoint, it left them all as reserved.
@qqmyers fixed this bug for the batch, registerall endpoint in v4.9.2 but I am not yet sure whether it still exists in the single file endpoint. @qqmyers , do you know the answer? Also, how did you switch your dois from reserved to public in prod?

**Comment by qqmyers** [comment]
@kcondon - The fix is in the RegisterDVObjectCommand which is called by both the all files and single file API calls, so it should be fixed for both. 

For QDR, I added a limit argument on the register all call, so I only had a couple files in reserved, and just used the ezid website to update them. If someone has many reserved DOIs, I'm not sure what the best option is. I don't think it would be hard to do programmatically, but I think the existing endpoint will skip them all and not just do the publicize part.

**Comment by kcondon** [comment]
@qqmyers Thanks, that helps.
