### ISSUE TITLE
Data subset: Downloading data subset is not working for basic file in 4.9.2

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4933]
Downloading data subset for the basic file, 50by1000 works in prod for v4.9.1 but does nothing in v4.9.2, no errors.

Note that this functionality has some mixed success on more complex files but there the failure is up front with no variables displayed in popup: #2586

**Comment by djbrooke** [comment]
@scolapasta is investigating before sprint planning tomorrow. There is some inconsistency in how this is broken, at least:

- Shows variables in popup, download button opens a new tab with "untitled" https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/9UQTEY/WCXNZB
- No variables shown in popup, shows buttons, download button opens a new tab with "untitled" https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/CVBBDW/UNPCXB

I'm still unclear on whether or not there's a dependency on TwoRavens here. If there's a dependency on TwoRavens, we should remove this download option. If there's no dependency, we should fix this and allow the subsets to be downloaded (and remove the TwoRavens branding).

**Comment by djbrooke** [comment]
Let's remove this, it's available through Data Explorer. This will require removing the subset option button, the front end (we still will allow access through the API), and updating the docs with a pointer to Data Explorer.

**Comment by mheppler** [comment]
Wanted to look into this while I was seeing these ReferenceError's in my console.

![Screen Shot 2019-08-14 at 4 54 43 PM](https://user-images.githubusercontent.com/687227/63055607-4440d100-beb4-11e9-8a6b-2b258886f1c9.png)

I could fix the `fileid` variable by moving the three inline scripts linked at the top of gui_subset.xhtml to the bottom of page, just under the script tag that sets the `fileid` var.

However, that resulted in a different error logged in the console, this time a 503 (Service Unavailable) status was returned.

![Screen Shot 2019-08-14 at 4 57 39 PM](https://user-images.githubusercontent.com/687227/63055774-a568a480-beb4-11e9-9fa5-1a80dccb3a24.png)

I was able to copy and paste that datafile access api URL into the browser, and saw the same 503 error. However, if I removed the `?format=prep` query from the URL, the browser was able to access the datafile and it was automatically downloaded.

Hope that helps.

**Comment by landreev** [comment]
Yeah, format=prep means it tries to download that "preprocessed", TwoRavens-proprietary metadata format. It's not for subsetting itself. You're getting a 503 because - probably - you don't have rserve running.
We've gone through all this during the planning meeting - let's just lose this code. 
If we ever want/need to implement subsetting within the app, we'll do it without relying on that prep metadata.

**Comment by mheppler** [comment]
Started a new branch `4933-remove-subset` to remove the "Data Subset" option from the Download btn dropdown for tabular data files. Here is an out line of what has been removed so far, as well as few backend items that I was afraid to cut into. Hoping to convince @landreev to swarm on this, in order to make more precise deletions from complicated java beans.

- [x] /subset/
- [x] dataset, downloadDataSubsetPopup popup
- [x] file, downloadDataSubsetPopup popup
- [x] file-download-button, Data Subset dropdown option,
- [x] file-download-popup, download popup commandButton, 'subset' fileFormat
- [x] bundle, "Data Subset"
- [x] FileDownloadHelper.java, writeGuestbookAndOpenSubset function
- [x] GuestbookResponseServiceBean.java, SetDownloadType("Subset")
- [x] FileDownload.java, (removed subset from downloadType comments)
- [ ] DatasetPage.java, setFileMetadataSelected function
- [ ] Access.java, DownloadInstance > isTabularData > "subset" ... downloadInstance.getConversionParam().equals("subset")
- [ ] DownloadInstance.java, checkIfServiceSupportedAndSetConverter > "subset".equals(dataService.getServiceName())
- [ ] DownloadInstanceWriter.java, di.getConversionParam().equals("subset")
- [ ] (ALL THE GUIDES)

**Comment by landreev** [comment]
I'm guessing we only need to get rid of the code that was directly borrowed from TwoRavens; and the actual subset buttons from the UI. 
Most of the java beans you listed should not be messed with at all - that's the backend code that does the actual subsetting in the API. This is the functionality that we are keeping. 
I would keep the subset-specific code in the FileDownloadHelper as well - in case we ever want to put subset back into our UI.

**Comment by mheppler** [comment]
@landreev please feel free to remove any of the checklist items above that shouldn't be touched, or if my changes should be reverted.
