### ISSUE TITLE
Add extra information for mime type "text/comma-separated-values"

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#4943]
This is a 1-2 issue. 

Most CSV files are identified as "text/csv". But we also accept "text/comma-separated-values"  (as an ingestable format). 
However, we only keep a "pretty", display type for "text/csv". (the mime display type properties bundle needs to be updated). 
Also, we don't have a file extension mapping for this type. (this means if you download the original, or uningest, the filename extension "csv" will be lost). 

Alternatively we can change "text/comma-separated-values" to "text/csv" when saving the original file info in the db.

**Comment by mheppler** [comment]
Updating this for @landreev, as `text/comma-separated-values=Comma Separated Values` was added to MimeTypeDisplay.properties in commit 5a195376120e7b33073849456eb900dd7677eb8f on May 2, 2019 as part of #2202, released in 4.15.

**Comment by pdurbin** [comment]
In the context of Croissant, specifically comparing output from Kaggle vs (upcoming) output from Dataverse, @goeffthomas made this observation:

"I see an `encodingFormat` of `text/comma-separated-values`. Kind of curious about that since I think `text/csv` is more the MIME type that's on https://www.iana.org/assignments/media-types/media-types.xhtml and https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types "

I think he's right. `text/csv` seem much more common than `text/comma-separated-values` (1 million vs. 35k hits on Google respectively). Plus the specs above and https://en.wikipedia.org/wiki/Comma-separated_values all seem to point to `text/csv` being the preferred type.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
