### ISSUE TITLE
Loading image on myData page doesn't go away /Jquery .error() removed

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#4945]
Upgrading to 4.9.2 (with qdr mods) I noticed that the loading image doesn't go away on the my data page. Looking into it, it appears the this is due to an error in the check_card_images() method on mydata.js:
$(...).error is not a function on line 393: which tries to call $("img").error(). That error then breaks further JS calls, such as the one to load another page of results.

Looking into jquery, it appears that this method was deprecated and then removed in jquery 3. I suspect that the recent update to Primefaces 6.2 updated Jquery enough to trigger this, but I'm not sure.

I was able to fix this by changing to the recommended $("img").on("error", function()); form, which I can submit as a PR if you want. However:

- can someone confirm that this exists on vanilla 4.9.2 as well?
- the function is supposed to work on images that .hasClass('file_card_img') - I don't see any of these in my mydata page and https://github.com/IQSS/dataverse/issues/3616 suggests they may no longer be being generated (image_url triggers login in cards_minimum.html that would add this class) - so is the better fix to remove the check_card_images() function itself?
- I see .error() used in dropins.js and jquery.sharrre.js as well but don't know how/where to look for any errors from them. Anyone know how to test them? Is it wortha  pre-emptive switch to the .on("error", ... form? (.error is used in documentation as well, but maybe that still uses older jquery?)

**Comment by pdurbin** [comment]
@qqmyers https://demo.dataverse.org hasn't been upgraded to 4.9.2 yet but you're welcome to try it on http://phoenix.dataverse.org which is 4.9.2 plus whatever has been merged since 4.9.2 was released. It runs the latest code from the "develop" branch as described at http://guides.dataverse.org/en/4.9.2/developers/testing.html#the-phoenix-server

**Comment by qqmyers** [comment]
Thanks - so yes the problem exists on phoenix/4.9.2+

**Comment by pdurbin** [comment]
@qqmyers thanks. And thanks for the bug report! I do agree that perhaps the recent upgrades of PrimeFaces or Bootstrap/JQuery in Dataverse 4.9.2 could have caused this, but who knows. It sounds like you have a couple directions in mind for a fix. If it's quick to create multiple pull requests, please feel free to do so.

With regard to image_url, it looks like there's some related information in #3886 #3932 and #3714 but it's been a while since I've looked at any of this code.

**Comment by qqmyers** [comment]
Given that #3714 is considered a bug (liveable though...), it looks like retaining the check_card_images() method makes sense, so my PR just updates the jquery .error() call which fixes the MyDataPage.
