### ISSUE TITLE
Restrict/unrestrict on files with mixed state fails silently

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#4955]
Selecting a mix of restricted and unrestricted files and then selecting restrict or unrestrict causes a silent failure with no change in the state of files in either state. Selecting one file of each type and hitting unrestrict (which 'fails') followed by hitting restrict succeeds.

Looking at the code in DatasetPage, it looks like the set of files is considered valid if ANY of the files are the right type whereas the subsequent code fails with an exception if ANY file is the wrong state. I've committed a change that reverses the logic to consider the set of files invalid if any are of the wrong state. This causes the same popup that occurs if no files are selected, e.g. stating " Please select restricted file(s) to be unrestricted." or vice versa. It also appears to 'fix' the sequence of unrestrict and then restrict succeeding on a mixed set of files - both operations fail.

I think it would be possible to change this to go ahead and restrict any additional selected files that aren't currently restricted and vice versa for unrestrict. Between the change above being simpler and concern that having a mixed set selected might indicate a user error (unintended selection), I thought the more strict option might be better.

**Comment by pdurbin** [comment]
@qqmyers thanks for pull request #4956. I'm not super familiar with this code but I'd like to note that the last time this code was touched was 528b04d for #2861 so we should probably make sure the logic is still good for the "create dataset" workflow, since that's what that old issue was about.

I was curious about the "silent error", and I see what you mean. There's definitely a bug in here. When I selected two files, one restricted and one unrestricted, and clicked "Restrict", I got no feedback in the UI but saw this in Glassfish's server.log: `#{DatasetPage.restrictSelectedFiles(true)}: edu.harvard.iq.dataverse.engine.command.exception.CommandExecutionException: File carolina1.jpg is already restricted`. This was as of 5dbf025 on http://phoenix.dataverse.org

Moving to QA. Thanks again.

**Comment by kcondon** [comment]
@qqmyers When I test this I now get a popup asking me to please select files to be restricted/unrestricted rather than failing silently and no server log error, unlike before.

**Comment by qqmyers** [comment]
@kcondon Right - the message says "Please select <unrestricted/restricted> files to be <restricted/unrestricted>".  This is the same message as when you select no files, but it does explain what to do. If it is worth adding more messages, it could say "please select _only_..." or other, but I wasn't sure how to add more popups or to send the message as a param, etc.

**Comment by kcondon** [comment]
@qqmyers My bad, I scanned your initial comment and saw it was possible but missed the part where you decided not to. OK, will merge then
