### ISSUE TITLE
Publication year sort in search facets

### ISSUE THREAD

**Issue by philippconzett** [IQSS/dataverse#4977]
The publication years in the search facets on the left side of the Dataverse front page should be sorted chronologically; cf.
![image](https://user-images.githubusercontent.com/21955790/44321405-24650180-a448-11e8-8670-20c403c9e7b7.png)

**Comment by pdurbin** [comment]
@philippconzett yes, I agree. Or at least I agree that something should be done with this facet. I hadn't thought of simply changing the sort order, which I hope wouldn't be too tough. #70 was opened four years ago and has some discussion about more radical UI changes that we haven't gotten around to. Thanks for the suggestion! My only concern is that the user experience will be a little less experience because the facets are sorted by "count" but it's a worse user experience for dates so maybe that doesn't matter.

**Comment by philippconzett** [comment]
@pdurbin Thanks! I just noticed similar behavior in other date field, e.g. Time Period Covered:
![image](https://user-images.githubusercontent.com/21955790/46676862-acae8a00-cbe1-11e8-9f21-14812d70fd4a.png)

**Comment by TaniaSchlatter** [comment]
Ideally "Time Period Covered Start" would display oldest year first, and "Time Period Covered End" would display most year first. User feedback and strong UI convention support chronological display as default, especially in this case as recent years may be hidden.
