### ISSUE TITLE
Upgrading DV 3.6 to 4.x and Merging to existing 4.8

### ISSUE THREAD

**Issue by bikramj** [IQSS/dataverse#4996]
We’re looking at upgrading the contents of an old Dataverse installation running version 3.6 to new Dataverse 4.8 installation. We had already upgraded our production 3.6 installation to 4.2, but in this case, we are looking into Merging Two Dataverse instances to One after upgrade. 
We’re wondering if there are any existing scripts or migration strategies that we should follow as best practices or if this idea of merging two instances into One is feasible or not!

**Comment by djbrooke** [comment]
@janetm @mdmada - I remember that you were regularly moving content from one Dataverse 4 instance to another. Are there any tools or scripts that you can share?

**Comment by mdmADA** [comment]
Hi - We haven't merged data of 2 different productions dataverse instances so I am afraid we can't offer any guidance or advice.


- M.

________________________________

**Comment by bikramj** [comment]
Thank you @mdmADA, so we are not sure at the moment if someone has already tried merging 2 instances into one!

**Comment by pameyer** [comment]
@bikramj I haven't tried it, but the import API (`$SERVER_URL/api/dataverses/$DV_ALIAS/datasets/:import`) *should* allow merging two dataverse instances by exporting all of the datasets from one dataverse, and importing them into the other.  So that might be an approach to look into, although it would probably need some additional scripting to handle migrating the dataverses and making sure that the datasets ended up in the correct dataverse.

**Comment by djbrooke** [comment]
I'm going to close this issue since it's a bit older, but if there's further interest in moving content from one dataverse installation to another (or from other repositories) there's been work in https://github.com/AUSSDA/nesstar2dataverse_datamigration and https://github.com/AUSSDA/pyDataverse that may be useful for similar situations.
