### ISSUE TITLE
TwoRavens warning after 4.8.6 upgrade

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#5003]
TDL just upgraded to 4.8.6 (with some resource leak patches) and following the 4.8.6 upgrade instructions to add &gbrecs=true to the dataurl for two ravens causes tworavens to show a warning:
"Warning: The request is not valid json. Check for special characters."
before showing the data. 

I checked on demo with https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.5072/FK2/TKBGPT - it doesn't show the error but checking the console shows that demo is not set up with &gbrecs=true. I think this step is no longer needed as of 4.9 when the double counting issue was solved, but, if so, the release notes should tell people to revert this change?

(I don't have a 4.9.2 with tworavens running to test if the warning shows up with &gbrecs=true appended or if its silent now, but seems like it should be dropped as people upgrade).

**Comment by qqmyers** [comment]
Just verified that this is an issue in the develop branch as of this week (just before 4.9.3 release). To resolve, I think the 4.9.3 release notes should just say to revert the change from 4.8.6 if it was done.

**Comment by pdurbin** [comment]
@qqmyers sorry, I'm confused. Revert a change having to do with `&gbrecs=true`? In the Java code? Most installations just deploy the war file as-is, I believe, without hacking on the code and compiling their own war file.

**Comment by qqmyers** [comment]
@pdurbin - The release notes for 4.8.6 tell you to edit app_ddi.js in the /var/www/html/dataexplorer/... and if you did that and are now on v 4.9+, you'll get a warning. The newer Dataverse java code no longer needs &gbrecs=true in the app_ddi.js file to avoid duplicate download counting, so if you revert to what it was before v 4.8.6, the warning is gone and all is good.

**Comment by pdurbin** [comment]
Ah, weird. So the fix is just to tweak the release notes? That sounds easy. You're making me wish our release notes were in git so you could make a pull request and I could move this to code review. I guess for now I'll put it in "community dev" to get it out of the inbox at https://waffle.io/IQSS/dataverse

**Comment by qqmyers** [comment]
@pdurbin - yep. Although I think it applies back to 4.9, just adding something about it to the 4.9.3 notes would be good.

**Comment by landreev** [comment]
@qqmyers Sorry this has taken so long. 
For the record, you DON'T want to remove that "&gbrecs=true" part of the URL; it wasn't a temporary fix, it's something that is needed going forward, since the original count bug has been fixed in 4.8.6 and the TwoRavens "explore" sessions are now properly counted on the Dataverse side. So without the gbrecs flag set by TwoRavens the download count will get incremented by 2. 

At the same time - you are absolutely correct, in that the unencoded "&" in that URL is indeed generating that JSON warning (at least with some browsers). So the real solution appears to be something like: 

ATTENTION: If you are running TwoRavens as part of your Dataverse installation, please find the following line in your TwoRavens app_ddi.js file:

```
dataurl = dataurl+"?key="+apikey+"&gbrecs=true";
```
(or, if you are using an older version, it may look like this:)
```
dataurl = dataurl+"?key="+apikey;
```
and change it as follows:
```
dataurl = dataurl+"?key="+apikey+"%26gbrecs=true";
```
(this ensures that the download counts are properly incremented for TwoRavens explore sessions, and eliminates the confusing "Warning: The request is not valid json. Check for special characters" messages that some users were seeing after the 4.8.6 upgrade)

So I'm adding the above to the 4.9.3 release notes.
Thank you for pointing this out to us...

**Comment by landreev** [comment]
OK, done. 
@qqmyers @kcondon - I've added that blurb (above) to the end of the 4.9.3 upgrade instruction. Please let me know if you think it should be made more prominent - ? 

(since there's no code, this is going directly into QA)

**Comment by qqmyers** [comment]
@landreev - glad I could help by suggesting the wrong fix, when I was involved in investigating the double counting to start with. :-) Thanks for documenting the correct fix - it looks good.
