### ISSUE TITLE
Better Logo for "Powered by Dataverse Project" in Footer

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#5009]
The image is pixelated on my Mac laptop. Attaching a screenshot and the image itself. Can we use a higher quality image or use some format that's less prone to pixelation?

![dataverseproject_logo](https://user-images.githubusercontent.com/7773392/44794952-97bcf080-ab77-11e8-8529-ea6b19ca8182.png)

<img width="313" alt="screen shot 2018-08-29 at 10 34 02 am" src="https://user-images.githubusercontent.com/7773392/44794855-5e848080-ab77-11e8-8555-177e837419a9.png">

**Comment by pameyer** [comment]
I'm relatively sure there's an SVG version floating around somewhere.  I'm not 100% sure about browser support for SVG; but SVG with PNG fallback is relatively straightforward.

**Comment by pdurbin** [comment]
Yes, there's an SVG version at https://github.com/IQSS/dataverse/blob/v4.9.2/doc/sphinx-guides/source/_static/dataverse_project_logo.svg

**Comment by mheppler** [comment]
Much better! Thanks, @matthew-a-dunlap for tackling this one.

![screen shot 2018-09-20 at 5 14 55 pm](https://user-images.githubusercontent.com/687227/45847421-fb5eb780-bcf8-11e8-8db2-c24a3cb2e89e.png)

**Comment by pdurbin** [comment]
Yes, looks better but I'll go ahead and repeat my comment from our sprint planning meeting yesterday that it makes more sense to me to say that an installation of our software is powered by Dataverse rather than powered by the Dataverse Project. The software is called Dataverse. We don't call the software "The Dataverse Project".

There's a doc from 2014 called "Naming Things" at https://docs.google.com/document/d/1McDaVmiHWe_w-QBsLYLPJdRP2X4P6vWr6qQcdInEK8Y/edit?usp=sharing that captures a conversation some of us had back then about the things that need names:

* The project
* The software
* Harvard's installation of the software
* Other installations of the software (they name these)
* Virtual data archive (i.e. Gary King Dataverse, Murray Dataverse)
* Multiverse? Harvesting. Federation. Search index across all installations.

Some of this has been figured out. For example, these days Harvard's installation of the software is called "Harvard Dataverse". Great. Other installations have names like "LibraData" or "Scholars Portal Dataverse." As far as I understand, the software is called Dataverse. Dataverse is what powers an installation.
