### ISSUE TITLE
Citation - Unicode ® + Emojis 🍔

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#5020]
(Full disclosure: I am sure there is a real world case about supporting unicode characters in the dataset citation, but I am not able to come up with one at the moment.)

When I [copy and paste an emoji](https://emojipedia.org/emoji/%F0%9F%8D%94/) into the dataset title, it displays properly in the beadcrumbs, title header and metadata, but not in the citation.

![screen shot 2018-09-05 at 3 27 09 pm](https://user-images.githubusercontent.com/687227/45116482-dbd46600-b120-11e8-8f05-2b7213ed8e25.png)

In case you were curious -- as I was -- ASCII displays fine.

![screen shot 2018-09-05 at 3 33 10 pm](https://user-images.githubusercontent.com/687227/45116532-04f4f680-b121-11e8-8c02-98d0ec86278a.png)

**Comment by mheppler** [comment]
Related to #4077.

**Comment by mheppler** [comment]
Sorta related... EMOJI's 😝... **UTF-8 characters in filenames not handled correctly in normal downloads #7188**

**Comment by JoaoMFCardoso** [comment]
Hi,
I've been trying to add some mathematical expressions as part of the descriptions of a costumized metadata block. However I'm struggling with getting the greek letters to be displayed.

Maybe this is the real world case for that unicode support.

One of my trial expressions is the following:
"standard score (x1 -  μ  ) /  σ  , where  μ  = mean and  σ  = standard deviation"

with unicode encoding:
"standard score (x1 - U+03BC) / U+03C3, where U+03BC = mean and U+03C3 = standard deviation"

Is there any way to circumvent this at the moment?

**Comment by pdurbin** [comment]
@JoaoMFCardoso I guess I'm confused. What if instead of entering something like `U+03BC` you type or copy the Unicode character in directly.

For example, here's me editing the description and adding Unicode characters:

![Screen Shot 2022-04-29 at 4 31 33 PM](https://user-images.githubusercontent.com/21006/166065467-fbd9d5da-8b78-402d-8371-1acd279a1fe8.png)

And when I click save, the Unicode characters seem to look ok:

![Screen Shot 2022-04-29 at 4 31 55 PM](https://user-images.githubusercontent.com/21006/166065476-65f2172e-0f41-41d0-9e0d-ee0fa71d9e1c.png)

**Comment by pdurbin** [comment]
@JoaoMFCardoso hi! Did my reply help? Are you still interested in this?

Either way, I'd be ok with closing this in favor of the following issue:

- #7375

**Comment by pdurbin** [comment]
Closing. For math support, please open a fresh issue. Related: https://groups.google.com/g/dataverse-community/c/7K0p4Gl4UvU/m/inG0oH4EAwAJ
