### ISSUE TITLE
Move dataverse.harvard to DataCite

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#5024]
Non-U of California Dataverse installations will no longer be able to use EZID to mint DOIs (https://www.cdlib.org/cdlinfo/2017/08/04/ezid-doi-service-is-evolving/). 

This issue will be done when dataverse.harvard is using DataCite to mint DOIs and when the community is provided relevant documentation to support their own moves. This should include editing current parts of the documentation that reference EZID.

Migration Guide: https://docs.google.com/document/d/1rsjFl6CvyiGaCE1SMpougZaFc135oBV_CkypoQx9x8g/edit

**Comment by pdurbin** [comment]
What I was trying to say at standup is that the reason why Dataverse developers all over the world are able to publish datasets in the dev environment is that EZID credentials are included in our installation process. Both the username and password are "apitest" as shown below. As part of this effort, do we remove these EZID credentials from the installation process? If so, what will they be replaced with? How will developers publish in the future? Something needs to change once EZID stops working for real. (When is the drop dead date anyway?) Will developers be forced to apply individually for DataCite credentials? Should they set up a Handle server? Should we ask DataCite for shared credentials like we've had for EZID? Should we create a FakePersitentIdProvider (that extends AbstractGlobalIdServiceBean) that developers use so that they don't have a dependency on a third party service?

```
$ ack apitest scripts
scripts/installer/glassfish-setup.sh
70:  ./asadmin $ASADMIN_OPTS create-jvm-options "\-Ddoi.password=apitest"
71:  ./asadmin $ASADMIN_OPTS create-jvm-options "\-Ddoi.username=apitest"
```

**Comment by landreev** [comment]
I actually like the idea of a fake persistent id provider, that could be enabled by default. 
In the short term, we should just change the installer to use DataCite by default; and adding some lines to the guide and the installer output, saying "if you are developer or tester, and you're not planning on buying a "real" global id namespace, go to DataCite in order to register for a test account. Until you do, you're not going to be able to publish datasets". 

We no longer have a system wide option for disabling global id registration, do we? 

I would not recommend setting up a handle server as the default installation scenario; that would be an unjustified amount of extra work, for a developer's system. 

But yes, let's open a dedicated issue for this (if hasn't been opened yet) and discuss this some more.

**Comment by landreev** [comment]
@scolapasta  
The issue of the "reserved" dois came up during the migration meeting we had earlier. The EZID people had specifically told us "you have a very large number of the dois that are reserved; do something about them before you migrate". 
So most of that "large number" must have been the dois of the published file, that got registered as reserved by mistake. I have converted them to public by a script since then (there was a separate issue). 
And for the remaining reserved ids of the unpublished draft datasets, did we agree to just go ahead and delete them w/ EZID by another script, on the day we migrate? - please confirm. The alternative is not to do anything about them at all; they are known  to EZID only, so migrating to DataCite will achieve the same result - they will be as good as deleted... But then we'll probably be receiving more warnings from EZID about them.

**Comment by landreev** [comment]
@djbrooke @scolapasta 
I tried to finalize the checklist of the remaining tasks for the migration; one question I still have - do we already have the account/credentials w/ Datacite, or have we already applied for one? Or is this still something that needs to be done?

**Comment by djbrooke** [comment]
@landreev - I have them, will share.

**Comment by scolapasta** [comment]
@landreev yes we should delte them with EZID on the day we migrate

**Comment by mfenner** [comment]
DataCite is happy to give credentials to the DataCite test system to everyone who asks for that, but we would not be happy with a standard test account and no password as EZID is doing. 

Even better: we have an API to create client accounts, so someone can automate this on behalf of the Dataverse consortium for the test and/or production system for DOI registration.

Martin (DataCite Technical Director).

**Comment by mfenner** [comment]
We are of course very interested in providing a nice developer experience with Dataverse.

Another issue that you might look at at some point (and in a different GitHub issue) is that DataCite has developed a new API for DOI registration. No reason to switch to that API now, but medium-term that is something to consider. Main advantage is that it is a JSON REST API :), and the MDS and EZ APIs are actually layered on top of that API.

**Comment by jonc1438** [comment]
I can not speak for Harvard studies but Odum has about 407 or so "Draft" studies that are assigned Draft DOIs with EzID. These can not just be deleted and not reassigned. Once the migration happens we will have to re-register them as drafts DOIs with DataCite. So we will need to track them so we do not lose DOIs in the process.

**Comment by landreev** [comment]
@mfenner It was already our working assumption that a DataCite-like shared test account was not an option. But thank you for chiming in and confirming.

**Comment by jonc1438** [comment]
Just a note too that after talking to EzID last week they gave us unitl Jan 1st to migrate all the GDCC DataCite Agents off EzID

**Comment by landreev** [comment]
@jonc1438 The thing about the DOIs of the draft datasets is that the concept of a "reserved" DOI is a proprietary DataCite-only feature. As their (DataCite's) migration document reminds us: "*Reserved identifiers cannot be migrated! They are “known” only to EZID.*" When your Dataverse is configured to use DataCite, the DOI of a newly-created, not-yet-published draft dataset only exists in the local database; and gets registered as a resolvable global id only when the dataset gets published. When we (Harvard and you) migrate to DataCite, we are simply moving to this model for all the DOIs currently reserved for our draft datasets. We are not assigning new DOIs to them, we'll keep the existing ones in our databases - but they will only be "officially" registered when/if these drafts get published. When Dataverse generates new ids for new datasets, it checks them for uniqueness against the ones already in the database - so this ensures that no other dataset will get one of the existing ids; even though they are not reserved on the provider side. 

(being able to reserve ids like that with EZID was still somewhat useful; it was then possible for, say, 2 Dataverses with separate databases to use the same name space, and still be guaranteed to avoid potential conflicts over the identifiers... but you're not sharing your name space like that, correct?)

**Comment by landreev** [comment]
(for the life of me I cannot talk about "DataCite" and "EZID" without mixing up the two; I did that in the first draft of the comment above - but have since corrected it; so it should the correct in its present form. I think)

**Comment by jonc1438** [comment]
Ok that makes sense when DataCite did not have "draft" DOIs but now they do. 

Does that mean once the study is published a second check against the DataCite server happens to be sure another group has not used the DOI Dataverse is holding locally.

The question we need to ask the community is should the "draft dois" be only in Dataverse or should they get registered? ie Does the public registration of draft DOIs get you anything?

**Comment by landreev** [comment]
"but now they do" - are you saying that DataCite has a concept of a draft/reserved identifier now? I wasn't aware of that.

**Comment by jonc1438** [comment]
yep

Yes, the "draft" DOIs provided by DataCite have basically the same functionality as EZID "reserved" DOIs. What we can't do though, is automatically transfer EZID "reserved" DOIs to DataCite, this has to be done manually. And DOIs in "registered" or "findable" state can't be turned back into "draft" DOIs.

Registering "draft" DOIs is easy with DOI Fabrica and the EZ API. And with the MDS API you simply omit the second API call to register the DOI in the handle system.

Let DataCite staff know if there are any questions about this.

Best,

Martin

**Comment by landreev** [comment]
Status update: 
I checked in a README file documenting the migration process (mostly with other Dataverses who will need to migrate as well in mind). 
We are NOT migrating on Oct. 8 after all - the date is not going to work for the DataCite staff. They offered Oct. 4 or 5 as "significantly easier" dates for them. So let's discuss and confirm.

**Comment by pdurbin** [comment]
@landreev I reviewed 18efd94 and it makes sense. I'd say you should feel free to make a pull request since the instructions are a nice addition we may well want to link to some day.

**Comment by landreev** [comment]
Yes, there's now a PR #5113. Whether this is something we want to merge now, or wait till we actually migrate - not sure. 
I feel we should wait till we are done with the actual migration - since it is possible we will run into something unexpected, that requires extra fixes that may need to be documented.

**Comment by pdurbin** [comment]
@landreev sure, that make sense. We might make a commit or two to that README based on lessons learned. Thanks for making the pull request.

**Comment by landreev** [comment]
The migration has been carried. I've added all the details to the README in the PR, including the time it took and the curl and asadmin commands involved. 
AND our old EZID account (CDL.DATAVERS) has already been removed! - that's efficiency.

**Comment by pdurbin** [comment]
> Should we create a FakePersitentIdProvider (that extends AbstractGlobalIdServiceBean) that developers use so that they don't have a dependency on a third party service?

See #5327
