### ISSUE TITLE
API test suite failing for "develop" branch post 4.9.2

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#5025]
I just ran the API test suite on the "phoenix" server and according to https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/ sometime between August 24th (df3e31f) and September 6th (d149475) the API test suite started failing. Here's a screenshot:

![screen shot 2018-09-06 at 2 46 56 pm](https://user-images.githubusercontent.com/21006/45178530-f6bbde80-b1e3-11e8-8cb3-5588ff0afd5e.png)

The phoenix server is described in the Dev Guide at http://guides.dataverse.org/en/4.9.2/developers/testing.html#the-phoenix-server

**Comment by matthew-a-dunlap** [comment]
They are all related to the changes in #4565 around builtinuser.

**Comment by pdurbin** [comment]
Pull request #5036 looks good to me. Moving to QA. @matthew-a-dunlap will be adding some testing notes.

**Comment by matthew-a-dunlap** [comment]
Half of the reason the IT tests were failing is due to the IT Tests looking for email in builtinuser, when it no longer lives there. 

The non-test changes were to:
1. Fix api endpoints for account conversion to look for the returning email from the right place.
2. Fix the authenticatedUser to strip leading/trailing spaces, which we supported already with builtinuser.

Testing this means confirming that both of these two pieces of code work as expected. Also maybe try changing a password and another basic account test or two to around email.
