### ISSUE TITLE
Support for SHA-256 and SHA-512 with update option

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#5033]
Related to #4706 - Support stronger hashes to be compatible with recommendations from the Digital Preservation Network (DPN) - SHA-256 - and Research Data Alliance (RDA) - SHA-512. Adding these two algorithms as options and creating an admin API to update between algorithms (run through all files and for those with hashes form the old algorithm, verify the content against the hash, compute the has with the new algorithm, and replace the hash/algorithm for the file).

**Comment by pdurbin** [comment]
@qqmyers we touched on this issue and your pull request #5035 very briefly at standup this morning. I said we should probably think a little more about what you're trying to achieve. It's probably fine, but we just want to understand it better.

**Comment by landreev** [comment]
@qqmyers 
We have actually missed a couple of things that need to be added: 
1. Harvested files. A "harvested file" is a metadata-only entry in the database, with no physical bytes of data available locally. So we should skip these; with a simple extra check - something like 
```
if (!df.isHarvested() && !df.getChecksumType().equals(cType)) {
...
```
This is not fatal as is; the end result will be the same - the harvested files end up skipped, as we fail to open byte streams for them; but it pollutes the logs with "getDataAccessObject: exception..." messages, and wastes CPU cycles. 

2. Tabular files need special treatment. This is because the checksum stored in the database describes the *original file* that was uploaded by the user (a data file in a proprietary format - Stata, SPSS, R, etc.); and not the current main physical file - which is the data converted to tab-delimited format. As currently implemented, the checksum algorithm tries to verify the old checksum and fails. 
So we want to be doing something like
```
if (!df.isTabularData()) {
   in = storage.getInputStream();
} else {
   // if this is a tabular file, read the preserved original "auxiliary file" instead:
   in = storage.getAuxFileAsInputStream(FileUtil.SAVED_ORIGINAL_FILENAME_EXTENSION);
}
```

(why do we do this? - we want to keep the checksum of the actual file uploaded by the user; for integrity/archival purposes. and for the purposes of maintaining the integrity of the generated tabular file we rely on the UNF signature. why do we handle the generated tabular file as the main payload of the datafile, and the preserved original as an "auxiliary", and not the other way around? - this question comes up once in a while, but it's more or less an issue of legacy by now, that we don't want to break)

**Comment by qqmyers** [comment]
@landreev -thanks - good catch - these issues also affect creating a Bag in #4706. This PR is now updated to skip harvested files and handle tabular ones. And remerged with dev. Should be good again.

**Comment by landreev** [comment]
@qqmyers  Looks great - moved it back into QA.
