### ISSUE TITLE
Add a "private" command to delete a published dataset

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#506]
---

Author Name: **Michael Bar-Sinai** (@michbarsinai)
Original Redmine Issue: 3921, https://redmine.hmdc.harvard.edu/issues/3921
Original Date: 2014-05-05
Original Assignee: Gustavo Durand

---

Used for testings, etc.
Called "Destroy" in 3.6

**Comment by scolapasta** [comment]
@michbarsinai So I don't think we need this under the secure API since the destroy command is already protected by a superuser check (only for released; for not released, it will just delete, assuming you have that perm).

So I added it to the datasets API with this path:
Path("{id}/destroy")

What do you think? So a user could try to delete with just id, but if released, then (assuming superuser), they just have to add /destroy

I'll pass you you for comment, if you're OK with this then we can just pass to QA.

**Comment by michbarsinai** [comment]
Makes sense.

**Comment by kcondon** [comment]
This does not work. As super user, user /destroy and got this error:
{"status":"ERROR","message":"Destroy dataset 2413 unauthorized."}

**Comment by scolapasta** [comment]
Taked with @kcondon and somehow admin user was not a superuser. So he will retest.

**Comment by kcondon** [comment]
OK, still doesn't work:
{"status":"ERROR","message":"Destroy dataset 31: Bad Request (Cannot delete a released file)"}

Verified deleting an unpublished version works with same command line without /destroy. Did notice command is case-sensitive, so DELETE works, delete fails.

**Comment by pdurbin** [comment]
I'm getting the same result when trying to work on indexing in #1316. I can't destroy a dataset with files:

`curl -X DELETE http://localhost:8080/api/datasets/10/destroy?key=$ADMINKEY`

```
{
  "message": "Destroy dataset 10: Bad Request (Cannot delete a released file)",
  "status": "ERROR"
}
```

Is this by design? Should I be able to destroy a published dataset with files?

**Comment by scolapasta** [comment]
As long as you haven't linked to the dataset this should now be working. Issue #1446 tracks the case of not being able to destroy a dataset that has been linked.
