### ISSUE TITLE
Implement ability to reserve DOIs through DataCite

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#5093]
Datacite has added the ability to reserve DOIs pre publish (as EZID did). This ticket will track adding the ability to reserve those DOIs when we create datasets, as well as a one time ability to reserve DOIs for existing drafts that have only reserved their DOIs on the dataverse side.

**Comment by poikilotherm** [comment]
This could be a better approach than using multiple providers as we had planned first in #4833 and #5082. Private drafts seem to be a proper fit for our use case, even so they won't be resolvable until "registered". (Scientist could share a Dataverse installation URL instead for collaboration...)

Do you guys think this is a good topic for a community contribution?

**Comment by poikilotherm** [comment]
(That was a quick and comprehensive answer, @pdurbin :wink: )

**Comment by pdurbin** [comment]
@poikilotherm heh. Thanks for chatting at http://irclog.iq.harvard.edu/dataverse/2018-10-10

As I mentioned there @sekmiller and I talked about it and we don't think the refactoring he's working on for #5060 will conflict.

We are, of course, available to answer any questions.

Thanks for linking to https://support.datacite.org/docs/doi-states which explains the new feature, listing three states:

- Draft DOIs
- Registered DOIs
- Findable DOIs

We're pretty sure that we'd want DOIs to go straight from "draft" to "findable" so that they're indexed in DataCite Search.

**Comment by poikilotherm** [comment]
To be more complete, I should mention that these states are [not usable via the XML based MDS API](https://support.datacite.org/docs/doi-states#section-doi-states-outside-of-fabrica), but via the [REST API](https://support.datacite.org/docs/api#section-creating-dois) and EZID API.

This could be a big blocker, because that means changing the whole code of `DOIDataCiteServiceBean` currently using the MDS API.

As it seems that @sekmiller wrote huge parts of the class: any ideas how to tackle this?

**Comment by pdurbin** [comment]
@poikilotherm as promised, I mentioned this issue at standup. Thanks for linking to https://support.datacite.org/docs/doi-states#section-doi-states-outside-of-fabrica which gives details on your assertion that we can't use the old DataCite API for this:

![screen shot 2018-10-10 at 12 00 18 pm](https://user-images.githubusercontent.com/21006/46749674-3a42b600-cc84-11e8-8ee6-8e4da4a811c9.png)

The vibe I got from @scolapasta and @sekmiller is that we certainly wouldn't mind if you poke around with the new DataCite API and report back any interesting findings!

**Comment by pdurbin** [comment]
@poikilotherm hi! Are you actively working on this? Do you still want to be assigned to it?

**Comment by poikilotherm** [comment]
No I am currently concentrating on "getting things testable".
I don't mind being assigned, as this is definitly a feature we need for FZJ and will be done once we have a prod setup done.

**Comment by poikilotherm** [comment]
Status update: we still will need this down the road, but concentrate on getting things moving to production currently.

**Comment by djbrooke** [comment]
We'll visit this in a tech hour. This is perhaps more than just adding the ability to reserve DOIs, but could also mean that we need to switch to the new DataCite API (json based vs xml based)
