### ISSUE TITLE
migrate endpoint throws a 404

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#5138]
Verified by Phil, and seemingly introduced at some point after 4.8.6:

`$ curl http://localhost:8080/api/batch/migrate` returns

{"status":"ERROR","code":404,"message":"'/api/v1/batch/migrate' endpoint does not exist on this server.

If this was intentional, please disregard and close. The 404 seemed to take Phil by surprise, though, so I'm dutifully opening an issue.

**Comment by pdurbin** [comment]
http://irclog.iq.harvard.edu/dataverse/2018-10-04#i_74736 has some details the important chatter from my perspective:

> hmm, I'm getting the same error: "message": "'/api/v1/batch/migrate/' endpoint does not exist on this server
> when I run `mvn test -Dtest=BatchImportIT` on a server running 4.9.4

As of b8090f0 that BatchImportIT test was working (Dataverse 4.9) but this test isn't in the list of tests on phoenix because it doesn't work over the network. This is because that "migrate" code operates on local files on disk. So I don't know when it "migrate" stopped working.

**Comment by donsizemore** [comment]
update: I've found that the migrate endpoint answered on a 4.9.1 deployment, but threw a 404 in 4.9.2. 109 closed issues in that milestone; i'll try to poke through them this evening or tomorrow.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
