### ISSUE TITLE
installer: make datacite url and credentials config_variables

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#5173]
c.f. https://github.com/IQSS/dataverse/blob/develop/scripts/installer/glassfish-setup.sh#L69 and https://github.com/IQSS/dataverse/blob/develop/scripts/installer/install#L57

would streamline the install process a bit. pull request forthcoming.

**Comment by pdurbin** [comment]
I didn't test it but pull request #5188 makes sense to me. Off to QA. Thanks, @donsizemore !

I guess I'll note that `doi.baseurlstring` and related fields also apply to EZID so we could consider changing the variable name from "DATACITE_BASEURL" to "DOI_BASEURL".

**Comment by pdurbin** [comment]
As of a354f35 the variables have been renamed so the pull request looks even better. Thanks again, @donsizemore

**Comment by pdurbin** [comment]
I can reproduce this with `vagrant up` as of a354f35

==> standalone: String found where operator expected at ./install line 116, near "'DOI_BASEURL'    'https://mds.test.datacite.org'"
==> standalone: 	(Missing operator before     'https://mds.test.datacite.org'?)
==> standalone: syntax error at ./install line 116, near "'DOI_BASEURL'    'https://mds.test.datacite.org'"
==> standalone: Execution of ./install aborted due to compilation errors.
==> standalone: If vagrant up was successful (check output above) Dataverse is running on port 8080 of the Linux machine running within Vagrant, but this port has been forwarded to port 8888 of the computer you ran vagrant up on. For this reason you should go to http://localhost:8888 to see the Dataverse app running.
murphy:dataverse pdurbin$ 

It looks like a comma was missing so I added it in bd78384

I'm sending this back to QA but I'll pull it out if `vagrant up` fails.

**Comment by pdurbin** [comment]
Ok, `vagrant up` is fine as of bd78384 . I get a working Dataverse installation on http://localhost:8888
