### ISSUE TITLE
Metadata Customization : add a note about setup

### ISSUE THREAD

**Issue by rmo-cdsp** [IQSS/dataverse#5205]
Add a note in the Metadata Customization part in the guide about the way the dataset fields are setup in the app. Thanks to @pdurbin , I now know that the script https://github.com/IQSS/dataverse/blob/v4.9.4/scripts/api/setup-datasetfields.sh , used by the installer script, define this. This information may be useful in the guide to understand this.

**Comment by pdurbin** [comment]
@rmo-cdsp thanks for opening this issue! As we discussed at http://irclog.iq.harvard.edu/dataverse/2018-10-17 this information is not currently in http://guides.dataverse.org/en/4.9.4/admin/metadatacustomization.html

The file to edit is https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/admin/metadatacustomization.rst

**Comment by pdurbin** [comment]
For anyone picking this up, please see #5164 for examples of the struggles people have when trying to make even simple changes to the tsv files. We might want to include a troubleshooting section.

**Comment by pdurbin** [comment]
I mentioned at https://groups.google.com/d/msg/dataverse-community/9TNH41iGgG8/SZZaPbdvCwAJ that I was working on this issue and just created pull request #5251 and moved this to code review. Feedback is welcome!

@matthew-a-dunlap and I discussed how rather than documenting a fix we need for http://localhost:8080/api/admin/index/solr/schema to produce the right output ("_text_" instead of "text") that we should just fix it so I did. Everything else is docs and comments.

**Comment by sekmiller** [comment]
Looks good in general. Discussed some of the quirks with @pdurbin.

**Comment by pdurbin** [comment]
My to do list (will edit this comment for clarity in a bit):

- [ ] out of sync google docs compared to tsv files in repo
- [ ] order of fields by column (abovefold doesn't matter)
- [ ] reloading
- [ ] Jim's additions to the old doc: http://irclog.iq.harvard.edu/dataverse/2018-10-31#i_77364

**Comment by pdurbin** [comment]
Ok, as of d33b2aa I'm done hacking on this branch. I'm ready for more code review.

**Comment by pdurbin** [comment]
It would be easy to roll a fix for #3976 into the pull request if there's interest.

**Comment by pdurbin** [comment]
I'd like to explain the two code changes in the pull request.

First, in d9adf2b I documented an API for learning more about metadata fields which has existed since 4.0 (undocumented) and adjusted the API to provide information about controlled vocabulary values.

The second change is basically a bug fix. In the "Updating the Solr Schema" section of the main doc in the pull request I explain the curl command for getting Solr fields out of Dataverse to put into schema.xml. For Solr 4 the "catchall" field was `text` but for Solr 7 it's now `_text_` so now the curl command output the correct field name.
