### ISSUE TITLE
"File access requested" notification : link not available in french

### ISSUE THREAD

**Issue by rmo-cdsp** [IQSS/dataverse#5226]
Hello !

I can resume the problem with two pictures:
![screenshot from 2018-10-23 16-00-45](https://user-images.githubusercontent.com/14806890/47372052-3fbee800-d6e9-11e8-956a-c50837361355.png)
![screenshot from 2018-10-23 16-01-03](https://user-images.githubusercontent.com/14806890/47372055-4188ab80-d6e9-11e8-8992-391760dc0f76.png)

On the first one, you can see the user notification page with some "File access" notifications, with a link to the dataset.
On the second one, you can see the same page, but in french. But there is no link, just a {0}. I assume something went wrong when trying to retrieve the url to the dataset.

**Comment by mhvezina** [comment]
Could it be related to the non-escaping of the apostrophe in the French text? (Also there seems to be one apostrophe missing between "d" and "accès" in your example). 
We ran into something similar. Try to escape all aportrophes... maybe with something like "Demande d''accès pour l''ensemble de données : {0}."

**Comment by pdurbin** [comment]
@mhvezina maybe! Are you interested in working on a pull request? 😄

**Comment by mheppler** [comment]
@rmo-cdsp thank you for catching and reporting this issue. As of the 4.13 release (#5720), we have changed how the various language bundle are added to the application. The English bundle is the only language included with the app, and the other languages have been moved to a new [dataverse-language-packs](https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs) repo.

I am going to close this issue, since there is no longer a code fix that applies to the current Dataverse version, and have opened a new issue in that repo at https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs/issues/29. You can track the progress of this bug fix with that new issue.

@mhvezina, thank you for your comments here and suggesting a fix. I was able to confirm this solution in my local dev environment.
