### ISSUE TITLE
File access request API

### ISSUE THREAD

**Issue by bappun** [IQSS/dataverse#5229]
Through the API, being able to:
- list access requests for a file
- grant access to a file for a specific user
- deny access to a file for a specific user

I think it could be also great to have an API to list all requests inside a dataverse, a dataset and maybe for all the files of a user (all files for which he has permission to manage requests).

Dataverse Community discussion:  https://groups.google.com/forum/#!topic/dataverse-community/PY7uz6cg8vQ

**Comment by djbrooke** [comment]
We should build the ability to request access for a file using the API as part of this as well.

**Comment by pdurbin** [comment]
I left a review on pull request #5309 and discussed it with @sekmiller who is going to make a few tweaks.

I was pleased to see at least a partial fix for #2855 in there (that issue is not a "small chunk" issue). As I explained at https://github.com/IQSS/dataverse/issues/2855#issuecomment-429540914 currently the person receiving the "access has been requested" email gets no indication of who is requesting the file. It looks like this:

<img width="592" alt="46905881-0b1c8680-cec8-11e8-9e8a-b9eda38e2890" src="https://user-images.githubusercontent.com/21006/48505104-42a68780-e814-11e8-8bc9-554f5f9c8b45.png">

**Comment by pdurbin** [comment]
@kcondon heads up that @sekmiller and I realized this morning that we can simplify the code by switching to `findUserOrDie` and removing redundant "key" query parameters. I pulled this issue out of QA.

**Comment by sekmiller** [comment]
As noted, the file access requester has been added to the notification and email received by the grantor of file access.  

The format is as follows:

File access requested for dataset: {0} was made by {1} ({2}).

with the dataset name replacing {0}, the requestor name replacing {1} and the requestor's email replacing {2}.

The emails/notifications sent on Dataset Request for Review have been modified to this format changing from "Name at Email" to "Name (Email).
