### ISSUE TITLE
Encoding issue in controlled vocabulary in metadata block

### ISSUE THREAD

**Issue by tcoupin** [IQSS/dataverse#5234]
When I setup glassfish in a centos:7 docker image or vagrant box, special characters are misdisplayed in  controlled vocabulary (ex: language in citation metadata, see screenshot).
![capture du 2018-10-18 12-02-00](https://user-images.githubusercontent.com/7457386/47497488-8c760080-d85a-11e8-9efe-ded759e9d4e0.png)

To reproduce, you can use [tcoupin/dataverse-docker](https://github.com/tcoupin/dataverse-docker) (a simplified fork of IQSS/dataverse-docker)

I found 2 ways to fix this issue:

- change in https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/api/DatasetFieldServiceApi.java#L232 from `br = new BufferedReader(new FileReader("/" + file));`
`br = new BufferedReader(new InputStreamReader(new FileInputStream("/" + file), "utf-8"));` based on https://stackoverflow.com/a/696641
- add `-Dfile.encoding=UTF8` in domain.xml before running installer

I suggest the first method to remove plateforme dependencies

**Comment by pdurbin** [comment]
@tcoupin since these are both one-line changes, how do you feel about making two pull requests? Then we can just close one of them (after we debate them a bit) and put the other through QA. Thanks for coming up with both solutions!

**Comment by pdurbin** [comment]
@qqmyers was it you who reported a similar problem in the "Dataverse 4.x Metadata Blocks syntax/semantics" doc at https://docs.google.com/document/d/1idh4wvCcoxSo7rPkolOkTD5Wvn6PQO__uXqkf7eQujA/edit ? I see "We've had charset issues during editing a metadata block file that resulted in garbled terms as well."

**Comment by qqmyers** [comment]
@pdurbin - Yes. Our initial issues were more with changes to the charset happening during editing of the file, but I see that we use the second method - having the -Dfile.encoding=UTF8 in glassfish - in QDR. I think that's the more comprehensive solution since I don't think that the tsv reader is the only place in Dataverse where the charset hasn't been specified. (It's in domain.xml but it can be set with glassfish asadmin create-jvm-options.)

For anyone who imported the tsv prior to this change, once you change it and re import through the api, you end up with both values in the DB. Deleting from the db as discussed in the google doc is the only way to get rid of the corrupted value that I know of. (Updating the tsvs to use an id for vocab terms would allow their values to be changed via the import api instead. That might be a useful PR (simple for new installs but an sql update would be needed for any existing install.)).

**Comment by pdurbin** [comment]
@tcoupin thanks, this is a useful query. If you want to modify domain.xml in a pull request I would suggest adding a line to our glassfish setup script. Here is where we set some other JVM options in that script:

https://github.com/IQSS/dataverse/blob/v4.9.4/scripts/installer/glassfish-setup.sh#L48

**Comment by qqmyers** [comment]
@tcoupin - added your query to https://docs.google.com/document/d/1idh4wvCcoxSo7rPkolOkTD5Wvn6PQO__uXqkf7eQujA/edit# ...

**Comment by pdurbin** [comment]
@qqmyers cool but I just added a deprecation notice at the top of that doc and asked for feedback on pull request #5251

**Comment by pdurbin** [comment]
@qqmyers as discussed at http://irclog.iq.harvard.edu/dataverse/2018-11-01#i_77605 the new non-deprecated doc is https://docs.google.com/document/d/1XpblRw0v0SvV-Bq6njlN96WyHJ7tqG0WWejqBdl7hE0/edit?usp=sharing (see 3bbde28) so please move the query there. Or open a new issue. Thanks!

**Comment by qqmyers** [comment]
@tcoupin - Here's a potential solution by just iteratively reloading the tsv via the API. It may be easier for you to just update the db, but...

The api will replace a value in the controlled vocabulary value table if it can match on name(strvalue) or identifier. So, just updating the tsv from having a corrupted cvv value to the new one won't remove the old value. (Instead it will create a new one.) 

However, if you create a tsv with the corrupted strvalue and an identifier and reload that, and then reload again with a tsv with that identifier and the right strvalue, it should replace the old value in those two steps. I think you could nominally reload a third time and remove the identifier if you like.
