### ISSUE TITLE
Command line file uploader

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#5240]
TDL has supported the development of a Java command line client that can be used to upload a directory of files to a Dataset. It's open source and we're going to host the code in an IQSS dataverse-uploader repo. 
Per @pdurbin in addition to populating that repo, this should be linked at
http://guides.dataverse.org/en/4.9.4/user/dataset-management.html#file-handling-and-uploading ,
http://guides.dataverse.org/en/4.9.4/developers/intro.html#related-projects , and 
http://guides.dataverse.org/en/4.9.4/api/apps.html ...

PR for guide updates tbd...

**Comment by pdurbin** [comment]
@qqmyers yep! The last thing I'll note is that as we discussed at http://irclog.iq.harvard.edu/dataverse/2018-10-26 we'll want to emphasize that this new uploader is community supported, similar to how we describe the API client libraries for Python, R, and Java at http://guides.dataverse.org/en/4.9.4/api/client-libraries.html

Thank you to @TexasDigitalLibrary for supporting the development of the uploader! I can't wait to try it out. 😄

**Comment by pdurbin** [comment]
@dlmurphy I moved pull request #5250 to QA because it looks good to me but since it involves edits to the User Guide I thought you might want to take a look.

As I mentioned at http://irclog.iq.harvard.edu/dataverse/2018-10-29#i_77169 I tried the uploader yesterday and it seemed to work fine with two tiny files. I showed @sekmiller . Here's the command I used:

`java -jar ~/Downloads/DVUploader-v1.0.0.jar -server=http://localhost:8080 -key=$API_TOKEN -did=doi:10.5072/FK2/4AQEAT /tmp/files`

I mentioned to @djbrooke that I like the TDL ascii art. 😄

**Comment by dlmurphy** [comment]
All set on my end, looking good!
