### ISSUE TITLE
Unclosed bracket in BibTeX citation

### ISSUE THREAD

**Issue by pkiraly** [IQSS/dataverse#5246]
One of our users just found, that the BibTeX citation export misses a closing bracket from the end of the exported file. Here is an example from the Harvard Dataverse (https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/QI2T9A):

```
@data{DVN/QI2T9A_2018,
author = {Boschee, Elizabeth and Lautenschlager, Jennifer and O'Brien, Sean and Shellman, Steve and Starz, James},
publisher = {Harvard Dataverse},
title = {ICEWS Automated Daily Event Data (IN TESTING)},
year = {2018},
doi = {10.7910/DVN/QI2T9A},
url = {https://doi.org/10.7910/DVN/QI2T9A}
```

Properly it should have an extra line with the closing bracket, such as the following:

```
@data{DVN/QI2T9A_2018,
author = {Boschee, Elizabeth and Lautenschlager, Jennifer and O'Brien, Sean and Shellman, Steve and Starz, James},
publisher = {Harvard Dataverse},
title = {ICEWS Automated Daily Event Data (IN TESTING)},
year = {2018},
doi = {10.7910/DVN/QI2T9A},
url = {https://doi.org/10.7910/DVN/QI2T9A}
}
```

**Comment by pdurbin** [comment]
@pkiraly thanks for the bug report. I'm just noting the the version of Dataverse is 4.9.4. It looks like the code to examine is writeAsBibtexCitation in DataCitation: https://github.com/IQSS/dataverse/blob/v4.9.4/src/main/java/edu/harvard/iq/dataverse/DataCitation.java#L243

**Comment by pkiraly** [comment]
The patch is quite evident:

Current code:
```
  out.write("url = {");
  out.write(persistentId.toURL().toString());
  out.write("}\r\n");
  out.flush();
```

Fix:
```
  out.write("url = {");
  out.write(persistentId.toURL().toString());
  out.write("}\r\n");
  out.write("}\r\n");
  out.flush();
```

**Comment by pdurbin** [comment]
@pkiraly yeah. Would you like to make a pull request? 😄

**Comment by pkiraly** [comment]
@pdurbin Sure, if it is not a problem, that I could do it not today, but on Thursday.

**Comment by pkiraly** [comment]
I added a patch #5256. I haven't found existing tests for that class, and I did not started creating one, because I should know more how to fetch data in a test.

I found that this class uses
```
    private void getCommonValuesFrom(DatasetVersion dsv) {
```
to initialize its internal variables. For me it's a bit strange (both the name and the concept), but I guess it has its own reason. If you could give me a hint on how to initialize a DatasetVersion object in a test, then I could continue, and write a test class.

**Comment by pkiraly** [comment]
@pdurbin 
I figured out how to test it, and added the test class (`DataCitationTest`) to a new pull request.

**Comment by pdurbin** [comment]
@pkiraly hi! Thanks for the pull requests! From a quick look, they seem the same except one is against the "master" branch and one is against the "develop" branch. It should be against "develop" because we only update "master" when we cut a release. For more on this topic, please see http://guides.dataverse.org/en/4.9.4/developers/version-control.html

**Comment by pdurbin** [comment]
@pkiraly nope, I closed one of them and approved pull request #5256. Off to QA. Thanks for adding tests! "Coverage increased (+0.06%) to 15.667%" 😄

**Comment by pkiraly** [comment]
I am thinking of adding more to this test class, covering all the rest public methods.
I guess I should create a new issue for that, and also new feature branch based on `develop` branch, new pull request. First I have to wait while this state of test class is available in that branch.

**Comment by pdurbin** [comment]
@pkiraly sure, it sounds fine to me to get this quick fix it for the broken bibtex and focus on increasing code coverage in a future issue. As I'm sure you've noticed, it's actually hard to test dataset fields since the metadata blocks are dynamic and driving by what's in the database. My you can see my technique for testing this with mocks in https://github.com/IQSS/dataverse/blob/5c2ed685f66629989fc93c3bbf68dd22453fbaa1/src/test/java/edu/harvard/iq/dataverse/export/SchemaDotOrgExporterTest.java . But we can talk more about this stuff in a new issue if you want.
