### ISSUE TITLE
Display Make Data Count use and citation metrics

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#5253]
After the backend for Make Data Count support is implemented in #4821, we'll need to display the metrics on the appropriate pages.

**Comment by djbrooke** [comment]
When displaying metrics, we need to take into account:

- Some installations have handles, we should display what we can for these, but we may not be able to display all the metrics
- Some installations will have DOIs through Datacite but won't have file-level DOIs enabled so we may not be able to display all the metrics

**Comment by TaniaSchlatter** [comment]
[Design doc](https://docs.google.com/document/d/1rzYwsWUYe5h95rnLzhg90ulT-9wUjyRcXLOabyRkp20/edit) with research, questions, mockups

**Comment by mheppler** [comment]
Front-end for the file and dataset pgs have been revamped based on [recent 5.0 mockups](https://docs.google.com/presentation/d/1PkXKJ4RWEOzDl-i1DdXjmDTWRuYYd7g5RHoc3NwuI90/edit#slide=id.g5905c4b257_0_19), in order to make some room for expanded metrics from Make Data Count.

New branch `5253-metrics-block-ui` is ready to be wired up. Static placeholder content has been added to the Metrics block, ready to be connected to the back-end.

Assorted UI changes include:
- Container div's for the top section of both pgs has been refactored to improve the use of the Bootstrap grid layout, and for the two pgs to look more consistent (further work can be done here to create a template both pgs use to keep the code and layout consistent)
- Metrics block has been moved to a column on the right of the citation blocks
- Publication status and version labels have been moved to their own line/block under the title, as opposed to inline at the end of the dataset title/file name
- Cite Dataset/Data File buttons have been moved under the citations, as opposed to a column on the right side of the citation block
- On the dataset pg, the panel component around the dataset summary section has been removed to get rid of the border around that section
- On the file pg, the two citation blocks have been swapped in order, so the file citation is displayed first, then the dataset citation
- (...file pg) the file preview/thumbnail/icon has been moved to the Metadata tab, and given a File Preview label
- (...file pg) the duplicate file metadata under the citation blocks has been removed, and the tags (which were not duplicated) have been moved to the Metadata tab, and given a File Tags label, and retaining the render logic to hide the block if there are no tags

![Screen Shot 2019-06-27 at 1 03 53 PM](https://user-images.githubusercontent.com/687227/60286200-41c2f180-98dd-11e9-95c3-4c9b64b8fd29.png)

![Screen Shot 2019-06-27 at 1 04 53 PM](https://user-images.githubusercontent.com/687227/60286207-44bde200-98dd-11e9-938e-7e23d8a51dfe.png)

**Comment by djbrooke** [comment]
- The change to move the preview under file metadata is a temporary change while we implement the file page redesign.

**Comment by pdurbin** [comment]
I started wiring up the Make Data Count back end to the front end.

First, to make it easier to work on the front end, I documented how to run an integration test to put some data in your database: 3760d31

Then I wired up downloads and views on the dataset page: bc5d512

While I was in there I noticed that the mockup above had downloads twice like this:

<img width="225" alt="Screen Shot 2019-07-12 at 4 43 26 PM" src="https://user-images.githubusercontent.com/21006/61157566-7bdae880-a4c4-11e9-8671-bfb151f3c809.png">

I changed the second "Downloads" to "Views" and added a CSS class called "metrics-views-mdc" but I couldn't find where the classes for downloads and citations are defined.

I also notice that there's some help text that could probably be added by someone who wants to swarm on this issue. Right now the popup has placeholder text and I'm not sure why "Downloads" doesn't have a link or a question mark. Here's how it looks after my changes:

<img width="188" alt="Screen Shot 2019-07-12 at 4 47 34 PM" src="https://user-images.githubusercontent.com/21006/61157677-d8d69e80-a4c4-11e9-9643-d580d299311d.png">

**Comment by pdurbin** [comment]
Good meeting today with @mheppler @TaniaSchlatter @djbrooke and @jggautier about this UI.

@mheppler I think I'm ready for some more assistance. Specifically you could:

- Wire up a popup for citations.
- Remove the stray line coming from (I think) `border-bottom:1px`.

If you look at my recent commits, you'll see I added a new table where I try to explain the config options. Here's a screenshot:

![Screen Shot 2019-07-15 at 4 57 08 PM](https://user-images.githubusercontent.com/21006/61249410-2a7c6480-a723-11e9-8979-2c851b91e5eb.png)

I'll try to explain below how I've currently implemented the render logic.

## MDC with DOIs

`curl -X PUT -d '/usr/local/glassfish4/glassfish/domains/domain1/logs' http://localhost:8080/api/admin/settings/:MDCLogPath`

`curl -X PUT -d 'doi' http://localhost:8080/api/admin/settings/:Protocol`

You should see this. Note that I change the hover text a bit:

![Screen Shot 2019-07-15 at 5 01 14 PM](https://user-images.githubusercontent.com/21006/61249380-1b95b200-a723-11e9-90b9-8f6d27ad1d55.png)

## MDC with Handles, no citations

`curl -X PUT -d '/usr/local/glassfish4/glassfish/domains/domain1/logs' http://localhost:8080/api/admin/settings/:MDCLogPath`

`curl -X PUT -d 'hdl' http://localhost:8080/api/admin/settings/:Protocol`

![Screen Shot 2019-07-15 at 5 01 41 PM](https://user-images.githubusercontent.com/21006/61249381-1b95b200-a723-11e9-8d1a-8fa571fb13f3.png)

## Out of the box, classic downloads

`curl http://localhost:8080/api/admin/settings/:MDCLogPath -X DELETE`


![Screen Shot 2019-07-15 at 5 02 09 PM](https://user-images.githubusercontent.com/21006/61249382-1b95b200-a723-11e9-8c1f-b2b826c0eb25.png)

**Comment by TaniaSchlatter** [comment]
Here's a different view of the config options/states with planned formats for maximum/minimum views.
I think that at the initial launch only Citations will link to a popup with a list of the citation sources.
<img width="693" alt="Screen Shot 2019-07-16 at 11 37 02 AM" src="https://user-images.githubusercontent.com/15386424/61308419-379a6180-a7be-11e9-934d-c17c6f894889.png">

**Comment by djbrooke** [comment]
@pdurbin thanks for mentioning the table at standup today. It's helpful. We can roll with this initially and expand based on feedback.

**Comment by mheppler** [comment]
@pdurbin UI has been cleaned up, placeholder msg text moved to bundle, static popup for citations added. Let me know if you need my attention on anything else.

**Comment by pdurbin** [comment]
@mheppler thanks, the popup is looking good! I'll go wire it up to the backend. 😄 

(I see you also removed the stray lines I mentioned above. Thanks!)

Here's a screenshot of the static popup:

![Screen Shot 2019-07-17 at 1 18 18 PM](https://user-images.githubusercontent.com/21006/61396331-7b13cf00-a895-11e9-8e69-783596015983.png)

When I stopped by @djbrooke 's office to ask about https://github.com/IQSS/dataverse.harvard.edu/issues/3 we talked about the popup and the fact that there's a workaround if someone can't see the thousands of citations their dataset has within the little popup. That is, they can retrieve the citation URLs from the API: http://guides.dataverse.org/en/4.15.1/api/native-api.html#retrieving-citations-for-a-dataset . So for now we're fine with an unordered, non-paginated list of URLs. I also mentioned that we can anticipate users wanting to see the title, author, journal, etc from the citations but this is out of scope for the current effort, for this issue. (We would need to write code to retrieve this information from DataCite or Crossref or elsewhere, I guess.)

@TaniaSchlatter on a related note, while users might not care much whether their dataset has 2 or 4 views I think the different in their minds between 2 and 4 citations of their dataset is probably significant. This because citations are going to be more rare, I think. I wasn't considering this during our discussion of the "<5" logic yesterday. Here are my notes from that conversation:

- instead of 0, 1, 2, 3, or 4 views, downloads, or citations show <5 
- use K and M for thousand and million, respectively

**Comment by pdurbin** [comment]
@TaniaSchlatter I just re-wrote the tooltips as promised and deployed the code to the same test server we've been using. The server is currently configured for Make Data Count so you sound see something like the screenshot below if you go to http://ec2-3-86-35-164.compute-1.amazonaws.com/dataset.xhtml?persistentId=doi:10.5072/FK2/GB9MJQ&version=1.0

<img width="303" alt="Screen Shot 2019-07-18 at 4 04 48 PM" src="https://user-images.githubusercontent.com/21006/61488381-12505380-a976-11e9-9bfe-0c39f2610a29.png">

You should see tooltips like the ones below while the server is in Make Data Count mode:

metrics.dataset.title=Dataset Metrics
metrics.dataset.tip.makedatacount=Metrics collected using Make Data Count standards.
metrics.dataset.views.tip=Dataset views are combined with aggregated file views.
metrics.dataset.downloads.makedatacount.tip=Each file download (single or multiple files) increments the download count.
metrics.dataset.citations.tip=Click for a list of citation URLs.
metrics.citations.dialog.header=Dataset Citations
metrics.citations.dialog.help=Citations for this dataset are retrieved from Crossref via DataCite a using Make Data Count standards.

metrics.file.title=File Metrics
metrics.file.tip.makedatacount=Individual file downloads are tracked but this is not part of the Make Data Count standard.
metrics.file.downloads.tip=Total downloads of this file.

To give you a preview of the tooltips you should expect to see when I reconfigure this server for "default" or "out of the box" mode (not Make Data Count), this is what you'll see.

metrics.dataset.tip.default=Aggregated metrics for this dataset.
metrics.dataset.downloads.default.tip=Total aggregated downloads of files in this dataset.
metrics.file.tip.default=Metrics for this individual file.

@mheppler if you're able to pull the latest and demo some of this on your laptop, this might be easier since I'm working remotely the rest of the week.

I also wired the citations pop up to the database so that the list is no longer hard coded.

Next I guess I'll look into the tasks I mentioned previously:

- instead of 0, 1, 2, 3, or 4 views, downloads, or citations show <5
- use K and M for thousand and million, respectively

@TaniaSchlatter I'm not sure if you saw the note in my last comment about how I think people will be quite happy with 4 citations so I'm not sure if the "<5" is needed for citations.

I should also mention that I haven't yet figured out the backend problem I mentioned at standup yesterday about how I wasn't able to produce the JSON file of views and downloads based on logs created by Dataverse. @sekmiller and I talked about it but he didn't work on this part of the code. I'm not sure if it's not working or if the docs weren't easy enough for me to follow to install, configure, and run Counter Processor. If anyone wants to swarm on this task, https://github.com/IQSS/dataverse.harvard.edu/issues/3 is highly related.

**Comment by mheppler** [comment]
If we're voting on the metrics number formatting, I would say that it is unnecessary. It isn't saving very much space, and I can see all the support emails now... my dataset page says, "1.1M Downloads", where are my 99,999 other downloads?

**Comment by pdurbin** [comment]
@mheppler well, it would be an easy way to cut scope by not implementing the metrics formatting suggested above. (And I don't know how to do it. I've been Googling a bit just now.) You're right that space isn't much of a concern. Here's a fake "views" metric with over a billion:

<img width="232" alt="Screen Shot 2019-07-18 at 4 38 53 PM" src="https://user-images.githubusercontent.com/21006/61490384-cfdd4580-a97a-11e9-86fd-7332ed3e4299.png">

The above is also consistent with the "big number formatting" we have at the installation level:

<img width="321" alt="Screen Shot 2019-07-18 at 4 41 47 PM" src="https://user-images.githubusercontent.com/21006/61490477-074bf200-a97b-11e9-95d8-6b7913e95b5a.png">

I dunno. If OmniFaces or JSF made this super easy to do (maybe @scolapasta knows how?) I would probably just throw it in there but maybe we should consider deferring this. I'm curious what @djbrooke thinks.

The other thing I'm thinking about is how when I was a kid I was a little sad when a McDonalds would switch over from "999,862 served" one week to "millions and millions served" the next. 😄 I guess I like the precision (which you can still get from the Dataverse API, by the way, regardless of what we do in the UI).

Whoops, I'm mis-remembering how these McDonalds signs worked, I think. I just found this:

![mcdonalds-1](https://user-images.githubusercontent.com/21006/61490880-ecc64880-a97b-11e9-8bac-5bf52bafffb4.jpg)

**Comment by djbrooke** [comment]
I believe using K and M was for internationalization purposes because it gives us extra space for those languages that have long words for "Downloads" and "Views"

**Comment by pdurbin** [comment]
@djbrooke right, right. Ok, I'll keep Googling. /me sings "Don't Wanna Be An American Idiot"

Oh, the other thing on my todo list is to switch from stuff like `jsf:rendered="#{not empty settingsServiceBean.get(':MDCLogPath')}"` which makes a lot of database calls to our settingsWrapper. I'll probably do that next.

If there are any JSF experts in the house that can advise on the K and M and <5, you know where to find me.

**Comment by mheppler** [comment]
Note: need to fix the CSS for the old metrics block that is still on the dataverse pg.

<img width="770" alt="Screen Shot 2019-07-19 at 9 37 01 AM" src="https://user-images.githubusercontent.com/687227/61539146-db774d80-aa08-11e9-892d-d9b105f807c6.png">

**Comment by pdurbin** [comment]
I just made pull request #6040 

In Slack @djbrooke @TaniaSchlatter @mheppler and I decided to defer the work on

- internationalization of large numbers. Mike linked us to https://meta.discourse.org/t/is-there-a-way-to-translate-numbers-e-g-1-3k-in-the-views-column/30374 and now I'm somewhat haunted by "No one of the 120 registered users in our forum is aware of the “K”." If Discourse hasn't figured this out yet I'm not sure we have a good solution. We'll just show 1,234,567,890 and let people translate "Views" or whatever into a word that fits in the UI.
- "<5" for small numbers. We'll think about this some more.
