### ISSUE TITLE
Restrict login to a set of users by ORCID iDs

### ISSUE THREAD

**Issue by barryrowlingson** [IQSS/dataverse#5275]
I'm trying to set up a restricted Dataverse instance. What I'd like to do is collect ORCID iDs and names of the authorised users, wave a magic API wand, and have those people be able to log in via the ORCID integration. "AllowSignUp" is false, so nobody can create an account themselves.

I can't see an API call to create a user with anything other than the "builtin" auth method. Do I have to initially create them using that and then they will have to convert themselves to ORCID logins?

**Comment by pdurbin** [comment]
@pameyer is in the process of launching an ORCID-only installation of Dataverse. By this I mean that he's not allowing people to create Dataverse accounts based on credentials from any system other than ORCID. The difference is that rather than pre-populating his Dataverse installation with a list of ORCID users (which isn't supported and would involve some database hacking), he plans to let anyone with an ORCID ID create a Dataverse account but only give access to create anything to the people he knows. I hope this makes sense.

If you know all the ORCID IDs of your users, you could in theory put the right values in the "authenticateduser" and "authenticateduserlookup" tables but we don't have an API for this or anything and you've be picking usernames for them. See http://phoenix.dataverse.org/schemaspy/latest/tables/authenticateduserlookup.html (screenshot below) for the fields involved:

![screen shot 2018-11-05 at 12 37 12 pm](https://user-images.githubusercontent.com/21006/48015621-894f0000-e0f7-11e8-8ac3-5c5f5603e15a.png)

**Comment by barryrowlingson** [comment]
Thanks, but that does look a bit hacky. Will probably create builtin users and recommend ORCID conversion.

**Comment by pdurbin** [comment]
Sure, that sounds like a good solution. Thanks for following up.
