### ISSUE TITLE
Only show draft file card if file has changed from published version

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#528]
---

Author Name: **Philip Durbin** (@pdurbin)
Original Redmine Issue: 3943, https://redmine.hmdc.harvard.edu/issues/3943
Original Date: 2014-05-07
Original Assignee: Philip Durbin

---

In #3795 multiple cards for datasets and files were introduced:

- published cards are discoverable by anonymous
- draft cards are discoverable by the creator

We're concerned, however, that when you take a published dataset and edit it, draft cards are created for each file in the published study. This might be overwhelming.

With screenshots, here is a sample publishing workflow where a published file turns gets a draft card perhaps prematurely because the description of the file is not changed until later:

![](https://redmine.hmdc.harvard.edu/attachments/download/769/Root_Dataverse_-_2014-05-07_09.02.31.png)

![](https://redmine.hmdc.harvard.edu/attachments/download/768/Root_Dataverse_-_2014-05-07_09.07.08.png)

![](https://redmine.hmdc.harvard.edu/attachments/download/767/Root_Dataverse_-_2014-05-07_09.36.54.png)

![](https://redmine.hmdc.harvard.edu/attachments/download/766/Root_Dataverse_-_2014-05-07_09.44.53.png)

![](https://redmine.hmdc.harvard.edu/attachments/download/765/Root_Dataverse_-_2014-05-07_09.50.55.png)

![](https://redmine.hmdc.harvard.edu/attachments/download/764/Root_Dataverse_-_2014-05-07_09.57.17.png)

---

Related issue(s): #380
Redmine related issue(s): [3795](https://redmine.hmdc.harvard.edu/issues/3795)

---

**Comment by eaquigley** [comment]
@landreev I just came across this ticket again and was wondering if there is a way to check the timestamps for files as @pdurbin suggests in the comment above.

**Comment by landreev** [comment]
This should be working as requested now. When you create a new draft version of a published dataset, only the files that have been added and/or edited in the draft version will show up in search results, as extra result cards. 
For example, in the dataset below, the file name of 12075.tab was modified in the draft version; so a draft search card is displayed, with the changed name. The file 120747.tab has not been modified at all since the released version; so there's only one search result card: 
![screen shot 2015-02-04 at 9 42 21 pm](https://cloud.githubusercontent.com/assets/737558/6054097/c915f604-acb6-11e4-91ed-cc95078f71dc.png)

**Comment by kcondon** [comment]
OK, works as described, closing
