### ISSUE TITLE
API tests failing at stage 2 after pull request 4883 was merged

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#5393]
Pull request #4883 was just merged and now I can't get stage 2 of the API tests on the "phoenix" server to run after several attempts:

<img width="1432" alt="screen shot 2018-12-11 at 8 01 47 pm" src="https://user-images.githubusercontent.com/21006/49840008-9bb7fb80-fd7f-11e8-940a-de164f830eb9.png">

The console logs are available at https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-deploy-develop/

If stage 2 doesn't complete, stage 3 (that REST Assured tests) can't run.

**Comment by pameyer** [comment]
881694bb1e607b45d52da3f8e3fe78c26096488e in docker-aio shows `Tests run: 82, Failures: 0, Errors: 0, Skipped: 1`

**Comment by landreev** [comment]
Similarly to @pameyer , the tests appear to be working for me. 
(ok, I haven't run through all of them yet - but on jenkins last night it failed *before* it got to the actual tests, still in setup-all.sh script; and it's definitely working for me now). 
As to what happened w/ Jenkins test build last night,  the answer may be right at the top of the Jenkins log: 

[phoenix.dataverse.org-deploy-develop] $ /bin/sh -xe /tmp/jenkins5389922273608838263.sh
...
ERROR:  database "dvndb" is being accessed by other users
DETAIL:  There are 1 other session(s) using the database.

i.e., it looks like it failed to drop the database early on. 
Note all the "table already exists" SQL warnings during the deployment of the app. It failed to drop and recreate the db, then deployed on an already populated database... and then it went downhill from there. 

We should clear all the zombie connections and re-run the test build. (but there may be more things that are broken with Jenkins right now; the deploy-develop project is showing a build stuck since last night; and there's the "jenkins is going to shut down" message at the top of the page (??).

**Comment by pdurbin** [comment]
@landreev and discussed how the sequence last night was this:

- job 321 hung for 45 minutes
- job 322 failed due to database unable to drop
- job 323 hung for 17 hours

**Comment by landreev** [comment]
tbh, I didn't even notice that the 321 didn't complete; I was looking at 322 all along. So yes, it makes sense - the job 321 got stuck, for whatever reason, aborting it didn't kill all the processes already spawned on the phoenix server; that in turn prevented the job 322 from dropping the database... 
Whatever it is, restarting the phoenix server should clear it all, I'm guessing.

**Comment by pdurbin** [comment]
I rebooted the phoenix server as requested but it made no difference.

I told @sekmiller and @pameyer about how phoenix is configured for DataCite and I can't publish a dataset with a file.

I'll swing by and try to catch @landreev and @kcondon on my way out to get there thoughts. I believe we had to switch some test servers away from DataCite recently. Maybe I should work on the fake PID provider in #5327? I will definitely use this on phoenix. I'll check with @djbrooke

**Comment by landreev** [comment]
I tried to reconfigure the Glassfish instance on phoenix to use our "real" DataCite account (GDCC.HARVARD-DV) and the base url https://mds.datacite.org (but still use the test name space 10.5072 of course), and re-ran the api tests. Which worked this time around. 

So the culprit appears to be the DataCite test setup - https://mds.test.datacite.org and/or the test account we've been using (DATACITE.HARVARD).

**Comment by landreev** [comment]
Tried publishing in my own dev. build, using mds.test.datacite.org; it's been hanging for a while.

**Comment by landreev** [comment]
(BTW, I also tried to use the https://mds.datacite.org, but with the test account credentials... and that failed right away, with "bad credentials"; so all in all, this appears to be a problem with the DataCite test server, mds.test.datacite.org. So yes, this is an extra reason not to rely on it so much)

**Comment by pdurbin** [comment]
@landreev well, the good news is that I just made pull request #5399 to add a fake PID provider and included a line in `scripts/deploy/phoenix.dataverse.org/post` to switch the phoenix server over to it.

Thanks for getting poor phoenix working again. As we discussed after standup, I'm planning to put a few things back before passing this issue to QA.

**Comment by pdurbin** [comment]
I put stage 1 and stage 2 back to how they were. Stage 1 sends the "publish" script from Jenkins to the phoenix server. Stage two runs the "publish" script and asserts that a file can be downloaded. Moving to QA.

**Comment by pdurbin** [comment]
> I tried reconfiguring the Glassfish instance on phoenix to use our "real" DataCite account

Just a note that I'm using these credentials on my laptop as well. Otherwise, I can't publish a dataset with a file while using DataCite. As soon as possible I'd like to switch my laptop (and phoenix) over to the fake PID provider in #5399. Others on the team have switched back to EZID. We don't know how long EZID will be available to us.
