### ISSUE TITLE
Add Metrics API to get datasets by subject AND to month

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#5398]
Currently, we can get datasets up to a certain month (and determine how many new by subtracting the previous month) or by subject, but one of the desired visualizations is to get by subject for a specific month, i.e. am metric to get to a certain month AND by subject.

**Comment by pdurbin** [comment]
After standup today, @landreev and I discussed that while 0.1 of the metrics aggregator can handle the 6 existing metrics endpoints, it should be updated to handle the new 7th endpoint that's being created.

Here's the current config file for the metrics aggregator with the 6 endpoints: https://github.com/IQSS/metrics.dataverse.org/blob/v0.1.0/config.json.sample

**Comment by landreev** [comment]
Made a pull request (#5451); this should *not* go into CR just yet - as I'm adding this new metrics to the aggregator in the other code repository, as described above. (thanks @pdurbin)

**Comment by matthew-a-dunlap** [comment]
This work is going to be incorporated into the new homepage/metrics changes on #5398, as this code will be changed again in that PR they will be reviewed together along with #5447.

**Comment by landreev** [comment]
@scolapasta 
@pdurbin 
@matthew-a-dunlap 
I modified the python scripts of the metrics aggregator (https://github.com/IQSS/metrics.dataverse.org) to support this new type of metrics. 
I had to come up with a new format for the aggregated .tsv file. 
We had the following 2 types supported: 
The monthly counts, that were aggregated like this (for example):
```
datasets-toMonth.tsv
month	count
...
2018-11	 1
2018-12	 4
2019-01	 6
```
and the totals by subject/category, like this (for example):
```
datasets-bySubject.tsv:
name	count
Agricultural Sciences	4
Social Sciences	2
```
So the by-the subject-and-by-month will now be aggregated like this:
```
datasets-bySubject-toMonth.tsv:
month	  name	count
2018-11	  Social Sciences	1
2018-12	  Agricultural Sciences	2
2018-12	  Social Sciences	2
2019-01	  Agricultural Sciences	4
2019-01	  Social Sciences	2
```

The PR for the aggregator code: https://github.com/IQSS/metrics.dataverse.org/pull/2. I requested review from Phil, since he wrote the original package.

**Comment by kcondon** [comment]
The numbers from this new endpoint are internally consistent with bySubject when chosen to the current date. There is some discrepancy between the endpoint and facets but that will be handled within the homepage ticket. Closing this but will be merged when pr for homepage is merged.

**Comment by pdurbin** [comment]
I spoke with @landreev and he mentioned that @matthew-a-dunlap might want to make a commit to that branch before we merge. It looks like he added https://github.com/IQSS/metrics.dataverse.org/commit/0468792 on Feb 6 which is after @kcondon commented above on Feb 1.

I don't think issue should have a milestone of 4.11 since nothing has been merged. I'll move it back into code review so we can make some decisions.

**Comment by pdurbin** [comment]
Correction, pull request #5475 on the Dataverse side was merged but nothing was merged on the aggregator side.

**Comment by djbrooke** [comment]
Thanks @pdurbin. I'm going to add this back to 4.11 as there were metrics changes that were merged to Dataverse, but not the metrics aggregator (please tell me if I'm incorrect).

**Comment by matthew-a-dunlap** [comment]
@pdurbin https://github.com/IQSS/metrics.dataverse.org/pull/2 should be merged if it looks good (looked fine to me). There were no additional changes needed for the other metrics endpoints from the homepage work, as we didn't want to store them in the aggregator (we don't care about the harvesting across installations).

**Comment by djbrooke** [comment]
@matthew-a-dunlap @pdurbin OK, will merge after standup tomorrow - thanks!
