### ISSUE TITLE
In BibTex exports, convert quote characters so LaTex displays quotes

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#5424]
In the title field for BibTex files, Dataverse needs to turn opening quote characters into two back ticks (``) and closing quote characters into two apostrophes ('').

This is because when LaTex sees the regular quote character next to some letters, like `"A`, it turns that string into a letter with a diaeresis, like `Ä`. In other cases, maybe when the letter is a consonant and wouldn't get a diaeresis,  it looks like it uses the closing quote, `”` twice.

So in this BibTex...

```
@data{DVN/NMCOBF_2018,
author = {Klasnja, Marko and Chauchard, Simon and Harish, S.P.},
publisher = {Harvard Dataverse},
title = {Replication Data for: "Getting Rich Too Fast? Voters' 
Reactions to Politicians' Wealth Accumulation"},
year = {2018},
doi = {10.7910/DVN/NMCOBF},
url = {https://doi.org/10.7910/DVN/NMCOBF}
}
```
... the quotes in the title field should look like:
```
title = {Replication Data for: ``Getting Rich Too Fast? Voters' 
Reactions to Politicians' Wealth Accumulation''},
```
And LaTex will turn those back ticks and apostrophes into opening and closing quotes.

Here's [a published dataset](https://doi.org/10.7910/DVN/NMCOBF) on Harvard Dataverse with regular quotes in the dataset title.

This was reported in https://github.com/IQSS/dataverse/issues/3759 and described in [this stackoverflow question](https://stackoverflow.com/questions/3901180/how-to-preserve-quotes-in-bibtex).

**Comment by pameyer** [comment]
For a visual illustration:

1058-57b3b7e :
![screenshot_20181221_122731](https://user-images.githubusercontent.com/10261853/50355295-3b158500-051c-11e9-9172-86fff8fd70d3.png)

After bibtex changes:
![screenshot_20181221_122743](https://user-images.githubusercontent.com/10261853/50355310-49fc3780-051c-11e9-84d7-371dfaeef8ee.png)

**Comment by jggautier** [comment]
Looks like capital letters turned into lowercase. Is that something BibTex formatting can prevent? Or maybe a LaTex package thing?

**Comment by pameyer** [comment]
There are BibTex formatting options for preserving capitalization in citation fields (default to letting latex handle it with existing typesetting rules).

**Comment by sekmiller** [comment]
![screen shot 2019-01-17 at 1 37 49 pm](https://user-images.githubusercontent.com/2364928/51340536-3087d600-1a5d-11e9-98de-af2fb58319b4.png)

**Comment by pameyer** [comment]
Checked in with @djbrooke, and updated this branch slightly so that the dataset titles will be handled in a case sensitive manner after the BibTex output from Dataverse is processed by the bibtex software.

Updated the unit tests so that they continue to pass after the case sensitivity changes, but didn't extend them to account for quotations in dataset titles.

**Comment by pdurbin** [comment]
I chatted with @pameyer this morning about tests and I hope that he an others don't mind that I added a test for...

    This Title ``Has Quotes'' In It

... in df7909d

I also attempted to address #5081 with a doc change in d5680cd

Finally, when I tried downloading BibTex for my dataset in production at https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/TJCLKP/JKTORG&version=2.0 I noticed that Firefox throws a syntax error because we are telling browsers that we are sending JSON when we really aren't. I didn't try to fix this but I did add a FIXME in the code at b59cf09 . Here are a couple screenshots of the user experience in Firefox:

![screen shot 2019-01-23 at 12 12 00 pm](https://user-images.githubusercontent.com/21006/51624373-ad58fb00-1f08-11e9-80ab-c1185a7f6518.png)

![screen shot 2019-01-23 at 12 09 51 pm](https://user-images.githubusercontent.com/21006/51624372-ad58fb00-1f08-11e9-8d79-4d530d92c394.png)

Finally, I'm dismayed to learn that code coverage reporting is broken with Netbeans again. Last time we fixed it with 792dd1c but when I tried to put in a similar fix I got this `Resolving expression: '${argLine}': Detected the following recursive expression cycle in 'argLine': [argLine] -> [Help 2]`. I didn't commit this, of course. I wrote about showing code coverage from Netbeans at http://guides.dataverse.org/en/4.10.1/developers/testing.html#observing-changes-to-code-coverage and I'd really like for this to work again.

**Comment by pdurbin** [comment]
@pameyer and I talked through the changes above and he's fine with them so I moved this to QA.

@poikilotherm if you have any idea about the Netbeans code coverage problem, please let us know!

**Comment by pdurbin** [comment]
For the Netbeans code coverage problem, see #5483 and associated pull request #5484.

**Comment by pdurbin** [comment]
> Finally, when I tried downloading BibTex for my dataset in production at https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/TJCLKP/JKTORG&version=2.0 I noticed that Firefox throws a syntax error because we are telling browsers that we are sending JSON when we really aren't. I didn't try to fix this but I did add a FIXME in the code at [b59cf09](https://github.com/IQSS/dataverse/commit/b59cf0928c3dece1ea7dad291da3e370b3c78e6b) . Here are a couple screenshots of the user experience in Firefox

There's a new issue tracking this: Cite Dataset - BibTeX - Firefox json error #6029
