### ISSUE TITLE
Elaborate on use FAKE DoiProvider

### ISSUE THREAD

**Issue by dheles** [IQSS/dataverse#5432]
The guide describes how to configure Dataverse to use the new fake DOI provider, but not the effect of doing so.

http://guides.dataverse.org/en/4.10/developers/dev-environment.html#configure-your-development-environment-for-publishing

Relates to PR #5399

**Comment by pdurbin** [comment]
@dheles thanks for opening this issue and chatting about this stuff at http://irclog.iq.harvard.edu/dataverse/2019-01-04#i_84022

lease note that there is already a little more elaboration at http://guides.dataverse.org/en/4.10/installation/config.html#doiprovider

Here's how it looks:

![screen shot 2019-01-04 at 11 13 59 am](https://user-images.githubusercontent.com/21006/50698065-f573b480-1011-11e9-82c3-582a52604c50.png)

Since you offered to make a pull request (thanks!) I'll go ahead and assign this issue to you.
