### ISSUE TITLE
Files get lost if Dataset DOI changes or if publishing was attempted from Dec 16 to Jan 9, 2019

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#5469]
Edit: See the "Design Summary" comment, from Apr. 29 2020, for the finalized decision on how to proceed with this.

Here's an issue that, going forward, should only appear if/when a dataset has to change it's DOI upon registration (as was emulated by the recent DataCite bug :-)). **Howver, it could have affected any DV instance where publishing attempts occurred between ~Dec 16 and the January 9, 2019 fix at DataCite.**

What I see is:
dataset was created with DOI 10.5072/FK2/abcdef, a file was added and stored in s3 with a path including 10.5072/FK2/abcdef/storageidentifier. 
An attempt to publish the dataset resulted in an update of the DOI to something else (e.g. 10.5072/FK2/123456), in my case due to the DataCite API issue but this would presumably occur for a real DOI conflict as well, and the dataset record was updated, but the file path was not.
For subsequent attempts to access the file in S3, i.e. for full-text indexing or downloads, the path is calculated using the new DOI while the file only exists at a path with the old DOI and it appears to be missing. 

I don't know if the file and other storageIO classes have the same issue or not, but I suspect they would. 

With the DataCite and DV bug resolved, this issue should only occur if/when there are real conflicts, only for PID providers like DataCite that don't register the PID on dataset creation, and only for installations where other instances/other software are creating potentially conflicting DOIs. So - I'm documenting it but not planning to pursue a solution at this point.

For critical data, I believe the files exist and could be found if the original dataset DOI can be found in the log or inferred by searching for the storageidentifier in s3 entries (or files, etc.). Copying entries manually to a path using the new DOI should restore access.

**Comment by pdurbin** [comment]
Related: #5539

**Comment by landreev** [comment]
We have discovered a few cases like this here too. Fortunately, this is recoverable - the files are not really "lost", they just end up sitting in the wrong directory. (yes, this affects all storage drivers). We have fixed all such cases we've found manually; by copying all the files to the correct folders.

**Comment by landreev** [comment]
Note the issue #5539, linked earlier. This is a broader issue, unfortunately, than just the Datacite-related publishing issues in Dec. - Jan., as there appear to be other scenarios where a Draft dataset can end up with a different DOI once published; and in all such cases the physical files become in accessible. 
So we need to solve this programmatically. If nothing else, we should assume that there may be a perfectly legitimate scenario where you have to assign a new DOI to a dataset. If somehow it's a real collision - if somebody else has managed to steal and register that identifier before you had a chance to publish. 

We already have something along these lines in place; for the case of a dataset that had a legacy handle identifier, but has since been issued a DOI. Then there is some logic for detecting which directory name to use. We can similarly handle legacy DOIs; or just move the entire existing files directory when the global identifier changes.

**Comment by qqmyers** [comment]
I agree that the underlying issue is not specific to the DataCite changes. It may be worth having a general way to change a dataset identifier, but this was a rare issue with EZID since DOIs were registered at the service when the dataset was first created. That was not possible to start with DataCite, but I think it is now and a change to the DataCite service could assure the DOI is set when the dataset is created.

**Comment by landreev** [comment]
Yes, when our DataCite service implementation was first written, it wasn't possible to reserve identifiers. But we've been talking about taking the advantage of the fact that it is now possible; similarly to how our EZID implementation has been handling it. 
I should go ahead an open an issue for this.

**Comment by landreev** [comment]
Sorry, we already have an open issue: #5093

**Comment by landreev** [comment]
This apparently still happens, occasionally. Not the mass Datacite outage part, but the condition where the dataset gets a NEW DOI when (re-)published; which results in the Dataverse looking for any pre-existing files in the wrong folder. Happened most recently in Oct. 2019, with the dataset 10.7910/DVN/C6OW6C. 
But the good part about this condition is that it is recoverable.

**Comment by landreev** [comment]
This keeps happening - we *really need to address this*!

Happened on Feb. 10, to dataset `doi:10.7910/DVN/LTW3A5`, which became `doi:10.7910/DVN/TP2OKY` when published. 

It would be nice to know *why* this is happening (what exactly was wrong with `LTW3A5` to justify the new id?). But most importantly, we should assume that the identifier change may be justified and prevent the files from "disappearing". (it's fixed for the dataset above; but I only detect these situations because I'm running some file audits outside Dataverse). 

The quickest way to address this would be to do what we've done with the datasets that had handles: save the old doi as the "other id", and mark it as the "storage id". The alternative would be to actually move the files from the old location to the new... which is more expensive and cumbersome.

**Comment by landreev** [comment]
Another spontaneous global id change-on-publish happened 2 days ago - the dataset doi:10.7910/DVN/65J45A became doi:10.7910/DVN/MOYPE7. 
(noticed when the backup script complained about not being able to find any of the files in the dataset; but do note that it only happened because the author had uploaded the files and published the dataset on the same day)

**Comment by landreev** [comment]
Design summary:
This was discussed on and off; and a somewhat arbitrary decision has been made on how to resolve this:
We'll use the straightforward approach, of saving the old pid as an "other id". 
So, the solution should be as follows: 
When publishing a dataset, register if the "this pid is already registered" condition has been encountered. Register the new pid for the dataset, as before, but save the current pid as an "other identifier", and designate it as "use this identifier for storage". See how we handle it when we assign DOIs to datasets with Handles (npi) as an example.
This way Dataverse will keep using the previously assigned pid to generate the name of the storage folder and any existing  files will stay downloadable.
As an added bonus: many actual users to whom this has happened were also confused when the old dataset url stopped working after publishing. With this in place, the url with the old pid will be properly redirecting.

**Comment by qqmyers** [comment]
This seems like an odd choice given that the major use cases are not real collisions - we've see DataCite fail to respond correctly (which they've fixed), and cases where Dataverse has registered the DOI and forgotten about it (as part of a transaction roll-back). And if it is a real collision - the DOI will be kept as a valid alternate in Dataverse when it really isn't. Seems like updating DataCite to reserve DOIs when they are first assigned would resolve this in a cleaner way - perhaps with some way to stop/override this check for datasets currently in draft, or a one-time update to register all draft DOIs.

**Comment by landreev** [comment]
@qqmyers One other thing I meant to add to that paragraph was that there would also be a notification sent to the admin; who can then choose to address the issue, by copying the files to a properly named folder (just like I do now, to fix this condition) and remove the "other identifier".

**Comment by landreev** [comment]
@qqmyers It is true that most of these situations are simply the result of a previously attempted publish that has failed, leaving the original DOI registered... But we tried to brainstorm a sure way of telling this condition, from a genuine collision - and somehow it was surprisingly tricky to tell for sure - ?

Regardless, we have just scheduled the issue for reserving a DOI; and it is true, that having that implemented may potentially render this issue moot.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
