### ISSUE TITLE
Broken error checking related to #5434

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#5471]
#5434 reported silent errors for large file uploads. The errors being silent was due to a merge issue when provenance upload was added that broke the earlier change that allowed the GUI to show any non-200 response code errors during http file upload. The error code should be applicable to provenance uploads as well. PR #5466 fixes the issue and applies error handling to prov upload as well.

**Comment by landreev** [comment]
For QA: let's double- and triple-check that the rendering is working properly with multiple uploads in progress. Specifically, that the file listing table DOES NOT get refreshed after every individual upload is complete. (otherwise, when N files are drag-and-dropped onto the page, N^2/2 individual cells have to be rendered by the time all the uploads are complete)
