### ISSUE TITLE
Add an admin API to merge accounts

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#5514]
We want to add an admin API that can be used to merge two acounts (i.e. move one account into another). This would require changing foreign keys as well as dealing with the role assignment table.

**Comment by matthew-a-dunlap** [comment]
I was hoping to get this done before my 2 weeks away from Dataverse, but it turned out to be a bit more complicated than I thought.

The code still needs tests and all the objects connected to the objects deleted in the command need to be altered. I'm not sure which need their foreign keys changed and which just need to be deleted. On friday Gustavo pointed me to https://github.com/IQSS/dataverse/blob/develop/scripts/migration/scrub_duplicate_emails.sql as reference for how we did this in the past but I didn't get to dig in. Specifically this part:

```
FROM information_schema.table_constraints tc
JOIN information_schema.key_column_usage kcu ON tc.constraint_name = kcu.constraint_name
JOIN information_schema.constraint_column_usage ccu ON ccu.constraint_name = tc.constraint_name
WHERE constraint_type = 'FOREIGN KEY' AND ccu.table_name='vdcuser';
```

It may be possible to manage this instead by using cascade inside java, investigating that was going to be my next step.

**Comment by scolapasta** [comment]
One last thing, should we be changing the actionlogrecords associated with the merged username? (I'm not sure). At the very least we should add a describe to this command with both usernames since there is not dvobject associated.

**Comment by matthew-a-dunlap** [comment]
The branch for this issue was combined with #5515 as they both needed the same changes to actionLogRecord. Please refer to the new PR for any future changes.

**Comment by kcondon** [comment]
I'll use this ticket to record both rename and merge issues.
1. Renamed/merged user remains logged in if happened while logged in. Generally harmless since cannot save a new dataset but can download public files without incrementing count or recording download in guestbookrepsonse.
2. Cannot log in to merged account. No error in logs but ui does not allow log in as if incorrect password.
