### ISSUE TITLE
Add Admin API to change a username

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#5515]
We want to add an admin API that can be used to change an account's username. This would require dealing with the role assignment table and the actionlogrecord, but other connections (like creator id, etc) should be accounted for by foreign keys.

**Comment by pdurbin** [comment]
The specific SQL update statements can be found at https://github.com/IQSS/dataverse/issues/1445#issuecomment-251712762

We will, of course, want all SQL updates to happen in a single transaction. I'm actually not sure how to accomplish this. I'm interesting in learning because I feel like there are occasions when only some SQL statements are run, leaving "bad data" in the database from partially completed actions. I assume it's some EJB magic?

**Comment by matthew-a-dunlap** [comment]
The branch for this issue was combined with #5514 as they both needed the same changes to actionLogRecord. Please refer to the new PR for any future changes.

**Comment by kcondon** [comment]
see #5514 for a list of issues for both merge and rename.
