### ISSUE TITLE
File Upload and handling: after selecting "save" and files have uploaded, page should resolve to file list and not remain on "Edit" mode

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#5547]
When I drag a drop a significant number (100) of image files, and select save, eventually the page appears to "refresh" but remains on the "edit" window, although files have successfully uploaded. This doesn't resolve on its own

<img width="2046" alt="screen shot 2019-02-14 at 3 41 16 pm" src="https://user-images.githubusercontent.com/8322346/52816442-3dedab80-306f-11e9-8750-cea51018fd36.png">

**Comment by qqmyers** [comment]
FWIW - this could be related to #5544 - part of the reason the error handling broke is because the javascript calls from the provenance panel replaced the ones from the edit files panel, which may have affected whether the file table gets closed or not. I'm not sure, but I'd suggest replicating in the current dev branch before anyone digs too deep into this...

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
