### ISSUE TITLE
For Datacite metadata, pass proper "N/A" code for legacy datasets that have missing values

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#5559]
In legacy versions of Dataverse some fields were not required and were migrated with special value "N/A". When sending metadata DataCite we should replace this with the appropriate code that best represents this.

**Comment by scolapasta** [comment]
Need to figure out which is the best code to assign from the datacite options. @jggautier can you inform this issue for that?

**Comment by jggautier** [comment]
[DataCite's metadata schema](https://schema.datacite.org/meta/kernel-4.1/doc/DataCite-MetadataKernel_v4.1.pdf) includes a list of accepted codes for when mandatory metadata is unavailable:

Code - Definition
(:unac) - temporarily inaccessible
(:unal) - unallowed, suppressed intentionally
(:unap) - not applicable, makes no sense
(:unas) - value unassigned (e.g., Untitled)
(:unav) - value unavailable, possibly unknown
(:unkn) - known to be unknown (e.g., Anonymous, Inconnue)
(:none) - never had a value, never will
(:null) - explicitly and meaningfully empty
(:tba) - to be assigned or announced later
(:etal) - too numerous to list (et alia)

Of these, I think (:unav) would be fine.

**Comment by pdurbin** [comment]
In addition to legacy, migrated datasets, it's also possible to create a dataset with no subject using the SWORD API. We allowed this for backward compatibility. The SWORD API was introduced in DVN 3 when "Subject" was not a required field.

"If Subject is empty it is automatically populated with “N/A”." -- http://guides.dataverse.org/en/4.10.1/api/sword.html#new-features-as-of-v1-1

**Comment by jggautier** [comment]
There's been discussion about what to do with the missing "subject" metadata for datasets in Harvard's installation, but I think these codes and this issue is for only the metadata that Datacite needs for registering DOIs, which are identifier, publisher, publicationyear, resourcetype (all four of these are system generated), title and creator. The missing creator (author) metadata may be what's preventing those datasets with handles from getting DOIs, so we could use the codes for those fields.

**Comment by pdurbin** [comment]
> The latest Datacite schema doesn't list subject as required metadata.

Interesting. So we could pass nothing?

**Comment by jggautier** [comment]
Yes. (Although in the future if Dataverse does send subject/keyword metadata to DataCite, I think we'd have to make sure that those "N/A" values aren't sent, and instead nothing is sent. I added a note about this on [the working crosswalk](https://docs.google.com/spreadsheets/d/1ZVeWnTMnitqKI4hIOuzY1fesON9FOPMt9UF62Geg47A).)

**Comment by djbrooke** [comment]
This may fix #3839 as well.

**Comment by kcondon** [comment]
Issues found:
1. Not sure which fields this needs to apply to, could not readily test N/A content in all metadata fields passed to Datacite due to required field/validation in UI: eg. description, contact email, author.
2. Publisher (dataverse name) set to N/A remains N/A, though author set to N/A becomes creator value :unav at Datacite as designed.
3. Do not have an actual list of all metadata fields passed but so far have:
-creator (author)
-affiliation (author affiliation)
-title
-publisher (dataverse name)
-publicationYear (auto generated by Dataverse)
-description
