### ISSUE TITLE
v4.11 and solr 7.3.1

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#5573]
It looks like the pom.xml and scripts have been updated to use solr 7.3.1 prior to the v4.11 tag but the release page doesn't mentioning upgrading to solr 7.3.1 as one of the steps. Is this an oversight?

**Comment by qqmyers** [comment]
Also noticed that the link to the Installation Guide in the v4.11 section points to the v4.10.1 guide (which has no WebAlanalyticsCode info...)

**Comment by djbrooke** [comment]
Hi @qqmyers, thanks for the report. 

I updated the release notes to point to 4.11 instead of 4.10.1. Our current process has the guides.dataverse.org update at dataverse.harvard.edu deployment time, which can be several days after the release here on Github. I didn't want to link to a Guides URL that did not exist (which is also why the WebAnalyticsCode piece is navigation steps instead of a URL), but we should find a better way to handle this. I'll update this to a URL as well. 

Regarding the solr update question, let me check around a bit and update if needed.

**Comment by djbrooke** [comment]
Hi @qqmyers, I've made the changes about the solr upgrade to the release notes:

https://github.com/IQSS/dataverse/releases/tag/v4.11

I'll close this, but please reopen if I missed anything.

**Comment by qqmyers** [comment]
@djbrooke - another minor issue: the file link for the update script has a different name ("upgrade_v4.10.1_to_4.11.sql"missing the second v before 4.11) that doesn't match the psql command in step 5.
