### ISSUE TITLE
Spike: investigate why a dataset with a large # of files takes a long time to make even a small metadata change

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#5598]
While fixing a delete file issue, we noticed that the performance was not good. As a simple test we tried making just a small metadata change (to see if the issue was related to the files themselves) and it still took a long time. Clearly, this should not be, but requires some investigation to why its happening.

**Comment by landreev** [comment]
To be more specific, for a dataset with 4K files, it took about 10 min. for the UpdateDatasetVersionCommand to complete (10 min. between the actual "start" and "end" time stamps in the action log record). 
Similar things had been observed in the past in other parts of the system. (it takes much longer to index a dataset with thousands of files - worse than linearly so in relation to the number of files, I believe). There's some anecdotal evidence/suspicion that the overhead comes from attempting to perform a database transaction on an object with that many interdependent objects. (there are cascaded dependencies between the dataset, the datafiles, the version and the filemetadatas, etc.) Since the command is executed as one transaction, a transaction context needs to be built for that entire interdependent mess... and something about that process may be growing exponentially(?).

"anecdotal" is the key - some serious research is needed.

**Comment by sekmiller** [comment]
Reindexing the dataset asynchronously seems to solve the problem. My 1000 file benchmark dataset went from around 30 seconds to 3.

We don't use use asyncIndexDataset anywhere else. We do use asyncIndexDatasetList when updating a dataverse. Any downside of using it here @landreev, @scolapasta ?
