### ISSUE TITLE
Visualization for Harvard Dataverse home page

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#5603]
This is a phase 2 of the Harvard Dataverse home page effort #5053 and #5445. The goal is to have a visualization for the home page. 

See the [design document](https://docs.google.com/document/d/11ub9qS9xrKGI__maFJEsmH0Tp2_6Z_dM7kSH4F8SXhw/edit#) that outlines the background, goals, and ideas for this effort.

Rather than focus on visualizing data by subject, we could visualize the structure of dataverses, datasets, and files deposited to Harvard Dataverse, and use that as a way to communicate and explore the concept of containers of data at a high level.

We can show snapshots of the structure of containers at certain times (such as day/week/month – TBD), as well as limit what is shown to items with certain activity (downloads/views). These limitations or views could help users make comparisons, as well as help us manage performance by limiting data represented.

**Comment by mheppler** [comment]
Adding this feature should including resolving this issue, _Moving Dataverses + Datasets: Provide way in the UI for a user to do this #2073_.

The navbar contains links for actions at the root/installation level. When you sign up for an account, the account is created at the highest level. When you use the search input, you are searching all contents of the root/installation. Following that logic, clicking "Add Data" would deposit the dataset/dataverse into the root dataverse, which goes against the preferred workflow, of depositing datasets into your own dataverse.

**Comment by pdurbin** [comment]
> we could visualize the structure of dataverses

I'd feel remiss if I didn't mention that miniverse has a number of experiments for visualizing the structure of dataverses. For example, you could click around https://services.dataverse.harvard.edu/miniverse/metrics/dv-tree and here's a screenshot:

![screen shot 2019-03-08 at 11 14 25 am](https://user-images.githubusercontent.com/21006/54040476-79bdf180-4193-11e9-9769-fc4a143512ae.png)

The code is here: https://github.com/IQSS/miniverse/tree/master/dv_apps/metrics/templates/metrics/viz-tree

There's another miniverse visualization (dv-tree2) that attempts to put dataverse in a tree which sounds great and works for Zelig models...

![screen shot 2019-03-08 at 11 36 03 am](https://user-images.githubusercontent.com/21006/54041724-724c1780-4196-11e9-816a-69ddac09f77d.png)

... but Harvard Dataverse has so many direct children of the "root" dataverse that it's a challenge to visualize in this way:

![screen shot 2019-03-08 at 11 37 28 am](https://user-images.githubusercontent.com/21006/54041812-aaebf100-4196-11e9-8832-07dbc9c2bfca.png)

**Comment by TaniaSchlatter** [comment]
We want to include a simple word change as part of this – from "All" to "Total":

<img width="1103" alt="Screen Shot 2019-03-13 at 2 13 59 PM" src="https://user-images.githubusercontent.com/15386424/54303849-49fb5900-459a-11e9-885f-793d852b5ad2.png">

**Comment by djbrooke** [comment]
Meeting set for mid-September.

**Comment by TaniaSchlatter** [comment]
Adding the conceptual image here for easier reference:

![Harvard_dataverse_structure](https://user-images.githubusercontent.com/15386424/67876173-d64c9300-fb0d-11e9-8c67-55078bff50fc.png)

In next steps we are talking about adjusting a bit to see how the data looks:

- try shifting what is shown to not show files and instead show:
Dataverse 1 > Dataverse 2 > Dataverse 3 > Datasets
I think this will start to create a different vis that focuses on structure, rather than a vis that focuses on activity and acknowledges structure, which is the concept shown. Still, worth trying.

- plan to look at including datasets that are in the root (small blue circles in the illustration above). 

- consider defining thresholds for sizes of circles, to help normalize the display, rather than showing all absolute sizes as D3 and Tableau do.

- subjects should show on rollover/click, and so do need to be in the JSON.

- Work toward including the concept of time/activity as shown in the image above. 

Looking at the image above, I did originally imagine some size variation, as seen in medium and small sized datasets (blue circles). Size is something we can continue to consider as we get closer to displaying the nested structure.

**Comment by pdurbin** [comment]
I had a fabulous hacking session this morning with Jess and @TaniaSchlatter 

I pushed the code so far to https://github.com/IQSS/dataverse-homepage-viz

It's heavily based on https://gist.github.com/mbostock/7607535

You can see the live version at https://iqss.github.io/dataverse-homepage-viz/

For now, we've removed the text labels so it looks like this:

<img width="592" alt="Screen Shot 2019-11-07 at 11 15 09 AM" src="https://user-images.githubusercontent.com/21006/68406479-e8eb4b80-014f-11ea-9967-53e1d70e677e.png">

Lots to do. Stay tuned! 😄

**Comment by pdurbin** [comment]
Over at https://twitter.com/michbarsinai/status/1195236700391387137 @michbarsinai asked for some technical details:

<img width="599" alt="Screen Shot 2019-11-15 at 7 07 25 AM" src="https://user-images.githubusercontent.com/21006/68942443-9b399900-0776-11ea-841f-854e370effe2.png">

Right now this visualization is very much cobbled together.

- First, we run a SQL query that currently lives in https://github.com/IQSS/dataverse/blob/fce1289e89bf9ef6a0675f5cd627dbcccb2ab684/doc/sphinx-guides/source/_static/api/file-parents.sql (see also #6238)
- Then, we transform the SQL output from TSV to JSON with this script: https://github.com/IQSS/dataverse-sample-data/blob/2219dc7ad4a55b058bea73e581c79b8e8c520971/to_packed_circles.py
- Then we replace the "data/data.json" file over in https://github.com/IQSS/dataverse-homepage-viz which is very heavily based on https://gist.github.com/mbostock/7607535

There's still lots to do. Today I'm meeting with someone who knows d3 (I don't know d3 very well) and here's the list of ideas and issues I sent that we can talk about:

- instead of cropping the large (hidden) root circle top and bottom, spread the circles across the whole rectangle
- activity determines the distance from the center (newer things in the center)
- show change over time (today, last week, last month)
- clicking should show a popup (instead of hover). clicking should not zoom like it does now
- in the popup, link to the actual dataverse

**Comment by TaniaSchlatter** [comment]
Phil met with Harvard Library D3 expert. (Cole's pull request: https://github.com/IQSS/dataverse-homepage-viz/pull/1) They are splitting up efforts:

- Cole is working on getting the circles to appear in a rectangle
- Phil is working on putting dates into the JSON
- Dataverse team will work on longer-term plan for getting data

**Comment by pdurbin** [comment]
I just some dates in the JSON in an experimental branch at https://github.com/IQSS/dataverse-homepage-viz/tree/invisible-circles which is deployed (as of this writing anyway) to https://dev2.dataverse.org/d3/invisible-circles/ and looks like this:

![Screen Shot 2019-11-20 at 10 40 42 AM](https://user-images.githubusercontent.com/21006/69275509-8875f880-0baa-11ea-9877-d34d383f6caf.png)

The thought was that perhaps we can spread out the real data (putting circles that were modified less recently further away from the center) by inserting invisible circles at regular intervals. 

Now that we have some dates to play with @TaniaSchlatter @sekmiller and I agree that we should go back to the SQL script and stop considering files that were uploaded in 2018 put published in 2019 to be part of 2018 activity. Here's the script I'll go hack on some more: https://github.com/IQSS/dataverse/blob/fce1289e89bf9ef6a0675f5cd627dbcccb2ab684/doc/sphinx-guides/source/_static/api/file-parents.sql

While I'm in the SQL, I plan to try to start including datasets that are direct children of the root dataverse, which we had excluded previously.

Meanwhile, we have a new #dataviz Slack channel that Jess and Cole have joined.

**Comment by pdurbin** [comment]
> stop considering files that were uploaded in 2018 put published in 2019 to be part of 2018 activity

Fixed in bd6e6d8

I also started taking tabs out of dataset titles (yuck) which means I was able to remove a hack I put into my tsv2json script where I was skipping over some data: https://github.com/IQSS/dataverse-homepage-viz/commit/410ca84

I just put the latest code at https://dev2.dataverse.org/d3/invisible-circles/ which looks like this now (still 2018 data):

![Screen Shot 2019-11-26 at 3 30 38 PM](https://user-images.githubusercontent.com/21006/69670343-b7381700-1061-11ea-9b81-8b1dda8ba106.png)

(Another change was to keep invisible circles out of the middle.)

@TaniaSchlatter and just chatted. The next step for me is to try putting datasets that are direct children of root into the data by hacking further on the SQL. We don't want to tweak the invisible circles any more until those datasets have been added in.

If another developer wants to swarm on this there is an independent task getting the circles to appear in a rectangle. I'm not sure how far Cole has gotten with this so it would be best to ping him in Slack.

**Comment by landreev** [comment]
So what is the SQL query that's taking too long?

**Comment by pdurbin** [comment]
@landreev thanks for asking! 😄 

Here is the SQL query: https://github.com/IQSS/dataverse/blob/bd6e6d8ae9e705c5d63e7daaa14e7a418412ad87/doc/sphinx-guides/source/_static/api/file-parents.sql

Currently, it does not include datasets that are direct children of the root dataverse. These need to be added somehow.

I was kind of hoping that commenting out the following line would help me make progress:

    and tree.id_path[1] = level1dv.id

But the query runs forever, basically, and fills up the disk on poor dvndb-qa1. 😭

**Comment by landreev** [comment]
@pdurbin that query, wow.
Commenting out that one line just makes the query ambiguous; so we don't want to do that. 

Since it works fast enough for the datasets that are direct children of non-root dataverses, a sensible approach would be to leave it as is, and simply run a second query, just for the files in the root-owned datasets - and then combine the results. 

It would be possible to instead modify the existing query to include the files in the datasets that are immediate children of root (the top portion of the query, the tree/path part, would need to be modified - since in its current form it specifically excludes all of these)... however, it would make the query even uglier and messier... (it's easy to modify the recursive tree segment to start with the root - but then it would need extra logic cases for what to show as dataverse_level_1). 

So, here's the simplified version of the query, that only selects the files in the root dataverse datasets: (it drops all that tree/path business: 

```
-- This query only deals with the datasets that are immediate children of the root dataverse; so we don't need to bother with building the tree/path structures. 
WITH maxVersion as (select id  from datasetversion where
concat(datasetversion.dataset_id,':', datasetversion.versionnumber + (.01 * datasetversion.minorversionnumber)) in
(select concat(datasetversion.dataset_id,':', max(datasetversion.versionnumber + (.01 * datasetversion.minorversionnumber))) as max
from datasetversion
join dataset on dataset.id = datasetversion.dataset_id
where versionstate='RELEASED'
and dataset.harvestingclient_id is null
group by dataset_id)), filedatefilter as (select id from dvobject where dtype='DataFile'
-- Make sure the file is published.
and publicationdate is not NULL
-- Optionally subset by file publication date.
--and publicationdate BETWEEN '2018-01-01' AND '2018-12-31'
)
select
    -- ID of the file
    dvo.id as fileid,
    fmd.label as filename,
    -- Strip out newlines and tabs in dataset titles.
    regexp_replace(dsfv.value, '[\r\n\t]+', ' ', 'g' ) as dataset_name,
    -- Only the datasets that are direct children of the root dataverse:
    rootdv.id as dataverse_level_1_id,
    rootdv.alias as dataverse_level_1_alias,
    rootdv.name as dataverse_level_1_friendly_name,
    -- No second level dataverses for these files:
    NULL as dataverse_level_2_id,
    NULL as dataverse_level_2_alias,
    NULL as dataverse_level_2_friendly_name,
    -- And no third level dataverses either:
    NULL as dataverse_level_3_id,
    NULL as dataverse_level_3_alias,
    NULL as dataverse_level_3_friendly_name,
    -- Separate multiple subjects with a delimeter.
    string_agg(cvv.strvalue, ';') AS subjects,
    -- Dataset publication date.
    dsv.releasetime as dataset_publication_date
    -- File creation date.
    --dvo.createdate as file_creation_date,
    -- File publication date.
    --dvo.publicationdate as file_publication_date
from filemetadata fmd, datasetversion dsv,
datasetfieldvalue dsfv, datasetfield dsf,
datasetfield dsfsub, datasetfield_controlledvocabularyvalue dsfcvv,
controlledvocabularyvalue cvv, dvobject dvo, 
dvobject datasetdvo, dvobject rootdvo,
dataverse rootdv, dataset, maxversion, filedatefilter
where fmd.datasetversion_id = dsv.id
and dsv.dataset_id = dataset.id
and datasetdvo.id = dataset.id
and datasetdvo.owner_id = rootdv.id
and dvo.owner_id = dataset.id
and rootdvo.owner_id IS null
and rootdv.id = rootdvo.id
and dsv.id = dsf.datasetversion_id
and dsf.id = dsfv.datasetfield_id
and fmd.datafile_id = dvo.id
and dsf.datasetfieldtype_id=1
-- We added dsfsub and dsfcvv to get subjects.
and dsfsub.datasetversion_id = dsv.id
-- For dev databases, "subject" is 20.
and dsfsub.datasetfieldtype_id=19
-- For Harvard's database, "subject" is 19.
--and dsfsub.datasetfieldtype_id=19
and dsfsub.id = dsfcvv.datasetfield_id
and cvv.datasetfieldtype_id = dsfsub.datasetfieldtype_id
and dsfcvv.controlledvocabularyvalues_id = cvv.id
-- Make sure the dataset is published.
and dsv.releasetime is not NULL
-- Get the latest published version of the dataset...
and dsv.id = maxversion.id
-- ... done getting the latest published version of the dataset.
and dvo.id = filedatefilter.id
-- optionally limit to datasets published at a certain time
-- fast (16 seconds) for all but last day of 2018
--and dsv.releasetime BETWEEN '2018-01-01' AND '2018-12-30'
-- slow (unbounded) for all of 2018
--and dsv.releasetime BETWEEN '2018-01-01' AND '2018-12-31'
-- fast for just the last day of 2018
--and dsv.releasetime BETWEEN '2018-12-30' AND '2018-12-31'
GROUP BY
-- Group by all the fields above *except* subject for the string_agg above.
fileid,
filename,
dataset_name,
dataverse_level_1_id,
dataverse_level_1_alias,
dataverse_level_1_friendly_name,
dataverse_level_2_id,
dataverse_level_2_alias,
dataverse_level_2_friendly_name,
dataverse_level_3_id,
dataverse_level_3_alias,
dataverse_level_3_friendly_name,
dataset_publication_date
order by dataset_publication_date desc;
```
So, run both queries, combine the results. 
A quick check confirms that the 2 lists generated by the 2 queries do not overlap. 
(re-sort the combined list by the publication_date, if that's important for your purposes!)

**Comment by landreev** [comment]
But, IMHO, things like this should really not be done fully inside Postgres. 
If I have time, I may put together a sample script of how I would do it - with 2 queries - one for building the list of all the datasets, with the parent dataverse paths; and then the other one that goes through all the published files and appends the info from the list from step 1, looked up by dataset id (plus maybe a third separate query for the list of subjects for each dataset). With some  python/perl/java in between as needed. 

I'm not entirely sure about the argument that Postgres does essentially the same thing on the inside anyway. It does it in pretty heavy and inefficient ways; but most importantly you end up with these multi-story queries that are scary and very hard to read/work with.

**Comment by pdurbin** [comment]
@landreev thanks for the script! I smashed the output together with other output and hacked on my Python script hand-edited the JSON ([combo.json.txt](https://github.com/IQSS/dataverse/files/3924004/combo.json.txt)) to create this:

![Screen Shot 2019-12-04 at 10 52 21 AM](https://user-images.githubusercontent.com/21006/70183141-36a59600-16b3-11ea-9dde-206600e262db.png)

Some notes on the above:

- I made the leaf nodes (datasets) black so we can see them more easily
- This 2018 data minus December because the file-parents.sql seemed to be timing out
- No invisible circles above

Generally, the feeling is that we like what we see but the fatal flaw is this:

**It's a circle and not a rectangle.**

So now what?

In Slack we talked about these two rectangular data visualizations:

![Screen Shot 2019-12-04 at 11 46 49 AM](https://user-images.githubusercontent.com/21006/70183142-36a59600-16b3-11ea-84e6-7bc53022b6ca.png)

From https://observablehq.com/@mbostock/packing-circles-inside-a-rectangle

![Screen Shot 2019-12-04 at 12 15 08 PM](https://user-images.githubusercontent.com/21006/70183144-36a59600-16b3-11ea-9f0c-4092ecb63247.png)

From https://stackoverflow.com/questions/13339615/packing-different-sized-circles-into-rectangle-d3-js/21612877#21612877

The problems with both of these are:

- These are not d3. We'd need to start over, basically.
- We lose all sense of hierarchy (up to 3 dataverses deep), which was a lot of the point. I also don't know if sorting is supported.

Lots of chatter in Slack (#dataviz) if anyone is interested. At this point we need to pick a direction. The options seem to be:

- Try to swap in a new packing algorithm into the visualization we've been working on.
- Start over with an option like the above that isn't based on d3 and try to somehow add the hierarchy and sorting we have with the visualization we've been working on.

**Comment by TaniaSchlatter** [comment]
It is great to see all the datasets for the 11 months (Jan-Nov) of 2018 represented! I really like the way it looks and the format for showing the nested structure of the data. Combining the vis with tool tips on click and rollover is interesting and kinda fun. As an exercise, I think it is a success. 

We need to consider next steps as @pdurbin mentions. A scaleable display is required to use this vis on the web. Meeting invite forthcoming.

**Comment by TaniaSchlatter** [comment]
Discussed:

- D3 can build circles sequentially, like the https://observablehq.com/@mbostock/packing-circles-inside-a-rectangle example

- recommendation from Cole to write a new javascript algorithm for the rectangular packing, and use that in D3 instead of circle packing algorithm.

- add transitions

- add an indication of time. Could be a scale for the x-axis, a key, color coding, and/or transparency.   Plan to show past 30 days as default, with the ability to show different sets of 30 days, and later goal of showing 1 year. 

- needs to be responsive and accessible, however can be simplified, like not load with transitions on mobile.

- define an upper-limit radius, for example, decision to not render more than some number of datasets to be determined.

**Comment by djbrooke** [comment]
Thanks @TaniaSchlatter for the RFP text. I'm working next week with the IQSS administrative team to get something in place ASAP.

**Comment by mheppler** [comment]
With Phil's assistance, I was able to hack together the visualization into the custom hmpg on my localhost. I cut the static 2018 data down to the last 30 days, and added mocked up popver preview for one of the dataverses, to help fill in some of that available horizontal real estate.

![Screen-Shot-2019-12-17-at-12 28 14-PM-2](https://user-images.githubusercontent.com/687227/71024124-3c977000-20d2-11ea-9c2b-a42f05706359.png)

**Comment by TaniaSchlatter** [comment]
Live version: https://dev2.dataverse.org/

Front end to dos: 

- Refine position of elements so that datasets newly added appear consistently at the center of the circle, and "push" older datasets away from the center of the circle. This does not need to be animated, but is how datasets should appear on pageload. (see Oct. 30 comment in this issue)

- Refine appearance and behavior of the visualization in the Harvard Dataverse home page (accessibility, responsiveness)

- Implement styled content in popovers

- Refine behavior of popover info boxes

- Implement a slider or other method of user interaction to display different segments of data (anticipate 30 day increments)

- Implement refined colors, and size of circles 

Back end to dos:

- enable calling data from https://dataverse.harvard.edu/, and populating the visualization at times to be determined, for example 24 hours, 1 week, 1 month, 1 year

**Comment by pdurbin** [comment]
@TaniaSchlatter @djbrooke after our phone call today I updated https://github.com/IQSS/dataverse-homepage-viz with everything we talked about.

- 1 month data
- 11 month data

I also updated the colors to reflect what we have on dev2. Now if you look at https://iqss.github.io/dataverse-homepage-viz/ it should look like what's at dev2, like this:

![Screen Shot 2020-01-17 at 5 11 31 PM](https://user-images.githubusercontent.com/21006/72649815-a5ca0780-394c-11ea-8aaf-469c5054239c.png)

**Comment by pdurbin** [comment]
@TaniaSchlatter just a heads up that once @kellyawang clicks "accept" in GitHub we should be able to assign this issue to her. And the git problem she reported in Slack should be resolved. I'm not feeling great so I'm heading out. Thanks.

**Comment by TaniaSchlatter** [comment]
We reviewed progress in a build on AWS. The design is stable and looking good. 

STATUS:

1. Refine position of elements so that those with most recent activity (dataset added date) appear consistently at the center of the circle, and "push" older datasets away from the center of the circle. This does not need to be animated, but is how datasets should appear on pageload. (see Oct. 30 comment in this issue). So far, this is controlled by the D3 packed circle algorithm that is sorting by the dif field. | **DONE** 

2. Implement refined colors, and size of circles  | Dataverse design team to do last

3. Implement styled content in popovers (Dataverse name, Dataset name, date of most recent activity, treatment of link to item in Harvard Dataverse) | **DONE**

4. Refine behavior of popover info boxes so that it is clear which circle the popover relates to | **DONE** 

5. [Responsiveness] On click outside the vis, hide any tooltips that are selected | **TO DO**

6. [Refinement] Re-orient tooltip differently if tooltip is going off the page | **TO DO**

7. [Responsiveness] Re-size svg if window resized  | **TO DO**

8. Implement a basic D3 slider or toggle with 30-60-90 day increments | **TO DO**

**Comment by TaniaSchlatter** [comment]
Update: Kelly added a global click handler to de-select tooltips whenever the user clicks outside of a circle: https://github.com/IQSS/dataverse-homepage-viz/pull/5

**Comment by TaniaSchlatter** [comment]
Status update. Reviewed visualization with Mercè. Feedback:

- positioning of the circles in the space when full width is a little awkward. 
- add a line of text to help contextualize what is shown. Wording to come. Position to help with the vis. layout issues (big circle cluster in rectangular shape)
- make date dynamic
- refine title

Other todos:
- connect to dynamic data
- figure out how to make links work
- adjust positioning of bubbles (most recent activity in center)

**Comment by TaniaSchlatter** [comment]
Work to get the data is complete ([#6750](https://github.com/IQSS/dataverse/issues/6750)). See the new issue [(#93)](https://github.com/IQSS/dataverse.harvard.edu/issues/93) to connect data and front end code.

**Comment by TaniaSchlatter** [comment]
Closing this issue. We are unlikely to implement the designed solutions.
