### ISSUE TITLE
StatusMessageHeader no longer displays in 4.11

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#5638]
As best I can tell. Still works properly in 4.9.4 and makes it into the page source of 4.11 but doesn't render visually:

``$ curl -X PUT -d "status2test" http://localhost:8080/api/admin/settings/:StatusMessageHeader
{"status":"OK","data":{":StatusMessageHeader":"status2test"}}``

I see it in the browser's page source:

``
div id="statusInfo" class="ui-dialog ui-widget ui-widget-content ui-corner-all ui-shadow ui-hidden-container smallPopUp"  div class="ui-dialog-titlebar ui-widget-header ui-helper-clearfix ui-corner-top"><span id="statusInfo_title" class="ui-dialog-title">status2test</span>
``

See [https://dataverse-test.irss.unc.edu/](https://dataverse-test.irss.unc.edu/) for example but I've tested several local instances.

**Comment by mheppler** [comment]
@donsizemore In 4.11, the alert code in `dataverse_header.xhtml` was changed to:

```
        <!-- Status Alert -->
        <o:form class="form-inline">
            <div id="status-alert" class="bg-warning" jsf:rendered="#{!empty settingsWrapper.get(':StatusMessageText') and !empty settingsWrapper.get(':StatusMessageHeader') and !dataverseSession.isStatusDismissed()}">
                <div class="alert alert-dismissible container text-warning">
                    <p:commandButton class="close" id="closeButton" actionListener="#{dataverseSession.setStatusDismissed(true)}" update="@form" value="&#215;" />
<!--                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&#215;</span></button>-->
                    <h:outputText styleClass="highlightBold" value="#{!empty settingsWrapper.get(':StatusMessageHeader') ? settingsWrapper.get(':StatusMessageHeader') : bundle['header.status.header']}"/>
                    <h:outputText rendered="#{!empty settingsWrapper.get(':StatusMessageText')}" value=" – #{settingsWrapper.get(':StatusMessageText')}" escape="false"/>
                </div>
            </div>
</o:form>
```

This puts the status msg in an alert panel across the top of the page.

![Screen Shot 2019-03-13 at 2 00 23 PM](https://user-images.githubusercontent.com/687227/54302999-5da5c000-4598-11e9-9e85-fc58e28f561f.png)

This was part of the changes in #4842. You shouldn't see a popup anymore. Although, I am now seeing that it somehow managed to remain in `dataverse_template.xhtml`.

That said, you should be seeing the new alert. Maybe try to add both a header and a message `:StatusMessageText` to your config settings.

**Comment by donsizemore** [comment]
"StatusMessageText must also be set for a message to show."

Me read good. Closing issue. Thanks.

**Comment by shlake** [comment]
OK, UVa - test system is now at 4.12. And in the process has realized that the "bubble" text for StatusMessageHeader no longer appears as Don points out as on UNC's test V 4.9.4 https://dataverse-test.irss.unc.edu/. 

My concerns with the current way status is shown.

1. A user can dismiss the notice (and then "forget" about it). If a browser is not closed, but windows are, when a new DV window opens the notice is not there (because it was dismissed previously).
2. With current config, you need to set BOTH StatusMessageHeader AND StatusMessageText with content for the alert panel to show up.
3. Why do I need to break up my text into two settings StatusMessageHeader AND StatusMessageText (in order for it to show up)?
4. I really liked the "bubble" text in the header - from StatusMessageHeader because that message appeared on EVERY page.

Maybe have two types of status - one for alerts - yellow panel, that can be turned off and one for warnings that cannot be turned off - red panel??

Thanks for listening.

**Comment by mheppler** [comment]
Hello, @shlake! Thank you for the feedback. All valid points that warrant consideration. I am going to open a new issue with your comment, since this issue is closed. This issue originally was created to report an issue in 4.11, as opposed to your request for feature changes.

**Comment by TaniaSchlatter** [comment]
Sticky cursor – reviewing, not adding to a milestone
