### ISSUE TITLE
Use Dataset Thumbnail in Open Graph metadata

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#5641]
For tracking and discussion of the changes proposed in this issue:

- #5621

**Comment by mheppler** [comment]
Checkout this [Open Graph Preview extension for Google Chrome](https://chrome.google.com/webstore/detail/open-graph-preview/ehaigphokkgebnmdiicabhjhddkaekgh?hl=en) to preview the cards for Facebook and Twitter directly from the browser for whatever page you are viewing.

<img width="1217" alt="Screen Shot 2019-03-15 at 9 13 50 AM" src="https://user-images.githubusercontent.com/687227/54433603-abd6d280-4702-11e9-90dd-1e3d81548b01.png">

**Comment by landreev** [comment]
Copy-and-pasting my comment that I first added in #4894:

About the dataset logos:
Unlike datafile thumbnails, dataset thumbnails are hardcoded at 48 pixels; they were never meant to be blown up - so they look terrible when these other sites try to do that in their preview cards.
It should be easy to add a size parameter to this API call - let's open an issue for it.
But, as I mentioned earlier, I was afraid it would not work as easily for the dataset thumbnails that are made from specially uploaded images ("logos"). Because I thought we might be resizing them to 48 pixels on upload, and discarding the originals... But no - it looks like we generate and save the thumbnail as "dataset_logo.thumb48"; but also save the original - as "dataset_logo_original". So we can make copies at different resolutions later on - and we can do that for the already existing logos as well.

**Comment by djbrooke** [comment]
Hi @qqmyers - I just created #5679 which, after merging, will require some changes to this PR. I'd like to put this one line change on ice temporarily.

**Comment by pdurbin** [comment]
Fixed by this PR:

- #5621
