### ISSUE TITLE
Attribute naming of bounding-box wrong (North and South Longitude)

### ISSUE THREAD

**Issue by pdante-ubc** [IQSS/dataverse#5645]
I was working on a harvester to grab data/metadata from Dataverse and noticed that North and South Latitude fields in the geospatial metadata are mislabeled as "Longitude". The web interface titles the fields as "Latitudes" so this doesn't break anything other than for developers who are trying to parse metadata coming out of Dataverse. The error is both in actual metadata coming out of Dataverse and in the field names in the Dataverse Metadata v4.x spreadsheet, although the spreadsheet has the correct labels in the title.

**Comment by djbrooke** [comment]
Hi @pdante-ubc - I'll tag in local metadata block enthusiast @jggautier to get his thoughts about what a fix would look like here.

**Comment by jggautier** [comment]
Thanks for pointing out this error, @pdante-ubc! Because this fix involves changes to the database's field names, as opposed to the field labels we see in the UI, I don't know if editing and reuploading the [geospatial.tsv](https://github.com/IQSS/dataverse/blob/develop/scripts/api/data/metadatablocks/geospatial.tsv)  would be appropriate. There's a warning in our [metadata customization guides](http://guides.dataverse.org/en/latest/admin/metadatacustomization.html): 

> Great care must be taken when reloading a metadata block. Matching is done on field names (or identifiers and then names in the case of controlled vocabulary values) so it’s easy to accidentally create duplicate fields.

So would only editing the field names and reloading the geospatial metadata block creating duplicate fields?

**Comment by pdurbin** [comment]
If it helps, the logic is in "DatasetFieldServiceApi.java": https://github.com/IQSS/dataverse/blob/v4.11/src/main/java/edu/harvard/iq/dataverse/api/DatasetFieldServiceApi.java

**Comment by mheppler** [comment]
Related to **Improve Geospatial Metadata Block #6713**.

**Comment by scolapasta** [comment]
@jggautier sorry no one fully answered your question, but yes it would create duplicates since the "name" is what we user to match the DatasetFieldType. 

So the change in the tsv would need to be accompanied by a corresponding db change. But it would be a straightforward update query.

**Comment by cmbz** [comment]
**2024/01/08:** This is a cleanup task. See tasks below. Update with size: 10

- [ ] - Correct the typo in the code
- [ ] - Provide SQL script to update database
- [ ] - Consider and address backwards compatibility issues

**Comment by cmbz** [comment]
2024/01/31
- Possibly update with a flyway script, but needs additional investigation.

**Comment by landreev** [comment]
As for maintaining backward compatibility on the API level - I don't really have a strong opinion. We can keep code in place that recognizes the old names, or we can say firmly that this is a breaking change and the old names are no longer accepted because they were wrong in the first place. Either option is ok, IMO.
