### ISSUE TITLE
Doc update needed for "Auth Modes"

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#5665]
As @pdurbin pointed out on [IRC today](http://irclog.iq.harvard.edu/dataverse/2019-03-19#i_88538), the section about "Auth Modes" needs an update, as referenced issues have been closed since.

[Docs about Auth Modes in v4.11](http://guides.dataverse.org/en/4.11/installation/config.html#id45)

**Comment by pdurbin** [comment]
Huh, pull request #6105 had the "closes" syntax but this issue was never closed.

This issue is on my mind after a conversation with @kcondon yesterday about pull request #6192 because it's looking like the OAuth support for Microsoft that's coming is not oriented toward centralized auth like ORCID, GitHub, and Google. So I'm feeling like more of a rewrite is needed.

@poikilotherm any thoughts on this? You opened this issue originally. Should we just close it? I can repeat what I said above over in the pull request for Microsoft OAuth stuff.

**Comment by poikilotherm** [comment]
I guess we can close this to cleanup.
