### ISSUE TITLE
OAI-ORE exports are missing ID Number

### ISSUE THREAD

**Issue by shlake** [IQSS/dataverse#5766]
The citation.tsv file modified for release 4.10 (and continues through 4.12) has one line with an extra tab. The line for the field "publicationIDNumber" (displayOrder=31) has an extra tab before the "purl" URL, so the termURI field for that line is really empty - the contents is in the next field over.

Not sure what this affects, but noticed the mis-alignment when I compared this citation.tsv file with the one we have for 4.9.4

**Comment by jggautier** [comment]
Thanks Sherry! It's affecting the OAI-ORE metadata export that @qqmyers worked on. So in that metadata export, Dataverse's Related Publication ID Number field isn't being mapped to [DataCite's ResourceIdentifier field](https://sparontologies.github.io/datacite/current/datacite.html#d4e615). I think the fix would involve just removing that extra tab you mentioned (and the other steps for [updating metadata blocks](http://guides.dataverse.org/en/latest/admin/metadatacustomization.html#reloading-a-metadata-block)).

QDR is the only repository I know of that is using that metadata export (https://github.com/IQSS/dataverse/issues/4706), but it looks like this formatting issue is fixed in their installation (in their OAI-ORE metadata exports, the Related Publication ID Number field is mapped to the DataCite field).

While we're on formatting problems in the citation.tsv file, in the controlled vocab section there's an extra "arxiv" that's always bugged me. I think Dataverse is ignoring it, but it would be nice to remove it.

![Screen Shot 2019-04-18 at 12 19 54 PM](https://user-images.githubusercontent.com/18374574/56375721-4b8cf200-61d4-11e9-8a3d-877ca3bdeed5.png)

**Comment by pdurbin** [comment]
I just made pull request #6022 to remove the extra tab character.

**Comment by jggautier** [comment]
Dataverse installations whose citation.tsv files have that extra tab are exporting OAI-ORE metadata files that are **missing** the following line in the `@context` section of the JSON:

`ID Number: "http://purl.org/spar/datacite/ResourceIdentifier"`

The `@context` section of the OAI-ORE exports should look like this:
<img width="612" alt="Screen Shot 2019-07-18 at 4 48 20 PM" src="https://user-images.githubusercontent.com/18374574/61490999-2c8d3000-a97c-11e9-8d60-8c59770e10dd.png">

That list is a mapping of Dataverse metadata fields to fields in other metadata standards. But Dataverse is only looking at the URLs in the "TermURI" column. The tab is pushing `http://purl.org/spar/datacite/ResourceIdentifier` to another column (see [the screenshot of the citation.tsv file](https://user-images.githubusercontent.com/18374574/56444621-773cd480-62c7-11e9-9072-77b186f58989.png) from an earlier comment), so Dataverse doesn't know that publicationIDNumber should be mapped to `http://purl.org/spar/datacite/ResourceIdentifier`

A fix for this issue will result in OAI-ORE metadata exports including `ID Number: "http://purl.org/spar/datacite/ResourceIdentifier"` in the `@context` section.

**Comment by pdurbin** [comment]
@jggautier thanks. I just changed the title of this issue to "OAI-ORE exports are missing ID Number" based on what you wrote above. Please don't be shy about further editing the title. @djbrooke @kcondon @scolapasta you too since you've studied this bug much more than I have.

> While we're on formatting problems in the citation.tsv file, in the controlled vocab section there's an extra "arxiv" that's always bugged me. I think Dataverse is ignoring it, but it would be nice to remove it.

I also wanted to note that thanks to the commit by @kcondon in 4cbfef1 this extra "arxiv" noise has been removed.
