### ISSUE TITLE
Default override of metadatablock values in tsv files

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#5793]
The implementation of internationalization for metadatablocks allows installations to provide one or more translations of the title/description/watermark fields that are given in the tsv files defining the blocks. However, if one does not set up to use this feature, the values in the tsv metadatablock files, which are loaded into the database via the api, are overridden by a new default <blockname.properties> file shipped as part of the war file.

While this isn't to hard to work around once discovered (either delete/rename the default properties file or update it to match the db values), it's not clear to me that the default properties files are needed. If they don't serve a purpose, can they be removed? (Perhaps with copies provided in the documentation as is done for the analytics-code.html and other branding materials so that people have a template to start from?)  If the idea is to always use a property file/make it easier to change the default values (which could also be done by just setting up the internationalization for one language), should the tsv files and db be updated to not have values that are never used?

**Comment by scolapasta** [comment]
@qqmyers the original idea was to remove completely from tsv and db (seems more straightforward to have one source of truth for these AND seems easier for allowing installations to modify as needed, rather than have to modify the db). If I recall correctly we left them in the db at the time to be backward compatible (not quite the term I'm looking for), but now that it's been around for a while, we can remove.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
