### ISSUE TITLE
Dashboard: Allow searching on users by their full name, affiliation 

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#5808]
This ticket is about using a user's full name to find their account with the Users Dashboard utility. Currently you can only search on either first or last name, not both. Both returns no results, presumably because firstname and lastname are different fields in the db.

This does work in the assign role popup on the permissions page. 

I recently went to look up a professor's user account by full name and found no results. This was confusing.

**Comment by djbrooke** [comment]
This has bit me a few times recently as I've been dealing with support issues. Moving onto the board for estimation and inclusion in a sprint.

**Comment by landreev** [comment]
I have fixed it so that "kevin condon" or "condon, kevin", etc., works now. 
But want to confirm one thing:
It still says "searching by ... [and] affiliation" in the title of the issue. My recollection is that we decided during the planning meeting to stick to searching by first and last name only. Is that the plan? If not - let me know, and I'll add it.

**Comment by djbrooke** [comment]
@landreev thanks for checking. In the sprint planning meeting y'all said it would still be a small if we added affiliation as well, so I updated the title of the issue.

**Comment by landreev** [comment]
OK, added affiliation to the search. Will move into CR once RestAssured test finishes on the branch.

**Comment by landreev** [comment]
Just want to mention, because of some issues with the spinup scripts, I wasn't able to have the restassured tests complete in full yesterday. But all the users api tests pass, so I feel confident about making a PR.
