### ISSUE TITLE
Deleting a file from the file page gives no feedback. Did it work?

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#5847]
Tested on https://demo.dataverse.org running v. 4.13 build 1309-a68b59d if I upload a file and then try to delete it from the file page, I get no feedback. Here are screenshots:

## Click Delete from file page

![Screen Shot 2019-05-15 at 12 06 05 PM](https://user-images.githubusercontent.com/21006/57791102-10fe7280-770a-11e9-9ed9-379dc565d43c.png)

## Confirm delete

![Screen Shot 2019-05-15 at 12 06 11 PM](https://user-images.githubusercontent.com/21006/57791103-10fe7280-770a-11e9-8084-84ccdb1da0be.png)

## Bug: no feedback. Did it work? Was the file deleted? Why am I still staring at it?

![Screen Shot 2019-05-15 at 12 06 18 PM](https://user-images.githubusercontent.com/21006/57791104-11970900-770a-11e9-9108-35cc54bc8e59.png)

I don't have access to server.log on demo but I'm going to suspect it's the same stack trace as in #5842.

**Comment by djbrooke** [comment]
Ah, this bug only happens in certain cases (don't they all?). Good news, file is deleted, bad news, as the title says, is no feedback. 

Steps that I took to reproduce this:

- Created a new test dataset in demo
- Added a file
- Went to the file page
- Deleted the file 
- No feedback, no navigation to the dataset page

Steps where this worked as expected:

- Created a new test dataset in demo
- Added a file
- Published the dataset
- Went to the file page
- Deleted the file 
- Taken back to the dataset page with a green message that the file was successfully deleted

**Comment by sekmiller** [comment]
In addition to the lack of feedback the under the covers manifestation of this bug is that files that have been deleted via the file page have not had their physical files deleted. It's difficult to assess how widespread this may be or how to find these physical files and delete them manually. (or if it's worth going through the exercise.)

**Comment by sekmiller** [comment]
@qqmyers  when we were testing this issue another issue was discovered wherein if you attempt to delete a published file from a draft version of a dataset via the file page, the delete fails and the dataset is left in "locked for edit in progress" state.  The problem is when you try the second merge at around line 179 (UpdateDatasetVersionCommand) you get a java.lang.IllegalArgumentException: Cannot merge an entity that has been removed: edu.harvard.iq.dvn.core.study.FileMetadata 

If I take out the merge at around line 145 everything works.  At first I thought that merge was to save the dataset lock to the DB, but that is not the case.  Do you know why this interim merge is there and what harm would be caused by removing it?

Thanks!

**Comment by qqmyers** [comment]
@sekmiller - I think both of those predate me. If I look at github's blame view and click to look before my change two months ago (which just indented everything to add a try/catch/finally structure), those merges haven't changed in a year+. Just from looking, it seems the first one is to merge changes related to thumbnails (comment around line 119) before the deletes.  One quick thought would be that the code for unpublished files also deletes the fmd from the categories (with the comment talking about merge issues) and that isn't done for a published file - could that be the source of the problem at the second merge?

Also - I was surprised that the try/finally to remove the lock doesn't work, but I guess that makes sense -  saveDataset is still null if the second merge fails - which I guess means the finally clause should fall back to using an earlier copy of the dataset if savedDataset is null. I can make that change unless you make other changes that eliminate the possibility of getting a null in finally. (let me know).
