### ISSUE TITLE
allow BagIT API to export to a local filesystem

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#5850]
pull request forthcoming.

**Comment by kcondon** [comment]
@donsizemore Can you explain a bit more what this pr accomplishes and how it differs from the existing bagit inplementation? Also, to what degree does it potentially interact with the existing implementation?
@qqmyers Does this continue to support your initial use case? Thanks.

**Comment by qqmyers** [comment]
@kcondon - Yep. We've been coordinating. This PR uses the same bag/ore but sends it to a local file system rather than to DuraCloud or Google cloud storage as I've done so far. It's a nice option for users who just want a local copy or have an app (like iRods) that can pick up/manage content from a local file system.

**Comment by kcondon** [comment]
@qqmyers Thanks, that's very helpful.
