### ISSUE TITLE
Typo : in admin document

### ISSUE THREAD

**Issue by Thanh-Thanh** [IQSS/dataverse#5855]
Hello,
In this admin guides, there's a typo : "identifiy"

http://guides.dataverse.org/en/4.14/admin/dataverses-datasets.html#diagnose-constraint-violations-issues-in-datasets

Thanks,

Thanh Thanh

**Comment by pdurbin** [comment]
@Thanh-Thanh hi! As we discussed at http://irclog.iq.harvard.edu/dataverse/2019-05-17#i_93950 I assigned this issue to you and moved it to the "Community Dev" column at https://github.com/orgs/IQSS/projects/2 so that you can make your first pull request.

Please branch from "develop" and call your branch "5855-typo" and make a pull request. Thanks!

If you'd like more details on this process, please see https://github.com/IQSS/dataverse/blob/f2ee26ca2fd16ac7548bf72af327a35e079edadd/doc/sphinx-guides/source/developers/version-control.rst#how-to-make-a-pull-request

**Comment by pdurbin** [comment]
@Thanh-Thanh thanks for making pull request #5857! It looks good so I approved it and moved it to the QA column in the kanban board I mentioned above.
