### ISSUE TITLE
Simplified "create collection" page with only non-required fields

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#5875]
We should consider collapsing all non-required metadata fields for Dataverse creation in an "advanced" or similar panel that would be collapsed by default. 

Created from #5493.

**Comment by mheppler** [comment]
Had this feature in my head during the community mtg, so I sketched a quick UI workflow. The user starts at the Add Data btn, selects New Dataverse, just as they do now, but rather than opening the create form in a new page, it is a popup.

Additionally, when they land on the new dataverse pg, with the success msg, there could be a new popover component displayed over the Edit btn (or some other UI prompt), to suggest to the dataverse creator that there are additional steps, like adding metadata block, uploading files, setting permissions, etc.

![Image from iOS(1)](https://user-images.githubusercontent.com/687227/59868870-eb473780-935f-11e9-8200-87c312cec7c3.jpg)
