### ISSUE TITLE
Clicking "Add" when editing metadata closes all metadata blocks other than the citation block

### ISSUE THREAD

**Issue by pdante-ubc** [IQSS/dataverse#5929]
Using DV v.4.10.1:

When I click the "Add [+]" plus button when editing metadata, all metadata blocks other than the citation block immediately get closed. This means I have to reopen the non-citation metadata group I'm editing and scroll down to the part of the block I wanted to add a duplicate field to.

I'm guessing this is an issue of the page getting completely reloaded when the "+" is pushed for a metadata field. Maybe a partial reload would solve this issue?

**Comment by pdante-ubc** [comment]
Steps to reproduce:
1) Click the + button of a field in a metadata block other than ones in the Citation Metadata block.

**Comment by mheppler** [comment]
@pdante-ubc, thank you for catching this and reporting it in a GitHub issue.

It appears this bug was fix with #5477 which was released in v. 4.11. Could you try to replicate this locally with an updated version higher than v. 4.10.1 or here on our demo server at https://demo.dataverse.org/.

We can close this issue as well as #5282, which you also commented on recently.

**Comment by djbrooke** [comment]
@pdante-ubc - I'll close this out, but feel free to reopen if this replicates in demo or another more recently upgraded environment.
