### ISSUE TITLE
Customization of subject list

### ISSUE THREAD

**Issue by pkiraly** [IQSS/dataverse#5938]
In the Dataset's citation metadata there is a mandatory 'Subject' field (according to the hint beside the field: it contains "Domain-specific Subject Categories that are topically relevant to the Dataset."). In Germany the main funding agency has a standard subject list and we would like to use that instead of this subject list. It is clear that the subject list is defined by the citation.tsv file, so the API regarding to the custom metadata block applies if we change the file.

There are two questions:

* is it typical, that a Dataverse user (the organization behind a Dataverse instance) would like to customize this part? (If yes, we might think of a more general solution)
* what would be the consequence of modifying this file?

**Comment by pdurbin** [comment]
> * is it typical, that a Dataverse user (the organization behind a Dataverse instance) would like to customize this part? (If yes, we might think of a more general solution)

Yes I think there is broad interest in installations being able to customize the Subject list to meet their needs. I recommend reading the following (and replying if you feel moved to):

- The "How to add new subject list in citation metadata" thread at https://groups.google.com/d/msg/dataverse-community/TNRb7hoJd8Q/TcSoJknkAAAJ
- The "Expanding Metadata Subjects" section of the 2017-01-31 Dataverse Community Call notes at https://groups.google.com/d/msg/dataverse-community/uDl01J8qMbg/68G6om-BAQAJ

> * what would be the consequence of modifying this file?

We put the following warning at http://guides.dataverse.org/en/4.14/admin/metadatacustomization.html

"Generally speaking it is safer to create your own custom metadata block rather than editing metadata blocks that ship with Dataverse, because changes to these blocks may be made in future releases of Dataverse. If you’d like to make improvements to any of the metadata blocks shipped with Dataverse, please open an issue at https://github.com/IQSS/dataverse/issues so it can be discussed before a pull request is made."

That is to say, we should work toward a general solution, like you're suggesting! 😄 

p.s. I can understand why you gave this issue a title of "Localization of subject list" but I wonder if "Customization of subject list" might be a little better and more general. It might speak to more people.

**Comment by pkiraly** [comment]
@pdurbin Thanks! I'll check these links you suggest and get back to this one with ideas.

**Comment by djbrooke** [comment]
Closing in favor of #6030 to evaluate as part of a larger effort.
