### ISSUE TITLE
Display "Creation Year" in facets on collection page

### ISSUE THREAD

**Issue by sharmaashish** [IQSS/dataverse#5945]
It would be very helpful to display the creation year on the main landing page. Something like this: 

![](https://user-images.githubusercontent.com/21006/59452020-d821ee00-8dda-11e9-8b60-41a18a7dadbd.png)

And a somewhat related observation: It's my understanding that **Publication Date** would be updated with each new version. Wouldn't it be better to use the date attributes that are used by Datacite — Registered --> Create --> Update. Publication implies creation but is used to indicate an update.

This issue stems from [issue 5279](https://github.com/IQSS/dataverse/issues/5729)

**Comment by jggautier** [comment]
Thanks for opening this issue @sharmaashish. Would you say that the definition of "Creation Year" here would be the year in which the dataset was first made publicly available anywhere (possibly but not necessarily in the Dataverse repository)? I ask because there was [discussion in issue 5279](https://github.com/IQSS/dataverse/issues/5729#issuecomment-501782182) about using the createdate field in the Dataverse database, but that timestamp is the date that the first dataset draft was created (saved) in the Dataverse repository.

> And a somewhat related observation: It's my understanding that Publication Date would be updated with each new version.

Dataverse's "Publication Date" is the date that a dataset was first made publicly available in the Dataverse repository, and it isn't updated with each new version. (That understanding might be my fault. On Dataverse search results pages, the date below the dataset title does get updated with each new major version, and in an image I posted with [my comment yesterday in issue 5279](https://github.com/IQSS/dataverse/issues/5729#issuecomment-501780662), I mistakingly labelled that date the "Publication Date," but uploaded a corrected image soon after. You can see the change in the comment revision history.)

> Wouldn't it be better to use the date attributes that are used by Datacite — Registered --> Create --> Update. Publication implies creation but is used to indicate an update.

I just want to make sure I understand that these three attributes are coming from the dates that DataCite uses to create and register DOIs, and not the dateTypes defined in [DataCite's metadata schema](https://schema.datacite.org/meta/kernel-4.1/doc/DataCite-MetadataKernel_v4.1.pdf) on page 41, which has a value called "Created" that I wouldn't necessarily say is defined as the date that the dataset was first made publicly available anywhere.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
