### ISSUE TITLE
File Ingestion Issue

### ISSUE THREAD

**Issue by Mahsanas** [IQSS/dataverse#5970]
Hi all, 

We are running Dataverse 4.9.4 and facing a file ingestion issue when "certain" csv files are uploaded. Once the CSV files are uploaded the ingestion process begins which ends "unsuccessfully." But the ingestion process apperanetly deforms the files changing them to a faulty tab format while keeping the CSV extension. The files can not then be retreived in the original format as the ingestion phases reshapes them. 
For clarification, we are "not" interested to have the files ingested successfully but to have them in Dataverse in the original format (and not the distoreted format). 

<img width="785" alt="Original" src="https://user-images.githubusercontent.com/12664337/60107561-1dc4ac00-9735-11e9-9a29-ea2f5266c855.png">
<img width="750" alt="File_in_Dataverse_ingest_unsuccessful" src="https://user-images.githubusercontent.com/12664337/60107566-1f8e6f80-9735-11e9-8152-26f015fa6ab6.png">

**Comment by djbrooke** [comment]
Thanks @Mahsanas for the report. I'm really interested in learning more about the files not being retrievable in the original format. 

If the file is not sensitive, can you attach the file here? Also, if it's not sensitive, can you test on demo.dataverse.org (running 4.14) and see if the behavior is the same? We've worked in the ingest code a bit since 4.9.4.

Lastly, I'll mention that we do have a file uningest API endpoint available (though maybe not in 4.9.4):

http://guides.dataverse.org/en/latest/api/native-api.html#uningest-a-file

**Comment by mheppler** [comment]
@Mahsanas @djbrooke -- the uningest API endpoint was added in 4.9, _API: "uningest" a tabular data file #3766_.

**Comment by djbrooke** [comment]
Thanks @mheppler. Time flies!

**Comment by Mahsanas** [comment]
@djbrooke . I just tested out the files on the demo site and  it is working fine there. The files are not ingested and thus not distorted.
It seems the issue belongs to our version of Dataverse and once we upgrade it will be resolved.
Thanks for the uningest option though this is not gonna be a permanent solution as we will see these types of files comming from an instrument to the repository often. 
I will upgrade to the latest version.
Thanks all.

**Comment by djbrooke** [comment]
OK, thanks for the update @Mahsanas! I'll close this out.
