### ISSUE TITLE
Use/Maintain Appropriate File Formats for Preservation and Reproducibility

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6006]
We discussed #6002 and #2720 in sprint planning today and plan to work on both during a future sprint. I'm closing out both of those in favor of this one. 

- For reproducibility, we want to maintain the original file format for tabular files because .tab may be referenced in scripts
- For preservation, .tsv is preferred as it is more recognized in the community

We should determine a way to meet both needs.

**Comment by pdurbin** [comment]
> For preservation, .tsv is preferred as it is more recognized in the community

Not just for preservation. For simple things like opening the tab-separated file in Excel. Please see https://twitter.com/Ray_J__/status/1202296388618457089 and the screenshot below:

<img width="952" alt="Screen Shot 2019-12-04 at 10 34 40 PM" src="https://user-images.githubusercontent.com/21006/70202970-5952a180-16e9-11ea-809d-0aec4f2f9fcd.png">

**Comment by mheppler** [comment]
Review as part of **Add originalFileName field to json #2734** when that is picked up in development.

**Comment by pdurbin** [comment]
> For reproducibility, we want to maintain the original file format for tabular files because .tab may be referenced in scripts

I'm not sure I understand what the change would be. We always maintain the original file.

> * For preservation, .tsv is preferred as it is more recognized in the community

I re-opened #2720 because I feel strongly that we should use .tsv instead of .tab

Given the above, is there any reason to keep this issue open?

Vote to close.

**Comment by pdurbin** [comment]
@jggautier you'd definitely right that there's something to fix for Binder. I just launched my dataset there and what I see is the .tab version, like you're saying.

Binder uses repo2docker under the covers and here's where Dataverse support was added: https://github.com/jupyterhub/repo2docker/pull/739

We could submit a PR to repo2docker to change the behavior so that original files rather than preservation (.tab) files are downloaded from Dataverse. I'd be worried about backward compatibility though.

Anyway, we need a specific, actionable plan. I'm happy to talk about this whenever.

**Comment by pdurbin** [comment]
> We could submit a PR to repo2docker to change the behavior so that original files rather than preservation (.tab) files are downloaded from Dataverse.

This is exactly what I did:

- https://github.com/IQSS/dataverse/issues/9374
- https://github.com/jupyterhub/repo2docker/pull/1253

**Comment by pdurbin** [comment]
Closing in favor of this issue:

- #2720
