### ISSUE TITLE
MakeDataCountApi is hardcoded to production datacite server

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#6137]
MakeDataCountApi, on line 142, hardcodes the api.datacite.org server. It might be better if it leveraged the doi.baseurlstring jvm option so that development/test servers using doi.baseurlstring=https://mds.test.datacite.org would query api.test.datacite.org for citations. (I verified that DOIs minted at mds.test.datacite.org report their info from api.test.datacite.org and not api.datacite.org, the latter of which just returns an ~empty json doc.)

Since the doi.baseurlstring currently includes the protocol and the mds service, I'm not sure whether it would be better to add a second doi.MDCurlstring or to switch to making the server configurable and prepending hardcoded https://mds. or https://api.  where needed. (Or use a Dataverse setting since there is no username/password associated with the public api service?)

**Comment by pdurbin** [comment]
@qqmyers thanks for trying out the new Make Data Count support! I'm definitely open to a pull request along the lines you're suggesting so please feel free to make one. I **think** I'm leaning toward a dedicated configuration option (no objection to having Make Data Count in the name) rather than refactoring code around existing settings.

Here's the line in question as of 09fe94b

`URL url = new URL("https://api.datacite.org/events?doi=" + authorityPlusIdentifier + "&source=crossref");`
