### ISSUE TITLE
 OAuth 2.0 - Microsoft

### ISSUE THREAD

**Issue by alejandratenorio** [IQSS/dataverse#6155]
With the current OAuth2 providers, we can only connect to specific providers. We worked with Active Directory and we had to connect with Microsoft.
Similar to ORCID, GOOGLE and GitHub, we integrate Mircrosoft as OAuth2 provider in Dataverse.  
The goal of CIMMYT is to contribute with this. We would like to share with you the source code for your review and comments.

**Comment by pdurbin** [comment]
@alejandratenorio hi! Thanks for your interest in contributing to Dataverse!

I was just clicking around https://data.cimmyt.org and noticed that the Microsoft login makes use of an HTTP Basic Auth pop ("Authentication Required") as in the screenshots below:

![Screen Shot 2019-09-18 at 11 01 15 AM](https://user-images.githubusercontent.com/21006/65160575-fadc2800-da03-11e9-97c5-34c14961fa53.png)
![Screen Shot 2019-09-18 at 11 01 19 AM](https://user-images.githubusercontent.com/21006/65160577-fb74be80-da03-11e9-8551-00430450f042.png)
![Screen Shot 2019-09-18 at 11 01 50 AM](https://user-images.githubusercontent.com/21006/65160579-fb74be80-da03-11e9-91dc-b0eafa9e1181.png)

Was the HTTP Basic Auth popup a design choice? The other OAuth providers look more like this with the standard OAuth login flow (Google shown below):

![Screen Shot 2019-09-18 at 11 05 33 AM](https://user-images.githubusercontent.com/21006/65160736-4a225880-da04-11e9-9900-b1cfeb592eda.png)

![Screen Shot 2019-09-18 at 11 05 36 AM](https://user-images.githubusercontent.com/21006/65160735-4a225880-da04-11e9-8ede-e3715c93ba42.png)

![Screen Shot 2019-09-18 at 11 05 47 AM](https://user-images.githubusercontent.com/21006/65160734-4a225880-da04-11e9-92e9-968c4abe83e2.png)

Please let us know. Thanks!

Also, I wanted to let you (and others) know that over at http://guides.dataverse.org/en/4.16/installation/shibboleth.html#shibboleth-and-adfs there are some instructions for logging into ADFS/Active Directory through Shibboleth/SAML instead of OAuth. I just mention this so that when it comes time to document the feature we can explain that there are multiple options (SAML and OAuth) for getting login to Microsoft working.

**Comment by alejandratenorio** [comment]
Hello @pdurbin,

Basic Auth pop was a specific condition for CIMMYT,   to limit log-in to email addresses ending in @cgiar.org. 

Without the Basic Auth pop look like,

![image](https://user-images.githubusercontent.com/31973211/65165002-8e612900-da03-11e9-8df3-efa4454fe7d3.png)

![image](https://user-images.githubusercontent.com/31973211/65165065-a8027080-da03-11e9-8f6d-36d9d4da6a91.png)
