### ISSUE TITLE
Update Make Data Count Metrics Tooltip to Popover, include URL

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6209]
We haven't yet made use of popovers in Dataverse, and we'd like to try it out on the Make Data Count so that we can point folks directly to the MDC documentation instead of to our guides. 

![popover](https://user-images.githubusercontent.com/7773392/65520391-7c74ff80-deb5-11e9-80e7-b6c5bb2c95a8.jpg)

When we start work on this, I'd be interested in pairing with a developer on this to see if it's something that I can learn.

**Comment by mheppler** [comment]
Added popover with link to metrics block (for Make Data Count configurations) on dataset and file pg.

_Dataset pg with Make Data Count configured_

![Screen Shot 2019-12-04 at 3 47 50 PM](https://user-images.githubusercontent.com/687227/70181264-95691080-16af-11ea-93a0-d09d85946804.png)

In order to do this, I also had to cleaned up the existing popover html and css on dataset, file, replace file pgs.

_Dataset pg with failed tabular file ingest_

![Screen Shot 2019-12-04 at 3 56 59 PM](https://user-images.githubusercontent.com/687227/70181379-c8130900-16af-11ea-841e-d035ada18f00.png)

_Dataset pg with image file + thumbnail_

![Screen Shot 2019-12-04 at 3 59 35 PM](https://user-images.githubusercontent.com/687227/70181383-cba69000-16af-11ea-8c53-ddd755494c28.png)

_Replace file pg with image file + thumbnail_

![Screen Shot 2019-12-04 at 3 59 55 PM](https://user-images.githubusercontent.com/687227/70181389-cea18080-16af-11ea-94da-5da0bfa49a98.png)

**Comment by mheppler** [comment]
@djbrooke in regards to pairing with a developer, I would be happy to discuss PR #6434 in more detail with you to review the changes required to add this feature.

**Comment by djbrooke** [comment]
Thanks @mheppler. I'm interested but I'm unfortunately not in the office for the rest of the week and it would be good to keep this moving. I saw that it got reviewed and I'll be happy to discuss next week if there are still outstanding questions.
