### ISSUE TITLE
Feature request: Email Templates (if possible)

### ISSUE THREAD

**Issue by mdmADA** [IQSS/dataverse#6222]
ADA has a number of requirements for emails that are sent to dataset owners and users on request access, access granted, etc.

For example, in ADA's forked code, the email sent to a dataset owner when a user requests access (with the guestbook popup) is generated with the actual guestbookresponse details appended to the boilerplate 'File access requested' text specified in the Bundle.properties file.

It would be nice to be able to create templates for emails that are sent to different types of users and that can be modified to contain more information than just the text specified in the Bundles.properties file. And, if templates could be used, without having to modify, recompile and deploy the code just to change the text of emails.

I am not sure how this could be done but it would certainly be a bonus to ADA. I am not sure how we will implement our email requirements once I manage the time to get the 'Guestbook at Request Access' functionality into the main codebase.

Thanks!

**Comment by djbrooke** [comment]
Seems like a good idea! We're happy to discuss in detail when you're ready. Regarding the email text, we at least one API endpoint where you can load in HTML (http://guides.dataverse.org/en/latest/installation/config.html#applicationtermsofuse). We could look at a similar model for these templates so that a deployment/code change would not be needed to update the email text.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
