### ISSUE TITLE
"Explore" and "Configure" buttons do not appear for file level tools with no contentType (Data Explorer, Data Curation Tool, etc.) on develop, works on 4.16

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#6229]
On Friday I merged https://github.com/IQSS/dataverse-ansible/pull/112 and saw with my own eyes the Data Curation Tool working just find on Dataverse 4.16. Here's a screenshot:

![Screen Shot 2019-09-30 at 1 00 25 PM](https://user-images.githubusercontent.com/21006/65899823-92d1fe00-e382-11e9-8447-6007ddcd850f.png)

At design standup this morning I offered to send a link around but I cannot get the "Configure" button to appear on the "develop" branch. I've tried the phoenix server and my dev2 server.

Here's how the Data Curation Tool is loaded on my dev2 server:

```
$ curl -s http://localhost:8080/api/admin/externalTools/20 | jq .
{
  "status": "OK",
  "data": {
    "id": 20,
    "displayName": "Data Curation Tool",
    "description": "Data Curation Tool for curation of variables",
    "type": "configure",
    "scope": "file",
    "toolUrl": "https://scholarsportal.github.io/Dataverse-Data-Curation-Tool/",
    "toolParameters": "{\"queryParameters\":[{\"dfId\":\"{fileId}\"},{\"siteUrl\":\"{siteUrl}\"},{\"key\":\"{apiToken}\"},{\"fileMetadataId\":\"{fileMetadataId}\"}]}"
  }
}
```

**Comment by pdurbin** [comment]
I know what this is and just chatted with @sekmiller and @djbrooke about it.

In 3d522aa when I starting allowing allow content type (MIME type) to be null (because datasets have no content type) I removed this logic (and the comment):

        //Legacy support - assume tool manifests without any mimetype are for tabular data
        if (contentType == null) {
            contentType = DataFileServiceBean.MIME_TYPE_TSV_ALT;
        }

@scolapasta and I discussed this removal (and "Not providing this parameter makes the tool work on ingested tabular files and is equivalent to specifying the contentType as “text/tab-separated-values”." from the docs) a bit at https://github.com/IQSS/dataverse/pull/6059#discussion_r319234001

The plan to put equivalent logic back and document it in a similar was as above.

**Comment by scolapasta** [comment]
@pdurbin rather than add this logic back in (*) can we just fix the manifest of the data curation tool (or ask them to specify it)?

(*) when I had first commented on that I had been looking at a bid of outdated code; I actually prefer to not have that assumption - we could allow this to be null for files and maybe even our logic on tools should always show for all files if this is null (i.e. imagine a tool that could work for any file)

**Comment by pdurbin** [comment]
@scolapasta we should absolutely reach out to the makers of the Data Curation Tool and Data Explorer (which is also affected). Before reading your note above, this is how I wrote up the change to the guides (documentation driven development):

"Dataset level tools do not use contentType. File level tools operate on a specific **file type** (content type or MIME type). For example, if your tool is for PDFs, use "application/pdf" as the contentType. If you leave out a contentType for file level tools, "text/tab-separated-values" will be used but you should not rely on this behavior as it may be removed in the future."

@djbrooke you seemed to favor putting the logic back in. Thoughts on this? An alternative would be to have Dataverse bark at the sysadmin with "contentType is required" or something. This would have been enough for me to figure out that something was amiss.

**Comment by djbrooke** [comment]
Thanks @pdurbin. When we talked it wasn't clear to me that this had already been discussed. I don't necessarily favor one approach over the other, but I am interested in getting 4.17 out and I was OK with not solving this issue now and just changing it back to what it was previously.  

If having some warning/logging about contentType being required is not controversial and easy, that's fine.

**Comment by scolapasta** [comment]
For 4.17, technically this doesn't need to be changed at all, as long as the manifests of the external tools specify the content type. 

It is a change of behavior that we introduced to no longer assume a content type of tab, if nothing is specified. My opinion is we want this change at some point soon (so we could support a theoretical tool that works on any file, but we could always introduce that change later (i.e when we change the code to support that - if we had already done that, the behavior we would have seen here is that these tools show up on all instead of none - still not what is wanted, but more obvious to the person who uploaded the manifest what is missing).

I guess what I'm saying is that currently allowing a tool with no content type doesn't make much sense since we don't display said tool for all files.

**Comment by pdurbin** [comment]
I just pushed a 6229-grandfather-tsv branch in pull request #6232 (haven't run the API tests yet).

I'll switch gears and try the "bark" approach next.

**Comment by pdurbin** [comment]
Ok, the bark approach is in as a second pull request: #6233 

I'll go back and run the API test suite on both branches before changing the pull requests from "draft" to "ready for review".

**Comment by pdurbin** [comment]
Ok, ExternalToolsIT now passes on both pull requests so I moved them to code review.

- pull request #6232 (6229-grandfather-tsv branch)
- pull request #6233 (6229-bark)

**Comment by pdurbin** [comment]
I just confirmed that Data Explorer is also affected so I updated the title of this issue.
