### ISSUE TITLE
Link Search broken, pop up window is blank

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#6268]
In Harvard Dataverse (4.17) and https://demo.dataverse.org (4.17), the experimental feature "[Link Search](http://guides.dataverse.org/en/latest/api/native-api.html#saved-search)" (available only to installation superusers) is broken. After performing a search when logged in as a superuser, when you click Link > Link Search, the pop up/modal window is blank, so there doesn't appear to be a way to continue.

![Screen Shot 2019-10-10 at 9 56 21 AM](https://user-images.githubusercontent.com/18374574/66575625-3b7f1b00-eb44-11e9-9d0a-2c37cd88a04a.png)

**Comment by alanpeng899** [comment]
I have the same problem, has this problem been solved?

**Comment by pdurbin** [comment]
@alanpeng899 unfortunately, this bug has not been fixed. I just tried it on a test server (screenshots below) as of 7422e1c, which is the latest commit on the "develop" branch (which is the branch that represents the next release of Dataverse).

<img width="1277" alt="Screen Shot 2019-11-27 at 7 20 57 AM" src="https://user-images.githubusercontent.com/21006/69723132-d6c55300-10e6-11ea-999b-2952e3a29b8f.png">

<img width="1277" alt="Screen Shot 2019-11-27 at 7 21 02 AM" src="https://user-images.githubusercontent.com/21006/69723131-d6c55300-10e6-11ea-9e26-0af36e108337.png">

This is a regression. Since Dataverse 4.0 Saved Search has been "superuser only" and somewhat experimental but it used to work. I don't know which version of Dataverse it still worked in.

**Comment by mheppler** [comment]
Did some initial investigation into this bug, and discovered that there are three blocks of content for this dialog that all use `DataversePage.dataversesForLinking.size()`, which is returning nothing when called. There are no errors in the server log, and the code annotations appears to be original from 4.0 (#114).

¯\_(ツ)_/¯
