### ISSUE TITLE
Carriage return in metadata blocking OAI-PMH Export

### ISSUE THREAD

**Issue by DS-INRA** [IQSS/dataverse#6275]
Certain metadata fields like the description may contain carriage returns.
When so, it is encoded as "\&#xd;" and not in UTF-8 "0x0D".
This cause the OAI-PMH export to be invalid.

The description should be encoded as UTF-8 for OAI-PMH Exports as required in OAI-PMH standards.

We could also imagine that carriage return should be avoided automatically anyway and possibly replaced with a \<br> tag.

**Comment by DS-INRA** [comment]
Hello, sadly we cannot work on it so we'd be glad that you add it into an upcoming sprint.
Thanks !

**Comment by djbrooke** [comment]
Thanks @DS-INRA ! Looks small, we'll work on it and get it into a release soon.

**Comment by jggautier** [comment]
Hi @DS-INRA.

I'm hoping you folks or really anyone in the community can help clarify some things. I can move these questions to the Dataverse Community Forums if that's better :)

From what I can tell, the description metadata in https://doi.org/10.7910/DVN/DTWZ1Y has carriage returns, but I’m able to view OAI-PMH records for at least some of the metadata formats, like oai_ddi (https://dataverse.harvard.edu/oai?verb=GetRecord&metadataPrefix=oai_ddi&identifier=doi:10.7910/DVN/DTWZ1Y). (I'm not able to see the exports in other metadata formats like "Datacite" (https://dataverse.harvard.edu/oai?verb=GetRecord&metadataPrefix=Datacite&identifier=doi:10.7910/DVN/DTWZ1Y), but I think that's not related to this encoding issue.) So I'm wondering:
- Am I testing this issue in the wrong way? What are the consequences of the OAI-PMH exports being invalid as you wrote?

Also, would this change affect how carriage returns are encoded in other metadata exports, like the DDI that you can get from the API (ex. https://dataverse.harvard.edu/api/datasets/export?exporter=ddi&persistentId=doi%3A10.7910/DVN/DTWZ1Y) and is that okay? Or in fact, is it better that in all metadata exports, carriage returns are encoded as UTF-8 (or replaced with `<br>` tags)?

**Comment by jggautier** [comment]
I should mention that those datasets are in an installation running Dataverse 4.17. I tried testing on Data Inra, which is running 4.10, but can't find datasets with carriage returns in that repository as I can in Harvard Dataverse (which I have database access to).

**Comment by DS-INRA** [comment]
Hi @jggautier ,
it seems that the example dataverse you used has <br /> tag and not what I mentionned as a carriage return i.e a carriage return from the UI or I haven't found it.
I've made examples if it can help :
- [https://data-preproduction.inra.fr/dataset.xhtml?persistentId=doi:10.70112/ZKHGJH](with carriage returns)
`<dcterms:description>Ceci&#xd;&#xd;Est&#xd;&#xd;Un&#xd;&#xd; Test</dcterms:description>`
- [https://data-preproduction.inra.fr/dataset.xhtml?persistentId=doi:10.70112/0R8RB3](with br tag) 
`<dcterms:description>Ceci&lt;br>Est&lt;br>Un&lt;br>Test</dcterms:description>`

As for OAI-PMH, the whole record should be in utf-8 as stated in the [https://www.openarchives.org/OAI/openarchivesprotocol.html](protocol). For other exports, at least for DDI there is no indication against using UTF-8 so I wouldn't see an issue for the carriage returns to be encoded the same way.

**Comment by jggautier** [comment]
Ah, thanks for the extra info.

The example I used has br tags and carriage returns in the description field:

<img width="858" alt="Screen Shot 2019-10-28 at 9 55 51 AM" src="https://user-images.githubusercontent.com/18374574/67684215-250cf800-f969-11e9-8dda-93ea9babce0b.png">

But I can still get [the dataset's oai-pmh record](https://dataverse.harvard.edu/oai?verb=GetRecord&metadataPrefix=oai_ddi&identifier=doi:10.7910/DVN/DTWZ1Y) and the `&#xd;` code does not show.

Here's [another dataset](https://doi.org/10.7910/DVN/UHSLKM) with a carriage return in the description field, but no tags:

<img width="866" alt="Screen Shot 2019-10-28 at 10 02 09 AM" src="https://user-images.githubusercontent.com/18374574/67684714-1410b680-f96a-11e9-85a0-b2cb08304410.png">

I can also get [it's oai-pmh record](https://dataverse.harvard.edu/oai?verb=GetRecord&metadataPrefix=oai_ddi&identifier=doi:10.7910/DVN/UHSLKM).

My computer won't open https://data-preproduction.inra.fr right now. Is it running the latest version of Dataverse (4.17)? Is it possible the problem was fixed in a recent version? I wasn't able https://data-preproduction.inra.fr.

@djbrooke, maybe a developer could take a closer look?

**Comment by DS-INRA** [comment]
Thank you for the screenshots.

As for https://data-preproduction.inra.fr, it's using 4.10.1 version.
And I forgot to mention it but it is on our intranet, that's why you can't access it :( so I can only send you screenshots if needed, but I think we have similar examples actually.

I've opened your oai-pmh record and get the \&#xd; too, but they appear only if you display source code. You can also export the record and view locally, so I've added the xml exports of my own examples here just in case :
[xml.zip](https://github.com/IQSS/dataverse/files/3779309/xml.zip)

**Comment by djbrooke** [comment]
Hi @DS-INRA - are you able to upgrade to a new version to see if this issue is resolved?

**Comment by DS-INRA** [comment]
Sorry I didn't close the issue after testing it on the new version, it worked fine
