### ISSUE TITLE
File Path field missing detailed description on upload

### ISSUE THREAD

**Issue by shlake** [IQSS/dataverse#6280]
Uploading a file - when hovering over the "?" for the "File Path" field, the detailed description does not show.

Editing File metadata - hovering over the "?" does show the detailed description.

**Comment by pdurbin** [comment]
Confirmed as of 731f160 on my "dev2" server. Thanks for the bug report, @shlake !

**Comment by mheppler** [comment]
@shlake, thank you for opening this issue. This bug was noticed on the file upload pg while working to add a popover to metrics block on the dataset and file pgs (#6209), which required refactoring existing popover and tooltip code. (Sorry that I didn’t notice your issue sooner!) It has been fixed, and merged, and will be included in the next release, which is earmarked as 4.19.
