### ISSUE TITLE
As a metadata configurator, I want to display values of a controlled vocabulary as images

### ISSUE THREAD

**Issue by doigl** [IQSS/dataverse#6289]
In a metadata block for software basing on CodeMeta (see [thread in user mailinglist](https://groups.google.com/forum/#!topic/dataverse-community/nDMbMv4fKf4)) we tried to get Dataverse to display the values of a controlled variable as images linking to pages with more information about the values (see [repostatus.org for examples](https://www.repostatus.org/))

The corresponding value for displayFormat in tsv is
`<a href='https://www.repostatus.org/##VALUE'><img src='https://www.repostatus.org/badges/latest/#VALUE.svg' alt='ProjectStatus: #VALUE '/>`

The whole tsv-file is attached ([codemeta.tsv.txt](https://github.com/IQSS/dataverse/files/3744336/codemeta.tsv.txt)), the line concerned is about codeMetaDevelopmentStatus	(line 5) with the vocabulary in line 28.

As there is an example with an image in the [documentation for display formats.](http://guides.dataverse.org/en/latest/admin/metadatacustomization.html#displayformat-variables), the image itself doesn't seem to be the problem. Dataverse is ignoring everything I put into the displayFormat field, even something like (#VALUE). 

Is this because of the controlled vocabulary? Are there any other possibilities to change the appearance of the metadata fields? 

Other wishes would be to combine the values of a compound field, like `<a href="#VALUE_OF_SUBFIELD_URL">#VALUE_OF_SUBFIELD_TITLE</a>`.

**Comment by djbrooke** [comment]
@jggautier, let's discuss next week!

**Comment by pdurbin** [comment]
Thanks to @donsizemore it's now possible to spin up instances of Dataverse with custom metadata blocks using dataverse-ansible. Here's the issue I just tested and closed: https://github.com/IQSS/dataverse-ansible/issues/133

Since I tested with the metadata block in this issue, here are some screenshots of how it looks:

## full "Metadata for Research Software" metadata block

![Screen Shot 2019-11-18 at 5 00 48 PM](https://user-images.githubusercontent.com/21006/69097699-188a3580-0a25-11ea-9ea0-3517db604c50.png)

## the repo status field (edit)

![Screen Shot 2019-11-18 at 5 01 07 PM](https://user-images.githubusercontent.com/21006/69097700-188a3580-0a25-11ea-9eee-383561cc975d.png)

## the repo status field (view)

![Screen Shot 2019-11-18 at 5 03 41 PM](https://user-images.githubusercontent.com/21006/69097833-699a2980-0a25-11ea-892f-3ad6cb3a129f.png)

**Comment by poikilotherm** [comment]
@doigl controlled vocabularies are retrieved as localized values but not formated with `displayFormat`.

https://github.com/IQSS/dataverse/blob/5c040de9f3620513bd1da3e3b8747ee8d22a5b81/src/main/java/edu/harvard/iq/dataverse/DatasetField.java#L303-L317

(`DatasetFieldValue.getDisplayValue()` is doing the format  work)

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
