### ISSUE TITLE
API search with subtree param :add more hierarchy information in result

### ISSUE THREAD

**Issue by kiktestdmp** [IQSS/dataverse#6354]
if I run an API search to give me back all the data within a specific dataverse and it's children.

If for example I wanted to make an hierarchical browser instead of the default search interface which flattens the results.

so using a request like:
http://dataverse.domain.com/api/search?q=*&subtree=adataversename

I do get the datasetname to which a file belongs
I get the dataverse to which a dataset belongs
but I do not get information to which dataverse another dataverse belongs

is there a way to get this information to show in my result? Or is this functionality missing?

so I would like it to have parent_dataverse: xxxxxxx

A dataverse item only has : 
{
name: "asubdataversename",
type: "dataverse",
url: "https://..../",
identifier: "asubdataversename",
description: "description here",
published_at: "2019-10-17T08:32:55Z"
},.

**Comment by pdurbin** [comment]
@kiktestdmp hi! This is a good idea and the hierarchy is already indexed into Solr. However, database IDs are used instead of aliases, like this:

"subtreePaths":["/1576", "/1576/1577"],

Here's the search I did:

http://localhost:8983/solr/collection1/select?rows=1000000&wt=json&indent=true&q=bafacalo_dataset_subset

For this file:

![Screen Shot 2019-11-12 at 10 47 47 AM](https://user-images.githubusercontent.com/21006/68686610-e2871600-0539-11ea-9f5e-3f8aa97f986f.png)

Let me try to explain what `"subtreePaths":["/1576", "/1576/1577"],` means in this example.

- 1576/1577 means the "JOPD" dataverse
- 1576 means the Ubiquity Press dataverse

Would these numbers, these database IDs, be useful to you?

This example comes from https://github.com/IQSS/dataverse-sample-data by the way. 😄

**Comment by pdurbin** [comment]
@kiktestdmp hi! I'm just checking in again since I just mentioned this issue in pull request #6441 made today.

Would you be able to give a JSON example of what would be useful? You can see a great example of this (JSON before/now vs. JSON after/proposed) in #6300.

It would be easy to return the `subtreePaths` I mentioned above but I don't know if numbers like `/1576/1577` are useful to you.

It would also be easy to return "parent id" (database id of the "owner") but I don't know if that number is useful to you.

It sounds like you'd like the alias of the parent dataverse? Is that right? Anything else? Do you want other stuff? 😄

**Comment by pdurbin** [comment]
@kiktestdmp hi, still interested?
