### ISSUE TITLE
6383-editor

### ISSUE THREAD

**Issue by youssefOuahalou** [IQSS/dataverse#6407]
Hello, 
I have a small problem of adaptation I tried to change the size of line and column but I did not have any change.
I edit the file: datasetFieldForEditFragment.xhtml I changed the tag <p: inputTextarea to become <p: textEditor

[datasetFieldForEditFragment.txt](https://github.com/IQSS/dataverse/files/3886873/datasetFieldForEditFragment.txt)
![TextEditor](https://user-images.githubusercontent.com/46802308/69545914-04998300-0f93-11ea-9cb3-f86802a57de5.PNG)

**Comment by djbrooke** [comment]
Hi @youssefOuahalou, as I mentioned in the previous issue (#6253), I'm not sure we want to support this and I would not be inclined to accept a PR for this at this time. Some research needs to happen from an interoperability standpoint and technical standpoint, and we may need to change how we handle some characters in displays. This would be a larger effort and we don't have the bandwidth right now.  

The IQSS team is pretty busy with roadmap items (https://www.iq.harvard.edu/roadmaps) and other work, and we're heading into the holidays here in the US. I'm not saying "no" to this, I'm just saying not now. If you can organize members of the community to do some research on the implications and if there's broader interest, we could accelerate this with the community's help, but it's not a problem that's a priority to solve right now.

**Comment by mheppler** [comment]
@youssefOuahalou, I suggest that you close this issue and continue to use the first issue you opened last week (_Markdown wysiwyg #6383_), as the issue to track your feature request. In that issue, I am also going to add a comment outlining some of the outstanding metadata support and validation concerns that @djbrooke spoke of in his comment and why this feature request is not as simple as changing the form component in the UI.

For future developer related questions, I suggest you use the [Dataverse Dev mailing list](https://groups.google.com/forum/#!forum/dataverse-dev), which you can find linked in our [Developer Guide](http://guides.dataverse.org/en/4.18.1/developers/intro.html).

That said, thank you for providing a code snippet and screenshot, in order to help replicate your issue. It appears this is a simple CSS fix, by removing the Bootstrap `form-control` style class, as well as removing the `rows` and `cols` attributes that are not used with this component, and adding some inline CSS to the PrimeFaces component. (Also added the toolbar facet to customize the formatting options displayed.)

```
    <p:textEditor value="#{dsfv.valueForEdit}" id="description" pt:aria-required="#{dsf.required}"
                  height="180" style="height:220px;"
                  rendered="#{dsfv.datasetField.datasetFieldType.fieldType == 'TEXTBOX' }">
        <f:facet name="toolbar">
            <span class="ql-formats">
                <select class="ql-font"></select>
                <select class="ql-size"></select>
            </span>
            <span class="ql-formats">
                <button class="ql-bold"></button>
                <button class="ql-italic"></button>
                <button class="ql-underline"></button>
                <button class="ql-strike"></button>
            </span>
        </f:facet>
    </p:textEditor>
```

<img width="1165" alt="Screen Shot 2019-11-25 at 3 31 54 PM" src="https://user-images.githubusercontent.com/687227/69575712-c8692100-0f98-11ea-99c2-ac48b08653da.png">

**Comment by youssefOuahalou** [comment]
Thank you for your comments, I already tried this but removing the form-control we have errors in the display
![dataverseErrorMetadat](https://user-images.githubusercontent.com/46802308/69616437-e9804f00-1036-11ea-9042-8742cb89d919.PNG)

**Comment by youssefOuahalou** [comment]
Thank you very much my concern is solved

**Comment by youssefOuahalou** [comment]
Thank you very much my concern is solved
![TextEditorNewdataset](https://user-images.githubusercontent.com/46802308/69624244-9f9e6580-1044-11ea-8dad-659ab0d8d550.PNG)
![CodeTextEditor](https://user-images.githubusercontent.com/46802308/69624245-a200bf80-1044-11ea-9a04-c9e9b5b53f47.PNG)
![ExempleIphoneX](https://user-images.githubusercontent.com/46802308/69624258-a4fbb000-1044-11ea-8ee1-501c93b83f11.PNG)
