### ISSUE TITLE
Can't preview in page for files in prior public dataset versions

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#6421]
Related to #6419 (and I asked about this there but am creating a separate issue), if there is more than 1 published version of a dataset, files in the earlier versions can't be previewed in page. This means that files that have been deleted can't be previewed at all and current files can only be previewed if they are accessed via the latest published version. I'm not sure if this was intended or is needed (these are still publicly accessible files). 
The related PR resolves this and still keeps all of the other limits to avoid previews of files that have restrictions/conditions/are in draft datasets/are in datasets with access terms...

**Comment by scolapasta** [comment]
@qqmyers I can't remember if there was a specific issue in allowing previewers on older versions or if it was just part of the "previewers on current versions adds value; let's get that in while we consider older versions".

Since this only adds the previewers for public files still, let's test this and merge.
