### ISSUE TITLE
delete DOI link from the citation block

### ISSUE THREAD

**Issue by benzaked** [IQSS/dataverse#6423]
Hi,
I'm recently deployed Dataverse at my organization. most of our data are privet (users privacy) and the server sits behind our corporate firewall. So we are not using DOI service at all. I wish to delete the DOI link from the site as discussed [here](https://github.com/IQSS/dataverse-docker/issues/30#issuecomment-559072171) 
Does anyone know how to do that? 
Thanks!

**Comment by pdurbin** [comment]
This reminds me a lot of the following issue: 

Make dataset DOI publication optional #3652

**Comment by djbrooke** [comment]
Hi @benzaked, I'll leave this open for a little while, as someone may have some suggestions on how to remove this (or may have some custom code for this), but it's not a feature request we'll consider adding or merging at this time, as the DOI is one of the most important things in data sharing. There's some chance that we'll revisit this in the future, but I don't feel it's likely.

**Comment by RightInTwo** [comment]
@benzaked Hi there! If I understand you correctly, you would be well off with using Handles instead of DOIs. See http://guides.dataverse.org/en/latest/installation/config.html#configuring-dataverse-for-handles for details. Handles do not carry any metadata (like DOIs do), they only provide a persistent id (PID) which will forward to the correct URL in your dataverse. We are using handles in our institute's dataverse as well. The one thing needed is a handle server, which you could setup yourself. We decided against that (because it would be another system to manage) and buy that as a service from https://www.pidconsortium.eu/. For a more detailed explanation, feel free to contact me via PM.

P.S.: Getting rid of PIDs overall is not an option that works with dataverse's architecture, as all mechanisms for datasets are based on using the PID as the identifier of the object.
P.P.S.: The customization of citations is something discussed in #5486 and #2297

**Comment by djbrooke** [comment]
Thanks @RightInTwo for the suggestions for @benzaked. I'm going to close this since we wouldn't want to make any code changes here.

**Comment by benzaked** [comment]
Thank you all!
