### ISSUE TITLE
Replicate theme folder for installation with several nodes

### ISSUE THREAD

**Issue by DS-INRA** [IQSS/dataverse#6491]
The folder containing the theme images (glassfish/domains/datainra/docroot/logos/) is not replicated on installations with several nodes.
Therefore (on an installation with several nodes), if a dataverse administrator adds or changes its theme image using the UI, when another node is used the image can't display, as the image will be only on the active node when the user uploaded it.

**Comment by pdurbin** [comment]
@DS-INRA yes, we should do something about this. There are a number of related directories that need to be synchronized or otherwise handled when multiple Glassfish servers are in use. I've been trying to keep a list at http://guides.dataverse.org/en/4.18.1/installation/advanced.html#multiple-glassfish-servers and here's a screenshot:

![Screen Shot 2020-01-08 at 3 05 39 PM](https://user-images.githubusercontent.com/21006/72011680-59821780-3228-11ea-9ebc-ebd83e594554.png)

The image/logo bug is the most easily visible problem from the UI but is it safe to assume you're looking for solutions for all of the above (sitemap, MDC, etc.) when running multiple Glassfish servers? I'm asking because I'm thinking about what the "scope" of this issue should be and if we should adjust the title to be about more than just the theme.

https://github.com/IQSS/dataverse-kubernetes/issues/10 is related.

**Comment by pdurbin** [comment]
@DS-INRA over at http://irclog.iq.harvard.edu/dataverse/2020-01-08#i_116005 @poikilotherm pointed out to me that he worked on some of this stuff in dataverse-kubernetes (community supported, by the way) and documented it. Sorry for the comically large arrows I added:

From https://dataverse-k8s.readthedocs.io/en/latest/day1/storage.html

![Screen Shot 2020-01-08 at 3 17 15 PM](https://user-images.githubusercontent.com/21006/72012875-bbdc1780-322a-11ea-9b0b-5d997cd14537.png)

From https://dataverse-k8s.readthedocs.io/en/latest/images/dataverse-k8s.html#important-directories

![Screen Shot 2020-01-08 at 3 20 25 PM](https://user-images.githubusercontent.com/21006/72012874-bbdc1780-322a-11ea-8c19-2397b6c1132f.png)

You are, of course, welcome to join us in chat: https://chat.dataverse.org

**Comment by pdurbin** [comment]
@DS-INRA is this still an issue for you? Is the documentation mentioned above enough? Did you write a script to replicate content across nodes?

**Comment by pdurbin** [comment]
@DS-INRA please keep an eye on this PR:

- #9662

I think it will address your problem.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
