### ISSUE TITLE
Tests not executed as expected on jenkins.dataverse.org

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6528]
The integration test suite is "failing" according to the tag on the bottom of the readme. If we look at the build in question it shows no failures but it skipped most of the tests in the API test suite:

https://jenkins.dataverse.org/job/IQSS-dataverse-develop/307/testReport/edu.harvard.iq.dataverse.api/

We should determine what's preventing the test suite from running to completion, resulting in these failure messages.

**Comment by landreev** [comment]
It really looks like it's failing while still installing and setting up Glassfish; specifically when it tries to patch Weld, because the following url is no longer valid: 
http://central.maven.org/maven2/org/jboss/weld/weld-osgi-bundle/2.2.10.SP1/weld-osgi-bundle-2.2.10.SP1-glassfish4.jar
the location is not completely dead, but returns "501 - https required". Changing `http:` to `https:` works, but gives a cert warning (so if downloading via wget/curl, extra params will be needed to force insecure connection...)
Switching to 
https://repo1.maven.org/maven2/org/jboss/weld/weld-osgi-bundle/2.2.10.SP1/weld-osgi-bundle-2.2.10.SP1-glassfish4.jar
however makes it work, without https warnings.

**Comment by landreev** [comment]
(seeing how it was a setup failure, I was assuming initially it had something to do with merging of my installer branch - the timing was really suspicious; but this thing isn't using the installer at all, neither old nor new...)

**Comment by donsizemore** [comment]
@landreev I updated dataverse-ansible yesterday; running manually in Jenkins now to test.

**Comment by landreev** [comment]
@donsizemore Thank you!

**Comment by donsizemore** [comment]
@landreev it's the maven switch to https, but Jenkins hits the first error during the 'maven package' step:

```
[INFO] ------------------------------------------------------------------------
[INFO] Building dataverse 4.18.1
[INFO] ------------------------------------------------------------------------
Downloading: http://repo1.maven.org/maven2/org/swordapp/sword2-server/1.1-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.swordapp:sword2-server:1.1-SNAPSHOT/maven-metadata.xml from/to central-repo (http://repo1.maven.org/maven2): Failed to transfer file: http://repo1.maven.org/maven2/org/swordapp/sword2-server/1.1-SNAPSHOT/maven-metadata.xml. Return code is: 501 , ReasonPhrase:HTTPS Required.
```

I hit the same error outside of Jenkins.

**Comment by landreev** [comment]
@pdurbin - I thought we were supplying sword jar(s) with the dataverse source locally, why is it even trying to download stuff from the maven repo?

**Comment by landreev** [comment]
thank you Don!

**Comment by pdurbin** [comment]
> I thought we were supplying sword jar(s) with the dataverse source locally, why is it even trying to download stuff from the maven repo?

Yeah, that `Downloading: http://repo1.maven.org/maven2/org/swordapp/sword2-server` stuff has been a head scratcher for me for years. Some day it would be nice to fix it so our builds don't attempt that download. Lots of technical debt. 😄 

@donsizemore thanks for the pull request! 🎉
