### ISSUE TITLE
Multiple 'related publication' fields are not shown in metadata summary

### ISSUE THREAD

**Issue by mderuijter** [IQSS/dataverse#6546]
## Context:
This is an issue directly related to the following discussion with the Dataverse Community: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/dataverse-community/PsHYVKGxYng/TZSU-N8gAwAJ

Some of the users at DANS noticed that when they filled in more than one related publication, only the first one is shown on the dataset page in the metadata summary. But the complete list of related publications is visible under the metadata-tab. 

## Example: 
![image](https://user-images.githubusercontent.com/56864998/72790072-26cb1c80-3c35-11ea-8873-f652deaa9580.png)

## The following solution was discussed: 
If there's more than one related publication, a coded message "Click the metadata tab below to see more related publications" should appear next to the first related publication. 
The coded message will not be saved as a value in the metadata field.

**Comment by TaniaSchlatter** [comment]
Thanks @mderuijter for opening this issue. Another solution is to change the text in the tool tip for Related Publication. For example, instead of what it says now, it could say:

"First publication that uses data from this Dataset. See the metadata tab for all related publications."

<img width="449" alt="Screen Shot 2020-01-21 at 3 54 59 PM" src="https://user-images.githubusercontent.com/15386424/72842591-acb38b80-3c66-11ea-9436-37a1864dfced.png">

**Comment by mderuijter** [comment]
Hi @TaniaSchlatter, that could work too. But I managed to implement the first solution relatively easy: 
![image](https://user-images.githubusercontent.com/56864998/72877814-01ecad00-3cfa-11ea-9625-049b2e2355e9.png)



The message appears only if there's more than one Related Publication:
![image](https://user-images.githubusercontent.com/56864998/72877655-afab8c00-3cf9-11ea-8298-cf6a75555f74.png)


This way the tool tip information stays consistent with the other tool tips. Plus I think it'll be a bit clearer at first glance.

**Comment by pdurbin** [comment]
One thought I have on this is that while tooltips for metadata fields are shown in the GUI I can imagine them being exposed via API so we may not want to have them refer to GUI elements such as buttons and tabs.

**Comment by djbrooke** [comment]
@mderuijter @TaniaSchlatter We'd really want to use the tooltip instead of introducing another help method into the application. This is for consistency and for scalability. I feel it will be challenging to manage the help text one-offs if we start adding them. 

@pdurbin point taken. Do we already do this (provide tool tip text in API responses) or would this be a future feature?

**Comment by pdurbin** [comment]
@djbrooke no, the tooltip isn't exposed but if you go to http://localhost:8080/api/admin/datasetfield/publication for example, you'll see something like this:

```
{
  "status": "OK",
  "data": {
    "name": "publication",
    "id": 29,
    "title": "Related Publication",
    "metadataBlock": "citation",
    "fieldType": "NONE",
    "allowsMultiples": true,
    "hasParent": false,
    "controlledVocabularyValues": [],
    "parentAllowsMultiples": "N/A (no parent)",
    "solrFieldSearchable": "publication",
    "solrFieldFacetable": "publication_ss",
    "isRequired": false
  }
}
```
