### ISSUE TITLE
Entire Application: Eliminate extra white space on pages

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#656]
---

Author Name: **Elizabeth Quigley** (@eaquigley)
Original Redmine Issue: 4106, https://redmine.hmdc.harvard.edu/issues/4106
Original Date: 2014-06-17
Original Assignee: Mike Heppler

---

From meeting with Gary:

All create, view, and edit pages for dataset: compress and get rid of all the extra white space.

**Comment by mheppler** [comment]
Related to #1319 -- maybe even a duplicate.

**Comment by mheppler** [comment]
Related: Dataverse - Create/Edit General Information Top Section Clean Up #1429

**Comment by eaquigley** [comment]
Moving to Beta 14 but most likely will be passed to QA and closed on 2/26 after a UI review.

**Comment by mheppler** [comment]
Had our UI review on 2/26 and concluded that we have sufficiently addressed this issue, where it mattered most, on the dataset page.

**Comment by eaquigley** [comment]
White space has been eliminated. Closing ticket.

**Comment by jggautier** [comment]
I was looking at citation metadata in Harvard Dataverse and came across this related publication metadata in IFPRI's dataverse. They're using html paragraph breaks in the Citation text box in order to create space between each compound field:

![screen shot 2019-01-18 at 11 25 09 am](https://user-images.githubusercontent.com/18374574/51567222-ad9fba80-1e64-11e9-82dc-7547688de0bc.png)

So that the metadata displayed in the UI is more readable:
![screen shot 2019-01-18 at 11 25 09 am](https://user-images.githubusercontent.com/18374574/51567409-2272f480-1e65-11e9-8ad3-7e0f0231c734.png)

Was this github issue (#656) an effort to make sure that the UI doesn't have spaces like these?

**Comment by mheppler** [comment]
@jggautier I’d suggest opening a new issue to specifically report this spacing issue with multiple entries to the Related Publication metadata field. This ancient 4.0 beta artifact is so old and vague that I doubt it is relevant.

**Comment by pdurbin** [comment]
@jggautier the "tighten up" comment indicates that this issue was more about the ratio of positive space and negative space: https://en.wikipedia.org/wiki/Negative_space . That's my recollection anyway.
