### ISSUE TITLE
Handle long strings in the UI

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6578]
There are a few issues with the display of longer strings in the UI:

- https://github.com/IQSS/dataverse/issues/5350
- https://github.com/IQSS/dataverse/issues/4484
- https://github.com/IQSS/dataverse/issues/1634

This isn't a major issue but it's for sure an annoying one for now, and it has implications for I18N. I'm interested in fixing the reported cases but also interested if there's some way to handle this well generally. Screenshots of each case are included here. 

![7d41b49a-c749-11e4-8757-b5366f33fcf8](https://user-images.githubusercontent.com/7773392/73106231-eedc0780-3ec8-11ea-94f1-40c0ffdb2c9e.jpg)
![37047009-c70af65e-2137-11e8-8b0e-b50913b7a375](https://user-images.githubusercontent.com/7773392/73106232-eedc0780-3ec8-11ea-89d3-0dc54796dbb6.png)
![49163032-29183c00-f2fa-11e8-8a4d-fa45bc4240c2](https://user-images.githubusercontent.com/7773392/73106233-eedc0780-3ec8-11ea-90db-cfb3a3b91e44.png)

**Comment by mheppler** [comment]
Research for _Truncate methods: checksums, long summary metadata fields #6685_ will provide potential solutions for some of these issues. Might need to break this issue up into separate, case by case solutions, as opposed to one site wide solution provided in a single PR.

Suggested spinning off the account pg email display issues as UI clean in issue _Email Verification: 2 issues; refresh un-verifies, verify email button should always be available. #3438_.

**Comment by mheppler** [comment]
Closing this issue, as other issues have been moved forward to fix these issues or are covered in remaining issues. Outline of the housekeeping as follows...

- Account email verified label overlap #4484 ... this issue was resolved in the PR #7516 for issue #3438
- Manage Permissions assign role label and description cleanup #5350 ... this issue was resolved in PR #7615
- Dataset description does not wrap #1634 ... this issue is being tracked in #6685 which will move forward in place of this issue
