### ISSUE TITLE
Payara Documentation Updates

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6593]
As we move towards upgrading app server requirements to Payara 5, we'll need to update our installation and developer guides. We should also do a check of other guides to see if there are any references to glassfish 4.1 there.

**Comment by scolapasta** [comment]
The biggest pending question is whether we will wait for Payara to ship with jsf 2.3.14 or whether we patch Payara 5.194 to use jsf 2.3.14. This will, of course, affect the installation process.

**Comment by poikilotherm** [comment]
[Payara 5.201 has been released yesterday](https://github.com/payara/Payara/releases/tag/payara-server-5.201).

It [contains the JSF 2.3.14 update](https://github.com/payara/Payara/pull/4492), so no manual patching necessary.

**Comment by pdurbin** [comment]
I made pull request #6816 yesterday and @donsizemore replied in IRC with "sir. we prefer small commits in small chunks." 😆 

I added "payara" 333 times in this pull request. There is demand internally to try to change some of these to "app server" so I pulled this out of code review.

That said, future code reviewers are welcome to think about the following (also in the pull request):

- Details about a patch to Mojarra (JSF) have not yet been included.
- An attempt was made to use a Unix user called "dataverse" instead of "glassfish".
- In the Installation Guide, should we delete the old Two Ravens content? I put a note saying "Please note that in the text below, Glassfish was changed to Payara but not tested."
- When should we update Vagrant code?
- When should we update docker-aio code?
- When should we update docker-dcm code?
- Should we clear out the "Containers" page in the dev guide and delete the related scripts, Openshift config and Docker files? The content is old and references Glassfish.

**Comment by pdurbin** [comment]
> try to change some of these to "app server"

done in f7923f464
