### ISSUE TITLE
File Page Redesign

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6604]
Now that we've taken in and analyzed user feedback on the Dataset and File Page (#3404), we should move towards implementation. The plan is to implement the new file page and new dataset page as individual issues instead of one larger issue. 

@TaniaSchlatter to include a mockup here. We'll plan to discuss before this enters a sprint.

**Comment by TaniaSchlatter** [comment]
Note that the primary goals of this redesign are to: 

1. address scaleability to better support a variety of browser states (responsiveness to browser viewport shifts and mobile access)

2. improve accessibility and compliance with WCAG 2.0 standards

3. communicate information and functionality in concert with the redesigned Dataset page (#6605), including supporting more informative file previews.

**Comment by TaniaSchlatter** [comment]
Our intern Jonathan Ji completed a heuristic review of most if not all preview types on the file page. Here are his Key Summary/Observations from the [full doc](https://docs.google.com/document/d/1tpc39Oo3QgfzfWm352istLteSHn06pM7jm1_Ku6yNAk/edit): 

- System response – loading graphic – should be included in all file preview types before it loads -> there's seems to be different types of loading responses 
- Unclear how the user knows what type of file they are looking at 
- Preview is presented differently within all file types 
- Wondering what the “Explore on” button actually is? Is it the preview on a different page? 
- Tabbing works on every page, even within the file previews 
- Size of the preview should be adjusted so that previews fit within the viewport and controls are visible (#7, #18, #10)
- All previews are important, but adjusting the size and the making clear the ability to zoom and scroll will be helpful to end users
