### ISSUE TITLE
Dataset Page Redesign 

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6605]
Now that we've taken in and [analyzed user feedback](https://docs.google.com/presentation/d/15lHibiyVZJr0JAHvBEKsETrVaSOZpvWuKTrHYuvBv1s/edit#slide=id.g6e2e2594b4_0_0) on the Dataset and File Page (#3404), we should move towards implementation. The plan is to implement the new file page and new dataset page as individual issues instead of one larger issue. 

@TaniaSchlatter to include a mockup here. We'll plan to discuss before this enters a sprint.

**Comment by TaniaSchlatter** [comment]
Note that the primary goals of this redesign are to: 

1. address scaleability to better support the growing variety of dataset-level functions and tools 
2. improve accessibility and compliance with WCAG 2.0 standards
3. support a variety of browser states (responsiveness to browser viewport shifts and mobile access)
4. communicate information and functionality in concert with the redesigned File page (#6604).

**Comment by TaniaSchlatter** [comment]
This issue is a work in progress, not a development-ready spec
Link to mockups: https://sketch.cloud/s/o5ZK3/a/OMPJGR
Itemization of changes:

- Remove name of dataset from breadcrumb
- Move dataset thumbnail into citation block
- Add clipboard icon and click to copy functionality to PIDs in citation block
- Change layout and styling of action buttons on the top of the dataset page 
- Change styling and layout of metrics block
- Adjust the layout of summary metadata to reduce space between labels and text
- Truncate summary metadata and enable open/close functionality to view all
- Update styling of file table tabs
- Refine layout of file table sort/filter/search functions
- Change file table button style and appearance in the UI to maximum 3 icon buttons  (3rd being "kabob" to display additional actions in a dropdown)
- Change table "cards" to responsive design, truncate file labels if needed
- Truncate UNFs, MD5s, etc. to show first 4-7 and last 3 characters

**Comment by pdurbin** [comment]
> Link to mockups: https://sketch.cloud/s/o5ZK3/a/OMPJGR

"We cannot find this document. It might have been deleted or moved, or you could have the wrong URL for it."

Bummer that we can't see the mockups any more.

As shown with the strikethroughs  above, we did most of this stuff. I'd like to suggest that new targeted issues be created for any remaining tasks.
