### ISSUE TITLE
Multistore: Metadata Export fails - tries to save in dataverse.files.directory, instead of the store

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#6666]
The various export format cache files representing dataset metadata are normally written to the storage identifier location upon dataset publish. This is not happening for file type storage when the name of the file storage identifier is anything other than "file", ie. "file1", etc.

This does work for S3 and does work when storage identifier is named "file".

**Comment by qqmyers** [comment]
Looks like the cached files are going to the default store rather than the same one as the dataset. @kcondon - is that consistent with the symptom above?

**Comment by kcondon** [comment]
@qqmyers It does not appear to be going to the default store, rather it creates two of the several cached files where it should but they are 0 length.

**Comment by qqmyers** [comment]
Hmm - very odd. In TDL's branch, I see the files showing up in the current store rather than the one used by the dataset (only occurs if the setting on the dataverse changes after the dataset is created). This will cause errors/duplicate re-creations of the cached files /failure to delete old ones, etc. 
I'm not sure whether that will fix what you're seeing or not since the main 'store the file' logic should be the same for all exports. Maybe there's another problem if one of the types is trying to read a file (or an aux of some file). 

I'll keep looking.

**Comment by landreev** [comment]
> @qqmyers It does not appear to be going to the default store, rather it creates two of the several cached files where it should but they are 0 length. Almost like two formats are more forgiving to the error that causes 0 length and then it hits a format that throws a hard failure and exits the process but that is speculation.

These two zero-length files (export_schema.org and export_dcterm) is what ends up in the dataset directory when you publish. 
you can then go to the metadata tab on the page, and request any of the available format - and it'll fail the same way; you get an empty page, and a zero-length file "cached" in the directory.

**Comment by landreev** [comment]
I'm also going to take a look. Could be something simple, like something hard-coded for the "file:" case. 
Since these are *dataset*-level files (as opposed to "normal" files, associated with datafiles), there may be something irregular/custom about how it was implemented, that's now breaking under the new framework.

**Comment by qqmyers** [comment]
I think the problem I mentioned in the other PR is at least part of the issue. The ExportService code looks like it writes a 0 length file if no temp file is required. That code hasn't changed in a long time though so I'm surprised. See https://github.com/IQSS/dataverse/pull/6490/commits/de4c5d01ad6e85a9a515da96f59af7740eff4869 which I'll pull out into a separate PR. Check the path if Line 258 succeeds in creating an outputStream, which it should for a file store, leaving tempFileRequired == false. The if clause at line 268 writes the contents to a different file and closes the outputStream (0 bytes). For S3 stores, which fail to open a stream, the other branch of the if is used and that works.

**Comment by qqmyers** [comment]
I also made a separate commit that I'll include in the same PR that avoids the issue I saw w.r.t. aux files going to the wrong place.

**Comment by landreev** [comment]
The lines in `ExportService` are indeed very old. 
I'm assuming export on filesystem storage was working until now because, when `(!tempFileRequired)`, we were writing the stream into `cachedMetadataFilePath`, created in line 265; and NOT into the `outputStream`, as you noted. (so, `outputStream.close()` in line 273 was NOT causing a zero-length file, because content has already been written into that file, via a different descriptor). 
And then with the Multi File Store PR the `Dataset.getFileSystemDirectory()` method (that the line 265 relies on) must have stopped working - hence the behavior we saw. 

That code in `ExportService` needs to be cleaned up of course. (teaches us right, exploiting interns' labor, lol). The `dataset.getFileSystemDirectory(`) method we should just get rid of... it's a remnant from the times before the `DataAccess` framework was expanded to cover dataset-level objects.

I'll take a look at what's going on with dataset logos. (that must be the only other known case, of a dataset-level stored file, I believe; other than the metadata exports)

(Sorry if I just repeated something you had already explained)

> I think the problem I mentioned in the other PR is at least part of the issue. The ExportService code looks like it writes a 0 length file if no temp file is required. That code hasn't changed in a long time though so I'm surprised. See [de4c5d0](https://github.com/IQSS/dataverse/commit/de4c5d01ad6e85a9a515da96f59af7740eff4869) which I'll pull out into a separate PR. Check the path if Line 258 in the old code succeeds in creating an outputStream, which it should for a file store, leaving tempFileRequired == false. The if clause at line 268 writes the contents to a different file and closes the outputStream (0 bytes). For S3 stores, which fail to open a stream, the other branch of the if is used and that works.

**Comment by qqmyers** [comment]
@landreev - I think you're onto something, Dataset.getFileSystemDirectory() uses System.getProperty("dataverse.files.directory") so the write to the 'cached' stream goes there while the outputStream goes to the right store (assuming the default hasn't changed - the other issue). So presumably there are now two files being written - one zero byte.

I only see two more places that getFileSystemDirectory is used - I can go ahead and remove those and the method so it won't bite anyone else.

**Comment by landreev** [comment]
Alternatively, I can go through it next week and clean up/remove these instances. As I said, this is a legacy artifact, that we should've got rid of long time ago.

**Comment by landreev** [comment]
>  So presumably there are now two files being written - one zero byte.

I don't think the actual metadata export file is being written at all now - because that code tries to write it into a file in a directory that does not exist. (the top-level default file directory - `dataverse.files.directory` does exist, but the directory for the dataset does not).

**Comment by qqmyers** [comment]
Yeah - that could be the reason for the IOException reported in https://github.com/IQSS/dataverse/pull/6488#issuecomment-587970676 ?

**Comment by qqmyers** [comment]
@landreev - I've replaced the one use of Dataset.getFileSystemDirectory() that was in FileAccesIO that should be store-aware, but I left one use of it with packageFiles where I think the storage still is independent of the storageIO model. (I've tried to avoid changing anything that would affect them elsewhere so I think using the default dir here would still be the right choice. Not sure though.

**Comment by landreev** [comment]
> @landreev - I've replaced the one use of Dataset.getFileSystemDirectory() that was in FileAccesIO that should be store-aware, but I left one use of it with packageFiles where I think the storage still is independent of the storageIO model. (I've tried to avoid changing anything that would affect them elsewhere so I think using the default dir here would still be the right choice. Not sure though.

Thank you. I'm seeing that one remaining Dataset.getFileSystemDirectory(), used in the context of a package file in DeleteDataFileCommand. It makes sense not to touch anything package file-related at this point. However, the method is never used when package files are actually created; it looks like all that code in FileRecordReader, FileRecordWriter, ImportFromFileSystemCommand.java etc. just go directly to whatever `dataverse.files.directory` is set to. I'm debating if i should modify DeleteDataFileCommand to do the same - and then I can just comment out Dataset.getFileSystemDirectory() completely. 
I'll move it along one way or the other momentarily.
