### ISSUE TITLE
Requesting Box Integration

### ISSUE THREAD

**Issue by jmjamison** [IQSS/dataverse#6680]
UCLA uses Box not Drop Box.   Box integration would be helpful for our Dataverse installation. Thank you.

**Comment by mheppler** [comment]
Related to _**File Uploading: Add Google Drive & other options #1746**_.

**Comment by shlake** [comment]
Note on something I have run into with University "sanctioned" Box. Institution Box accounts seem to be different from ordinary Box accounts. I think each institution decides on "approved" connections. For example, I used to be able to use my UVA Box with my OSF account, I can't any more and get this error when trying to connect: **Disabled by Administrator: This application cannot be used because it is not allowed by your Box administrator.**

**Comment by pdurbin** [comment]
@jmjamison hi! Are you still interested in this? Thanks.

**Comment by jmjamison** [comment]
Yes, I am still interested.

**Comment by cmbz** [comment]
2024/09/30: Closing. Better to solve this problem using the external tool option instead. We will open another, more general issue that covers this particular use case.
