### ISSUE TITLE
Layout and styling of action buttons on the dataset and file page

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#6684]
Related issues: #3341 #3404 #3815 #6072 #6605 #6604 #6085 #6450 

Design to address the addition of action buttons at the dataset level (scaleability), improve the visibility of edit button, and prepare for responsive design. 

Changes to the dataset action buttons apply to the File page action buttons 

Implementing a new design will provide the opportunity to address accessibility issues found on buttons

Link to mockups: https://sketch.cloud/s/mWGQJ/a/4KZgLZ

Dynamic "run in..." link under the Download/Access button functionality is out of scope for this effort

Design to dos:
- [x] inventory: list of all button options, conditions for appearance, and behavior of states for both dataset and file actions – [version 1](https://docs.google.com/spreadsheets/d/1guVKxR00vS6ICBuJSkvwDefrK9vw_-SJDgp9mi4Jxr4/edit#gid=823971545) | [version 2](https://docs.google.com/spreadsheets/d/12TNSplVTxwBnNm3cj3MwpQW_4djTn9_G9hA01Cz_xq0/edit#gid=183143698)
- [x] review the inventory and designs to determine if all situations/configurations are planned for, or needed additions
- [ ] mock up any common configurations and/or states that are missing if needed 
- [ ] map buttons to bootstrap styles (create custom bootstrap theme if needed)
- [ ] update style guide with new styles

**Comment by mheppler** [comment]
Lots and lots has been moving and changing in order to deliver the improved button style and responsiveness of page layout. Here is a detailed outline of completed improvements and remaining to-do's.

**TEMPLATE**

_Breadcrumbs_
- [x] removed highlighted/bold current page
- [ ] added render logic to hide on root datasets

**FILE PG**

_Responsive layout_
- [x] moved citation, button, metrics, deaccession reason
- [x] improved responsive grid col widths
- [x] added Bootstrap 3 layout order hack (https://stackoverflow.com/a/24834574)

_File Name header_
- [x] increased font size 

_Ingest Warning icon_
- [x] moved next to file name, removed from file
- [x] download-buttons fragment

_Restricted Access/Lock icon_
- [x] moved next to version, publication status labels

_Publication Status labels_
- [x] removed colors, switched to default

_Citations_
- [x] added new button styles, responsive col widths
- [x] CSS word-wrap: break-word for xs viewport + DOI link

_Action buttons_
- [x] added new layout, larger, added "File" to text labels
- [x] added new Access File btn, and btn-primary style
- [x] moved Download, Request Access, Explore, Compute as dropdown options under Access File btn
- [x] moved Configure btn as dropdown option under Edit File brn
- [x] fixed Configure>Map unpublished popup
- [x] improved render logic

_Metrics_
- [x] added new style

_Deaccession Reason_
- [x] improved render logic, added new styles

_Metadata Tab > Add + Edit Metadata btn_
- [x] improved render logic for dataset lock

**DATASET PG**

_Responsive layout_
- [x] added Bootstrap 3 layout order hack (https://stackoverflow.com/a/24834574)

_Dataset Title header_
- [x] increased font size

_Publication Status labels_
- [x] removed colors, switched to default

_Citation_
- [x] added new button styles, responsive col widths
- [x] CSS word-wrap: break-word for xs viewport + DOI link

_Thumbnail/Icon_
- [x] moved to citation block
- [x] increased font size of icon
- [ ] increased thumbnail size 140 px (#6769)

_Action buttons_
- [x] added new layout, larger, added "Dataset" to text labels
- [x] added new Access Dataset btn, and btn-primary style
- [x] moved Download, Explore, Compute as dropdown options under Access Dataset btn
- [x] improved render logic
- [x] fixed publish btn render logic for deaccession (thank you, @sekmiller) 

_Metrics_
- [x] added new style

_Summary_
- [x] moved, improved responsive layout, removed containers

_Deaccession Reason_
- [x] improved render logic, added new styles

**DATSET PG FILE TABLE**

Ingest
- [x] moved ingest icon/msg

Actions
- [x] converted default button style to icon text link style
- [x] added title tooltip
- [x] added aria-label to btn-group containers
- [ ] fix tooltip disabled btn state

Here are the remaining high-level to-do's to be addressed here or spun off into other issues.

...

**Comment by mheppler** [comment]
Wanted to add a note here that the PR #6830 for issue **Change default thumbnail size #6769** was merged into the `6684-dataset-pg-btn-responsive` branch for this issue. It added a new `DEFAULT_DATASET_THUMBNAIL_SIZE` 140px image size to ImageThumbConverter.java, which is now being used to deliver a larger dataset thumbnail image to the new layout for the dataset pg.

**Comment by mheppler** [comment]
After talking briefly @qqmyers about the analytics code and some event tracking issues I've discovered with the new UI, I am going to spin off a new issue (#6938) to detail all the fixes required in the new button UI code, as well as changes required to the analytics code. These changes will require release notes for sysadmins to update their installation's analytics code if they use event tracking code provided in the Installation Guide.

Here are is the current list of known analytics event tracking issues for the file pg. I did not continue with the same detailed review on the dataset pg once the changes were deemed significant enough to spin off into a new issue.

**FILE PG**
- error 500 pg cite data file btn, event works
- tabular download btn w/submenu event broken (btn w/o dropdown/pdf works)
- pdf/multi explore btn w/submenu event broken (btn w/o dropdown/txt works)
- pdf/tabular/multi preview btn w/dropdown event broken (no btn w/o dropdown)
- events double counted... ACCESS > DOWNLOAD X2... ACCESS > EXPLORE > WORLD MAP X2...
