### ISSUE TITLE
Spike: investigate adding folder support to Primefaces upload component

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#6696]
Currently when you drag a folder into the file upload component, the structure is flattened. There is a primefaces issue: https://github.com/primefaces/primefaces/issues/2705 but no plan for them to work on it.

This issue is for us to investigate either adding the code to primefaces ourselves or finding some other workaround.

**Comment by djbrooke** [comment]
@scolapasta is this a dupe and/or possible solution to #6692  ?

**Comment by pdurbin** [comment]
This may not be needed now that @qqmyers has created https://github.com/gdcc/dvwebloader ! 🚀 🎉

**Comment by jggautier** [comment]
I'd have concerns about only adding dvwebloader in Dataverse repositories as a solution to letting depositors more easily upload files organized in folders without needing to first compress them in a zip file (and have Dataverse retain that structure so it can be displayed and re-created on download).

The dvwebloader option is displayed in the dataset page's "Access" dropdown menu. I don't think that depositors would know to look there in order to upload the folders that contain their data. And if they did, I don't think they know that the menu's dvwebloader option is what would let them upload folders.

Is dvwebloader added in a Dataverse repository now, and what do depositors think about how it works?

**Comment by qqmyers** [comment]
W.r.t. the Access menu, see #9095 / #9096.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
