### ISSUE TITLE
Docker-Compose: Better development env setup

### ISSUE THREAD

**Issue by alaxalves** [IQSS/dataverse#6709]
I have realized through [this](http://guides.dataverse.org/en/latest/developers/dev-environment.html) guide page, that contributing to dataverse project is very difficult since it requires a lot of package installing. Since there is already docker image support, one could "easily" configure a docker-compose yaml file that could abstract everything described by the guide page. I'd be interested on working on this, if the community has any interest on this feature, and is willing to able available on this issue to discuss and answer eventual questions.

**Comment by poikilotherm** [comment]
Hi @alaxalves,

welcome to the show. I am the maintainer of IQSS/dataverse-kubernetes and as a core contributer, I very much feel the same.

Personally, I use skaffold and minikube for my dev setup, which is already taking a lot of burden from me.

But I see that people enjoy using docker-compose, which is why I came up with IQSS/dataverse-kubernetes#118. There is also a PR with a working proof of concept.

If you would like to work on that to reuse the existing images and ideas (please also see the guide at https://dataverse-k8s.rtfd.io and it's dev section), maybe we could work together?

I'm pretty sure @4tikhonov would be delighted, too. He is the maintainer of IQSS/dataverse-docker, but IIRC he was interested in joining forces.

**Comment by 4tikhonov** [comment]
@alaxalves, we've created http://github.com/IQSS/dataverse-docker module in 2018 and using it for the development purposes, on local computers, for Cloud deployment I would recommend IQSS/dataverse-kubernetes as @poikilotherm just suggested, it's nice starting point. 
If you're not happy with it, you're welcome to contribute indeed.

**Comment by djbrooke** [comment]
Hey @alaxalves, it looks like you've heard from the two people that I would have tagged in this conversation. :) Thanks for reporting this issue and for your interest in contributing. 

As far as this issue, is there something in the guides that could be explained better? If not, I'll plan to close this out for housekeeping purposes.

**Comment by pameyer** [comment]
Hi @alaxalves - If you're looking for a quick way to get started with Dataverse development without having to go through glassfish/solr setup, https://github.com/IQSS/dataverse/tree/develop/conf/docker-aio may be worth a look (it's not mentioned in the developer guide; but I was able to use it for Dataverse development).

Not at all meaning to dissuade you (or anyone else) from improving the Dataverse/Docker developer experience; but just mentioning in case your interest was more towards having a dev environment that would work with slightly less setup (this approach still needs java8, maven, make, and wget in addition to docker).

**Comment by pdurbin** [comment]
@alaxalves I don't want to lose you as a potential contributor. #6716 is a small change if you want to take a look. Please comment there if you'd like to try making a pull request. @charvey-CSS I know you're eager to contribute too but maybe you could work on #6724?
