### ISSUE TITLE
Multistore: If no files are uploaded to published dataset, export fails.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#6739]
Discovered while testing export/import where test case involved a published dataset with no files. If using a local file store, a published dataset with no files fails to export, returns a json file with error. If add files then publish, works as expected.

**Comment by landreev** [comment]
FWIW, my first assumption was that the above was the result of trying to save a *dataset-level* file, before any datafiles are uploaded and saved. 
But the underlying issue appears to be this: 
```
Could not find storage driver for: null://10.70122/FK2/NFEKQL
```

i.e., the dataset has "null" instead of a legit storage type in the storageidentifier. And that in turn is a result of this being an OLDER dataset, created back in Feb., most likely by a Dataverse built from the multistore branch while it was still buggy.

**Comment by landreev** [comment]
HOWEVER, we have created a new dataset, and publishing without files still failed; but with different error messages (export failed). 
This one appears to have a correct storageidentifier: file://10.70122/FK2/UEMM1W; export is failing quietly, and the directory does not appear to exist. 
So that may mean that my first was right after all? 
Either way, should be easy to fix.

**Comment by landreev** [comment]
(My first guess being: only an attempt to save a DataFile creates the dataset directory in a file store; for dataset-level files, the code assumes it already exists)

**Comment by landreev** [comment]
OK, on closer inspection, this was introduced NOT in the original multistore PR, but in #6670, the followup PR that specifically addressed some issues with export in the first multistore PR (#6488)
