### ISSUE TITLE
 Rendering of the "Add Data" button in the header should be based on permissions of generic authenticated user in Root

### ISSUE THREAD

**Issue by BPeuch** [IQSS/dataverse#6741]
Version: 4.19

Hello everybody,

A small comment about the new "Add Data" button, who's now part of the toolbar (see #5718).

When a Dataverse administrator decided that a user, or all users, may only add datasets, as shown here…

![onlydatasets](https://user-images.githubusercontent.com/15209224/76526362-b2ab3900-646d-11ea-9c35-2ab1d3b2bb48.png)

… then the users in question only have the "Add Dataset" option when they click on the original "Add Data" button, the one located above the list of datasets and sub-Dataverses. However, the option to "Add Dataverse" still appears in the new "Add Data" button, as you can see here:

![newdataset](https://user-images.githubusercontent.com/15209224/76526256-898aa880-646d-11ea-9270-97ba2c3da6ce.png)

**Comment by TaniaSchlatter** [comment]
Thanks for bringing this up, @BPeuch. After a brief discussion with @mheppler, next steps are to take a close look at the render logic behind the buttons.

**Comment by scolapasta** [comment]
The buttons allow the user to create Datasets (or Dataverses) in different Dataverses. The ones in the header create at the root dataverse, while in page create at the Dataverse you are in.

(though in both cases you can change what the host is, once the create page is loaded, to any dataverse where you have appropriate permissions)

Maybe the in page button should say "Add data to this dataverse"?

Also, I checked the code and there is no render logic for the ones in the header at all. So if permissions for the root dataverse are changed to not allow anyone to deposit on root, the button still shows is there. Clicking it sends you to an Not Authorized page.

**Comment by poikilotherm** [comment]
Sorry to create noise, but isn't this related / part of #6708 ?

**Comment by BPeuch** [comment]
You're right @poikilotherm. I should have linked the issues for clarity's sake, especially since this is a young feature. Thank you for mentioning it.

**Comment by TaniaSchlatter** [comment]
There is a proposed solution discussed in #6772:

There are 4 user states that relate to the Add Data button in the header:

1. User can not add to Root – propose no "Add Data" button in header.

2. User can add dataverses but not datasets to Root – propose "Add Data" button in header with only "Add Dataverse" option.

3. User can add datasets but not dataverses to Root (**this issue**) – propose "Add Data" button in header with only "Add Datasets" option.

4. User can add Dataverses and Datasets to Root (Harvard) – "Add Data" button in header with both options – what we have now.

**Comment by shlake** [comment]
In @TaniaSchlatter listed user states above, UVa has the 1st one.

Then what about the "Add Data" button on My Data. That too assumes adding dataverses and datasets in root Dataverse.

**Comment by BPeuch** [comment]
I must say I'm really happy with how the button now behaves in the latest version. I think this is a great way of stimulating user engagement:

![add_data_new](https://user-images.githubusercontent.com/15209224/78897828-1461c180-7a73-11ea-994c-e3e84fc2228e.png)

**Comment by TaniaSchlatter** [comment]
@shlake There would not be an "Add Data" button on the My Data page. There would be an "Add Data" button on Dataverses that the logged in user has permissions to add to. I think this is current functionality, and it would not change. Pinging @scolapasta.

**Comment by scolapasta** [comment]
Right. Confirming that the idea is to get the logic of the Add Data button in the header in line with the logic of the Add Data button on the Root Dataverse (since the Add Data button Add Buttons go to the Create Dataverse / Dataset under the Root).

I thought the one open question was #5, whether we wanted the popup, or to just send you to the login page* (which offers a sign up link). What we agreed on is that there did not seem to be a valid reason for an inconsistent behavior here.

(*) from a technical perspective the link would just always go to the create page, which would then redirect a non logged in user to login.

The difference I see with the two options:
Without the popup, we would only show the options that any authenticated user has. Once a user logs in, they may have direct access to add other objects. 

A concrete example: Authenticated users have access to add datasets at the root, while my account has direct access to also add datasets. So before logging in, I would see the Add button, click on it, and only see Add Dataset. If I were logged in, I would see both Add Dataverse and Add Dataset. (I think this is the reason we chose the popup before - we knew we could show the button because we knew there would always be something the user could add (based on the authenticated users permission), but we waited until they logged in to show which things, so the button wouldn't show different options once clicked, if logged in or not.

**Comment by shlake** [comment]
@scolapasta Please don't assume that authenticated users have access to add datasets at the root - UVa does not allow datasets at the root.

**Comment by scolapasta** [comment]
That was not meant as an assumption; just an example. We are definitely keeping the "no permission for authenticated users at root" use case in mind.

See #1 from Tania's use case.

**Comment by djbrooke** [comment]
- This is a display logic change, the goal is to bring the "Add Data" button on the header into alignment with the display logic for the button on the page. 
- An open question is about what happens when the user is not logged in in cases where  the installation allows for depositing in the root. Do they get the popup that users see when they click "Add Data" on the page, or do they get what happens on Harvard Dataverse now, which is the login page? We can figure this out when we pick it up.

**Comment by sekmiller** [comment]
@djbrooke I have modified the logic so that the Add Data in the header will only show the user's permissions on Root in the header or "Any Authenticated User" if not logged in. So now we need an answer to the question above. If you're not logged in do you go directly to the login page if you try to add a ds or dv, or should you get the "Hey login or create an account!" popup that you get in the page (non-header) Add Data button?

**Comment by djbrooke** [comment]
@sekmiller thx for tagging me. I vote for keeping it consistent with the other add data button, so let's show the popup.

**Comment by sekmiller** [comment]
Got it! thanks.

**Comment by sekmiller** [comment]
Based on the discussions during the Design meeting yesterday, I have modified the rendering of the Add Data button in the header. In the header it will be rendered based on the permissions of a generic authenticated user, regardless of whether the user is logged in and that logged in user's permissions on Root. So even if I am a logged in super user, if the a generic authenticated user has no add permissions in Root I won't have an add data button in the header. The rendering of the Add Data button in the body of the dataverse page remains unchanged - that is it is based on the permissions a generic user if no one is logged in or the logged in user. (and based on the permissions in the dataverse currently being viewed.) I am going to change the title of the ticket accordingly.

**Comment by TaniaSchlatter** [comment]
With further thought, for installations that allow non-admin users to add (anywhere, not just at the root), I think that there should be an "Add Data" link in the header. It is something to consider going forward.
