### ISSUE TITLE
document ec2-create-instance.sh move to dataverse-ansible repo

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#6742]
ec2-create-instance.sh got moved to the dataverse-ansible repo due to its heavy usage of the ansible role, but this move didn't get updated in the guides/documentation, particularly deployment.html and testing.html

PR forthcoming to update said documentation, remove old ec2-* copies and document the security group requirement.

**Comment by jggautier** [comment]
Has the code in ec2-create-instance.sh changed recently? Is it expected to change? (Not sure what "security group requirement" means.)

I've been using my local copy of ec2-create-instance.sh? Is it better practice to clone the dataverse-ansible repo instead and keep my clone synced so that I'm always using the latest ec2-create-instance.sh? (I hope this question isn't too much noise in this issue :)

**Comment by djbrooke** [comment]
Closed by https://github.com/IQSS/dataverse/pull/6743
