### ISSUE TITLE
Geospatial Metadata fields not properly indented compared to other fields

### ISSUE THREAD

**Issue by BPeuch** [IQSS/dataverse#6753]
Version: 4.19

Hello everybody,

There is a discrepancy in indentation between the fields of Geospatial Metadata and those of Citation Metadata and Social Sciences and Humanities Metadata, as you can see here:

![geogindent](https://user-images.githubusercontent.com/15209224/77165790-4b1b6c00-6ab3-11ea-9240-38406d9b7ba4.png)

The issue occurred in Firefox, Chrome and Opera.

**Comment by BPeuch** [comment]
Version: 4.20

Hello everybody,

It looks like the identation problem now also occurs with the Social Sciences and Humanities Metadata box now that we've moved to version 4.20:

![probindent](https://user-images.githubusercontent.com/15209224/78675591-90c69a00-78e5-11ea-95f0-b1d81bb80020.png)

I believe there are now three indentation tabs, one for each metadata box. Maybe this will help detect the origin of the problem?

The issue occurred with Firefox, Chrome and Opera.

**Comment by mheppler** [comment]
@BPeuch good catch, and thank you for reporting the issue. It appears that the recent layount changes to the metadata on the dataset pg in 4.18 (#6109) missed this label column width inconsistency. With a few minor adjustments to the stylesheet properties, we now have a consistent label column width of 25% because we have a consistent table width of 100%. The varying label column widths was due to varying width of the table. Now that the table is 100% of the panel width, that 25% label column width will hold consistently across all the blocks.

<img width="747" alt="Screen Shot 2020-05-13 at 11 15 02 AM" src="https://user-images.githubusercontent.com/687227/81831653-9da16380-950b-11ea-8566-d4c59a215d8a.png">

**Comment by BPeuch** [comment]
Wonderful! Thanks a lot for your feedback, @mheppler, and to everyone else for tackling this issue so quickly.
