### ISSUE TITLE
Change default thumbnail size

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#6769]
For the upcoming dataset page redesign, thumbnails will be displayed in a larger form. However, the currently created thumbnails don't scale well to this new size. This issue is to:
• change the size for which thumbnails are created to 140x140 (@TaniaSchlatter please verify this the size we want)
• regenerate existing thumbnail

**Comment by scolapasta** [comment]
Note, we will eventually want the ability to produce thumbnails of different sizes (see issue #5679) but this is a smaller, quicker chunk to unblock this aspect of the redesign.

**Comment by pdurbin** [comment]
I just pushed 17c3891 to change 64 to 140 and here's a visual of how a dataset page looks:

![Screen Shot 2020-04-14 at 11 50 17 AM](https://user-images.githubusercontent.com/21006/79245730-7ab95c00-7e46-11ea-921e-a431778308d1.png)

Note that the trees next to the title are as small as ever. The trees in the file listing (and the other file) are now 140 pixels wide and covering up the file name.

I'll probably jump in #dv-design for clarification of what's desired.

**Comment by mheppler** [comment]
Added `max-width:64px; max-height:64px;` to the stylesheet in order to apply size dimensions to the file thumbnail on the dataset pg (file table), upload/edit files pg, replace file pg.

**Comment by mheppler** [comment]
Had a good call with @pdurbin to move this issue forward, which ended up being an unintentional code review.

Recommended changes include:
- revert CSS fix that I added for resizing the thumbnails images in the file table on the dataset pg
- revert image size change added to `DEFAULT_THUMBNAIL_SIZE` on ImageThumbConverter.java
- add new 140px image size to `ImageThumbConverter` class on ImageThumbConverter.java
- change dataset pg related (DatasetWidgetsPage.java?, DatasetUtil.java?) `DEFAULT_THUMBNAIL_SIZE` references to  to point to new 140px image size instead

Would then like to discuss with the team (tech hours?) + @djbrooke if we should move these changes to my branch in order to apply the necessary UI front-end/css changes required to support this larger dataset thumbnail image, or do we create a PR and move it to QA to merge without resolving the thumbnail overlapping content UI issue?

**Comment by djbrooke** [comment]
@mheppler @pdurbin thanks for the discussion and for tagging me. Sounds like it's better if this is included in the buttons branch instead of as an independent PR.

**Comment by pdurbin** [comment]
@djbrooke ok, @mheppler suggested making a pull request against his branch, so I just did with pull request #6830.

**Comment by djbrooke** [comment]
@pdurbin cool, thanks!

**Comment by mheppler** [comment]
Merged the PR from @pdurbin into my `6684-dataset-pg-btn-responsive` branch. Will document these changes in issue #6684 for QA.

**Comment by mheppler** [comment]
Additional revisions to this code from @landreev in 4254a0fb01c324980fa7a1da57ad20f01fff9e4a.

**Comment by pdurbin** [comment]
This wasn't auto-closed by pull request #6830 so I'm closing it now.
