### ISSUE TITLE
API test failures (develop 47ca3c36e4b2c2bb9954f75f554068d21264545f)

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#6813]
In my hands in docker-aio, FilesIT.testUningestFileViaApi is failing.  This disagrees w\ GDCC jenkins (https://jenkins.dataverse.org/job/IQSS-dataverse-develop/415/) , so it's possible that this is due to setup rather than code.

` FilesIT.testUningestFileViaApi:1193 expected:<200> but was:<500>`

**Comment by pameyer** [comment]
reference to `MAXIMUM_INGEST_LOCK_DURATION` in code strongly suggests this is a setup problem w\ timing issue rather than a code issue

**Comment by landreev** [comment]
> reference to `MAXIMUM_INGEST_LOCK_DURATION` in code strongly suggests this is a setup problem w\ timing issue rather than a code issue

Not sure about that - this is not a setting configured in the environment; it appears to be a hard-coded constant in UtilIT... It may be another timing condition - something our RestAssured test suite is apparently full of - as in, every time we try to run it on a new system, new things are failing simply because something takes more (or less?) time than on the system(s) where it's been running before... 

I would try bumping that `MAXIMUM_INGEST_LOCK_DURATION` to 5 or 10 sec., just to see what happens.

**Comment by pameyer** [comment]
@landreev Thanks for the suggestion - in my hands, setting it to 10 or 20 doesn't seem to change things (still fails).  
If it's working for other folks, it might just be a odd timing thing...

**Comment by pameyer** [comment]
closing in favor of #6821 (same failing test, although it's failing routinely here vs intermittently there)
