### ISSUE TITLE
edu.harvard.iq.dataverse.api.FilesIT.testUningestFileViaApi failing intermittently

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6821]
edu.harvard.iq.dataverse.api.FilesIT.testUningestFileViaApi has been failing intermittently over the last few test runs on dataverse.org Jenkins (416 is one build where this occurs). We should determine why this is occurring and get our test suite healthy.

**Comment by landreev** [comment]
So it is the same test as in #6813 - except it was failing consistently for @pameyer. OK, must be some weird timing condition; we'll figure it out. 
(it's probably unrelated, but there was a tiny change recently in how uningest works; we are now saving the original file name, rather than reconstructing it... I guess there's a possibility that it has changed the timing by some milliseconds, making this failure more likely? - who knows)

**Comment by pdurbin** [comment]
I'm reliably getting a 500 error on my laptop. That is to say, I believe this issue is easy to reproduce.

UningestFileCommand.java:167 is implicated which does this:

`MapLayerMetadata mapLayerMetadata = ctxt.mapLayerMetadata().findMetadataByDatafile(uningest);`

I'm also seeing a lot of javax.validation.ConstraintViolationException

**Comment by pdurbin** [comment]
I just created pull request #6824
