### ISSUE TITLE
jsf.externalcontext.no.mime.type.found WARNING in logs (Pf8, 4.20, 4.19)

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#6836]
This apparently non-functional problem was discovered during pf8 testing but did not want to hold up merging that pr for this issue. That said, it should be looked at:

3. On dataset create, flurry of server log entries (6) of this type:
this also happens when click log on and visit the dataverse homepage for the first time.
```
[2020-04-16T15:15:15.184-0400] [glassfish 4.1] [WARNING] [jsf.externalcontext.no.mime.type.found] [javax.enterprise.resource.webcontainer.jsf.context] [tid: _ThreadID=150 _ThreadName=jk-connector(3)] [timeMillis: 1587064515184] [levelValue: 900] [[
  JSF1091: No mime type could be found for file bs/css/bootstrap.min.css.map.  To resolve this, add a mime-type mapping to the applications web.xml.]]
```

**Comment by mheppler** [comment]
I actually have a browser tab open for a similar mime.type error issue from 4.0.1 #2112. From what I can tell, this is not a PF8 issue specifically. There may be more of these errors due to PF8, but these bootstrap.min.css.map errors were in the console prior to the upgrade.

I am going to take the assignee away from @scolapasta and look into it. From what I can remember, I thought this exact error was fix once upon a time, so I will try to dig up that fix and see if something changed.

**Comment by mheppler** [comment]
Found a [Stack Overflow answer](https://stackoverflow.com/a/44184109) suggesting to add a mime-type of `application/json` for .map files, so I added that to our web.xml just as we do for various web font and favicon file types required by the UI.

**Comment by pdurbin** [comment]
Fixed by this PR:

- #6840
