### ISSUE TITLE
Publish message on front page

### ISSUE THREAD

**Issue by philippconzett** [IQSS/dataverse#6887]
As a Dataverse admin, I'd like to be able to add a status message to the repository front page to notify users e.g. about the system not being available due to an upcoming upgrade. I'd like to place this message using the GUI/Dashboard. Once a user has read the message, they can close the message window.

**Comment by poikilotherm** [comment]
This might be helpful: :wink:

http://guides.dataverse.org/en/latest/installation/config.html#statusmessageheader
http://guides.dataverse.org/en/latest/installation/config.html#statusmessagetext

**Comment by djbrooke** [comment]
Hi @philippconzett - I'm going to close this, because I think what @poikilotherm shows here would meet your needs. This is also what we use to notify users of upcoming upgrades on dataverse.harvard.edu. We'll be re-engineering some of the backend here as part of #7263.

Feel free to comment if you'd like this reopened and we can discuss further.
