### ISSUE TITLE
Metadata licensing

### ISSUE THREAD

**Issue by philippconzett** [IQSS/dataverse#6888]
As a Dataverse admin, I'd like to be able to specify under what license the metadata from my repository (or even at sub-dataverse level) are made available for reuse.

There are several existing issues about data licensing, but as far I can see, no one has requested the possibility to specify machine-readable license information about the metadata. TROLLing ([https://trolling.uit.no/](https://trolling.uit.no/)) is currently working on an application to become a CLARIN B Centre (cf. https://www.clarin.eu/content/clarin-centres). One of the requirements for service providers is that the data and metadata of the services are licensed:

> The centre has to provide a URL to a webpage where its information about licenses is described, enabling users of the repository to get information on how data and metadata are licensed.

Currently, DataverseNO (which TROLLing is a part of) provides this information in the section “Copyright and Licensing” in the DataverseNO Access and Use Policy (cf. https://site.uit.no/dataverseno/about/policy-framework/access-and-use-policy/):

> DataverseNO (by owner) waives any and all rights DataverseNO might have with respect to Descriptive Metadata in DataverseNO. To the extent that DataverseNO’s own contributions to selecting and arranging Descriptive Metadata may be protected by copyright, DataverseNO (by owner) dedicates such contributions to the public domain pursuant to a CC0 Public Domain Dedication.

In addition, we'd like to have the information about metadata license being part of the machine-readable metadata provided by Dataverse.

**Comment by jggautier** [comment]
Hi @philippconzett. Thought I'd note that [this Google Groups thread](https://groups.google.com/forum/#!msg/dataverse-community/kf0VDKfdq8g) has a very similar discussion, including info about how the DDI Codebook standard supports including license information for the metadata document itself. Merce mentioned that work on DataTags would help resolve this issue, since supporting sensitive data will make it necessary to assign different types of licenses to the metadata in machine readable and more granular ways (e.g. for each dataset or even each file?).

Thoughts on how to express this info with each metadata export:
- Changing the Dataverse JSON standard to include this info is probably easiest since we control it
- I think DataCite/OpenAIRE would require an update in order to be able to distinguish between metadata license and data license
- I'd guess that we wouldn't be able to successfully push for a change to simplified Dublin Core given that standard's mission, and that it would be easier to export a simplified DC XML for the metadata (in addition to the current one for the data). The same might be true for the extended (qualified or Terms) Dublin Core
- The [guidelines Dataverse follows from Google for using Schema.org](https://developers.google.com/search/docs/data-types/dataset#structured-data-definitions) don't mention anything about distinguishing between metadata license and data license, but the practices around using that huge schema for data publishing are still evolving, and the need to express metadata licenses could be brought up or reiterated in [the RDA working group](https://www.rd-alliance.org/groups/research-metadata-schemas-wg) and/or in [the channels that Schema.org set up for feedback](https://schema.org/)

**Comment by philippconzett** [comment]
Thanks, @jggautier, for pointing to the existing discussion in Google Group; I obviously didn’t search thoroughly enough. I think, the information about metadata license should be included both at dataset level and at repository level, an in a way that complies with DataCite and OpenAIRE requirements. Then there is the question of where to define the metadata license of a repository. Maybe, re3data ([https://www.re3data.org/](https://www.re3data.org/)) could be possible place? In re3data, the metadata license of a repository can be specified in the section _Database licenses_ under the _Terms_ tab. For DataverseNO, we have chosen CC0 (see [re3data record](https://www.re3data.org/repository/r3d100012538)). (The name “Database licenses” is probably not so straightforward to understand, but I got confirmed from re3data that this means the metadata license.) As re3data records are accessible via API, I guess the repository license information could easily be accessed by other services.

**Comment by jggautier** [comment]
Thanks for confirming the purpose of re3data's "Database licenses" field. Looks like Harvard Dataverse took it to mean the Apache license of the Dataverse software instead of the license of the dataset metadata that the repository publishes.

I'm just learning about CLARIN Centres, so I guess my questions would be:
- Would their reviewers find that having information about a repository's license in re3data be good enough? Do they want repositories (or collections) to publish in some metadata standard information about the licenses of the datasets they publish?
- Do they want a repository's dataset-level metadata to include the license of the dataset itself? This was the focus in that Google Group's thread. Should it be in the scope of this Github issue?

**Comment by philippconzett** [comment]
Actually, CLARIN does currently not request metadata licence information. In the application form they say:

> Note: at the moment, licensing for metadata is discussed by the legal issues committee. Awaiting the outcomes of this process, it is optional to provide a license for metadata

So, I guess our answer including a reference to our policy is just fine for the moment.
However, I think it would be good to include machine-readable information about metadata licence in Dataverse, as this would imply full support for the FAIR R1.1. Principle:

> (Meta)data are released with a clear and accessible data usage license

**Comment by jggautier** [comment]
Agreed! That section of the FAIR principles is what got me thinking about metadata licenses in metadata documents, too. Glad there's a GitHub issue about it. Hopefully it'll help when the community tackles these things.

**Comment by philippconzett** [comment]
I just noticed that license support for metadata is set out as a desired characteristics in the COAR Community Framework for Good Practices in Repositories ([https://doi.org/10.5281/zenodo.4110829](https://doi.org/10.5281/zenodo.4110829)); cf.:

> 1.10 The metadata in the repository are available under a Creative Commons Public Domain License [...].

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
