### ISSUE TITLE
Any way to search datasets / get dataset by "other ID" instead of DOI

### ISSUE THREAD

**Issue by eblondel** [IQSS/dataverse#6952]
When submitting an Atom entry with Sword API, the local identifier provided to Dataverse is kept as "Other Id" in Dataverse. Is there any way to:

* list each dataverse entries including their native / local Id (as submitted to Dataverse) as part of their metadata?
* get a dataverse member based on local id, instead of using global Id? Something like ``https://$HOSTNAME/dvn/api/data-deposit/v1.1/swordv2/edit/study/other_id:my-local-identifier`` instead of ``https://$HOSTNAME/dvn/api/data-deposit/v1.1/swordv2/edit/study/doi:TEST/12345``

Currently this is required if we want to do CRUD management cycle based on record local identifiers. 

Any advice how to do that with Dataverse (and hopefully through the Sword API)?

Thanks a lot in advance

**Comment by pdurbin** [comment]
@eblondel hi! I just noticed these unanswered questions. Sorry for a late reply!

<img width="413" alt="Screen Shot 2021-12-02 at 2 21 13 PM" src="https://user-images.githubusercontent.com/21006/144492147-d7e09e2e-3f47-4a2c-aa16-18764cb35719.png">

Are you still interested in answers, a year and a half later?!? If so, I can try to dig in.

**Comment by eblondel** [comment]
@pdurbin yes definitely interested still, on our side we would like to make use of standard protocol for managing resources in Dataverse, and the Sword API is still under consideration, although it deserves improvements 

(Actually, I take the opportunity to say that we might need to create other tickets and interact further with you related to Sword, and if this is welcome we may need also to create pull requests for that, especially related to the metadata mapping done between the Atom XML/Dublin core and the Dataverse metadata, as it handles very few elements at this stage)

I copy @wheintz who is involved in the operation of Dataverse for the national data portal of the French National Institute for Agronomics and Environmental studies (INRAE), portal that is powered by Dataverse.

**Comment by pdurbin** [comment]
I'm getting a little faster in responding. :smile:

You start with this...

> When submitting an Atom entry with Sword API, the local identifier provided to Dataverse is kept as "Other Id" in Dataverse.

... but is this true? When I create a dataset using the XML from the API Guide and look at "Other ID" (screenshot below), that metadata field isn't populated. Are you saying it's possible to populate it via SWORD?

![Screen Shot 2021-12-07 at 2 04 25 PM](https://user-images.githubusercontent.com/21006/145092852-b95caf07-171d-46ca-bec6-1f20414fda1a.png)

For this question:

> list each dataverse entries including their native / local Id (as submitted to Dataverse) as part of their metadata?

When you say "entries" do you mean datasets or dataverses? (We're in the process of renaming dataverses to dataverse collections, by the way.) You might be interested in the "Show Contents of a Dataverse Collection" API at https://guides.dataverse.org/en/5.8/api/native-api.html#show-contents-of-a-dataverse-collection . From SWORD you can list datasets with "List datasets in a Dataverse Collection" at https://guides.dataverse.org/en/5.8/api/sword.html#list-datasets-in-a-dataverse-collection

For this one:

> get a dataverse member based on local id, instead of using global Id?

I think to better understand what you mean by local id. We tend to use the term PID (Persistent ID) instead of Global ID. We also use the term "database id" for the primary key of the object (dataverse collection, dataset, file, etc.). There's also "Other ID", the metadata field in the screenshot above. We don't tend to use the term "local id" much.

> the Sword API is still under consideration, although it deserves improvements

I don't expect our current SWORD code (v2) to change much. It works well enough but all development is going into our "native" API. There's a been a little chatter about SWORD v3 here, but not a ton of interest from what I can tell: https://groups.google.com/g/dataverse-community/c/D7lRTA3f8Hc/m/nX0v50MKAgAJ

So please feel free to create SWORD-related issues, but I'm curious, have you considered using the native API instead?

Finally, issues are especially good for bugs and not bad for requesting features, but for questions I'd probably steer you toward the resources at https://dataverse.org/contact especially:

- https://groups.google.com/g/dataverse-community
- https://chat.dataverse.org
- support@dataverse.org

Thanks!

**Comment by eblondel** [comment]
@pdurbin thanks for your answers,

Since you reply :-), I stick with this ticket, but I'm ok to further discuss in other channels as you suggest.

When I say entries, I refer to the vocabulary of the Atom syndication format / DC standard that is used as data exchange format for the standard SWORD API in which entries become 'members' of 'collections'; In Dataverse vocabulary that would be 'datasets' i assume, not 'dataverse' which referring to the standard would be the `collection`.

The fact you use the example provided in the doc logically leads to no "other id", because the DC entry example in the doc doesn't have any id. But when a user specifies a complete DC entry starting with its core property: its identification, this information doesn't seem to be retained by Dataverse, although it is the primary identification of the entry. This points out a first weakness of the mapping DC vs Dataverse "Qualified mapping" since a Atom/DC entry `id` is not kept. This is I mean by 'local' id, the ID that was set-up by the user in the DC entry, as generic `id` or scoped to a particular `agency` (the case if the published resources in Dataverse refer to resources already identified in an agency information system, a catalogue, a database, a register, etc). It is not insignificant property since it's a best practice for a data manager to properly identify their resources, and in most of cases for data managers resources and where already "identified" before publishing them through a Dataverse portal. They are other DC qualified mapping related issues, but they may deserve specific github issues.

As you say SWORD operations work quite well, I confirm (at least for insert/update, other users spotted out issues with dataset deletion). However the DC qualified mapping as it is, is very limited, deserves major improvements (starting with the "id" discussed in this issue). While other tickets may follow on this, just a brief summary of key issues spotted out (apart the fact the mapping is missing key elements): 
- the mapping is sometimes doing strong assumptions/shortcuts eg. dc:publisher mapped to producerName
- part of the features highlighted in the mapping doc do not work (eg. adding `Type` attributes to `dc:contributor` has no effect)
- although not directly related to the DC vs; Dataverse Qualified mapping: the contact person/email set-up as part of the metadata is not the one used then when we click on the "Button" contact which is bound to the user account used for creating the Dataverse dataset. On this, it's very common practice that in research institutes, (meta)data managers do the publication (programmatically or not) on behalf of the actual dataset contact/focal points. Last but not least, on mouse over the "contact" button it's said (at least in the french translation) to "contact the dataset owner". So here there's a mix between dataset contact, dataverse user, and dataset owner;

Hence, i'm wondering what would be the steps to improve the DC/Dataverse qualified mapping within the Dataverse; if it deals with Dataverse specific source code, or if it concerns third-party software dependencies, and based on that, if Dataverse team is open to open/in-kind contributions to improve this mapping in order strenghten the support of Atom / AtomPub / SWORD in Dataverse. 
I see i'm not the only one to spot out DC metadata mapping issues: https://github.com/IQSS/dataverse/issues/2749, https://github.com/IQSS/dataverse/issues/8129 

ps: Regarding the Dataverse native API, it had been considered in the past (but facing too many issues, at least through the R client). In general, binding automated publication workflows targeting Dataverse need to be as stable in time, and API backward compatibility issues (whether this is , absence of conservative approach regarding API version (where a sofware tends to overwrite the API within a software distribution) is a major issue for data managers that need to run sustainable workflows. This is the reason why API based on a standard specification (AtomPub/SWORD) may be preferred to a software-based API. Maybe less flexibility (binding to the standard) but more sustainability & stability. 

cc @wheintz, juldebar (for their information)

**Comment by scolapasta** [comment]
Hi @eblondel. We would definitely be happy with PRs to update and improve the sword functionality of the code. Ideally, it would be worth considering upgrading the code to support v3, but that, of course, is a bigger undertaking, so smaller PRs making incremental changes are also fine.

Also be aware that we do try to keep the native APIs backward compatible, and if we do make a breaking change make sure to announce it in the release notes.

**Comment by pdurbin** [comment]
> Since you reply :-), I stick with this ticket, but I'm ok to further discuss in other channels as you suggest.

@eblondel yeah, I think we should take this to some other channel if you don't mind. If you're looking for real time, I'm often in https://chat.dataverse.org 😄 

Or the mailing list I mentioned is fine if you prefer.

Thanks!

**Comment by eblondel** [comment]
@pdurbin  well yes still interested, but i didn't get answers on key aspects /issues mentioned above. Maybe you can clarify if some of the items i mentioned have been fixed meanwhile. 

I copy to @wheintz one of they guys that are responsible for french open data initiatives, for which AFAIK dataverse has been chosen as tool.

**Comment by pdurbin** [comment]
@eblondel I'm replying inline. I hope you find this helpful.

> When I say entries, I refer to the vocabulary of the Atom syndication format / DC standard that is used as data exchange format for the standard SWORD API in which entries become 'members' of 'collections'; In Dataverse vocabulary that would be 'datasets' i assume, not 'dataverse' which referring to the standard would be the `collection`.

Right. What SWORD calls entries, Dataverse calls datasets.

> The fact you use the example provided in the doc logically leads to no "other id", because the DC entry example in the doc doesn't have any id. But when a user specifies a complete DC entry starting with its core property: its identification, this information doesn't seem to be retained by Dataverse, although it is the primary identification of the entry. This points out a first weakness of the mapping DC vs Dataverse "Qualified mapping" since a Atom/DC entry `id` is not kept. This is I mean by 'local' id, the ID that was set-up by the user in the DC entry, as generic `id` or scoped to a particular `agency` (the case if the published resources in Dataverse refer to resources already identified in an agency information system, a catalogue, a database, a register, etc). It is not insignificant property since it's a best practice for a data manager to properly identify their resources, and in most of cases for data managers resources and where already "identified" before publishing them through a Dataverse portal. They are other DC qualified mapping related issues, but they may deserve specific github issues.

Right. If you want to retain a dataset's original DOI (its primary identification), instead of SWORD, I would recommend using the newer Data Migration API: https://guides.dataverse.org/en/5.12.1/developers/dataset-migration-api.html

Alternatively, since you like standards (don't we all!), you could retain the DOI by using the "import using DDI format API": https://guides.dataverse.org/en/5.12.1/api/native-api.html#import-a-dataset-into-a-dataverse-installation-with-a-ddi-file

> As you say SWORD operations work quite well, I confirm (at least for insert/update, other users spotted out issues with dataset deletion). However the DC qualified mapping as it is, is very limited, deserves major improvements (starting with the "id" discussed in this issue). While other tickets may follow on this, just a brief summary of key issues spotted out (apart the fact the mapping is missing key elements): 
> 
> - the mapping is sometimes doing strong assumptions/shortcuts eg. dc:publisher mapped to producerName

Yes, we defined these mappings early on, maybe 8-9 years ago. I agree there are assumptions built in.

> - part of the features highlighted in the mapping doc do not work (eg. adding `Type` attributes to `dc:contributor` has no effect)

Hmm, we don't seem to have an issue tracking this, but certainly it should be re-tested if you're saying it's not working!

> - although not directly related to the DC vs; Dataverse Qualified mapping: the contact person/email set-up as part of the metadata is not the one used then when we click on the "Button" contact which is bound to the user account used for creating the Dataverse dataset. On this, it's very common practice that in research institutes, (meta)data managers do the publication (programmatically or not) on behalf of the actual dataset contact/focal points. Last but not least, on mouse over the "contact" button it's said (at least in the french translation) to "contact the dataset owner". So here there's a mix between dataset contact, dataverse user, and dataset owner;

I think I see what you're getting at. For SWORD, the contact address becomes the email used by the person creating the dataset. Yes, I can see how this could be problematic. If needed, you could change the address with the native API.

> Hence, i'm wondering what would be the steps to improve the DC/Dataverse qualified mapping within the Dataverse; if it deals with Dataverse specific source code, or if it concerns third-party software dependencies, and based on that, if Dataverse team is open to open/in-kind contributions to improve this mapping in order strenghten the support of Atom / AtomPub / SWORD in Dataverse. 
> I see i'm not the only one to spot out DC metadata mapping issues: https://github.com/IQSS/dataverse/issues/2749, https://github.com/IQSS/dataverse/issues/8129 

Generally speaking, we haven't put much effort or focus into the SWORD code. We definitely should fix bugs, such as this one:

- #8625

As for extending the functionality of our SWORD API, you already found this relatively ancient issue:

- #2749

It was really a placeholder to explore this space but in 7 years we haven't gotten around to it and there hasn't been much interest in it.

Again, I'll mention that there hasn't been much interest in SWORD v3 either: https://groups.google.com/g/dataverse-community/c/D7lRTA3f8Hc/m/nX0v50MKAgAJ

In the past I've encouraged pull requests before checking with the team that we actually want them. Are you sure you want to pour effort into SWORD v2? Should we talk about this on a future community call? Please see https://dataverse.org/community-calls

> ps: Regarding the Dataverse native API, it had been considered in the past (but facing too many issues, at least through the R client). In general, binding automated publication workflows targeting Dataverse need to be as stable in time, and API backward compatibility issues (whether this is , absence of conservative approach regarding API version (where a sofware tends to overwrite the API within a software distribution) is a major issue for data managers that need to run sustainable workflows. This is the reason why API based on a standard specification (AtomPub/SWORD) may be preferred to a software-based API. Maybe less flexibility (binding to the standard) but more sustainability & stability. 

Yes, I completely agree that it's best to use standards whenever possible. Again, I'd like to suggest that you try putting your data in DDI format and using the "import using DDI format API": https://guides.dataverse.org/en/5.12.1/api/native-api.html#import-a-dataset-into-a-dataverse-installation-with-a-ddi-file

Phew! I hope this helps! 😄 Happy to do a Zoom or whatever! I think it would be easier. Or if you want to keep typing, can we close this issue and talk at https://groups.google.com/g/dataverse-community or https://chat.dataverse.org instead? Those channels are better for discussion.

**Comment by jggautier** [comment]
> part of the features highlighted in the mapping doc do not work (eg. adding Type attributes to dc:contributor has no effect)
> 
> Hmm, we don't seem to have an issue tracking this, but certainly it should be re-tested if you're saying it's not working!

I think https://github.com/IQSS/dataverse/issues/3588 is related more broadly.

**Comment by pdurbin** [comment]
> Phew! I hope this helps! 😄 Happy to do a Zoom or whatever! I think it would be easier. Or if you want to keep typing, can we close this issue and talk at https://groups.google.com/g/dataverse-community or https://chat.dataverse.org instead? Those channels are better for discussion.

@eblondel I'm gong to close this issue. I hope my answers above were helpful! Please feel free to reach out in any of the channels I mentioned above.
