### ISSUE TITLE
Download: 404 error for pdf downloads in projects with ingested tabular files 

### ISSUE THREAD

**Issue by rdemgenski** [IQSS/dataverse#6972]
When selecting a single pdf file on a data project page and downloading it from the upper download option button, it (1) gives the option of "original format" and "archival format" when it should not; and (2) selecting original format leads to 404 download error

(1) only happens for projects that include ingested files

(2) error occurs only for non-ingested files

(3) error happens when selecting original format (works when selecting .tab even though that doesn't exist)

Issue replicated on demo: https://demo.dataverse.org/dataset.xhtml?persistentId=doi%3A10.70122%2FFK2%2FNDP9TB

Erroneous download option:
![image](https://user-images.githubusercontent.com/42038889/84171580-f865a680-aa48-11ea-8bd9-ce4e7e0e3b73.png)

Error message:

{"status":"ERROR","code":404,"message":"'/api/v1/access/datafile/1113532' datafile access error: requested optional service (image scaling, format conversion, etc.) is not supported on this datafile."}

Issue first discovered on QDR DV v. 4.20-qdr

(also reported in #7505)

**Comment by djbrooke** [comment]
Thanks @rdemgenski for the report. I was able to confirm this on demo.dataverse.org.

**Comment by landreev** [comment]
OK, we've just run into this issue all over again, while testing PR #7047. 

So there are  a couple of issues at play:
It looks like we ALWAYS present the "original vs. tabular" choice whenever there are any tab. files in the (entire) dataset. Even if the selected checkboxes are not tabular; even if there's only one checkbox, for a non-tabular file, that is selected. (even if there are no tab. files in this given version either!) 
So we do want to replace this with a check on only the files that are actually selected via the checkboxes. 

In most situations, It's not a huge deal of an issue - but could be confusing. It only becomes a real issue, with the failing download, when there's only one, non-tabular file selected; or multiple files are selected, but only one is left once the restricted-to-the-user files are stripped off the list. Because then it's redirected to the single file download API; and it doesn't like when a format that does not apply to the specified file is requested. Note that this latter case will still be a possibility, even after the fix described above is applied. So we should also address that, by dropping the "format=orig" parameter from the final /api/access/datafile call, if the one remaining file is not tabular.  

(should be trivial enough fixes though)
