### ISSUE TITLE
Search/Browse: Improve facet UI for dates in fields such as "Publication Date"

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#70]
---

Author Name: **Philip Durbin** (@pdurbin)
Original Redmine Issue: 3478, https://redmine.hmdc.harvard.edu/issues/3478
Original Date: 2014-02-03
Original Assignee: Philip Durbin

---

Date facets in DVN 3.x are sorted by count:

Production Date
2002 (2261)
1996 (1717)
1988 (424)
2010 (371)
2009 (314)

We should probably order by date:

2013-2014 (4)
2011-2012 (3)

Do we like this? Should we have a larger "span" than 2 years? What should the UI look like? Should there be a slider?

**Comment by eaquigley** [comment]
I'd like this date range slider to be like this where a user can either enter a range or slide to their preferred range: 
![image](https://cloud.githubusercontent.com/assets/5922904/7394743/8a7f4e60-ee63-11e4-9c0d-02c4aaf722c8.jpg)

@posixeleni could you identify the metadata fields that would need a date range slider?
@mheppler i've looked for date range slider components and found this one but don't think/know if it is compatible with Dataverse: https://github.com/projectblacklight/blacklight_range_limit Would you mind helping me look for more examples?
@pdurbin this seems to be the information from Solr on how to make this type of facet work: https://wiki.apache.org/solr/SimpleFacetParameters

**Comment by posixeleni** [comment]
The following fields can benefit from the date range slider:

In the Citation Metadata
- dsPublicationDate
- dateOfDeposit
- productionDate
- distributionDate

But there are also compound fields with start and end dates that we can use the slider for:

- Time Period Covered: timePeriodCoveredStart + timePeriodCoveredEnd (Citation Metadata)
- Date of Collection: dateOfCollectionStart + dateOfCollectionEnd (Citation Metadata)

In the Astronomy Metadata:
- coverage.Temporal: coverage.Temporal.StartTime + coverage.Temporal.StopTime

**Comment by pdurbin** [comment]
@eaquigley I like how that slider looks but I'm not sure it's compatible with JSF. There are a variety of Primefaces sliders here that may be of interest: http://www.primefaces.org/showcase/ui/input/slider.xhtml

I'd also like to point out that this issue has a hard dependency on #370 so that the data is available to Solr as numbers and dates rather than text.

**Comment by pdurbin** [comment]
Feedback via @thegaryking at https://help.hmdc.harvard.edu/Ticket/Display.html?id=232324

"at https://dataverse.harvard.edu/dataverse/GovDept why is there a list of dates that goes only up to 2013 even though the individual items go until 2016? see screenshot" ![pubdate](https://cloud.githubusercontent.com/assets/21006/12888537/afabe778-ce48-11e5-87d6-1db18a97127f.png)

It's probably time to take "finalize" out of the title of this issue. I'll try to come up with a better title. We should probably make this issue specifically about date ranges even though it depends on figuring proper indexing of range values as described in #370.

**Comment by kcondon** [comment]
Including notes from and closing a similar, duplicate ticket #370. That also includes ranges for numbers generally such as wavelength.

**Comment by kcondon** [comment]
From #370:
[Kevin]
This ticket is a placeholder for indexing fields that contain something other than strings, eg. dates and floats, to support range queries for either facets or searches, depending on what is finally decided.
Right now, we are indexing all fields as text_en per #485 (comment)

[Phil]
In practice, these are all astro fields right now (resolution.Spatial, coverage.RedshiftValue, etc.) and there's a doc called "Astro range queries" at https://docs.google.com/a/harvard.edu/document/d/19DB4heSUMTm2CNTJFjt9AUDfaaZUZvdoh1QGhedXWkk/edit?usp=sharing where I tried to spur some discussion of what the UI should look like. See also #3478 which was originally asking about the UI for dates.

**Comment by djbrooke** [comment]
Removing from 4.5, will be reprioritized for a future release.

**Comment by pdurbin** [comment]
The other day @rtreacy passed along some feedback to me from someone who looked at https://dataverse.harvard.edu and remarked something to the effect of "**It looks like there's only old data here** because it's 2018 and I don't see anything newer than 2016 under 'Publication Date'."

![screen shot 2018-05-23 at 12 40 18 pm](https://user-images.githubusercontent.com/21006/40438574-6680e690-5e86-11e8-8f7a-3d0f367c46ad.png)

If you click "More..." a couple times, you can tell there is in fact data from 2017 and 2018, but I'm sure we could do a better job with date facets like this:

![screen shot 2018-05-23 at 12 43 14 pm](https://user-images.githubusercontent.com/21006/40438714-bf33359a-5e86-11e8-8773-925011425a19.png)

For all facets we show a count with the highest number on top but for dates it would probably be more interesting to see "all time" vs. "last five years" vs. "last six months" or whatever.

**Comment by pdurbin** [comment]
Over at #4977 @philippconzett suggests that we simply sort the publication year facet chronologically.

There was also a little discussion with @mdmADA about date facets at https://github.com/IQSS/dataverse/issues/4908#issuecomment-411243393

**Comment by djbrooke** [comment]
Closing in favor of #4977.

**Comment by pdurbin** [comment]
> I'd like this date range slider to be like this where a user can either enter a range or slide to their preferred range:
> ![image](https://cloud.githubusercontent.com/assets/5922904/7394743/8a7f4e60-ee63-11e4-9c0d-02c4aaf722c8.jpg)

The idea of a date range UI component lives on in this new issue:

- #8813
