### ISSUE TITLE
Support Near Realtime Search (handle indexing failures)

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#702]
---

Author Name: **Philip Durbin** (@pdurbin)
Original Redmine Issue: 4160, https://redmine.hmdc.harvard.edu/issues/4160
Original Date: 2014-06-30
Original Assignee: Philip Durbin

---

Dataverse 4.0 requires "near realtime search" because the moment dataverses, datasets, or files are added, updated, or deleted the "cards" and facet counts must immediately reflect the change.

> "Near realtime search means thats documents are available for search almost immediately after being indexed - additions and updates to documents are seen in 'near' realtime." -- http://wiki.apache.org/solr/NearRealtimeSearch

In order to support near realtime search, we must handle indexing failure and re-try the indexing operation.

As we are designing this system, we should probably consider other cases where detecting failure of a network service and re-trying is desirable, such as:

* registering DOIs
* posting to Twitter

We should also considering using notifications for cases where re-indexing was attempted several times but continues to fail.

In DVN 3.x there is a method called getUnindexedStudies at https://github.com/IQSS/dvn/blob/3.6.1/DVN-root/DVN-web/src/main/java/edu/harvard/iq/dvn/core/index/IndexServiceBean.java#L1061 that uses the following query to determine which studies need to be re-indexed:

`List<Study> studies = (List<Study>) em.createQuery("SELECT s from Study s where s.lastIndexTime < s.lastUpdateTime OR s.lastIndexTime is NULL").getResultList();`

Another approach could be to use a database table as a queue (thought this approach could be problematic: https://blog.engineyard.com/2011/5-subtle-ways-youre-using-mysql-as-a-queue-and-why-itll-bite-you/ )

See also:

http://lucene.472066.n3.nabble.com/strategies-for-managing-Solr-indexing-failures-and-retries-td4139186.html

---

Related issue(s): #229
Redmine related issue(s): [3643](https://redmine.hmdc.harvard.edu/issues/3643)

---

**Comment by pdurbin** [comment]
@scolapasta can you please explain what you expect to be delivered for this issue? The scope of this ticket, I mean. What functionality should go through QA.

**Comment by scolapasta** [comment]
the scope is to get the indexing to be asynchronous for 4.0. We can discuss in more detail when we get to this next week.

**Comment by pdurbin** [comment]
The plan is to use the `@Asynchronous` annotation in the same way it's used at processFilePath at https://github.com/IQSS/dataverse/blob/e3d7d0daf75215b72023e2a7f63c7d0a968783d3/src/main/java/edu/harvard/iq/dataverse/api/BatchServiceBean.java#L31

**Comment by pdurbin** [comment]
I just made "index all" async with some ideas from @ekraffmiller (thanks!). Since indexing operations return a String with status such as "10 dataverses and 3 datasets indexed" or "Server refused connection at: http://localhost:8983/solr" I'd like to be able to return this String to the person who called "index all". The examples at http://docs.oracle.com/javaee/7/tutorial/ejb-async002.htm use Future<String> in a backing bean so I created one: SuperUserPage.java in a0600f9 . I think of this page a prototype for what @bencomp is asking for in #1574 to replace the old "Dataverse Network Options GUI" in DVN 3.6. Mostly I put it in to get my hands dirty with the `Future` class from the Java EE tutorial.

Next steps:

- see what @scolapasta and others think about the "[superuser](http://localhost:8080/superuser.xhtml)" page (we can remove it or rename it)
- make more indexing operations async such as when you create a dataset, etc.
- figure out a way to kick off "index all" from the API and later check the status from the API
- write up a list of what should go through QA for this ticket.

**Comment by pdurbin** [comment]
@scolapasta I've made the following methods in IndexServiceBean async...

- indexAll
- indexDataverse
- indexDataset (also indexes files)

... and ran a build on https://apitest.dataverse.org and the tests passed: https://build.hmdc.harvard.edu:8443/job/apitest.dataverse.org-apitester/16/testReport/ (also different curl tests locally and got the output I expected). I'm passing this to you to think about the code and comments I've made. You're welcome to pass it to QA if you think it's ready.

**Comment by pdurbin** [comment]
@scolapasta and I discussed this ticket and we agreed that we would keep async for "index all" but remove/disable it from all other indexing methods (indexDataverse, indexDataset).

**Comment by pdurbin** [comment]
@scolapasta please review 0921d8a where I took out `@Asynchronous` on indexDataverse and indexDataset.

Now the only places in the project where `@Asynchronous` occurs in indexAll (so curl doesn't time out) and the processFilePath method of the BatchServiceBean.

**Comment by kcondon** [comment]
@pdurbin This appears to have been addressed somewhat by asynch indexing. Closing but feel free to comment and reopen as needed with more detail on what need to happen.

**Comment by pdurbin** [comment]
@kcondon this is the issue I was using to track the idea of handling indexing failure. For example, what if Solr is down? Some reindexing should happen, hopefully automatically (maybe it gets put in a queue?). If this is not a priority, I'm fine with leaving this issue closed. I defer to you on this. #2322 about fault tolerance is related and still open (addressed by pull request #2985).
