### ISSUE TITLE
Allow user-control of DOI string

### ISSUE THREAD

**Issue by mankoff** [IQSS/dataverse#7032]
It would be nice if dataverse allowed us to (optionally) enter a DOI rather than generate a random one. 

Our pre-dataverse DOI scheme embedded human-useful information in the DOI, rather than just random-but-unique identifiers for computers. For example `doi:nn.nnnn/data/project`. 

I searched through the existing tickets and was not able to find this request, nor a response to it. I did find two tickets that may be related:

+  Review creation of DS identifiers #1967 
+  support alternative local identifier schemes #3654

**Comment by mankoff** [comment]
The solution now is cumbersome - Externally and manually mint the desired DOI, then import an existing (empty) dataset to the dataverse with that DOI. It seems like a text field could be added that, if it contains anything, attempts to use that string (checking of course for uniqueness).

**Comment by pdurbin** [comment]
@mankoff hi, this isn't a solution for you and I see you found #3654 but I wanted to make you aware of the `:IdentifierGenerationStyle` setting. Here's a screenshot of the docs:

<img width="743" alt="Screen Shot 2020-06-29 at 1 51 14 PM" src="https://user-images.githubusercontent.com/21006/86038926-b1e3e600-ba0f-11ea-8bac-dc6bdfeca5a6.png">

http://guides.dataverse.org/en/4.20/installation/config.html#identifiergenerationstyle

This setting was introduced because (as you've expressed) the random 6 character string wasn't desired. Right now `:IdentifierGenerationStyle` can be one of two values:

- randomString
- sequentialNumber

It sounds like you're advocating for a third option

- letMeSpecify (or whatever we want to call it)

One thing I'd like to point out is that I've heard many times that DOIs are supposed to meaningless and that idea has obviously been implemented in Dataverse.

**Comment by mankoff** [comment]
Hi @pdurbin - Yes, please consider this a feature request for a "userSpecified" option.

As for DOIs "supposed to be meaningless", the DOI handbook "suffix" section here https://www.doi.org/doi_handbook/2_Numbering.html#2.2.3 states,


> The DOI suffix shall consist of a character string of any length chosen by the registrant. Each suffix shall be unique to the prefix element that precedes it. The unique suffix can be a sequential number, or it might incorporate an identifier generated from or based on another system used by the registrant (e.g. ISAN, ISBN, ISRC, ISSN, ISTC, ISNI; in such cases, a preferred construction for such a suffix can be specified, as in Example 1).

And gives an example of:

> **0.1038/issn.1476-4687** DOI suffix using an ISSN. To construct a DOI suffix  using an ISSN, precede the ISSN (including the hyphen) with the  lowercase letters "issn" and a period, as in this hypothetical example  of a DOI for the electronic version of Nature.

And I note many journals embed the issue, volume, and pages into the DOI.

It doesn't appear to break the DOI specification, so if the system can make life a bit more efficient (less opaque) for humans, I think it would be a good feature.

**Comment by pdurbin** [comment]
> letMeSpecify (or whatever we want to call it)

@mankoff these days you can write your own stored procedure: https://guides.dataverse.org/en/5.12/installation/config.html#identifiergenerationstyle

Does that help?
