### ISSUE TITLE
Addition to User Guide

### ISSUE THREAD

**Issue by philippconzett** [IQSS/dataverse#7055]
The section Notifications in the Dataverse User Guide (cf. [http://guides.dataverse.org/en/latest/user/account.html](http://guides.dataverse.org/en/latest/user/account.html)) says that as a user you will receive notification when "[a]nother Dataverse user has requested access to a restricted file in one of your datasets". I suggest you add that this is only true if the user has the Curator role. A user with only the Contributor role will not get this notification. Instead the curator of the dataverse where the dataset/file has been published will get a notification about requested access to a restricted file. In our installation, the curator will then contact the depositor to check whether access should be granted. It makes sense that only users with the Curator role get this notification as the Curator role is needed to grant access to a restricted file.

**Comment by jggautier** [comment]
Great catch! I agree the user guides should be updated.

> It makes sense that only users with the Curator role get this notification as the Curator role is needed to grant access to a restricted file.

File request notifications not being sent to dataset contributors is a surprise to me - didn't realize it when we put together [an inventory of Dataverse notifications](https://docs.google.com/spreadsheets/d/1Bw8MdN2Cv_IZp31hzZgtdyremvA2DobsC1O9x3PguJY) (the inventory didn't have the associated roles recorded for this notification, and most other notifications don't).

I'm not sure that journal editors that have authors use the submit for review workflow to submit datasets would prefer that they handle all access requests to restricted files. But I don't think we've ever heard any complaints from journals using Harvard Dataverse, maybe because there are very few datasets (only four right now) in "Journal" dataverses with restricted files and file access request enabled, and very few downloads recorded for those files, so these journals don't seem to need to deal with these notifications in the first place.

Maybe this is an "if it ain't broke, don't fix it situation", but I'd be curious to know what other Dataverse users/curators think. (There are also older issues like https://github.com/IQSS/dataverse/issues/868 that I think propose a more flexible notification system.)

**Comment by philippconzett** [comment]
Thanks, @jggautier! I agree that there is no need to fix the system other than updating the guide. I also just left a note in the #868 issue.

**Comment by pdurbin** [comment]
@philippconzett hi! If you feel like making a pull request, the file to edit is https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/user/account.rst

**Comment by philippconzett** [comment]
Thanks, @pdurbin! I have submitted a pull request.
