### ISSUE TITLE
Reserve file-level DOIs?

### ISSUE THREAD

**Issue by adam3smith** [IQSS/dataverse#7068]
At QDR, we're thinking of enabling reserving DOIs for files prior to publication. 

**User Story:** As a researcher, I want to refer to a data file (think a specific interview or document) in a manuscript. I _don't_ want to publish the data project until the manuscript is published and I want to avoid having to replace all file placeholders with DOIs prior to publication.

**Implementation considerations:** Given that files are often deleted and DOIs never published, we don't want to reserve those DOIs with datacite but rather reserve them internally, the way project DOIs are currently reserved in Dataverse. 
Given the fact that files can be deleted (and, in fact, commonly are deleted and replaced in our curation process) we might want to consider making this available via a manual option rather than always (which may lead to misunderstandings and non-existing DOIs ending up in citations); on the other hand, auto-generating them is a cleaner solution with no additional UI requirement.

**Question:** Would this be something that IQSS would consider for the core dataverse code and if so, what are the main concerns that we'd need to address? (I didn't go back to look through the file DOI discussion to see what were the considerations there, so may just require a link).

CC @qqmyers

**Comment by qqmyers** [comment]
FWIW: I think reserving at DataCite, at file creation time (or manually upon request), would also work. (We'd have to make sure that deleting the file also deleted the reserved DOI at DataCite (allowed until the DOI is made findable) and that DataCite isn't charging for them.) There are two reasons that wasn't done already that I'm aware of:

- DataCite didn't support reservations at first. They do now, so Dataset DOIs are being changed to reserve at DataCite when they're created
- DOI creation is slow enough that creating hundreds during an upload didn't make sense. This is probably still true, but the work in Dataverse to make API calls to DataCite asynchronous (and able to be retried if they fail due to DataCite being down) could help resolve this.

That said, the main advantage of reserving with DataCite is to avoid other apps with the same authority/shoulder from reusing the same DOI which is unlikely at all given the naming schemes and even less likely if using the file DOI = <datasetDOI>/<filepart> convention. So if DataCite want's to charge for reserved but not findable DOIs, it may not be worth it.

**Comment by djbrooke** [comment]
Thanks @adam3smith for starting the conversation. I'm in favor of this change and I think it'd be good to bring into the core codebase. The use case that you outline exists at multiple institutions. There's also general interest in more functionality pre-publish, and this could be useful. 

- @jonc1438 - for GDCC, will Datacite charge for Draft DOIs? I searched the docs and I could not find details.
- @qqmyers, we have the ability to unregister DOIs for destroyed datasets, added in #6060, and we could do similar with file DOIs upon deletion if we do decide to register with Datacite instead of locally.  
- If we reserve locally only, I think we'd want to autogenerate instead of having some manual option. I'd like to get an answer to the first bullet above before considering how we'd handle this for file DOIs registered on Datacite. :)   
- Whether we reserve locally or with Datacite, we'd need to plan to wait until the dataset DOI gets reserved before reserving the file DOIs.

**Comment by luddaniel** [comment]
Just adding a comment to say that #7334 should fix an encountered issue : if something goes wrong during a `FinalizeDatasetPublication` that is taking too long cut by Payara being stopped for whatever reason, part of DOI files might be `Findable` in Datacite while not existing in Dataverse Database. DOI file reservation as Draft will fix this issue.
@qqmyers @pdurbin
