### ISSUE TITLE
DOI registration is not confirmed by Datacite

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#7102]
Now that pull request #6901 has been merged, a DOI is reserved from DataCite when a dataset is created.

However, what if something goes wrong? What if the DOI is not reserved on the DataCite side? In this case we want to prevent publishing.

As part of the pull request above, the following commit implemented this:

- 28f3222 grey out publish button if DataCite and no PID create time

However, the code on the xhtml side was removed in a flurry of merge conflict resolution (where render logic was refactored).

#6980 is related in that the button will stay greyed out until someone does something to reserve the DOI.

**Comment by landreev** [comment]
From the discussion yesterday, it sounds like we never implemented dropping the DOI from the citation shown on the draft page, until the Datacite DOI is reserved. (the idea was, we don't want to encourage the author to start sharing the DOI, if there's a chance it'll have to change). 
Should we address that as part of this issue?

**Comment by landreev** [comment]
And to summarize the "no publish until reserved" part, since there was (somehow?) so much discussion involved:
This is the code that got lost, from the xhtml of the page:
```
 or (settingsWrapper.dataCiteInstallation and DatasetPage.dataset.globalIdCreateTime == null)
```
rather than putting it back into the xhtml, it was requested to add it to the bean in which all the rendering logic now lives. Still going to be a one line change or so.

**Comment by landreev** [comment]
I've changed the subject back, just to avoid any confusion, and to be boring and a stickler to precision. 
This is not about any *publish* errors. (publish hasn't been attempted yet). 
There are two possible scenarios why the DOI may not have been reserved:
1) This is a Dataverse that has been upgraded from a pre-v5.0 version; and the admin hasn't yet reserved the DOIs for the existing drafts;
2) There was a Datacite error when the dataset was created.

**Comment by landreev** [comment]
BTW, I verified, and this check - whether the doi is reserved, if "reserveable" - is already inside PublishDatasetCommand. So if we left that publish button un-greyed out and somebody tried, it would fail with a clear message to the user. (it would fail in the first, synchronous and quick, command - the PublishDatasetCommand proper). So by greying it out we are just sparing them some unnecessary heartbreak.

This also means it'll fail cleanly and properly if an API user try to publish a dataset with an unreserved datacite DOI; without any extra changes needed.

**Comment by djbrooke** [comment]
Thanks @landreev for the additional info here.

After some discussion with @TaniaSchlatter @mheppler and @pdurbin I now feel it would be better to show the "contact support" message that you mention if publishing is attempted for  a non-reserved dataset, instead of greying out the button. 

When I previously made the decision to grey out and not show any messaging, I thought that the proposal was that we grey out AND show a message, which I felt would generate too many support contacts whenever there was a short delay with DataCite registration. We should instead show the button and provide the message about being unable to publish and to contact support, as this will handle those actual cases where someone wants to do split second publishing after creating their dataset and will not create unnecessary support cycles of people seeing a message in all cases.

Thanks all for the discussion here, and happy (really!) to discuss further if needed.

**Comment by pdurbin** [comment]
> better to show the "contact support" message

Without any changes, on the develop branch as of 941d17dd0, the following two screenshots show the user experience when you click "Publish" and then "Continue":

<img width="1143" alt="Screen Shot 2020-07-22 at 1 05 06 PM" src="https://user-images.githubusercontent.com/21006/88206522-61c9ff00-cc1c-11ea-9b68-90d848db94c8.png">
<img width="1143" alt="Screen Shot 2020-07-22 at 1 05 17 PM" src="https://user-images.githubusercontent.com/21006/88206513-5f67a500-cc1c-11ea-9bb8-a9fb160a9730.png">

I'm happy to change "Cannot publish dataset because its persistent identifier has not been reserved" to something else if we want. Otherwise, I don't plan to make any changes to how the Publish button works. No greying-out, etc.

Next I'll look into changing the citation but as I mentioned during the design meeting, the DOI will show up in various places such as the URL.

**Comment by pdurbin** [comment]
I just pushed 8e3149ce4 to make a very minimal change to just the citation. The logic checks if "GlobalIdCreateTime" is null, which is what we use to mean if a DataCite DOI has been reserved or not. (I'm not sure how Handle or EZID works.)

Mostly, I just wanted to show some screenshots.

Here's a dataset without a DOI in the citation:

<img width="1143" alt="Screen Shot 2020-07-22 at 4 12 05 PM" src="https://user-images.githubusercontent.com/21006/88223978-5b488100-cc36-11ea-99df-ade51dbbe369.png">

For comparison, here's a normal dataset.

<img width="1143" alt="Screen Shot 2020-07-22 at 4 12 22 PM" src="https://user-images.githubusercontent.com/21006/88223984-5e437180-cc36-11ea-93d7-040283deaa2d.png">

**Comment by pdurbin** [comment]
Ultimately, we decided to add a message to the top. I just made pull request #7121.
