### ISSUE TITLE
Bagit PostPublication Workflow: Some datasets generate invalid bags

### ISSUE THREAD

**Issue by mderuijter** [IQSS/dataverse#7130]
While experimenting with the internal archiver workflow and using the [dataverse-sample-data ](https://github.com/IQSS/dataverse-sample-data) script. I noticed only 10 out of 21 datasets are archived and out of those 10 bags 4 are invalid and won't unzip. 

![Screen Shot 2020-07-24 at 12 19 15](https://user-images.githubusercontent.com/56864998/88404223-e6a84a80-cdcd-11ea-927f-c6447592774a.png)

These are the titles of the datasets from the sample data that generate invalid bags:
1. Cause of Death Data
2. Dataset with Shapefiles, Images, and Tabular Files
3. “Changes in test-taking patterns over time” concerning the Flynn Effect in Estonia
4. Data from the BAFACALO project: The Brazilian Intelligence Battery based on two state-of-the-art models: Carroll's model and the CHC model.

My internal archiver workflow config is as follows:
<img width="332" alt="Screen Shot 2020-07-24 at 16 36 41" src="https://user-images.githubusercontent.com/56864998/88405655-df823c00-cdcf-11ea-854b-5027a8c4d3b5.png">

This appears to be a bug in the bag generator.

**Comment by qqmyers** [comment]
Thanks for the report! Looks like the bagger is currently hardcoded to retrieve files via https (It streams the files into the bag from their source (such as S3) rather than creating a local copy.) It looks like those calls are failing when the server is on http and all of the bags for datasets that contain files are bad on a server using http ( out of 10 here I think). Is that your case or is there also another issue to fix? 

(W.r.t.  10 out of 21 - the sample data only has 10 datasets (and 10 dataverses plus root but those aren't archived).

**Comment by qqmyers** [comment]
FWIW: Until this is resolved, one work-around would be to test with a self-signed cert.

**Comment by mderuijter** [comment]
@qqmyers Using a self-signed cert did indeed solve the problem for the most part. 
But i noticed a NullPointerException which results in some empty zip files when the field contactNameTerm is left empty:
![image](https://user-images.githubusercontent.com/56864998/101474022-d511aa80-394a-11eb-9640-6e334d208b41.png)
![image](https://user-images.githubusercontent.com/56864998/101474056-e3f85d00-394a-11eb-8741-1831b08b2633.png)

**Comment by mderuijter** [comment]
@qqmyers I think there should be an `if(contactNameTerm != null)` to prevent the NullPointerException

**Comment by qqmyers** [comment]
Yes. It looks like there are two places to check (where you indicate and a few lines up for the case when there are multiple contacts in an array.) I'll reopen the issue.

**Comment by qqmyers** [comment]
@mderuijter - since you're looking at the ORE/Bags - I want to make sure you're aware of the [Request For Comments](https://docs.google.com/document/d/1UeWgVozS8B6VV94Um0olglT1KyRf6mbqI-ITBmvb4L4/edit?usp=sharing) we have regarding planned changes. If you have any concerns/other thoughts, please comment there.

**Comment by mderuijter** [comment]
> @mderuijter - since you're looking at the ORE/Bags - I want to make sure you're aware of the [Request For Comments](https://docs.google.com/document/d/1UeWgVozS8B6VV94Um0olglT1KyRf6mbqI-ITBmvb4L4/edit?usp=sharing) we have regarding planned changes. If you have any concerns/other thoughts, please comment there.

Yes thank you, I'll share this with my team at DANS.
