### ISSUE TITLE
Add File tags to advanced search, update dataset page to allow file tag searching (with proper syntax)

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#7194]
Currently you can type fileTags:XXXXX and dataverse will search the index for XXXXX in the fileTags. But we should add this as a field in Advanced Search, so the user does not need to know this syntax.

(additionally we need to make sure it works this way from the dataset page, as in some quick tests fileTags:XXXXX did not return results as expected)

**Comment by scolapasta** [comment]
An example of the fileTags search prefix working:

![image](https://user-images.githubusercontent.com/4268292/90043113-a1bf5780-dc99-11ea-8af0-648a7839edb3.png)

**Comment by scolapasta** [comment]
But not on the dataset Page:

**Comment by TaniaSchlatter** [comment]
Next step involves making the UI functionality that is there more apparent to the user, using the syntax that exists.

**Comment by pdurbin** [comment]
I just poked around the code and will go ahead and make a pull request to add "File Tags" to the Advanced Search page. Making this change is easy and straightforward (in line with the "Small" estimate) and clearly provides value, surfacing a feature in the UI that was hidden. Here's how it looks (feedback welcome):

<img width="751" alt="Screen Shot 2020-11-03 at 3 10 41 PM" src="https://user-images.githubusercontent.com/21006/98037491-a81d2580-1de9-11eb-8542-eaa59e0c6dab.png">

The other thing that's being suggested in this issue is to allow users to type "fileTags:GOAT" (for example) into the search at the dataset level. Very few users will want to do this (or remember to prepend "fileTags:" to their query) and rather than a significant rewrite of the code to support this, I'd like to suggest a couple alternatives.

Alternative 1 is to simply point users to the nice existing feature where they can click "File Tag" and then click on the tag they are interested in. Here's an example from https://doi.org/10.7910/DVN/NSTBR7 :

<img width="604" alt="Screen Shot 2020-11-03 at 3 28 15 PM" src="https://user-images.githubusercontent.com/21006/98037492-a8b5bc00-1de9-11eb-8e59-b802d61aebcf.png">

Alternative 2 is to make file tags searchable without requiring "fileTags:GOAT" (for example). You would just type "GOAT". Right now filename and description is searched and the fix would be to add file tags to the list of fields that are searched. Here's an example of searching for the tag "Foo Bar":

<img width="639" alt="Screen Shot 2020-11-03 at 3 47 18 PM" src="https://user-images.githubusercontent.com/21006/98039126-34304c80-1dec-11eb-8a83-2abe3bd9961a.png">

**Comment by djbrooke** [comment]
Thanks @pdurbin for starting the discussion and bringing up the alternatives. I was under the impression that the filetags:xxx on the dataset search was a small change but it sounds like it may be bigger. I use the functionality on Github (for label: anyway) and I could see it being useful here when there are lots of files or tags, but if it's not easy then it's definitely worth discussing cost/benefit. 

Another alternative is how Google handles this - if the inputted text matches a label, it suggests it as an option:

<img width="397" alt="Screen Shot 2020-11-03 at 4 03 31 PM" src="https://user-images.githubusercontent.com/7773392/98040464-51feb100-1dee-11eb-9c73-5702fb4b8a8e.png">

It'll be good to get a take from @TaniaSchlatter here as well.

**Comment by qqmyers** [comment]
FWIW: Aside from being rather hidden, the fileTags:GOAT in the simple search box option, and the fact that the simple search accepts the _full_ solr query grammar, makes it very hard to implement full text search on restricted files. (See QDR's [implementation](https://github.com/QualitativeDataRepository/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/search/SearchUtil.java#L192) and enjoy the regexps - they're the reason there was no PR for this. The basic issue is that if there are indexed things with different levels of restriction (open metadata and restricted file contents today, but DataTags going forward), then the search logic has to deal with all the and/or/not logic, special fields tags, etc. that go in the simple search field.) 

My vote would be to keep simple search simple (and make it simpler than it is now) and support other features via the advanced search and/or other means.

**Comment by TaniaSchlatter** [comment]
Alternative 2 that @pdurbin describes would be great: make file tags searchable without requiring "fileTags:GOAT" (for example). You would just type "GOAT".

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
