### ISSUE TITLE
Possible to reset "Downloads" counter on homepage?

### ISSUE THREAD

**Issue by BPeuch** [IQSS/dataverse#7212]
Version: 4.20

Hello everybody,

Sorry if that's already been asked, but I couldn't find anything in relation to this in the Dataverse guide (neither in the Metrics API nor in the Make Data Count sections).

Is there a way to reset the "Metrics: Downloads" counter on the homepage of Dataverse?

Our problem is that we've been doing a lot of testing (and therefore test downloads) but now that we are about to go live, we would like to wipe the slate.

**Comment by djbrooke** [comment]
Hey @BPeuch - there's not a way I know of to reset this number, outside of some direct database edits. That may cause other issues. How many test downloads have you generated? :)

**Comment by BPeuch** [comment]
Hey @djbrooke. Thanks for your quick answer.

We are looking into Dataverse's DB as we speak, so we might very well experiment with that in the future and report on our outcomes.

So far our meter registered 105 downloads.

**Comment by scolapasta** [comment]
If you haven't set up any Make Data Count, it should be straightforward in the db: there are two tables:
filedownload
guestbookresponse

if you're ok clearing all your downloads, you should be able to just delete all the rows from these two tables.

**Comment by qqmyers** [comment]
FWIW: I have looked at the datasetmetrics table, which is the only table involved in MDC tracking of counts and that is one where you could delete entries prior to a certain date or truncate and repopulate by rerunning counter-processor only for the mdc logs you consider good/non-testing.

Also note - even with MDC turned on, the file page reports downloads from the non-MDC/guestbook entries. (MDC is only reporting downloads at the dataset level.) Because of that, the download counts on the file page won't necessarily match the downloads on the MDC_enabled dataset page (since MDC removes robot downloads, etc), but if you remove MDC counts, the disparity will be even wider (since the file page would still show test downloads as well) unless you also handle the internal (filedownload/guestbookresponse) counts.

Lastly, there have been some discussions w.r.t. MDC and being able to suppress counts from testing on an ongoing basis. I don't know that anyone has implemented this, but it may be possible by adding any machines that are used for testing to the blacklist counter-processor uses to remove counts from robots/crawlers.  Again, these changes wouldn't address the file page download counts since those aren't filtered by counter-processor, so perhaps this wouldn't be worth it. (The script normally pulls those from a list maintained at github but one could point to a fork/local copy that has additional entries for test machines. If you figure that out, I'd be interested to know details.)

**Comment by djbrooke** [comment]
Hey @BPeuch - I'm going to close this since there's not any code change here. If there's some query that could be useful for the community, feel free to share it in the common queries doc linked from the guides:

https://docs.google.com/document/d/1-Y_iUduSxdDNeK1yiGUxe7t-Md7Fy965jp4o4m1XEoE/edit#heading=h.avuoo5kf0mdt

**Comment by BPeuch** [comment]
Thanks, @djbrooke. I will. That's a very helpful document here I did not know about!
