### ISSUE TITLE
Support newer version of Sphinx so that Guides Search still works

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#7233]
I acknowledge this issue is a bit slim on content, but I'll do my best to summarize and let more technical folks fill in the details. 

In #7228 we ran into an issue with Guides search that we plan to resolve by doing a local build of the guides on version 1.5.x of Sphinx, which we'll then put up on the guides.dataverse.org server. This course of action was taken because my primary goal was to get search working.

In a future version of Dataverse I'd like to use newer versions (3.2.x) of Sphinx, and I'm happy to assign some sprint time to this. 

Thoughts/discussion welcome.

**Comment by mheppler** [comment]
Need to review the latest code for Sphinx available at https://github.com/sphinx-doc/sphinx.

Started a branch `7233-sphinx-jquery-update` and removed the local copies of jQuery 3.4.1 that were added in #4219, which was originally intended to upgrade the copy of jQuery from Sphinx but it did not, it only added a second jQuery library to the source code.

Since multiple jQuery libraries is [known to produce $.getQueryParameters undefined errors](https://github.com/sphinx-doc/sphinx/issues/1676), we should start this effort with a clean slate, and only one jQuery library referenced in the source code.

I was able to get search working in Sphinx 1.8-something with these changes and a few more fixes, but it has not worked in Sphinx 3.3.0 (the latest of this writing), which is using jQuery 3.5.1.

**Comment by pdurbin** [comment]
Today Sphinx 1.5.6 was installed on the guides server to build the docs for Dataverse 5.1.

**Comment by pdurbin** [comment]
I spoke with @djbrooke and @donsizemore about this issue.

The main features we want is what we've had for years:

- automatic building of the guides
- working search for the guides

The good news is that as of Tuesday, thanks to @donsizemore, we are back to having both.

The fix was to switch back to Sphinx 1.5.6, which we have used to build the guides for over 3 years (since Dataverse 4.8.6).

The guides are built from a Jenkins job and Ansible is used to ensure that the right version of Sphinx is installed.

While the building of the guides is mostly automated, there are a couple of manual steps:

- Before clicking "Build Now", the version needs to be updated in the job.
- After the job has finished, the "latest" link is manually updated.

The job can be found at https://jenkins.dataverse.org/job/guides.dataverse.org/ and the config for the job can be found at https://github.com/IQSS/dataverse-jenkins

Given the age of Sphinx 1.5.6 (released in May 2017), it likely contains Javascript vulnerabilities. Unfortunately that means that there may be Javascript vulnerabilities in the docs for the past 47 releases of Dataverse. To address this risk we should think about what to do about docs for old releases of Dataverse. Do we disable Javascript features such a search for docs of old releases? Do we rebuild all docs with modern versions of Sphinx periodically? How much of a maintenance burden would that become?

In short the immediate goals for this issue have been met. When we cut a release, we can do an automated build of docs with search enabled.
