### ISSUE TITLE
Short-lived Tokens (DP Tool)

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#7244]
Revise/extend the token system to include tokens which are:
  - Short-lived
  - (ideally) Narrowed in scope

The origin of this issue is Dataverse integration with the DP Tool (#7158) where the workflow includes temporary storage of the Dataverse API token by both the DP Tool as well as the Microsoft (MS) Execution Engine. Concerns raised by Microsoft during the initial integration are that:
  - The temporary storage of a token with full user privileges increases the potential security threat surface
  - The main concern is a long-lived token that can read private data
  
In addition to tightening security for the DP tool integration, an advantage of an update to the token system is that it could be further open up Dataverse dataset usage for applications that use non-public data in their workflows.

**Comment by qqmyers** [comment]
In #5671 is a [note](https://github.com/IQSS/dataverse/issues/5671#issuecomment-476702800 ) about implementing what amounts to presigned URLs for external tools - time-limited, API-call and user specific URLs that could be sent to external tools instead of a general api key. The design I mentioned there uses a hash mechanism to avoid having to track existing tokens in the db. Happy to discuss/help implement if that's of interest for this issue.

**Comment by qqmyers** [comment]
FYI: #7325 implements URL signing/validation algorithms as mentioned above that would allow restricting tool access to a specific API call(s) and specified time window. #7325 uses this to provide secure access to a remote file store intended for use with a shared key from the remote service, but the algorithm can also be used with a user's API key instead which should make it easy to add URL validation in front of the existing user-based access control checks.

**Comment by pdurbin** [comment]
Related:

- #9001

**Comment by pdurbin** [comment]
As mentioned above, Signed URLs should be used: https://guides.dataverse.org/en/6.0/api/external-tools.html#authorization-options
