### ISSUE TITLE
Is RData/Rds download and ingest necessary?

### ISSUE THREAD

**Issue by kuriwaki** [IQSS/dataverse#7249]
As a R user I don't think we need the following functions in the Dataverse GUI:

1.  A data user downloading a ingested file in RData file
2. A data creator having their RData files being ingested

For the first point, R has no problem reading csv's/dta's so forcing it into a RData is at best superflous.   For the second, most RData files in the wild are not rectangular datasets. In fact the comparative advantage of a RData file is that it can bundle any arbitrary R object (in which case "download as original" works best).

Related  (but different) issue: 

- There have been discussions of how to download RData files or Rds files at #6678. That's a discussion about what file transformation Dataverse should apply when user asks for the "R" download option.

**Comment by kuriwaki** [comment]
I've edited the original post ^ for clarity.

**Comment by landreev** [comment]
Some of my thoughts on this: (mostly copy-and-pasting from a discussion last week)

I feel like we should be entirely open to discussing this [discontinuing download-as-RData]. Like much of the functionality we offer, generating these RData frames for ingested files is basically legacy. So it’s entirely possible that it’s no longer needed. It is true that anyone who uses R should be able to import a tab-delimited frame into R; or to download and import the Stata original into R, etc. 

And as for attempting to ingest RData frames: I understand the argument that "most RData files in the wild are not rectangular datasets". But, instead of eliminating ingest for RData altogether, personally I would prefer to make it optional. I.e., would give the user an easy option to skip the ingest (or even make it skip ingest by default, with an optional checkbox for ingest...). If it were up to me, I would make ALL ingest optional. Again, this is pure legacy - dataverse was originally created for fairly specific data - from research in a narrowly defined discipline, where most data files were indeed rectangular variable/observation frames, and where ingest was a central part of the functionality. But this is no longer true.

I've been bringing this up and we should continue discussing this (although there has been some push back too [to the idea of giving users an option to skip ingest easily] ).

**Comment by pdurbin** [comment]
Related:

- #8711

**Comment by pdurbin** [comment]
@kuriwaki are you still interested in this? I'm wondering if we should close this issue in favor of this one:

- #8526

That is, we can still consider making RData ingest and download optional. We can still refer back to this issue.

**Comment by pdurbin** [comment]
@kuriwaki yes, I do think the substance of this issue will be considered when we get around to the other issue (#8526) so I'll go ahead and close it. Thanks.

I definitely appreciate your perspective on this!

For further discussion, I think a mailing list post might be better, so please feel free to kick off a thread at any time (you or anyone reading this): https://groups.google.com/g/dataverse-community
