### ISSUE TITLE
Recent Activity on Homepage Shows ...

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#7382]
See attached screenshot. We used to see numbers for all activity, now we see ... 

<img width="983" alt="Screen Shot 2020-11-03 at 11 35 58 AM" src="https://user-images.githubusercontent.com/7773392/98013818-d9d1c480-1dc8-11eb-8623-62ffe18a47e6.png">

I changed some values in developer tools and looked through https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/_static/installation/files/var/www/dataverse/branding/custom-homepage-dynamic.html but I didn't see anything specific. 

One other thing I'll mention is that I see a commit from last year (https://github.com/IQSS/dataverse/commit/39be7f6e76331b3523ca1866fb1fc7177a6b2fc4#diff-f3fc97bbca6598d78d2ee05b2c034e2cf6c698600286c712daa6585db178919b) that changes "All" to "Total" on the home page, but it doesn't seem this change is reflected on the page itself. 🤔 Maybe we're not running the latest version of the homepage in prod?

**Comment by scolapasta** [comment]
I'm fairly sure I know the issue here.

The way these values work is that they start as "..." then gets replaced by an javascript call. Here are the two JS calls that don't seem to populate:

`
    queryMetricSimple("datasets", "?dataLocation=all", ["headAllTimeAllDatasetsValue", "activityAllTimeAllDatasetsValue"]);
    queryMetricSimple("downloads", "", ["headAllTimeAllDownloadsValue", "activityAllTimeAllDownloadsValue"]);
`

But in the source code, those head* values got commented out. So it must be breaking because it can't replace the first (head*) value and never gets to the 2nd. 

(note: there is also a third for dataverses that involves head*, but only individually:
`
queryMetricSimple("dataverses", "", "headAllTimeAllDataversesValue");
`)

The fix will be to either:
• uncomment out the head* values
• remove the head* values from the javascript call
(alternatively, you could possibly switch the order of the values in the JS call, and the one that fails would be 2nd. But either we want these or we don't...)

**Comment by scolapasta** [comment]
Actually, it's dumber than that. These lines got commented out in production:
`
    // queryMetricSimple("datasets", "?dataLocation=all", ["headAllTimeAllDatasetsValue", "activityAllTimeAllDatasetsValue"]);
    // queryMetricSimple("downloads", "", ["headAllTimeAllDownloadsValue", "activityAllTimeAllDownloadsValue"]);
    // queryMetricSimple("dataverses", "", "headAllTimeAllDataversesValue");
`

Who did that?

**Comment by scolapasta** [comment]
My guess is the above were commented out when the spans that would show the head* values got commented out. But that had the undesired affect and not making this call for either place (same # used in two places).

I went ahead and added two lines:
`
    queryMetricSimple("datasets", "?dataLocation=all", "activityAllTimeAllDatasetsValue");
    queryMetricSimple("downloads", "", "activityAllTimeAllDownloadsValue");
`
and they are back to working.

Note the code in the repo would also be fine since it doesn't have any of this commented out. Not sure who made the change and why they made it directly in prod and not via github. Of course, now I did that too, so what's left is to decide what we want and sync the github and actually being used pages. But for now, this is fixed in current prod.

![image](https://user-images.githubusercontent.com/4268292/101963703-5a13f280-3bdd-11eb-8446-069e3f3561e0.png)

**Comment by mheppler** [comment]
@scolapasta -- apologies for getting a little too aggressive with my code comments. Should have paid closer to attention to what I was hacking up when the last metrics revisions were made. I have taken your fixes from your comment above and applied them to the customization resource files in Google Drive ... Harvard Dataverse Customization > resourcesProd-2020-12-16.zip.

You have my blessing to close this issue, will be happy to revisit and revise our processes in IQSS/dataverse.harvard.edu#94 and  IQSS/dataverse.harvard.edu#93.
