### ISSUE TITLE
Distributor tag automatically added in the OAI-DDI and DDI export

### ISSUE THREAD

**Issue by bappun** [IQSS/dataverse#7387]
A distributor element is automatically added in the OAI-DDI and DDI export.
In our case, "data.sciencespo" is added alongside "Sciences Po, Centre de données socio-politiques (CDSP), CNRS (CDSP)".

We have this in our [dataset](https://data.sciencespo.fr/dataset.xhtml?persistentId=doi:10.21410/7E4/00LYOG):
![image](https://user-images.githubusercontent.com/24225471/98123881-c13dd900-1eb2-11eb-91f2-425de61390fb.png)

In the OAI-DDI and DDI export we have:

- Inside `<docDscr>`:

```
<distrbtr source="archive">data.sciencespo</distrbtr>
```

- Inside `<stdyDscr>`:

```
<distrbtr source="archive">data.sciencespo</distrbtr>
<distrbtr abbr="CDSP">Sciences Po, Centre de données socio-politiques (CDSP), CNRS</distrbtr>
```

**Comment by pdurbin** [comment]
@bappun well if you want to make a pull request, here's the first place where `distrbtr` appears in the code: https://github.com/IQSS/dataverse/blob/v5.1.1/src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java#L199

I'm a little confused though. Is it a bug? Is it a preference? Should it be configurable? Is it required by the DDI spec? That's where my thoughts are. 😄

**Comment by jggautier** [comment]
Just describing my understanding of the way these fields are used in Dataverse now, and more importantly asking you how you think those fields **should** be used:

The Citation metadatablock's Distributor field is intended to identify who is distributing the data (as opposed to the metadata), and in the DDI Codebook XML export, that Distributor field is mapped to stdyDscr/distrbtr. It's meant to say, the data/study itself is distributed by whatever's entered in the Distributor field, e.g. "Sciences Po, Centre de données socio-politiques (CDSP), CNRS".

A second distrbtr element is used to say that the data is also distributed by the repository. The source attribute is used to signal that "data.sciencespo" is the "archive" charged with storing the data.

All of the metadata in the XML's docDscr section, like docDscr/distrbtr, describes the metadata document itself. The reasoning is that since the repository is distributing the metadata export, the name of the Dataverse-based repository is hardcoded into that part of the DDI XML export. I think someone in the repository's database settings, "data.sciencespo" is set as the name of the repository, and it used in multiple places to identify the repository.

This part of the DDI XML metadata export was changed recently (within the last few months?) to try to follow the DDI Codebook rules more closely (make more of the exported XML valid against the DDI Codebook schema). But these decisions about who or what is labelled as a "distributor" of the metadata document and of the data weren't discussed very broadly. So I think it would be helpful to learn what you think. Could you share that?

**Comment by qqmyers** [comment]
FWIW: Dataverse is currently adding the name of the root Dataverse collection to both the docDscr and stdyDscr fields. There isn't currently a way to add more distributors to docDscr and I assume we always want a value there (true?). That suggests a couple possible changes to address this issue:

1. Add an optional setting for a default distributor that would be used instead of the root collection name for docDscr
2. Only add the default distributor to the studyDscr if there is no distributor set in metadata 

Some variants might include:

3. Add a True/False setting to indicate if the default distributor should be included in studyDscr
4. Use the 'Affiliation' field of a Dataverse collection for the default distributor instead of the collection name (without a setting to override that (option 1) or in addition to it). 

My thought is that options 1 and 2 together would resolve this issue and make sense for other institutions, but, if there are concerns, also adding option 3 would enable full backward compatibility (don't override the default of using the root collection name by adding that setting and use true to make sure the root collection is added to the stdyDscr as well). Option 4 would be a way to avoid having a new setting (option 1), but I'm not sure that the current uses of Affiliation are consistent with using it in docDscr and stdyDscr (since affiliation appears in within parentheses after the collection name, will you always want the same value there and in the DDI?).

So - any thoughts? Do 1) and 2) make sense? Is 3) needed as well?

**Comment by qqmyers** [comment]
Per zoom discussion, SciencesPO is still evaluating the above proposal. We also briefly discussed whether an option to allow a Dataverse collection specific term (as in 4) above) would be useful at SciencesPO or elsewhere. I suggested that we could start with the proposal above, move on with other issues, and if time is available, potentially come back to look at a per-collection option. (Post-call, Danny pointed out that doing that would mean that moving a Dataset would change the citation (which currently includes the distributor). This adds complexity/cost and might mean that we might need to inform users that a move would do this.)

**Comment by bappun** [comment]
At Sciences Po, we only need to be able to set a global distributor that would be used for all datasets. The following solution would perfectly fit our needs:
> 1. Add an optional setting for a default distributor that would be used instead of the root collection name for docDscr

The other solutions are also good ideas since Dataverse could be more flexible and work for more repositories.

**Comment by jggautier** [comment]
@bappun, so it sounds like it's fair to say that you'd like the name of the repository and the name of the "root" Dataverse collection to be two different things, and that you'd like the name of the repository to be included in the DDI exports. [Dartmouth's repository](https://dataverse.dartmouth.edu/) has a similar issue since they're "root" Dataverse collection is still named "root". (I've emailed the repository contact about it but haven't heard back.)

Would this change to the DDI exports also change the other places where the repository's name is added? If not, would you need this change to be applied to other places?

As of version 5.3, the name of the "root" Dataverse is added in:
- Metadata exports:
  - Dataverse JSON:
    - publisher
  - DC Terms:
    - dcterms:publisher
  - DC Core (oai_dc):
    - dc:publisher
  - DDI (xml and html):
    - docDscr > citation > biblCit
    - docDscr > distStmt > distrbtr
    - stdyDscr > distStmt > distrbtr
  - DataCite:
    - publisher
  - OpenAIRE:
    - publisher
  - Schema.org:
    - includedInDataCatalog > name
    - publisher > name
    - provider > name

- Dataset and file citation exports:
  - EndNoteXML:
    - publisher
  - RIS:
    - PB
  - BibTeX:
    - publisher

- HTML meta tags in the dataset pages:
  - `<meta name="DC.publisher" content="Demo Dataverse" />`
  - `<meta property="og:site_name" content="Demo Dataverse" />`

If the definition of done for this story (GitHub issue) is to let Dataverse installations specify the repository name (as opposed to the "root" Dataverse collection name) and to use that name instead only in the one metadata element in the DDI exports (docDscr > distStmt > distrbtr), one or more other issues should be created to correct the metadata in the other places I listed above.
