### ISSUE TITLE
Make a HTML version of the DDI Codebook XML

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#739]
Request from user:

We have a lot of users just now embarking on research data management on behalf of researchers, and one basic requirement we’d like to push to researchers is the inclusion of a detailed file level codebook, ideally based on DDI, and since the XML is quite hard to read, a PDF or HTML version would be great to include alongside other documentation. Having the Dataverse system generate a codebook (preferable PDF and HTML options) would be a useful application

Example PDF of Codebook we can generate from the XML version of the DDI Codebook:
https://drive.google.com/file/d/0BzeLxEN77UZoYll6LTY4dVlyVzQ/edit?usp=sharing

**Comment by pdurbin** [comment]
#2584 is related in the sense that even trying to print a dataset page is messy.

**Comment by mheppler** [comment]
Related in the sense that both involve a printer, but the codebook is an entirely different feature from clicking command-P when viewing a dataset pg.

**Comment by amberleahey** [comment]
hi folks! I think this relates to the work @lubitchv is doing to build a curation tool for variable-level metadata enhancement in Dataverse. I feel like this question may have originally came from us, but I'll second it nonetheless. 

In our investigation to support this kind of Codebook PDF output from the Dataverse Data Curation Tool https://github.com/scholarsportal/Dataverse-Data-Curation-Tool , we've uncovered existing tools , one such workflow would be for Dataverse to support 'Download' of these PDF Codebooks directly. 
The existing tool we've come across is from the DDI community:

Sent from Olof Olsson @the Swedish National Data Service : 
"The nesstar codebook is done via a DDI-C -> XSLT -> XML-FO -> PDF transformation.
 
It was developed by Pascal Heus in 2006 and used in nesstar webview and publisher.
A staff member at SND have done some fixes and restructure of it an published as a part of the ddi-xslt package: https://github.com/MetadataTransform/ddi-xslt/tree/master/ddi-fo
 
Link to the full xslt file: https://raw.githubusercontent.com/MetadataTransform/ddi-xslt/master/ddi-fo/dditofo_complete.xsl
 
To run this you need apache fop https://xmlgraphics.apache.org/fop/ 
 
Example of transformation:
fop -xml ddifile.xml -xsl dditofo_complete.xsl -pdf pdffile.pdf"

Could something like this be packaged and supported IN Dataverse? We weren't sure if it would make sense in the separate curation tool or as part of Dataverse since it would combine study-level and variable-level , representing a Dataverse (repository) generated Codebook for the data. 

Would love to hear ideas / thoughts about this, as I think it means support for new technologies. Maybe there are other existing DV solutions to generate this PDF?

**Comment by pdurbin** [comment]
@amberleahey it sounds neat but does it work? I tried fop-2.3-bin.tar.gz but getting the errors below. Am I doing something wrong? Do you have a working ddifile.xml you can give me?

```
dhcp-10-250-190-90:fop pdurbin$ curl -s 'https://dataverse.harvard.edu/api/datasets/export?exporter=ddi&persistentId=doi%3A10.7910/DVN/TJCLKP' > ddifile.xml
dhcp-10-250-190-90:fop pdurbin$ 
dhcp-10-250-190-90:fop pdurbin$ curl -s https://raw.githubusercontent.com/MetadataTransform/ddi-xslt/master/ddi-fo/dditofo_complete.xsl > dditofo_complete.xsl
dhcp-10-250-190-90:fop pdurbin$ 
dhcp-10-250-190-90:fop pdurbin$ 
dhcp-10-250-190-90:fop pdurbin$ 
dhcp-10-250-190-90:fop pdurbin$ ./fop -xml ddifile.xml -xsl dditofo_complete.xsl -pdf pdffile.pdf
SystemId Unknown; Line #127; Column #210; Could not find function: if
SystemId Unknown; Line #127; Column #210; Extra illegal tokens: 'then', 'concat', '(', ''('', ',', '/', 'codeBook', '/', 'stdyDscr', '/', 'citation', '/', 'titlStmt', '/', 'altTitl', ',', '')'', ')', 'else', '(', ')'
SystemId Unknown; Line #127; Column #210; function token not found.
(Location of error unknown)java.lang.NullPointerException
May 31, 2019 4:00:45 PM org.apache.fop.cli.Main startFOP
SEVERE: Exception
org.apache.fop.apps.FOPException
java.lang.NullPointerException
	at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:296)
	at org.apache.fop.cli.InputHandler.renderTo(InputHandler.java:116)
	at org.apache.fop.cli.Main.startFOP(Main.java:186)
	at org.apache.fop.cli.Main.main(Main.java:217)
Caused by: java.lang.NullPointerException
	at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:279)
	... 3 more

---------

java.lang.NullPointerException
	at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:279)
	at org.apache.fop.cli.InputHandler.renderTo(InputHandler.java:116)
	at org.apache.fop.cli.Main.startFOP(Main.java:186)
	at org.apache.fop.cli.Main.main(Main.java:217)

dhcp-10-250-190-90:fop pdurbin$ 
```

**Comment by amberleahey** [comment]
[xml_ddi.zip](https://github.com/IQSS/dataverse/files/3242734/xml_ddi.zip)
try this one?

**Comment by amberleahey** [comment]
[Hockey Night in Canada, 2014.pdf](https://github.com/IQSS/dataverse/files/3242741/Hockey.Night.in.Canada.2014.pdf)
this is what it would look like as PDF

**Comment by pdurbin** [comment]
@amberleahey sorry but I'm getting the same error when I try that file in your zip like this:

`./fop -xml ari-hnic-E-2014.xml -xsl dditofo_complete.xsl -pdf pdffile.pdf`

Reproducibility is hard. 😄 The above command works for you? Are you on Windows, Mac, or Linux?

**Comment by pdurbin** [comment]
I'm going to take a look at pull request #6081 by @lubitchv (thanks!)

@lubitchv when this goes to QA, does it make sense to test with some of the codebooks from #3648 ? (Kudos to @mheppler for rediscovering that issue.)

**Comment by lubitchv** [comment]
@pdurbin Do you mean to test the conversion of 
Item 1:https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/BAMCSI
Item 2: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/P4JTOD
xmls from #3648 into html codebooks?
In that case, sure, it can be tested. I just run the quick conversion on their xml DDI files and the resulting html looks ok to me, unless you meant something else.

**Comment by pdurbin** [comment]
@lubitchv thanks for testing those! Earlier I tried to spin up your branch on EC2 but I ran into a snag: https://github.com/IQSS/dataverse-ansible/issues/97

**Comment by pdurbin** [comment]
@djbrooke I think pull request #6081 is very close but it delivers HTML so I'm wondering if we should remove "PDF" from the title of this issue to avoid confusion when we link to it from release notes.

It seems like a great feature. Thanks again, @amberleahey and @lubitchv !
