### ISSUE TITLE
Rogue popup displayed for restrict files on Add New Dataset pg

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#7449]
Discovered in a development branch, and replicated in develop, and demo (v. 5.2 build 254-4951505).

1. create new dataset and upload file(s)
2. restrict file(s), Save Dataset, see File Restrictions popup displayed
3. (leave form empty or fill it out) click Continue, see Select File(s) popup mistakenly displayed

ALSO... if you "X' out of Select File(s) popup, it closes popup but the overlay remains covering the pg, same if you cancel on the File Restrictions popup.

The rogue Select File(s) popup does not appear on Edit Files pg, or when restricted on dataset pg, only on the Add New Dataset pg.

As you can see in this screenshot, the Select File(s) popup is displayed over a form that clearly shows there are in fact files selected, never mind the fact that it is displayed at a point in the restrict workflow that is completely inappropriate.

<img width="1156" alt="Screen Shot 2020-12-02 at 4 20 46 PM" src="https://user-images.githubusercontent.com/687227/100932763-59cb7700-34ba-11eb-92f1-77dbc7db8113.png">

**Comment by scolapasta** [comment]
Discussed with @mheppler and @TaniaSchlatter. We decided that rather than fix this to be exactly how it worked, we are going to modify the workflow slightly. The access popup will appear when the user clicks restrict (as it does, when you are on an already saved dataset) rather than when you click save. To help ensure users understand that the popup will modify these values for the entire dataset, the title (and possibly the text) of the popup will be updated, as well.

**Comment by djbrooke** [comment]
@scolapasta @mheppler @TaniaSchlatter Thanks for discussing and finding a good solution here!
