### ISSUE TITLE
API endpoint

### ISSUE THREAD

**Issue by kamil386** [IQSS/dataverse#7475]
Is there any API endpoint currently available to retrieve the information about total downloads of single **file**? I can found API Metrics only related to datasets, not files.

**Comment by pdurbin** [comment]
@kamil386 hi, there is no such API for a count of downloads of a single file. Please keep in mind that any API like this would be for "classic" download counts, rather than Make Data Count (MDC) download counts, which are aggregated at the dataset level.

**Comment by djbrooke** [comment]
Hi @kamil386, there may be something helpful to you in:

https://guides.dataverse.org/en/latest/admin/reporting-tools-and-queries.html 

I'm going to close this issue because I think the question is answered, but if none of the tools above work for you and this endpoint is important, we could consider it as a feature request (and would be happy to look at any PRs submitted). If this is the case, please feel free to open a new issue.

**Comment by qqmyers** [comment]
FWIW: The not yet merged PR #7178 adds a file downloads per dataverse endpoint. Not all the way to dataset, but fairly selective and you'd be able to filter based on DOI from there. That might be a future option.
