### ISSUE TITLE
Application Allows Form Submission Without Maximum Character Limit

### ISSUE THREAD

**Issue by felipecastro-fiocruz** [IQSS/dataverse#7486]
Hello everyone!

It was identified that the application does not restrict a maximum limit of characters sent in the text box, and may contribute to an eventual outage scenario with the sending of thousands
of characters at the "Description box"

The recommendation is : "to apply a maximum character limit for each field on the form to prevent
very large messages are sent in order to allocate storage resources
arbitrarily."

My Dataverse is 4.20, any suggestions? Has this been fixed in newer versions? Thank you!!

![print 3](https://user-images.githubusercontent.com/68251561/102645107-b5dffd80-4140-11eb-9520-511e81282b22.PNG)
![print 4](https://user-images.githubusercontent.com/68251561/102645110-b7112a80-4140-11eb-97df-10d49c15acdb.PNG)
![print 5](https://user-images.githubusercontent.com/68251561/102645115-b8425780-4140-11eb-9a6b-998ada9df0e9.PNG)
![print 6](https://user-images.githubusercontent.com/68251561/102645117-b8daee00-4140-11eb-9974-624a26f97f67.PNG)
![print 1](https://user-images.githubusercontent.com/68251561/102645119-b8daee00-4140-11eb-8cfe-fc7aee115dc4.PNG)
![print 2](https://user-images.githubusercontent.com/68251561/102645121-b8daee00-4140-11eb-9eab-df93099f3bda.PNG)

**Comment by djbrooke** [comment]
Hey @felipecastro-fiocruz - thanks for the report. I think instead of setting a max character limit we'd want to do a better job with truncation, which we're investigating as part of a larger effort in https://github.com/IQSS/dataverse/issues/6685. This has not yet been implemented in Dataverse. 

Since we're tracking the truncation work in the other Github issue, I'll close this one, but feel free to reply if you have other ideas.
