### ISSUE TITLE
Allow non-integer sequential identifiers 

### ISSUE THREAD

**Issue by claudiodsf** [IQSS/dataverse#7548]
Dataverse provides a [mechanism](https://guides.dataverse.org/en/latest/installation/config.html#identifiergenerationstyle) for generating integer sequential identifiers through a database stored procedure.

In our implementation, we would like instead to generate fixed length string hashes that keep chronological order.
We already have a stored procedure for that, written in Perl, that returns a `char` instead of a `int`.

However, Dataverse [casts](https://github.com/IQSS/dataverse/blob/fb772d1dfbe78c7b96c88dbafa6218f8511f3a15/src/main/java/edu/harvard/iq/dataverse/DatasetServiceBean.java#L290) the output of `generateIdentifierAsSequentialNumber` to an `Integer`, and then [converts it](https://github.com/IQSS/dataverse/blob/fb772d1dfbe78c7b96c88dbafa6218f8511f3a15/src/main/java/edu/harvard/iq/dataverse/DatasetServiceBean.java#L296) to a `String`.

It would be nice if the output of `generateIdentifierAsSequentialNumber` could be considered a `String` or if another function could be added (e.g., `generateIdentifierAsSequentialString`).

**Comment by djbrooke** [comment]
Hey @claudiodsf - if this is important your installation, would you consider making a pull request to add this functionality? If you're interested in making a PR for this, @scolapasta and others could advise on the feasibility and implementation details.

**Comment by claudiodsf** [comment]
I can take a stab at it, but I'm not a Java programmer! 

But, if only a slight modification of `generateDatasetIdentifier()` is required, along with the creation of a new function similar to `generateIdentifierAsSequentialNumber()`, I think that it is feasible.

Before making a PR, I would like to be sure on the way this should be implemented.
Should we add a new option for `:IdentifierGenerationStyle` ? For instance: `string` or `customString`?

I would then create a Java function called `generateIdentifierAsString()` or `generateIdentifierAsCustomString()` which would look for a stored procedure with the same name.

What do you think? Any better idea?

**Comment by scolapasta** [comment]
Since it's unlikely that any installation would use two different methods for generating their ids, we could also  just modify the existing code to cast as a String.

In order to make sure it isn't confusing, some renaming might be in order:
`generateIdentifierAsSequentialNumber`-> `generateIdentifierFromStoredProcedure`
`sequentialNumber` -> `storedProcGenerated`

This seems more scalable than adding a new type, while allowing any installation to just modify the stored procedure, as needed.

**Comment by claudiodsf** [comment]
That's certainly the easiest approach. 

But renaming would break backwards compatibility. Aren't you concerned about that?

**Comment by pameyer** [comment]
Regarding backwards compatibility, documenting the SQL `ALTER FUNCTION generateIdentifierAsSequentialNumber RENAME TO generateIdentifierFromStoredProcedure` seems like it might be enough (if there were still sql scripts for updates, it might make sense to include there - but it seems likely to me that there aren't enough installations using the currently named stored procedure to bring back update scripts just for that).  If this is something that could be included in the flyaway scripts, then that should make it backwards comparable enough to be unnoticeable.

**Comment by scolapasta** [comment]
Yes, but the backwards compatibility should be handled with release notes and flyaway scripts:

Release note to explain the change and that if you are using this to modify your setting.
The flyaway script to call: `ALTER FUNCTION x RENAME TO y;`

And also, there is a REST assured test that checks to see if it returns numeric, so that will have to change, as well.
