### ISSUE TITLE
zip ingest not happening

### ISSUE THREAD

**Issue by virgilejarrige** [IQSS/dataverse#7572]
Hello,

Running two Dataverse 5.3 instances here with (almost) the same parameters.

On server A, everything is working.

On server B, there are 2 issues, first one is in previous message.

When I upload a zip file it just stays as it is, the ingest process is not triggered. No error message, no warning, nothing, nowhere.

An idea where I could dig?

and take care ! :-)

Virgile

**Comment by qqmyers** [comment]
The one things I can think of: using direct upload with S3 stores disables unzipping. (Partly due to added work needed to support it and partly on principle: since sending the zip file to S3 to then bring it to dataverse and unzip, and then send the files back to S3 is less efficient than just uploading the zip to Dataverse in the first place.)

**Comment by virgilejarrige** [comment]
Thanks for the quick answer!

hmm then it's "server A" that is not working as intended... because it also has "redirect upload = True" parameter ^^
