### ISSUE TITLE
updating 5.2 to 5.3 problems with EJB timer app

### ISSUE THREAD

**Issue by jmjamison** [IQSS/dataverse#7610]
When I was updating test.dataverse.ucla.edu last December I ran into some issues with the EJB timer:
: EJB Timer Service is not available. 
An error has occurred Error occurred during deployment: Exception while loading the app : EJB Timer Service is not available. Please see server.log for more details.

```
PER01003: Deployment encountered SQL Exceptions:
```

The directions have been update regarding replacing this section:
with (that I copied from the P5 version of domain.xml:

```xml
<jdbc-connection-pool datasource-classname="org.h2.jdbcx.JdbcDataSource" name="__TimerPool" res-type="javax.sql.XADataSource">
  <property name="URL" value="jdbc:h2:${com.sun.aas.instanceRoot}/lib/databases/ejbtimer;AUTO_SERVER=TRUE"></property>
</jdbc-connection-pool>
```

That part is in the directions now.  I tried to upgrade dataverse.ucla.edu (production system) a couple of days ago and again got the errors:
with (that I copied from the P5 version of domain.xml:

```xml
<jdbc-connection-pool datasource-classname="org.h2.jdbcx.JdbcDataSource" name="__TimerPool" res-type="javax.sql.XADataSource">
  <property name="URL" value="jdbc:h2:${com.sun.aas.instanceRoot}/lib/databases/ejbtimer;AUTO_SERVER=TRUE"></property>
</jdbc-connection-pool>
```

Going back through my notes from the test system upgrade it looks like it is (also) necessary to delete or "hide" the service time app:   ejb-timer-service-app

After this I was able to complete deplyment.

**Comment by poikilotherm** [comment]
Hi @jmjamison I edited your text a bit to make the XML visible as code blocks (they were hidden for me because the browser interpreted them as HTML)

**Comment by poikilotherm** [comment]
Hi @jmjamison,

I'm really curious what makes the difference in newly setup domains of Payara 5 and yours, so we can learn what parts are missing in the release / upgrade notes.

Would you be able to share your domain files (not the Dataverse project code, but stuff like the `domain.xml` and others at `/domain1`), masking any secrets so I can do a diff and figure out why this is happening?

Also: on what Payara version are you currently?

**Comment by jmjamison** [comment]
Payara 5.2020.6

**Comment by poikilotherm** [comment]
Sorry for the delay @jmjamison, the edit didn't trigger a notification. Thanks for sending your `domain.xml`.

I compared with a vanilla `domain.xml` from 5.2020.6 and found some differences. However, regarding the timers I found the following... (Left is vanilla, right is your config)

![grafik](https://user-images.githubusercontent.com/5468333/110487664-16525b80-80ee-11eb-8c44-bb78efd2079f.png)

- You might have issues because of (1), but I'm not so sure about that. The 5.0 release notes only advised to replace the connection pool definition.
- Replacing (2) might be a good idea, too, als Derby is dead. (This hasn't been part of any release notes)
- When you are in there, please delete what I marked with (Del). This hasn't been part of the 5.3 release notes, those do no harm, but while in there... Well... :smile: 

![grafik](https://user-images.githubusercontent.com/5468333/110488671-f707fe00-80ee-11eb-98fb-3a3408b2acae.png)

In the vanilla config, there is no default store set for the EJB timers. The 5.3 release notes advice us to these:
```
<payara install path>/bin/asadmin set configs.config.server-config.ejb-container.ejb-timer-service.timer-datasource=jdbc/__TimerPool
```
This is also not present in your config - was this the change you mentioned last in your initial comment?
It might be a good idea to readd the session store parameter, though...

**Comment by jmjamison** [comment]
I haven't changed anything since you saw the config file.  I'll put in your suggestions.   Thank you,  Jamie

**Comment by pdurbin** [comment]
@jmjamison it looks like you're on the latest now! 5.11.1! Shall we close this issue? 😄
