### ISSUE TITLE
S3 - allow ingest of "small" zip files

### ISSUE THREAD

**Issue by virgilejarrige** [IQSS/dataverse#7643]
Hello,

Would it be possible to implement the same process  of "tabular files ingest" to compressed (zip) files when using s3?

That would imply we'd be able to define the max size of a zip file that can be ingested.

example : curl -X PUT -d 2000000000 http://localhost:8080/api/admin/settings/:ZipIngestSizeLimit

and the best would be to be able to define this per storage id, as a jvm option 

example : -Ddataverse.files.<id>.ZipIngestSizeLimit=<SizeInBytes>

Take care,

Virgile

**Comment by qqmyers** [comment]
Some general comments:

- This is technically possible - the direct upload code just bypasses the unzipping stage in the upload. However, without some redesign, it would mean that the file is pulled from S3 to the Dataverse machine, unzipping is done to temporary files, and all the files are pushed back to S3 - more work than if you just turned off direct upload for S3 and uploaded the zip file to the Dataverse instance to start, and would require temporary local file space for the zip and unzipped files (for all uploads if there's more than one zip file being uploaded at a time).
- Turning off direct upload (per Dataverse collection or for a given dataset via the API) would be a workaround today. 
- Another option would be to use DVUploader to upload an unzipped copy of the files - DVUploader can load files from a directory tree and keep their paths.

**Comment by djbrooke** [comment]
Hey @virgilejarrige - in the Harvard Dataverse Repository, when we have a dataset that has some large files that require a direct upload, and other files that do not, we've done what @qqmyers is suggesting. We've uploaded the large files via direct upload, switched the store at the dataset/collection level, and then uploaded the rest of the files in order to take advantage of the unzipping/ingesting features.

**Comment by virgilejarrige** [comment]
Thank you both for your replies.

The DVUploader seems to be the best option, but it cannot be used for v. 5.x+ when "direct upload" is activated (if I understood well https://github.com/GlobalDataverseCommunityConsortium/dataverse-uploader/releases/ )

We'll have to do the "switch store" trick I guess! :-)

Take care,

Virgile

**Comment by djbrooke** [comment]
Sounds good @virgilejarrige - I'll close this one for now.

**Comment by qqmyers** [comment]
@virgilejarrige - DVUploader 1.1.0 does direct uploads for v5.x. Since direct uploading changed (with multipart uploads now supported), 1.1.0 can't do direct uploads to pre5.x Dataverse instances. Normal uploads didn't change, so 1.1.0 can also be used for normal uploads on older versions. Here's a table:

  | Direct S3 Uploads | Normal uploads
-- | -- | --
Dataverse v5.x | 1.1.0 | 1.1.0 or 1.0.9
Dataverse 4.x | 1.0.9 | 1.1.0 or 1.0.9
