### ISSUE TITLE
Dataset Success Messages: Some issues discovered in first update for later consideration

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#7746]
1. Ingest complete causes please publish message to go away, should remain. 
2. Should Metadata be plural, replace has with have? 
4. "Metadata has changed" message has 3 wordings for publish (2) and submit for review (1). Essentially a brief one "publish it" and a longer one for publish and review with ending text, "so others can see these changes"
5. There are 3 different messages for three different file update conditions: "Files have been updated", "Selected files have been updated", "The file has been updated". The singular version, "the file has been updated", never appears. Only the first two messages appear ("Files have been updated" when uploading files and "selected files have been updated" when selected/edited or deleted).

**Comment by kcondon** [comment]
<img width="1164" alt="Screen Shot 2021-03-31 at 11 00 22 AM" src="https://user-images.githubusercontent.com/4983816/113177680-ca419500-921b-11eb-9192-c57dbb8e4b35.png">
<img width="1159" alt="Screen Shot 2021-03-31 at 11 00 48 AM" src="https://user-images.githubusercontent.com/4983816/113177683-cada2b80-921b-11eb-8a8f-3a32e4b77e62.png">
<img width="1141" alt="Screen Shot 2021-03-31 at 11 01 10 AM" src="https://user-images.githubusercontent.com/4983816/113177684-cada2b80-921b-11eb-8fcc-5570ab6228e8.png">
<img width="1147" alt="Screen Shot 2021-03-31 at 11 01 40 AM" src="https://user-images.githubusercontent.com/4983816/113177687-cada2b80-921b-11eb-8152-466ac7a6c0e2.png">
<img width="1141" alt="Screen Shot 2021-03-31 at 11 03 24 AM" src="https://user-images.githubusercontent.com/4983816/113177688-cb72c200-921b-11eb-8225-13607749f454.png">
<img width="1144" alt="Screen Shot 2021-03-31 at 11 03 51 AM" src="https://user-images.githubusercontent.com/4983816/113177690-cb72c200-921b-11eb-810e-d6b36f7c763f.png">
<img width="1139" alt="Screen Shot 2021-03-31 at 11 04 43 AM" src="https://user-images.githubusercontent.com/4983816/113177691-cb72c200-921b-11eb-8a58-951266702b1b.png">
<img width="1142" alt="Screen Shot 2021-03-31 at 11 16 42 AM" src="https://user-images.githubusercontent.com/4983816/113177692-cc0b5880-921b-11eb-925a-ead4a185d01e.png">
<img width="911" alt="Screen Shot 2021-03-31 at 11 31 11 AM" src="https://user-images.githubusercontent.com/4983816/113177693-cc0b5880-921b-11eb-9963-c61e86e48fd1.png">
<img width="876" alt="Screen Shot 2021-03-31 at 11 32 01 AM" src="https://user-images.githubusercontent.com/4983816/113177695-cc0b5880-921b-11eb-82d3-3bdc81c0a321.png">

**Comment by jggautier** [comment]
> 4. There are 3 different messages for three different file update conditions: "Files have been updated", "Selected files have been updated", "The file has been updated". The singular version, "the file has been updated", never appears. Only the first two messages appear ("Files have been updated" when uploading files and "selected files have been updated" when selected/edited or deleted).

This missing third message - "This file has been updated. If it’s ready for sharing, please publish it so that others can see these changes." - was listed in [a Google Doc](https://docs.google.com/document/d/1rJOirg1uvdLnw-dlTKBhw1q_OFgj1eaEAS0j3ul0944) used to propose the messaging changes. The message was meant to appear on the file page, after users saved changes on that page. But it was decided not to update the success messaging on that page. The reasoning is in a closed comment @djbrooke made in that Google Doc, which I'm pasting here:

> I'd like to revisit once we can prioritize the necessary design work around encouraging people to publish, and not introduce a change right now. There's some discussion in https://github.com/IQSS/dataverse/issues/4153 about this, and we could do the bandaid you describe there, telling people to go to the dataset page, but it would require some additional logic changes (to differentiate between submit for review and publish)

**Comment by mreekie** [comment]
This issue was created after improvements to success messages. When Kevin was testing he found additional issues that are itemized here.  These were deferred temporarily so as to stay focused on the initial UX issue.   It's important to get this low hanging fruit completed as it relates to the previous issue that has been addressed.

**Comment by mreekie** [comment]
prio:
 - small
 - straightforward'

**Comment by sekmiller** [comment]
"Metadata has changed" message has 3 wordings for publish (2) and submit for review (1). Essentially a brief one "publish it" and a longer one for publish and review with ending text, "so others can see these changes"

The difference in the "Metadata has changed" message is that the one with the ending text "so others can see the changes" is added to previously published datasets. Datasets that have never been published don't have that ending text. I guess we could say something like "so that others can see it.(discover it?) (something else to indicate that publishing makes it available to the public?)"

**Comment by TaniaSchlatter** [comment]
Per changes in https://github.com/IQSS/dataverse/issues/4153 Publish dataset after editing a file, if a dataset or file has been edited, there will be a separate "Warning" message that appears stacked under the "Success" message on dataset and file to prompt users to publish or submit for review. That change effects this issue:

**All "Success" messages that appear on the dataset and file pages only state that changes have been made successfully.**

As part of this, wording of Success messages can be simplified (slight expansion of scope):
Examples: "Success – This dataset has been created.", "Success – Tabular files have been ingested.", "Success – Terms of Use have been updated.", "Success – Terms of Access have been updated."

From the original issue:
1. Ingest complete causes please publish message to go away, should remain.
**expected result is "Success – Tabular files have been ingested."** 

2. Should Metadata be plural, replace has with have?
**Yes: "Success – Metadata have been updated."** 

3. "Metadata has changed" message has 3 wordings for publish (2) and submit for review (1). Essentially a brief one "publish it" and a longer one for publish and review with ending text, "so others can see these changes"
**One message for all: "Success – Metadata have been updated."**

4. There are 3 different messages for three different file update conditions: "Files have been updated", "Selected files have been updated", "The file has been updated". The singular version, "the file has been updated", never appears. Only the first two messages appear ("Files have been updated" when uploading files and "selected files have been updated" when selected/edited or deleted).
**One message for all: "Success – One or more files have been updated."**

**Comment by pdurbin** [comment]
PR #8687 didn't have the "closes" syntax for this issue. My read is that it should have.

**Comment by pdurbin** [comment]
Just checked with @sekmiller. Ok to close. Fixed by PR #8687.
