### ISSUE TITLE
Thumbnails aren't created during s3/direct upload

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#7749]
During an upload with s3 (possibly only with direct upload - haven't confirmed), thumbnails aren't shown in the upload UI and a message like `Failed to read in an image from /tmp/files/temp/s3://dataverse-bucket:1788e049621-f3e29d96058b: Can't read input file!` shows in the log.
This appears to be due to [EditDatafilePage.isTemporaryPreviewAvailable() assuming all files are local](https://github.com/IQSS/dataverse/blob/0dc7eb2063949c9e36377676bc93c751185c79de/src/main/java/edu/harvard/iq/dataverse/EditDatafilesPage.java#L2334).

Probably a low priority given that it only makes a difference during uploading and is non-fatal, but I wanted to put in an issue since this has appeared in other issues (see #7561 and #6829) where it confused things and wasn't resolved.

**Comment by donsizemore** [comment]
I can reproduce this consistently in 5.3 using S3 with `upload-redirect=true`

Uploading an image using the dataset page displays an image preview during upload / progress bar, but once the file is uploaded, server.log complains

```
[Payara 5.2020.6] [WARNING] [] [edu.harvard.iq.dataverse.dataaccess.ImageThumbConverter] 
[[Failed to read in an image from /tmp/files/temp/s3://dataverse-bucket:1788e58a429-9b718bf3aae4: Can't read input file!]]
```

There is no preview/thumbnail once the file is uploaded:

<img width="442" alt="Screen Shot 2021-04-01 at 12 52 13" src="https://user-images.githubusercontent.com/12831666/113327949-9896ff80-92e9-11eb-8915-1996f5a5399b.png">

but once the dataset changes are saved, the thumbnail reappears:

<img width="401" alt="Screen Shot 2021-04-01 at 12 52 28" src="https://user-images.githubusercontent.com/12831666/113327987-a8aedf00-92e9-11eb-8f39-a466e1f2a272.png">

Again, `upload-direct=true` and `-Ddataverse.files.file.directory` are set, and Payara has write access to the latter. As this is a testing server, SELinux is set to permissive.

The consensus seems to be that this is a minor-but-noisy bug... as long as it doesn't affect S3 (direct-)upload functionality.

**Comment by PaulBoon** [comment]
After an upgrade from 4.20 to 5.6 I inspected the logs and discovered plenty of those errors even in the old logs. 
Example: 

`[2021-07-13T13:50:04.738+0200] [glassfish 4.1] [WARNING] [] [edu.harvard.iq.dataverse.dataaccess.ImageThumbConverter] [tid: _ThreadID=52 _ThreadName=jk-connector(4)] [timeMillis: 1626177004738] [levelValue: 900] [[
  caught IOException trying to open an input stream for file://168a3ff1bb8-c464b2bc3a0cjava.io.IOException: Failed to open local file file:///data/assets/assetstore1/studies/10.34894/ICIXQA/168a3ff1bb8-c464b2bc3a0c]]
`

There is no S3 involved, we are just using the local filesystem. 
The `/data/assets/assetstore1/studies/10.34894/ICIXQA` does not exist, because the PID was migrated from Handle to DOI, files are in a directory with the Handle prefix in the path. 
Maybe the `ImageThumbConverter` is also not looking in the right place for the files when S3 is involved?
