### ISSUE TITLE
Dataverse 5.3 vs 4.9.4: metrics section shows different numbers.

### ISSUE THREAD

**Issue by ipcraiurosario** [IQSS/dataverse#7778]
Hi!

It's me again... I've found a new "issue" with my update process, in my Dataverse 4.9.4 my Metrics sections shows the following:
![image](https://user-images.githubusercontent.com/53486765/114076996-ecb35e00-986c-11eb-854d-a262c2889abb.png)
and the 5.3 Dataverse shows this:
![image](https://user-images.githubusercontent.com/53486765/114077038-f9d04d00-986c-11eb-8bc9-3137f1ba109f.png)

As I've said on other issues, my development server (dataverse 5.3) is using a copy of the 4.9.4 database.

Maybe I just need to run a command from the server console or something similar?

Hope you guys can help with this!

Thanks in advance

**Comment by qqmyers** [comment]
In 5.3, that number is pulled directly from a query that counts all the entries in the guestbookresponse table
`select count(o.id) from GuestbookResponse  o;`
so you should be able to verify if the 5.3 number is correct. 

I thought v4.9.4 did the same thing, so I'm surprised at the difference, but its possible there was a problem in that version. So, rather than debug that, if the number is correct in 5.3, you're OK at this point.

**Comment by ipcraiurosario** [comment]
@qqmyers when I run the sql sentence it shows the exact same number:
![image](https://user-images.githubusercontent.com/53486765/114196892-6bfd6c00-9917-11eb-9785-d24b0c91c7c9.png)

So the 5.3 number is the one that I should trust.

Again, thank you very much!
