### ISSUE TITLE
S3 Storage, Deleting a draft of a published dataset does not remove files added in that draft.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#7790]
Steps to reproduce:
1. create and publish a dataset with 1 file, eg. file1.txt
2. upload another file, file2.txt, which creates a new draft of the published dataset.
3. delete the draft of the dataset, notice file2.txt remains, happens on S3 and local storage too. (thx @qqmyers )

**Comment by qqmyers** [comment]
Looks like #5592 moved deleting files out of the DeleteDataFileCommand but didn't add the logic needed to delete files after a DatasetPage.deleteDatasetVersion() call. The logic is in DatasetPage.deleteDataset(). 
So 
a) this affects file as well as S3 stores, and 
b) it's been around a while which means abandoned files have probably been accumulating...

**Comment by djbrooke** [comment]
- As a separate issue, consider a regularly scheduled job that reviews the expected files vs. the files in S3. We should be proactive about this - add some ways for installations to periodically audit this. This will address one of the ways to generate these files, but other ways may exist.
- This has been around for ~2 years (since 4.12)
