### ISSUE TITLE
 Investigate and reduce the number of Errors, Exception, and SEVERE events from server.log

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#7805]
SEVERE events are ones whose level is SEVERE according to Payara. 
Errors and Exceptions may be WARNING or INFO level but nonetheless contains important info.

The search strings are "SEVERE" "Error" and "Exception"

**Comment by PaulBoon** [comment]
Yes, every time when looking into the server.log I have to take a deep breath ...
 see my issue: https://github.com/IQSS/dataverse/issues/5749

**Comment by eunices** [comment]
Hello, just to add onto this issue. 

Recently we also noticed EZIDException in `server.logs`. Also mentioned in https://groups.google.com/g/dataverse-community/c/hge7q5xsjh4/m/NMJB3K6YAgAJ. It isn't fatal according to @qqmyers. Could consider removing the severe log for [DOIEZIdServiceBean.java](https://github.com/IQSS/dataverse/blob/096e3c30900e6d50873a4b6c9896f6ad7808bd8c/src/main/java/edu/harvard/iq/dataverse/DOIEZIdServiceBean.java) especially since [EZID is no longer used](https://guides.dataverse.org/en/latest/installation/config.html?highlight=ezid).

```log
[SEVERE] [] [edu.harvard.iq.dvn.core.index.DOIEZIdServiceBean] [tid: _ThreadID=65 _ThreadName=RunLevelControllerThre
  Other Error on ezidService.login(USERNAME, PASSWORD) - not EZIDException ]] 
```

**Comment by pdurbin** [comment]
Let's open more targeted issues, please. Smaller chunks.
