### ISSUE TITLE
Investigate Payara Health Check

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#7811]
https://blog.payara.fish/the-health-check-service-in-depth-payara-server

**Comment by akio-sone** [comment]
Just FY related to `HEALTHCHECK` command in `c8.Dockerfile` in `dataverse/conf/docker-aio`; this line
 `HEALTHCHECK CMD curl --fail http://localhost:4848/monitoring/domain/server.json || exit 1`
does not work after a customized domain.xml no longer overwrites the factory default domain.xml.
Since this `HEALTHCHECK` command fails, a created container is now marked "unhealthy" although the payara server is running. It seems the API endpoint or URL for healthcheck is flexible; I came across a Dockerfile that uses the URL of the top page of the web application as the HEALTHCHECK api endpoint.

At first I was perplexed by the API endpoint `server.json` beause there is no endpoint named `server.json` according to the API document; later I realized `.json` is a format specifier for the response;
"[Monitoring Payara Server in Production](https://www.payara.fish/resource/monitoring-payara-server-in-production/)" says
```
Both the REST services can be accessed using the HTTP protocol by any REST client (including any browser). Results will be provided in JSON, XML or HTML format. The default format is HTML, but it can be changed easily by using the appropriate suffix. Compare the output of the following:

• http://localhost:4848/monitoring/domain
(HTML output with links to related resources)

• http://localhost:4848/monitoring/domain.json
(JSON output)

• http://localhost:4848/monitoring/domain.xml
(XML output)
```
And when it was working, we got the following response:
```
# explicitly specify json
curl  -X GET -H "Accept: application/json"  http://localhost:4848/monitoring/domain/server.json

{"message":"","command":"Monitoring Data","exit_code":"SUCCESS","extraProperties":{"entity":{"starttime":"1618763293290","state":"1","uptime":"18564977"},"childResources":{"jvm":"http://localhost:4848/monitoring/domain/server/jvm"}}}

# without .json 
$ curl  -X GET -H "Accept: application/json"  http://localhost:4848/monitoring/domain/server

{"message":"","command":"Monitoring Data","exit_code":"SUCCESS","extraProperties":{"entity":{"starttime":"1618763293290","state":"1","uptime":"19360790"},"childResources":{"jvm":"http://localhost:4848/monitoring/domain/server/jvm"}}}

```
see the following manual page: 
[Formats for Resource Representation of Monitoring Objects](https://glassfish.org/docs/5.1.0/administration-guide/general-administration.html#GSADG00712) 
[Supported Content Types in Requests to REST Resources](https://glassfish.org/docs/5.1.0/administration-guide/general-administration.html#GSADG00714)
