### ISSUE TITLE
Include CodeMeta schema out of the box

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#7844]
Resulting from the [Software, Workflows & Containers Working Group](https://swc.wgs.gdcc.io) discussions, we want to implement different changes within the Dataverse software.

A first low hanging fruit is the addition of the [CodeMeta metadata schema](https://codemeta.github.io) for scientific software. Providing it out-of-the-box for any (new) Dataverse installation and adding to existing instances with upstream support greatly enhances Dataverse. This issue has none to low impact on software development resources.

A solution involves at least:
- Adding the schema as a TSV filebase custom metadata block (along with the existing ones)
- Adding docs to the guide about its existance, linking to the project etc
- Adding a release notes doc

This might involve in this first step or as aftermath little code contributions to enable for #6289.

**Comment by mreekie** [comment]
Found this in the global backlog today in the sprints tab.
Not sure how it got here.
Looks to be associated with PR #7877 which was part of the Dec 15, 2022 sprint.
Adding it to that sprint.

**Comment by pdurbin** [comment]
Right, not just associated but closes. So merging the PR closed the issue.

**Comment by mreekie** [comment]
> Right, not just associated but closes. So merging the PR closed the issue.

Got it. Get it. :)  This represents one of those corner cases from my point of view of tracking our progress.  The dev team got the PR, sized it and worked it. However, there was also an issue associated with it (This issue).  It confused me when it popped up after the fact on my radar.  

Thinking out loud, but I'm thinking that since we didn't take this issue into account in the planning, let's not insert it later in the tracking process  by adding the Sprint label. The two will still remain associated by the issue/PR relationship.

This raises another thing too.  If someone other than me sets that label arbitrarily it will make the tracking harder. I'm not sure at this point how to make everyone aware not to do that.
