### ISSUE TITLE
File Tags at collection level

### ISSUE THREAD

**Issue by DS-INRA** [IQSS/dataverse#7857]
Users have suggested us that some custom files tag could be set at the dataverse level, like  the metadata template, to avoid typos and typing them repeatedly across the dataverse.
Here is a quick and dirty potential mockup :
![filetag_edit_dataverse](https://user-images.githubusercontent.com/46443753/117481040-b4359b80-af62-11eb-8bd5-6f80393247d5.png)
___
![filetag_menu](https://user-images.githubusercontent.com/46443753/117481055-ba2b7c80-af62-11eb-9e59-97edf62f9a1e.png)
___

**Comment by philippconzett** [comment]
This feature was also requested by a research group for which we currently are implementing a sub-collection. This would allow us to support the use of consistent file tags across dataset within a (sub-)dataverse.

**Comment by pdurbin** [comment]
@DS-INRA @philippconzett there's a newish (5.10.1) global setting (rather than collection level) that might help: https://guides.dataverse.org/en/5.11.1/installation/config.html#filecategories

---

## :FileCategories

Overrides the default list of file categories that is used in the UI when adding tags to files. The default list is Documentation, Data, and Code.

This setting is a comma-separated list of the new tags.

To override the default list with Docs, Data, Code, and Workflow:

curl -X PUT -d 'Docs,Data,Code,Workflow' http://localhost:8080/api/admin/settings/:FileCategories

To remove the override and go back to the default list:

curl -X PUT -d '' http://localhost:8080/api/admin/settings/:FileCategories

---

What do you think? Helpful? Good enough for now to close this issue? 😄 Or do you really need it at the collection level?

**Comment by philippconzett** [comment]
Thanks, Phil! I guess this should work for us at installation level. To get this applied consistently at collection level, the collection managers could simply need to provide some clear documentation. So, from my side, it's fine to close the issue. Thanks!

**Comment by pdurbin** [comment]
@philippconzett great, thanks.

@DS-INRA what do you think? Do you want to try the system level option? Do you want to keep this issue open for collection level? Or is it ok to close it?

**Comment by DS-INRA** [comment]
Thanks for pointing out the new feature, I think it is still not entirely sufficient as collection managers should be able to configure it themselves, but would still allow to address the user's need.

**Comment by pdurbin** [comment]
@DS-INRA I'm glad to hear that the new system-wide feature is at least a step in the right direction! 😄

**Comment by sbarbosadataverse** [comment]
Closed per last comments in 2022
