### ISSUE TITLE
Add Support for International Characters Across All Display Functionality

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#786]
Need to make non-latin characters display correctly across all dataverse functionality.

1. metadata entered in the UI by users (copy+paste, such as from Microsoft Word documents #787)
2. files names display correctly
3. ingest: variables within files are indexed correctly
4. batch import 
5. harvesting

We will need to start prioritizing language support for languages that use non-latin characters (non-latin UTF8, [CJK language encoding](http://en.wikipedia.org/wiki/Chinese_character_encoding), etc).

**Comment by landreev** [comment]
This was a parent ticket for a bunch of issues related to accents/funny characters, that have all been moved into QA in beta 12. 
The only part of the dataverse functionality that hasn't been specifically tested for this is the batch metadata import, that Ellen has been working on. 
Since this is something currently being tested with production DDIs, please check some study that has accents/non-latin characters and see if they get imported correctly. If there are problems, I can try and fix it (and/or work with Ellen on fixing it). 
But please keep in mind that some production DDIs may still have *improperly exported/encoded* funny characters. (this would be something to specifically address during the migration). 
So if you see an imported production study with a broken accent - please double-check if it got messed up on import, or if it was so messed up in the DDI...

**Comment by posixeleni** [comment]
We have migrated 3.6 data and dataverses in http://dvn-vm5.hmdc.harvard.edu/

Migrated Dataverse description shows accents correctly:
![image](https://cloud.githubusercontent.com/assets/5013837/6753938/dfd6136e-ceef-11e4-9c1f-b498df067a19.png)

However, I still need to test for migrated datasets:
@ekraffmiller would it be possible to migrate specific datasets from 3.6 Dataverse into http://dvn-vm5.hmdc.harvard.edu/ ? 
- This particular study would be useful to test accents got imported correctly: http://hdl.handle.net/1902.1/19664
- This particular study would be useful to test non-latin characters get imported correctly: http://hdl.handle.net/10527/10483

**Comment by posixeleni** [comment]
Just spoke with Leonid and harvested studies are still in the process of being migrated over so I cannot test the non-latin characters found in the study mentioned above http://thedata.harvard.edu/dvn/faces/study/StudyPage.xhtml?globalId=hdl:10527/10466

**Comment by posixeleni** [comment]
Havent been able to find a local study that has non-latin chars to test so waiting for this migration to complete.

**Comment by posixeleni** [comment]
As Leonid pointed out accented characters that were migrated from 3.6 show up fine:
![image](https://cloud.githubusercontent.com/assets/5013837/6984277/25ffb664-d9f5-11e4-97b7-f6e2b38208c5.png)

I also recreated a study that had non-latin characters to build to see if the characters would display properly and the Thai is showing up great. 

Will close this ticket.

However, searching for a known dataset with Thai characters is another issue altogether though:  
![image](https://cloud.githubusercontent.com/assets/5013837/6984415/9913349a-d9f6-11e4-8213-83ee3fd0a4bb.png), which we had resolved in #1274 for Japanese characters so I will create a new ticket for this issue.
