### ISSUE TITLE
updateSchemaMDB.sh script not working

### ISSUE THREAD

**Issue by Kris-LIBIS** [IQSS/dataverse#7871]
In our installation, the updateSchemaMDB.sh script does not perform as expected. We always get the message "Dataverse responded with empty file. When running on K8s: did you bootstrap yet?".

The problem is with the test ```[[ "`wc -l ${TMPFILE}`" < "3" ]]``` which always returns true, even when the result is much more than 3 lines. If changed to ```[[ `wc -l < ${TMPFILE}` -lt 3 ]]```, it correctly returns true or false depending on whether the file size is less than 3 lines.

I'll create a PR with the fix, but I'm holding off for now because of PR https://github.com/IQSS/dataverse/pull/7865#issuecomment-840436115.

**Comment by pdurbin** [comment]
I had occasion to run updateSchemaMDB.sh while reviewing a pull request with a custom metadata block but it didn't "just work". Even though the schema XML was being written correctly to `${TMPFILE}`, as reported above, I always got the error `Dataverse responded with empty file. When running on K8s: did you bootstrap yet?` This is on my Mac, where I'm running Bash 3.2. I believe it works fine on Linux.

I tested the fix by @Kris-LIBIS above (`[[ `wc -l < ${TMPFILE}` -lt 3 ]]`) and it seems to work fine of both Mac and Linux.

I see @poikilotherm already commented on the fix at https://github.com/IQSS/dataverse/pull/7904/files#r640606957 ("We should start using $() here and let shellcheck bark at other things it finds") which sounds fine.

That pull request has various fixes but at the moment anyway, I'm mostly focused on the fix above so that the script runs on Mac, which we use for dev.

@Kris-LIBIS any thoughts on this? Any interest in making a small pull request just to fix the problem above? The scope of this issue seems to be exactly the problem I had. I'm thinking that #7903 can represent the larger problem of the script no longer being fully automated.
