### ISSUE TITLE
File Permissions: Restricting File Access

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#792]
Right now, when you publish a dataset, access to files is unrestricted.

Notes: https://docs.google.com/document/d/1Lmp70OrfLkX5UuXWVkz2iqh3H749n0pLo6tq69XtwWw/edit?usp=sharing

**Comment by mheppler** [comment]
Notes from UI meeting with Merce, Gustavo, Liz, Mike:
- Restrict files workflow is part of Upload + Edit Files page, includes dynamic Restrict/Unrestrict Selected Files based on the state of the selected files, as well as "Select All..." dropdown button for selecting: all files, restricted files, or unrestricted files.
- Restricted icons are added to the thumbnail preview.
- File Access button that opens popup displaying Users + Groups with access to file, and link to edit those access permissions in the File Permissions page.
- Confirmation popup on save, if necessary, that allows editing of Request Access and Terms of Access from the License + Terms settings.

![filepermissions_page_1](https://cloud.githubusercontent.com/assets/687227/5764504/7df3918c-9cc0-11e4-9581-71acc52f81a1.png)

**Comment by mheppler** [comment]
Related to #1345 and .

**Comment by scolapasta** [comment]
Added the buttons. Still needs the "Select all, select restricted, etc. functionality).

**Comment by scolapasta** [comment]
For checkbox 1, this was the logic before we decided to allow restrict and unrestrict as separate buttons. Since we show both, we don't need separate Select All Restricted / Select All Unrestricted, as you can just select use select all.

For example, in the songle button mode, you would select all unrestricted so that the button would say Restrict, then click restrict, end result all files restricted.

In current way, you can just say select all, and restrict, and this will leave current restricted alone and restrict unrestricted, end result all files restricted.

That said, select all is not there yet. Primefaces provides a working select all for this (since these are using the primefaces datatable selection model. But it is on the header row. (you can see this working on the files permissions page gtant access popup). @mheppler can you add the header and then use css to make it display the way you would want? This would be much easier than trying to wire our own select all button (without going to the back end).

@mheppler checkbox 2 is also for you.

I will work on 4, and we should discuss 3 at some point.

**Comment by scolapasta** [comment]
Point 4 is also done, but needs UI help. Passing to @mheppler for now, for UI for 1,2,4

**Comment by mheppler** [comment]
The UI should be good, save for some minor spacing issues with the buttons, that are being addressed in another general UI ticket.

Dataverse
- No restricted icons are displayed on the file cards.

**Comment by kcondon** [comment]
OK, works, closing. Saw one issue in UI for FF and will open a new ticket.
