### ISSUE TITLE
Globus - database setting to skip checksum validation based on dataset size/number of files

### ISSUE THREAD

**Issue by JayanthyChengan** [IQSS/dataverse#8043]
Hi:
At Scholars Portal, while we were integrating Globus with Dataverse for large file transfers, noticed that it takes longer time to complete checksum validation while publishing the dataset.

So, would like to have an option to skip checksum validation for the dataset on publish
if the dataset size is greater than threshold limit (configure by database setting)  or
if the number of datafiles is greater than a specified limit (configure by database setting). 

 Please let me know, whether I can proceed submitting the PR.

Thanks

**Comment by qqmyers** [comment]
There is a :FileValidationOnPublishEnabled true/false setting already. Is that enough?

**Comment by JayanthyChengan** [comment]
@qqmyers : Thanks for pointing it.

If I set :FileValidationOnPublishEnabled to false, it will skip validating all the datafiles on publish
https://guides.dataverse.org/en/latest/installation/config.html?highlight=filevalidationonpublishenabled

But I am proposing to have more granular settings, so that only the dataset larger than specified size will be skipped from checksum validation.

Let me know your thoughts.  Thanks

**Comment by qqmyers** [comment]
I guess I'm asking more about policy - is the intent to never validate large files/many small files in large datasets? Or are you planning to do that asynchronously? If the latter, would it be better to have, for example, a size setting at which things go asynchronous (or always do this asynchronously like indexing)? Or better to just shut off validation at publish (presumably, especially with object storage, problems are very rare) and rely on periodic asynchronous checks via the API, etc.

That said, turning the true/false flag into a file size limit is consistent with other actions like ingest and zipping where granularity has been added. Making the choice also depend on number of files adds some complexity (would a total dataset size limit make more sense?), but it is understandable that something would be needed to put an overall limit on the processing time that could occur.

Lastly, I'm not sure what the decision process is on something like this, but I know it doesn't become my decision just because I responded first. Overall, I don't think this is very controversial given the community interest in it, so I'd think you could go ahead  and just watch in case someone responds with some objection.

**Comment by pdurbin** [comment]
Most people don't ask. They just put up a pull request. 😄 

I'm also thinking that you'll probably want checksums for those files eventually, whether by some async process or whatever.

There's a "Physical Files Validation in a Dataset" API that will tell you if the checksums in the database aren't right: https://guides.dataverse.org/en/5.5/api/native-api.html#physical-files-validation-in-a-dataset

You can then use the "Datafile Integrity" API to add a checksum for any file that doesn't have one: https://guides.dataverse.org/en/5.5/api/native-api.html#id20

So I guess I'm thinking maybe the "skip checksum if over limit" feature could be added and then the checksums could be added later with the API endpoints above. Perhaps we could even remove the :FileValidationOnPublishEnabled setting and document how to achieve the same thing with a new setting (-1 or something).

Just some thoughts. I'll drop a link to this issue in #dv-tech in case anyone else wants to weigh in.

**Comment by landreev** [comment]
> ... asking more about policy - is the intent to never validate large files/many small files in large datasets? Or are you planning to do that asynchronously?

Just want to point out that this validation step is always asynchronous already. (performed in that second, "finalize publishing" command).

**Comment by landreev** [comment]
I personally have no objections to making it possible to disable that validation step based on size as well. 
(When documenting that option, maybe some words could be added on how "if you choose to disable this validation during publishing, we strongly recommend that you perform it later, using the integrity API" - something like that?)
