### ISSUE TITLE
dcterms:rights needs to be mapped "restrictions" or some other Dataverse field for SWORD

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#805]
At the "Crosswalk DC-Dataverse for Data Deposit API (Dataverse 4.0)" doc at https://docs.google.com/spreadsheet/ccc?key=0AjeLxEN77UZodFRhcVUxMDV5NFFUZWN2M3NpdlZoMGc&usp=sharing dcterms:rights does not currently map to a Dataverse field. It says "TDB: restrictions".

According to https://github.com/IQSS/dvn/blob/develop/doc/sphinx/source/dataverse-api-main.rst#dublin-core-dc-qualified-mapping---ddi---dataverse-network-db-element-crosswalk in DVN 3.6 "dcterms:rights" went to DDI 2.4.2.3 restrctn (restrictions) with a note saying, "any restrictions on the access or use of the dataset."

I know we are working on this in #22 and #342 but I'm opening this ticket specifically for Data Deposit API backward compatibility.

@posixeleni I'm going to assign this ticket to you until the decision about which field to use on the Dataverse side has been made. Then, please give it to me and I'll commit the appropriate `INSERT INTO foreignmetadatafieldmapping` line into the SQL reference data script.

**Comment by scolapasta** [comment]
@posixeleni access fields have been added, so this should be able to be mapped. Can you figure out which one then pass to phil?

**Comment by posixeleni** [comment]
@sekmiller I don't know how the field names are stored in the DB (since they are not in my tsv) but @pdurbin they should map from DC Terms as follows:

dcterms:rights --> This would map to the general Terms of Use field but need to get this information from the db
dcterms:license --> If the license = "CC0" then this would map to the License field but need to get this. Otherwise the license would be set to custom and the text in the license field should be mapped to "Terms of Use" like we do for rights.

I am tracking this in this doc: https://docs.google.com/spreadsheets/d/1r5jDqw9qMeeHaZ2ga8PSXTtom58gsmd5If3Skr9ercw/edit?usp=sharing

**Comment by sekmiller** [comment]
The fields are on the datasetVersion table.
The general terms of use field is called termsofuse.
The license field is called license.



On Jan 9, 2015, at 12:24 PM, Eleni Castro <notifications@github.com<mailto:notifications@github.com>> wrote:


@sekmiller<https://github.com/sekmiller> I don't know how the field names are stored in the DB (since they are not in my tsv) but @pdurbin<https://github.com/pdurbin> they should map from DC Terms as follows:

dcterms:rights --> This would map to the general Terms of Use field but need to get this information from the db
dcterms:license --> If the license = "CC0" then this would map to the License field but need to get this. Otherwise the license would be set to custom and the text in the license field should be mapped to "Terms of Use" like we do for rights.

I am tracking this in this doc: https://docs.google.com/spreadsheets/d/1r5jDqw9qMeeHaZ2ga8PSXTtom58gsmd5If3Skr9ercw/edit?usp=sharing

**Comment by pdurbin** [comment]
> (if CC0 is not selected) the license would be set to custom

As I've discussed with @sekmiller we can't currently save "custom" to the database. The choices for license are "CC0" and "None". **Should we change "None" to "Custom"?** (This is in code on an enum.) Or should it be "See Terms of Use"? The the GUI the Terms of Use form only appears when click a radio button other than CC0.

**If you don't select CC0, should Terms of Use be required?** Currently, this is not enforced in the GUI. Should SWORD enforce this? That is, if you don't select CC0 from SWORD, should you be required to also provide Terms of Use?

**What if from SWORD you try to specify Terms of Use but you don't specify a license? Should we automatically persist the non-CC0 value to the database?**

I'm passing this to @scolapasta for comment.

**Comment by scolapasta** [comment]
We'll need to discuss with @posixeleni when she gets back

**Comment by eaquigley** [comment]
@sekmiller Can you change this from NONE to CUSTOM in the database? @pdurbin and I discussed this and it makes more sense for it to be CUSTOM.

@posixeleni @mcrosas: Currently when a user selects No, do not apply CC-0 they are not required to add in Terms of Use. Do we want that to be a required field that needs to be filled out? It makes sense to me to make a user to provide some information as to why the dataset is not CC-0 and how a downloader can use it.

**Comment by eaquigley** [comment]
@sekmiller no need to change from NONE to CUSTOM in the database. Also, terms of use will not be a required field. Passing this to QA to test.

**Comment by pdurbin** [comment]
This is not ready for QA so I'm taking it back. I think I have enough answers after discussion with @eaquigley this morning about my questions: https://github.com/IQSS/dataverse/issues/805#issuecomment-70290922

**Comment by pdurbin** [comment]
The rules from @eaquigley are listed below and I attempted to implement them in 6babd4a45586f408e72bbf54db3083372553958c

- If you don't provide `<dcterms:license>` the license should be set to "CC0" on dataset creation.
- If you don't provide `<dcterms:license>` the license on dataset modification, the license should not change.
- To provide `<dcterms:rights>` you much either omit `<dcterms:license>` (for backwards compatibility since `<dcterms:license>` was not a required field for SWORD in DVN 3.6) or set `<dcterms:license>` to "NONE".
- It is invalid to provide "CC0" under `<dcterms:license>` in combination with any value under `<dcterms:rights>`.
- It is invalid to attempt to change the license to "CC0" if Terms of Use (`<dcterms:rights>`) is already on file.
- Both `<dcterms:rights>` and `<dcterms:license>` can only be specified once. Multiples are not allowed. Neither are blank values.

Passing to QA. Please note that I also opened #1385 to think about making sure the default license is consistently applied in the GUI, SWORD, and the native API. Perhaps we need another ticket to have the rules be enforced in the "native" API? Perhaps there should be centralized validation of these business rules?

**Comment by jwhitney** [comment]
Related to the rule in the list: older versions of the OJS Dataverse plugin may provide a blank value in `<dcterms:rights>` if journal managers haven't provided a copyright notice in journal set-up.

**Comment by pdurbin** [comment]
> older versions of the OJS Dataverse plugin will send a blank value in <dcterms:rights> if journal managers haven't provided a copyright notice in journal set-up

Hmm. Ok, @jwhitney I **really** don't want to introduce additional backward-incompatible changes so I just modified the code to allow blank values and this is what I wrote in the [API Guide](http://guides.dataverse.org/en/latest/api/sword.html):

> “License” can now be set with dcterms:license and the possible values are “CC0” and “NONE”. “License” interacts with “Terms of Use” (dcterms:rights) in that if you include dcterms:rights in the XML, the license will be set to “NONE”. If you don’t include dcterms:rights, the license will default to “CC0”. It is invalid to specify “CC0” as a license and also include dcterms:rights; an error will be returned. For backwards compatibility, dcterms:rights is allowed to be blank (i.e. `<dcterms:rights></dcterms:rights>`) but blank values will not be persisted to the database and the license will be set to “NONE”.

I also [changed the integration test](https://github.com/IQSS/dataverse-apitester/commit/72c00758534ae70d703420cdcc29b71baf55f8c5) to leave dcterms:rights blank and [the test still passes](https://build.hmdc.harvard.edu:8443/job/apitest.dataverse.org-apitester/6/) on https://apitest.dataverse.org so you're welcome to test there, @jwhitney .

**Comment by kcondon** [comment]
Tested all cases, works as described. Closing.
