### ISSUE TITLE
Cannot add TwoRavens as an external tool (Dataverse v5.5)

### ISSUE THREAD

**Issue by TKNKMR** [IQSS/dataverse#8063]
The following error : {"status":"ERROR","message":"contentType is required."} occurs when I run the curl command 
curl -X POST -H 'Content-type: application/json' --upload-file twoRavens.json http://localhost:8080/api/admin/externalTools
with the twoRavens.json downloaded from https://guides.dataverse.org/en/latest/installation/r-rapache-tworavens.html#e-enable-tworavens-in-a-dataverse-installation.
A solution is provided by Jim from the dataverse community (https://groups.google.com/g/dataverse-community/c/yA-g3wlFH48)

![jim_solution](https://user-images.githubusercontent.com/88823880/129163639-752a8be9-2013-42ed-81ad-98666efffabb.PNG)

**Comment by pdurbin** [comment]
@TKNKMR thanks for opening this issue.

The fix is simple enough but I'd like to repeat something I said in the thread mentioned above:

Patrick, if you're able to create an issue about twoRavens.json being out of date, I'd really appreciate it. This situation is exactly why we now have a policy that we'd like external tools to maintain their own documentation, keep their config files up to date, etc. We had a similar problem [with TwoRavens] when we added "scope" at #6203

Once upon a time #4429 represented the idea that we need to rethink how we document tools that were once part of the core code and guides. WorldMap/Geoconnect was once part of the guides (and code) but TwoRavens remains in the guides and should probably be removed.
