### ISSUE TITLE
Ingest: Uploading an excel file with only one row leaves it in a permanently ingest in progress state.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#809]
This was reported by a user via beta feedback form, see RT 182797.

The excel ingest fails when the file contains only one row of data. On save, it remains stuck with the ingest in progress spinner and makes the dataset uneditable.

**Comment by landreev** [comment]
The "remains stuck" part had been fixed a while ago. 
But I've also added a better error message. Now you should be getting the red triangle of failure; with the embedded text that says "one row only...". If you can think of a better wording for the message - do let me know. 

Also, since a file needed to reproduce this is going to be tiny by design - it'll likely be subject to the "no automatic page refresh" issue, that's being tracked separately. I.e., it's not *stuck* in the in progress state; you'll just need to reload the page.

**Comment by kcondon** [comment]
Yes, fails with red triangle and simply adding a variable row works. As for the tiny timing issue, this is tracked in another ticket relating to websocket and atmosphere. Closing
