### ISSUE TITLE
UI Layout: Make sure page layouts work in all screen resolutions, via bootstrap. 

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#811]
In most recent weekly review, presentation was made in lower res screen which revealed some page layout issues.

Bootstrap should be able to handle this ("responsive" appears on the homepage of http://getbootstrap.com ) but we need to actively focus on this.

This ticket is a place holder to do that.

**Comment by eaquigley** [comment]
Moving to In Design to start thinking about responsiveness and the long term plan for making the application more responsive. Will this be done little by little or need to be done all at once? As well as need to have a conversation about what screen resolutions we should support and what the app looks like on tablets for a mobile solution.

**Comment by mheppler** [comment]
One thing that we will need to discuss is if we want to provide users who visit the site on hand held devices a different layout/UI than those on desktops.

An example of this would be to hide the facets in the results listing section of the dataverse page. An example of how we can achieve this is used in this Bootstrap template from Bootply.

http://www.bootply.com/render/128936

Load the page in a normal sized browser window on your desktop, and you'll see the sidebar. Shrink the browser window smaller than 768px wide, and the UI changes, the sidebar disappears off the page, and you can toggle it back into view by clicking the blue button with the white arrow at the top of the page.

I have already implemented a prototype of this on the dataverse page (see screenshots). My question to the team is, do we want to develop a unique experience for some basic workflows in Dataverse, which would require a good deal of design and development, or do we want to just shrink the entire site down, so that it is viewable, but might not be all that usable, without zooming in, on hand held, mobile devices and tablets?

![screen shot 2015-09-03 at 2 02 55 pm](https://cloud.githubusercontent.com/assets/687227/9666510/8766d88e-5244-11e5-983f-40b65cc6c1cf.png)
![screen shot 2015-09-03 at 2 02 39 pm](https://cloud.githubusercontent.com/assets/687227/9666512/8aa134f4-5244-11e5-8e70-34d570780df4.png)

**Comment by kcondon** [comment]
@mheppler
What about using the new widgets, presenting basic lists, and simple pages that use the widgets?

**Comment by mheppler** [comment]
The expanded features of the widgets will also benefit from improvements we can make to the responsiveness of the site's layout. The widget as it is currently built uses the same results listing table code that the dataverse page does. If we improve the responsiveness of the dataverse page as a whole, we can add more of it's features, like the facets, to the widget.

**Comment by kcondon** [comment]
Just curious what an out of the box design for mobile would look like, not in anyway advocating for this because I hate special versions and know how much work it is for everybody, but what is cool about tablet or mobile apps over desktop? I don't know wondering if people could articulate it conceptually.

**Comment by eaquigley** [comment]
I went ahead and took a look at Google Analytics for 3.x and 4.x (please note 4.x had an issue with Google Analytics briefly so this data is not 100% accurate)

For 3.x:
-Between 4/1/2014-4/1/2015, 7.99% of sessions were mobile + tablet sessions (22,474 sessions)
-From reviewing the Users Flow for mobile + tablet sessions, it appears most actions are viewing dataverse and study pages as well as creating an account
-Screen resolutions: ipad (768x1024), iphone (320x568), iphone (320x480), iphone (375x667), not set (1366x768)

For 4.x:
-Between 4/15/2015-9/2/2015, 8.75% of sessions were mobile + tablet sessions (7,006 sessions)
-From reviewing the Users Flow for mobile + tablet sessions, it appears most actions are viewing dataverses, datasets, and creating an account.
-Screen resolutions: iPad (768x1024), iphone (320x568), iPhone (375x667), iphone (320x480), not set (360x640), iphone (414x736), not set (1366x768), Google nexus 5 (360x640)

Based off this data, I think we should first focus on searching/browsing and viewing dataverses, datasets, and file pages before being concerned with write actions. Although it is interesting to see the create and edit account pages showing up in the pages. Also, google analytics doesn't show how many mobile users downloaded files so that is an unknown for us.

We should focus on creating a cross channel experience. This is a good article that goes over that: http://www.nngroup.com/articles/cross-channel-consistency/

**Comment by kcondon** [comment]
Yeah, maybe with linked cloud storage using mobile for files isn't implausible. Still trying to think about the scenario: someone is on the way to a conference or on the way home from work and says, "Hey, I forgot to upload and publish my dataset. Why don't I use my phone?" On the other hand, people in the field might have such smaller devices and not ready access or good access to laptop?
Some of these devices are being integrated into specific POS type data gathering so that could be another angle, albeit maybe an automatic one?

**Comment by kcondon** [comment]
@eaquigley @mheppler 
Would it make sense to survey users about whether and how they might use Dataverse on low res devices: phone/ tablets?

**Comment by mheppler** [comment]
Yes, I think long term, we can do surveys, and mine usage analytics, to find what our users are doing, and want to do. Short term, I think we can also identify some easy improvements to add into 4.2 development -- like the facets toggling.

**Comment by eaquigley** [comment]
@kcondon @mheppler for this situation, a survey wouldn't be the correct research method for discovering whether we need a mobile app for Dataverse. Surveys can provide false results for questions like, "would you use a mobile app?" because in the moment of taking the survey and answering the questions, a user might go, "well yeah of course I would" but actually never would. The survey won't capture the actual pattern of behavior from the user. (more info about survey misuse here: http://www.uie.com/articles/on_surveys/) 

Since we allow users to tweet or share datasets and dataverses via Facebook  (and the Dataverse Twitter account does this as well), I believe it is very important to make sure Dataverse and dataset pages are responsive, easy to view, and don't look broken on mobile devices so when someone views them on their mobile device after clicking a link in a tweet, they are seeing a version of Dataverse that works well.

@kcondon very good point about people in the field using tablets for data collection and wanting to put into Dataverse. I'm going to dive into the analytics again to see what devices are being used in areas with lower connection speeds.

**Comment by pdurbin** [comment]
@mheppler can we close this issue? We're trying to work in small chunks these days.

**Comment by mheppler** [comment]
@pdurbin If you say so.

**Comment by pdurbin** [comment]
@mheppler thanks! Closing!
