### ISSUE TITLE
Review and improve metadata tooltips, field labels and watermarks

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#8127]
This issue is to outline and track the effort to improve tooltips, field labels and watermarks related to metadata blocks. Clear and consistent tip text, labels and watermarks should help depositors curate their datasets and enter data accurately, leading to more and more consistent metadata. 

**Goals:**  
- Improve the collection of dataset metadata 
- Define and document rules for adding or editing metadata tip text, field labels and watermarks

**Scope/definition of done:**
Review metadata tooltip text, field labels and watermarks for consistency and clarity: citation block, social sciences block, journals, geospatial, astrophysics 
- [x] define[ "working rules" to guide grammar and style/consistency](https://docs.google.com/document/d/1tY5t3gjrIgAGoRxVMWQSCh46fnbSmnFDLQ7aLkNLhJ8) improvements to tip text, form labels and watermark text
- [x] apply the working rules to existing tooltips, field labels and watermarks. [Drafting proposed edits](https://docs.google.com/spreadsheets/d/1sHRvSpGSF0XfKTp4nWxT0zX4z8TORcuX7DTDrktOorg/edit#gid=0) for review
- [x] document opportunities for additional improvements, such as form layout and behavior. These could be broken off as separate issues
- [x] review proposed text changes with metadata/topic experts
- [x] communicate with the community about changes (affects languages/translation)
- [x] update tooltip text, field labels and watermarks in Dataverse
- [x] evaluate changes
- [ ] complete & share the style guide

**Comment by djbrooke** [comment]
Thanks @TaniaSchlatter @scolapasta @jggautier for discussing earlier. The above checklist remains accurate.

- @scolapasta @jggautier and @djbrooke will meet to get a shared understanding of how tool tips are managed and updated for those installations that have localized and those that have not. In the meeting, we should also look at how to manage tool tips for system generated content (such as the dataset PID). We're planning on meeting Thursday at 1 PM.
- Groups that were mentioned for follow up were DDI Alliance, Scholar's Portal/Portage, and the curation team at the Harvard Dataverse Repository. @jggautier has a list as well. We will do targeted outreach to these groups and also general outreach to the community.

**Comment by scolapasta** [comment]
@jggautier I would expect those changes to just have to be made to the bundle.

**Comment by jggautier** [comment]
That worked, thanks!

**Comment by jggautier** [comment]
Tooltips aren't being removed as part of these changes, so the PR attached to this issue doesn't remove any tooltips.

**Comment by jggautier** [comment]
To share the Style Guide, @TaniaSchlatter and I thought it would be best to include a link to the Google Doc in the Admin Guide's [Metadata Customization page](https://guides.dataverse.org/en/latest/admin/metadatacustomization.html), maybe in a "Style Guide" section after the "Introduction" section. After the guide's been tested more (i.e. we get more feedback as it's reviewed and used more often to apply the guidelines to the application's other metadata field names, tooltips and watermarks), we could consider moving the text into the actual guides.

So the last to do for this issue is for me to prepare the style guide to be able to share more widely and add it the Metadata Customization page:
- Copy the Google Doc into a Google Doc that can live in IQSS's "Dataverse" Google Drive folder
- Move the notes and questions into [a Google Doc that lists the unresolved issues](https://docs.google.com/document/d/1ESDo8w0JD0OeI9K2NMn8RTYLX1naqN70l8Ak5yjf_i4) discussed during reviews of the changes to the Citation metadatablock.
- Create an "epic" GitHub issue listing each of the unresolved issues and referencing any existing GitHub issues and discussion in other channels (e.g. the Dataverse Community Group (Google Group))
- In [the PR with the changes to the metadata fields](https://github.com/IQSS/dataverse/pull/8454), edit [the Metadata Customization page](https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/admin/metadatacustomization.rst) of the Admin Guides to include a Style Guide section with a link to the Style Guide

**Comment by jggautier** [comment]
We've decided to add the guidelines to [the Style Guide](https://guides.dataverse.org/en/latest/style/index.html), in a new page called "Text" for style guidelines related to text. The page, created in the PR associated with this issue, is called "Text" and will include a link to the Google Doc where we're keeping the metadata text guidelines for now (since we expect frequent changes to it).

In the "Tips from the Dataverse Community" section of the [Metadata Customization page](https://guides.dataverse.org/en/latest/admin/metadatacustomization.html), I mention and link to the Style Guide and its "Text" page.

I hope by the end of this week to have the Google Doc organized enough so that the link to it can be included in the Text page and that should be the last to-do for this issue.

**Comment by jggautier** [comment]
The Style Guide "Text" page is updated. Moving the PR to the review column.

**Comment by mreekie** [comment]
Sprint: 
 - #8127 goes into the next sprint (Needs a new PR)
 - See: https://github.com/IQSS/dataverse/pull/8592#issuecomment-1124209003

**Comment by pdurbin** [comment]
PR #8592 was just merged so as discussed I just put this issue in "Next Sprint". Also as discussed, we need a new PR.

**Comment by jggautier** [comment]
I just submitted the changes in a PR

**Comment by mreekie** [comment]
Prio:
- This should be straightforward to move through.
- High priority to get through.
