### ISSUE TITLE
Harvesting

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#813]
In DVN 3.x we had harvesting: https://github.com/IQSS/dvn/blob/develop/doc/sphinx/source/dataverse-user-main.rst#harvesting-section

There should be an option to show federated dataverses in the featured dataverses UI developed in #750.

**Comment by bencomp** [comment]
For issue management: this issue concerns OAI-PMH.

**Comment by bencomp** [comment]
For consideration: [ResourceSync][rs] is a set of protocols based on [Sitemaps][sitemaps] for publishing information about, links to or dumps of changed resources - both data and metadata. As it was developed by the people from the [Open Archives Initiative][oai], some consider this the new [OAI-PMH][pmh].

[rs]: http://www.openarchives.org/rs/
[sitemaps]: http://www.sitemaps.org/protocol.html
[oai]: http://www.openarchives.org/
[pmh]: http://www.openarchives.org/pmh/

**Comment by bencomp** [comment]
And ResourceSync was already mentioned in #900.

**Comment by posixeleni** [comment]
@scolapasta @eaquigley please also keep in mind that we need to add a new Dataverse to our harvest per this request from the UBC Abacu Dataverse team. Should I create a separate ticket for this?

>​Eleni:
>
>We are very excited to see Dataverse 4.0 alive. Is there a way for us to harvest our UBC Abacus dataverse we run for the province of BC and include the results in the main dataverse index?
>
>Thanks!
>
>Eugene​

**Comment by eaquigley** [comment]
@scolapasta @mcrosas @posixeleni do we have a list of all installations and others that we will be harvesting from? wanted to check due to @posixeleni comment above. also, @scolapasta should i have this ticket still or should it be going to someone else? we've already decided the behavior for displaying harvested materials (is searchable, has a search card with the harvested icon and text, will open in a new tab at the location where it is from)

**Comment by mcrosas** [comment]
Here is the current list (harvested dataverses):

https://docs.google.com/spreadsheets/d/1xE55jFE--sEDvvS-vtXavBxc8VvKvKpGJXcjfkelcAw/edit#gid=0






Mercè Crosas, Ph.D.
Director of Data Science, IQSS
Harvard University
http://scholar.harvard.edu/mercecrosas

**Comment by bencomp** [comment]
I just realised this issue is not about providing an OAI-PMH endpoint for dataset metadata. Or is it? Should another issue be opened for it?

**Comment by mcrosas** [comment]
@bencomp yes, supporting harvesting includes supporting OAI-PMH for dataset metadata.

**Comment by bencomp** [comment]
One of our partners needs the OAI-PMH endpoint to be available to meet project responsibilities. Is there any new information about the milestone this will be part of?

**Comment by mcrosas** [comment]
The plan for now is to do this for 4.3. We'll be reviewing 4.2 and 4.3 issues in this week and next (in our weekly "Issues review" meetings) and make a decision then.

**Comment by pdurbin** [comment]
I created a [Harvesting Functional Requirements Document (FRD)](https://docs.google.com/document/d/1XZHpTyYUwyPN3FIfJhaSFg5_h-9C415mlE42Fuao38w/edit?usp=sharing) and @landreev and I wrote down some use cases (one definite and tentative). We definitely want to support harvesting of DDI over OAI-PMH and @landreev will be making a sub-issue for that specific use case. Comments are welcome on the FRD! We're trying to define what we will be shipping in 4.4 and what will be worked on in subsequent releases.

**Comment by eaquigley** [comment]
@scolapasta what should i do with this ticket? i'm working on the BRD but @landreev has already done some development for this.

**Comment by landreev** [comment]
I am working on this now. 
I guess I should just go ahead and take this issue?

**Comment by djbrooke** [comment]
@landreev - I met with @eaquigley to review the Usability Testing Feedback and these items should be fixed for this release:

- Move Dashboard link to be an item in the navigation and not within the username dropdown
- Make all boxes on Dashboard landing page same size
- If a user tries to harvest content that has already been harvested, there is nothing in the UI that tells them this has happened. It continues to show “INPROGRESS” in the table - let's provide better messaging about what is happening
- Add text that says the scheduling is for the local time of the installation 
- Change column heading from "Statistics" to "Number of datasets" (unless this will display anything aside from Number of datasets)
- Use Tool tips instead of onscreen text under the specific boxes 
- Make the first input field the focus when opening a new modal

**Comment by landreev** [comment]
There was one serious bug found during the usability session that is NOT on this list: After creating a new, or editing and saving an existing client, clicking on the "edit" button resulted in an empty popup; the page would stay in that state  until reloaded. 
This was indeed a really bug, unlike almost everything else on this list, and it has been fixed.

**Comment by landreev** [comment]
@djbrooke 
I would like to point out that 4 of these bullet points: 1, 2, 6 and 7 are cosmetic fixes of the page itself; that would be for Mike to work on, and not for me. They are probably very easy to fix, but seeing how it's kind of late, and nobody has yet alerted Mike about it, I propose we table them - ? (and seeing how they don't appear to be anywhere near crucially important for the actual functionality of the pages)

**Comment by landreev** [comment]
Any chance we could drop number 4 from the list: 

 - Add text that says the scheduling is for the local time of the installation 

and just go on pretending it has never been brought up in the first place? Unless somebody could give me a single reason anyone would ever assume that this is NOT their local time, but, say, London or Central Australian time?

**Comment by landreev** [comment]
Item 5: 

- Change column heading from "Statistics" to "Number of datasets" (unless this will display anything aside from Number of datasets)

it's more complex than just a "number of datasets" - it could be *various* numbers of datasets related to this set: "N number of datasets found; M already exported; K marked as deleted". But, I agree, "Statistics" is not the best term. I have changed it to just "Datasets" - would that be ok? 
Because that's what the column is for - to show the information about the Datasets that belong to the set in question.

**Comment by landreev** [comment]
Item number one: 
- Move Dashboard link to be an item in the navigation and not within the username dropdow

I can do this is in about 5 seconds, most likely... but where is "navigation"?

**Comment by mheppler** [comment]
@landreev @djbrooke -- My $0.02... Why have usability testing if we aren't going to implement suggested UI improvements? Can we meet quickly this afternoon to review these and I can give a LOE to determine if indeed I can get them into this release. Seems foolish not to.

**Comment by landreev** [comment]
Number 3: 
This is a super important one (was the single most embarrassing point of the usability session)
Because it failed in the most un-gracious, user-unfriendly way (by hanging in the "inprogress" state) 

This is the way I have resolved this: 
Now, if any dataset being harvested is found to already exist in this Dataverse installation, but AS PART OF ANOTHER dataverse, the following will happen: 
- the dataset will be skipped
- the harvest will continue, and will complete; 
- it will be listed under the "failed" count in the last harvest results. 

However, it will still not be immediately obvious to the admin using the page, that the dataset failed to get harvested for this specific reason - because it's already present in another dataset. To find that, they would need to go and read the harvest log. 
My solution is to explain this in the admin guide: 

... You can consult the detailed harvesting log (found in ...) to learn more about the harvesting failures. For example, please note that an attempt to harvest datasets that are already present *in another dataverse*, will result in these datasets being skipped and listed  as failed. (Deleting harvested datasets from dataverse A will make it possible to harvest them into dataverse B). 

(Alternatively, a new statistics field could be added - in addition to "harvested", "deleted" and "failed", something like "exist in another dataverse, skipped" - to be shown in the results immediately. If you feel it is necessary for this release, I could put it in place today)

**Comment by landreev** [comment]
@mheppler @djbrooke 
Mike, that is the plan - Danny and I are meeting at 2:30 to go through the list. 
I was about to ask you if you wanted to join us. 
I just wanted to comment on all this before the meeting. 

I wasn't talking about not implementing these (with the exception of one, the time zone)
I was talking  about 4.5 vs 4.5.1. 

If you feel that any of this is a low-hanging fruit that you could easily fix for 4.5, by all means do so. But I am strongly against actually holding the release on account of cosmetic changes, at this point. I've said this about a million times already, but one more time: this functionality is for admins only; these pages will be used by admins only, *and very rarely* - compared to the workhorse pages used by all the users every day.

**Comment by djbrooke** [comment]
Thanks @landreev and @mheppler for meeting about this! Good to put together a plan to tackle these.

**Comment by mheppler** [comment]
Status of my UI updates from the list above:

[x] Move Dashboard link to be an item in the navigation and not within the username dropdown
[x] Make all boxes on Dashboard landing page same size
[ ] Use Tool tips instead of onscreen text under the specific boxes
[ ] Make the first input field the focus when opening a new modal

**Comment by kcondon** [comment]
OK, looks good. Have completed baseline testing of Harvesting, functionality is delivered and issues found are opened in new individual tickets. Closing.
