### ISSUE TITLE
".qpj" file taken out of QGIS Shapefile zip

### ISSUE THREAD

**Issue by mathieu-massaviol** [IQSS/dataverse#8134]
**What steps does it take to reproduce the issue?**
Publishing a zipped Shapefile created with QGIS tool.

* When does this issue occur?
When creating a new dataset and uploading a zipped Shapefile created with QGIS

* Which page(s) does it occurs on?
We can see it on a dataset files tab

* What happens?
The Shapefile from QGIS tool has a subfile ".qpj" which is the equivalent of the ArcGis ".prj". After publishing the zipped Shapefile we can see in the files tab of the dataset that the ".qpj" has been taken out of the Shapefile zip. It seems that this file extension is unknown by dataverse.

**Which version of Dataverse are you using?**
v. 4.15 build 221-9a0b627

Thanks in advance for your help.

Mathieu Massaviol

**Comment by djbrooke** [comment]
Hi @mathieu-massaviol - since 4.15 is an older version, can you try this on demo.dataverse.org and see if you get the same behavior?

**Comment by pdurbin** [comment]
Related:

- #8816

**Comment by pdurbin** [comment]
> https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.70122/FK2/OTZQNB&version=DRAFT

Sadly, the dataset and file are gone now because we clear out the demo site periodically.

@mathieu-massaviol are you able to upload a sample file to this issue? If not, would you want to add it (and a parent dataset) to our "sample data" repo? It's at https://github.com/IQSS/dataverse-sample-data

**Comment by pdurbin** [comment]
@Saixel I gave you this issue because it's geospatial-related and I'm hoping it's relatively straightforward to reproduce. Please try the shape_with_qpj.zip file above and let us know if you see the same behavior, that the .qpj file has been removed from the zip file after it has been processed by Dataverse.

Then, in the code, please poke around in [ShapefileHandler.java](https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/util/ShapefileHandler.java) and ShapefileHandlerTest.java. I didn't write this feature but I'm pretty sure this is the right area to look at.

**Comment by pdurbin** [comment]
@mathieu-massaviol hi! @Saixel coded up this fix...

- #10305 

... and it's been merged and deployed to https://beta.dataverse.org

Please feel free to try it out! Thanks!

**Comment by mathieu-massaviol** [comment]
I just tested it and it works perfectly !

Thanks !
