### ISSUE TITLE
Feature Request/Idea: Download metadata from search results as CSV

### ISSUE THREAD

**Issue by Harshpanday** [IQSS/dataverse#8264]
Hi all,
It might be interesting to have a ‘download metadata as CSV on the webpage showing the search results.
Thus allowing non-programmers to get that metadata and inspect it in a spreadsheet application.

With kindest regards,
Harsh Panday

**Comment by mateolan** [comment]
+1

**Comment by pdurbin** [comment]
Good idea. One complication is representing a hierarchy (multiple authors, etc.) as a CSV.

When I first developed the Search API and search/browse UI I thought it might be useful to have a link at the bottom of the UI that said "Show these results in the Search API." That would be JSON instead of CSV, though, and perhaps a bit too geeky and confusing for many users. Would that be helpful? Or do you really want a CSV?

**Comment by jggautier** [comment]
This is related to the GitHub issue at https://github.com/IQSS/dataverse/issues/6471.

Also just leaving some more info that could be helpful if/when we have the bandwidth to work on this:

This kind of feature came up during a conversation I had today with someone who emailed Dataverse support (https://help.hmdc.harvard.edu/Ticket/Display.html?id=348831) to get help with looking for certain kinds of datasets in Harvard Dataverse.

They also wrote that the AEA RCT Registry has a similar feature on [its advanced search page](https://www.socialscienceregistry.org/trials/search).
