### ISSUE TITLE
Fix Postgres Constraint: DatasetVersion allows possibilility of non-existing Dataset

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#828]
At the **postgres level**, if a Dataset is deleted:

+ The related DatasetVersion rows remain intact even though the Dataset itself is gone

```sql
CONSTRAINT fk_datasetversion_dataset_id FOREIGN KEY (dataset_id)
      REFERENCES dvobject (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
```
Consider either:

1. Changing the FK constraint from ```ON DELETE NO ACTION``` to ```ON DELETE RESTRICT```
   + The Dataset row cannot be deleted without first deleting the DatasetVersion row
2. (probably not) Changing the FK constraint to ```ON DELETE CASCADE```
   + Deleting the Dataset Row also deletes the DatasetVersion rows

**Comment by ekraffmiller** [comment]
This is a general issue with tables that are created using Join inheritance in the entities.  The foreign keys are mapped to the parent entity (dvobject), rather than the child - in this case dataset.  It affects many other relationships in the application as well.  It's a known issue in Eclipselink:  https://bugs.eclipse.org/bugs/show_bug.cgi?id=333100.  

I spoke to Gustavo about this, and since there is still a constraint at the parent level - ie, within SQL,  you can't delete a dvobject if a related datasetversion exists, and also because the cascade delete works as expected when deleting from the application level, that it's ok to leave things as they are.

@raprasad , just wanted to get your feedback on this - is it ok to close?  Or maybe we can keep as a lower priority, so we can track the Eclipselink bug.

**Comment by raprasad** [comment]
@ekraffmiller, yes, fine with me to close. thanks
