### ISSUE TITLE
versioning: optimize load time for dataset with multiple versions

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#8328]
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/2USIUM

This dataset "versions" tab load page is taking approximately 50 seconds. There are 73 versions at this time with plans for continued versioning.

**Comment by qqmyers** [comment]
FWIW: It would be good to understand why people want to view that table. A lot of the processing behind it is to calculate the per-version differences, so if users just want to see when versions were released (or other subset of what is currently calculated) this table could be made lighter weight. There might also be ways to make things more efficient in general, but certainly easier if we just don't need everything that is there now.

Also FWIW: there are 130+ versions counting all the minor numbers.

**Comment by sbarbosadataverse** [comment]
For any dataset,  someone may want to access the data files for older
versions. For example,  one version of this dataset contains the 1000 or so
files that have some downloads.  Those same files were removed from the
most recent version.  A user may want to go back and access those files in
the earlier version.

Thanks

**Comment by qqmyers** [comment]
The key question is really whether finding the right past version requires knowing the per-version differences (which are currently expensive to calculate) all the time or if just showing the list of versions and release dates is enough for most cases (perhaps still with the checkboxes to let you the difference between two specific versions). If seeing those differences is only rarely needed we could also make it an option. If it is always needed, we really need to look into how to calculate them much faster or to cache the results so they don't get recalculated when we're trying to show the page. (My guess is the long-term fix is to improve the efficiency, but it might be a quick improvement for users to drop the difference calculations for now.)

**Comment by mreekie** [comment]
sizing:
- PM added to ordered sizing queue

**Comment by mreekie** [comment]
sizing:
 - First step on this would be a spike for an investigation.
 - It would start with a set of use cases, and which ones are critical. This would enable us to look at optimizing the code for speed.
 - The first step - the use cases would need to be done by Sonia.

**Comment by cmbz** [comment]
**2023/10/04**
- Related to https://github.com/IQSS/dataverse/pull/9883 
- @landreev will review to determine if https://github.com/IQSS/dataverse/pull/9883 will either fully or partially address the problem described in this issue.

**Comment by cmbz** [comment]
2023/10/10: Sized at 3 and moved into "This Sprint" as per @landreev 's comments. He will comment later here.

**Comment by landreev** [comment]
Here's a promised comment from me: 
This was discussed on slack; 
The issue was opened for making the versions tab on the dataset page less of a hog for dataset with too many versions;
The only way to achieve that, I’m pretty sure, is to both optimize the lookups AND add pagination to the versions list display. We almost certainly don’t want to spend that much effort on the existing jsf page.
However, I suggested opening it as a temp. spike, to just try and see if switching that versions view to using the recently added optimized (“deep”) version lookup methods would speed things up there at least somewhat. So this is why it’s a “3" - it’s just to make a few very simple changes, build it and throw the war file on the perf. cluster, and see how it fares with the monstrous dataset(s) mentioned there.

**Comment by cmbz** [comment]
2024/01/03: resized during kickoff

**Comment by landreev** [comment]
I ran into some trouble trying to wrap up this spike, the "testing on the perf. cluster" part, since it appears to be broken at the moment. I may need to revisit this tomorrow.

**Comment by landreev** [comment]
Unfortunately, a quick change as described above does not really fix it. Of the view things I tried, the simplest change, https://github.com/IQSS/dataverse/commit/974721459d06a088413427e20c6ca8146e6a81fb - looking up the entire versions-filemetadatas-datafiles tree in one go with the new `DatasetService.findDeep()` method - appears to be the most effective, but still only speeds up the rendering time for the tab on 2USIUM by ~30% only on the perf. system. So in prod. this would be something like 50 sec. instead of the currently observed 70 sec. - still a hog. I could make a PR, but I'm a bit hesitant/not sure if it's worth bothering. The extended lookup is faster, but it's not free either, I understand that we pay for it with much more memory spent processing the query output. There is also a chance this model may slow it down for other, less exotic datasets.

This does make sense - it appears that the most expensive part of the operation is not the files, but the metadata fields. There gotta be ways to optimize that part as well, maybe even with custom queries. Adding pagination to the view (only show 10 versions at a time) appears to be a must as well. ... But will probably have to wait til SPA. (will double-check with the team as to what to do w/ this).

**Comment by landreev** [comment]
We talked about this during standup yesterday. 
The consensus appeared to be, since it wasn't possible to radically improve the performance of the tab with the quick fix above, we were going to remove it from "this sprinrt" and sent it back into the purgatory. With the understanding that we will make this tab more efficient in the new SPA. But that it doesn't appear to be prudent to invest any serious amount of work optimizing this component in the old PrimeFaces UI. 
@scolapasta does this sound about right?

**Comment by cmbz** [comment]
2024/03/14
- Take this issue off the board entirely and close it.
- Open an SPA issue that is related to this one; @pdurbin

**Comment by pdurbin** [comment]
I opened an issue on the SPA side:

- https://github.com/IQSS/dataverse-frontend/issues/343
