### ISSUE TITLE
Provide an API for retrieving information about an individual datafile

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#8339]
We do not have an easy way to retrieve a full information record for a single datafile, such as what's listed in `/api/datasets/{did}/versions/{vid}` (for all files in the version). 
We do have `/api/files/{id}/metadata`, but it literally only shows what's in the FileMetadata entity (such as file and folder names), plus the tags and the restriction status. I.e., it's not showing all the info that's in the DataFile entity (size, mime type, etc. etc.). So the only practical way for an API user to look up a full info record for a file is to get a full list of all the files (above) and parse it out, which is inefficient. 

We could extend `/api/files/{id}/metadata`, synchronizing its output to what's listed in the records under `/api/datasets/{did}/versions/{vid}`. 
Alternatively, we could provide a GET `/api/files/{id}` to produce such a record. (This could be a better option - since it would match the behavior of other entity APIs - `/api/datasets/{id}` etc. - ?)

**Comment by mreekie** [comment]
At a high level we provide this for all files at once.
We will likely be able to reuse this code, and change it so that you can just specify a single file.
We should write automated tests to go along with this.

There is a decision needed before code can begin.
- We have a file metadata endpoint.
- We don't have a file endpoint.

Part of this would be a 3 day timebox to figure out the decision.

Thoughts
- We add metadata in one place, and it goes to all files and the one file.
- Does this impact performance?
- We have file metadata class and then the file itself. In order to do anything with the file you need to hit both of those things. Do you make one API call or 2? That is less impactful than how the data is stored in the database.

sized at 33

**Comment by mreekie** [comment]
added to sprint Dec 15, 2022

**Comment by mreekie** [comment]
upated: Working on tests. Close to a PR
