### ISSUE TITLE
Dataset Export: Metadata character causing json parsing error, schema.org export fail and subsequent 500 error

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#8358]
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/J9TLXT

Something in the metadata is causing schema.org export to fail with a json parsing error, posting a blank file allows dataset to load. 

So, this ticket is to:
1. identify latest failing char to be fixed.
2. consider once again:
-allowing the dataset page to load despite one or more export failures
-allowing the page to be loaded in a raw mode that can be used for troubleshooting/fixing.

**Comment by djbrooke** [comment]
Thanks @kcondon for creating this issue!

**Comment by pdurbin** [comment]
Export goes to /tmp initially. You might be able to figure out the bad character.

The blank file workaround works because exports are cached. If a file exists, it will be served up rather than showing an error. If we remove the blank file, we can reproduce the error.

Consider loading native JSON locally to see if you can reproduce it.

It would be nice to more gracefully handle 500 errors when exporting.

**Comment by pdurbin** [comment]
I can't reproduce this in develop now that multi license (PR #7920) has been merged.

That's because the Schema.org JSON-LD output has changed. Instead of the following in 5.9 and below...

```
  "license": {
    "@type": "Dataset",
    "text": "My custom terms"
  },
```

... develop/5.10 and above now have a URL like this:

```
  "license": "http://localhost:8080/api/datasets/:persistentId/versions/1.0/customlicense?persistentId=doi:10.5072/FK2/N19IYT",
```

To reproduce this on demo (running 5.9):

- Choose non-CC0 license
- For "Terms of Use" put `Put &quot;ditto&quot; marks around it.` as in the screenshot below.

![140801467-0ed45a29-bcd0-4bcd-a257-0701ae77a953](https://user-images.githubusercontent.com/21006/158683913-95500965-ae46-4771-a872-7b3a05239f59.png)

On publish, the page will blow up with a 500 error like this:

![Screen Shot 2022-03-16 at 4 28 02 PM](https://user-images.githubusercontent.com/21006/158684989-d5ccadb3-e722-4665-8e91-3ee28d547f94.png)

This issue is basically a duplicate of #8224. If we can't reproduce this post 5.9, should we close both? I'll put this in review for discussion.

**Comment by kcondon** [comment]
@pdurbin @scolapasta The symptoms aren't exactly the same -the dataset is already published for instance, but I do still see an error when attempting to export the schema.org JSON-LD export, with the export page showing: {"status":"ERROR","message":"Export Failed"}

I am not seeing an error in server.log, however.

**Comment by kcondon** [comment]
This is working now for this dataset.
