### ISSUE TITLE
Publishing: When trying to use the overwrite publishing option, error message with failed to publish

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#8400]
Navigate to this dataset and updates the related publication fields to include metadata for "id type" "id number" and "url" field: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi%3A10.7910%2FDVN%2F0C3BTS

Select save and get a successful draft. 

Select publish and choose the overwrite option and error message shows up

superuser functionality

Expected that the publish would overwrite the existing version.

**Screenshots:**

![Screen Shot 2022-02-04 at 2 21 38 PM](https://user-images.githubusercontent.com/8322346/152590717-8015a093-51ef-4d5d-b6d2-809dff2276a8.png)

**Comment by pdurbin** [comment]
This is the "curate new version" feature (superuser only).

@scolapasta @qqmyers and @sekmiller have discussed briefly. @sekmiller unable to reproduce.

Has happened on multiple drafts. Draft still able to be deleted.

Related to inter versions? If one version has a space?

Code assumes previously published version from list. Could it have the wrong version? Line 102. More details in Slack. #8382 is about version differences.

@scolapasta can probably upload the stacktrace.

No actual file metadata changes. Probably from the draft.

Around line 155, curate command is trying to delete links to file metadatas. Watch out for references to file metadatas.

**Comment by scolapasta** [comment]
@valentinapasquale The removal is a technical aspect of how overwrite works (since what the code for overwrite copies the info from the draft to the last published, then deletes the draft, effectively "removing" the filemetadata objects the draft created). We are still trying to determine the cause of the error, so any additional info you have  about that dataset - since it doesn't always happen - would be helpful.

Creating a new version instead should definitely work.
