### ISSUE TITLE
Multilicense flyway not consistent with JSON examples

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#8407]
The [CC0 1.0 license json file](https://github.com/IQSS/dataverse/blob/develop/scripts/api/data/licenses/licenseCC0-1.0.json) is consistent with the other examples in using the title recommended by Creative Commons (including the version number) but this is inconsistent with the update provided by the flyway script (which was created early on). The URL (differing by a trailing slash), short description, and icon location also differ. The db upgrade should match the examples and the pattern for the other licenses.

There seem to be two options for implementing

1. Update the existing flyway script (requires developers to remove the record of running the prior version from their db, but avoids a second flyway script in this release)
2. Add a second flyway script to modify the results of the first (possibly simpler to create, easier for developers, ends up with second flyway script)

@scolapasta /others - any preference? (I think I'm leaning towards 2, but will implement whatever).

**Comment by scolapasta** [comment]
prefer the first, since it feels cleaner. But I get the pros and cons of both, and don't feel strongly about it.

**Comment by pdurbin** [comment]
I'm a little weirded out that there are two copies of the CC0 config:

1. the JSON file
2. the Flyway script

If we're going to mess with the Flyway script anyway, I'm wondering if it's an opportunity to get down to a single source of truth, the JSON file.

I know we discussed in tech hours how the CC0 change has to happen in Flyway but I don't think that's necessarily the case. For one thing, Flyway is relatively new to us. 😄 In the pre-Flyway days, it was pretty common to instruct people to use a combination of curl commands (loading JSON files) and manual SQL updates.

So I imagine we could have something like this in our release notes:

- Minimal Flyway script to add the new column: `ALTER TABLE termsofuseandaccess ADD COLUMN IF NOT EXISTS license_id BIGINT;`
- Run a curl command to add the CC0 license from the JSON file.
- Instructions to run a SQL upgrade script (the rest of the current Flyway script) that needs the CC0 license to be in place.

And in the installer (setup-all.sh), instead of relying on a random Flyway script to add the CC0 license, we'd add:

- curl command to add CC0 from the JSON file (and possibly other licenses per #8347)

Advantages:

- Single source of truth for CC0 license (JSON file)
- Licenses treated like all other items under `scripts/api/data` such as metadata blocks, roles, authentication providers, etc. They are input for the installer.
