### ISSUE TITLE
Docs > installation/installation-main:  default.config file format is not compliant with the one available on releases page

### ISSUE THREAD

**Issue by j-n-c** [IQSS/dataverse#8481]
_default.config_ sample file available for download in the [installation guide](https://guides.dataverse.org/en/latest/installation/installation-main.html#running-the-dataverse-software-installer) is out of date and uses a differente format from the one available in dvinstall.zip (from the releases page)

**Comment by pdurbin** [comment]
@j-n-c please remind me... were you planning on creating a pull request for this? I'm asking because this bug just bit us again today ("File contains no section headers"): https://matrix.to/#/!AmypvmJtUjBesRrnLM:matrix.org/$Ii8Y7-6mQ56r3LBkPxlATQEUbbl-mRiOaI_3a8hJ5Z8

As a workaround I suggested using https://github.com/IQSS/dataverse/blob/v5.10.1/scripts/installer/default.config (from our current release).

I think we should treat `scripts/installer/default.config` as the source of truth and delete the obsolete version from the docs. We can use the Sphinx "literal include" and/or "download" directives to pull in the one from that `scripts` directory.

**Comment by j-n-c** [comment]
@pdurbin I'll investigate how to include the file from the `scrips` diretory and submit the pull request
