### ISSUE TITLE
Feature Request/Idea: Suggestion to use Google captcha

### ISSUE THREAD

**Issue by eunices** [IQSS/dataverse#8529]
**Overview of the Feature Request**
Use Google captcha

**What kind of user is the feature intended for?**
(Example users roles: API User, Curator, Depositor, Guest, Superuser, Sysadmin)
all authenticated users

**What inspired the request?**
Prevent brute-force hacking since existing captcha's output is an sum of numbers up to 20.

**What existing behavior do you want changed?**
Use Google captcha instead of captcha based on sum

**Any brand new behavior do you want to add to Dataverse?**
NA

**Any related open or closed issues to this feature request?**
Not that I found any

**Comment by poikilotherm** [comment]
I'd advice against a static inclusion of a CAPTCHA service like reCAPTCHA, because there's lots of problems with their privacy policy and availability around the world etc.

- This should be an optional feature
- This should be configurable (JavaScript to include for client side, CAPTCHA API call for verification etc)
