### ISSUE TITLE
Idea: Move "Managing Datasets and Dataverse Collections" under API Guide

### ISSUE THREAD

**Issue by kaitlinnewson** [IQSS/dataverse#8539]
**Overview of the Feature Request**

As someone frequently using the User Guide, I often have a hard time finding the page "Managing Datasets and Dataverse Collections", which is primarily made up of API commands. It is currently under Admin Guide, but I would like to recommend moving it under the API section instead. I am happy to make a PR for this if others agree.

**What kind of user is the feature intended for?**
API Users looking for documentation.

**What inspired the request?**
I have a hard time finding this page! But I'm starting with an issue before a PR in case others feel differently.

**What existing behavior do you want changed?**
The location of the "Managing Datasets and Dataverse Collections" page.

**Any brand new behavior do you want to add to Dataverse?**
No

**Any related open or closed issues to this feature request?**
No

**Comment by pdurbin** [comment]
@kaitlinnewson no objection but rather than a wholesale removal, on the "Managing Datasets and Dataverse Collections" can you please leave the headers and link to the sections of the API Guide? That's what we do at https://guides.dataverse.org/en/5.10/admin/user-administration.html (screenshot below).

![Screen Shot 2022-03-28 at 4 07 57 PM](https://user-images.githubusercontent.com/21006/160478706-dd12b5ce-2948-46e3-a673-b9fd1b840ddf.png)

Here's the rst:

```
Merge User Accounts
---------------------

See :ref:`merge-accounts-label`

Change User Identifier
-------------------------

See :ref:`change-identifier-label`

Delete a User
-------------

See :ref:`delete-a-user`

Deactivate a User
-----------------

See :ref:`deactivate-a-user`
```

Hmm. I see there are a lot of headings under "Managing Datasets and Dataverse Collections"...

![Screen Shot 2022-03-28 at 4 12 17 PM](https://user-images.githubusercontent.com/21006/160479206-4e9d7018-e747-4176-a697-c7959c723506.png)

... if what I'm suggesting sounds unreasonable, please let me know.

**Comment by poikilotherm** [comment]
Somewhat related: https://github.com/IQSS/dataverse/issues/5155#issuecomment-1036224846

**Comment by pdurbin** [comment]
Here's a related issue where I'm looking for a place in the guides to link to scripts that the community has written for migrating data into Dataverse:

- #8275

**Comment by jggautier** [comment]
Just mentioning that the issue at https://github.com/IQSS/dataverse/issues/8120 is related.

**Comment by pdurbin** [comment]
Closing in favor of this issue:

- #8120
