### ISSUE TITLE
Location of the DOI/DataCite password

### ISSUE THREAD

**Issue by lmaylein** [IQSS/dataverse#8568]
Hi

In https://guides.dataverse.org/en/latest/installation/config.html, it looks to me like the DataCite password should be in plain text in domain.xml.

```
<jvm-options>-Ddoi.username=...</jvm-options>
<jvm-options>-Ddoi.password=...</jvm-options>
```
However, https://guides.dataverse.org/en/latest/installation/installation-main.html: states that the doi_password would be set as alias during installation.

```
Here is a list of the password aliases that are set by the installation process and entered into Payara’s domain.xml file:
    dataverse.db.password
    doi_password_alias
    rserve_password_alias

```

Is there a difference between older and newer installations? Should we change this if we still have the password directly in domain.xml? And if so, how?

**Comment by pdurbin** [comment]
@lmaylein good questions. Alias passwords were added in Dataverse 4.11 in pull request #5487. You already mentioned what's in the guides but here's a bit more from https://guides.dataverse.org/en/5.10/installation/installation-main.html

---

IMPORTANT: As a security measure, the as-setup.sh script stores passwords as “aliases” rather than plaintext. If you change your database password, for example, you will need to update the alias with `asadmin update-password-alias dataverse.db.password`, for example. Here is a list of the password aliases that are set by the installation process and entered into Payara’s domain.xml file:

- dataverse.db.password
- doi_password_alias
- rserve_password_alias

For more information, please see https://docs.payara.fish/documentation/payara-server/password-aliases/password-alias-asadmin-commands.html

---

There's no real difference between older and newer installations. The pull request simply took advantage of a feature of Glassfish/Payara that's been around for a long time. Installations of 4.11 and above make use of the password alias feature. Older installations do not, but you can set it up manually. (Judging from the 4.11 release notes at https://github.com/IQSS/dataverse/releases/tag/v4.11 we never explicitly suggested that older installations set up password aliases.) I would say, yes, it's a good security practice to set this up. In dev, I'm not in the habit of changing these passwords so I don't have much experience with these commands. I'd suggest looking at the Payara docs linked above.

**Comment by lmaylein** [comment]
I have now tried the following change:
 * /usr/local/payara5/glassfish/bin/asadmin create-password-alias doi_password_alias
 * delete `<jvm-options>-Ddoi.password=***</jvm-options> from domain.xml
Unfortunately this does not work:

```
[2022-07-25T08:58:06.823+0200] [Payara 5.2021.6] [WARNING] [] [edu.harvard.iq.da
taverse.DOIDataCiteServiceBean] [tid: _ThreadID=208 _ThreadName=__ejb-thread-pool1] [timeMillis: 1658732286823] [levelValue: 900] [[
  modifyMetadata failed: Response from postMetadata: 401, Bad credentials
java.io.IOException: Response from postMetadata: 401, Bad credentials
```
Did I forget something during the changeover?

**Comment by donsizemore** [comment]
Hello, after you deleted the `doi.password` jvm-option, did you recreate it and restart?

https://github.com/IQSS/dataverse/blob/develop/scripts/installer/as-setup.sh#L110

**Comment by lmaylein** [comment]
No. That will have been the mistake. I'll try it again the next few days. Thank you.

**Comment by lmaylein** [comment]
It works! Thanks.
