### ISSUE TITLE
Re-add value "cell counting" to Life Science metadatablock's Measurement Type field vocabulary

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#8655]
**What steps does it take to reproduce the issue?**

* When does this issue occur?
  When adding and editing dataset metadata fields in the Life Sciences metadatablock

* Which page(s) does it occurs on?
  Edit dataset page

* What happens?
  When choosing controlled vocabulary values from the Measurement Type field (studyAssayMeasurementType), the "cell counting" value is missing.

* To whom does it occur (all users, curators, superusers)?
  Curators and depositors

* What did you expect to happen?
  "cell counting" should be an option in the dropdown

**Which version of Dataverse are you using?**
  v5.10.1

**Any related open or closed issues to this bug report?**
https://github.com/IQSS/dataverse/pull/7278, where I think the value was accidentally removed during an unrelated change to the metadatablock

**Screenshots:**

"cell counting" is not an option of the Measurement Type field when adding or editing metadata on Demo Dataverse (v5.10.1)
<kbd><img width="954" alt="Screen Shot 2022-04-26 at 2 09 56 PM" src="https://user-images.githubusercontent.com/18374574/165364688-36d0e0f9-2e1d-499f-8d64-1f3a0ef79126.png"></kbd>

"cell counting" is an option of the Measurement Type field when adding or editing metadata on Harvard Dataverse Repository (v5.10.1)
<kbd><img width="921" alt="Screen Shot 2022-04-26 at 2 12 06 PM" src="https://user-images.githubusercontent.com/18374574/165366152-15dc5128-c3e1-4ba2-abaa-b9905787fc7f.png"></kbd>

**Comment by pdurbin** [comment]
Thanks, @jggautier. This becomes a problem for people reading the API Guide and trying to use the `dataset-create-new-all-default-fields.json` file to create a dataset: https://guides.dataverse.org/en/5.10.1/api/native-api.html#create-a-dataset-in-a-dataverse-collection

The dataset is not created and they see this error instead:

`{"status":"ERROR","message":"Error parsing Json: Value 'cell counting' does not exist in type 'studyAssayMeasurementType'"}`

It looks like "cell counting" was removed in ac71026, so Dataverse 5.1, as part of this pull request (as you said):

- #7278

I assume we should simply add "cell counting" back in.

It probably wouldn't be a bad idea to also add a test to exercise `dataset-create-new-all-default-fields.json` as well because it probably would have helped us catch this bug a lot sooner.

As you point out, installations older that 5.1 still have "cell counting". This is because the "reload metadata block" logic can add values but can't remove them.
