### ISSUE TITLE
Feature Request/Idea:  Dataverse External Tools Fail if Pop-ups are blocked which is easy to miss 

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse#8766]
The external tools mechanism in Dataverse attempts to pop tools up in a separate tab (This is not completely true for  previewers, a sub-type of external tool - we first take you to the datafile page with an embedded view (works without popups enabled), but the view in external window option on that page then tries to popup a new tab.) 

For this to succeed, the user must allow Dataverse to pop-up new Windows. While this isn't hard, it isn't obviously required and the only indicator that you haven't done this on some browsers is a tiny icon in the URL bar, e.g. 
![image](https://user-images.githubusercontent.com/6731983/171729654-564ec521-583a-4f34-9b3c-872832b38ab2.png)

This can cause new users of Dataverse to think external tools/previewers aren't working. 

It would be good to avoid this situation. There may be multiple possible solutions so a quick Spike to see which make sense (technically and UI-design-wise) could be helpful. Possible options include:

- replacing the Dataverse window rather than popping up a new one (does this work? will it work with the new mechanism to launch tools via POST that will be used by OpenDP?). 
- detecting that popups are blocked (is this possible?) and alerting the user (how? how detailed?), either at login or when attempting to use a tool, that they must enable that for the tool to work.
- ?

**Comment by mreekie** [comment]
relates to; Include Signed-urls in the External Tools Framework #7715

**Comment by mreekie** [comment]
Just an FYI that the user is made aware of issue in the [DP Creator Demo Beta Instructions](https://docs.google.com/document/u/1/d/e/2PACX-1vRlZ2IgigIhl4oz_uOakQPxovzlrmFkbD-x_9RUO31dC0eRq2wCt_vN2Go0_9LTRd67srjgy04CfPVk/pub) at the very end of section: "B. Start in Dataverse"


----
If your browser is not opening a new tab for the DP Creator application, it is likely because you have pop-ups blocked in your browser.  You need to unblock pop-ups in your browser.  For example, if you are using Chrome, you can unblock pop-ups by following [these instructions](https://www.google.com/url?q=https://support.google.com/chrome/answer/95472?hl%3Den%26co%3DGENIE.Platform%253DDesktop&sa=D&source=editors&ust=1654289552189282&usg=AOvVaw1CDM5mcrS3VoK6TDw_LVUn) and add [https://demo-dataverse.dpcreator.org/](https://www.google.com/url?q=https://demo-dataverse.dpcreator.org/&sa=D&source=editors&ust=1654289552189899&usg=AOvVaw0zHqkneCThr7yEseZME058) as a site allowed to send pop-ups and use redirects.

**Comment by qqmyers** [comment]
Looking into this briefly - it [looks like one can detect whether a popup opened correcty with some simple logic](https://thewebdev.info/2022/04/28/how-to-detect-if-a-browser-is-blocking-a-popup-with-javascript/) so I did a simple experiment to try changing the javascript we use to open previewers to 
```
const newWin = window.open(...); if (!newWin || newWin.closed || typeof newWin.closed == "undefined") {
  alert("You must enable popups to use previewers/explore tools");
}

```
in places like 
https://github.com/IQSS/dataverse/blob/a324b51679a23586c68387cc28b3d744732b443c/src/main/java/edu/harvard/iq/dataverse/FileDownloadServiceBean.java#L318

and 

https://github.com/IQSS/dataverse/blob/a324b51679a23586c68387cc28b3d744732b443c/src/main/java/edu/harvard/iq/dataverse/DatasetPage.java#L5635

and it appears to work. Presumably we'd want a Dataverse dialog box or a warning label, etc. and to internationalize the text rather than using a modal alert(), but assuming this works across browsers (as it is supposed to), this should be a relatively straight-forward dev task once the UI design is clear (e.g. dialog or warning bar, etc.).

**Comment by mreekie** [comment]
This allows a warning on the page.
Small.

**Comment by pdurbin** [comment]
I had a quick play with the solution from @qqmyers above and it looks promising!

![Screen Shot 2022-07-25 at 5 00 57 PM](https://user-images.githubusercontent.com/21006/180873387-c346b365-d33e-4334-bb5d-20465df1907a.png)
