### ISSUE TITLE
Expand the suite of automated tests of the Harvesting functionality

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#8843]
A followup issue for #8372 (PR #8753).
The existing restassured tests are fairly primitive. We need tests covering all the OAI functionality we provide.

**Comment by pdurbin** [comment]
Obviously, there are lots of tests we could write. This might be a good one:

- #8739

**Comment by pdurbin** [comment]
@landreev added some tests in this PR:

- #9174

The idea of this issue is to add more tests to cover all the harvesting functionality. I'm not sure exactly how much time this will take so I'd suggest we timebox it to a full sprint (2 weeks) for a single developer (maybe @landreev but any of us could jump in) to see how much can get done. Giving it an 80.

Review and QA should be light. As long as the tests pass, we should be good.

I don't believe we have a good way of checking code coverage for API tests like this (red/green per line).

**Comment by mreekie** [comment]
Working out a PR today.
There will be more review than QA.
Should be able to wrap up by the end of the sprint
