### ISSUE TITLE
Can not create a dataset via API

### ISSUE THREAD

**Issue by sergejzr** [IQSS/dataverse#9143]
**What steps does it take to reproduce the issue?**
Dear Dataverse developers,
I get errors when executing the example for creating a dataset provided in tutorial[1]: 
I am using the suggested command and the demo file [2] 
````
curl -H 'X-Dataverse-key:b23-456-456-45-mysecrettoken-0e09f167e2' -X POST "https://localhost/api/dataverses/root/datasets" --upload-file "dataset-finch1.json" -H 'Content-type:application/json'
````
I get following error response:
````
{"status":"ERROR","code":400,"message":"Bad Request. The API request cannot be completed with the parameters supplied. Please check your code for typos, or consult our API guide at http://guides.dataverse.org.","requestUrl":"http://localhost:8080/api/v1/dataverses/root/datasets","requestMethod":"POST"}
````
and the server log (also attached as a file with FINEST log level)
````
javax.ejb.EJBException: Specified metadatalanguage ( metadataLanguage, http://schema.org/inLanguage) not allowed in this collection.
````

I tried many times with different parameters and different tutorials. The problem does always occur. I guess it is a bug.

[1]https://guides.dataverse.org/en/latest/api/native-api.html#id43
[2]https://guides.dataverse.org/en/latest/_downloads/fc56af1c414df69fd4721ce3629f0c03/dataset-finch1.json

* When does this issue occur?
always when executing the API request

* Which page(s) does it occurs on?
I did not notice problems with other API requests

**Which version of Dataverse are you using?**

5.12

*

[stacktrace.log](https://github.com/IQSS/dataverse/files/9942346/stacktrace.log)

**Comment by qqmyers** [comment]
There could be a bug but it may also be a valid response: if your administrator has defined which metadatalanguage(s) are allowed in a given collection, any dataset created by API has to include a term matching one of the allowed ones, as in the second example[1] of the Create a Dataset in a Dataverse Collection[2] of the guides which sets this to French. (A submission without a metadatalanguage specified when the collection requires one is a 400 Bad Request by design.)

If you try uploading to demo.dataverse.org, which doesn't have metadatalanguage set and have a problem, we can check into it being a bug.

Taking a quick look, I don’t know that there is a way to see which language(s) are allowed in a collection via the API, so you may have to ask someone or look in the UI – if a metadatalanguage(s) is set, opening the create dataset form will either show the one value or give you an input to select from the choices. The API uses the two-letter code for the language you want. (Feel free to open an issue to add the metadatalanguage options to the API – perhaps as part of the view dataset call.).

[1] https://guides.dataverse.org/en/latest/_downloads/a6c9eedc6d8961b6c5c801aa0126e69d/dataset-finch1_fr.json
[2] https://guides.dataverse.org/en/latest/api/native-api.html#create-a-dataset-in-a-dataverse-collection

**Comment by sergejzr** [comment]
Thank you very much! This was exactly the problem.
In our dataverse the Metadatalanguage is set to "Choosen at Dataset Creation", but I there is no metadatalanguage identified in the example json file.
I wish the error message would be more clear in the logs, something like  "dataset requires a metadatalanguage to be set to:..."
And also, probably, the tutorial should remove the json without the metadatalanguage set, if this is anyway a mandatory option..

Anyway, thank you once again, and sorry that I wrongly identified the issue as a bug.

**Comment by qqmyers** [comment]
Glad it was simple. metadatalanguage isn't required unless your admin has turned that on so the guides example does work for the standard case. Pull requests for clearer language in the guides is always welcome - not always clear to someone who just wrote the code what will/won't be clear to other people.
