### ISSUE TITLE
S3 logging without credentials

### ISSUE THREAD

**Issue by orazionelson** [IQSS/dataverse#9205]
Hello,
I'm using dataverse 5.10 and I can't upload files to S3 without credentials file and  by just defining an AWS-IAM role.

It is possible to upload only creating an AWS-IAM user with credentials (API key + secret) and adding credentials file to  the .aws directory in dataverse user home.

The problem would be solved by adding to the file: S3AccessIO.java
 
the AWS class: **InstanceProfileCredentialsProvider**

In the poviderChain at this line:

`AWSCredentialsProviderChain providerChain = new AWSCredentialsProviderChain(profileCredentials, staticCredentials);`

(line 1196 of the develop branch)

Is it enough? 

Is it possible to add the feature?

Thanks,
Alfredo

**Comment by qqmyers** [comment]
I'm not sure I understand. Profile credentials are loaded on https://github.com/IQSS/dataverse/blob/bf2e4267b248b548aa2cb02b30419915a7432fed/src/main/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIO.java#L1185 and having a credential file in the ~/.aws should work, without having to define static credentails. (The only time I've had a problem is when I accidentally start Payara as the wrong user.)

**Comment by qqmyers** [comment]
After a side conversation with @donsizemore, I think I understand better - you're interested in using role-based access/no credentials file. That is managed by the InstanceProfileCredentialsProvider which we'd need to add to the credentials chain - as you indicate.

Do you know if this used to work, i.e. prior to v5.10? It seems to me that before https://github.com/IQSS/dataverse/commit/d038f85c94583a9b8fcf3c00008e9316f2b3919c we were just creating a standard AWSClient which I think would have supported role or credential file access. That's not too important, it would just mean we're restoring a capability that was accidentally dropped rather than adding something we never had.

**Comment by orazionelson** [comment]
As @abollini said me this feature was in dataverse before the 4.20

**Comment by kcondon** [comment]
Hi @orazionelson ,
There is a fix we are testing here: https://github.com/IQSS/dataverse/pull/9206 , if you would like to try it.
