### ISSUE TITLE
Bug: Fix dataset creation in the payara 6 branch

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse#9214]
Decomposed from: 
- [PR 9116](https://github.com/IQSS/dataverse/pull/9116) 

This is exploratory work.
It requires investigation, then code work.
The logic works. In the best case the work here is correcting an incompatibility.

You can create datasets in the API, as the API test suite passes.
This issue is located around JSF (UI).
Could this be that we are an old version of JSF or Jakarta compatibility?

**Comment by mreekie** [comment]
added to sprint Dec 15, 2022

**Comment by landreev** [comment]
Just to clarify, dataset creation through the UI was in fact working. It's the dataset page in View mode that is broken in the Payara 6 branch. So the page bombs when the user is redirected to view the newly-created dataset. It bombs the exact same way if you attempt to view a dataset created via the API. 
The error occurs in the dataset-citation fragment, everything else on the page appears to be working. (i.e., the page is functioning ok with dataset-citation.xhtml commented out). 
The actual exception is a strange jsf error in rendering of the citation download dropdown. (Will explain).

**Comment by landreev** [comment]
So if anyone is curious, the part that's bombing is this dropdown menu for downloading the dataset citation in different formats: 
```
<li>
   <a jsf:id="endNoteLink" jsf:action="#{DatasetPage.fileDownloadService.downloadDatasetCitationXML(DatasetPage.dataset)}" >
      #{bundle['dataset.cite.downloadBtn.xml']}
   </a>
</li>
etc.
```
what happens is that instead of rendering the download link, jsf now tries to actually *execute* the method, and that results in an exception and a 500 when the method tries to grab the output stream which is already in use by the page itself. The only other place in the application where we are using the same notation - `<a ...` in combination with `jsf:action=...` (or `jsf:actionListener=...`) is for a similar citation download dropdown on the file page (failing there in the same way). 
I thought simply rewriting the above as 

```
<li>
   <p:commandLink id="endNoteLink" styleClass="btn-download" process="@this"> 
      <f:actionListener binding="#{fileDownloadService.downloadDatasetCitationXML(DatasetPage.dataset)}"/>
         #{bundle['dataset.cite.downloadBtn.xml']}
   </a>
</li>
```
was a straightforward workaround (this is how it's implemented in the file download dropdown, which is working). But this only works in a sense that the page is no longer bombing; but then nothing happens when clicking on the link. The difference with the file download links is those result in a redirect to the download api, while the citation download methods just want to write they output stream to the client directly.  I'll figure it out.

**Comment by qqmyers** [comment]
An interesting change in behavior! Given that we want API calls for everything, would just writing those api calls now be the easiest ~fix for this?

**Comment by landreev** [comment]
Yes, it did cross my mind that it could be useful to just make APIs for these citations. 
I'm still curious about how to get it to work; it is a perfectly legit use case, needing to generate some content dynamically for the user to be able to download without leaving the page. (trying to remember/find any other places where we are doing this)

**Comment by landreev** [comment]
(I'm assuming `<p:fileDownload ...>` would be the proper way to implement this dynamic download in the ui; but yes, rather than getting that to work, I think I'll just go ahead and add the API(s) for citations)

**Comment by landreev** [comment]
Actually, the page is only bombing when the download method is referenced like this:
```
jsf:action="#{DatasetPage.fileDownloadService.downloadDatasetCitationXML(DatasetPage.dataset)}"
```
i.e., note the `DatasetPage.` part there. We have the `getFiledownloadService()` method in DatasetPage.jave; but it's redundant. If you change it to 
```
{fileDownloadService.downloadDatasetCitationXML(DatasetPage.dataset)}"
```
the page stops crashing; but download isn't working still. So yeah, some change in behavior has occurred; with some extra confusion on the part of jsf.

**Comment by poikilotherm** [comment]
Is there a particular reason not to use the [Primefaces File Download Links](https://www.primefaces.org/showcase/ui/file/download.xhtml?jfwid=06d43)?

**Comment by landreev** [comment]
Yes, `p:fileDownload` is the official/supported way to handle dynamic downloads in Primefaces. (I added comments about doing it with `p:fileDownload` and other things here yesterday; but deleted it all since, because I felt like the issue was being polluted with too much idle talk). 
But yes, having looked into this a bit, it's not clear at all why the hack-ish `<a action="...">` solution is still working at all in the main branch.

**Comment by poikilotherm** [comment]
I tried to find out why these annotations work at all, as they are meant to be used with `h:commandLink` et al...

Hard to google for or look at SO. Probably this has been a bug in implementations before or was something that worked because of Java Server Pages being a part of Jakarta Faces before?

The code itself isn't even consistent with `action` in the top one and `actionListener` in the others. Anyway, the code is from 2016 and pre-Payara-5, so probably it's a good idea to cleanup the messy code (the Primefaces API to create the streams is pretty good to read and less hacky than our approach...)

**Comment by poikilotherm** [comment]
Wait a sec - wouldn't it be possible to just migrate the existing methods in the existing bean?
