### ISSUE TITLE
Feature Request/Idea: Make Series repeatable

### ISSUE THREAD

**Issue by philippconzett** [IQSS/dataverse#9255]
**Overview of the Feature Request**
Makes the metadata field Series in the Citation Metadata block repeatable.

**What kind of user is the feature intended for?**
API User, Curator, Depositor, Guest, Superuser, Sysadmin

**What inspired the request?**
Data contained in a dataset may belong to multiple series. Making the field Series repeatable will make it possible to reflect this fact in the dataset metadata.

**What existing behavior do you want changed?**
The field not being repeatable.

**Any brand new behavior do you want to add to Dataverse?**
No. Other, similar fields are already repeatable, e.g., Keyword.

**Any related open or closed issues to this feature request?**
No.

**Comment by jggautier** [comment]
@sekmiller found that when dataset metadata is exported in the RIS format, Series Name mapped to Tertiary Title (T3).

```
Provider: Demo Dataverse
Content: text/plain; charset="utf-8"
TY  - DATA
T1  - Testing
T3  - Series name
AU  - Finch, Fiona
...
```

When RIS files are imported into some reference managers, the value of Tertiary Title (T3) is imported as the reference's Series name. So it seems intentional that we're mapping Series Name to the RIS field's Tertiary Title (T3), since some reference managers interpret Tertiary Title (T3) as the Series name.

Here's how it looks when I export a dataset with a Series name and import that RIS file into Endnote web:

<kbd><img width="1361" alt="Screenshot 2023-03-27 at 12 04 49 PM" src="https://user-images.githubusercontent.com/18374574/227998806-b726605a-08bc-4e30-b3d1-d7b615a35184.png"></kbd>

When importing the RIS file into Zotero's desktop app, the value of Tertiary Title (T3) isn't imported. I haven't checked RefWorks. (My [crosswalk](https://docs.google.com/spreadsheets/d/1ZW5-KmKk5dJWZAD12m7xc1i11xtEY_4vCvTVK72bG38) says it also isn't imported, but that crosswalk's over 5 years old.)

@adam3smith, since you've worked on the RIS exports, would you know if the folks maintaining reference managers like Zotero and EndNote expect multiple series names? Or do they expect that each referenced resource would belong to just one series?

To try to guess this, in the RIS file that Dataverse creates, if I add more Tertiary Title (T3) entries...

```
Provider: Demo Dataverse
Content: text/plain; charset="utf-8"
TY  - DATA
T1  - Testing
T3  - Series name1
T3  - Series name2
T3  - Series name3
AU  - Finch, Fiona
...
```

... and import that into Endnote web, it puts all of the values into the same Series Name field with line breaks:

<kbd><img width="1051" alt="Screenshot 2023-03-27 at 12 13 00 PM" src="https://user-images.githubusercontent.com/18374574/228000705-784b8ead-6b5b-4809-8c17-e36213db106b.png"></kbd>

That's how the UI also handles the display of "Investigators", by putting multiple author/creator names into the same textbox, field, but the field label for that Investigators is plural, while the field label for series is Series Title, singular. So I wonder if Endnote expects only one series name.

**Comment by jggautier** [comment]
Just an update on this. It was decided that when a dataset depositor adds multiple Series Names, in that dataset's RIS citation file, those Series names are included in separate T3 tags, like this:

```
Provider: Demo Dataverse
Content: text/plain; charset="utf-8"
TY  - DATA
T1  - Testing
T3  - Series name1
T3  - Series name2
T3  - Series name3
AU  - Finch, Fiona
```
