### ISSUE TITLE
Feature Request/Idea:Implement mechanism to support integration with OntoPortal

### ISSUE THREAD

**Issue by jonquet** [IQSS/dataverse#9276]
**Overview of the Feature Request**

This issue is a connection to the correspondent issue in the OntoPortal repo: https://github.com/ontoportal/ontoportal-project/issues/16

We would like a way to ease the selection of vocabulary/ontology term in Dataverse using OntoPortal instances. 
(e.g., BioPortal or AgroPortal)
For the moment the current interface requires 4 fields (example from DataINRAE):

![image](https://user-images.githubusercontent.com/7379183/211806905-c6749469-b89f-4417-86ef-9da890dbc46e.png)

In [Data INRAE](https://entrepot.recherche.data.gouv.fr/dataverse/inrae) we can replace the fields above with only one, the concept search below:

<img width="484" alt="image" src="https://user-images.githubusercontent.com/7379183/211807828-803c2a8b-2839-4e79-80db-0d799f674e59.png">

**What existing behavior do you want changed?**

- [ ] Implement a mechanism to change the 4 fields above by only one field with autocompletion with selected vocabularies hosted in an OntoPortal instance
- [ ] Implement a mechanism to call the correspondant OntoPortal Annotator on the title/abstract fields of the dataset to pre-propose some ontology/vocabulary terms in the UI that the user can only keep or discard.

**What kind of user is the feature intended for?**
Depositor
The key idea is to ease depositon going from n*4 fields for n terms to only one field with autocompletion

**What inspired the request?**
Tons of request for this. 
This is being done in the context of Horizon Europe project FAIR-IMPACT T4.5

**Any related open or closed issues to this feature request?**
https://github.com/ontoportal/ontoportal-project/issues/16

**Comment by jonquet** [comment]
Colleagues on OntoPortal side: @syphax-bouazzouni and Dataverse (at INRAE side) @DS-INRA

**Comment by qqmyers** [comment]
I'd suggest developing an [external vocabulary script ](https://github.com/gdcc/dataverse-external-vocab-support)for this. The compoundDemo field in the examples there seems to be close to what you want - retrieving values from a Skosmos server rather than OntoPortal but it shows the user one field and fills in the four required by Dataverse.

**Comment by luddaniel** [comment]
Hi everyone, as we started to work on implementing Ontoportal support for external controlled vocabulary, we wanted to start a list of points that was need to face to successed.

- [ ] Having the capability to use an apikey on backend side (`registerExternalTerm` function) 
Handling 2 service urls for api search and user interface exploration 
Both under PR #10145
- [ ] Create a POC on [dataverse-external-vocab-support](https://github.com/gdcc/dataverse-external-vocab-support) for Javascript implentation : Done here [poc_ontoportal branch](https://github.com/gdcc/dataverse-external-vocab-support/compare/main...Recherche-Data-Gouv:dataverse-external-vocab-support:poc_ontoportal)
- [ ] Finalize `ontoportal.js` : 
- the POC does not display each vocabularies (aka. ontologies) maybe be we should make this configurable (either select an ontology before search or search on all configured ontologies)
- allow to not use term search by allowing to type on each of child fields of `keyword` (a bit more complexe than `"allow-free-text": true`)
- [ ] Handling languages of Ontoportal API : complicated to estimate at the moment because Ontoportal software are just starting to deploy lang metadata in API results 
- [ ] Indexing in SOLR documents synonyms and terms of all languages : 
On Dataverse v5.12.1 it was possible to just add a `retrieval-filtering` field in `cvoc.json` but since PR #9402 (v5.14) only 2 fields are indexed (`key.equals("termName") || key.equals("personName")`). 
An idea would be to enlarge the indexing support using a attribute like [`"indexed": true`](https://github.com/Recherche-Data-Gouv/dataverse-external-vocab-support/blob/poc_ontoportal/examples/config/cvoc-agroportal-ontoportal-conf.json#L59C1-L60C1). 
It is complicated to make the code generic here because Ontoportal unlike Skomos does not have at the moment a JSON Object with `value` and `lang` attribute for each terms. 
- [ ] Not mandatory for this feature, but it would be great to think about what is shared inside export format of the dataset's metadata.
- Import subject : what will happen of CVOC feature under SPA Dataverse architecture ?

**Comment by pdurbin** [comment]
> Import subject : what will happen of CVOC feature under SPA Dataverse architecture ?

I [checked](https://iqss.slack.com/archives/C04MJ76A34Z/p1701203803358159) with @GPortas. @DS-INRA please go ahead and create an issue at https://github.com/IQSS/dataverse-frontend when you get a chance. I'm sure @4tikhonov (and many others) will be interested! 😄

**Comment by qqmyers** [comment]
With #10145, #10331, #10371, and #10503, #10404, #10505, #10603 all merged, can #9276 now close?

**Comment by pdurbin** [comment]
Sure, sounds good. Closing! I added the 6.3 milestone to this issue.
