### ISSUE TITLE
Submit for review workflow: when a collection admin "returns" a dataset to an author, the default notification email (see attached) received by the author should contain the email address of the collection admin and not the email address of the Dataverse repository

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#9296]
-->

**Overview of the Feature Request
The "Return to author" notification email includes the email address of the repository. Instead, the email should include the email address of the admin of the collection admin.

**What kind of user is the feature intended for?**
Depositor, Superuser, Collection admin

**What inspired the request?**
Because the email that dataset authors get includes the email address of the Harvard Dataverse Repository, dataset authors email Harvard Dataverse Repository admins, when they should be emailing the admins of the collection that returned the dataset.

**What existing behavior do you want changed?**
The email address included in the "return to author" is the email address of the collection admin instead of the email of the Dataverse repository.

<img width="2040" alt="Screen Shot 2023-01-17 at 4 41 42 PM" src="https://user-images.githubusercontent.com/8322346/213021989-2a45d939-1d38-47d3-bc17-be77db787c95.png">

**Comment by cmbz** [comment]
2023/10/02: This needs more investigation. @sbarbosadataverse and @jggautier will attempt to recreate the problem and share their findings. @scolapasta will provide insight about the notifications systems that might help clarify the nature of the behavior.

**Comment by scolapasta** [comment]
A few notes:
• we can look into adding an email for the user to respond to in the text of the message. Not sure how easy that will be, because there could be multiple curators? need to see if we can add email at the time the send back happens from the user who performed that action. We could move this issue forward as a spike to see if that's possible.
• the installation email is part of the generic footer that we put on all notifications, so I think should stay there.
• this may also get "better" with tools like Easy Review that may have a separate communication pathway from reviewer to author? @JR-1991 any thoughts on this?

**Comment by cmbz** [comment]
2023/10/16
- @jggautier will test on demo to see if he can recreate the behavior.

**Comment by cmbz** [comment]
**2023/10/16:**
- Example of an RT ticket that demonstrates this problem: https://help.hmdc.harvard.edu/Ticket/Display.html?id=349456
