### ISSUE TITLE
API: Update API documentation, particularly native API for testing

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#930]
The native api doc is out of date so it is hard to know whether failures are due to a bug or changes in the API.

**Comment by michbarsinai** [comment]
Entire readme.md doc updated.

**Comment by eaquigley** [comment]
@michbarsinai Can you please move this into API guides? Link to see guides: http://guides.dataverse.org/en/latest/api/index.html Link to add guides: https://github.com/IQSS/dataverse/tree/master/doc/sphinx-guides/source/api

**Comment by michbarsinai** [comment]
Moved the doc to Sphinx.

**Comment by pdurbin** [comment]
http://guides.dataverse.org/en/latest/api/native-api.html is looking good! As part of #915 however, we should probably drop "native-api" from the URL and split it into the names we agreed to in this spreadsheet: https://docs.google.com/a/harvard.edu/spreadsheets/d/12yN3otyqXPQ4uM_iYife7xSwr1PdtoZzazanDgBDqCI/edit?usp=sharing

As part of this, we decided to have "sword" in the URL rather than "data-deposit", for example. And to have a separate page for the Search API.

**Comment by kcondon** [comment]
@michbarsinai Thanks for updating, will check it out. One small thing: all commands show http but we are enforcing https, correct?

**Comment by michbarsinai** [comment]
Dunno. I'm not enforcing it, maybe at some higher level (Apache? Glassfish?) someone does. It's probably a good idea.

**Comment by kcondon** [comment]
Documentation has been updated and moved to guides. Will open a separate ticket to retest APIs. Closing.
