### ISSUE TITLE
Datafile DOI predictable before publication?

### ISSUE THREAD

**Issue by lmaylein** [IQSS/dataverse#9343]
For us, it is a very important feature that the DOI of a dataset is known before publication. For example, the DOI is often already included in advance in an associated text publication.
We would like to see the same for the file DOIs. How are the file DOIs formed? Is the trailing part of the DOI (extension of the dataset DOI) predictable or is it randomly determined at the moment of publication/DOI registration?
I had hoped to already see the DOI of not yet published files in the dvobject table. However, the DOI is apparently added here with the registration.

**Comment by qqmyers** [comment]
FWIW, I wrote #7334 to reserve the file PIDs but the concern at the time was that this may slow uploads unacceptably. I'm not sure if that was ever tested. Otherwise file DOIs would not usually be predictable - there are some options (using sequential numbering, using a db method) that could be predictable though.

**Comment by lmaylein** [comment]
Sorry. I had actually forgotten that I had asked the question before.
