### ISSUE TITLE
Analyze Dataverse application containerization for development

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse#9415]
## Overview of the Feature Request
This issue is created within the scope of IQSS/dataverse#9423.

Since there are already approaches and ongoing work for Dataverse application containerization, the goal of this issue is to analyze the existing resources and achievements, which can be useful for creating the Dataverse development container needed for IQSS/dataverse#9423 and to complement IQSS/dataverse#9414.

## What kind of user is the feature intended for?
Developers

## What inspired the request?
- Working on IQSS/dataverse#9423
- Standup discussions

## What existing behavior do you want changed?
N/A

## Any brand new behavior do you want to add to Dataverse?
No, should be the same.

## Any related open or closed issues to this feature request?
- IQSS/dataverse#9423
- IQSS/dataverse#9414

**Comment by pdurbin** [comment]
I believe the place to start is 83cb5b3 by @poikilotherm from this branch: https://github.com/IQSS/dataverse/compare/develop...poikilotherm:dataverse:8934-ct-dv-image

The big task is to figure out the bootstrapping. For a regular dev environment, we run the installer.

https://github.com/IQSS/dataverse-docker by @4tikhonov is another obvious place to look for inspiration.

On a related note, I tried out this pull request by @GPortas last night and it works great for running dependencies like PostgreSQL, Solr, and an SMTP server for dev:

- #9417

I wrote up my findings here: https://github.com/IQSS/dataverse/issues/9353#issuecomment-1451101241

I mention this because it might make sense to start a new branch from @GPortas 's branch and they cherry-pick the commit above by @poikilotherm and keep hacking from there. That way all the containers for dev are in the same branch.

**Comment by pdurbin** [comment]
I just sent the save the date:

Save the date! March 21 kickoff of Containerization Working Group (Docker, Kubernetes, etc.) - https://groups.google.com/g/dataverse-community/c/Wlxo7xDf0i0/m/PQQ6ccErDQAJ

I think we can close this and take it off the board now but let me check with @GPortas first.

**Comment by pdurbin** [comment]
@GPortas pointed out that he and @poikilotherm wrote a containerization strategy doc the other day that I nearly forgot about: https://docs.google.com/document/d/15-sqdKzpCgQBtaPaAGYMaqcxsQXmt-2CwAVNPmmAPRY/edit?usp=sharing

The containerization working group will definitely use that doc as a resource as it works on its proposal, which I stubbed out here: https://docs.google.com/document/d/14DHDB24Cp_kzpYqhHCKCtnzOw8_WuLOOONyqJHSsaYM/edit?usp=sharing

Now that the kickoff has been announced, I'm taking this issue off the board. I'm not closing it yet, however, because this PR from @poikilotherm is marked to close it:

- #9424

**Comment by pdurbin** [comment]
Closing. As discussed at standup, we've done enough analysis to make the next step, which is this PR:

- #9439
