### ISSUE TITLE
Publishing fails, even after fixing the initial error.

### ISSUE THREAD

**Issue by lmaylein** [IQSS/dataverse#9419]
Due to a hardware error where a file could not be read, the publishing of a dataset failed yesterday. This error is fixed and the checksums of all involved files are correct now. However, the publishing of a record still fails. What do I have to do so that the record can be published?

`[2023-03-02T13:56:11.443+0100] [Payara 5.2022.3] [SEVERE] [] [edu.harvard.iq.dataverse.DatasetPage] [tid: _ThreadID=108 _ThreadName=http-thread-pool::jk-connector(3)] [timeMillis: 1677761771443] [levelValue: 1000] [[`
`  This dataset cannot be published because some files have been found missing or corrupted. . Please contact support to address this.]]`

Software version: 5.12.1

**Comment by qqmyers** [comment]
Hmm. There's an admin api call that may help give more information - see https://guides.dataverse.org/en/latest/api/native-api.html#physical-files-validation-in-a-dataset .

**Comment by qqmyers** [comment]
Ah - it looks like that non-obvious message is sent because the dataset still has a FileValidationLock: https://github.com/IQSS/dataverse/blob/1a797171cdb73741b5da4a683f38697558349b5c/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/PublishDatasetCommand.java#L216-L219 - removing that lock. https://guides.dataverse.org/en/latest/admin/troubleshooting.html?highlight=lock#a-dataset-is-locked-and-cannot-be-edited-or-published talks about this in general. Removing the lock can be done via API: https://guides.dataverse.org/en/latest/api/native-api.html#manage-locks-on-a-specific-dataset.

**Comment by lmaylein** [comment]
It worked. Thank you very much.
