### ISSUE TITLE
Shibboleth: Author name field in dataset not prepopulated when using shib account

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#945]
When creating a dataset with a shib account, eg. alterego, author name field is not prepopulated.

**Comment by pdurbin** [comment]
Yeah, DatasetPage.java is sort of cheating in the sense that it relies on **builtin** users rather than Shibboleth users. There's a comment that says "Get builtin user to supply default values for contact email author name, etc."

See also my comment about how I believe the authenticated user table needs to change: https://github.com/IQSS/dataverse/issues/457#issuecomment-66558549

@scolapasta and I discussed this the other day and how #965 is related.

**Comment by kcondon** [comment]
Works, closing.
