### ISSUE TITLE
Metrics API downloads problem

### ISSUE THREAD

**Issue by sirineREKIK** [IQSS/dataverse#9536]
Hello,

We detected a bug at Metrics API:
The result is the same for these two api calls: (count:35523)
1/ curl -s https://demo.dataverse.org/api/info/metrics/downloads | jq -r .data.count 
2/ curl -s https://demo.dataverse.org/api/info/metrics/downloads?parentAlias=csvconfv723 | jq -r .data.count
--> It is like the ‘parentAlias’ is not working good.
For the scenario we used this dataset for test: https://demo.dataverse.org/dataverse/csvconfv723

When investigating the code, we found that the SQL Query is missing parenthesis in the condition, and we think that is the origin of the problem: 
Class: MetricsServiceBean
Method: downloadsToMonth(..)
Query: select count(id) from guestbookresponse where date_trunc('month', responsetime) <=  to_date('" + yyyymm + "','YYYY-MM') or responsetime is NULL .......

**--> We propose that you add () to the query that become:** 
select count(id) from guestbookresponse where ( date_trunc('month', responsetime) <=  to_date('" + yyyymm + "','YYYY-MM') or responsetime is NULL ) .......

**Comment by qqmyers** [comment]
Good catch! I can confirm at QDR that the query is wrong as you indicate - 'and' takes precedence over the 'or' in the where clause. I checked the other metrics queries and don't see any others affected by this.

Are you interested in making a pull request with the fix? If so, please do. Otherwise, let me know and I can submit the fix.

Thanks!

**Comment by sirineREKIK** [comment]
It's done for the PR : (https://github.com/sirineREKIK/dataverse/tree/9536_metrics_api_download)
Is it ok for you ?
