### ISSUE TITLE
CSV File Ingest Failed

### ISSUE THREAD

**Issue by sirineREKIK** [IQSS/dataverse#9583]
Regarding: Dataverse v 5.12.1

An error occured in logs when trying to ingest the **CSV file :**   [Infos_Gwell.csv](https://github.com/IQSS/dataverse/files/11439293/Infos_Gwell.csv)
Ingest produced tabular data, but failed to save it in the database.
**log file :** [ingest_bdd_error.log](https://github.com/IQSS/dataverse/files/11439294/ingest_bdd_error.log)

**Comment by pdurbin** [comment]
@sirineREKIK thanks, I'm just pulling out the exception

Internal Exception: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(255)
Error Code: 0
Call: INSERT INTO DATAVARIABLE (FACTOR, FILEENDPOSITION, FILEORDER, FILESTARTPOSITION, FORMAT, FORMATCATEGORY, INTERVAL, LABEL, NAME, NUMBEROFDECIMALPOINTS, ORDEREDFACTOR, RECORDSEGMENTNUMBER, TYPE, UNF, WEIGHTED, DATATABLE_ID) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)

I don't think it's this issue:

- #7386

(A header is present and all values are under 255 according to `head -1 Infos_Gwell.csv | tr \; "\n" | while read i; do echo $i | wc -c; done`)

Maybe it's the semicolons:

- #8990

@sirineREKIK do you want to try it again with commas (or tabs) instead of semicolons? Just to see what happens?

**Comment by sirineREKIK** [comment]
@pdurbin 
Yes it seems good when replacing semicolons with commas, no exception was reported.

**Comment by pdurbin** [comment]
@sirineREKIK thanks, closing in favor of this issue:

- #8990
