### ISSUE TITLE
Enable configure option for dataset external tool

### ISSUE THREAD

**Issue by raravumich** [IQSS/dataverse#9589]
Hello Team

We(ICPSR @ University of Michigan) are working on getting an external tool built for Dataverse that enables users to run a metadata health check for the dataset they create. 
This tool allows the user to look at suggestions/recommendations and some point make api calls to dataverse to persist the changes the user accepts.
Basically this is a configure option for a dataset, which I believe is currently not enabled.
Please help us in understanding if this option would be enable in the near future or if it is enabled per use case.

Regards
Raghunath Ravi
Technical Lead
Team TurboCurator
CNS - ICPSR 
University Of Michigan

**Comment by qqmyers** [comment]
@raravumich - Thanks for the issue. I'm not aware of any activity on this right now but others may know more. 

I don't think this should be a blocker w.r.t. development for you though - the main difference between explore and configure tools is that configure tools only show when you have write permissions on the dataset/datafile. An explore tool can still get the user's api key or signed URLs (needed to get read access to restricted content that user can access but also usable to get write access.) So if you configure as an Explore tool for Datasets, you can still write if the user can. The problem for production is that users without write access to the dataset will still see the tool (which you may want here if you want to provide a read-only summary publicly?) and you'd have to turn off write functionality/handle permission issues/explain why they can't do writes, etc. in your tool.

FWIW: Given that the difference is mostly about when tools are shown, I don't think the dev work in Dataverse to add dataset-level config tools is that big either.

Another thing that could be fixed is to make dataset-level explore tools visible when there are no files in a dataset (perhaps optionally if tools can work when no files exist). The rule that one file is needed now is mostly because the whole Access Dataset menu where the tools get listed is also where download options show and the menu as a whole is only showing when there are files because of that. Until then, if you use explore during development, you'll have to remember a file is needed for the menu listing your tool to appear.

**Comment by pdurbin** [comment]
> I don't think the dev work in Dataverse to add dataset-level config tools is that big either.

Me neither. I'm giving this a size of 3.

**Comment by a2mshen** [comment]
Hello Team,

I'm Mei from ICPSR, Raghu is on vacation, but we'd like to follow up on the issue.  Is there any updates on it?

Thank you,
Mei Shen
Team TurboCurator
CNS - ICPSR
University Of Michigan

**Comment by pdurbin** [comment]
@a2mshen hi! No updates. This issue hasn't been prioritized. @siacus @cmbz @scolapasta here are the notes from when @qqmyers @landreev and I met with ICPSR in late April: https://docs.google.com/document/d/1zMnO64hJQv89QodtLZMUE-uS6VikM37a22mE4rsMvWs/edit?usp=sharing

**Comment by a2mshen** [comment]
Good morning Team!

If there is no updates, could you provide an estimate about it?  Really appreciate your help @pdurbin , @siacus, @cmbz , @scolapasta !  :)

Thank you!
Mei Shen
CNS - ICPSR
University Of Michigan

**Comment by cmbz** [comment]
I've added the issue to the Global Backlog in the community column. @pdurbin please arrange the cards as desired. I will raise it at the 7/31 prioritization meeting.

**Comment by pdurbin** [comment]
@cmbz thanks! I just moved it to the number 3 spot:

![Screen Shot 2023-07-26 at 4 19 54 PM](https://github.com/IQSS/dataverse/assets/21006/d246b345-2404-470e-825b-0d887f238ede)

As I explain at https://github.com/IQSS/dataverse.org/issues/68 I've been heavily prioritizing pull requests over issues but because this issue is small (I think), why not! 😄 

If anyone out there wants to create a pull request, please get in touch! You may draw inspiration from this pull request created just today:

- #9737

**Comment by cmbz** [comment]
Please review again, resizing may be needed.

**Comment by a2mshen** [comment]
thank you @pdurbin @cmbz !!

**Comment by qqmyers** [comment]
@raravumich  - issues are usually used to track work on this project. 

W.r.t. this one - is there a need for both solutions - its clear that there needs to be a way to launch a dataset-level tool when there are no files and either adding a config-tool option or allowing explore tools to appear when no files exist would solve that. Do we need both now? Adding dataset-level config tools would enable a read/write tool. Would you also want to display something to people who don't have write permission on the dataset (that would suggest the explore-tools-with-no-files fix)? If so, are you planning two tools - one for editing and one for public display (might need both solutions)? Or just one tool (which could then be an explore tool that shows more functionality if you have write permissions)?

If both solutions are needed now, I guess another issue would make sense (cross-referencing), since they could be developed separately. If you just need to enable explore tools when no files exists, I'd suggest adapting this issue.

Are you approaching production-release of your tool? As I mentioned, it should be easy to test/demo your tool without this issue being fixed, so knowing your schedule could help IQSS prioritize this.

**Comment by pdurbin** [comment]
@raravumich @a2mshen I just made a pull request:

- #9925

Please comment there. Oh, and I included a screenshot for you. Have a great weekend!
