### ISSUE TITLE
AGROVOC for keyword

### ISSUE THREAD

**Issue by ReisQuarteu** [IQSS/dataverse#9604]
'skosterm' is not a datasetField name of a field defined in a metadata block file. Can the 'skosterm' field-name be replaced by 'keyword' or the 'keyword' field must be be hidden and 'skosterm' must be used?

**Overview of the Feature Request**

**What kind of user is the feature intended for?**
(Example users roles: API User, Curator, Depositor, Guest, Superuser, Sysadmin)

**What inspired the request?**

**What existing behavior do you want changed?**

**Any brand new behavior do you want to add to Dataverse?**

**Any open or closed issues related to this feature request?**

**Comment by qqmyers** [comment]
skosterm is a field in the example metadata block at https://github.com/gdcc/dataverse-external-vocab-support/blob/main/examples/metadatablocks/cvocdemo.tsv. 

To use Skos for any single/primitive field in another metadata block should only require creating a new configuration file where the field name has been changed, i.e. replacing skosterm at https://github.com/gdcc/dataverse-external-vocab-support/blob/6055e9a461de3646bf2256083f35d46964f26dbd/examples/config/cvoc-conf.json#L85-L86.

The keyword field is slightly different from the compound demo example in the repository as there are only 3 subfields instead of 4 (keywordValue, keywordVocabulary, keywordVocabularyURI but no separate keywordURI child field.) I've made a quick example at https://github.com/gdcc/dataverse-external-vocab-support/pull/17 for the keyword field. (It uses the UNESCO Thesaurus rather than AGROVAC, but you should be able to swap to use AGROVAC by swapping that in from https://github.com/gdcc/dataverse-external-vocab-support/blob/6055e9a461de3646bf2256083f35d46964f26dbd/examples/config/cvoc-conf.json#L98-L101.

I've only tested this on the develop/5.14 branch but I think it should work on earlier versions as well.

**Comment by ReisQuarteu** [comment]
The URL 'https://skosmos.dev.finto.fi/rest/v1/search?unique=true&vocab=agrovoc&parent=&lang=en&&query=agr*'  does not work. This is the url used in cvoc-conf.json.  Any suggestion to fix this?

**Comment by pdurbin** [comment]
Hmm, is it the hostname? What about https://demo.skosmos.org/rest/v1/search?unique=true&vocab=agrovoc&parent=&lang=en&&query=agr ?

**Comment by pdurbin** [comment]
It looks like @qqmyers opened an issue for this:

- https://github.com/gdcc/dataverse-external-vocab-support/issues/15

**Comment by ReisQuarteu** [comment]
Thank you for your precious help. I replaced "skosmos.dev.finto.fi" by "demo.skosmos.org" globally in the relevant examples/config/* files for the Skosmos examples to work. But the demo has another problem: when someone writes in 'ardcVocabulary' datafield nothing happens (the datafield 'ardcVocabularyURI' is not changed)

**Comment by pdurbin** [comment]
@ReisQuarteu gotcha. Can you please open an issue about this at https://github.com/gdcc/dataverse-external-vocab-support/issues ? I think that's the right place. 😅
