### ISSUE TITLE
Need ability to edit variable metadata 

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#961]
Be able to edit the variable label and type, and to tag columns.

Need to consider how this affects the download the format that is the original file.

type:
numeric
boolean
string
date

tags:
weights
time
continuous
count
ordinal
unique identifier
nominal / categorical
space
-   lat / long
-   FIPS
-   census

**Comment by pdurbin** [comment]
It's not entirely clear to me what this issue is about but `label` and `type` both exist in the `datavariable` table ( http://phoenix.dataverse.org/schemaspy/latest/tables/datavariable.html ) so I assume that's what it's about. A user story would help. Even better would be knowing who is asking for this feature so we can let them know if or when we implement it. :smile:

**Comment by pdurbin** [comment]
Hmm, editing variable labels and types is mentioned (among many other things) in #962 (and opened on the same day).

**Comment by pdurbin** [comment]
@scolapasta is this a duplicate of #962?

**Comment by pdurbin** [comment]
We should probably close this issue in favor of #4448
