### ISSUE TITLE
Swagger Dataverse API issue: openapi file

### ISSUE THREAD

**Issue by sirineREKIK** [IQSS/dataverse#9612]
Hello,

We found that the openapi file is not valid.
We fixed the yaml file hoping it would work, but still not. You can find the corrected yaml file attached:
[openapi_fixed.yml.zip](https://github.com/IQSS/dataverse/files/11553152/openapi_fixed.yml.zip)

you can also use these 2 tools to test the validity of the file : https://redocly.com/redocly-cli/   or   https://github.com/IBM/openapi-validator

By doing analysis we estimate that the problem comes from the yaml descriptor:
we suspect an infinite loop at the component level, because there are LOTS of them, and when trying to display the structure of a response from an endpoint it crashes.

**Comment by DS-INRA** [comment]
Would this be solved by
- #10328
?

**Comment by pdurbin** [comment]
Probably. @DS-INRA and @sirineREKIK you're welcome to jump into the ongoing discussion at https://dataverse.zulipchat.com/#narrow/stream/379673-dev/topic/.2Fopenapi.20broken.20in.206.2E0

**Comment by pdurbin** [comment]
[In Zulip](https://dataverse.zulipchat.com/#narrow/stream/379673-dev/topic/.2Fopenapi.20broken.20in.206.2E0/near/444734425) @luddaniel said we can go ahead and close this.

As discussed there this issue was opened by a former colleague of his. @luddaniel or others will open smaller issues that we can hopefully fit into a sprint so that we can make progress getting the error count down over time.
