### ISSUE TITLE
Metadata Customization : url fieldType validator

### ISSUE THREAD

**Issue by luddaniel** [IQSS/dataverse#9739]
Hello there,
We are facing an issue regarding [url](https://guides.dataverse.org/en/5.13/admin/metadatacustomization.html?highlight=url#datasetfield-field-properties) `fieldType` validation while using uncommon url.
Here is such url : https://archive.softwareheritage.org/swh:1:dir:561bfe6698ca9e58b552b4eb4e56132cac41c6f9;origin=https://github.com/gem-pasteur/macsyfinder;visit=swh:1:snp:1bde3cb370766b10132c4e004c7cb377979928d1;anchor=swh:1:rev:868637fce184865d8e0436338af66a2648e8f6e1 (generated by the website as a permalink)

Deeper analysis reveals that the [url validator](https://github.com/IQSS/dataverse/blob/0661c3a5c35f29e83db7799d802aa31300fb919d/src/main/java/edu/harvard/iq/dataverse/validation/URLValidator.java#L44-L47C1) is based on `org.apache.commons.validator.routines.UrlValidator` and will fail on validation due to the `//` near `6f9;origin=https://githu`.

UrlValidator as capability to be customized with options such as [ALLOW_2_SLASHES](https://commons.apache.org/proper/commons-validator/apidocs/org/apache/commons/validator/routines/UrlValidator.html#ALLOW_2_SLASHES) that _Allow two slashes in the path component of the URL_ : 

```java
UrlValidator urlValidator = new UrlValidator(schemes, UrlValidator.ALLOW_2_SLASHES);
```

The question now is : is it reasonable to add this option "for everyone and every url fields" ?
What do you think ?

Depending on the answer a PR could be considered.

**Comment by qqmyers** [comment]
FWIW: My understanding is that // is potentially an issue on the server the URL is for, e.g. for https://archive.softwareheritage.org in your example, rather than a potential problem for Dataverse (since Dataverse isn't trying to parse/interpret a URL in metadata). 
So I'd think that changing this would be OK. It allows users to add potentially unusable URLs as metadata (if the referenced server can't handle them), or potentially to create two URLs for the same item (i.e. adding // adds an empty path segment that could be ignored meaning the URL with/without the // point to the same thing) but that seems like a minor concern (as one can add URLs that return 404s, etc.) given the benefit for your use case.
Others may see an issue, but I'd say go ahead with a PR if you don't get further comments.

**Comment by pdurbin** [comment]
I mean, the URL you mentioned definitely works when I click it: https://archive.softwareheritage.org/swh:1:dir:561bfe6698ca9e58b552b4eb4e56132cac41c6f9;origin=https://github.com/gem-pasteur/macsyfinder;visit=swh:1:snp:1bde3cb370766b10132c4e004c7cb377979928d1;anchor=swh:1:rev:868637fce184865d8e0436338af66a2648e8f6e1

So, yes, I think we should allow two slashes in URLs. And @qqmyers seems to think so too. @luddaniel please feel free to make a pull request!
