### ISSUE TITLE
Performance: Slow response for the versions API call with large number of files or versions

### ISSUE THREAD

**Issue by tainguyenbui** [IQSS/dataverse#9763]
Hi Dataverse Team,

I just wanted to share with you something that affects datasets with high number of versions or files. 

 There have been some previously related issues that were already solved/closed. However, I strongly believe that the problem may still happen. I will backup the issue with some interesting data.

The below problem is happening when retrieving `dataset versions information` through the native API, hitting the endpoint: `http://demo.dataverse.org/api/datasets/<dataset-version>/versions`

**Given** that I am a user with large many files and versions in a dataset
**When** I retrieve all the dataset versions
**Then** I would like to receive a fairly "fast" response
**So** the user experience is smooth

# Current behavior
When the dataset has a large number of files, and also a large number of versions, the response time increments dramatically. This can be seen in the below table

| dataset id  | # of versions  | # of files | response size (MB) | response time  | # lines in response  |
|:---:|:---:|:---:|:---:|:---:|:---:|
| 767863 | 4 | 1349 | 2.92 | 11.42s | 120k |
| 396086 | 82 | 36 | 1.66 | 10.83s | 80k |
| 774618 | 14 | 69 | 0.51 | 3.57s | 23k |
| 770972 | 2 | 60 | 0.08 | 1.14s | 3.3k |

One of our concerns here is the fact that the dataset with id `767863` already takes a long time only having 4 versions, which means that once it reaches for instance 10 versions, it may be easily taking more than 20 seconds to respond, and could potentially cause a timeout in Dataverse.

Additionally, Dataverse currently returns as part of the response to all the files and their metadata for each of the versions available. That causes a very large response payload that may be unnecessary.

**Note:** The number of files also seem to affect the speed at which a version is published

# Expected behavior
To have the ability to retrieve **dataset versions information** in an efficient way that does not impact massively the response time.

# Possible solution
- To return basic metadata about each of the dataset versions available without file information that could potentially be the real problem.

- To review whether there are possible parallelization improvements

It is likely that the user will not necessarily need all the information for each of the datasets, normally, they would click on the version they are interested in, where we could actually perform another request such as `http://demo.dataverse.org/api/datasets/<dataset-id>/versions/<version>`

Thanks a lot!

**Comment by landreev** [comment]
@GPortas I just want to confirm quickly that you are ok with what I'm doing in this branch wrt the `datasets/.../versions` api: 
- Dropping the files listing from the (default) output of both the `/api/datasets/{id}/versions` and `/api/datasets/{id}/versions/{vid}`.
- Adding the optional `includeFiles=true` flag to the apis above, in case anyone needs backward compatibility. 
- Adding optional pagination to `/api/datasets/{id}/versions` via `offset=` and `limit=`. 

I'm very open to any input/if any changes are needed.

**Comment by GPortas** [comment]
@landreev 

Looks good to me! Just a couple of considerations:

- Making the includeFiles option true by default, even if it is not specified by query param. For backwards compatibility. I guess you've considered it but just in case. 

- Extend the documentation to warn of the performance issues that we can find if we do not use these new parameters.

- I would also reference the `/api/datasets/{id}/versions/{versionId}/files` endpoint (The one we are extending) in the documentation as the preferred option in case the user is working closer to the files and looking for more filtering and sorting options.

**Comment by landreev** [comment]
(btw, yes, I did mention the `.../files` api in the guide update, as the recommended endpoint for the files information)

**Comment by GPortas** [comment]
@landreev 

I like the idea of adding the total number of files, I think it can be useful in certain scenarios. 

In addition to the total number of files, for the SPA we also need the number of files by type, access and category, since this information is necessary for the SPA (See: https://github.com/IQSS/dataverse-frontend/blob/develop/src/files/domain/models/FilesCountInfo.ts). 

I thought of creating a specific "counting" endpoint for this, in order not to overload `/api/datasets/{id}/versions/{vid}`.

What do you think?

**Comment by landreev** [comment]
> I thought of creating a specific "counting" endpoint for this, in order not to overload `/api/datasets/{id}/versions/{vid}`.

Yes, that may deserve its own dedicated endpoint. Something like 
`/api/datasets/{id}/versions/{vid}/counts` maybe?

**Comment by GPortas** [comment]
@landreev Yes, or `/api/datasets/{id}/versions/{vid}/fileCounts`, to specify that the counts are for files.

**Comment by landreev** [comment]
Sorry, I did actually mean to include the `/files` part in there - like
`/api/datasets/{id}/versions/{vid}/files/counts`... but "fileCounts" works too of course.

**Comment by GPortas** [comment]
@landreev Sure. I like `/api/datasets/{id}/versions/{vid}/files/counts`. More structured in my opinion.

**Comment by GPortas** [comment]
@landreev I have created an issue por the file counts endpoint: https://github.com/IQSS/dataverse/issues/9834. Working on it.

**Comment by landreev** [comment]
To summarize, in this branch I'm addressing the performance issues in the versions api via a combination of the following approaches: 
- (optional) pagination is being added to `/api/datasets/{id}/versions`
- a new flag `includeFiles` is added to both `/api/datasets/{id}/versions` and `/api/datasets/{id}/versions/{vid}` (true by default), providing an option to drop the file information from the output
- when files are requested to be included, the filemetadatas are looked up using the "left joint fetch" optimizations that retrieve the information from the extended table tree in a single query, instead of allowing EJB to perform 1 SELECT query on each 1:1 relation for each FileMetadata entry. On a version with N filemetadatas this saves 3*N individual queries. This is not free resources-wise by any means (costs more memory primarily), but still appears to show measurable improvement on datasets with large numbers of versions and/or files. 

The following real life datasets from IQSS prod. service are used in the sample tests below: 

- 5255036: 237 versions (!), ~2,400 files. Files are relatively sparsely spread between versions. 
- 4554342: 2 versions, 1 pub. 1 draft. ~25,000 files (all appear in both versions).
- 2710927: a control "reasonable" dataset, 100 files, 3 published versions. 


`/api/datasets/{id}/versions`:

| dataset id  | # of versions  | # of files | response size | v5.14 response time | new response time | new size w/out files | new time w/out files |
|:---:|:---:|:---:|:---:|:---:|---:|---:|---:|
| 5255036 | 237 | 2400 | 38MB | 1m30s | 48s | 2MB | 12s | 
| 4554342 | 2 | 25000 | 17MB | 2m16s | 12s | 2.5K | 1s |
| 2710927 | 3 | 100 | .2MB | 1s | <1s | 26K | <1s |

`/api/datasets/{id}/versions/{vid}`:

| dataset id  | version  | # of files in version | response size | v5.14 response time | new response time | new size w/out files | new time w/out files |
|:---:|:---:|:---:|:---:|:---:|---:|---:|---:|
| 5255036 | 87.1 | 12 | 24K | 1s | <1s | 12K | <1s | 
| 4554342 | draft | 25000 | 17MB | 2m17s | 12s | 4K | <1s |
| 2710927 | 3.0 | 100 | 78K | 1s | <1s | 9K | <1s |

Note: `/api/datasets/4554342/versions` and `/api/datasets/4554342/versions/draft` produce the same amount of output because the former api was called without authentication, so only one, published version was included. 

Note: tests above were run on the dedicated IQSS test system (not in prod., which is a beefier and faster system). 

I will add more info, and will include this in the pr as well.

**Comment by landreev** [comment]
(to clarify, the results in the last update are with the extra "citation date" logic commented out from the code; I am working on addressing that)

**Comment by ErykKul** [comment]
I did something similar some time ago with the left-join hints in this PR: https://github.com/IQSS/dataverse/pull/9684
The issue I had opened https://github.com/IQSS/dataverse/issues/9683 looks redundant to this one, sorry that I had missed it.
