### ISSUE TITLE
 Google Cloud Storage library using deprecated javax package

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#9812]
If you run `mvn dependency:tree` you can see that `javax.annotation-api` is being pulled in but the namespace has changed to Jakarta: https://jakarta.ee/specifications/annotations/2.1/

```
[INFO] +- com.google.cloud:google-cloud-storage:jar:2.11.3:compile
[INFO] |  +- javax.annotation:javax.annotation-api:jar:1.3.2:compile

```

Once we release Dataverse 6 with Payara 6 and EE 10 it is unknown if any problems will surface with the export BagIt to Google Cloud feature: https://guides.dataverse.org/en/5.14/installation/config.html#google-cloud-configuration

**Comment by qqmyers** [comment]
FWIW: For this and the dependency in #9811 - it looks like these are compile-time dependencies (according to maven central) rather than run time.  Hopefully that means that if we're just using the libraries it won't be an issue. Can anyone confirm that in general?

**Comment by poikilotherm** [comment]
@qqmyers why would a compile time dependency not be used during runtime? Maven scope "runtime" just means you don't need a dependency when compiling. Scope "compile" on the other hand does not mean you don't need a dependency during runtime. https://www.baeldung.com/maven-dependency-scopes

**Comment by qqmyers** [comment]
I'll see if I can make them external - it's already dynamically loading and we have the exporters example code now.

**Comment by qqmyers** [comment]
I think [this](https://github.com/QualitativeDataRepository/dataverse/commit/8d6fcc4a03df578c3de0afbd1d60884aad29e7f6) may be about all that is needed to allow archivers to be loaded from external jars. It is bigger than a 6.0 task to redesign the archivers to only use interfaces so they can be built against an spi jar, but this may enough to allow them and their dependencies to be packaged as separate jars as a next step. Together these would allow that jar to be replaced if/when issues with the javax classes arise without having to create a new Dataverse release (even with the archiver still using DatasetVersion, etc. directly). (QDR will definitely want the Google archiver to work once we update to DV 6.0. It's not something I can do immediately though, so separating from the DV 6.0 release would be good.)

**Comment by qqmyers** [comment]
I cleaned this up and tested a bit and have hit a snag. While I can load the Archiver class externally, the ArchiverUtil class that loads it is currently in the main war and if the google jars are in the external dir instead of the war, there are failures of the Google Exception classes not being found. At present, I'm not sure how to handle that in a clean way and I think if we can't pull the google jars out and replace them, it's not going to be helpful w.r.t. 6.0. If anyone has ideas, let me know (or try things yourself), but if not, I'd suggest we switch to just warning people that these archivers may not work in 6.0. (FWIW: The changes I've made are [here](https://github.com/QualitativeDataRepository/dataverse/compare/develop...QualitativeDataRepository:dataverse:extarchivers).)
