### ISSUE TITLE
QA for Fundreg and ROR support

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse#9973]
**Overview of the QA Request**
- The following issue: [Fundreg and ROR support #14](https://github.com/gdcc/dataverse-external-vocab-support/pull/14) related to a GREI aim (see: https://github.com/IQSS/dataverse/issues/9151) was merged (at my request) and needs QA

**What existing behavior do you want investigated?**
- Please see [comment](https://github.com/IQSS/dataverse/issues/9151#issuecomment-1572710674): "perform some review/QA of the overall changes to Dataverse (https://github.com/IQSS/dataverse/issues/9150) with the new JavaScript (https://github.com/gdcc/dataverse-external-vocab-support/pull/14) w.r.t. the goals of the deliverable - could be done before or after https://github.com/gdcc/dataverse-external-vocab-support/pull/14 is merged"

**Comment by kcondon** [comment]
@qqmyers I could use some help configuring this on test/demo. What I've done so far:
1. Combined the individual field json files, grantNumberAgencyFundreg.json and rorAuthAffiliation.json into a consolidated json file, cvocconf-fundreq_ror.json and loaded them into the :CVocConf setting using the endpoint: curl -X PUT --upload-file cvocconf_fundreq_ror.json http://localhost:8080/api/admin/settings/:CVocConf , restarted
2. Downloaded the java script files, cvocutils.js  fundreg.js  ror.js and put them under docroot/cvocconf/js, making sure the payara user has access
3. Created a dataset, paying attention to the author affiliation field (ror?) and the funder fields. No evidence of controlled vocab and no errors in logs. 

What am I missing? I'm doing this on test/internal first, then will move to demo.


[cvocconf_fundreq_ror.json](https://github.com/IQSS/dataverse/files/12937947/cvocconf_fundreq_ror.json)

**Comment by kcondon** [comment]
Thanks @qqmyers and @landreev, I was able to configure this on test and demo. The main changes needed were:
1. create a cvoc_fundreg_ror.json that includes the json from the individual files into an array: 
[cvocconf_fundreq_ror.json](https://github.com/IQSS/dataverse/files/12968063/cvocconf_fundreq_ror.json)

2. Move the .js scripts from the gdcc repo to /var/www/http/cvoc/js and make the owner dataverse

3. Edit ssl.conf and add Rewrite rules to skip these files from being forwarded to payara, ie. serve from apache:
RewriteRule   ^/cvoc/js/cvocutils.js      /var/www/html/cvoc/js/cvocutils.js
RewriteRule   ^/cvoc/js/fundreg.js      /var/www/html/cvoc/js/fundreg.js
RewriteRule   ^/cvoc/js/ror.js      /var/www/html/cvoc/js/ror.js

Status of this issue is resolved:
1. deployed to demo, 2. can set author affiliation (ror) and grantfunding/funder fields using controlled vocab. 3. The last item in 9402 said all major issues resolved and needs UX post spa 4. Will communicate demo availability to dvn-core shortly 5. The path it took was winding but I think it is mostly delivered but needing UX at a later date. I think there is some useful info in the issues found as in what to look out for, later.
